.github/workflows/bundle-stats.yaml
.github/workflows/check-js.yaml
.github/workflows/check-rs.yaml
.github/workflows/release.yml
.github/workflows/test.yml

chore: migrate CI to public runner

---

.changeset/slow-trains-melt.md
crates/rspack_error/src/catch_unwind.rs
crates/rspack_error/src/lib.rs

Panics are not supposed to happen on the user-side. 
But when it occurs, we should provide more clear message to guide user to report the fatal error back to us.

feat: support guided panic info with backtrace

---

packages/rspack/src/compiler.ts
packages/rspack/src/watching.ts

1. remove unnecessary `ts-expect-error`

chore: 🤖 remove unnecessary ts-expect-error

---

.changeset/good-frogs-kneel.md
packages/rspack-cli/src/rspack-cli.ts
packages/rspack/src/config/schema.js
packages/rspack/src/rspack.ts

For more smoother migration from webpack
```sh
rspack serve # same as strict, strict is default strategy and encouraged
RSPACK_CONFIG_VALIDATE=strict rspack serve # throw error and tell where is invalidate
RSPACK_CONFIG_VALIDATE=loose rspack serve # report invalidate config but not throw error
RSPACK_CONFIG_VALIDATE=loose-silent rspack serve # not report and not throw error
```

feat: config validate strategy

---

.changeset/famous-queens-breathe.md
packages/rspack/src/config/adapter-rule-use.ts

feat: loader api add dependency

---

package.json
packages/rspack-cli/package.json
packages/rspack/package.json
pnpm-lock.yaml

There have many duplicated packages to install. Such as 3 `typescript` and 2 `yargs`.
- Manual change dev dependency `typescript` version to `^4.7.4`, To keep same in `@rspack/dev-server`
- Manual change dependency `yargs` version to `17.6.2`
- Deduplicate packages by running `pnpm dedupe`
- Reduce the size of `node_modules` from `659M` to `573M`
None.

chore: dedupe packages to reduce the size of node_modules

---

crates/rspack_plugin_javascript/src/visitors/tree_shaking.rs

Making code more concise and readable, while also making it more functional.
use `unwrap_or_else` to replace `if let`

refactor: use `unwrap_or_else`

---

.github/workflows/bench-history.yaml

The Ci is failed because of the 30min timeout.
1. We don't need 30 min timeout, because we using public CI now.

chore: 🤖 remove benchmark history timeout limit

---

.github/workflows/check-rs.yaml

I was wrong about the env variable :-(

ci: fix clippy warnings not being raised as errors

---

.github/workflows/check-rs.yaml
.github/workflows/test.yml

We are now using GitHub CI instead of self hosted machines which doesn't have caches.

ci: add cache to rust build steps

---

.github/workflows/bench.yaml

1. Because the public ci resource is too slow, then can't  finish Benchmark in 30 minutes, so we need to remove this timeout
you can refer to https://github.com/web-infra-dev/rspack/actions/runs/4401579159

chore: 🤖 remove benchmark timeout

---

.changeset/twenty-months-sleep.md
Cargo.lock
crates/loader_runner/Cargo.toml
crates/node_binding/Cargo.lock
crates/rspack_core/Cargo.toml

close: #2180
more info: https://github.com/web-infra-dev/rspack-sources/pull/54
perhaps it would be better to wait for the `rspack-source` release before merging in.

pref(source): use use once cell for source map line chunk during substring

---

.changeset/nasty-taxis-protect.md
crates/node_binding/binding.d.ts
crates/rspack_binding_options/src/options/mod.rs
crates/rspack_binding_options/src/options/raw_external.rs
crates/rspack_core/src/options/compiler_options.rs
crates/rspack_core/src/options/externals.rs
crates/rspack_loader_sass/tests/fixtures.rs
crates/rspack_plugin_externals/src/plugin.rs
crates/rspack_testing/src/test_config.rs
packages/rspack/src/config/adapter.ts
packages/rspack/src/config/schema.js
packages/rspack/src/config/types.ts
packages/rspack/src/rspack.ts

```js
externals: ['vue', 'react']
```
fix part of #2149, when target is `"node"` externals will be modified by `NodeTargetPlugin`, we need implement `externalsPresets` first to completely fix it.
Didn't add tests because tests needs `target: "node"`...

feat: array type for externals

---

.changeset/smart-starfishes-perform.md
packages/rspack-plugin-html/src/template.ts
packages/rspack-plugin-html/tests/basic.spec.js
packages/rspack-plugin-html/tests/fixtures/issue2179.html

Webpack leverages child-compiler to deal with template compilation. 
So with builtin define functionalities, `process` can be replaced correctly. 
I used a workaround in this PR to achieve almost the same capability.
closes https://github.com/web-infra-dev/rspack/issues/2179

fix(plugin-html): fix template with process

---

.changeset/young-paws-join.md
packages/rspack-cli/package.json
packages/rspack-cli/tests/build/typescript/rspack.config.ts
packages/rspack-cli/tests/build/typescript/typescript.test.ts

Mark ts-node as optional peer dep to avoid package manager complaints.
Fix style to pass the lint test by the way.

fix(cli): make ts-node as an optional peer dependency

---

.github/workflows/check-rs.yaml
x

1. Try to fix random test fail and retry success
here is the time cost  between test-threads=1, and test-threads=${defualt-value}
2. Notice that our rspack is still running in multi-thread, this change only makes the testing tasks run in single thread.

fix: try rs test run in single thread

---

crates/rspack_testing/src/eval_raw.rs

Resolved a serious issue with cargo test fixtures controlled by  `test.config.js` config file was not able to retrieve correctly context information during execution, leading to test failures. 
This optimization improves the contributor maintenance experience.

fix(testing): resolve context for fixtures controlled by `test.config.js` 

---

.changeset/olive-spoons-kick.md
crates/rspack_core/src/runtime_module.rs
crates/rspack_plugin_javascript/src/runtime.rs
crates/rspack_plugin_runtime/src/runtime_module/get_chunk_filename.rs
crates/rspack_plugin_runtime/src/runtime_module/get_full_hash.rs
packages/rspack/tests/cases/module-variables/webpack-hash/index.js

- fix: runtime module cacheable
#2177

fix: runtime module cacheable

---

.changeset/eleven-falcons-approve.md
packages/rspack-dev-middleware/src/middleware.ts

Currently there are two issues I'm facing with dev-middleware:
1. it uses `express`-only handlers like `req.path` and `res.send()`
2. it does not respect a public path (I may be misunderstanding how this is meant to be used though - should this only be registered to handle paths beginning with the publicPath?
This PR uses node-compatible methods (`req.url` and `res.end()`) which will also work in express, expanding the compatibility of this library. It also normalises any URLs beginning with `publicPath` so they can be handled in this middleware.
(I am happy to remove the change to publicPath handling if this is intended.)

fix(dev-middleware): compatibility with native node handler

---

.github/workflows/bench.yaml
.github/workflows/check-rs.yaml

1. do not cancel when there is no `pull_request.number` , using a unique_id `run_id` instead.

chore: 🤖 do not cancel task in main branch

---

crates/rspack_core/src/module_graph/connection.rs
crates/rspack_core/src/module_graph/mod.rs

There are two bottlenecks around `ModuleIdentifer`:
* it is a long path, which takes a lot of time to compute the hash
* it is a `Ustr`, accessing the contents of the `Ustr` is a roundtrip to the heap, which is slow
When we use `ModuleIdentifier` as the key for `HashMap`s, the profiler shows performance hot spots in hot paths.
This PR removes the need to read `ModuleIdentifier` in hot paths, and uses a vector as the backing storage. `ConnectionId` and `Dependency` Id are the indexes to their respective vectors.
For a large project with 20k modules, code splitting time is now reduced from 7s to 6s.
As a bonus, the `AtomicUsize`s are now gone :-)

refactor module graph lookups

---

.changeset/ninety-terms-build.md
packages/rspack-cli/src/index.ts
packages/rspack-cli/src/rspack-cli.ts

1. Add `defineConfig`  
Resolved #2263

feat: 🤖 finish defineConfig

---

.github/workflows/check-rs.yaml

CI cache on check-rs is taking about 1G, I think it's due to double caching here.

fix(ci): clean up check-rs, attempt to fix ci cache taking 1G

---

.github/workflows/check-rs.yaml

ci: combine lint, format and test to save ci time and cache

---

.changeset/loud-pianos-smash.md
crates/rspack_core/src/ast/javascript.rs
crates/rspack_core/src/cache/occasion/build_module.rs
crates/rspack_core/src/compiler/compilation.rs
crates/rspack_core/src/compiler/queue.rs
crates/rspack_core/src/context_module.rs
crates/rspack_core/src/module.rs
crates/rspack_core/src/module_graph/mod.rs
crates/rspack_core/src/normal_module.rs
crates/rspack_core/src/parser_and_generator.rs
crates/rspack_core/src/raw_module.rs
crates/rspack_plugin_javascript/src/plugin.rs
crates/rspack_plugin_javascript/src/runtime.rs
crates/rspack_plugin_javascript/src/visitors/mod.rs
crates/rspack_plugin_javascript/src/visitors/strict.rs
crates/rspack_plugin_runtime/src/lazy_compilation.rs
packages/rspack/src/config/defaults.ts
packages/rspack/tests/Defaults.unittest.ts
packages/rspack/tests/cases/interop/node-mode/index.js
packages/rspack/tests/cases/interop/node-mode/lib.mjs
packages/rspack/tests/cases/interop/node-mode/value.js

- fix: node mode interop
fixes #2190 
related https://github.com/nodejs/node/issues/40891

fix: mjs file node mode interop

---

README.md

Initially the NPM badge was redirecting to https://www.npmjs.com/package/@rspack/core?activeTab=versions
With this change it will now redirect to the main NPM page https://www.npmjs.com/package/@rspack/core?activeTab=readme
- [ X] Docs change / Dependency upgrade

Small fix to improve the readme file 

---

.changeset/happy-berries-wonder.md
packages/rspack-cli/src/rspack-cli.ts

none of react cli prints stats.modules info expect webpack-cli, which is not friendly to developer since it will flush server info out of screen

fix(cli): set stats default to errors-warning to avoid server info flushhed by module stats

---

.github/workflows/team-label.yaml

The team-label action is currently failing on writing to issues, this adds the permission to do so.

ci: add write permission to team-label

---

Cargo.lock
Cargo.toml
crates/loader_runner/Cargo.toml
crates/loader_runner/src/runner.rs
crates/loader_runner/tests/load_runner.rs
crates/node_binding/Cargo.lock
crates/rspack_core/Cargo.toml
crates/rspack_core/src/cache/occasion/resolve_module.rs
crates/rspack_core/src/compiler/resolver.rs
crates/rspack_core/src/context_module_factory.rs
crates/rspack_core/src/normal_module_factory.rs
crates/rspack_core/src/tree_shaking/optimizer.rs
crates/rspack_core/src/tree_shaking/test.rs
crates/rspack_core/src/tree_shaking/visitor.rs
crates/rspack_core/src/utils/hooks.rs
crates/rspack_loader_sass/src/lib.rs
crates/rspack_loader_sass/tests/fixtures.rs

This PR brings the following changes:
1. more friendly error tips when tsconfig not founded.
2. expose description data(package.json) to resourceData. close https://github.com/web-infra-dev/rspack/issues/2298

feat: expose description data to resolve_data

---

.changeset/breezy-parents-reflect.md
.changeset/strange-shirts-impress.md
packages/rspack-dev-middleware/package.json
packages/rspack-dev-server/package.json
packages/rspack/package.json
pnpm-lock.yaml

remove the peerDep Warning of webpack-dev-server & webpack-dev-middleware and  fixes #2318

chore: upgrade webpack-dev-server & webpack-dev-middleware

---

.vscode/settings.json
crates/rspack_core/src/ast/javascript.rs
crates/rspack_core/src/tree_shaking/optimizer.rs
crates/rspack_core/src/tree_shaking/visitor.rs
crates/rspack_plugin_javascript/src/ast/parse.rs
crates/rspack_plugin_javascript/src/plugin.rs

1. prerequisite for some features like `pure annotation` in tree shaking , custom chunk name in bundle splitting
1. https://github.com/web-infra-dev/rspack/issues/2335
2. https://github.com/web-infra-dev/rspack/issues/2335

feat: parse with comments

---

.changeset/clever-pianos-help.md
crates/rspack_binding_options/src/options/raw_external.rs
packages/rspack/tests/configCases/externals/array-externals/index.js
packages/rspack/tests/configCases/externals/array-externals/inject.js
packages/rspack/tests/configCases/externals/array-externals/webpack.config.js

fix(core): fix regex external not working

---

packages/rspack/src/config/adapter-rule-use.ts

Removed several ts-expect-error with proper typing
None

fix: remove several ts-expect-error

---

.changeset/beige-moose-destroy.md
packages/rspack/src/compiler.ts

- optimize the initialization of instance
Now, even if the `instance` is not `undefined`, it will still execute `options`.
Let `options` behind of `??` will improve performance.

chore: optimize the initialization of instance

---

packages/rspack/src/multiCompiler.ts
packages/rspack/src/watching.ts

chore: fix some ts types

---

Cargo.lock
Cargo.toml
crates/node_binding/Cargo.lock
crates/rspack/Cargo.toml
crates/rspack_core/Cargo.toml
crates/rspack_loader_sass/Cargo.toml
crates/rspack_loader_sass/src/lib.rs
crates/rspack_plugin_javascript/Cargo.toml
crates/rspack_plugin_javascript/src/ast/minify.rs
crates/rspack_plugin_javascript/src/plugin.rs

This removes a large dependency which should improve our build speed a bit.
Note: mpsc::channel is now a port of crossbeam, they have no difference.
See: `https://github.com/rust-lang/rust/pull/93563`

refactor(rust): remove unnecessary usage of crossbeam

---

crates/rspack_binding_macros/Cargo.toml
crates/rspack_binding_options/Cargo.toml
crates/rspack_napi_shared/Cargo.toml

This removes the following cargo warnings
```
warning: rspack/crates/rspack_binding_options/Cargo.toml: unused manifest key: dependencies.napi-derive.version
warning: rspack/crates/rspack_napi_shared/Cargo.toml: `default-features` is ignored for napi, since `default-features` was not specified for `workspace.dependencies.napi`, this could become a hard error in the future
warning: rspack/crates/rspack_binding_macros/Cargo.toml: `default-features` is ignored for napi, since `default-features` was not specified for `workspace.dependencies.napi`, this could become a hard error in the future
```

chore(rust): remove cargo warnings around napi

---

.changeset/silver-phones-learn.md
crates/node_binding/binding.d.ts
crates/node_binding/src/hook.rs
crates/node_binding/src/js_values/hooks.rs
crates/node_binding/src/plugins/mod.rs
crates/rspack_core/src/compiler/compilation.rs
crates/rspack_core/src/compiler/mod.rs
crates/rspack_core/src/plugin/api.rs
crates/rspack_core/src/plugin/plugin_driver.rs
packages/rspack/src/compilation.ts
packages/rspack/src/compiler.ts

feat: add finishModules hook

---

.github/workflows/team-label.yaml

The team-label action is currently running on every action type, this reduces it by only running on `opend`. See https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#issues

ci: check team-label only on pr and issue open

---

.github/workflows/check-changeset.yml

pnpm cache is not being used, let's see if this fixes that

ci: use pnpm/action-setup in check-changeset

---

crates/rspack_plugin_remove_empty_chunks/src/lib.rs

- A initial chunk may contain zero modules due to splitChunks
- We should not remove the empty initial chunks because that rspack will inject some bootstrap code in it.

fix: should not remove empty initial chunk

---

.changeset/honest-rabbits-lie.md
crates/rspack_plugin_javascript/src/visitors/dependency/scanner.rs
packages/rspack/tests/cases/module-variables/webpack-public-path/index.js

feat(runtime): support set __webpack_public_path__ runtime

---

.changeset/brave-pillows-tan.md
crates/rspack_plugin_javascript/src/visitors/mod.rs
packages/rspack/tests/configCases/target/mix-cjs-esm/webpack.config.js

https://github.com/web-infra-dev/rspack/issues/2501

fix: cjs transfrom preset env

---

crates/rspack_plugin_runtime/src/runtime_module/runtime/css_loading_with_hmr.js
packages/rspack-dev-middleware/src/middleware.ts

js hmr is broken due to css hmr crash which cause js hmr logic is not executed

fix: fix hmr not working

---

.changeset/wet-spies-fold.md
crates/node_binding/binding.d.ts
crates/rspack_binding_options/src/options/raw_builtins/mod.rs
crates/rspack_core/src/options/builtins.rs
crates/rspack_plugin_javascript/src/visitors/mod.rs
crates/rspack_plugin_javascript/src/visitors/swc_visitor/mod.rs
crates/rspack_plugin_javascript/src/visitors/swc_visitor/provide.rs
crates/rspack_testing/src/test_config.rs
packages/rspack/src/config/builtins.ts
packages/rspack/tests/Defaults.unittest.ts
packages/rspack/tests/configCases/builtins/provide/a.js
packages/rspack/tests/configCases/builtins/provide/aaa.js
packages/rspack/tests/configCases/builtins/provide/b.js
packages/rspack/tests/configCases/builtins/provide/bbbccc.js
packages/rspack/tests/configCases/builtins/provide/ddd.js
packages/rspack/tests/configCases/builtins/provide/env.js
packages/rspack/tests/configCases/builtins/provide/esm.js
packages/rspack/tests/configCases/builtins/provide/foo.mjs
packages/rspack/tests/configCases/builtins/provide/harmony.js
packages/rspack/tests/configCases/builtins/provide/harmony2.js
packages/rspack/tests/configCases/builtins/provide/index.js
packages/rspack/tests/configCases/builtins/provide/webpack.config.js

Support the `ProvidePlugin` as a `provide` builtin in rspack
#1358

feat: built-in support for ProvidePlugin

---

crates/rspack_core/src/tree_shaking/visitor.rs
crates/rspack_error/src/lib.rs

remove unnecessary std::mem::take

chore: remove unnecessary std::mem::take

---

crates/node_binding/Cargo.toml

closes #2081
Dashmap is already synced to v5.4.0, this bumps the version in Cargo.tom and closes #2081
https://github.com/web-infra-dev/rspack/blob/9d02abc78d14215e7b747fdc09c944d7a970f9a2/crates/node_binding/Cargo.lock#L466-L477

deps(node_binding): dashmap v5.4.0

---

.editorconfig
.gitattributes

Motivation: To make .x file work under Linux.
What is changed: The files will be created with "LF" for any new clone, existing files will not be changed. About the details, please reference this great article about CRLF and LF: https://www.aleksandrhovhannisyan.com/blog/crlf-vs-lf-normalizing-line-endings-in-git/
Have to say I am kind of confused, the CONTRIBUTING.md seems to be prepared for Linux, but ".x" is using CRLF as line endings, which make it complains "env: node\r: No such file". Note the strange "\r", which is the problem.
We cloud also add such content to .editorconfig to express intension better, I do not add it for now:
``` .editorconfig
[*]
end_of_line = lf
```
This should not cause any problem in Windows, there is no "bat" or "cmd" file in the repo.
Not sure, I guess it's …

chore: unify line endings for all files for any new clone

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json

Add an easy way to prepare environment for VSCode. 
- This environment contains rust 1.68, node 16.18.0, and pnpm. 
- The VSCode devcontainer includes "rust-analyzer" extension.
- When attaching to the devcontainer, "pnpm run init" command will be ran automatically.
For details, please reference https://code.visualstudio.com/docs/devcontainers/containers
Maybe improvement?

chore: add devcontainer files

---

.changeset/tame-seals-pull.md
crates/rspack_plugin_dev_friendly_split_chunks/src/plugin.rs

The FS project emits a 30MB js asset due to the number `MAX_MODULES_PER_CHUNK`.
This PR reduced the number of `MAX_MODULES_PER_CHUNK` and add a `MAX_SIZE_PER_CHUNK` condition to split chunks that are bigger than `MAX_SIZE_PER_CHUNK`.
Fixes #2529.

feat(rspack_plugin_dev_friendly_split_chunks): reduce `MAX_MODULES_PER_CHUNK` and add `MAX_SIZE_PER_CHUNK` condition

---

.github/workflows/release.yml

1. for more details you could refer https://github.com/web-infra-dev/rspack/issues/2583
1. Part of https://github.com/web-infra-dev/rspack/issues/2583

ci: release pre check

---

Cargo.lock
Cargo.toml
crates/node_binding/Cargo.lock
crates/node_binding/binding.d.ts
crates/rspack_binding_options/src/options/raw_resolve.rs
crates/rspack_core/src/options/resolve.rs
packages/rspack/src/config/types.ts

This PR upgrade the version of `nodejs_resolver`, it brings following change:
1. Optimized handling of `extendsions`, which reduces content usage and optimizes execution speed.  relative: https://github.com/web-infra-dev/nodejs_resolver/issues/157
2. Fixed the paths map match in tsconfig.
- some test: https://github.com/web-infra-dev/nodejs_resolver/pull/172/files#diff-9bfc51173c154df5ab54a96fc510a2c449c578905e2b9be080b19450792d5236R193
4. fix some string slice in utf8. 
- test case: https://github.com/web-infra-dev/nodejs_resolver/commit/dc99710c2612f01f1ecbf99edfb1b164c6e8e19e#diff-24975acf43b4bc39c4c8b57246e4bfbdc0c76428c86ed68f1db0e1b10a6db277R1093-R1101
- close https://github.com/web-infra-dev/rspack/issues/2546
5. support `resolve.fullySpecified`, close …

fix: bump nodejs-resolver to fix path issue with chinese characaters

---

package.json
packages/create-rspack/package.json
packages/playground/package.json
packages/postcss-loader/package.json
packages/rspack-cli/package.json
packages/rspack-dev-client/package.json
packages/rspack-dev-middleware/package.json
packages/rspack-dev-server/package.json
packages/rspack-plugin-html/package.json
packages/rspack-plugin-minify/package.json
packages/rspack-plugin-node-polyfill/package.json
packages/rspack/package.json

From https://docs.npmjs.com/cli/v9/configuring-npm/package-json#repository:
> If the package.json for your package is not in the root directory (for example if it is part of a monorepo), you can specify the directory in which it lives:
---
1. It allows a more accurate direct link to the source code from www.npmjs.com/package
1. When `rspack` is installed in your project's `node_modules`, if you encounter an error with a stack trace, it makes it easy for the IDE/Terminal to open the Github source code directly by examining the closest `package.json` file.
Nil.

chore: Update all package.json#repository fields to include the monorepo-relative directory

---

.changeset/four-vans-decide.md
packages/rspack/src/multiCompiler.ts
packages/rspack/src/watching.ts
packages/rspack/tests/MultiCompiler.test.ts

Watching should be still #initial until invalidate happens, as multiCompiler may block the watching first run
closes #2585

fix: initial watching should stale until invalidate happens

---

.changeset/chilly-colts-yawn.md
Cargo.lock
crates/node_binding/Cargo.lock
crates/node_binding/binding.d.ts
crates/rspack_binding_options/Cargo.toml
crates/rspack_binding_options/src/options/mod.rs
crates/rspack_core/src/cache/local/code_splitting_cache.rs
crates/rspack_core/src/compiler/compilation.rs
crates/rspack_core/src/options/entry.rs
crates/rspack_loader_sass/Cargo.toml
crates/rspack_loader_sass/tests/fixtures.rs
packages/rspack/src/config/adapter.ts
packages/rspack/tests/case.template.ts
packages/rspack/tests/configCases/builtins/html-entry-order/index.html
packages/rspack/tests/configCases/builtins/html-entry-order/index.js
packages/rspack/tests/configCases/builtins/html-entry-order/polyfill.js
packages/rspack/tests/configCases/builtins/html-entry-order/webpack.config.js

fix: 🐛 Module Export Entry does not respect ordering

---

packages/rspack/src/watching.ts

fix #2654, we should store last startTime before resetting
#2654

fix: fix compile time is NaN in watch

---

crates/rspack_plugin_dev_friendly_split_chunks/src/plugin.rs

Generally, this PR does the following things:
1. Try to create chunks. Each chunk contains 2000 shared modules.
2. If the created chunk is bigger than 3MB, split the chunk into a small ones.
With this PR, every js asset of the FS project is smaller than 3.6MB.

feat: split chunks more delicately for `devFriendlySplitChunks: true`

---

.github/ISSUE_TEMPLATE/1-bug-report.en-US.yml
.github/ISSUE_TEMPLATE/2-feature-request.en-US.yml

Using GitHub action to add labels cause some latency.

chore: add "pending triage" to new issue by default

---

crates/rspack_core/src/tree_shaking/optimizer.rs

Pure refactoring. I also added some comments and used meaning variable name to improve readability.
N/A

chore: several style change for more concise code 

---

.changeset/curvy-weeks-burn.md
packages/rspack-cli/src/utils/loadConfig.ts

since we support mjs as config file now, we should support `rspack.config.mjs` as default config file

feat(cli): support mjs&cjs as default config file

---

crates/rspack_core/src/ast/javascript.rs
crates/rspack_core/src/build_chunk_graph/code_splitter.rs
crates/rspack_core/src/dependency/dynamic_import.rs
crates/rspack_core/src/dependency/mod.rs
crates/rspack_core/src/normal_module.rs
crates/rspack_plugin_javascript/src/dependency/esm/mod.rs
crates/rspack_plugin_javascript/src/lib.rs
crates/rspack_plugin_javascript/src/visitors/dependency/mod.rs
crates/rspack_plugin_javascript/src/visitors/dependency/scanner.rs
crates/rspack_plugin_runtime/src/runtime_module/load_chunk_with_module.rs
package.json
packages/rspack/tests/cases/parsing/issue-6867/a.js
packages/rspack/tests/cases/parsing/issue-6867/b.js
packages/rspack/tests/cases/parsing/issue-6867/c.js
packages/rspack/tests/cases/parsing/issue-6867/d.js
packages/rspack/tests/cases/parsing/issue-6867/e.js
packages/rspack/tests/cases/parsing/issue-6867/f.js
packages/rspack/tests/cases/parsing/issue-6867/g.js
packages/rspack/tests/cases/parsing/issue-6867/h.js
packages/rspack/tests/cases/parsing/issue-6867/index.js
packages/rspack/tests/copyPlugin/build/_t3/dest1/tempfile1.txt
packages/rspack/tests/copyPlugin/fixtures/watch/_t3/directory/tempfile1.txt
packages/rspack/tests/copyPlugin/fixtures/watch/_t3/directory/tempfile2.txt
pnpm-lock.yaml

- If you want review the regex, click this [link](https://jex.im/regulex/#!flags=&re=webpackChunkName%5Cs*%3A%5Cs*%5B%22%7C'%7C%60%5D%5Cs*(%5Cw%5B%5Cw0-9%5D*)%5Cs*%5B%22%7C'%7C%60%5D%22)
Closes #2385

feat: support magical comment "webpackChunkName"

---

scripts/check_changeset.js

sometime changeset may have problems when we do bump, but it's too late to find these bugs in release which cause we waste time on build bindings which can't be published https://github.com/web-infra-dev/rspack/actions/runs/4663369570/jobs/8254632533, this pr finds these problems ASAP.

chore: check bump in ci

---

.changeset/config.json

it would be better if nightly version carries datetime info so user know when is the nightly version published

chore: add datetime to nightly version

---

.changeset/dry-camels-tie.md
crates/rspack_core/src/options/output.rs
crates/rspack_plugin_html/src/config.rs
crates/rspack_plugin_html/src/plugin.rs
packages/rspack/tests/configCases/builtins/html-public-path-auto/index.js
packages/rspack/tests/configCases/builtins/html-public-path-auto/webpack.config.js

The builtins html will inject the assets into the html, but injection path is wrong when public path is auto.
https://github.com/web-infra-dev/rspack/issues/2710

fix(html): html inject public path incorrect

---

.changeset/bright-carrots-behave.md
packages/rspack-cli/src/commands/build.ts
packages/rspack-cli/src/commands/serve.ts
packages/rspack-cli/src/rspack-cli.ts
packages/rspack-cli/src/utils/options.ts
packages/rspack-cli/tests/build/basic/basic.test.ts

* check unknown command to avoid user passing unknown options or command
* add rspack dev as a alias of rspack serve
This remove the behavior of passing entry by post options which is not documented

chore: enable strictCommand & strictOption check

---

.changeset/shiny-squids-matter.md
crates/rspack_plugin_progress/src/lib.rs

The `progress_bar.set_prefix` method will immediately draw an empty progress bar, which looks ugly.
We can move the `progress_bar.set_prefix` to `make` stage, so the empty progress bar will not be printed:

fix(progress): should not display empty progress bar

---

Cargo.lock
Cargo.toml
crates/node_binding/Cargo.lock
crates/node_binding/Cargo.toml
crates/node_binding/package.json
packages/playground/fixtures/import-empty-css-file/test/index.test.ts
pnpm-lock.yaml
scripts/check_rust_dependency.js

1. fix the issue caused by: https://github.com/napi-rs/napi-rs/pull/1531, this issue will cause napi-rs to generate different `d.ts` even if you start a blank pr and just rebuild the node-binding.
2. 'bitflags': napi has upgraded to latest `bitfalgs@2.x.x`, but there are still lots of dependencies still use `bitflags@1.x.x`, like `clap, swc`, this cause CI failed in version checking, `bitflags@2.x.x` still need some time to adopt in rust community, but we need upgrade napi-rs to latest to fix some bug. so bypass `bitflags` for now.

chore: 🤖 bump napi

---

crates/rspack_core/src/build_chunk_graph/code_splitter.rs

Code splitting has a hot path on `depended_modules`, this PR caches the result.
In a project a with 20k modules, code splitting time is reduced from 6s to 2s.

perf(core): improve cold startup performance by caching `depended_modules` function in code splitter

---

.changeset/new-papayas-rest.md
crates/node_binding/binding.d.ts
crates/node_binding/src/hook.rs
crates/node_binding/src/js_values/hooks.rs
crates/node_binding/src/plugins/mod.rs
crates/rspack_core/src/compiler/compilation.rs
crates/rspack_core/src/plugin/api.rs
crates/rspack_core/src/plugin/plugin_driver.rs
packages/rspack/src/compilation.ts
packages/rspack/src/compiler.ts
packages/rspack/tests/Compiler.test.ts

feat(hook): add optimizeModules hook

---

packages/rspack-plugin-minify/src/index.js

feat(terser): expose terser options: mangle, keep_classnames and keep_fnames
Exposing these options allow us to customize the terser properties. 
```
config.optimization = {
minimize: true,
minimizer: [
new minifyPlugin({
minifier: 'terser',
keep_fnames: true,
}),
]
};
```

feat(terser): expose terser options

---

CONTRIBUTING.md

Just a small fix on [CONTRIBUTING.md](https://github.com/web-infra-dev/rspack/blob/main/CONTRIBUTING.md) as currently pnpm@7.32.0 is forced by engine definition in package.json.

docs: pnpm install command fix based on engine

---

examples/plugin-compat/package.json
examples/plugin-compat/rspack.config.js
examples/plugin-compat/src/index.js
packages/rspack/src/compilation.ts
pnpm-lock.yaml

Closed https://github.com/web-infra-dev/rspack/issues/2913
This pull request adds a getter method for the chunks property of the Compilation class in packages/rspack/src/compilation.ts. 
The integration is working well however the licenses file doesn't show all the included dependencies of the first-level included dependencies. 
The licenses file includes all first-level included dependencies but not for all second-level and the following. I guess to include all levels should be necessary also add compatible compilation.chunkGraph. 
</details>

feat: add compatible compilation.chunks

---

packages/rspack/src/compiler.ts

Appearing the build error in case of set [perChunkOutput](https://github.com/web-infra-dev/rspack/blob/98b6c6b8b98235f27d8462f07df0b1709da83be0/examples/plugin-compat/rspack.config.js#LL62C25-L62C25
) as false: 
```
Error: napi error: GenericFailure - TypeError: compilation.compiler.isChild is not a function
...
:28)
0: _napi_register_module_v1
1: <unknown>
2: <unknown>
```
The Rspack isn't supporting the LicenseWebpackPlugin when the perChunkOutput property has value false.
```javascript
new licensePlugin.LicenseWebpackPlugin({
stats: {
warnings: false,
errors: false
},
perChunkOutput: true,
outputFilename: `3rdpartylicenses.txt`
}),
```

fix(license-plugin): add support for license-plugin in case of perChunkOutput as false

---

packages/rspack/tests/MultiCompiler.test.ts

(which may be the source of crashing in CI)

chore(rspack): skip multi compiler pressure test

---

.github/workflows/reusable-build.yml

closes #3404
Passing build: https://github.com/web-infra-dev/rspack/actions/runs/5161482807
I'll trigger the nightly once this is merged.

fix: fix aarch64-unknown-linux-gnu not building jemallocator

---

Cargo.lock
crates/rspack_binding_options/src/options/raw_split_chunks.rs
crates/rspack_napi_shared/Cargo.toml
crates/rspack_napi_shared/src/ext/js_reg_exp_ext.rs
crates/rspack_napi_shared/src/ext/mod.rs
crates/rspack_napi_shared/src/js_values/js_reg_exp.rs
crates/rspack_napi_shared/src/lib.rs
crates/rspack_plugin_split_chunks_new/src/common.rs

- This PR makes converting `JsRegExp` to `RspackRegex` easier.
- The converting also covered `flags` of `RegExp` in JS.
- It would be better to merge #3573 with this PR together.

feat: easier way for converting `JsRegExp` to `RspackRegex`

---

crates/rspack_core/src/compiler/hmr.rs

1. remove new_compilation module_graph ast to use code_generation cache

fix: code generation cache not working

---

crates/rspack_core/src/module_factory.rs
crates/rspack_loader_runner/src/runner.rs
packages/rspack/tests/cases/schemes/data-imports/webpack.config.js

When using `rspack serve` it may automatically run a rebuild after the first build completes.
By debugging this behavior, I discovered that watchpack had emitted an array containing empty strings as deleted files which triggered the issue. And this empty string is a file_dependency which is generated by `data uri`.
1. Modify tests to ensure all items in `compilation.*deps` are absolute paths
2. Only add the resource_path which is a absolute path

fix: rspack serve will automatically rebuild once

---

crates/rspack_core/src/compiler/hmr.rs

The `compilation.has_module_import_export_change` is used to skip code & bundle splitting, it can improve hmr speed when no module import and export changes.
It is incorrectly set to `true` which will cause code & bundle splitting to never be skipped.
Fix the incorrect value of `compilation.has_module_import_export_change` and fix hmr performance degradation.
Currently no testing plan but I will build hmr monitoring system to avoid hmr speed degradation.
For more information see: https://github.com/web-infra-dev/rspack/issues/3593

fix: import export check invalidation on make stage

---

.github/CODEOWNERS

This PR offloads work from @hardfist to @Boshen. Code reviewers are now assigned to teams with the following settings

chore: update CODEOWNERS.md

---

.github/workflows/release-canary.yml
.github/workflows/reusable-build.yml

This PR refactors the release canary workflow.
I used the trick to force a build, we can't use `!canary` because it uses the file from the main branch.
```
push:
branches:
- canary
```
CI succeeds:
* https://github.com/web-infra-dev/rspack/actions/runs/5420876863/jobs/9855999770
Npm has the correct canary version:
* https://www.npmjs.com/package/@rspack/core/v/0.2.4-canary-e11ab9b-20230630084907

ci: refactor release-canary

---

packages/rspack-plugin-html/package.json

```js
const HtmlWebpackPlugin = require('@rspack/plugin-html')
// ... other config
plugins: [
new HtmlWebpackPlugin({ title: 'My App' })
]
}
```
Error: ENOENT: no such file or directory, open '/Users/xxx/project/node_modules/@rspack/plugin-html/default_index.ejs'

fix: npm package contains default_index.ejs file

---

crates/rspack_core/src/dependency/mod.rs
packages/rspack/tests/configCases/worker/not-fully-specified-by-default/a.js
packages/rspack/tests/configCases/worker/not-fully-specified-by-default/index.js

```js
new Worker(new URL("./worker"), import.meta.url)
```
resolve without extension for worker should works
- `packages/rspack/tests/configCases/worker/not-fully-specified-by-default`

fix: resolve worker without extension

---

crates/rspack_plugin_split_chunks_new/src/plugin/min_size.rs
crates/rspack_plugin_split_chunks_new/src/plugin/module_group.rs
packages/rspack/tests/configCases/split-chunks/issue-3646/src/another.js
packages/rspack/tests/configCases/split-chunks/issue-3646/src/index.js
packages/rspack/tests/configCases/split-chunks/issue-3646/src/shared.js
packages/rspack/tests/configCases/split-chunks/issue-3646/webpack.config.js

Since we removed some modules and chunks from the `other_module_group`. There are chances that the `min_chunks` and `min_size` validation is not satisfied anymore. So we need run validations again.
This prevents creating small chunks that violate the `minSize` option.
Related issue
- #3646 
I will close this issue after I change the docs.
Add a test.

fix(splitChunks): should validate `min_size` of `ModuleGroup` in the each end of round

---

examples/angular/scripts/build.js
packages/rspack-plugin-minify/src/index.js

Directly deleting options from the original object will cause the `this.options` cannot be used for the next run. 
This also causes failure on the angular example.
Fixed build exit code for angular and the example itself.

fix(minifier): fix minifier options difference between minifications

---

crates/node_binding/binding.d.ts
crates/node_binding/src/js_values/asset.rs
crates/rspack_core/src/chunk.rs
crates/rspack_core/src/compiler/compilation.rs
crates/rspack_core/src/options/output.rs
packages/rspack/src/util/index.ts
packages/rspack/tests/configCases/output/chunk-filename/index.js
packages/rspack/tests/configCases/output/chunk-filename/webpack.config.js

closes #3704
Fixed an issue that does not have `chunkhash` placeholder in chunk context.
See changes in `rspack/test/configCases/output/chunk-filename`

fix: `chunkhash` should be available in chunk context

---

crates/rspack_plugin_javascript/src/dependency/mod.rs
crates/rspack_plugin_javascript/src/dependency/module_argument_dependency.rs
crates/rspack_plugin_javascript/src/visitors/dependency/api_scanner.rs
crates/rspack_plugin_javascript/src/visitors/dependency/hot_module_replacement_scanner.rs
crates/rspack_plugin_javascript/src/visitors/swc_visitor/react.rs

Replace `module.id` `module.hot` `__webpack_module__` to module argument. Also, avoid react refresh runtime use `module.hot` directly.
These test at js side and already test it.

fix: replace module refrence or __webpack_module__ to module argument

---

.github/workflows/reusable-build.yml

We have a zig installation which is never used, this PR removes it
Our current CI doesn't run mac builds, so I did a separate CI run to make sure Mac builds succeed.
https://github.com/web-infra-dev/rspack/actions/runs/5462017982/jobs/9941882978

ci: remove setup-zip because it is no longer needed

---

crates/rspack_core/src/external_module.rs
crates/rspack_plugin_library/src/amd_library_plugin.rs
crates/rspack_plugin_library/src/system_library_plugin.rs
packages/rspack/tests/configCases/externals/non-amd-externals-amd/index.js
packages/rspack/tests/configCases/externals/non-amd-externals-amd/test.config.js
packages/rspack/tests/configCases/externals/non-amd-externals-amd/webpack.config.js
packages/rspack/tests/configCases/library/amd-unnamed/index.js

https://github.com/webpack/webpack/pull/17466
- `packages/rspack/tests/configCases/externals/non-amd-externals-amd`

fix: non amd external break amd library

---

scripts/bench/make-threejs10x-production-config.js

1. Our option normalized logic is done by js side, so we need to enable `treeShaking` by hand on rust side benchmark.

chore: 🤖 enable tree shaking in bench

---

.github/workflows/release-canary.yml

Add `x86_64-unknown-linux-gnu` to canary so it can be tested on Cloud IDEs.
None

chore: release canary with x86_64-unknown-linux-gnu for Cloud IDE

---

crates/rspack_core/src/context_module.rs
packages/playground/cases/context/delete-file/index.test.ts
packages/playground/cases/context/delete-file/rspack.config.js
packages/playground/cases/context/delete-file/src/index.html
packages/playground/cases/context/delete-file/src/index.js
packages/playground/cases/context/delete-file/src/mod1.js
packages/playground/cases/context/delete-file/src/mod2.js

Fix the "resolve error" when delete module in a context directory on development mode, which mentioned in #2901 .
Add context_dependency to build_info may make this context be watched by watchpack correctly. So when some module in this context is deleted, the context can be passed to compilation as modified_files and make the snapshot become invalid.
Add a E2E test case in playground to mock the file delete action.

fix(rspack_core): context delete file

---

Cargo.lock
Cargo.toml
crates/cargo-rst/Cargo.toml
crates/node_binding/Cargo.toml
crates/rspack/Cargo.toml
crates/rspack_binding_options/Cargo.toml
crates/rspack_build/Cargo.toml
crates/rspack_core/Cargo.toml
crates/rspack_hash/Cargo.toml
crates/rspack_loader_runner/Cargo.toml
crates/rspack_loader_swc/Cargo.toml
crates/rspack_plugin_asset/Cargo.toml
crates/rspack_plugin_css/Cargo.toml
crates/rspack_plugin_dev_friendly_split_chunks/Cargo.toml
crates/rspack_plugin_entry/Cargo.toml
crates/rspack_plugin_html/Cargo.toml
crates/rspack_plugin_javascript/Cargo.toml
crates/rspack_plugin_progress/Cargo.toml
crates/rspack_plugin_wasm/Cargo.toml
crates/rspack_regex/Cargo.toml
crates/rspack_symbol/Cargo.toml
crates/swc_plugin_import/Cargo.toml

Bump Rust dependencies and remove unused dependencies with `cargo machete`.
CI passes.

chore: bump Rust dependencies

---

crates/rspack_plugin_css/src/dependency/url.rs
packages/rspack/tests/__snapshots__/case.test.ts.snap
packages/rspack/tests/__snapshots__/configCase.test.ts.snap
packages/rspack/tests/configCases/css/urls/index.js
packages/rspack/tests/configCases/css/urls/urls.css

escape css url content
`url(data:text/bad-base64;base64, abcd?#iefix)` => `url("data:text/bad-base64;base64, abcd?#iefix")`
- `packages/rspack/tests/configCases/css/urls`

fix: should escape css url content

---

crates/rspack_plugin_runtime/src/runtime_module/runtime/css_loading.js
packages/playground/cases/css/render-to-body/index.test.ts
packages/playground/cases/css/render-to-body/rspack.config.js
packages/playground/cases/css/render-to-body/src/index.css
packages/playground/cases/css/render-to-body/src/index.html
packages/playground/cases/css/render-to-body/src/index.js

The webpack css hmr runtime use `document.head` to update css but maybe the user inject css link to body, the pr is fixed it.  `mini-css-extract-plugin` do it at https://github.com/webpack-contrib/mini-css-extract-plugin/blob/master/src/index.js#L908.
Added e2e

fix: hmr should work for inject css link to body

---

.github/workflows/release-canary.yml

closes #3784
Debug mode creates 1 bloated >1G binary which can not be uploaded to npm.
We can try a canary once this is merged, but it should pass because this is now the same as all the other full releases.

ci: release canary without debug mode because binary size is too big to upload (>1G)

---

packages/rspack/src/config/zod/builtins.ts

Fixes what looks like an accidental typo in `builtins.html` types generated with zod. The name of `publicPath` instead is `publicPathz`. The [official documentation](https://www.rspack.dev/config/builtins.html#builtinshtml) correctly lists `publicPath`.
I've discovered the issue in a project. `publicPath` is still the only working option, it's just the types that are wrong, no need to test anything.

fix(core): Typo in html builtins types

---

.github/workflows/release-canary.yml

Canary release is triggered with comments. GitHub workflows that are triggered with comments sets their checkout branch to default branch. So **we should make sure to checkout to the PR branch to test corresponding Pull Request**.
Ref: https://github.com/web-infra-dev/modern.js/blob/51297712c2d9b5c0ac6a13ab5c3bc97b36f0fd89/.github/workflows/release.yml#L37
N/A

chore: fix canary release

---

crates/rspack/tests/tree-shaking/class-extend/app.js
crates/rspack/tests/tree-shaking/class-extend/expected/main.js
crates/rspack_plugin_javascript/src/dependency/esm/harmony_import_specifier_dependency.rs

Before will replace shorthand filed to null, it will throw `Cannot use a reserved word as a shorthand property`.
Added

fix: shorthand filed symbol unsed

---

packages/rspack/src/chunk_group.ts
packages/rspack/src/compilation.ts
packages/rspack/src/compiler.ts
packages/rspack/src/config/adapter-rule-use.ts
packages/rspack/src/config/adapter.ts
packages/rspack/src/config/types.ts
packages/rspack/src/loader-runner/index.ts
packages/rspack/src/stats.ts
packages/rspack/src/stats/DefaultStatsFactoryPlugin.ts
packages/rspack/src/util/bindingVersionCheck.ts
packages/rspack/src/util/index.ts
packages/rspack/src/util/normalization.ts
packages/rspack/src/watching.ts

Add version consistency check for core, binding and addon.
closes https://github.com/web-infra-dev/rspack/issues/3715
ecosystem-ci passing

feat(packages/rspack): add version check for binding

---

.github/workflows/ci.yml

This should reduce the workload for a single job, and reduce the CI cache size
See https://github.com/web-infra-dev/rspack/actions/runs/5608756480/jobs/10261543104 for passed CI (I triggered this from a push event).

ci: split `cargo check` and `cargo test` into two jobs

---

crates/rspack_plugin_javascript/src/visitors/swc_visitor/react.rs
packages/playground/cases/react/class-component/index.test.ts
packages/playground/cases/react/class-component/react-refresh.js
packages/playground/cases/react/class-component/rspack.config.js
packages/playground/cases/react/class-component/src/App.jsx
packages/playground/cases/react/class-component/src/index.html
packages/playground/cases/react/class-component/src/index.jsx

Because the code which react class component transformed by `react-refresh` hasn't `$RefreshReg$/$RefreshSig$` flag, so it isn't inject refresh runtime.It caused react class component only update by bubble to parent component at hmr. The pr always inject refresh runtime to fix it.
Note: class component hmr will not preserve status, you can see at https://github.com/pmmmwh/react-refresh-webpack-plugin/blob/main/docs/TROUBLESHOOTING.md
Added

fix: react class component hmr

---

scripts/release/publish.mjs

I just noticed that we use `0.x.y` other than `v0.x.y` for release tag which is not popular in OSS, both react、vue and other projects all use 'v0.x.y' for release tag, and since we will introduce minor branch soon, I think we should use '0.x.y' for branch name and 'v0.x.y' for release tag name, in case we mix them and do wrong operations on it.
No Test Needed

chore: use v0.x.y instead of 0.x.y for release tag

---

packages/rspack/src/rspack.ts

fix type: should not return null when only called rspack with only one parameter
use ts function overload to handle the rspack return type

chore(types): should not return null when only called rspack with one parameter

---

crates/rspack_core/src/compiler/compilation.rs
crates/rspack_core/src/context_module.rs
crates/rspack_core/src/external_module.rs
crates/rspack_core/src/module.rs
crates/rspack_core/src/normal_module.rs
crates/rspack_core/src/parser_and_generator.rs
crates/rspack_core/src/tree_shaking/analyzer.rs
crates/rspack_core/src/tree_shaking/asset_module.rs
crates/rspack_core/src/tree_shaking/js_module.rs
crates/rspack_core/src/tree_shaking/mod.rs
crates/rspack_core/src/tree_shaking/optimizer.rs
crates/rspack_core/src/tree_shaking/visitor.rs
crates/rspack_plugin_asset/src/lib.rs
crates/rspack_plugin_css/src/parser_and_generator/mod.rs
crates/rspack_plugin_javascript/src/parser_and_generator/mod.rs
crates/rspack_plugin_json/src/lib.rs
crates/rspack_plugin_wasm/src/parser_and_generator.rs

1. Close https://github.com/web-infra-dev/rspack/issues/3649
2. In the make phase, the module graph does not have detailed info on each module, we can't get the module id of each dependencies. So we use `""` by default, in analyze phase transform dependency id into module id. 
4. 
1. Tests should pass.

chore: use dep_id instead of module id

---

crates/rspack_core/src/tree_shaking/optimizer.rs
crates/rspack_core/src/tree_shaking/symbol/mod.rs
crates/rspack_core/src/tree_shaking/visitor.rs

1. `ctxt` in import map is useless in the rest of stage, so removed it.

refactor: remove ctxt of variable in import map

---

crates/rspack_plugin_css/src/dependency/import.rs
crates/rspack_plugin_css/src/visitors/mod.rs

Css-import replacement was originally implemented with dependency template. 
The implementation is supposed to remove the css-import statement in order to do module concatenation.
This PR refactors the current span calculation workaround into a more reasonable way which leverages the at-rule span.
closes #3813
This is a refactor, so tests has been added before(using snapshots).

refactor: css-import span should be calculated with at-rule

---

examples/react-with-less/rspack.config.js
examples/react-with-sass/rspack.config.js

Currently, `react-with-less` and `react-with-sass` examples cannot be started normally. 
Modify their `rspack.config.js` so that they can be started easily.
Goto these example dirs and execute `pnpm dev`. Then check that the view has rendered normally.

chore: fix example code

---

Cargo.lock
crates/rspack_error/Cargo.toml
crates/rspack_error/src/emitter.rs
crates/rspack_error/tests/fixtures/char-based-offset-error-span/fixtures__char-based-offset-error-span.snap
crates/rspack_error/tests/fixtures/html_syntax_error/fixtures__html_syntax_error.snap
crates/rspack_error/tests/fixtures/js_syntax_error/fixtures__js_syntax_error.snap
crates/rspack_error/tests/fixtures/jsx_syntax_error/fixtures__jsx_syntax_error.snap
crates/rspack_error/tests/fixtures/recoverable_syntax_error/fixtures__recoverable_syntax_error.snap
crates/rspack_error/tests/fixtures/sass-warnings/fixtures__sass-warnings.snap
crates/rspack_error/tests/fixtures/ts_syntax_error/fixtures__ts_syntax_error.snap
crates/rspack_error/tests/fixtures/tsx_syntax_error/fixtures__tsx_syntax_error.snap
crates/rspack_error/tests/out_of_order/multi_json_syntax_error/fixtures__multi_json_syntax_error.snap
crates/rspack_error/tests/out_of_order/multiple_file_syntax_error/fixtures__multiple_file_syntax_error.snap
packages/rspack/tests/Stats.test.ts
packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap

1. Now the error frame can display () 4 lines of source code above where the error happen, and 4 lines below error happen.

feat: add more context for error frame

---

packages/rspack/package.json
packages/rspack/src/config/types.ts
packages/rspack/src/index.ts
packages/rspack/tests/configCases/type/multiple-options/index.js
packages/rspack/tests/configCases/type/multiple-options/respack.config.js
packages/rspack/tests/configCases/type/multiple-options/rspack.config.js
packages/rspack/tsconfig.test.json

Fixes #3607.
Rspack config files should support MultiRspackOptions. But for the `Configuration` type, only "single" `RspackOptions` are used.
This PR changes the definition of `Configuration` type in `packages/rspack/src/config/types.ts` to add support to MultiRspackOptions. After this, we expect following `rspack.config.js` will emit no error:
```js
// @ts-check
/** @type {import('@rspack/cli').Configuration} */
const test = [];
module.exports = test;
```
Added several test cases to ensure such configuration can pass type checking.

fix: modify Configuration type to support MultiRspackOptions

---

crates/node_binding/src/js_values/stats.rs

Fixed a panic issue for node binding.
Note:
For developers who are writing NAPI-RS bindings, returning a `Result` or annotate `#[napi(catch_unwind)]` is acceptable unless you can be sure 100% that `expect` is working or it will cause a runtime panic
Not necessary.

fix: fix a panic issue of `get_hash` if assertion is failed

---

webpack-test/cases/inner-graph/circular/test.config.js
webpack-test/cases/inner-graph/circular/test.filter.js
webpack-test/cases/inner-graph/circular2/test.config.js
webpack-test/cases/inner-graph/circular2/test.filter.js
webpack-test/cases/inner-graph/class-dynamic-props/test.config.js
webpack-test/cases/inner-graph/class-dynamic-props/test.filter.js
webpack-test/cases/inner-graph/export-default-named/test.config.js
webpack-test/cases/inner-graph/export-default-named/test.filter.js
webpack-test/cases/inner-graph/extend-class/test.config.js
webpack-test/cases/inner-graph/extend-class/test.filter.js
webpack-test/cases/inner-graph/extend-class2/test.config.js
webpack-test/cases/inner-graph/extend-class2/test.filter.js
webpack-test/cases/inner-graph/no-side-effects/test.config.js
webpack-test/cases/inner-graph/no-side-effects/test.filter.js
webpack-test/cases/inner-graph/pure-in-removed/test.config.js
webpack-test/cases/inner-graph/pure-in-removed/test.filter.js
webpack-test/cases/inner-graph/reexport-namespace-and-default/test.config.js
webpack-test/cases/inner-graph/reexport-namespace-and-default/test.filter.js
webpack-test/cases/inner-graph/simple/test.config.js
webpack-test/cases/inner-graph/simple/test.filter.js
webpack-test/cases/inner-graph/static-of-class/test.config.js
webpack-test/cases/inner-graph/static-of-class/test.filter.js
webpack-test/cases/inner-graph/switch/test.config.js
webpack-test/cases/inner-graph/switch/test.filter.js
webpack-test/cases/inner-graph/try-globals/test.config.js
webpack-test/cases/inner-graph/try-globals/test.filter.js

1. enable most of cases/inner-graph tests, the rest tests needs `pureExpressionDependency`

test: migrate inner-graph test

---

crates/node_binding/binding.d.ts
crates/node_binding/src/js_values/stats.rs
crates/rspack_binding_options/src/options/mod.rs
crates/rspack_core/src/compiler/compilation.rs
crates/rspack_core/src/compiler/queue.rs
crates/rspack_core/src/lib.rs
crates/rspack_core/src/module_graph/mod.rs
crates/rspack_core/src/module_graph_module.rs
crates/rspack_core/src/module_profile.rs
crates/rspack_core/src/options/compiler_options.rs
crates/rspack_core/src/stats.rs
crates/rspack_loader_sass/tests/fixtures.rs
crates/rspack_loader_swc/tests/fixtures.rs
crates/rspack_testing/src/test_config.rs
packages/rspack/src/config/adapter.ts
packages/rspack/src/config/defaults.ts
packages/rspack/src/config/normalization.ts
packages/rspack/src/config/types.ts
packages/rspack/src/config/zod/index.ts
packages/rspack/src/stats/DefaultStatsFactoryPlugin.ts
packages/rspack/src/stats/statsFactoryUtils.ts
packages/rspack/tests/Stats.test.ts
packages/rspack/tests/__snapshots__/Defaults.unittest.ts.snap
packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap

enable to add module profile info in `stats.module[]`, only contain factory, building, and integration time consuming, storing and restoring are related to mem cache, and we haven't implement it yet
- add in `Stats.test.ts`

feat: support configuration.profile

---

crates/rspack_core/src/utils/hooks.rs
packages/rspack/tests/Errors.test.ts

fixs #3891, esm error missing due to importer contains "javascript/esm" which cause fs.readfile failed
No Test Needed

fix(core): fix missing source_info in esm module error

---

crates/rspack/tests/tree-shaking/nested-import-3/answer.js
crates/rspack/tests/tree-shaking/nested-import-3/app.js
crates/rspack/tests/tree-shaking/nested-import-3/expected/main.js
crates/rspack/tests/tree-shaking/nested-import-3/index.js
crates/rspack/tests/tree-shaking/nested-import-3/lib.js
crates/rspack/tests/tree-shaking/nested-import-3/test.config.json
crates/rspack_core/src/tree_shaking/optimizer.rs

1. fix issue when a importAllAs namespace access follows a export all symbol

fix: nested import follow a export all symbol

---

packages/rspack-cli/src/rspack-cli.ts
packages/rspack-cli/src/utils/profile.ts
packages/rspack-cli/tests/build/profile/profile.test.ts

add `stats.logging` when RSPACK_PROFILE enabled
- updated `packages/rspack-cli/tests/build/profile/profile.test.ts`

feat: add logging when RSPACK_PROFILE enabled

---

.github/workflows/bench.yml

Running benchmarks in merge_group and pr is very different, I will add a github action to run benchmarks on merge_group

chore: remove benchmark test on merge_group

---

Cargo.lock
crates/bench/src/main.rs
crates/rspack/benches/main.rs
crates/rspack/tests/fixtures.rs
crates/rspack_error/tests/fixtures.rs
crates/rspack_error/tests/fixtures/char-based-offset-error-span/test.config.json
crates/rspack_error/tests/fixtures/sass-warnings/test.config.json
crates/rspack_loader_sass/tests/fixtures.rs
crates/rspack_loader_sass/tests/fixtures/rspack_importer/test.config.json
crates/rspack_loader_swc/tests/fixtures.rs
crates/rspack_loader_swc/tests/fixtures/esm/test.config.json
crates/rspack_loader_swc/tests/fixtures/ts/test.config.json
crates/rspack_testing/Cargo.toml
crates/rspack_testing/examples/build-cli.rs
crates/rspack_testing/src/lib.rs
crates/rspack_testing/src/loader.rs
crates/rspack_testing/src/run_fixture.rs
crates/rspack_testing/src/test_config.rs
crates/rspack_testing/test.config.scheme.json

Adds support for resolving builtin loaders in Rust tests.
Changed Rust test option field `Rule.use.builtinLoader` -> `Rule.use.loader`
Turned on a few tests. See Git Diff.

feat: support resolving builtin loaders in Rust tests

---

.eslintignore
.github/workflows/ci.yml
examples/loader-compat/rspack.config.js
package.json
pnpm-lock.yaml

Let's lint the codebase with oxlint :-)
* running `pnpm run lint:js` succeeds
* The new CI job "Lint js" passes https://github.com/web-infra-dev/rspack/actions/runs/5924295664/job/16061553616
* for lint-staged, I modified a file and made sure it got triggered and reported errors
Running locally:
```
rspack  oxlint ❯ pnpm run lint:js
> monorepo@0.2.12 lint:js /Users/bytedance/github/rspack
> oxlint .
Finished in 1011ms on 827 files with 56 rules using 12 threads.
Found 0 warnings and 0 errors.```

chore: add oxlint

---

crates/rspack_core/src/dependency/const_dependency.rs
crates/rspack_core/src/dependency/mod.rs

Const Dependency size 56 -> 40, DependencyType 32 -> 24

perf: reduce memory size of const dependency and dependency type

---

crates/rspack/tests/fixtures/code-splitting/expected/main.js
crates/rspack/tests/samples/remove-parent-modules/self-import/expected/main.js
crates/rspack/tests/tree-shaking/cjs-export-computed-property/expected/main.js
crates/rspack/tests/tree-shaking/export-all-from-side-effects-free-commonjs/expected/main.js
crates/rspack_core/src/dependency/runtime_template.rs
crates/rspack_plugin_javascript/src/visitors/dependency/common_js_export_scanner.rs
crates/rspack_plugin_javascript/src/visitors/dependency/harmony_detection_scanner.rs
crates/rspack_plugin_javascript/src/visitors/dependency/mod.rs
crates/rspack_plugin_javascript/src/visitors/dependency/util.rs
crates/rspack_plugin_javascript/tests/fixtures/magic_comment/expected/main.js

Before we use `dynamic` as exports type for all commonjs, webpack is analzyed the commonjs and split to four state.
- Mark `dynamic` for dynamic `__esModule`
- Mark `flag` for `__esModule` value is true, the behavior is same as `namespace`(mark esm)
- Mark `undefined` for can't scanned `__esModule`
- Mark `default` for original commonjs
It will avoid use runtime to detect `__esModule` and make code faster.
The webpack cjs analzye test is already migrated.

feat: cjs analyze

---

Cargo.lock
Cargo.toml
crates/rspack_core/src/normal_module_factory.rs
crates/rspack_core/src/tree_shaking/visitor.rs
crates/rspack_core/src/utils/module_rules.rs
crates/rspack_loader_runner/Cargo.toml
crates/rspack_loader_runner/src/lib.rs
crates/rspack_loader_runner/src/runner.rs

This PR removes nodejs-resolver from rspack_loader_runner by directly using the serde_json::Value returned from the resolver.
We'll change the dependency once nodejs-resolver makes a new release for
* https://github.com/web-infra-dev/nodejs_resolver/pull/196
CI passes.

refactor(rspack_loader_runner): remove nodejs_resolver dependency

---

crates/rspack_core/src/build_chunk_graph/code_splitter.rs
crates/rspack_core/src/compiler/compilation.rs
crates/rspack_core/src/dependency/mod.rs
crates/rspack_core/src/module_graph/mod.rs
crates/rspack_core/src/module_graph_module.rs
crates/rspack_plugin_javascript/src/dependency/hmr/import_meta_hot_accept.rs
crates/rspack_plugin_javascript/src/dependency/hmr/import_meta_hot_decline.rs
crates/rspack_plugin_javascript/src/dependency/hmr/module_hot_accept.rs
crates/rspack_plugin_javascript/src/dependency/hmr/module_hot_decline.rs
crates/rspack_util/src/comparators.rs

- `DependencyId` size 16 -> 8, the `u32` is enough.
-  HMR Dependency size 56 -> 32
- `ModuleGraphModule` size 648 -> 336
Not need.

perf: reduce ModuleGraphModule memory size

---

crates/node_binding/binding.d.ts
crates/node_binding/src/plugins/loader.rs
crates/rspack_binding_options/src/options/mod.rs
crates/rspack_core/src/compiler/compilation.rs
crates/rspack_core/src/compiler/hmr.rs
crates/rspack_core/src/compiler/mod.rs
crates/rspack_core/src/compiler/queue.rs
crates/rspack_core/src/module_factory.rs
crates/rspack_core/src/normal_module_factory.rs
crates/rspack_core/src/options/compiler_options.rs
crates/rspack_loader_sass/tests/fixtures.rs
crates/rspack_loader_swc/tests/fixtures.rs
crates/rspack_testing/src/test_config.rs
packages/rspack/src/config/adapter.ts
packages/rspack/src/config/adapterRuleUse.ts
packages/rspack/src/config/defaults.ts
packages/rspack/src/config/normalization.ts
packages/rspack/src/config/types.ts
packages/rspack/src/config/zod/index.ts
packages/rspack/src/loader-runner/index.ts
packages/rspack/tests/__snapshots__/Defaults.unittest.ts.snap
packages/rspack/tests/configCases/loader/additional-data/webpack.config.js
packages/rspack/tests/configCases/loader/source-map/webpack.config.js
webpack-test/configCases/loaders/issue-3320/deprecations.js
webpack-test/configCases/loaders/issue-3320/index.js
webpack-test/configCases/loaders/issue-3320/test.filter.js
webpack-test/scripts/test-metric.js

closes https://github.com/web-infra-dev/rspack/issues/3737
Added support for `resolveLoader`. However, nodejs-resolver does not support 
alias with a custom query or fragment, which results in the failure with the first webpack test case.
See test changes and add back the first test once `resolve.alias` supports custom query and fragment.

feat: support option `resolveLoader`

---

packages/rspack/src/Stats.ts

In the previous implementation, `Stats` will be converted eagerly from compilation to `JsStats` 
and this cause a severe performance impact on large applications. So https://github.com/web-infra-dev/rspack/pull/4029 reverts this.
However, at the same time, we still have to deal with the problem that the previous PR fixed.
`webpack-dev-server` and other implementations alike will try to access the previous 
compilation stats unintentionally. In JavaScript, this does not create a problem, however, 
in the world of Rust, the reference of compilation will be dropped as the next compilation starts.
The core part of this is that `Stats` is depending on that reference to generate the stats, which 
results in `get_hash` a failure on the JS side.
So here comes the workaround for that problem:
This …

fix: add workaround for accessing previous stats

---

crates/rspack_binding_options/src/options/raw_module/mod.rs
crates/rspack_core/src/compiler/compilation.rs
crates/rspack_core/src/compiler/queue.rs
crates/rspack_core/src/compiler/resolver.rs
crates/rspack_core/src/context_module.rs
crates/rspack_core/src/module.rs
crates/rspack_core/src/module_factory.rs
crates/rspack_core/src/module_graph_module.rs
crates/rspack_core/src/normal_module.rs
crates/rspack_core/src/normal_module_factory.rs
crates/rspack_core/src/options/module.rs
crates/rspack_core/src/plugin/args.rs
crates/rspack_core/src/stats.rs
crates/rspack_loader_sass/src/lib.rs

`TaskResult` size 392 -> 16
Not need.

perf: reduce task structs memory size

---

crates/node_binding/src/plugins/loader.rs
crates/rspack_core/src/normal_module.rs
crates/rspack_core/src/normal_module_factory.rs
crates/rspack_loader_runner/src/runner.rs
crates/rspack_loader_runner/src/scheme.rs
packages/rspack/src/config/adapterRuleUse.ts
packages/rspack/tests/configCases/loader/builtin-loader-ident/index.js
packages/rspack/tests/configCases/loader/builtin-loader-ident/lib.ts
packages/rspack/tests/configCases/loader/builtin-loader-ident/webpack.config.js

Support `ident` for builtin loader. You can now use `ident` as a way to pass options to builtin loaders. See test changes for details.
See test changes.

feat: support `ident` for builtin loader

---

crates/rspack_core/src/dependency/dependency_template.rs
crates/rspack_core/src/dependency/runtime_template.rs
crates/rspack_core/src/external_module.rs
crates/rspack_core/src/init_fragment.rs
crates/rspack_plugin_javascript/src/dependency/commonjs/module_decorator_dependency.rs
crates/rspack_plugin_javascript/src/dependency/esm/harmony_compatibility_dependency.rs
crates/rspack_plugin_javascript/src/dependency/esm/harmony_export_imported_specifier_dependency.rs
crates/rspack_plugin_javascript/src/dependency/esm/harmony_export_specifier_dependency.rs
crates/rspack_plugin_javascript/src/dependency/esm/harmony_import_dependency.rs
crates/rspack_plugin_javascript/src/parser_and_generator/mod.rs
crates/rspack_plugin_javascript/src/runtime.rs

Add add InitFragment trait, because need add `HarmonyExportInitFragment` for `HarmonyExportSpecifierDependency` codegen. The treeshaking need refactor `HarmonyExportSpecifierDependency` codegen.
Not need.

refactor: add InitFragment trait

---

lint-staged.config.mjs
package.json

Currently when a specific file is passed to oxlint (e.g. `/pwd/to/test.js`), it will lint the file despite having it specified in `.eslintignore`, this makes lint-staged useless when an ignored file is committed.
oxlint has the same behavior as eslint.
This PR makes lint-staged to run on all changed files. The overhead is manageable because oxlint completes within a second.
See
* https://github.com/okonet/lint-staged#how-can-i-ignore-files-from-eslintignore
* https://github.com/okonet/lint-staged#example-run-tsc-on-changes-to-typescript-files-but-do-not-pass-any-filename-arguments
I verified the behaviour we want: when an ignored file is commited, it does not get linted.

chore: run oxlint on all files during lint-staged (for now)

---

crates/rspack/tests/tree-shaking/import-export-all-as-a-empty-module/expected/main.js
crates/rspack/tests/tree-shaking/namespace-access-var-decl-rhs/expected/main.js
crates/rspack/tests/tree-shaking/react-redux-like/expected/main.js
crates/rspack/tests/tree-shaking/reexport-all-as-multi-level-nested/expected/main.js
crates/rspack/tests/tree-shaking/simple-namespace-access/expected/main.js
crates/rspack/tests/tree-shaking/webpack-side-effects-all-used/expected/main.js
crates/rspack/tests/tree-shaking/webpack-side-effects-simple-unused/expected/main.js
crates/rspack_core/src/compiler/compilation.rs
crates/rspack_core/src/dependency/mod.rs
crates/rspack_core/src/init_fragment.rs
crates/rspack_core/src/tree_shaking/optimizer.rs
crates/rspack_plugin_javascript/src/dependency/esm/harmony_export_expression_dependency.rs
crates/rspack_plugin_javascript/src/dependency/esm/harmony_export_imported_specifier_dependency.rs
crates/rspack_plugin_javascript/src/dependency/esm/harmony_export_specifier_dependency.rs
crates/rspack_plugin_javascript/src/plugin/provided_exports_plugin.rs
crates/rspack_plugin_javascript/src/visitors/dependency/harmony_export_dependency_scanner.rs

The pr add `HarmonyExportSpecifierDependency` `get_exports` implement to support treeshaking, and also merge `HarmonyExportInitFragment` to generate one `webpack_require.d`
Not need.

feat: implement HarmonyExportSpecifierDependency get_exports

---

.github/workflows/reusable-build.yml

https://github.com/web-infra-dev/rspack/actions/runs/6021243804/job/16334084913#step:8:367 node14 on windows is broken and we can't fix it now, it seems related to nodejs itself
https://github.com/nodejs/help/issues/2660

chore: takedown node14 test on windows

---

crates/node_binding/binding.d.ts
crates/rspack_binding_options/src/options/mod.rs
crates/rspack_binding_options/src/options/raw_builtins/mod.rs
crates/rspack_binding_options/src/options/raw_entry.rs
crates/rspack_core/src/build_chunk_graph/code_splitter.rs
crates/rspack_core/src/chunk.rs
crates/rspack_core/src/chunk_group.rs
crates/rspack_core/src/compiler/compilation.rs
crates/rspack_core/src/compiler/hmr.rs
crates/rspack_core/src/dependency/entry.rs
crates/rspack_core/src/dependency/mod.rs
crates/rspack_core/src/module_graph_module.rs
crates/rspack_core/src/options/entry.rs
crates/rspack_plugin_entry/src/lib.rs
crates/rspack_plugin_javascript/src/dependency/esm/import_dependency.rs
crates/rspack_plugin_javascript/src/dependency/worker/mod.rs
crates/rspack_plugin_javascript/src/visitors/dependency/worker_scanner.rs
crates/rspack_testing/src/test_config.rs
packages/rspack-dev-server/src/server.ts
packages/rspack-dev-server/tests/__snapshots__/normalizeOptions.test.ts.snap
packages/rspack-dev-server/tests/normalizeOptions.test.ts
packages/rspack/src/Compiler.ts
packages/rspack/src/builtin-plugin/EntryPlugin.ts
packages/rspack/src/builtin-plugin/base.ts
packages/rspack/src/builtin-plugin/index.ts
packages/rspack/src/config/adapter.ts
packages/rspack/src/index.ts
packages/rspack/src/lib/EntryOptionPlugin.ts
packages/rspack/src/rspack.ts
packages/rspack/src/rspackOptionsApply.ts

- refactor and expose EntryPlugin
- compilation.globalEntry for [the `name: undefined` to prepend entry case](https://github.com/web-infra-dev/rspack/pull/4073/files#diff-6195dbe0219b3b7ba39567cf6de6d629fb3a7b78c582c6b0b2957d1425105922R243)
- no need

feat: expose `EntryPlugin`

---

.github/workflows/ci.yml

I have no idea why every merge queue event is triggered on the main branch: 
However, it seems to me we can trigger the workflow only if checking is requested.  Action type `destroyed` is not what we should care about I guess. Please check on this @jerrykingxyz 
https://docs.github.com/en/webhooks/webhook-events-and-payloads?actionType=destroyed#merge_group

ci: only run `merge_group` tests on check being requested

---

packages/rspack-dev-client/src/reactRefreshEntry.js

Make dev-server compatible in chrome 49;
Only this line in dev-client, make the web project not been opened in chrome 49.
I changed the code in my project/node_modules/@rspack/dev-client/src/reactRefreshEntry.js.
and my web project worked.

fix: make dev-server compatible with globalThis

---

.github/workflows/reusable-build.yml

Reverts web-infra-dev/rspack#4018 to see if it fixes the CI.

revert: "ci: reduce binary size"

---

packages/rspack/src/Compilation.ts
packages/rspack/src/Stats.ts
packages/rspack/src/config/types.ts
packages/rspack/src/stats/DefaultStatsFactoryPlugin.ts
packages/rspack/tests/Stats.test.ts

fix: align stats.modulesSpace default behaivor with webpack

---

packages/rspack/src/Compiler.ts
packages/rspack/src/rspackOptionsApply.ts

eagerly apply entry and externals is a break change, so revert it before we release a patch version
- eco-ci should pass

revert: apply entry and externals eagerly

---

crates/node_binding/binding.d.ts
crates/rspack_binding_options/src/options/mod.rs
crates/rspack_binding_options/src/options/raw_experiments.rs
crates/rspack_core/src/options/experiments.rs
packages/rspack/src/config/adapter.ts
packages/rspack/src/config/defaults.ts
packages/rspack/src/config/schema.js
packages/rspack/src/config/types.ts
packages/rspack/src/config/zod/experiments.ts
packages/rspack/tests/__snapshots__/Defaults.unittest.ts.snap

Initializes future flags. Rspack learned the technique for future flag from remix team.
Future flagging is fundamentally the same as other terms you may heard of like `feature-gates`, `feature-flags`.
Essentially, in Rspack, when it comes to adopting a deprecation or a newly added feature that differs from 
the behavior of the previous version, a new future flag is added.
For example:
```js
experiments: {
rspackFuture: {
disableTransformByDefault: true, // opt-in new deprecations
newResolver: true
}
}
}
```
| Version |  Future flag | Deprecation message | Stability of the future behavior |
| - | - |  - | - |
| Current minor | Added (Default: _same as the old behavior_) | Added | ⚠️ (Not guaranteed)  |
| Next minor |  Still available (Default: _new behavior enabled_)  | …

feat: initialize future flags

---

crates/rspack_plugin_runtime/src/runtime_module/css_loading.rs
packages/rspack/tests/runtimeCases/runtime/split-css-chunk/index1.js
packages/rspack/tests/runtimeCases/runtime/split-css-chunk/index2.js

`initial_chunk_ids_without_css` is render to `installedChunks`.
`initial_chunk_ids_with_css` is render to `loadCssChunkData`, it will be add to `installedChunks`
so here direct use `initial_chunk_ids`.
Added.

fix: css loading module should render initial_chunk_ids

---

crates/node_binding/binding.d.ts
crates/rspack_binding_options/src/options/raw_module/mod.rs
crates/rspack_core/src/options/module.rs
crates/rspack_core/src/utils/module_rules.rs
packages/rspack/src/config/adapter.ts
packages/rspack/src/config/types.ts

Fixes https://github.com/web-infra-dev/rspack/issues/4112
Fixes https://github.com/web-infra-dev/rspack/issues/4003
This PR fixes the issue on the Rspack side to provide a better interoperability
with JavaScript runtime. However, **leveraging the order of each rule being called
is, to me, not a good choice to make**, but webpack does not provide a good alternative 
for us to match `resourcePath` and `resourceQuery` at the same time,
which is a bummer for implementations in a multi-threaded environment. 
Nevertheless, it's reasonable for vue-loader or some other loaders to choose as 
they do not have another choice to make.
See: https://github.com/web-infra-dev/rspack/issues/4003#issuecomment-1689662380
Tested locally on the reproduction demos.

fix: improve interoperability of rules with side-effects

---

crates/rspack_binding_options/src/options/raw_module/js_loader.rs
crates/rspack_loader_runner/src/runner.rs
crates/rspack_loader_sass/src/lib.rs
crates/rspack_loader_swc/src/lib.rs
package.json
packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
packages/rspack/tests/statsCases/parse-error-builtin-swc-loader/index.ts
packages/rspack/tests/statsCases/parse-error-builtin-swc-loader/webpack.config.js

Continue https://github.com/web-infra-dev/rspack/pull/4082
In webpack, `emitWarning` or `emitError` can be used to create some additional error on the compilation. 
In Rspack, we have the `loader_context.diagnostics` field to represent this behavior. But this one has been misused in builtin-loaders. In order to make error report successfully and treat the loader error as the module build error, I changed it to returning a `Err`. 
But still, there's some misalignment in the `ModuleBuildError`, I will create a new issue to indicate this problem.
Added.

fix: `builtin:swc-loader` does not report error correctly

---

.github/workflows/need-doc.yml

we already sync the document issue to website when we add label, so no need to add duplicate one when we close merge request

chore: disable sync document when closed merge request

---

crates/node_binding/src/js_values/stats.rs
crates/rspack_core/src/cache/occasion/code_generate.rs
crates/rspack_core/src/cache/occasion/resolve_module.rs
crates/rspack_core/src/compiler/compilation.rs
crates/rspack_core/src/compiler/queue.rs
crates/rspack_core/src/context_module_factory.rs
crates/rspack_core/src/logger.rs
crates/rspack_core/src/module_factory.rs
crates/rspack_core/src/normal_module_factory.rs
packages/rspack/src/logging/Logger.ts
packages/rspack/src/stats/DefaultStatsFactoryPlugin.ts
packages/rspack/src/stats/DefaultStatsPrinterPlugin.ts
packages/rspack/tests/Stats.test.ts

Add cache hits info to stats for benchmark and debugging the cache
- Adding cases in Stats.test.ts, should include the outputs of cache hits info when stats.logging=verbose, and should not have any outputs when the cache is disabled

feat(core): add cache hits info to stats

---

examples/monaco-editor-js/package.json
examples/monaco-editor-ts-react/package.json

monaco-editor-example takes too long to build in ci, let's save our ci time by remove it in ci

chore: takedown down monaco-editor example build in ci

---

packages/rspack-dev-server/src/patch.ts
packages/rspack-dev-server/src/server.ts
packages/rspack/src/Stats.ts

Patch webpack-dev-server to prevent it from reading empty stats (to whom using rspack-dev-server).
Continue: https://github.com/web-infra-dev/rspack/pull/4028
Blocked by https://github.com/web-infra-dev/rspack/issues/4120

fix: patch `sendStats` of webpack-dev-server

---

Cargo.lock
Cargo.toml
crates/rspack_loader_sass/tests/fixtures/rspack_importer/snapshot/output.snap
crates/rspack_plugin_css/tests/fixtures/custom/composes/b.module.css
crates/rspack_plugin_css/tests/fixtures/custom/composes/d.module.css
crates/rspack_plugin_css/tests/fixtures/custom/composes/e.module.css
crates/rspack_plugin_css/tests/fixtures/custom/composes/f.module.css
crates/rspack_plugin_css/tests/fixtures/custom/composes/index.js
crates/rspack_plugin_css/tests/fixtures/custom/composes/snapshot/output.snap
crates/rspack_plugin_css/tests/fixtures/custom/composes/style.module.css
crates/rspack_plugin_css/tests/fixtures/custom/composes/test.config.json
crates/rspack_plugin_css/tests/fixtures/custom/http_import/snapshot/output.snap
crates/rspack_plugin_css/tests/fixtures/custom/modules-ident-name/snapshot/output.snap
crates/rspack_plugin_css/tests/fixtures/webpack/at-charset/snapshot/output.snap
crates/rspack_plugin_css/tests/fixtures/webpack/at-import-in-the-middle/snapshot/output.snap
crates/rspack_plugin_css/tests/fixtures/webpack/at-import/snapshot/output.snap
crates/rspack_plugin_css/tests/fixtures/webpack/default-options/snapshot/output.snap
crates/rspack_plugin_css/tests/fixtures/webpack/multiple-entry/snapshot/output.snap
crates/rspack_plugin_css/tests/fixtures/webpack/nested/snapshot/output.snap
crates/rspack_plugin_css/tests/fixtures/webpack/output-iife/snapshot/output.snap
crates/rspack_plugin_css/tests/fixtures/webpack/shared-import/snapshot/output.snap
crates/rspack_plugin_css/tests/fixtures/webpack/simple-async-load-css/snapshot/output.snap
crates/rspack_plugin_css/tests/fixtures/webpack/simple-async/snapshot/output.snap
crates/rspack_plugin_css/tests/fixtures/webpack/simple-commonjs-syntax/snapshot/output.snap
crates/rspack_plugin_css/tests/fixtures/webpack/simple-es-module-syntax/snapshot/output.snap
crates/rspack_plugin_css/tests/fixtures/webpack/simple-multiple/snapshot/output.snap
crates/rspack_plugin_css/tests/fixtures/webpack/simple/snapshot/output.snap
crates/rspack_plugin_javascript/src/ast/stringify.rs
crates/rspack_testing/src/run_fixture.rs

bump swc version to fix #3875 and add test.
closes #3875
see also:
https://github.com/swc-project/swc/pull/7917
unit test

fix(css/modules): bump swc version to fix #3875 and add test

---

packages/rspack/src/config/zod.ts

Improve zod type, so I can iterate on the `Rule.type` deprecation warning more eazily

feat: improve zod types

---

Cargo.lock
crates/rspack_core/Cargo.toml
crates/rspack_core/src/resolver/resolver_impl.rs

This release of the oxc resolver contains the following features:
* Automatic tsconfig project references path resolution.
* When `tsconfig.json#references` is specified, their respective `tsconfig.json#compilerOptions.paths` is used for resolving path alias within that project.
* See https://www.typescriptlang.org/docs/handbook/project-references.html
* Tracing capabilities via `OXC_RESOLVER=DEBUG` / `OXC_RESOLVER=ERROR` and `OXC_RESOLVER=TRACE` environment variables
* Tons of performance improvements
* node_modules lookups are cached
* symlink resolutions are cached
* total number of path hashes are reduce by half
* removed searching inside non-existent directories for scoped packages. Previously `node_modules/@scope/package/index.js` is searched when `node_modules/@scope` does not …

feat(rspack_core): oxc_resolver v0.2.0

---

crates/rspack_plugin_javascript/src/ast/stringify.rs
crates/rspack_plugin_javascript/src/parser_and_generator/mod.rs
examples/builtin-swc-loader/src/App.jsx
examples/builtin-swc-loader/src/index.jsx
packages/rspack/tests/configCases/source-map/source-map/App.jsx
packages/rspack/tests/configCases/source-map/source-map/index.js
packages/rspack/tests/configCases/source-map/source-map/webpack.config.js

- Fixed a case where source-map cannot be mapped to original content, even if `"module"` is enabled.
- Aligned JavaScript source to Webpack
Added.

fix: fix module source-map

---

examples/nestjs/rspack.config.js
packages/rspack-dev-server/src/server.ts
packages/rspack-dev-server/tests/__snapshots__/normalizeOptions.test.ts.snap
packages/rspack-dev-server/tests/normalizeOptions.test.ts
packages/rspack/src/config/defaults.ts
packages/rspack/src/config/zod.ts
packages/rspack/tests/__snapshots__/Defaults.unittest.ts.snap

feat: disableReactRefreshByDefault future flag

---

crates/rspack_error/src/catch_unwind.rs

Remove `panic_hook` to avoid lock contentions.
`take_hook` and `set_hook` needs to acquire locks.
Let's not distinguish whether a panic needs to be suppressed.
No need.

perf: remove `panic_hook`

---

Cargo.lock
crates/rspack_plugin_swc_js_minimizer/Cargo.toml
crates/rspack_plugin_swc_js_minimizer/src/lib.rs
crates/rspack_plugin_swc_js_minimizer/src/minify.rs
crates/rspack_util/src/lib.rs

perf: parallelize swc js minify

---

crates/rspack_loader_swc/src/options.rs
crates/rspack_loader_swc/src/transformer.rs
packages/rspack/tests/configCases/builtin-swc-loader/react-refresh-false/webpack.config.js
packages/rspack/tests/configCases/builtin-swc-loader/react-runtime-classic/webpack.config.js

`rspackExperiments.react.refresh` is quite different from the original `jsc.transform.react.refresh`. So, at the time of implementing this feature, 
this option was migrated to `rspackExperiments`. However, this would add some problem.
Since the `rspackExperiments.react.refresh` does two things.
1. Apply `react-refresh/babel`
2. Apply `react-refresh-webpack-plugin/loader`
The second one should respect the bail-out path provided by user and the path of `react-refresh` and `react-refresh-webpack-plugin/client/ReactUtils` and something like this,
which cannot be decided directly from user when writing the configuration. So we decide to remove this and respect to swc-loader's original `jsc.transform.react` and not including the `react-refresh-webpack-plugin/loader` transformations. …

fix: remove `react` from `rspackExperiments` of `builtin:swc-loader`

---

packages/rspack-dev-server/src/server.ts
packages/rspack-dev-server/tests/__snapshots__/normalizeOptions.test.ts.snap
packages/rspack-dev-server/tests/normalizeOptions.test.ts
packages/rspack/src/config/defaults.ts
packages/rspack/src/config/zod.ts
packages/rspack/tests/__snapshots__/Defaults.unittest.ts.snap

move to disableTransformByDefault since this actually depend on disableTransformByDefault

fix: merge disableReactRefreshByDefault to disableTransformByDefault

---

packages/rspack/src/Compiler.ts

fix: missing rspack-only plugins on compiler.webpack

---

packages/rspack/src/builtin-plugin/index.ts
packages/rspack/src/config/adapterRuleUse.ts

Prepare for deprecation for `builtin:sass-loader` in 0.4.0.
See: https://github.com/web-infra-dev/rspack/pull/4041

feat: deprecate `builtin:sass-loader`

---

packages/rspack-plugin-react-refresh/package.json
packages/rspack-plugin-react-refresh/src/index.js
packages/rspack-plugin-react-refresh/src/options.js
packages/rspack-plugin-react-refresh/src/options.json
packages/rspack-plugin-react-refresh/tests/fixtures/.gitignore
packages/rspack-plugin-react-refresh/tests/fixtures/custom/index.js
packages/rspack-plugin-react-refresh/tests/fixtures/default/index.js
packages/rspack-plugin-react-refresh/tests/fixtures/node_modules/foo/index.js
packages/rspack-plugin-react-refresh/tests/fixtures/node_modules/foo/package.json
packages/rspack-plugin-react-refresh/tests/test.spec.ts
pnpm-lock.yaml

- Add `react-refresh-entry` to the loader excluding list
- Support passing `include` or `exclude` of plugin
Added

feat: support `include` and `exclude` of react-refresh-rspack-plugin

---

packages/rspack-dev-server/src/server.ts
packages/rspack-plugin-react-refresh/src/index.js

avoid builtin:react-refresh-loader and builtins.react.refresh transform at the same time
so builtin:react-refresh-loader and react-refresh-plugin should only used when `rspackFuture.disableTransformByDefault` enabled

fix: avoid double react refresh transform in rspack-dev-server

---

crates/node_binding/binding.d.ts
crates/rspack_binding_options/src/options/raw_external.rs
crates/rspack_core/src/dependency/runtime_template.rs
crates/rspack_core/src/external_module.rs
crates/rspack_core/src/lib.rs
crates/rspack_core/src/options/externals.rs
crates/rspack_core/src/utils/mod.rs
crates/rspack_core/src/utils/property_access.rs
crates/rspack_plugin_externals/src/plugin.rs
crates/rspack_plugin_library/src/amd_library_plugin.rs
crates/rspack_plugin_library/src/assign_library_plugin.rs
crates/rspack_plugin_library/src/export_property_plugin.rs
crates/rspack_plugin_library/src/module_library_plugin.rs
crates/rspack_plugin_library/src/system_library_plugin.rs
crates/rspack_plugin_library/src/umd_library_plugin.rs
crates/rspack_plugin_library/src/utils.rs
packages/rspack/src/builtin-plugin/ExternalsPlugin.ts
packages/rspack/src/config/zod.ts
packages/rspack/tests/configCases/externals/item-value-object/index.js
packages/rspack/tests/configCases/externals/item-value-object/lodash.js
packages/rspack/tests/configCases/externals/item-value-object/webpack.config.js

feat: support object external item value

---

crates/node_binding/src/loader.rs

fix: passing option as `&str` caused memory leak in `builtin:swc-loader`

---

packages/rspack/src/builtin-plugin/index.ts

chore: add builtins.react/... only works for transformByDefault tip

---

crates/rspack_loader_react_refresh/src/lib.rs
crates/rspack_swc_visitors/src/react.rs
packages/playground/cases/react/basic-disableTransformByDefault/.gitignore
packages/playground/cases/react/basic-disableTransformByDefault/node_modules/foo/index.jsx
packages/playground/cases/react/basic-disableTransformByDefault/node_modules/foo/package.json
packages/playground/cases/react/basic-disableTransformByDefault/rspack.config.js
packages/playground/cases/react/basic-disableTransformByDefault/src/App.jsx
packages/rspack-plugin-react-refresh/client/reactRefreshEntry.js
packages/rspack-plugin-react-refresh/tests/test.spec.ts

fix https://github.com/web-infra-dev/rspack-website/pull/479#discussion_r1335759431
webpack-plugin did the same, the loader will [inject runtime code](https://github.com/pmmmwh/react-refresh-webpack-plugin/blob/0b960573797bf38926937994c481e4fec9ed8aa6/loader/index.js#L47), if a module doesn't have the injected runtime, it will use the empty implementation of `register` and `signature`, which equal to `$RefreshReg$` and `$RefreshSig$`
added

fix: $RefreshReg$ is not defined error in node_modules

---

crates/rspack_core/src/utils/module_rules.rs
packages/rspack/tests/configCases/module/issue-4224/index.js
packages/rspack/tests/configCases/module/issue-4224/index.scss
packages/rspack/tests/configCases/module/issue-4224/webpack.config.js
packages/rspack/tests/configCases/module/one-of-nested/webpack.config.js
packages/rspack/tests/configCases/module/order-nested/index.js
packages/rspack/tests/configCases/module/order-nested/lib.js
packages/rspack/tests/configCases/module/order-nested/loader.js
packages/rspack/tests/configCases/module/order-nested/loader1.js
packages/rspack/tests/configCases/module/order-nested/loader2.js
packages/rspack/tests/configCases/module/order-nested/webpack.config.js

- `Rule.oneOf` should match at least one rule, otherwise the `effects` does not take affect.
- `Rule.rules` should run ahead of `Rule.oneOf`
Fixes https://github.com/web-infra-dev/rspack/issues/4224
Added

fix: fix `Rule.oneOf` and `Rule.rules`

---

crates/rspack_loader_swc/src/lib.rs

This PR adds a check for `rspack_loader_swc` config so the user doesn't use both `env` and `jsc.target` at the same time. This is fixed in accordance with the official way its done under SWC here: https://github.com/swc-project/swc/pull/7704/files#diff-05ec577011f6096aac154c266838a96b40e857713f31a3441fc73baf1d90580eR376
Ticket: #4081
- Go to `examples/builtin-swc-loader/rspack.config.js`
- Under the `builtin:swc-loader` loader options add `jsx.target: "es2016"` and `env.targets: "es2016"`
- Run the build ` pnpm --filter "./examples/builtin-swc-loader" build`
- Build should fail

fix(rspack_loader_swc): Fail the build when jsc.target and env are used together for the SWC loader

---

packages/rspack-dev-server/src/server.ts

Updated from 0.3.0 to 0.3.4, use new builtins:swc-loader and set disableTransformByDefault to true

fix: type error when use builtins:swc-loader and disableTransformByDefault

---

.github/workflows/release-nightly.yml

nightly failed message kinds of pollute github issue especially during holiday, so change it to discord

chore: change nightly release notification to discord other than github issue

---

.github/workflows/reusable-build.yml

remove android sdk save 15GB which seems big enough for use, let's save some time for free-disk-cache itself
reduce 3min -> 1min, seems not bad
No Need

chore: only remove android sdk

---

packages/rspack-plugin-react-refresh/src/index.js
packages/rspack/src/web/ResolveSwcPlugin.ts

CI passes. Should be working if `react-refresh` is removed from the package.

feat: handle `react-refresh` resolving in `@rspack/plugin-react-refresh`

---

packages/rspack/src/builtin-plugin/HtmlRspackPlugin.ts
packages/rspack/tests/configCases/builtins/html-meta/index.js
packages/rspack/tests/configCases/builtins/html-meta/webpack.config.js

rspack will ignore the builtins.html.meta value set to `Record<string, Record<string, string>>`
updated the builtins.html test cases to cover this.

fix: rspack builtin.html.meta.* support Record<string, string>

---

crates/rspack_binding_macros/src/lib.rs
crates/rspack_core/src/loader/loader_runner.rs
crates/rspack_plugin_javascript/src/dependency/esm/mod.rs

This PR use `visibilitiy` to check unused imports

chore: remove unused imports

---

packages/rspack-cli/src/rspack-cli.ts

GitHub Issue: #4314 
This bug is exactly caused by the internal bug in "yargs". when we use .command method in yargs, if the async handler function we pass in throws an error, it will result in an unexpected "--help" command execution.
I also propose an issue for "yargs", maybe they will fix this bug.
about the bug detail you can see [yargs issue 2368](https://github.com/yargs/yargs/issues/2368)
For rspack, I wrap the handler code with a "try-catch" block to catch the error we throw. In the catch block, we should exit the process by calling "process.exit()" ourselves instead of throwing an error, which prevents the internal bug in "yargs".
Why don't use "try-catch" block wrap `await this.program.parseAsync(hideBin(argv));`?
I have tried this, but it doesn't work, It may be because the …

fix(4314): remove help info print when throw error

---

webpack-test/configCases/split-chunks/asnyc-entries/test.filter.js
webpack-test/configCases/split-chunks/chunk-filename-delimiter-default/test.filter.js
webpack-test/configCases/split-chunks/chunk-filename-delimiter/test.filter.js
webpack-test/configCases/split-chunks/custom-filename-function/test.filter.js
webpack-test/configCases/split-chunks/custom-filename-many-custom/test.filter.js
webpack-test/configCases/split-chunks/custom-filename/test.filter.js
webpack-test/configCases/split-chunks/entry-point-error/test.filter.js
webpack-test/configCases/split-chunks/incorrect-chunk-reuse/test.filter.js
webpack-test/configCases/split-chunks/issue-11337/test.filter.js
webpack-test/configCases/split-chunks/issue-11513/test.filter.js
webpack-test/configCases/split-chunks/issue-12307/test.filter.js
webpack-test/configCases/split-chunks/issue-8908/test.filter.js
webpack-test/configCases/split-chunks/issue-9491/test.filter.js
webpack-test/configCases/split-chunks/max-size-casing/test.filter.js
webpack-test/configCases/split-chunks/module-type-filter/test.filter.js
webpack-test/configCases/split-chunks/move-to-entrypoint/test.filter.js
webpack-test/configCases/split-chunks/no-options/test.filter.js
webpack-test/configCases/split-chunks/reuse-chunk-name/test.filter.js
webpack-test/configCases/split-chunks/runtime-chunk-async-node/test.filter.js
webpack-test/configCases/split-chunks/runtime-chunk-no-async/test.filter.js
webpack-test/configCases/split-chunks/runtime-chunk-node-13130/test.filter.js
webpack-test/configCases/split-chunks/runtime-chunk-node/test.filter.js
webpack-test/configCases/split-chunks/runtime-chunk/test.filter.js
webpack-test/configCases/split-chunks/vendor-only-entrypoint/node_modules/vendor.js
webpack-test/configCases/split-chunks/vendor-only-entrypoint/test.filter.js

runs webpack tests, leave reasons for why tests are failed

chore: align webpack tests

---

webpack-test/cases/entry-inline/no-var-leak-strict/test.filter.js
webpack-test/cases/entry-inline/no-var-leak/test.filter.js
webpack-test/cases/errors/case-sensitive/test.filter.js
webpack-test/cases/errors/crash-missing-import/test.filter.js
webpack-test/cases/errors/cyclic-reexport-references/test.filter.js
webpack-test/cases/errors/harmony-import-missing/test.filter.js
webpack-test/cases/errors/harmony-import-missing2/test.filter.js
webpack-test/cases/errors/load-module-cycle-multiple/test.filter.js
webpack-test/cases/errors/load-module-cycle/test.filter.js
webpack-test/cases/errors/load-module-error/test.filter.js
webpack-test/cases/errors/loader-error-warning/test.filter.js
webpack-test/cases/errors/mjs-non-fully-specified/test.filter.js
webpack-test/cases/errors/module-request/test.filter.js
webpack-test/cases/esm/import-meta/index.js
webpack-test/cases/esm/import-meta/test.filter.js
webpack-test/cases/esm/import-meta/warnings.js
webpack-test/cases/inner-graph/circular/test.filter.js
webpack-test/cases/inner-graph/circular2/test.filter.js
webpack-test/cases/inner-graph/export-default-named/test.filter.js
webpack-test/cases/inner-graph/extend-class/test.filter.js
webpack-test/cases/inner-graph/no-side-effects/test.filter.js
webpack-test/cases/inner-graph/pure-in-removed/test.filter.js
webpack-test/cases/inner-graph/reexport-namespace-and-default/test.filter.js
webpack-test/cases/inner-graph/simple/test.filter.js
webpack-test/cases/inner-graph/static-of-class/test.filter.js
webpack-test/cases/inner-graph/switch/test.filter.js
webpack-test/cases/inner-graph/try-globals/test.filter.js

chore: enable more webpack-test

---

crates/rspack_core/src/dependency/mod.rs
crates/rspack_core/src/tree_shaking/visitor.rs
crates/rspack_plugin_javascript/src/dependency/esm/harmony_import_dependency.rs
crates/rspack_plugin_javascript/src/plugin/infer_async_modules_plugin.rs
crates/rspack_plugin_javascript/src/visitors/dependency/harmony_import_dependency_scanner.rs
packages/rspack/tests/configCases/tree-shaking/multiple-same-import-side-effect/index.js
packages/rspack/tests/configCases/tree-shaking/multiple-same-import-side-effect/lib.js
packages/rspack/tests/configCases/tree-shaking/multiple-same-import-side-effect/webpack.config.js

checkout added test case
after we introduce [source_order](https://github.com/web-infra-dev/rspack/pull/4262) for new tree shaking implementation, HarmonyImportSideEffectDependency will be duplicated, and merged by InitFragment, this is aligned behavior with webpack, before it won't be duplicated
```js
// before:
import {a} from "./lib" // => Dependency(100 /* dependency_id */, "./lib")
import {b} from "./lib" // => Dependency(100 /* dependency_id */, "./lib")
```
```js
// after:
import {a} from "./lib" // => Dependency(100 /*dependency_id*/, "./lib", 0 /* source_order */)
import {b} from "./lib" // => Dependency(101 /*dependency_id*/, "./lib", 1 /* source_order */)
```
but in the old tree shaking implementation will find dependency by its request and dependency_type, so when we want to …

fix: variable undefined with multiple same import

---

.github/actions/docker-build/action.yml
.github/actions/pnpm-cache/action.yml
.github/actions/rustup/action.yml
.github/workflows/ci.yml
.github/workflows/reusable-build.yml

fix build cache not work in CI and support use self hosted runner. Some CI data are as follows:
* github action - https://github.com/web-infra-dev/rspack/actions/runs/6558444654
* pr with self hosted - https://github.com/web-infra-dev/rspack/actions/runs/6559111173
| | github action | pr with self hosted |
|--|--|--|
| build rspack |  23m4s | 5m46s |
| build job |  27m56s | 9m42s |
| rust test | 6m37s | 3m13s |
| nodejs test | 7m12s | 5m43s |
| one time CI | 39m14s | 15m46s |
This new runner can be toggled by the CI action variables `LINUX_RUNNER_LABELS`. See https://github.com/web-infra-dev/rspack/settings/variables/actions (permission required).
No

chore: use self hosted ci

---

.github/workflows/ci.yml
.github/workflows/reusable-build.yml

forked repo can not access global variable in ci, this pr will make it fallback to github action.
I will try to extract the logic for calculating runner labels in another PR

chore: support run ci with forked repo PR

---

Cargo.lock
Cargo.toml
crates/rspack/tests/tree-shaking/handle-side-effects-commonjs-required/snapshot/new_treeshaking.snap
crates/rspack_core/src/compiler/mod.rs
crates/rspack_core/src/dependency/mod.rs
crates/rspack_core/src/runtime_globals.rs
crates/rspack_core/src/tree_shaking/symbol/mod.rs
crates/rspack_core/src/tree_shaking/utils.rs
crates/rspack_core/src/tree_shaking/visitor.rs
crates/rspack_plugin_css/src/swc_css_compiler.rs
crates/rspack_plugin_javascript/src/utils.rs
crates/rspack_plugin_javascript/src/visitors/dependency/import_meta_scanner.rs
crates/rspack_plugin_javascript/src/visitors/mod.rs
crates/rspack_plugin_javascript/src/visitors/swc_visitor/compat.rs
crates/rspack_plugin_javascript/src/visitors/swc_visitor/typescript.rs

Bump SWC to fix optional chain transform bug
SWC uses new string cache strategy, so js_word cannot be used for match pattern directly
SWC typescript pass is refactored, TsEnumConfig is deprecated
No

chore: bump swc

---

crates/rspack_binding_options/src/options/raw_split_chunks.rs
webpack-test/configCases/split-chunks-common/correct-order/test.filter.js
webpack-test/configCases/split-chunks-common/extract-async-from-entry/test.filter.js
webpack-test/configCases/split-chunks-common/hot-multi/test.filter.js
webpack-test/configCases/split-chunks-common/hot-multi/webpack.config.js
webpack-test/configCases/split-chunks-common/hot/test.filter.js
webpack-test/configCases/split-chunks-common/hot/webpack.config.js
webpack-test/configCases/split-chunks-common/inverted-order/test.filter.js
webpack-test/configCases/split-chunks-common/issue-12128/test.filter.js
webpack-test/configCases/split-chunks-common/library/test.filter.js
webpack-test/configCases/split-chunks-common/move-entry/test.filter.js
webpack-test/configCases/split-chunks-common/move-to-grandparent/test.filter.js
webpack-test/configCases/split-chunks-common/simple/test.filter.js
webpack-test/configCases/split-chunks-common/target-node/test.filter.js

- splitChunks.enforce should make minChunks to be 1
- pass more webpack-tests

fix: splitChunks.enforce, pass more webpack-tests

---

crates/rspack_core/src/dependency/runtime_template.rs
crates/rspack_plugin_javascript/src/dependency/esm/harmony_export_specifier_dependency.rs
crates/rspack_plugin_javascript/src/visitors/dependency/harmony_import_dependency_scanner.rs
packages/rspack/tests/cases/indirect-call/call/dep.js
packages/rspack/tests/cases/indirect-call/call/index.js
packages/rspack/tests/cases/indirect-call/tagged-template-expression/dep.js
packages/rspack/tests/cases/indirect-call/tagged-template-expression/dep1.js
packages/rspack/tests/cases/indirect-call/tagged-template-expression/index.js

Fixes #4380
The ﻿`TaggedTemplate` should be marked with ﻿`enter_call`. Consequently, it will generate an indirect call in the form of `﻿(0, xxxx)()`.

fix: use indirect call for TaggedTpl

---

.github/workflows/reusable-build.yml

this pr will install the rust target on windows and macos, linux will install it in docker.

chore: windows and macos add target before build

---

crates/rspack_binding_options/src/options/raw_resolve.rs
crates/rspack_core/src/dependency/mod.rs
crates/rspack_core/src/options/resolve.rs
packages/rspack/src/config/README.md
packages/rspack/tests/configCases/resolve/issue-4432/index.js
packages/rspack/tests/configCases/resolve/issue-4432/package/custom.js
packages/rspack/tests/configCases/resolve/issue-4432/package/package.json
packages/rspack/tests/configCases/resolve/issue-4432/webpack.config.js

Fixes #4432
There has `undefined` and `default` field in `resolve.byDependency` in webpack, so let us change it to `Map<String, Resolve>`

fix: use string as key for resolve.by_dependency

---

crates/rspack_plugin_javascript/src/visitors/dependency/common_js_import_dependency_scanner.rs
crates/rspack_plugin_javascript/src/visitors/dependency/mod.rs
crates/rspack_plugin_javascript/src/visitors/dependency/util.rs
pnpm-lock.yaml
webpack-test/cases/require/issue-4465/index.js

Fixes #4465
We should avoid replacing ﻿`require` or `﻿require.xxx` when it has not been resolved

fix: not replace require when it not resolved

---

.github/workflows/release-canary.yml
.github/workflows/release-nightly.yml
.github/workflows/release.yml
pnpm-lock.yaml

Update pnpm lock file and remove --no-frozen-lockfile when running pnpm install on ci

chore: remove --no-frozen-lockfile when pnpm install

---

crates/rspack_plugin_runtime/src/runtime_module/runtime/async_module.js
packages/rspack/tests/runtimeDiffCases/runtime-async-module/src/a.js
packages/rspack/tests/runtimeDiffCases/runtime-async-module/src/index.js
packages/rspack/tests/runtimeDiffCases/runtime-async-module/test.config.js
packages/rspack/tests/runtimeDiffCases/runtime-async-module/webpack.config.js

Alignment of async runtime module and adding the diff test cases:
- Convert the es6+ code to es5, just like the other runtime modules
- https://github.com/webpack/webpack/blob/v5.89.0/lib/runtime/AsyncModuleRuntimeModule.js#L104

chore: alignment of async runtime module

---

packages/rspack/src/Compiler.ts
packages/rspack/src/util/assertNotNil.ts
packages/rspack/tests/configCases/hooks/issue-4395/index.js
packages/rspack/tests/configCases/hooks/issue-4395/rspack.config.js

Fixes #4395
utilize `﻿compile` instead of `﻿run` within ﻿`runAsChild`

feat: support `Compiler.compile`

---

crates/rspack_plugin_runtime/src/runtime_module/get_trusted_types_policy.rs
crates/rspack_plugin_runtime/src/runtime_module/runtime/get_trusted_types_policy.js
crates/rspack_plugin_runtime/src/runtime_plugin.rs
packages/rspack/tests/runtimeDiffCases/runtime-get-trusted-types-policy/rspack.config.js
packages/rspack/tests/runtimeDiffCases/runtime-get-trusted-types-policy/src/chunk.js
packages/rspack/tests/runtimeDiffCases/runtime-get-trusted-types-policy/src/index.js
packages/rspack/tests/runtimeDiffCases/runtime-get-trusted-types-policy/test.config.js
packages/rspack/tests/runtimeDiffCases/runtime-get-trusted-types-policy/webpack.config.js

Alignment of get trusted type policy runtime module.
- Adding logic of generating code by runtime requirements
> output.trustedTypes.onPolicyCreationFailure is not supported in Rspack yet

chore(runtime-diff): alignment of get trusted type policy runtime module

---

crates/rspack_plugin_javascript/src/utils/mod.rs
crates/rspack_plugin_javascript/src/visitors/dependency/api_scanner.rs
crates/rspack_plugin_javascript/src/visitors/dependency/common_js_export_scanner.rs
crates/rspack_plugin_javascript/src/visitors/dependency/common_js_import_dependency_scanner.rs
crates/rspack_plugin_javascript/src/visitors/dependency/common_js_scanner.rs
crates/rspack_plugin_javascript/src/visitors/dependency/compatibility_scanner.rs
crates/rspack_plugin_javascript/src/visitors/dependency/mod.rs
crates/rspack_plugin_javascript/src/visitors/dependency/node_stuff_scanner.rs
crates/rspack_plugin_javascript/src/visitors/dependency/util.rs

`SyntaxContext` is just a u32 and is cheaper to copy than pass by reference.

perf: pass `SyntaxContext` by copy

---

packages/rspack/package.json
packages/rspack/src/loader-runner/index.ts
pnpm-lock.yaml

close https://github.com/web-infra-dev/rspack/issues/4526 
I just found an alternative npm package named fast-querystring. According its readme description(https://www.npmjs.com/package/fast-querystring), it's a fast choice.
But I'm curious about where to locate the test case file?
remove old deps & update new one

chore: replace querystring with fast-querystring in @rspack/core deps

---

packages/rspack/package.json
pnpm-lock.yaml

`util` is a built module of Node.js, so `@rspack/core` do not need to declare the `util` as a dependecy.
https://nodejs.org/api/util.html

perf(@rspack/core): remove util dependency

---

crates/rspack_core/src/build_chunk_graph/code_splitter.rs
crates/rspack_plugin_javascript/src/runtime.rs
crates/rspack_plugin_runtime/src/runtime_module/load_chunk_with_module.rs
packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
webpack-test/configCases/chunk-graph/issue-9634/test.filter.js

enable `webpack/configCases/chunk-graph/issue-9634`
Insert the runtime into the child chunk group of the split module.

fix: deep insert runtime to splitted chunk

---

packages/rspack/src/builtin-plugin/base.ts
packages/rspack/tests/builtinPlugin.test.ts

Make builtin plugins class name consistent with webpack.
```js
// before
import { DefinePlugin, ProvidePlugin } from '@rspack/core';
console.log(new DefinePlugin({}).constructor.name); // -> 'Plugin'
console.log(new ProvidePlugin({}).constructor.name); // -> 'Plugin'
// after
import { DefinePlugin, ProvidePlugin } from '@rspack/core';
console.log(new DefinePlugin({}).constructor.name); // -> 'DefinePlugin'
console.log(new ProvidePlugin({}).constructor.name); // -> 'ProvidePlugin'
```

fix: make builtin plugins class name consistent with webpack

---

.github/actions/upload-artifact/action.yml

Upload artifact needs output current runner labels to keep download artifact working on same mechine

chore: upload artifact use RUNNER_LABELS

---

crates/rspack_regex/src/algo.rs
packages/rspack/tests/cases/context/issue-4557/folder/my-story.js
packages/rspack/tests/cases/context/issue-4557/index.js

Fix [Panic in require.context regex](https://github.com/web-infra-dev/rspack/issues/4557) (#4557)
Regexes using `endWith` algorithm should return `false` when checking for sticky or global flag.
Added test case
Verified that without the fix, it fails with the following error:
```
● cases › context › issue-4557 › issue-4557 should compile
error[internal]: internal error: entered unreachable code
This is not expected, please file an issue at https://github.com/web-infra-dev/rspack/issues.
0: <unknown>
1: <unknown>
2: <unknown>
3: <unknown>
4: <unknown>
5: <unknown>
6: <unknown>
7: <unknown>
8: <unknown>
9: <unknown>
10: <unknown>
11: <unknown>
● cases › context › issue-4557 › issue-4557 should load the compiled test
```

fix: require.context should not fail when using `endWith` algo (#4557)

---

packages/rspack-dev-client/package.json
packages/rspack-dev-server/package.json
packages/rspack-plugin-html/package.json
packages/rspack-plugin-minify/package.json
packages/rspack-plugin-node-polyfill/package.json
packages/rspack-plugin-react-refresh/package.json
packages/rspack/package.json

[Issue 4541](https://github.com/web-infra-dev/rspack/issues/4541)
add the `./package.json` in field `exports` of the related packages' `package.json` files to allow `package.json` file to be imported

fix: add the `./package.json` in the package.json's exports

---

crates/rspack/tests/tree-shaking/cjs-export-computed-property/snapshot/new_treeshaking.snap
crates/rspack/tests/tree-shaking/cjs-export-computed-property/snapshot/output.snap
crates/rspack/tests/tree-shaking/export-all-from-side-effects-free-commonjs/snapshot/new_treeshaking.snap
crates/rspack/tests/tree-shaking/export-all-from-side-effects-free-commonjs/snapshot/output.snap
crates/rspack/tests/tree-shaking/tree-shaking-interop/snapshot/new_treeshaking.snap
crates/rspack/tests/tree-shaking/tree-shaking-interop/snapshot/output.snap
crates/rspack_core/src/dependency/mod.rs
crates/rspack_core/src/dependency/runtime_template.rs
crates/rspack_core/src/exports_info.rs
crates/rspack_core/src/init_fragment.rs
crates/rspack_core/src/runtime_globals.rs
crates/rspack_plugin_javascript/src/dependency/commonjs/common_js_exports_dependency.rs
crates/rspack_plugin_javascript/src/dependency/commonjs/mod.rs
crates/rspack_plugin_javascript/src/dependency/esm/harmony_compatibility_dependency.rs
crates/rspack_plugin_javascript/src/runtime.rs
crates/rspack_plugin_javascript/src/visitors/dependency/common_js_export_scanner.rs
crates/rspack_plugin_javascript/src/visitors/dependency/mod.rs
crates/rspack_plugin_javascript/src/visitors/dependency/util.rs
packages/rspack/tests/Stats.test.ts
packages/rspack/tests/__snapshots__/Stats.test.ts.snap

Alignment of commonjs exports dependency, 
- Currently commonjs tree shaking does not implemented in rspack, so used name will always return itself
- This is a pre-task for alignment of module level runtime requirements and commonjs tree shaking
- Runtime requirements will also affected the result of render_module
- Test cases have been exists under test/cases/mjs

feat(runtime): alignment of commonjs exports dependency

---

packages/rspack/package.json
packages/rspack/src/config/adapterRuleUse.ts
packages/rspack/src/loader-runner/index.ts
pnpm-lock.yaml

Remove schema-utils from `@rspack/core` to improve the start up performance and reduce npm dependencies.
resolve https://github.com/web-infra-dev/rspack/issues/4588

perf(@rspack/core): remove schema-utils

---

.vscode/launch.json
crates/rspack_plugin_runtime/src/helpers.rs

It seems when we ported get_relative_path we change the logic and cause infinite loop when entry key contains '/' like 'routes/_index'
No Need

fix: fix infinite while loop when entry name contains '/' like 'routes/index'

---

examples/arco-pro/rspack.config.js

By reading CI logs, I noticed arco-pro build takes 3 - 5 minutes on Mac.
> examples/arco-pro build: Rspack compiled successfully in 255.98 s
Disabling it for faster CI run.

ci: disable minification for example/arco-pro to speed up CI

---

crates/rspack_core/src/chunk_graph/chunk_graph_chunk.rs

Some chunkGraph API in Webpack that can insert cgc or cgm if not present

fix(chunk_graph): chunkGraph insert if not present

---

crates/node_binding/src/lib.rs
crates/rspack_loader_swc/src/lib.rs
crates/rspack_plugin_css/src/lib.rs
packages/rspack/src/builtin-loader/swc/pluginImport.ts
packages/rspack/tests/configCases/builtin-swc-loader/issue-4597/.gitignore
packages/rspack/tests/configCases/builtin-swc-loader/issue-4597/diy.js
packages/rspack/tests/configCases/builtin-swc-loader/issue-4597/node_modules/aaaaa/es/button/index.js
packages/rspack/tests/configCases/builtin-swc-loader/issue-4597/node_modules/aaaaa/es/button/style/css.js
packages/rspack/tests/configCases/builtin-swc-loader/issue-4597/node_modules/aaaaa/es/button/style/index.css
packages/rspack/tests/configCases/builtin-swc-loader/issue-4597/node_modules/aaaaa/es/index.js
packages/rspack/tests/configCases/builtin-swc-loader/issue-4597/node_modules/aaaaa/package.json
packages/rspack/tests/configCases/builtin-swc-loader/issue-4597/rspack.config.js
packages/rspack/tests/configCases/builtin-swc-loader/issue-4597/src/index.js

Fixes #4597
This issue arises due to incorrect argument passing to ﻿`RawPluginImportConfig.style`. Currently, the ﻿`resolvePluginImport` does not handle the scenario where ﻿`RawPluginImportConfig.style` in the child compiler is an object due to normalization.
Since it does not involve a child compiler, it can utilize the arguments correctly.
Incorrect arguments were indeed generated. However, since only the builtin loader is present, it does not receive the incorrect arguments from the JavaScript side.
To address this, I've implemented a handler for the scenario where the type of ﻿`import.style` is an object. In such cases, we will use the original value.

fix: use original value when `import.style` is object

---

.vscode/extensions.json
examples/basic/src/lib.js
package.json
pnpm-lock.yaml
x.mjs

Introduce a drop-in replacement for Rspack/Jest CLI to 
make debugging experience better on Rspack. 
**Commands**:
- x rspack / x rs: Normal rspack-cli commands
- x jest / x j: Normal jest-cli commands
- x rsd: Debugging command for rspack-cli with VSCode support
- x jd: Debugging command for jest-cli with VSCode support
New commands did almost nothing. Passing variadic arguments is supported with `--`. CLI arguments are directly passed to respect CLI.
**Examples**:
```bash
$ x rspack -- [your-rspack-cli-args...]
$ x rspack --debug -- build
$ x rs -d -- build
$ x rsd -- build
```
```bash
$ x jest -- [your-jest-args...]
$ x jest --debug -- -t <test-name-pattern>
$ x j -d -- [test-path-pattern]
$ x jd -- [your-jest-args...]
```
We only support vscode for now and …

chore: better debugging

---

examples/angular/rspack.config.js
examples/cra-ts/rspack.config.js
examples/cra/rspack.config.js
examples/extract-license/rspack.config.js
examples/loader-compat/rspack.config.js
examples/plugin-compat/package.json
examples/plugin-compat/rspack.config.js
examples/react-15-classic/rspack.config.js
examples/react-15/rspack.config.js
examples/react-refresh-babel-loader/rspack.config.js
examples/react-refresh/rspack.config.js
examples/react-storybook/rspack.config.js
examples/react-with-less/rspack.config.js
examples/react-with-sass/rspack.config.js
examples/solid/rspack.config.js
examples/styled-components/rspack.config.js
examples/svgr/rspack.config.js
examples/vue2-tsx/rspack.config.js
examples/vue3-jsx/rspack.config.js
examples/vue3-vanilla/rspack.config.js
pnpm-lock.yaml

I disabled most minifications based on the build timings that are > 10s on Mac from reading the raw logs:

ci: disable most of the optimization.minimize in examples to speed up CI

---

packages/rspack-plugin-react-refresh/client/reactRefreshEntry.js
packages/rspack-plugin-react-refresh/src/index.ts
packages/rspack-plugin-react-refresh/src/options.ts
packages/rspack-plugin-react-refresh/tests/test.spec.ts
packages/rspack/src/Compiler.ts

When two and more projects are loaded in one site, there should be mutiple react refresh instance for perform refresh by themselves. So we should add unique name for each instance to make sure there is no conflict

feat: support library for instance unique name

---

tsconfig.base.json

Example:
Input:
``` typescript
import ModuleFilenameHelpers from "./lib/ModuleFilenameHelpers.js"
console.log(ModuleFilenameHelpers)
```
Ouput: (NodeNext)
``` typescript
const ModuleFilenameHelpers = require("./lib/ModuleFilenameHelpers.js")
// console undefined
console.log(ModuleFilenameHelpers.default)
```
Output: (CommonJS)
``` typescript
const ModuleFilenameHelpers = require("./lib/ModuleFilenameHelpers.js")
// console a object
console.log(ModuleFilenameHelpers)
```

fix: compiler.webpack.ModuleFilenameHelpers type error

---

.github/workflows/ecosystem-ci-trigger.yml

Support three ref types for rspack-ecosystem-ci:
- MODERN_REF: branch name to test against modern
- RSPRESS_REF: branch name to test against rspress
- RSBUILD_REF: branch name to test against rsbuild
```
MODERN_REF=<your-test-ref> !eco-ci modern
MODERN_REF=<your-test-ref> RSBUILD_REF=<your-test-ref> !eco-ci
RSPRESS_REF=<your-test-ref> !eco-ci
```

chore: support passing refs to ecosystem-ci

---

crates/rspack/tests/tree-shaking/tree-shaking-interop/snapshot/new_treeshaking.snap
crates/rspack/tests/tree-shaking/tree-shaking-interop/snapshot/output.snap
crates/rspack_core/src/dependency/runtime_template.rs
crates/rspack_plugin_runtime/src/runtime_module/runtime/compat_get_default_export.js
packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
packages/rspack/tests/runtimeDiffCases/runtime-compat-get-default-export/src/a.js
packages/rspack/tests/runtimeDiffCases/runtime-compat-get-default-export/src/b.js
packages/rspack/tests/runtimeDiffCases/runtime-compat-get-default-export/src/index.js
packages/rspack/tests/runtimeDiffCases/runtime-compat-get-default-export/test.config.js

Revert #4607 and #4639, the is_call is not aligned with webpack due to the differences between swc and acorn

revert: get export default

---

packages/rspack/tests/cases/parsing/issue-4643/a.js
packages/rspack/tests/cases/parsing/issue-4643/b.js
packages/rspack/tests/cases/parsing/issue-4643/c.js
packages/rspack/tests/cases/parsing/issue-4643/index.js

Adding test cases for #4643, affected #4607 and #4639, which has been reverted. 
These test cases will be used when is_call is fixed

test: add test cases for #4643

---

crates/node_binding/binding.d.ts
crates/rspack_binding_options/src/options/raw_external.rs
crates/rspack_binding_options/src/options/raw_module/js_loader.rs
crates/rspack_binding_values/src/compilation.rs

part of #4640
This is part of #4640. Currently the rspack.d.ts has several type errors due to ExternalObject.
I am not 100% sure if this is a correct direction to fix/work around. Appreciate @Brooooooklyn 's feedback.
This pull request avoid un-generated identifiers by using string literal. 
It will still work because either the API is internal or is used as an opaque token. 
With this, we are one step forward toward removing skipLibCheck flag. cc @xiaoxiangmoe 
I used `tsc` to check the lib is type-error-free.

fix(typing): fix ExternalObject type argument not found

---

crates/rspack_plugin_javascript/src/lib.rs
crates/rspack_plugin_javascript/src/visitors/dependency/import_scanner.rs
crates/rspack_plugin_javascript/src/visitors/dependency/require_context_scanner.rs
packages/rspack/tests/cases/context/issue-4663/assets/sample.js
packages/rspack/tests/cases/context/issue-4663/index.js

closes https://github.com/web-infra-dev/rspack/issues/4663

fix: `require.context` should parse literals

---

crates/rspack_core/src/normal_module_factory.rs
packages/rspack/tests/configCases/loader/issue-4630/index.js
packages/rspack/tests/configCases/loader/issue-4630/webpack.config.js
packages/rspack/tests/configCases/loader/issue-4630/こんにちは世界.js
packages/rspack/tests/configCases/loader/issue-4630/你好世界.js
packages/rspack/tests/configCases/loader/issue-4630/반갑구나세상아.js
x.mjs

closes https://github.com/web-infra-dev/rspack/issues/4630

fix: fix filenames with multiple bytes in match-resource

---

packages/rspack-cli/src/commands/build.ts
packages/rspack-cli/src/rspack-cli.ts
packages/rspack-cli/src/utils/loadConfig.ts
packages/rspack-cli/src/utils/options.ts
packages/rspack-cli/src/utils/profile.ts

part of #4640
This fixes all ts-expect-error in packages/rspack-cli.  Errors are most related to 
* nullable config. 
* unannotated callback
* not importing types
`tsc --noEmit`

fix(typing): fix packages/rspack-cli ts-expect-error

---

examples/angular/package.json
package.json
pnpm-lock.yaml

Bump Webpack 5.76.0 to 5.89.0 to run diff on examples
CI

chore: bump dev webpack from 5.76.0 to 5.89.0

---

webpack-test/cases/parsing/issue-11353/async_generator_function.js

Found the slowest test by reading the logs :-)
```
PASS  ./TestCasesNormal.basictest.js (12.318 s, 240 MB heap size)
```
-> 
```
PASS  ./TestCasesNormal.basictest.js (7.36 s, 287 MB heap size)
```
Sped up the test run by ... surprising 5 seconds!

fix(webpack-test): fix the slow 5 seconds test

---

webpack-test/configCases/asset-modules/base-uri/index.js

This test reads a huge png, which constantly takes 1 second.
Our webpack-test now runs in an instant :-)

fix(webpack-test): fix the 1 second slow test

---

webpack-test/jest.config.js
webpack-test/package.json

Assumptions don't hold overtime.
We added `--runInBand` to webpack-test's jest when it was flaky, it isn't anymore.
Removing `--runInBand` reduces execution time from 15s to 12s on my i7.
I also removed `coverageReporters` because we are not using any test coverages.
After running on CI:
```
PASS ./TestCasesNormal.basictest.js (32.799 s, 297 MB heap size)
PASS ./ConfigTestCases.basictest.js (5.595 s, 433 MB heap size)
```
->
```
PASS ./TestCasesNormal.basictest.js (16.218 s, 234 MB heap size)
PASS ./ConfigTestCases.basictest.js (5.581 s, 207 MB heap size)
```
CI passes.

chore: run webpack tests in parallel

---

.github/actions/docker-build/action.yml

`sccache --show-stats` sometimes makes ci fail, but the build succeeds, this pr will skip this failed operation. more error info see:
https://github.com/web-infra-dev/rspack/actions/runs/6925892459/job/18837235457?pr=4041#step:7:461

chore: skip show sccache stats

---

crates/rspack_plugin_javascript/src/dependency/esm/harmony_import_specifier_dependency.rs
crates/rspack_plugin_javascript/src/visitors/dependency/harmony_import_dependency_scanner.rs

There is a field in harmonyImportSpecifier called `call`, it should be true if the imported specifier in call_expr or tagged templates'tag.
for example:
```javascript
import { foo } from 'bar'
foo() // call=true
foo`` // call=true
new foo() // call=false (undefined in webpack
`${foo}` // call=false (undefined in webpack
```
Before:
The new expression or tagged template expression both are not correct cases for `call` to be `true`, we only checked callee before

fix(harmony-deps-scanner): should only be `dep.call=true` in call_expr or tagged template's tag

---

.github/actions/pnpm-cache/action.yml

We upgrade pnpm version from v7 to v8, but share the node_modules cache will case [some bugs](https://github.com/web-infra-dev/rspack/actions/runs/6926876033/job/18847080010?pr=4041) in self hosted runner. This PR will use the diff cache directory via pnpm version

chore: pnpm set cache dir by version

---

packages/rspack/src/Watching.ts

The default aggregateTimeout of WatchPack is `200ms`, using smaller values can improve hmr performance.
- webpack defaults to 20ms: https://github.com/webpack/webpack/blob/87660921808566ef3b8796f8df61bd79fc026108/lib/Watching.js#L53-L55
- next.js defaults to 5ms: https://github.com/vercel/next.js/blob/0a4f26f1ef26ae07131bea07e5a2058807193c65/packages/next/taskfile-watch.js#L40
Ref:
- https://github.com/webpack/watchpack/tree/dc690bbaea140820f1d9c7c2ec4dff8902798ff9#api

perf: reduce aggregateTimeout to speed up HMR

---

packages/rspack/src/config/zod.ts

The incremental rebuild is stable, so add deprecation warning for `experiments.incrementalRebuild` and will be removed in 0.5.0. More info see
https://github.com/web-infra-dev/rspack/issues/4708

feat: `experiments.incrementalRebuild` add deprecation warning

---

Cargo.lock
crates/rspack_core/Cargo.toml

Previously Package.json path returned the non-symlinked path, which breaks code splitting where it tries to resolve package_json.sideEffects.
https://github.com/oxc-project/oxc/pull/1481/files
* I ran the code where it went wrong and made sure the path returned the symlinked one.
* I also added a runtime check inside oxc_resolver to make sure all paths are correct.

fix(resolver): make sure package.json path is inside the resolved path

---

.github/workflows/reusable-build.yml

Self-hosted macOS does not have sudo permissions and comes with a macOS SDK already available.

chore: self hosted macos skip remove sdk

---

crates/rspack/tests/tree-shaking/tree-shaking-interop/snapshot/new_treeshaking.snap
crates/rspack/tests/tree-shaking/tree-shaking-interop/snapshot/output.snap
crates/rspack/tests/tree-shaking/webpack-inner-graph-export-default-named/snapshot/new_treeshaking.snap
crates/rspack/tests/tree-shaking/webpack-inner-graph-export-default-named/snapshot/output.snap
crates/rspack_core/src/dependency/runtime_template.rs
crates/rspack_plugin_runtime/src/runtime_module/runtime/compat_get_default_export.js
packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
packages/rspack/tests/cases/parsing/issue-4643/d.js
packages/rspack/tests/cases/parsing/issue-4643/e.js
packages/rspack/tests/cases/parsing/issue-4643/index.js
packages/rspack/tests/runtimeDiffCases/runtime-compat-get-default-export/src/a.js
packages/rspack/tests/runtimeDiffCases/runtime-compat-get-default-export/src/b.js
packages/rspack/tests/runtimeDiffCases/runtime-compat-get-default-export/src/index.js
packages/rspack/tests/runtimeDiffCases/runtime-compat-get-default-export/test.config.js

Re-implement of #4639 and #4607
Depend on the modified logic of is_call in branch #4729
- Add some edge cases

chore: compat get default export

---

crates/node_binding/binding.d.ts
crates/node_binding/src/hook.rs
crates/node_binding/src/plugins/mod.rs
crates/rspack_binding_values/src/codegen_result.rs
crates/rspack_binding_values/src/hooks.rs
crates/rspack_binding_values/src/lib.rs
crates/rspack_binding_values/src/module.rs
crates/rspack_core/src/code_generation_results.rs
crates/rspack_core/src/compiler/compilation.rs
crates/rspack_core/src/plugin/api.rs
crates/rspack_core/src/plugin/plugin_driver.rs
crates/rspack_testing/src/eval_raw.rs
crates/rspack_testing/src/lib.rs
packages/rspack/src/Compilation.ts
packages/rspack/src/Compiler.ts
packages/rspack/src/Module.ts

Add execute module in plugin_driver
This is pre-request for importModule

feat(plugin-driver): add execute module

---

packages/rspack-dev-server/src/server.ts
packages/rspack/package.json
pnpm-lock.yaml

`@types/webpack-dev-server` will cause two versions of webpack-dev-server to be installed. This will make ci fail https://github.com/web-infra-dev/rspack/actions/runs/6954833718/job/18922501326?pr=4743

fix: remove @types/webpack-dev-server

---

.github/actions/pnpm-cache/action.yml

self hosted runner will share pnpm global config, so we should set store-dir in project

chore: ci set pnpm store-dir in project

---

packages/create-rspack/template-react-ts/package.json
packages/create-rspack/template-react/package.json
packages/create-rspack/template-vue/package.json

Use fixed version instead of latest in template of `create-rspack`

fix: use fixed version for rspack in template

---

packages/rspack/src/Compiler.ts

make compilation.hooks.optimizeChunkModules auto disable, this bug is introduced by
https://github.com/web-infra-dev/rspack/commit/46016b6f331c6a34e2f4a7e5cf0fd555e0dde5bd#diff-5eba14dafadd5b7ee447411919692ad06f841b6b93770e131cc6b364771f68b5

perf: compilation.hooks.optimizeChunkModules auto disable

---

package.json
webpack-test/ConfigTestCases.template.js
webpack-test/configCases/async-library/0-create-library/test.filter.js
webpack-test/configCases/issues/issue-7563/test.filter.js

This PR tries to make webpack-test more future proof by catching more errors where appropriate.
`webpack-test` has the assumption where all configs are valid and everything will compile, but this is not the case with Rspack.
I also found 2 passing tests so I added to this PR.
* CI passes.

chore(webpack-test): make tests more future proof

---

crates/node_binding/binding.d.ts
crates/rspack_binding_options/src/options/raw_builtins/mod.rs
crates/rspack_binding_options/src/options/raw_optimization.rs
crates/rspack_plugin_externals/src/plugin.rs
crates/rspack_plugin_javascript/src/plugin/mod.rs
packages/rspack/src/Compiler.ts
packages/rspack/src/builtin-plugin/SplitChunksPlugin.ts
packages/rspack/src/builtin-plugin/base.ts
packages/rspack/src/builtin-plugin/index.ts
packages/rspack/src/config/adapter.ts
packages/rspack/src/rspackOptionsApply.ts
packages/rspack/tests/configCases/chunk-loading/issue-4754/child-entry.js
packages/rspack/tests/configCases/chunk-loading/issue-4754/index.js
packages/rspack/tests/configCases/chunk-loading/issue-4754/webpack.config.js

Fixes #4754
#4754 panics because it erroneously generates chunks by registering ﻿`SplitChunksPlugin` twice, while in reality, webpack only registers it once (specifically in the root compiler). As a result, it executes an additional `﻿render_chunk` operation, leading to a panic.
In this PR, I have relocated the registration of `﻿SplitChunksPlugin` to `﻿createCompiler` to ensure that it only registers once.

fix: only register `SplitChunkPlugin` once

---

.github/workflows/ci.yml
.github/workflows/release-canary.yml

canary release add windows platform and enable windows ci on main branch

chore: canary release add windows and enable windows ci on main branch

---

packages/rspack/src/config/defaults.ts
packages/rspack/src/config/zod.ts
packages/rspack/tests/Defaults.unittest.ts

see [webpack-outputuniquename](https://webpack.js.org/configuration/output/#outputuniquename)
Webpack prefers to take `output.library.name` first, and only if the user has not configured it, will it take the `name` from `package.json`.
copy by [webpack defaults config](https://github.com/webpack/webpack/blob/87660921808566ef3b8796f8df61bd79fc026108/lib/config/defaults.js#L804)
see [rspack-outputuniquename-doc](https://www.rspack.dev/config/output.html#outputuniquename) , In fact, this is how he described it.

fix uniqueName Acquisition method

---

packages/rspack/src/config/adapter.ts
packages/rspack/src/config/adapterRuleUse.ts
packages/rspack/src/loader-runner/index.ts
packages/rspack/tests/configCases/module/issue-4777/index.js
packages/rspack/tests/configCases/module/issue-4777/loader.js
packages/rspack/tests/configCases/module/issue-4777/sub/a.js
packages/rspack/tests/configCases/module/issue-4777/sub/b.js
packages/rspack/tests/configCases/module/issue-4777/sub/c.js
packages/rspack/tests/configCases/module/issue-4777/sub/d.js
packages/rspack/tests/configCases/module/issue-4777/sub/e.js
packages/rspack/tests/configCases/module/issue-4777/sub/f.js
packages/rspack/tests/configCases/module/issue-4777/sub/g.js
packages/rspack/tests/configCases/module/issue-4777/sub/h.js
packages/rspack/tests/configCases/module/issue-4777/webpack.config.js
webpack-test/configCases/loaders/issue-3320/test.filter.js

Fixes #4777 
In this PR, I have chosen to retain the original query instead of replacing it with an empty string.

fix: keep the query passed to loader

---

crates/rspack_core/src/context_module.rs
crates/rspack_plugin_javascript/src/visitors/dependency/context_helper.rs
packages/rspack/tests/cases/context/context-module-cjs-require-tagged-template/child/child/index.js
packages/rspack/tests/cases/context/context-module-cjs-require-tagged-template/child/index.js
packages/rspack/tests/cases/context/context-module-cjs-require-tagged-template/index.js
packages/rspack/tests/cases/context/context-module-dynamic-import-tagged-template/child/index.js
packages/rspack/tests/cases/context/context-module-dynamic-import-tagged-template/index.js
webpack-test/cases/parsing/complex-require/test.filter.js

resolve #4420 
Add `templateStringKind` param for `scan_context_module_tpl`, if there is no `String.raw` tag function, inner_reg will created by `templateElement.cooked`, otherwise `templateElement.raw` will be used

feat: support String.raw for context module

---

packages/rspack-plugin-react-refresh/src/index.ts

fix: use correct DefinePlugin in plugin-react-refresh

---

packages/rspack-plugin-react-refresh/client/reactRefresh.js
packages/rspack-plugin-react-refresh/client/refreshUtils.js
packages/rspack-plugin-react-refresh/package.json
packages/rspack-plugin-react-refresh/src/index.ts
pnpm-lock.yaml

Fork refreshUtils from [pmmmwh/react-refresh-webpack-plugin](https://github.com/pmmmwh/react-refresh-webpack-plugin).
Fix peer dependency warnings when create a React project, also reduce a lots of third party dependencies.
- close https://github.com/web-infra-dev/rspack/issues/4537
- close https://github.com/pmmmwh/react-refresh-webpack-plugin/pull/785
- close https://github.com/web-infra-dev/rsbuild/issues/255
Tested in Rsbuild demo project.

fix(plugin-react-refresh): fix peer warning and reduce dependencies

---

Cargo.lock
crates/rspack_core/Cargo.toml
packages/rspack/tests/cases/resolve/query/index.js
packages/rspack/tests/cases/resolve/query/测试.js

closes #4630
Source: https://github.com/oxc-project/oxc/pull/1591
I have:
* added integration test in rspack tests
* added integration test on the oxc side
* verified this manually on https://github.com/h-a-n-a/issue_1130_rspack_new_resolver

fix(resolver): resolve query and fragments with unicode filenames

---

crates/node_binding/binding.d.ts
crates/rspack_binding_values/src/asset.rs
packages/rspack/src/util/index.ts

The `version` field in JsAsset is used to control whether emit the asset, but it is not aligned with webpack

feat: JsAsset remove version field

---

.github/actions/download-artifact/action.yml
.github/actions/upload-artifact/action.yml
.github/workflows/diff.yml
.github/workflows/reusable-build.yml

Use github.sha to generate self-hosted runner local cache path, and then the artifacts can be shared between workflows

ci: speed up diff ci

---

crates/rspack_core/src/dependencies_block.rs
crates/rspack_core/src/dependency/runtime_template.rs
crates/rspack_plugin_javascript/Cargo.toml
crates/rspack_plugin_javascript/src/dependency/commonjs/common_js_require_dependency.rs
crates/rspack_plugin_javascript/src/dependency/commonjs/mod.rs
crates/rspack_plugin_javascript/src/dependency/commonjs/require_header_dependency.rs
crates/rspack_plugin_javascript/src/lib.rs
crates/rspack_plugin_javascript/src/utils/basic_evaluated_expression.rs
crates/rspack_plugin_javascript/src/utils/mod.rs
crates/rspack_plugin_javascript/src/visitors/dependency/common_js_import_dependency_scanner.rs
packages/rspack/tests/Stats.test.ts
packages/rspack/tests/__snapshots__/Stats.test.ts.snap
packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
packages/rspack/tests/cases/parsing/issue-4816/a.js
packages/rspack/tests/cases/parsing/issue-4816/b.js
packages/rspack/tests/cases/parsing/issue-4816/index.js

Fixes #4816
Related to #4424
This PR introduces ﻿`BasicEvaluatedExpression` which is utilized to process expressions during js parsing.

refactor: use `BasicEvaluatedExpression`

---

Cargo.lock
crates/node_binding/binding.d.ts
crates/rspack_binding_values/Cargo.toml
crates/rspack_binding_values/src/chunk.rs
packages/rspack/src/Chunk.ts
packages/rspack/src/ChunkGraph.ts
packages/rspack/src/Compilation.ts
packages/rspack/tests/configCases/plugins/chunk-modules/async.js
packages/rspack/tests/configCases/plugins/chunk-modules/index.js
packages/rspack/tests/configCases/plugins/chunk-modules/webpack.config.js

#4809 is caused by rspack being lack of ChunkGraph-related apis.
this pr simply implements one of such apis - `chunks.modulesIterable` - that is used by `LicenseWebpackPlugin`.
1. Run `webpack --config rspack.config.js` (without configuration that causes errors) on `examples/plugin-compat/`  and `examples/plugin-compat/dist/3rdpartylicenses.txt` should be produced.
2. Run `rspack build` on `examples/plugin-compat/` (with same configuration as case 1) and a same `3rdpartylicenses.txt` should be produced.

feat: implement `ChunkGraph.getChunkModulesIterable` and `ChunkGraph.getChunkEntryModulesIterable`

---

packages/create-rspack/template-react-ts/rspack.config.js
packages/create-rspack/template-react/rspack.config.js

Under the current template, the production environment build will use the refreshPlugin, resulting in an error when directly opening the index.html.

fix: production environment refreshPlugin error

---

packages/rspack/src/config/adapter.ts
packages/rspack/src/config/zod.ts
packages/rspack/tests/configCases/split-chunks-common/default/index.js
packages/rspack/tests/configCases/split-chunks-common/default/test.config.js
packages/rspack/tests/configCases/split-chunks-common/default/webpack.config.js
packages/rspack/tests/configCases/split-chunks-common/disable/index.js
packages/rspack/tests/configCases/split-chunks-common/disable/test.config.js
packages/rspack/tests/configCases/split-chunks-common/disable/webpack.config.js

rspack disables SplitChunksPlugin when `optimization.splitChunks` is `false` which is of same behavior as webpack excepting rspack's options validation prints an error for it.
it is not documented on webpack's doc but allowed by webpack.
schema: https://github.com/webpack/webpack/blob/87660921808566ef3b8796f8df61bd79fc026108/schemas/WebpackOptions.json#L2560
- `optimization.splitChunks = undefined`: configCases/split-chunks-common/default
-  `optimization.splitChunks = false`: configCases/split-chunks-common/disable

feat: align webpack - allow `false` for `optimization.splitChunks` on options validation

---

packages/rspack-plugin-html/README.md

since we're compatible with html-webpack-plugin, deprecate @rspack/plugin-html，
but I'm not sure whether html-webpack-plugin will break rspack in the future.
No Need

chore: deprecate @rspack/plugin-html

---

crates/rspack_plugin_javascript/src/visitors/dependency/common_js_export_scanner.rs
packages/rspack/tests/cases/parsing/harmony-commonjs-mix-decorator/bbb.js
packages/rspack/tests/cases/parsing/harmony-commonjs-mix-decorator/cjs.js
packages/rspack/tests/cases/parsing/harmony-commonjs-mix-decorator/cjs1.js
packages/rspack/tests/cases/parsing/harmony-commonjs-mix-decorator/cjs2.js
packages/rspack/tests/cases/parsing/harmony-commonjs-mix-decorator/cjs3.js
packages/rspack/tests/cases/parsing/harmony-commonjs-mix-decorator/cjs4.js
packages/rspack/tests/cases/parsing/harmony-commonjs-mix-decorator/cjs5.js
packages/rspack/tests/cases/parsing/harmony-commonjs-mix-decorator/esm1.js
packages/rspack/tests/cases/parsing/harmony-commonjs-mix-decorator/esm2.js
packages/rspack/tests/cases/parsing/harmony-commonjs-mix-decorator/esm3.js
packages/rspack/tests/cases/parsing/harmony-commonjs-mix-decorator/esm4.js
packages/rspack/tests/cases/parsing/harmony-commonjs-mix-decorator/esm5.js
packages/rspack/tests/cases/parsing/harmony-commonjs-mix-decorator/esm6.js
packages/rspack/tests/cases/parsing/harmony-commonjs-mix-decorator/index.js

Fix commonjs exports scanner to generate ModuleDecoratorDependency correctly
Adding `packages/rspack/tests/cases/parsing/harmony-commonjs-mix-decorator` to check:
- HarmonyModuleDecorator should be append correctly
- NodeModuleDecorator should be append correctly
1. Use `module.children` to check module has been decorated
2. If harmony mixed, assigning to `module.exports` will throw an error

fix: module decorator when harmony mixed

---

crates/rspack_plugin_runtime/src/runtime_module/runtime/harmony_module_decorator.js
crates/rspack_plugin_runtime/src/runtime_module/runtime/node_module_decorator.js
packages/rspack/tests/runtimeDiffCases/runtime-harmony-module-decorator/src/aaa.js
packages/rspack/tests/runtimeDiffCases/runtime-harmony-module-decorator/src/bbb.js
packages/rspack/tests/runtimeDiffCases/runtime-harmony-module-decorator/src/index.js
packages/rspack/tests/runtimeDiffCases/runtime-harmony-module-decorator/test.config.js
packages/rspack/tests/runtimeDiffCases/runtime-node-module-decorator/src/aaa.js
packages/rspack/tests/runtimeDiffCases/runtime-node-module-decorator/src/bbb.js
packages/rspack/tests/runtimeDiffCases/runtime-node-module-decorator/src/index.js
packages/rspack/tests/runtimeDiffCases/runtime-node-module-decorator/test.config.js

Depend on #4900 
Align module decorator runtime with webpack
- HarmonyModuleDecoratorRuntimeModule
- NodeModuleDecoratorRuntimeModule
- Test cases in `packages/rspack/tests/runtimeDiffCases`

chore(runtime-diff): align module decorator runtime modules with webpack

---

packages/rspack-cli/tsconfig.json
packages/rspack-dev-server/src/server.ts
packages/rspack-dev-server/tsconfig.json

This issue is part of https://github.com/web-infra-dev/rspack/issues/4640

chore: remove all skipLibCheck

---

packages/rspack/tests/ConfigCase.template.ts
packages/rspack/tests/HotTestCases.template.ts
packages/rspack/tests/RuntimeDiff.diff.test.ts
packages/rspack/tests/StatsTestCases.test.ts
packages/rspack/tests/WatchTestCases.template.ts
packages/rspack/tests/case.template.ts
packages/rspack/tests/utils.ts

Add filter to directories of test cases which can not start with `.`
Noop

test: prevent .DS_store been add to test cases on macos

---

packages/rspack-plugin-node-polyfill/README.md

we're compatible with node-polyfill-webpack-plugin@3.0 now

chore: deprecate @rspack/plugin-node-polyfill

---

crates/node_binding/src/panic.rs
crates/rspack_core/src/compiler/mod.rs
crates/rspack_core/src/debug_info.rs
crates/rspack_core/src/lib.rs

Print debug info with additional information when program panics.

chore: add debug info under panic with debug build

---

crates/rspack/tests/fixtures.rs
crates/rspack_plugin_javascript/src/utils/mangle_exports.rs

fix:  should return number.to_string instead of char::from

---

Cargo.lock
crates/rspack_core/src/tree_shaking/optimizer.rs
crates/rspack_error/Cargo.toml
crates/rspack_error/src/diagnostic.rs
crates/rspack_error/src/error.rs
crates/rspack_error/src/lib.rs
crates/rspack_error/src/macros.rs
crates/rspack_loader_sass/src/lib.rs
crates/rspack_plugin_ensure_chunk_conditions/src/lib.rs

This chain of PRs are intended to solve problems related to errors/diagnostics as follows.
`InternalErrors` are abusively used across rspack crates. However these errors
should provide more useful **context**. See: https://github.com/web-infra-dev/rspack/issues/4613, https://github.com/web-infra-dev/rspack/issues/4321.
`Diagnostics` in rspack is represented by another custom type
to be fed to `codespan-reporting` in reporting. This indicates that errors
should be converted in the first place in order to be consumed by `Stats`.
In the following PRs, the essential idea to solve the problems are as follows:
1. `miette` and `thiserror`: This pair of libraries can either make fancy diagnostics and create easy to read errors. `GraphicalReportHandler` of `miette` can be helpful to directly print …

refactor: error and diagnostics

---

diffcases/arco-pro/rspack.config.js
diffcases/arco-pro/webpack.config.js
packages/rspack-test-tools/src/compare/compare.ts
packages/rspack-test-tools/src/compare/format-code.ts
packages/rspack-test-tools/src/compare/replace-module-argument.ts
packages/rspack-test-tools/src/processor/diff.ts
packages/rspack-test-tools/src/reporter/diff-html.ts
packages/rspack-test-tools/src/webpack/module-placeholder-plugin.ts
packages/rspack-test-tools/viewer/pages/diff-report.tsx
packages/rspack-test-tools/viewer/templates/diff.html
packages/rspack-test-tools/viewer/utils/generateTreeData.tsx
packages/rspack/tests/RuntimeDiff.diff.test.ts
scripts/diff.cjs

1. Modify diff cases
- Remove react refresh plugin
- Use prod mode
- Use experiments css 
2. Transform generated code of diff case to prevent unnecessary diff lines
- Add `ignoreBlockOnlyStatement` to prevent differences caused by single-statement blocks
- Add `ignoreSwcHelpersPath` to prevent differences caused by injecting @swc/helpers
- Add `ignoreObjectPropertySequence` to prevent differences caused by sequence of object properties
- Add `ignoreCssFilePath` to prevent differences caused by webpack css local idents

chore: optimize diff test case

---

crates/rspack/tests/fixtures.rs
crates/rspack_core/src/build_chunk_graph/code_splitter.rs
crates/rspack_core/src/compiler/hmr.rs
crates/rspack_core/src/compiler/mod.rs
crates/rspack_core/src/lib.rs
crates/rspack_core/src/module_graph/mod.rs

Remove static new_treeshaking switch because when run tests, this can be affected by other test cases

fix: remove static new_treeshaking switch

---

crates/rspack_core/src/chunk_group.rs
crates/rspack_core/src/compiler/compilation.rs
crates/rspack_core/src/compiler/hmr.rs
crates/rspack_core/src/module_graph/mod.rs
crates/rspack_core/src/options/output.rs
crates/rspack_plugin_javascript/src/visitors/dependency/import_scanner.rs
packages/playground/cases/chunk/issue-4936/index.test.ts
packages/playground/cases/chunk/issue-4936/rspack.config.js
packages/playground/cases/chunk/issue-4936/src/app.js
packages/playground/cases/chunk/issue-4936/src/index.js
packages/playground/cases/html/issue-4366/index.test.ts

Fixes #4936 
In this PR, I have added ﻿`group_options` because merely comparing the module identifier is not sufficient for caching.

fix: compare blocks and its group_options

---

crates/node_binding/src/plugins/mod.rs
crates/rspack_ast/src/lib.rs
crates/rspack_binding_options/src/options/raw_builtins/raw_banner.rs
crates/rspack_binding_options/src/options/raw_external.rs
crates/rspack_binding_options/src/options/raw_module/js_loader.rs
crates/rspack_binding_options/src/options/raw_module/mod.rs
crates/rspack_binding_options/src/options/raw_split_chunks/raw_split_chunk_cache_group_test.rs
crates/rspack_binding_options/src/options/raw_split_chunks/raw_split_chunk_name.rs
crates/rspack_core/src/code_generation_results.rs
crates/rspack_core/src/context_module.rs
crates/rspack_core/src/module_graph/mod.rs
crates/rspack_core/src/module_graph_module.rs
crates/rspack_loader_react_refresh/src/lib.rs
crates/rspack_loader_runner/src/runner.rs
crates/rspack_loader_sass/src/lib.rs
crates/rspack_loader_swc/src/lib.rs
crates/rspack_plugin_asset/src/lib.rs
crates/rspack_plugin_css/src/parser_and_generator/mod.rs
crates/rspack_plugin_css/src/plugin/impl_plugin_for_css_plugin.rs
crates/rspack_plugin_css/src/swc_css_compiler.rs
crates/rspack_plugin_devtool/src/lib.rs
crates/rspack_plugin_javascript/src/ast/stringify.rs
crates/rspack_plugin_javascript/src/parser_and_generator/mod.rs
crates/rspack_plugin_javascript/src/runtime.rs
crates/rspack_plugin_json/src/lib.rs
crates/rspack_plugin_mf/src/sharing/consume_shared_runtime_module.rs
crates/rspack_plugin_mf/src/sharing/share_runtime_module.rs
crates/rspack_plugin_runtime/src/module_chunk_format.rs
crates/rspack_plugin_swc_js_minimizer/src/lib.rs
crates/rspack_plugin_wasm/src/wasm_plugin.rs

Adjust some of expectations with the philosophy of https://github.com/web-infra-dev/rspack/pull/4848:
1. NAPI should panic if failed to call
2. Assume every source-map emitted from SWC are valid source-maps.
3. Some minor changes
as-is.

refactor: should not always rely on `Result`

---

packages/rspack/src/builtin-plugin/index.ts
packages/rspack/src/config/defaults.ts
packages/rspack/tests/__snapshots__/Defaults.unittest.ts.snap
packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
packages/rspack/tests/configCases/plugins/minify-disabled-on-empty-array/index.css
packages/rspack/tests/configCases/plugins/minify-disabled-on-empty-array/index.js
packages/rspack/tests/configCases/plugins/minify-disabled-on-empty-array/webpack.config.js

fix(@rspack/core): minify should be disabled when minimizer is an empty array

---

examples/arco-pro/rspack.config.js

It currently takes 200s for arco-pro to build in CI.
On my local machine, turning off sourcemap results in 20s -> 13s and 1.1G max rss -> 700MB.
* CI passes and arco-pro build time decreases.

ci: speed up CI by turning off sourcemap for arco-pro

---

crates/node_binding/binding.d.ts
crates/rspack_binding_options/src/options/raw_builtins/mod.rs
packages/rspack/src/Compiler.ts
packages/rspack/src/builtin-plugin/SplitChunksPlugin.ts
packages/rspack/src/builtin-plugin/SwcJsMinimizerPlugin.ts
packages/rspack/src/builtin-plugin/base.ts
packages/rspack/tests/configCases/plugins/issue-4982/child.js
packages/rspack/tests/configCases/plugins/issue-4982/index.js
packages/rspack/tests/configCases/plugins/issue-4982/webpack.config.js

Fixes #4982 
webpack can utilize `this.hooks[name].taps.slice()` to enable the `childCompiler` to inherit these plugins from webpack. However, we can't do the same.
Therefore, we're adding this plugin to ensure these plugins function properly.

fix: append builtin minify plugin for child compiler

---

crates/rspack_plugin_javascript/src/parser_and_generator/mod.rs
crates/rspack_plugin_javascript/src/plugin/inner_graph_plugin.rs
crates/rspack_plugin_javascript/src/plugin/side_effects_flag_plugin.rs
packages/rspack/tests/configCases/tree-shaking/inner-graph-static-block/a.js
packages/rspack/tests/configCases/tree-shaking/inner-graph-static-block/index.js
packages/rspack/tests/configCases/tree-shaking/inner-graph-static-block/lib.js
packages/rspack/tests/configCases/tree-shaking/inner-graph-static-block/webpack.config.js

1. fix inner graph to detect class member effects, should not add PureExpressionDep on `staticBlock`
1. added a unit test under packages/rspack

fix: 🐛 class memeber side effects

---

crates/rspack_core/src/runtime_globals.rs
crates/rspack_plugin_javascript/src/visitors/dependency/api_scanner.rs
crates/rspack_plugin_runtime/src/runtime_module/chunk_name.rs
crates/rspack_plugin_runtime/src/runtime_module/mod.rs
crates/rspack_plugin_runtime/src/runtime_plugin.rs
webpack-test/configCases/parsing/extended-api/test.filter.js

Align `__webpack_chunkname__` and ChunkNameRuntimeModule with webpack
- Reuse `webpack-test/configCases/parsing/extended-api` 
- [] No

feat(runtime): support __webpack_chunkname__

---

crates/rspack_plugin_runtime/src/runtime_plugin.rs

Add `RuntimeGlobals::Require` when use property on it

fix(runtime): globals on require in runtime plugin

---

crates/rspack_plugin_runtime/src/runtime_module/css_loading.rs
crates/rspack_plugin_runtime/src/runtime_module/import_scripts_chunk_loading.rs
crates/rspack_plugin_runtime/src/runtime_module/jsonp_chunk_loading.rs
crates/rspack_plugin_runtime/src/runtime_module/module_chunk_loading.rs
crates/rspack_plugin_runtime/src/runtime_module/readfile_chunk_loading.rs
crates/rspack_plugin_runtime/src/runtime_module/require_js_chunk_loading.rs
crates/rspack_plugin_runtime/src/runtime_module/runtime/module_chunk_loading.js
crates/rspack_plugin_runtime/src/runtime_module/runtime/module_chunk_loading_with_loading.js
crates/rspack_plugin_runtime/src/runtime_module/utils.rs
packages/rspack/tests/runtimeDiffCases/runtime-module-chunk-loading/rspack.config.js
packages/rspack/tests/runtimeDiffCases/runtime-module-chunk-loading/src/a.js
packages/rspack/tests/runtimeDiffCases/runtime-module-chunk-loading/src/b.js
packages/rspack/tests/runtimeDiffCases/runtime-module-chunk-loading/test.config.js
packages/rspack/tests/runtimeDiffCases/runtime-module-chunk-loading/webpack.config.js

Align module chunk loading runtime module with webpack. 
> Do not align whole logic of function `itemsToRegexp`
- Reuse `packages/rspack/tests/configCases/output-module/simple` to test BooleanMatcher::Condition(true) 
- Reuse `packages/rspack/tests/configCases/output-module/single-runtime` to test BooleanMatcher::Matcher(String) 
Should add more test cases for module federation, because it will add more chunks to entrypoint chunk group.

chore(runtime-diff): module chunk loading runtime module

---

crates/rspack_plugin_javascript/src/utils/const/logic_expr.rs
crates/rspack_plugin_javascript/src/visitors/dependency/common_js_import_dependency_scanner.rs
packages/rspack/tests/cases/parsing/issue-4816/index.js

Fixes #4997 
Parsing of left and right expressions should continue even if the evaluation of the logical expression fails.

fix: parse left and right when eval failed for logic expr

---

crates/rspack_plugin_javascript/src/parser_plugin/drive.rs
crates/rspack_plugin_javascript/src/parser_plugin/trait.rs
crates/rspack_plugin_javascript/src/utils/eval/eval_array_expr.rs
crates/rspack_plugin_javascript/src/utils/eval/eval_binary_expr.rs
crates/rspack_plugin_javascript/src/utils/eval/mod.rs
crates/rspack_plugin_javascript/src/utils/mod.rs
crates/rspack_plugin_javascript/src/visitors/dependency/common_js_import_dependency_scanner.rs
packages/rspack/tests/cases/parsing/issue-4816/index.js

Related to #4424 
Now, we can use `[] != [] || require("fail")`

feat: support eval abstract equal

---

packages/rspack/src/config/zod.ts

Fixing https://github.com/web-infra-dev/rspack/issues/5022
When specifying the symlinks option in resolve section a config validation error is thrown Unrecognized key(s) in object: 'symlinks' at "resolve"
- Added `resolve.symlinks` to basic example and ran the build. No error thrown or warning printed
- Ran the test suite
I don't think any new tests need to be written for this case?

fix: add "symlinks" option to resolve config validation

---

crates/rspack_core/src/build_chunk_graph/code_splitter.rs

When removing parent modules, filter runtime chunk properly

fix(remove-parent-modules): only filter runtime chunk

---

crates/rspack/tests/samples/remove-parent-modules/ancestor-has-all-modules/foo.js
crates/rspack/tests/samples/remove-parent-modules/ancestor-has-all-modules/index.js
crates/rspack/tests/samples/remove-parent-modules/ancestor-has-all-modules/parent-1.js
crates/rspack/tests/samples/remove-parent-modules/ancestor-has-all-modules/parent-2.js
crates/rspack/tests/samples/remove-parent-modules/ancestor-has-all-modules/shared.js
crates/rspack/tests/samples/remove-parent-modules/ancestor-has-all-modules/snapshot/output.snap
crates/rspack/tests/samples/remove-parent-modules/ancestor-has-all-modules/test.config.json
crates/rspack_core/src/build_chunk_graph/remove_parent_modules.rs

Giving chunk group relations as following:
```
A
|  \
B  C
|  /
D
```
Remove availableModules can remove modules from parents and ancestor, we have this logic before, but for some reason it didn't work properly, this is a fix for this

fix: remove available modules from ancestor

---

Cargo.lock
crates/rspack_core/Cargo.toml

Closes #5039
PRs: 
* https://github.com/oxc-project/oxc_resolver/pull/34
* https://github.com/oxc-project/oxc_resolver/pull/36
The browser field has no formal specification so all behaviors need to follow enhanced-resolve.
* I've added all relevant tests in oxc_resolver
* Manually tested the canary version for [this repro](https://github.com/web-infra-dev/rspack/issues/5039#issuecomment-1859028977) as well as `@wangeditor/editor-for-vue`

chore(rspack_core): oxc_resolver v0.6.2

---

crates/rspack_binding_options/src/options/raw_module/js_loader.rs
crates/rspack_core/src/compiler/queue.rs
crates/rspack_core/src/context_module.rs
crates/rspack_core/src/external_module.rs
crates/rspack_core/src/loader/loader_runner.rs
crates/rspack_core/src/missing_module.rs
crates/rspack_core/src/module.rs
crates/rspack_core/src/module_graph/mod.rs
crates/rspack_core/src/normal_module.rs
crates/rspack_core/src/raw_module.rs
crates/rspack_core/src/runtime_module.rs
crates/rspack_error/src/diagnostic.rs
crates/rspack_loader_sass/tests/fixtures.rs
crates/rspack_loader_swc/tests/fixtures.rs
crates/rspack_plugin_mf/src/container/container_entry_module.rs
crates/rspack_plugin_mf/src/container/fallback_module.rs
crates/rspack_plugin_mf/src/container/remote_module.rs
crates/rspack_plugin_mf/src/sharing/consume_shared_module.rs
crates/rspack_plugin_mf/src/sharing/provide_shared_module.rs
crates/rspack_plugin_runtime/src/lazy_compilation.rs
x.mjs

Aligns Rspack's module error with Webpack's.
Added trait `Diagnosable` for diagnostics.
See [how webpack did this](https://github.com/webpack/webpack/blob/6be4065ade1e252c1d8dcba4af0f43e32af1bdc1/lib/Module.js#L583)

refactor: diagnosable modules

---

crates/rspack_binding_values/src/compilation.rs
crates/rspack_core/src/compiler/compilation.rs
crates/rspack_core/src/normal_module.rs
crates/rspack_core/src/stats.rs
crates/rspack_error/src/diagnostic.rs
crates/rspack_error/src/emitter.rs
packages/rspack/tests/Compiler.test.ts
packages/rspack/tests/Errors.test.ts
packages/rspack/tests/Stats.test.ts
packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
webpack-test/configCases/plugins/environment-plugin/errors-sort.js

Rspack and webpack both have different errors for module.
This PR replaced the error for `message` of `StatsError` with `miette::Diagnostic` to make error more likely as Webpack's.
The example below show the difference between Webpack and Rspack's `ModuleParseError`. Currently, Rspack does not implement fine-grained error. This will be improved one by one.
Rspack:
Webpack:
See snapshot changes.

feat: diagnostics in overlay

---

crates/rspack_core/src/compiler/compilation.rs

This PR remove some useless `tracing::instrument` to avoid OOM when use trace.

fix: OOM when use trace

---

crates/rspack_plugin_javascript/src/runtime.rs
crates/rspack_plugin_runtime/src/runtime_module/css_loading.rs

Avoid importing runtime code from `css_loading_with_loading.js` when no CSS files are imported.
The relevant code lines in the webpack can be found here: https://github.com/webpack/webpack/blob/main/lib/css/CssLoadingRuntimeModule.js#L87

fix: unnecessary import runtime code from css_loading_with_loading.js

---

packages/rspack/src/rspack.ts

closes #4996
Saves 80ms.
Do people use this debug? I don't think it's documented anywhere.

chore: remove heavy debug node `util.inspect` call

---

.github/workflows/ci.yml
scripts/alert/lark.js

send notification to `Lark` when main branch ci failed

chore: send notification when main branch ci failed

---

package.json
packages/rspack/src/util/index.ts
pnpm-lock.yaml

removes all deprecate warning in CI
https://github.com/web-infra-dev/rspack/issues/5067
watch CI info

feat: removes all deprecate warning in CI

---

crates/rspack_plugin_library/src/module_library_plugin.rs
packages/rspack/tests/configCases/output-module/issue-4784/index.js
packages/rspack/tests/configCases/output-module/issue-4784/m.js
packages/rspack/tests/configCases/output-module/issue-4784/test.config.js
packages/rspack/tests/configCases/output-module/issue-4784/webpack.config.js
webpack-test/configCases/container/0-container-full/test.filter.js
webpack-test/configCases/container/1-container-full/test.filter.js
webpack-test/configCases/container/3-container-full/test.filter.js
webpack-test/configCases/container/module-federation-with-shareScope/test.filter.js

fix: library module renderStartup missing export

---

crates/rspack_plugin_runtime/src/runtime_module/utils.rs
packages/rspack/tests/configCases/chunk-loading/chunk-name/a.js
packages/rspack/tests/configCases/chunk-loading/chunk-name/index.js
packages/rspack/tests/configCases/chunk-loading/chunk-name/test.config.js
packages/rspack/tests/configCases/chunk-loading/chunk-name/webpack.config.js

Fix artifact problem on case:
https://github.com/web-infra-dev/rspack/blob/a5e489842cdd0f4599757f8ae868a9a6154cfad0/packages/rspack/tests/configCases/chunk-loading/chunk-name/webpack.config.js
```markdown
* Feature Related: Chunk Loading
* Case: There's `\\u`, `\\x` or `"` in chunk name
```
The artifact would contain code like `var installedChunks = {"aa\uaaa\xaaa"aaa": 0,};` that is invalid.
```markdown
* OS: Windows
* Setup: html-webpack-plugin@5.6.0
* Edge situation:  There's any path component starting with `u` or `x`
```
Error sample:
```
start   Compiling...
error   Compile error: 
Failed to compile, check the errors for troubleshooting.
SyntaxError
× [html-rspack-plugin]: Invalid Unicode escape sequence
│ C:\userCode\23-2-2\vue-app6\node_modules\@rsbuild\core\static\template.html:74 …
```

fix(plugin-runtime): `stringify_chunk` should escape special chars in chunk names as js\'s JSON.stringify do

---

packages/rspack/src/util/index.ts

Partially reverts: https://github.com/web-infra-dev/rspack/pull/5127
Keep `@types/is-ci` in `@rspack/core`

revert: removes all deprecate warning in CI by github CI

---

crates/rspack_core/src/chunk_group.rs
crates/rspack_core/src/compiler/compilation.rs
crates/rspack_plugin_entry/src/lib.rs
crates/rspack_plugin_mf/src/container/container_plugin.rs
packages/rspack/tests/configCases/container/.2-container-full/webpack.config.js
packages/rspack/tests/configCases/container/0-container-full/webpack.config.js
packages/rspack/tests/configCases/container/1-container-full/webpack.config.js
webpack-test/ConfigTestCases.template.js
webpack-test/configCases/container/2-container-full/test.filter.js

enable `webpack-test/configCases/container/2-container-full`

fix: entryOptions should able to merge

---

crates/rspack_core/src/module_graph/connection.rs

When one connection state is false should return the other, align [webpack](https://github.com/webpack/webpack/blob/87660921808566ef3b8796f8df61bd79fc026108/lib/ModuleGraphConnection.js#L29-L36)

fix(treeshaking): calculate add_connection_states right

---

crates/rspack_core/src/exports_info.rs
crates/rspack_plugin_javascript/src/plugin/flag_dependency_exports_plugin.rs

1. Using exports/export id to workaround rustc borrow rules instead clone them.

refactor: 🤖 avoid clone exports info

---

crates/rspack_core/src/compiler/compilation.rs
crates/rspack_core/src/stats.rs

diagnostics tests should be stable.

fix: sort errors and warnings in stats based on offsets

---

crates/rspack_plugin_javascript/src/visitors/dependency/import_meta_scanner.rs
crates/rspack_plugin_javascript/src/visitors/dependency/util.rs
packages/rspack/tests/cases/esm/import-meta-property/index.js

`import.meta.url.length` should not be transform to `undefined`
- Add `packages/rspack/tests/cases/esm/import-meta-property`

fix: import meta url property

---

crates/rspack_core/src/external_module.rs
packages/rspack/tests/configCases/library/esm-external/index.js
packages/rspack/tests/configCases/library/esm-external/webpack.config.js

External modules should also be exports in esm
Add `packages/rspack/tests/configCases/library/esm-external`

fix: external modules in esm

---

crates/rspack_core/src/compiler/compilation.rs
crates/rspack_core/src/compiler/queue.rs
crates/rspack_core/src/context_module_factory.rs
crates/rspack_core/src/module_factory.rs
crates/rspack_core/src/normal_module_factory.rs
examples/basic/src/index.js

Aligns the behavior with webpack. So that rspack can watch missing dependencies, etc.
When `options.bail` is enabled, then rspack does nothing.
Test blocked by https://github.com/web-infra-dev/rspack/pull/5152

fix: should store dependencies even if module factorization is failed

---

Cargo.lock
Cargo.toml

Fixes #5149 
edit: `tracing` had support `NO_COLOR` in https://github.com/tokio-rs/tracing/commit/81ab9d6faedaf5a1e4b9d69567949052a401e723, we can use it directly.
~~This PR introduces the `﻿RSPACK_LOG_COLOR` environment variable, which can have one of three values: `﻿always`, `﻿never`, or `﻿auto`:~~
~~- `﻿always`: Always displays colors, both in the terminal and when writing to files.~~
~~- `﻿never`: Never displays colors.~~
~~- `auto (default)`: Displays colors in the terminal but not when writing to files.~~
~~Here's a comparison before and after applying the `﻿RSPACK_PROFILE=TRACE=layer=logger npx rspack build > log.log` command:~~

feat: bump tracing to support `NO_COLOR`

---

crates/rspack_plugin_javascript/src/dependency/commonjs/common_js_self_reference_dependency.rs
crates/rspack_plugin_javascript/src/visitors/dependency/common_js_export_scanner.rs
packages/rspack/tests/cases/cjs-tree-shaking/complex-member/assign-exports.js
packages/rspack/tests/cases/cjs-tree-shaking/complex-member/assign-module-exports.js
packages/rspack/tests/cases/cjs-tree-shaking/complex-member/assign-this.js
packages/rspack/tests/cases/cjs-tree-shaking/complex-member/index.js
packages/rspack/tests/cases/cjs-tree-shaking/complex-member/self-exports.js
packages/rspack/tests/cases/cjs-tree-shaking/complex-member/self-module-exports.js
packages/rspack/tests/cases/cjs-tree-shaking/complex-member/self-this.js

- Compatible with empty names of CommonJsSelfReferenceDependency
- Fix commonjs export scanner to compatible complex member expression
- Add `packages/rspack/tests/cases/cjs-tree-shaking/complex-member`

fix: empty name and complex member expression in cjs dependency

---

crates/rspack_plugin_javascript/src/lib.rs
crates/rspack_plugin_javascript/src/visitors/dependency/import_scanner.rs
crates/rspack_plugin_javascript/src/webpack_comment.rs
pnpm-lock.yaml
webpack-test/configCases/parsing/import-ignore/test.filter.js

Fixes #3513
Supports the `﻿webpackIgnore` comment in import statements. However, handling import statements with templates and required calls still need improvement.

feat: support `webpackIgnore` comment

---

package.json

build rspack/core first to avoid typescript multiple compiler error. more info see https://github.com/web-infra-dev/rspack/issues/5173

chore: build rspack/core first

---

crates/rspack_plugin_javascript/src/utils/const/if_stmt.rs
crates/rspack_plugin_javascript/src/utils/eval/eval_array_expr.rs
crates/rspack_plugin_javascript/src/utils/eval/eval_binary_expr.rs
crates/rspack_plugin_javascript/src/utils/eval/eval_cond_expr.rs
crates/rspack_plugin_javascript/src/utils/eval/eval_new_expr.rs
crates/rspack_plugin_javascript/src/utils/eval/eval_tpl_expr.rs
crates/rspack_plugin_javascript/src/utils/eval/eval_unary_expr.rs
crates/rspack_plugin_javascript/src/visitors/dependency/api_scanner.rs
crates/rspack_plugin_javascript/src/visitors/dependency/common_js_export_scanner.rs
crates/rspack_plugin_javascript/src/visitors/dependency/common_js_import_dependency_scanner.rs
crates/rspack_plugin_javascript/src/visitors/dependency/common_js_scanner.rs
crates/rspack_plugin_javascript/src/visitors/dependency/compatibility_scanner.rs
crates/rspack_plugin_javascript/src/visitors/dependency/export_info_api_scanner.rs
crates/rspack_plugin_javascript/src/visitors/dependency/harmony_detection_scanner.rs
crates/rspack_plugin_javascript/src/visitors/dependency/harmony_export_dependency_scanner.rs
crates/rspack_plugin_javascript/src/visitors/dependency/harmony_import_dependency_scanner.rs
crates/rspack_plugin_javascript/src/visitors/dependency/harmony_top_level_this.rs
crates/rspack_plugin_javascript/src/visitors/dependency/hot_module_replacement_scanner.rs
crates/rspack_plugin_javascript/src/visitors/dependency/import_meta_scanner.rs
crates/rspack_plugin_javascript/src/visitors/dependency/import_scanner.rs
crates/rspack_plugin_javascript/src/visitors/dependency/mod.rs
crates/rspack_plugin_javascript/src/visitors/dependency/node_stuff_scanner.rs
crates/rspack_plugin_javascript/src/visitors/dependency/url_scanner.rs
crates/rspack_plugin_javascript/src/visitors/dependency/util.rs
crates/rspack_plugin_javascript/src/visitors/dependency/worker_scanner.rs
packages/rspack/tests/cases/parsing/remove-dependency/index.js

Fix code generation error when code removed by compile time evaluation
```js
// source
if (typeof require !== 'function' /* always false */) {
__webpack_hash__
}
// before
if (false /* always false */ ) __webpack_require__.h(){}
// after
if (false /* always false */ ) {}
```
Due to the lack of parser hooks, scanners will not be stopped even when the statements had been removed. So dependencies will be generated and trigger DependencyTemplate.apply as well. The code will be insert and cause runtime error.
- Add `packages/rspack/tests/cases/parsing/remove-dependency`

fix: do not generate dependency after removing

---

crates/rspack_plugin_javascript/src/utils/const/logic_expr.rs
crates/rspack_plugin_javascript/src/utils/eval/mod.rs
packages/rspack/tests/cases/parsing/issue-4816/index.js
pnpm-lock.yaml

related to #4907 
support eval `nullish` operation in `ConstPlugin`

feat: support eval nullish in const plugin

---

crates/rspack_core/src/build_chunk_graph/code_splitter.rs
webpack-test/configCases/chunk-graph/issue-9634/test.filter.js

Since we don't have any dependency that match the ConnectionState::TransitiveOnly, I will add tests about this after #5072

feat: skip transitiveonly dependencies and enable more test

---

Cargo.lock
crates/node_binding/binding.d.ts
crates/rspack_binding_options/src/options/raw_experiments.rs
crates/rspack_binding_options/src/options/raw_resolve.rs
crates/rspack_core/Cargo.toml
crates/rspack_core/src/compiler/mod.rs
crates/rspack_core/src/options/experiments.rs
crates/rspack_core/src/options/resolve/clever_merge.rs
crates/rspack_core/src/options/resolve/mod.rs
crates/rspack_core/src/resolver/factory.rs
crates/rspack_core/src/resolver/resolver_impl.rs
packages/rspack/src/config/adapter.ts
packages/rspack/src/config/defaults.ts
packages/rspack/src/config/zod.ts
packages/rspack/tests/__snapshots__/Defaults.unittest.ts.snap
packages/rspack/tests/configCases/resolve/tsconfig-project-references-auto/webpack.config.js
packages/rspack/tests/configCases/resolve/tsconfig-project-references-manual/webpack.config.js

> [!NOTE] 
> The target branch is 0.5.0
Remove  nodejs_resolver and `experiments.rspackFuture.newResolver` for v0.5.0

refactor(rspack_core): remove nodejs_resolver and `experiments.rspackFuture.newResolver`

---

crates/rspack_core/src/normal_module_factory.rs
packages/rspack/jest.config.js
scripts/test/slash.cjs

The old package `slash`  introduced in `jest-serializer-path` which is a long not maintained project is later fixed this issue.
This PR fixed `jest-serializer-path` not working when non-ascii code contains by syncing the implementation from the newest version.

test: jest serializer path should be working with non-ascii code

---

packages/rspack/tests/Stats.test.ts
packages/rspack/tests/StatsTestCases.test.ts

Since https://github.com/web-infra-dev/rspack/pull/5190 fixed the serializer, then we can remove these not necessary manual replacements.

test: remove manual path normalizations in snapshots

---

crates/rspack_plugin_javascript/src/visitors/dependency/common_js_scanner.rs
crates/rspack_plugin_javascript/src/visitors/dependency/util.rs
webpack-test/configCases/parsing/require.main/test.filter.js
webpack-test/configCases/split-chunks-common/correct-order/test.filter.js
webpack-test/configCases/split-chunks-common/inverted-order/test.filter.js

Close #5183, close #3562
- Reuse `webpack-test/configCases/parsing/require.main`
- Reuse `webpack-test/configCases/split-chunks-common/correct-order`
- Reuse `webpack-test/configCases/split-chunks-common/inverted-order`

feat: add require.main

---

crates/rspack_plugin_javascript/src/visitors/dependency/common_js_export_scanner.rs
crates/rspack_plugin_javascript/src/visitors/dependency/common_js_import_dependency_scanner.rs
packages/rspack/tests/cases/parsing/typeof-api/index.js
packages/rspack/tests/cases/parsing/typeof-api/typeof.js

Source Code: 
```js
// lodash-es/isBuffer.js
import root from './_root.js';
import stubFalse from './stubFalse.js';
/** Detect free variable `exports`. */
var freeExports = typeof exports == 'object' && exports && !exports.nodeType && exports;
// ...
```
Webpack register module&exports evaluateTypeOf only when module type is JAVASCRIPT_MODULE_TYPE_AUTO or JAVASCRIPT_MODULE_TYPE_DYNAMIC. So typeof module and typeof exports will not be evalutated in ESM.
```js
// exports is undefined in esm, so the following code will not execute
var freeExports = typeof exports == 'object' && exports && !exports.nodeType && exports;
```
But currently rspack CommonJsImportScanner will evaluate in all types of javascript modules.
```js
var freeExports = true && exports && !exports.nodeType && exports;
``` …

fix: remove module/exports evaluation 

---

packages/playground/cases/context/delete-file/index.test.ts
packages/playground/cases/css/chunk-loading-order/index.test.ts
packages/playground/cases/css/css-filename/index.test.ts
packages/playground/cases/css/render-to-body/index.test.ts
packages/playground/cases/hooks/asset-emitted/index.test.ts
packages/playground/cases/html/issue-4366/index.test.ts
packages/playground/cases/react/basic-disableTransformByDefault/index.test.ts
packages/playground/cases/react/basic/index.test.ts
packages/playground/cases/react/class-component-disableTransformByDefault/index.test.ts
packages/playground/cases/react/class-component/index.test.ts
packages/playground/cases/react/tailwindcss-disableTransformByDefault/index.test.ts
packages/playground/cases/react/tailwindcss/index.test.ts
packages/playground/cases/react/with-babel/index.test.ts
packages/playground/cases/vue3/index.test.ts
packages/playground/fixtures/rspack.ts
packages/playground/playwright.config.ts

NOBODY likes flaky tests ;-(
Use auto-retrying assertions and remove manual pollings.
Ref: https://playwright.dev/docs/api/class-locator#locator-get-attribute
Ref: https://playwright.dev/docs/api/class-locator#locator-text-content
If there's any further tests not working, then It should at least be timeouts instead of something like context destroyed.

ci: fix flaky e2e tests

---

crates/rspack_plugin_json/src/lib.rs
crates/rspack_plugin_json/tests/fixtures/simple/index.js
crates/rspack_plugin_json/tests/fixtures/simple/snapshot/output.snap
crates/rspack_plugin_json/tests/fixtures/simple/string.json

related to https://github.com/toeverything/blocksuite-ecosystem-ci/pull/27#discussion_r1440548551
This is a failing case when import json file contains a string
* string.json
```json
"hello world"
```
`stringify`  ref: https://github.com/maciejhirsz/json-rust/blob/master/tests/stringify.rs
pass this test

fix: failed to import string json

---

packages/rspack/src/container/ModuleFederationPlugin.ts
packages/rspack/src/container/default.runtime.js

fix(mf1.5): add resolve alias for mf runtime

---

crates/rspack_plugin_javascript/src/visitors/dependency/api_scanner.rs
crates/rspack_plugin_javascript/src/visitors/dependency/common_js_scanner.rs
crates/rspack_plugin_javascript/src/visitors/dependency/mod.rs
crates/rspack_plugin_javascript/src/visitors/dependency/util.rs
packages/rspack/tests/cases/parsing/unsupport-require-property/index.js
packages/rspack/tests/cases/parsing/unsupport-require-property/warnings.js

resolve #5040, resolve #5235
Transform unsupport require.xxx or require.xxx() to undefined and throw warnings
- Add `packages/rspack/tests/cases/parsing/unsupport-require-property`

feat: unsupport require property

---

crates/rspack_core/src/compiler/compilation.rs
crates/rspack_core/src/plugin/api.rs
crates/rspack_core/src/plugin/plugin_driver.rs
crates/rspack_plugin_asset/src/lib.rs
crates/rspack_plugin_css/src/plugin/impl_plugin_for_css_plugin.rs
crates/rspack_plugin_hmr/src/lib.rs
crates/rspack_plugin_javascript/src/plugin/impl_plugin_for_js_plugin.rs
crates/rspack_plugin_wasm/src/wasm_plugin.rs

Change ret type of render_manifest to TWithDiagnostics, so that plugin can emit diagnostics in render_manifest hook

refactor: change return type of `render_manifest` to `TWithDiagnosticArray`

---

crates/rspack_loader_swc/src/lib.rs
crates/rspack_plugin_css/src/plugin/impl_plugin_for_css_plugin.rs
crates/rspack_plugin_javascript/src/dependency/is_included_dependency.rs
crates/rspack_plugin_javascript/src/parser_plugin/common_js_imports_parse_plugin.rs
crates/rspack_plugin_javascript/src/parser_plugin/drive.rs
crates/rspack_plugin_javascript/src/parser_plugin/mod.rs
crates/rspack_plugin_javascript/src/parser_plugin/require_context_dependency_parser_plugin.rs
crates/rspack_plugin_javascript/src/parser_plugin/trait.rs
crates/rspack_plugin_javascript/src/parser_plugin/webpack_included_plugin.rs
crates/rspack_plugin_javascript/src/utils/eval/eval_binary_expr.rs
crates/rspack_plugin_javascript/src/visitors/dependency/api_scanner.rs
crates/rspack_plugin_javascript/src/visitors/dependency/common_js_import_dependency_scanner.rs
crates/rspack_plugin_javascript/src/visitors/dependency/mod.rs
crates/rspack_swc_visitors/src/define.rs
packages/rspack-cli/tests/build/basic/public/main.js
packages/rspack/tests/cases/parsing/typeof-api/index.js
pnpm-lock.yaml
webpack-test/cases/parsing/webpack-is-included/test.filter.js

Fixes #4443
This PR introduces two changes:
- integration of `﻿JavascriptParser.hooks.typeof` support;
- implementation of `﻿+` operation support in eval for binary expressions.

feat: eval `+` op for binary expr

---

crates/rspack_plugin_split_chunks_new/src/plugin/module_group.rs

This PR will remove useless `tracing::span!` in `rspack_plugin_split_chunks_new`, and it will make trace.json which have 5 times HMR from 160M to 16M

fix: remove useless tracing span

---

crates/rspack_plugin_javascript/src/visitors/dependency/api_scanner.rs
crates/rspack_plugin_javascript/src/visitors/dependency/util.rs
packages/rspack/tests/cases/parsing/unsupport-require-property/index.js

should not remove unsupport require declaration when local variable
- Added

fix: should not remove unsupport require declaration when local variable

---

crates/rspack_plugin_javascript/src/dependency/commonjs/common_js_full_require_dependency.rs
crates/rspack_plugin_javascript/src/visitors/dependency/common_js_import_dependency_scanner.rs
packages/rspack/tests/cases/cjs-tree-shaking/full-require/index.js
packages/rspack/tests/cases/cjs-tree-shaking/full-require/warnings.js

Related to comment in #5197, full rqeuire in try catch should be optional
added

fix: full require in try catch should be optional

---

packages/rspack-plugin-react-refresh/src/index.ts
packages/rspack-plugin-react-refresh/src/options.ts
scripts/meta/check_is_workspace_root.js

part of #4640
Some errors are truly expected to work around typescript complaints.
I added comments for these comments.

fix: address expect-error in react-refresh and script

---

packages/rspack/src/Compilation.ts

`undefined` requires an explicit `return` statement.

fix: replace undefined with void in hooks

---

crates/rspack_binding_values/src/module.rs

THIS PR is used only to make `succeedModule` and other module related hooks not being panicked at runtime. We haven't decided whether to keep this hook for performance reason.
closes https://github.com/web-infra-dev/rspack/issues/5054
Not for now.

fix: `succeedModule` should not panic

---

README.md
README.zh-CN.md

Part of https://github.com/web-infra-dev/rspack/issues/5295

chore: add link to rspack-contrib/rspack-examples in README

---

crates/node_binding/src/plugins/mod.rs
crates/rspack_core/src/compiler/compilation.rs
crates/rspack_core/src/compiler/hmr.rs
crates/rspack_core/src/compiler/make/mod.rs
crates/rspack_core/src/compiler/make/rebuild_deps_builder.rs
crates/rspack_core/src/compiler/mod.rs
crates/rspack_core/src/plugin/api.rs
crates/rspack_core/src/plugin/plugin_driver.rs
crates/rspack_plugin_entry/src/lib.rs
crates/rspack_plugin_mf/src/container/container_plugin.rs
crates/rspack_plugin_progress/src/lib.rs
packages/playground/cases/css/chunk-loading-order/rspack.config.js
packages/playground/cases/css/css-filename/rspack.config.js
packages/playground/cases/css/import-double-css-files-with-empty/rspack.config.js
packages/playground/cases/css/import-empty-css-file/rspack.config.js
packages/playground/cases/css/render-to-body/rspack.config.js
packages/playground/cases/file/context-delete-file/rspack.config.js
packages/playground/cases/file/missing-files/index.test.ts
packages/playground/cases/file/missing-files/rspack.config.js
packages/playground/cases/react/basic/rspack.config.js
packages/playground/cases/react/class-component/rspack.config.js
packages/playground/cases/react/with-babel/rspack.config.js
packages/playground/cases/react/worker/rspack.config.js
packages/playground/cases/vue3/rspack.config.js

This PR fix the module graph incorrect when delete or create file. There are some summary:
* Add parent module to `force_build_module` when module factorize failed instead of add deps to `force_build_deps`. if the module is entry module, we should still add deps to `force_build_deps`, because of it no parent module.
* Deleting the file should not only mark the affected module as `force_build_module` but also add its parent module to `force_build_module`
We can see a simply example:
``` js
// index.js
import a form "./a" // <-- HarmonyImportSideEffectDependency
console.log(a) // <-- HarmonyImportSpecifierDependency
```
the `index.js` have two deps `HarmonyImportSideEffectDependency` and `HarmonyImportSpecifierDependency` . 
If we don't have `a.js` and create it, we should not only create …

fix: module graph incorrect when delete or create file

---

webpack-test/jest.config.js
webpack-test/package.json

For targeting 1.0, I think we should make the test suite as stable as possible.
I tried a local debug build and it ran successfully.

chore: turn off `--bail` `--forceExit` `--logHeapUsage` from webpack test

---

.npmrc
pnpm-lock.yaml

Since the examples folder directory is removed,
it should be safe to use all the latest pnpm features.
CI should pass.

refactor: use pnpm v8 default flags

---

crates/rspack_core/src/tree_shaking/optimizer.rs
crates/rspack_plugin_copy/src/lib.rs
crates/rspack_plugin_javascript/src/lib.rs
crates/rspack_plugin_library/src/assign_library_plugin.rs
crates/rspack_plugin_library/src/umd_library_plugin.rs
crates/rspack_plugin_runtime/src/runtime_module/utils.rs
crates/rspack_testing/src/test_config.rs
rust-toolchain.toml

Upgrade to the latest Rust v1.75.0 release https://blog.rust-lang.org/2023/12/28/Rust-1.75.0.html

chore: upgrade Rust to v1.75.0 (nightly)

---

crates/node_binding/binding.d.ts
crates/rspack_binding_options/src/options/raw_resolve.rs
crates/rspack_core/src/options/resolve/clever_merge.rs
crates/rspack_core/src/options/resolve/mod.rs
crates/rspack_core/src/resolver/resolver_impl.rs
packages/rspack/src/config/defaults.ts
packages/rspack/src/config/zod.ts
packages/rspack/tests/Defaults.unittest.ts
packages/rspack/tests/__snapshots__/Defaults.unittest.ts.snap
webpack-test/TestCases.template.js

This PR deprecates resolve.browserField in favor of resolver.aliasFields.
In addition, resolve.{preferAbsolute,restrictions,roots,aliasFields} are all enabled and passed to `oxc_resolver`
* CI passes

feat: deprecate resolve.browserField and enable resolve.{preferAbsolute,restrictions,roots,aliasFields}

---

crates/rspack_plugin_javascript/src/visitors/dependency/import_scanner.rs
crates/rspack_plugin_javascript/src/visitors/dependency/mod.rs
crates/rspack_plugin_javascript/src/webpack_comment.rs
packages/rspack/tests/diagnostics/module-parse-failed/magic_comment_warning/a.js
packages/rspack/tests/diagnostics/module-parse-failed/magic_comment_warning/index.js
packages/rspack/tests/diagnostics/module-parse-failed/magic_comment_warning/stats.err
packages/rspack/tests/diagnostics/module-parse-failed/non_support_warning/stats.err

Make warnings of magic comments traceable
- Add `packages/rspack/tests/diagnostics/module-parse-failed/magic_comment_warning`

refactor: traceable magic comments warnings

---

packages/rspack-cli/src/commands/build.ts
packages/rspack-cli/src/commands/serve.ts
packages/rspack-cli/src/utils/options.ts
packages/rspack-cli/tests/build/basic/basic.test.ts
packages/rspack-cli/tests/build/basic/entry.env.js

for sharing configuration file between rspack and webpack.
for instance:
```js
// rspack.config.js
module.exports = function(env) {
/** align with webpack's WEBPACK_BUNDLE @{link https://github.com/webpack/webpack-cli/blob/eea6adf7d34dfbfd3b5b784ece4a4664834f5a6a/packages/webpack-cli/src/webpack-cli.ts#L2500-L2503} */
const isRspack = env.RSPACK_BUNDLE;
const config = {};
if (isRspack) {
config.experiments.rspackFuture = {
newTreeShaking: true
};
}
return config;
}
```
i'm also going to add `WEBPACK_` prefixed builtin env in 0.5.0.
the plugin dev can separately introduce different logics for rspack and webpack.
for instance:
```js
const plugin = {
apply(compiler) {
const { isRspack } = compiler;
if (isRspack) {
// do something special
}
}
}
```

feat(cli): support built-in rspack envs

---

crates/rspack_plugin_javascript/src/plugin/inner_graph_plugin.rs
crates/rspack_plugin_javascript/src/plugin/side_effects_flag_plugin.rs

1. Part of https://github.com/web-infra-dev/rspack/issues/5317

fix: tree shaking size differentiation between webpack

---

crates/rspack_core/src/compiler/compilation.rs
crates/rspack_core/src/compiler/queue.rs
pnpm-lock.yaml

Add callback parameter to handle_module_creation
In Webpack, processDependencies task finishes after all the dependencies actually factorized. I use a oneshot channel to get informed

refactor(compilation): Add callback to factorizeTask and make process dependencies happen after all dependencies get factorized

---

Cargo.lock
crates/rspack_core/src/compiler/compilation.rs
crates/rspack_core/src/compiler/queue.rs
crates/rspack_error/src/lib.rs
crates/rspack_util/Cargo.toml
crates/rspack_util/src/fx_dashmap.rs
crates/rspack_util/src/lib.rs

In Webpack, any plugin can add task to factorizeQueue, buildQueue and other workerQueue, we can use QueueHandle to do the same. A queue handle can be sent through threads, without mutable reference, to let other plugins be capable to push new task into the queue.
Add more dependency id as arg for succeed_module hook input.
For more performant dashmap

feat(compilation): introduce queue handles representing task_queue

---

crates/rspack_core/src/build_chunk_graph/code_splitter.rs
crates/rspack_core/src/chunk_graph/chunk_graph_module.rs
crates/rspack_core/src/chunk_graph/mod.rs
crates/rspack_core/src/compiler/compilation.rs
crates/rspack_core/src/context_module.rs
crates/rspack_core/src/dependencies_block.rs
crates/rspack_core/src/dependency/runtime_template.rs
crates/rspack_core/src/external_module.rs
crates/rspack_core/src/lib.rs
crates/rspack_core/src/module.rs
crates/rspack_core/src/module_graph/mod.rs
crates/rspack_core/src/normal_module.rs
crates/rspack_core/src/raw_module.rs
crates/rspack_core/src/runtime_module.rs
crates/rspack_core/src/self_module.rs
crates/rspack_plugin_javascript/src/parser_and_generator/mod.rs
crates/rspack_plugin_javascript/src/plugin/flag_dependency_usage_plugin.rs
crates/rspack_plugin_javascript/src/visitors/dependency/import_scanner.rs
crates/rspack_plugin_javascript/src/visitors/dependency/worker_scanner.rs
crates/rspack_plugin_mf/src/container/container_entry_module.rs
crates/rspack_plugin_mf/src/container/fallback_module.rs
crates/rspack_plugin_mf/src/container/remote_module.rs
crates/rspack_plugin_mf/src/sharing/consume_shared_module.rs
crates/rspack_plugin_mf/src/sharing/provide_shared_module.rs
crates/rspack_plugin_runtime/src/lazy_compilation.rs

After remove `__webpack_require__.el`, we don't need AsyncDependenciesBlockIdentifier to generate the `__webpack_require__.el` code anymore

refactor: remove async dependencies block identifier

---

packages/rspack-cli/package.json
packages/rspack-test-tools/package.json
packages/rspack/package.json
packages/rspack/tests/configCases/builtin-swc-loader/styled-components/index.jsx
packages/rspack/tests/configCases/builtins/minify-pure-funcs/index.js
packages/rspack/tests/configCases/builtins/minify-pure-funcs/webpack.config.js
packages/rspack/tests/configCases/hooks/before-resolve/webpack.config.js
packages/rspack/tests/configCases/parsing/node-source-plugin-off/index.js
packages/rspack/tests/configCases/parsing/node-source-plugin-off/webpack.config.js
packages/rspack/tests/configCases/plugins/minify-esbuild/index.js
packages/rspack/tests/configCases/plugins/minify-pure-funcs/index.js
packages/rspack/tests/configCases/plugins/minify-pure-funcs/webpack.config.js
packages/rspack/tests/configCases/split-chunks-common/enforce-minsize/async.js
packages/rspack/tests/configCases/split-chunks-common/enforce-minsize/foo.js
packages/rspack/tests/configCases/split-chunks/css-simple/index.js
packages/rspack/tests/configCases/split-chunks/issue-3646/src/shared.js
scripts/debug/launch.mjs
webpack-test/configCases/parsing/node-source-plugin-off/test.filter.js

1. Remove logs from test
2. rspack `node-source-plugin-off` is removed, in favor of webpack's.
3. Keep dep warnings in test

chore: remove logs from tests

---

crates/rspack_core/src/dependencies_block.rs
crates/rspack_plugin_javascript/src/parser_plugin/const/if_stmt.rs
crates/rspack_plugin_javascript/src/visitors/dependency/api_scanner.rs
crates/rspack_plugin_javascript/src/visitors/dependency/common_js_export_scanner.rs
crates/rspack_plugin_javascript/src/visitors/dependency/common_js_scanner.rs
crates/rspack_plugin_javascript/src/visitors/dependency/compatibility_scanner.rs
crates/rspack_plugin_javascript/src/visitors/dependency/export_info_api_scanner.rs
crates/rspack_plugin_javascript/src/visitors/dependency/harmony_detection_scanner.rs
crates/rspack_plugin_javascript/src/visitors/dependency/harmony_export_dependency_scanner.rs
crates/rspack_plugin_javascript/src/visitors/dependency/harmony_import_dependency_scanner.rs
crates/rspack_plugin_javascript/src/visitors/dependency/harmony_top_level_this.rs
crates/rspack_plugin_javascript/src/visitors/dependency/hot_module_replacement_scanner.rs
crates/rspack_plugin_javascript/src/visitors/dependency/import_meta_scanner.rs
crates/rspack_plugin_javascript/src/visitors/dependency/import_scanner.rs
crates/rspack_plugin_javascript/src/visitors/dependency/mod.rs
crates/rspack_plugin_javascript/src/visitors/dependency/node_stuff_scanner.rs
crates/rspack_plugin_javascript/src/visitors/dependency/parser/mod.rs
crates/rspack_plugin_javascript/src/visitors/dependency/util.rs
crates/rspack_plugin_javascript/src/visitors/dependency/worker_scanner.rs

before 4.7s:
after 3.4s:
----
The performance regression is caused by the linear search operation within ﻿`self.ignored`. The time cost escalates linearly as the size increases. To counter this, I have replaced it with a `﻿HashSet` to transform the time complexity to logarithmic, thereby enhancing performance

perf: use hashset to compare ignore

---

crates/rspack_ast/src/ast/javascript.rs
crates/rspack_plugin_javascript/src/parser_plugin/api_plugin.rs
crates/rspack_plugin_javascript/src/parser_plugin/mod.rs
crates/rspack_plugin_javascript/src/visitors/dependency/mod.rs
crates/rspack_plugin_javascript/src/visitors/dependency/parser/mod.rs
crates/rspack_plugin_javascript/src/visitors/dependency/parser/walk.rs
crates/rspack_plugin_javascript/src/visitors/dependency/util.rs
packages/rspack-cli/tests/build/basic/public/main.js.map
packages/rspack/tests/cases/parsing/typeof-api-2/index.js

Visiting each identifier incurs a significant amount of time. Therefore, optimizing the `﻿ApiScanner` can aid in improving performance.
before 3.3s:
after this PR, 2.7s:

perf: cleanup `ApiScanner`

---

Cargo.lock
crates/rspack_plugin_progress/Cargo.toml
crates/rspack_plugin_progress/src/lib.rs

#4973 
Last time in #3803, we only supported the activeModule report and progress_handler compatibility. However, it had some issues, such as the default_handler not correctly reflecting the build duration. Due to several missing sealing hooks, the process duration wasn't accurate either.
Comparing to webpack, rspack will build modules with mulitple threads, between `build_module` and `succeed_module` , maybe other module will be build in other thread. Now we have `default_handler` and `progress_handler`, and in the future there may be some custom handler from user.
We don't want the progress bar shows "building module2" after module2 build succeed, so we should correct the progress bar message, when module2 `succeed_module`. In code side, I use `linked_hash_map` which can keep the …

feat: progress plugin

---

.github/renovate.json

Only `github-actions` is configured for this PR for testing purposes
relates #5387

ci: setup renovatebot

---

crates/rspack_plugin_javascript/src/parser_plugin/common_js_imports_parse_plugin.rs
packages/rspack/tests/cases/parsing/issue-5426/index.js

fix: use `eval.as_string()` lazily

---

crates/rspack_plugin_javascript/src/visitors/dependency/harmony_import_dependency_scanner.rs
packages/rspack/tests/cases/parsing/evaluate-if/foo.js
packages/rspack/tests/cases/parsing/evaluate-if/index.js

fix #5430 
before:
```js
it('should have correct syntax', () => {
if (true) console.log('hello');
else _foo__WEBPACK_IMPORTED_MODULE_0__.foo{ }
});
```
after:
```js
it('should have correct syntax', () => {
if (true) console.log('hello');
else { }
});
```

fix: evaluate if stmt should skip import specifier in dead branch

---

packages/rspack/src/Compilation.ts
packages/rspack/src/Compiler.ts
packages/rspack/src/util/memoize.ts

Rspack spent a lot of time on `optimizeTree` when use html-webpack-plugin. This is caused by move `compilation.modules` and `compilation.chunks` from rust side to node js side. 
This PR add lazy calculation for `compilation.modules` and `compilation.chunks` to make html-webpack-plugin faster

perf: lazy calculate compilation.modules and compilation.chunks

---

crates/rspack_core/src/normal_module_factory.rs
crates/rspack_loader_runner/src/runner.rs
packages/rspack/tests/configCases/source-map/relative-source-maps-by-loader/index.js

Resolved an issue where using an inline loader without a module specifier resulted in an error, as demonstrated below:
```js
require("./loader-source-root!");
```

fix: resolve error with inline loader without module specifier

---

packages/rspack/src/Compiler.ts

fixes #5398
The recent modification disabled the `Compiler#newCompilation` function from being called when there are no taps on the `thisCompilation` hook. See: https://github.com/web-infra-dev/rspack/pull/5202
As a result, every rebuilding now share a single instance of `Compilation`, which is not expected as it leads to the problem described in #5398.

fix(@rspack/core): js Compilation instance is not recreated as expected when rebuilding on watch/serve mode

---

.github/workflows/ci.yml
Cargo.lock
crates/rspack_core_macros/Cargo.toml
crates/rspack_plugin_devtool/Cargo.toml
crates/rspack_plugin_javascript/Cargo.toml
crates/rspack_plugin_runtime/Cargo.toml
crates/swc_plugin_import/Cargo.toml

https://github.com/est31/cargo-udeps is outdated and broken.
https://github.com/bnjbvr/cargo-machete makes everything easy by using greping for the dependency, which is correct 99% of the time for a Rust project :-)

chore: use `cargo machete` for checking unused dependencies

---

Cargo.lock
Cargo.toml
crates/rspack_plugin_css/Cargo.toml

The upgrade is safe because it's a only a Rust MSRV change.
See https://github.com/indexmap-rs/indexmap/blob/master/RELEASES.md

chore: bump indexmap from 1.9.3 to 2.1.0

---

crates/rspack_core/src/compiler/compilation.rs
packages/rspack/tests/configCases/container-1-5/assign-depth-for-add-include/a/index.js
packages/rspack/tests/configCases/container-1-5/assign-depth-for-add-include/a/util.js
packages/rspack/tests/configCases/container-1-5/assign-depth-for-add-include/index.js
packages/rspack/tests/configCases/container-1-5/assign-depth-for-add-include/reexport.js
packages/rspack/tests/configCases/container-1-5/assign-depth-for-add-include/webpack.config.js

build should not suspend when assign depth for include dependencies

fix: assign depth for include dependencies

---

Cargo.lock
Cargo.toml
crates/rspack_core/src/fake_namespace_object.rs
crates/rspack_core/src/normal_module.rs
crates/rspack_core/src/runtime_globals.rs
crates/rspack_core/src/tree_shaking/mod.rs
crates/rspack_core/src/tree_shaking/symbol/mod.rs
crates/rspack_core/src/tree_shaking/visitor.rs
crates/rspack_loader_runner/src/loader.rs
crates/rspack_plugin_css/src/plugin/mod.rs

The breaking changes are API only, see https://github.com/bitflags/bitflags/releases/tag/2.0.0

chore: bump bitflags to v2.4.2

---

.github/renovate.json

Turn on `devDependencies` first ... I've got no clue on how to deal with `dependencies`

chore: renovate bot turn on npm devDependencies update

---

.github/renovate.json

This ignores updating 
```
"diffcases/**",
"npm/**",
"packages/create-rspack/**",
```

chore: renovate ignore more directories

---

.github/renovate.json

Otherwise e2e will error out with:
```
main.js:31267 Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
```

chore: ignore react upgrades

---

crates/node_binding/binding.d.ts
crates/rspack_binding_values/src/asset.rs
crates/rspack_binding_values/src/compilation.rs
packages/rspack/src/Compilation.ts

This PR will add lazy calculation for asset.source which will make html-webpack-plugin faster.
Here is some data from my project.
| html-webpack-plugin | pr + html-webpack-plugin | rspack.HtmlRspackPlugin |
|--|--|--|
| 1s 636ms | 640ms | 580ms |
| ![image](https://github.com/web-infra-dev/rspack/assets/9291503/fddb36d2-b5bc-49d2-8153-7a7037096058) | ![image](https://github.com/web-infra-dev/rspack/assets/9291503/91f3b433-33db-436f-884c-fe9a0206da43) | ![image](https://github.com/web-infra-dev/rspack/assets/9291503/673388c8-4edf-48fe-a03b-d7ebd7863591) |

perf: lazy calculate asset.source

---

crates/rspack_plugin_hmr/src/runtime/hot_module_replacement.js
crates/rspack_plugin_runtime/src/runtime_module/import_scripts_chunk_loading.rs
diffcases/arco-pro/package.json
diffcases/arco-pro/rspack.config.js
diffcases/arco-pro/webpack.config.js
package.json
packages/rspack-test-tools/package.json
packages/rspack-test-tools/src/compare/format-code.ts
packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
pnpm-lock.yaml
scripts/diff.cjs

Modify configuration of diff repo:
1. Enable newTreeshaking
2. Bump webpack to 5.90.0 to support namedExports of experiments.css
3. Add generator and parser config to config file to prevent difference between less files
4. Align runtime module code with webpack 5.90.0 (fetchPritority)

chore: enable newTreeshaking on arco-pro diff case

---

packages/rspack-cli/src/rspack-cli.ts

set default WATCHPACK_WATCHER_LIMIT to 20 to improve kill process performance, related to https://github.com/vercel/next.js/pull/51826/files
It takes about 5s+ to kill `rspack dev` before and instantly kill after set `WATCHPACK_WATCHER_LIMIT=20` in my project
Rsbuild seems need this too @chenjiahan 
No Need

perf: set default WATCHPACK_WATCHER_LIMIT to 20

---

.github/renovate.json
package.json
pnpm-lock.yaml
tsconfig.base.json

chore: revert TypeScript to v5.0.2 due to broken "NodeNext" for compilerOptions.module

---

Cargo.toml

We now have better machines, let's try "thin" LTO. If this satisfactory, we'll try "fat" LTO in a later PR.

perf: enable "thin" LTO for release

---

packages/rspack/tests/configCases/split-chunks/issue-5485/src/index.js
packages/rspack/tests/configCases/split-chunks/issue-5485/src/lib/a.js
packages/rspack/tests/configCases/split-chunks/issue-5485/test.config.js
packages/rspack/tests/configCases/split-chunks/issue-5485/webpack.config.js

#5510 added test for ensuring consistent splitChunks, however the tests failed on Windows platform because the path regex is incorrect.
`/path\/to/` should be `/path[\\\/]to`

fix: fix test for consistent splitChunk

---

crates/rspack_core/src/dependency/mod.rs
crates/rspack_core/src/dependency/static_exports_dependency.rs
crates/rspack_core/src/external_module.rs
crates/rspack_plugin_mf/src/container/container_entry_module.rs
crates/rspack_plugin_wasm/src/parser_and_generator.rs

Align ExternalModule and StaticExportsDependency with webpack 
- Reuse exists

refactor: align external module and static exports dependency with webpack

---

packages/rspack/src/config/defaults.ts
packages/rspack/tests/Defaults.unittest.ts
packages/rspack/tests/__snapshots__/Defaults.unittest.ts.snap

relates #5314
This PR syncs our default resolve options with webpack.
Except `roots: [context]`, which has failing test cases, I'll update them in another PR.
CI passes.

feat(rspack): align default resolveOptions with webpack

---

crates/rspack_core/src/build_chunk_graph/code_splitter.rs
crates/rspack_core/src/chunk_group.rs
crates/rspack_core/src/compiler/execute_module.rs

move chunk_group_info into CodeSplitter

refactor: move chunk_group_info to code splitting

---

crates/rspack_core/src/chunk_graph/chunk_graph_module.rs
crates/rspack_core/src/compiler/compilation.rs
crates/rspack_core/src/concatenated_module.rs
crates/rspack_core/src/dependency/runtime_template.rs
crates/rspack_core/src/exports_info.rs
crates/rspack_core/src/module.rs
crates/rspack_core/src/module_graph/mod.rs
crates/rspack_plugin_javascript/src/dependency/commonjs/common_js_full_require_dependency.rs
crates/rspack_plugin_javascript/src/dependency/commonjs/common_js_self_reference_dependency.rs
crates/rspack_plugin_javascript/src/dependency/is_included_dependency.rs
crates/rspack_plugin_javascript/src/plugin/flag_dependency_exports_plugin.rs
crates/rspack_plugin_javascript/src/plugin/module_concatenation_plugin.rs
crates/rspack_plugin_javascript/src/plugin/side_effects_flag_plugin.rs

Using imutable module graph during code generation to prevent immutable&mutable issue while calling module.get_exports_type, which is used widely:
- Chunk module hash
- Runtime Template
- HarmonyExportImportedSpecifierDendency::get_mode, which may be called in code generation and FlagDependencyExportsPlugin
- HarmonyImportSpecifierDependency::get_referenced_exports, which may be called in FlagDependencyUsagePlugin and ModuleConcatenationPlugin
- Reuse exists

refactor: immutable module graph during code generation

---

packages/rspack-cli/src/utils/isEsmFile.ts
packages/rspack-cli/tests/build/config/cjs_in_esm/main.ts
packages/rspack-cli/tests/build/config/cjs_in_esm/package.json
packages/rspack-cli/tests/build/config/cjs_in_esm/rspack.config.cjs
packages/rspack-cli/tests/build/config/cjs_in_esm/rspack.config.cts
packages/rspack-cli/tests/build/config/config.test.ts

currently rspack-cli will throw error when `.cts` in folder which contains `type:module` in package.json

fix(cli): fix cts support

---

packages/rspack/src/config/zod.ts

a small fix. 24 source-map options in total

fix: zod.devtool - missing inline-nosources-cheap-source-map

---

crates/rspack_core/src/cache/occasion/code_generate.rs
packages/rspack/tests/configCases/loader-import-module/codegen-cache/app.js
packages/rspack/tests/configCases/loader-import-module/codegen-cache/foo.js
packages/rspack/tests/configCases/loader-import-module/codegen-cache/index.js
packages/rspack/tests/configCases/loader-import-module/codegen-cache/loader.js
packages/rspack/tests/configCases/loader-import-module/codegen-cache/webpack.config.js

Different runtime may generates different content, so cache in codegen should consider runtime

fix: codegen cache should consider runtime

---

crates/rspack_plugin_javascript/src/parser_plugin/common_js_imports_parse_plugin.rs
crates/rspack_plugin_javascript/src/parser_plugin/common_js_plugin.rs
crates/rspack_plugin_javascript/src/parser_plugin/drive.rs
crates/rspack_plugin_javascript/src/parser_plugin/import_meta_plugin.rs
crates/rspack_plugin_javascript/src/parser_plugin/trait.rs
crates/rspack_plugin_javascript/src/parser_plugin/webpack_included_plugin.rs
crates/rspack_plugin_javascript/src/visitors/dependency/parser/mod.rs
crates/rspack_plugin_javascript/src/visitors/dependency/parser/walk.rs
crates/rspack_plugin_javascript/src/visitors/dependency/util.rs

And support `for_name` for `typeof` hooks

refactor: cleanup `expr_mather::import_meta`

---

crates/rspack_core/src/module.rs

Align `module.get_exports_type()` with [webpack](https://github.com/webpack/webpack/blob/4a2662381ed8e6a9d849b494511459f5858d4e82/lib/Module.js#L470-L510) to prevent generating unnecessary code.
- Reuse current

refactor: align get_exports_type with webpack

---

crates/rspack_core/src/dependency/runtime_template.rs
crates/rspack_core/src/utils/compile_boolean_matcher.rs
crates/rspack_core/src/utils/mod.rs
crates/rspack_plugin_css/src/runtime/mod.rs
crates/rspack_plugin_runtime/src/lib.rs
crates/rspack_plugin_runtime/src/runtime_module/import_scripts_chunk_loading.rs
crates/rspack_plugin_runtime/src/runtime_module/jsonp_chunk_loading.rs
crates/rspack_plugin_runtime/src/runtime_module/module_chunk_loading.rs
crates/rspack_plugin_runtime/src/runtime_module/readfile_chunk_loading.rs
crates/rspack_plugin_runtime/src/runtime_module/require_js_chunk_loading.rs
crates/rspack_plugin_runtime/src/runtime_module/utils.rs

merge duplicate implementation of boolean matcher

refactor: merge duplicate implementation of boolean matcher

---

crates/node_binding/binding.d.ts
crates/rspack_binding_options/src/options/raw_builtins/mod.rs
packages/rspack/src/builtin-plugin/BundlerInfoRspackPlugin.ts
packages/rspack/src/builtin-plugin/index.ts
packages/rspack/src/rspackOptionsApply.ts

rename BundlerInfoPlugin to BundlerInfoRspackPlugin

chore: rename bundler info plugin

---

crates/node_binding/src/plugins/mod.rs
crates/rspack_core/src/compiler/compilation.rs
crates/rspack_core/src/plugin/api.rs
crates/rspack_core/src/plugin/plugin_driver.rs
crates/rspack_plugin_devtool/src/lib.rs
packages/rspack/tests/configCases/hooks/issue-5571/index.css
packages/rspack/tests/configCases/hooks/issue-5571/index.js
packages/rspack/tests/configCases/hooks/issue-5571/webpack.config.js

Fix #5571, run runtime_module hook after runtime_requirements_in_tree to make sure the code generation can use full runtime requirements

fix: runtime module hook after tree runtime requirements

---

crates/rspack_core/src/dependency/runtime_template.rs
crates/rspack_plugin_javascript/src/dependency/esm/harmony_import_dependency.rs
crates/rspack_plugin_javascript/src/dependency/esm/mod.rs
crates/rspack_plugin_javascript/src/dependency/hmr/harmony_accept_dependency.rs
packages/rspack/tests/hotCases/worker/issue-5597/changed-file.js
packages/rspack/tests/hotCases/worker/issue-5597/chunk.js
packages/rspack/tests/hotCases/worker/issue-5597/chunkS.js
packages/rspack/tests/hotCases/worker/issue-5597/index.js
packages/rspack/tests/hotCases/worker/issue-5597/module.js
packages/rspack/tests/hotCases/worker/issue-5597/moduleA.js
packages/rspack/tests/hotCases/worker/issue-5597/moduleAs.js
packages/rspack/tests/hotCases/worker/issue-5597/moduleB.js
packages/rspack/tests/hotCases/worker/issue-5597/moduleBs.js
packages/rspack/tests/hotCases/worker/issue-5597/moduleS.js
packages/rspack/tests/hotCases/worker/issue-5597/webpack.config.js
packages/rspack/tests/hotCases/worker/issue-5597/worker.js
packages/rspack/tests/hotCases/worker/issue-5597/workerA.js
packages/rspack/tests/hotCases/worker/issue-5597/workerB.js

Relate #5597, this pr aim to fix the error reported in #5597, but the `move-between-runtime`  case can not pass because hmr in rspack does not process module in multiple runtimes correctly.

fix: runtime condition of hot accept dependency

---

crates/rspack_core/src/build_chunk_graph/code_splitter.rs
crates/rspack_core/src/chunk_graph/chunk_graph_module.rs
crates/rspack_core/src/chunk_graph/mod.rs
crates/rspack_core/src/compiler/compilation.rs
crates/rspack_core/src/concatenated_module.rs
crates/rspack_core/src/context_module.rs
crates/rspack_core/src/dependencies_block.rs
crates/rspack_core/src/dependency/runtime_template.rs
crates/rspack_core/src/external_module.rs
crates/rspack_core/src/lib.rs
crates/rspack_core/src/module.rs
crates/rspack_core/src/module_graph/mod.rs
crates/rspack_core/src/normal_module.rs
crates/rspack_core/src/raw_module.rs
crates/rspack_core/src/self_module.rs
crates/rspack_core_macros/src/lib.rs
crates/rspack_plugin_javascript/src/parser_and_generator/mod.rs
crates/rspack_plugin_javascript/src/parser_plugin/common_js_imports_parse_plugin.rs
crates/rspack_plugin_javascript/src/parser_plugin/import_meta_context_dependency_parser_plugin.rs
crates/rspack_plugin_javascript/src/parser_plugin/import_parser_plugin.rs
crates/rspack_plugin_javascript/src/parser_plugin/require_context_dependency_parser_plugin.rs
crates/rspack_plugin_javascript/src/parser_plugin/worker_plugin.rs
crates/rspack_plugin_javascript/src/plugin/flag_dependency_usage_plugin.rs
crates/rspack_plugin_mf/src/container/container_entry_module.rs
crates/rspack_plugin_mf/src/container/fallback_module.rs
crates/rspack_plugin_mf/src/container/remote_module.rs
crates/rspack_plugin_mf/src/sharing/consume_shared_module.rs
crates/rspack_plugin_mf/src/sharing/provide_shared_module.rs
crates/rspack_plugin_runtime/src/lazy_compilation.rs
packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap

Replace asyncDependenciesBlockId with Identifier, this can be good for incremental build.
When Modifying a module we will check if its dependencies change, this include static imports(module identifiers) and dyn imports(async dependencies Id), using identifier for asyncDependenciesId can make sure it's the same for every build if not changed.
- No

refactor: replace asyncDependenciesBlockId with Identifier

---

crates/rspack_core/src/init_fragment.rs
crates/rspack_plugin_javascript/src/dependency/commonjs/common_js_export_require_dependency.rs
crates/rspack_plugin_javascript/src/dependency/commonjs/common_js_exports_dependency.rs
packages/rspack-test-tools/src/case/diff.ts
packages/rspack-test-tools/src/compare/comparator.ts
packages/rspack-test-tools/src/compare/format-code.ts
packages/rspack-test-tools/src/processor/diff.ts
packages/rspack/tests/cases/cjs-tree-shaking/export-require-unused/index.js
packages/rspack/tests/cases/cjs-tree-shaking/export-require-unused/react.js
packages/rspack/tests/cases/cjs-tree-shaking/export-require-unused/reexport.js
packages/rspack/tests/cases/cjs-tree-shaking/export-require-unused/webpack.config.js

Align get_exports and get_referenced_exports of CommonJsExportRequireDependency to make tree shaking works

refactor: align get_exports of CommonJsExportRequireDependency

---

packages/rspack-cli/package.json
packages/rspack-dev-server/package.json
packages/rspack-test-tools/package.json
packages/rspack/package.json
pnpm-lock.yaml

I wrote a script ...
pnpm -r -c exec 'node /path/to/script.js'
```javascript
const util = require('util');
const exec = util.promisify(require('child_process').exec);
const process = require('process');
const path = require('path');
async function main() {
const cwd = process.cwd();
const packageJsonPath = path.join(cwd, "package.json");
const packageJson = require(packageJsonPath);
if (packageJson.devDependencies === undefined) {
return
}
const deps = Object.keys(packageJson.devDependencies);
const scripts = packageJson.scripts || {};
const results = [];
const tasks = deps
.filter((dep) => !dep.startsWith('@types'))
.filter((dep) => !Object.values(scripts).some((s) => s.includes(dep)))
.map(async (dep) => {
try {
const { stdout } = await exec(`git grep ${dep} | grep -e import -e …
```

chore: remove unused dev dependencies

---

crates/rspack_plugin_javascript/src/parser_plugin/api_plugin.rs
crates/rspack_plugin_javascript/src/parser_plugin/const/mod.rs
crates/rspack_plugin_javascript/src/parser_plugin/initialize_evaluating.rs
crates/rspack_plugin_javascript/src/parser_plugin/node_stuff_plugin.rs
crates/rspack_plugin_javascript/src/utils/eval/eval_unary_expr.rs
crates/rspack_plugin_javascript/src/utils/eval/mod.rs
crates/rspack_plugin_javascript/src/visitors/dependency/parser/mod.rs
packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap

This PR introduces:
- remove eval `typeof __resourceQuery` in `api_plugin`, this can help us alian to webpack.
- some test for js slice

feat: eval more unary expr

---

crates/rspack_core/src/compiler/compilation.rs
crates/rspack_core/src/module_graph/mod.rs

If module's all dependencies and blocks stay the same, Rspack skips building chunk graph. However dependencies can change easily, for example:
```js
import {foo} from 'bar';
```
there is 1 dependency which is `ImportSideEffectDependency`. However if I add one line like:
```js
import {foo} from 'bar';
console.log(foo);
```
We don't need to rebuild chunk graph, as there are no connections change. But we do have dependencies change, we have 
`ImportSideEffectDependency` and `ImportSpecifierDependency` now, so cache miss.
I choose to sort all outgoings by there span location first, this step ensures dependency orders change can make cache invalidate.
Then I dedupe them by there target module, so I add extra import to the same module or I make access to import specifier should hit cache as …

fix: hit cache when imports connection not changed

---

crates/rspack_plugin_javascript/src/parser_plugin/common_js_imports_parse_plugin.rs
crates/rspack_plugin_javascript/src/parser_plugin/node_stuff_plugin.rs
crates/rspack_plugin_javascript/src/visitors/dependency/parser/mod.rs
crates/rspack_plugin_javascript/src/visitors/dependency/util.rs
packages/rspack/tests/cases/parsing/renaming/index.js

This PR introduces:
- Delete some useless `expr_match::xxxx`
- make `typeof aliasRequire` return `fcuntion`.

fix: eval `typeof aliasRequire` should work

---

crates/rspack_plugin_javascript/src/parser_plugin/drive.rs
crates/rspack_plugin_javascript/src/visitors/dependency/parser/walk.rs
packages/rspack/tests/cases/parsing/issue-3346/index.js
packages/rspack/tests/cases/parsing/issue-3346/locale/a.js
packages/rspack/tests/cases/parsing/issue-3346/locale/b.js

feat: rename during walk assign expr

---

crates/rspack_core/src/module_graph/connection.rs
crates/rspack_core/src/module_graph/mod.rs
crates/rspack_plugin_javascript/src/plugin/module_concatenation_plugin.rs

* update module align with webpack [module_graph.updateModule](https://github.com/webpack/webpack/blob/eaa685e1310e2abc882adc269e9fd6e264bf3f06/lib/ModuleGraph.js#L225)
* module_graph.revokeConnection should remove active connection if current connection not active

fix: module_graph update module align with webpack

---

crates/node_binding/binding.d.ts
crates/rspack_binding_options/src/options/raw_module/js_loader.rs
crates/rspack_loader_runner/src/runner.rs
crates/rspack_plugin_hmr/src/lib.rs
packages/rspack/src/loader-runner/index.ts
packages/rspack/tests/configCases/loader/hot/index.js
packages/rspack/tests/configCases/loader/hot/loader.js
packages/rspack/tests/configCases/loader/hot/webpack.config.js

loaderContext.hot should be determine by HotModuleReplacementPlugin

fix: loaderCtx.hot should be injected by HMRPlugin

---

packages/rspack/src/config/zod.ts
packages/rspack/tests/Compiler.test.ts

Fix #4887
minChunks zero breaks the contract of splitChunks, Webpack disable minChunks less than 1 as well

fix: minChunks should be greater than 0

---

crates/rspack_core/src/chunk_graph/chunk_graph_module.rs
crates/rspack_core/src/exports_info.rs

should not rehash exportsInfo, otherwise it will fall into infinite recursive

fix: hash exports info should not fall into inf recursive

---

crates/rspack_plugin_javascript/src/visitors/dependency/parser/walk.rs
packages/rspack/tests/configCases/parsing/getter-import-specifier/a.js
packages/rspack/tests/configCases/parsing/getter-import-specifier/index.js
packages/rspack/tests/configCases/parsing/getter-import-specifier/webpack.config.js

should visit propName in getter/setter

fix: should visit prop-name in getter/setter

---

.github/renovate.json

we are currently forking the graphical reporter, which makes it hard to upgrade right now. cc @h-a-n-a

chore: stop updating miette from renovate

---

packages/rspack-test-tools/package.json
webpack-cli-test/package.json

set rspack-test-tools and webpack-cli-test as private

fix: skip release rspack-test-tools and webpack-cli-test

---

crates/rspack_core/src/build_chunk_graph/code_splitter.rs
crates/rspack_core/src/module_graph/mod.rs
crates/rspack_plugin_css/src/parser_and_generator/mod.rs

Using dependencies order as blockModules order

refactor(code-splitting): using raw dependencies order

---

crates/rspack_core/src/dependency/runtime_template.rs
crates/rspack_plugin_javascript/src/dependency/esm/harmony_export_imported_specifier_dependency.rs
packages/rspack/tests/configCases/runtime/namespace-cache/index.mjs
packages/rspack/tests/configCases/runtime/namespace-cache/proxy.js
packages/rspack/tests/configCases/runtime/namespace-cache/utils.js
packages/rspack/tests/configCases/runtime/namespace-cache/webpack.config.js

Give correct key for namespace_cache initFragment

fix: should not contain duplicate initFragments for namespace_cache

---

packages/rspack-cli/bin/rspack
packages/rspack-cli/package.json
pnpm-lock.yaml

source-map-suport is used to decode js error frame to ts error frame which is not necessary(can be replaced with [enable-source-maps](https://nodejs.org/dist/latest-v12.x/docs/api/cli.html) and may introduce unexpected behaivor

chore: remove source-map-support

---

crates/node_binding/binding.d.ts
crates/node_binding/src/hook.rs
crates/node_binding/src/plugins/mod.rs
crates/rspack_binding_values/src/hooks.rs
crates/rspack_core/src/context_module_factory.rs
crates/rspack_core/src/plugin/api.rs
crates/rspack_core/src/plugin/plugin_driver.rs
packages/rspack/src/Compiler.ts
packages/rspack/src/ContextModuleFactory.ts
packages/rspack/tests/configCases/hooks/context-module-after-resolve/dir/foo.js
packages/rspack/tests/configCases/hooks/context-module-after-resolve/index.js
packages/rspack/tests/configCases/hooks/context-module-after-resolve/webpack.config.js

Before Rspack has a bug that uses normalModuleFactory as argument, and is passed to contextModuleFactory hook, after fixing this, some users have used the afterResolve hook from normalModuleFactory, so add this hook to contextModuleFactory

fix: add context module afterResolve hook

---

packages/rspack-dev-server/src/server.ts

修复在 node 16.9 以下版本中，启动  @rspack/dev-server 报错的问题。
报错内容如下：
```
[rspack-cli] Error: Cannot find module '/Users/xxx/app/node_modules/@rspack/dev-server/client/index.js.js'
at createEsmNotFoundErr (node:internal/modules/cjs/loader:960:15)
at finalizeEsmResolution (node:internal/modules/cjs/loader:953:15)
at trySelf (node:internal/modules/cjs/loader:458:12)
at Function.Module._resolveFilename (node:internal/modules/cjs/loader:910:24)
at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/Users/xxx/app/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
at Function.resolve (node:internal/modules/cjs/helpers:100:19)
at RspackDevServer.addAdditionalEntries (/Users/xxx/app/node_modules/@rspack/dev-server/src/server.ts:416 …
```

fix: @rspack/dev-server Cannot find module

---

packages/rspack/jest.config.js
packages/rspack/package.json
pnpm-lock.yaml

source remapping will cause uncertainty about snapshot code, so we need to disable it for snapshot, 
see https://github.com/kulshekhar/ts-jest/issues/727#issuecomment-1022957909

chore: disable jest sourcemap support

---

.gitignore
Cargo.lock
Cargo.toml
crates/rspack_loader_swc/Cargo.toml
crates/rspack_loader_swc/src/lib.rs
crates/rspack_plugin_css/src/parser_and_generator/mod.rs
crates/rspack_plugin_css/src/utils.rs
packages/rspack/package.json
packages/rspack/tests/ConfigTestCases.template.js
packages/rspack/tests/StatsTestCases.basictest.js
packages/rspack/tests/__snapshots__/StatsTestCases.basictest.js.snap
packages/rspack/tests/configCases/builtin-swc-loader/swc-plugin/index.js
packages/rspack/tests/configCases/builtin-swc-loader/swc-plugin/webpack.config.js
packages/rspack/tests/statsCases/loader-builtin-swc-plugin-warn/index.js
pnpm-lock.yaml

Fixes  #5763 
I've locked `rkyv` to version which is used in swc and wrapped tuple in a struct as it wouldn't deserialize with an older `rkyv` version

fix(rspack_loader_swc): enable SWC plugins

---

crates/rspack_core/src/module_factory.rs

- fixes: web-infra-dev/rsbuild#1704
- fixes: web-infra-dev/rspress#464
when the a file path in `file_dependencies`/`fileDependencies` differs from the one watchpack resolved, it will be removed from the watch list.
examples:
| fileDependencies | watchpack resolved |
|---|---|
| `/path/to/./src/Operation.graphql.ts` |`/path/to/src/Operation.graphql.ts` |
| `/path/to/foo/../src/Operation.graphql.ts` |  `/path/to/src/Operation.graphql.ts` |
| `C:/path/to/bar.ts` | `C:\path\to\bar.ts` |
| `C:\path\to\foo/bar.ts` | `C:\path\to\foo\bar.ts` |
which will lead to
1. a rebuild will be triggered right after initial build
2. changes on these files will not trigger a rebuild
when `artifactDirectory` in `relay.config.js` is set to `./foo`, the import statement for an operation will be `import Operation …

fix: fix some "changes didn't emit a rebuild" issues

---

crates/rspack_plugin_css/src/dependency/css_module_export.rs

1. Closed https://github.com/web-infra-dev/rspack/issues/5869

fix: 🐛 should not mangle css module identifier

---

crates/rspack_core/src/context_module_factory.rs
crates/rspack_core/src/normal_module_factory.rs
crates/rspack_core/src/resolver/mod.rs
crates/rspack_core/src/resolver/resolver_impl.rs
packages/rspack/tests/__snapshots__/StatsTestCases.basictest.js.snap
packages/rspack/tests/configCases/loader/rspack-issue-4297/fragmentloader.js
packages/rspack/tests/configCases/loader/rspack-issue-4297/index.js
packages/rspack/tests/configCases/loader/rspack-issue-4297/lib.js
packages/rspack/tests/configCases/loader/rspack-issue-4297/queryloader.js
packages/rspack/tests/configCases/loader/rspack-issue-4297/webpack.config.js

fix #4297
resolved resource without ? and #, its resourceQuery and resourceFragment should be empty string instead of None

fix: empty resource query and fragment

---

crates/node_binding/binding.d.ts
crates/rspack_binding_values/src/chunk_group.rs
crates/rspack_core/src/chunk.rs
crates/rspack_core/src/chunk_group.rs
crates/rspack_core/src/compiler/compilation.rs
crates/rspack_plugin_runtime/src/helpers.rs
crates/rspack_plugin_runtime/src/module_chunk_format.rs
packages/rspack/src/ChunkGroup.ts
packages/rspack/src/Compilation.ts
packages/rspack/src/Entrypoint.ts
packages/rspack/tests/configCases/plugins/get-runtime-chunk/test.config.js
packages/rspack/tests/configCases/plugins/get-runtime-chunk/webpack.config.js

feat: entrypoint.getRuntimeChunk

---

Cargo.lock
Cargo.toml
crates/node_binding/binding.d.ts
crates/node_binding/src/plugins/interceptor.rs
crates/node_binding/src/plugins/mod.rs
crates/rspack_napi_shared/src/callback.rs
crates/rspack_napi_shared/src/lib.rs
crates/rspack_napi_shared/src/new_tsfn.rs

This PR refactored the old tsfn impl. The original impl has a few problems as follows:
- **Type definition** It's hard to read whether the original JS function returned `Promise<T>` or `T`. This is originally designed for loader, since JS Loaders can be called both synchronously and asynchronously. This usage has been spread to most of JS functions and each signature should be defined explicitly.
- **Type conversion** The original tsfn locates in the NAPI-RS crate, it's hard for us to extract implementation like https://github.com/napi-rs/napi-rs/pull/1475 because of the orphan rule especially paired with generics which trait constraint is defined in NAPI-RS.
In this new tsfn impl, the improvements are as follows:
- **Type definition** Type should be explicitly defined, such as …

refactor: support new tsfn (stage 1)

---

packages/rspack/src/Compilation.ts
packages/rspack/src/Compiler.ts
packages/rspack/src/MultiCompiler.ts
packages/rspack/src/config/zod.ts
packages/rspack/src/node/NodeWatchFileSystem.ts

part of [#4640](https://github.com/web-infra-dev/rspack/issues/4640)
This pr fixes all ts-expect-error in packages/rspack/src/Compiler.ts and packages/rspack/src/Compilation.ts. Errors are most related to
* Align two type `WatchOptions` present in rspack
* Solve the type problems caused by optional `args` in type `LogFunction`
* Solve some type problems concerning optional or required attributes
```
cd packages/rspack
pnpm build
```

fix(typing): fix partial ts-expect-error in  packages/rspack 

---

crates/node_binding/binding.d.ts
crates/node_binding/src/plugins/mod.rs
crates/rspack_binding_values/src/hooks.rs
crates/rspack_binding_values/src/normal_module_factory.rs
crates/rspack_core/src/context_module_factory.rs
crates/rspack_core/src/normal_module_factory.rs
crates/rspack_core/src/plugin/args.rs
packages/rspack/src/Compiler.ts
packages/rspack/tests/configCases/hooks/after-resolve-resource/a.js
packages/rspack/tests/configCases/hooks/after-resolve-resource/b.js
packages/rspack/tests/configCases/hooks/after-resolve-resource/c.js
packages/rspack/tests/configCases/hooks/after-resolve-resource/duplicate.js
packages/rspack/tests/configCases/hooks/after-resolve-resource/request.js
packages/rspack/tests/configCases/hooks/after-resolve-resource/resource.js
packages/rspack/tests/configCases/hooks/after-resolve-resource/test.config.js
packages/rspack/tests/configCases/hooks/after-resolve-resource/webpack.config.js

Relate #5912
- After resolve hook should run before create module, just like webpack
- After resolve hook can modify resource and request
> Warning: this will result in significant performance regression

feat: support modify resource in after resolve hook

---

packages/rspack-test-tools/src/case/index.ts
packages/rspack-test-tools/src/case/treeshaking.ts
packages/rspack-test-tools/src/case/watch.ts
packages/rspack-test-tools/src/processor/treeshaking.ts
packages/rspack-test-tools/src/test/creator.ts
packages/rspack-test-tools/tests/TreeShaking.test.js

chore: run tree shaking by new test runner

---

crates/rspack_plugin_javascript/src/dependency/esm/harmony_export_imported_specifier_dependency.rs
packages/rspack/tests/TestCases.template.js
packages/rspack/tests/cases/esm/export-star-missing/errors.js
packages/rspack/tests/cases/esm/export-star-missing/index.js
packages/rspack/tests/cases/esm/export-star-missing/lib.js

fix panic when export star a missing module

fix: export star missing module panic

---

packages/create-rspack/index.js

Hi~ I noticed that create-rspack cannot exit during creation. I hope this could help.

feat(create-rspack): support cancel operation

---

website/package.json
website/pnpm-lock.yaml
website/rspress.config.ts

This PR adds Open Sans as the default font for Rspack website, uses https://github.com/rspack-contrib/rspress-plugin-font-open-sans.
The Node.js new website is using Open Sans and looks good. see http://nodejs.org/

docs: use Open Sans as the default font

---

crates/node_binding/binding.d.ts
crates/node_binding/src/hook.rs
crates/node_binding/src/plugins/interceptor.rs
crates/node_binding/src/plugins/mod.rs
crates/rspack_binding_values/src/hooks.rs
crates/rspack_core/src/compiler/compilation.rs
crates/rspack_core/src/plugin/api.rs
crates/rspack_core/src/plugin/plugin_driver.rs
crates/rspack_plugin_progress/src/lib.rs
packages/rspack/src/Compilation.ts
packages/rspack/src/Compiler.ts

refactor: optimize modules and after optimize modules hook

---

crates/rspack_plugin_javascript/src/visitors/dependency/parser/walk_block_pre.rs
packages/rspack/tests/configCases/plugins/provide-plugin-issue-5994/harmony.js
packages/rspack/tests/configCases/plugins/provide-plugin-issue-5994/index.js
packages/rspack/tests/configCases/plugins/provide-plugin-issue-5994/mod.js
packages/rspack/tests/configCases/plugins/provide-plugin-issue-5994/webpack.config.js

fix: missing define_variable for export declarations

---

crates/rspack_core/src/external_module.rs
crates/rspack_core/src/lib.rs
crates/rspack_plugin_css/src/plugin/impl_plugin_for_css_plugin.rs
crates/rspack_plugin_css/src/plugin/mod.rs
crates/rspack_plugin_css/tests/fixtures/webpack/at-import-in-the-middle/expected/main.css
crates/rspack_plugin_css/tests/fixtures/webpack/at-import-in-the-middle/snapshot/output.snap
packages/rspack/tests/__snapshots__/ConfigTestCases.basictest.js.snap
packages/rspack/tests/configCases/css/at-import-in-the-top/a.css
packages/rspack/tests/configCases/css/at-import-in-the-top/b.css
packages/rspack/tests/configCases/css/at-import-in-the-top/c.css
packages/rspack/tests/configCases/css/at-import-in-the-top/index.js
packages/rspack/tests/configCases/css/at-import-in-the-top/webpack.config.js

fix issue [6000](https://github.com/web-infra-dev/rspack/issues/6000)

fix: Move @import to top of concatenated CSS output (#6000)

---

package.json

Modify the format:js script command to make it compatible with the Windows environment.

chore: make format compatible with windows

---

packages/rspack/tests/configCases/plugins/provide-plugin-issue-5994/default.js
packages/rspack/tests/configCases/plugins/provide-plugin-issue-5994/index.js
packages/rspack/tests/configCases/plugins/provide-plugin-issue-5994/webpack.config.js

Related: https://github.com/web-infra-dev/rspack/pull/6012/files#r1537020562

test(rspack): add test for ExportDefaultDecleration case with ProvidePlugin

---

website/package.json
website/pnpm-lock.yaml
website/rspress.config.ts

Integrate Rsbuild plugins for website:
- Use `rsbuild-plugin-google-analytics` to use google analytics. 
- Use `rsbuild-plugin-open-graph` to generate open graph meta tags.
- Bump `rsfamily-nav-icon` v1.0.2 to improve bundle size.
See:
- https://github.com/rspack-contrib/rsbuild-plugin-google-analytics
- https://github.com/rspack-contrib/rsbuild-plugin-open-graph
- https://github.com/rspack-contrib/rsfamily-nav-icon/commits/main/

docs: integrate Rsbuild plugins for website

---

website/components/i18n/en.json
website/components/i18n/zh.json
website/docs/en/config/builtins.mdx
website/docs/en/config/plugins.mdx
website/docs/en/guide/language-support.mdx
website/docs/en/misc/branding.mdx
website/docs/zh/config/builtins.mdx
website/docs/zh/config/plugins.mdx
website/docs/zh/guide/language-support.mdx
website/docs/zh/misc/branding.mdx

Remove the deprecated rspack-html-plugin & rspack-plugin-node-polyfill from the website.
See: https://github.com/web-infra-dev/rspack/pull/5988

docs: remove deprecated html and node-polyfill plugin

---

packages/rspack/src/exports.ts
packages/rspack/src/lib/NormalModuleReplacementPlugin.ts
packages/rspack/tests/configCases/plugins/normal-module-replacement-plugin/index.js
packages/rspack/tests/configCases/plugins/normal-module-replacement-plugin/request.v1.js
packages/rspack/tests/configCases/plugins/normal-module-replacement-plugin/request.v2.js
packages/rspack/tests/configCases/plugins/normal-module-replacement-plugin/resource.bar.js
packages/rspack/tests/configCases/plugins/normal-module-replacement-plugin/resource.foo.js
packages/rspack/tests/configCases/plugins/normal-module-replacement-plugin/webpack.config.js

feat(rspack): NormalModuleReplacementPlugin

---

crates/rspack_allocator/Cargo.toml
crates/rspack_allocator/src/lib.rs

closes: #6072
related: #6065
linux musl binding now performs ~3x times faster than before.
```
Running case debian (GNU)
Rspack compiled successfully in 1.67 s
Running case alpine (musl)
Rspack compiled successfully in 6.39 s
Running case alpine-mimalloc-v1 (musl, redirecting malloc to mimalloc 1.8.2)
Rspack compiled successfully in 1.78 s
Running case alpine-mimalloc-v2 (musl, redirecting malloc to mimalloc 2.1.2)
Rspack compiled successfully in 1.70 s
```
```
Running case debian (GNU, nothing change in this pr)
Rspack compiled successfully in 1.86 s
Running case alpine (musl, with mimalloc rust binding)
Rspack compiled successfully in 1.97 s
Running case alpine-mimalloc-v1 (musl, with mimalloc rust binding, redirecting malloc to mimalloc 1.8.2)
Rspack compiled successfully in 1.89 s …
```

perf: use mimalloc for musl target

---

packages/rspack-test-tools/tests/__snapshots__/Defaults.unittest.js.snap
packages/rspack/src/Compiler.ts
packages/rspack/src/builtin-plugin/EntryPlugin.ts
packages/rspack/src/config/defaults.ts
packages/rspack/src/config/zod.ts
packages/rspack/src/rspackOptionsApply.ts
website/docs/en/config/experiments.mdx
website/docs/zh/config/experiments.mdx

refactor: remove rspackFuture.disableApplyEntryLazily

---

.github/workflows/release-canary.yml

It' error-prone that users use canary version but can't use it in specific platform, fix #6101

chore: release all platform for canary release

---

crates/rspack_plugin_css/src/parser_and_generator/mod.rs
packages/rspack/src/config/normalization.ts
webpack-test/configCases/css/default-exports-parser-options/index.js
webpack-test/configCases/css/default-exports-parser-options/style.module.css
webpack-test/configCases/css/default-exports-parser-options/webpack.config.js
webpack-test/configCases/css/named-exports-parser-options/index.js
website/docs/en/config/experiments.mdx
website/docs/en/config/module.mdx
website/docs/zh/config/experiments.mdx
website/docs/zh/config/module.mdx
website/project-words.txt

https://github.com/webpack/webpack/pull/18271

feat: support css default export and named export at same time

---

crates/swc_plugin_import/src/legacy_case.rs
crates/swc_plugin_import/src/lib.rs
packages/rspack/tests/configCases/builtin-swc-loader/plugin-import/index.js
packages/rspack/tests/configCases/builtin-swc-loader/plugin-import/legacy-babel-plugin-import.js
packages/rspack/tests/configCases/builtin-swc-loader/plugin-import/src/legacy-babel-plugin-import/index.js
packages/rspack/tests/configCases/builtin-swc-loader/plugin-import/src/legacy-babel-plugin-import/lib/x-i-p-object/x_i_p_object.js
packages/rspack/tests/configCases/builtin-swc-loader/plugin-import/webpack.config.js
website/docs/en/guide/builtin-swc-loader.mdx
website/docs/zh/guide/builtin-swc-loader.mdx

fixes: #6060
- Add `legacyKebabCase` for compatibility with babel-plugin-import versions [before 1.13.7](https://github.com/umijs/babel-plugin-import/blob/8efa0aa1472f0e6c1d574eb04bf2b9100fccf5a7/src/Plugin.js#L4-L6)
- Add `legacySnakeCase` for compatibility with babel-plugin-import versions [before 1.13.7](https://github.com/umijs/babel-plugin-import/blob/8efa0aa1472f0e6c1d574eb04bf2b9100fccf5a7/src/Plugin.js#L4-L6) using [camel2UnderlineComponentName](https://github.com/umijs/babel-plugin-import/blob/8cc97c8e394891a684d7300d26cbe2b86f20d076/src/Plugin.js#L68-L69)
(yes babel-plugin-import breaks its core naming convention behavior in a patch update

feat(swc_plugin_import): legacy kebab/snake case for legacy babel-plugin-import compatibility

---

Cargo.lock
Cargo.toml
crates/rspack_util/Cargo.toml
crates/rspack_util/src/comparators.rs

The current implement of `compare_ids` always alloc memory for `a`, `b` unnecessarily. we can use `unicase` to implement 0-allocation compare. this is expected to be good for performance.
The `unicase` crate is already in our dependency tree, so it's not a new dependency.
This PR also modifies `compare_numbers` to Rusty implementation.

perf(core): Use unicase for compare_ids

---

packages/rspack/tests/copyPlugin/helpers/run.js
packages/rspack/tests/helpers/AsyncEventIterator.js

related: #6084
- https://github.com/web-infra-dev/rspack/actions/runs/8505294188/job/23293849274#step:9:65
- https://github.com/web-infra-dev/rspack/actions/runs/8507670127/job/23300468307#step:8:66
```log
packages/rspack test: FAIL tests/copyPlugin/CopyPlugin.test.js (66.335 s, 34 MB heap size)
packages/rspack test:   ● CopyPlugin › watch mode › should include all files when multiple patterns used
packages/rspack test:     TypeError: Cannot read properties of undefined (reading 'compilation')
packages/rspack test:        9 | 	const assets = {};
packages/rspack test:       10 |
packages/rspack test:     > 11 | 	Reflect.ownKeys(stats.compilation.assets)
packages/rspack test:          | 	                      ^
packages/rspack test:       12 | 		.filter(a => a !== "main.js")
packages/rspack …
```

test: make CopyPlugin.test faster and more stable

---

packages/rspack-test-tools/src/helper/legacy/copyDiff.js
packages/rspack/tests/WatchTestCases.template.js

related #6084  
- https://github.com/web-infra-dev/rspack/actions/runs/8507289799/job/23299027187#step:6:198
- https://github.com/web-infra-dev/rspack/actions/runs/8507289799/job/23299027187#step:6:53
```log
packages/rspack test: FAIL tests/WatchTestCases.longtest.js (32 MB heap size)
packages/rspack test:   ● WatchTestCases › compiler › multiply-compiler › multiply-compiler should compile
packages/rspack test:     EEXIST: file already exists, mkdir '/home/webinfra/ec2-linux-ci-3/_work/rspack/rspack/packages/rspack/tests/js'
packages/rspack test:       74 | 		beforeAll(() => {
packages/rspack test:       75 | 			let dest = path.join(__dirname, "js");
packages/rspack test:     > 76 | 			if (!fs.existsSync(dest)) fs.mkdirSync(dest);
packages/rspack test:          | …
```

test: fix random ci failure

---

crates/rspack_plugin_javascript/src/plugin/flag_dependency_exports_plugin.rs

fix: 🐛 use set queue instead of `VecDeq`

---

crates/rspack_core/src/exports_info.rs
crates/rspack_core/src/module.rs

perf: ⚡️ reduce alloc in ModuleGraphAccessor impl

---

Cargo.lock
Cargo.toml
crates/rspack_core/src/module_factory.rs
crates/rspack_core/src/normal_module_factory.rs
crates/rspack_core/src/options/context.rs
crates/rspack_core/src/resolver/mod.rs
crates/rspack_plugin_copy/src/lib.rs
crates/rspack_util/src/identifier.rs

- update `sugar_path` to 1.2.0
- There are no changes on internal logic.
- This update only removes some dropped API

chore(rust/dep): update `sugar_path` to 1.2.0

---

packages/create-rspack/template-react-ts/package.json
packages/create-rspack/template-react/package.json
packages/create-rspack/template-vanilla/package.json
packages/create-rspack/template-vue/package.json
pnpm-lock.yaml

use workspace rspack version in create-rspack template, so we can test local use  create-rspack/template-xxx.
Note: it is only effect local, this version will be rewritten when create template.
https://github.com/web-infra-dev/rspack/blob/49f9435c83d19c05768d06e391292fdf8c95af7b/packages/create-rspack/index.js#L99-L115

chore: use workspace rspack version in create-rspack template

---

website/docs/en/config/optimization.mdx
website/docs/en/guide/tree-shaking.mdx
website/docs/zh/config/optimization.mdx
website/docs/zh/guide/tree-shaking.mdx

- Add docs about transform imports in sideEffects
- Remove useless `removeAvailableModules` option
Need https://github.com/rspack-contrib/rspack-examples/pull/49

docs: modify treeshaking sideEffects docs and remove removeAvaModules config

---

crates/rspack_plugin_javascript/src/plugin/flag_dependency_exports_plugin.rs
crates/rspack_plugin_javascript/src/plugin/flag_dependency_usage_plugin.rs
crates/rspack_plugin_javascript/src/utils/mod.rs
crates/rspack_plugin_javascript/src/utils/queue.rs

Webpack uses SetQueue under the hood, thus can reduce many duplication computations

perf: use set as queue for flag_dependency_usage_plugin

---

website/docs/en/guide/tree-shaking.mdx
website/docs/zh/guide/tree-shaking.mdx

Add re-exports optimization diagram to the tree shaking document:

docs: add re-exports optimization diagram

---

crates/rspack_loader_swc/src/lib.rs
packages/rspack/package.json
packages/rspack/tests/configCases/source-map/source-map-loader/a.js
packages/rspack/tests/configCases/source-map/source-map-loader/a.js.map
packages/rspack/tests/configCases/source-map/source-map-loader/index.js
packages/rspack/tests/configCases/source-map/source-map-loader/webpack.config.js
pnpm-lock.yaml

fix #5480
`std::mem::take` will be replaced with the default value. Therefore, subsequent loaders cannot obtain the correct value.

fix: builtin swc loader input sourcemap

---

crates/rspack_plugin_css/src/parser_and_generator/mod.rs
crates/rspack_plugin_css/src/visitors/mod.rs
packages/rspack/tests/configCases/css/export-selector/imported.js
packages/rspack/tests/configCases/css/export-selector/index.js
packages/rspack/tests/configCases/css/export-selector/reexported.js
packages/rspack/tests/configCases/css/export-selector/style.module.css
packages/rspack/tests/configCases/css/export-selector/webpack.config.js

support :export in css module
close #5454

feat: support css module :export

---

website/docs/en/misc/join-us.mdx

There are two "who we are" titles in the page, causing this:

docs(website): fix broken right nav in join-us page

---

website/README.md
website/docs/en/guide/tree-shaking.mdx
website/docs/zh/guide/tree-shaking.mdx

Add image assets guide to website README.
We use `https://assets.rspack.dev/` to host assets. The `rsfamily-design-resources.netlify.app` is no longer used because it might be blocked in some areas.

docs: add image assets guide to website README

---

website/docs/en/index.md
website/docs/zh/index.md

Most landing pages put "get started" as the primary button.

docs(website): change "get started" button to primary and "intro" button to secondary

---

crates/node_binding/binding.d.ts
crates/rspack_binding_values/src/compilation.rs
crates/rspack_binding_values/src/filename.rs
crates/rspack_binding_values/src/path_data.rs
packages/rspack/etc/api.md
packages/rspack/src/Compilation.ts
packages/rspack/src/config/zod.ts
packages/rspack/tests/configCases/hooks/compat-path-data-chunk-contenthash/test.config.js
packages/rspack/tests/configCases/hooks/compat-path-data-chunk-contenthash/webpack.config.js

before `pathdata.chunk.contentHash` is only `HashMap<String, String>`, but in practice (css-loader) it can be a `String`

fix: napi value convert error in css-loader

---

.github/ISSUE_TEMPLATE/1-bug-report.en-US.yml
webpack-examples/README.md
webpack-test/README.md

Update package manager of webpack-test README, we can only use `pnpm` in the Rspack repo.

chore: update package manager of webpack-test README

---

website/docs/en/guide/language-support.mdx
website/docs/en/guide/react.mdx
website/docs/en/guide/vue.mdx
website/docs/zh/guide/language-support.mdx
website/docs/zh/guide/react.mdx
website/docs/zh/guide/vue.mdx

Use PackageManagerTabs to display install commands.
It is a builtin component of Rspress and supports `Bun`.
see: https://rspress.dev/api/client-api/api-components.html#packagemanagertabs

docs: use PackageManagerTabs to display install commands

---

.github/workflows/test-ng.yml
packages/rspack-test-tools/etc/api.md
packages/rspack-test-tools/src/runner/basic.ts
packages/rspack-test-tools/src/runner/hot-step.ts
packages/rspack-test-tools/src/runner/hot.ts
packages/rspack-test-tools/src/runner/multiple.ts
packages/rspack-test-tools/src/runner/normal.ts
packages/rspack-test-tools/src/runner/runner/basic.ts
packages/rspack-test-tools/src/runner/runner/hot.ts
packages/rspack-test-tools/src/runner/runner/watch.ts
packages/rspack-test-tools/src/runner/type.ts
packages/rspack-test-tools/src/runner/watch.ts
packages/rspack-test-tools/src/type.ts

fix: stats in multiple runner

---

crates/rspack_plugin_devtool/src/lib.rs
crates/rspack_plugin_devtool/src/mapped_assets_cache.rs

Fix performance degradation cased by https://github.com/web-infra-dev/rspack/pull/6125 .

fix: performance degradation for auxiliary files

---

website/cspell.config.cjs
website/docs/en/blog/announcing-0.4.mdx
website/docs/en/config/builtins.mdx
website/docs/en/config/optimization.mdx
website/docs/en/guide/module-federation.mdx
website/docs/zh/blog/announcing-0.4.mdx
website/docs/zh/config/builtins.mdx
website/docs/zh/config/optimization.mdx
website/docs/zh/guide/module-federation.mdx

Fix all broken plugin links, the plugin documents has been moved to separate pages.

docs: fix all broken plugin links

---

website/components/i18n/en.json
website/components/i18n/zh.json
website/docs/en/guide/production.mdx
website/docs/zh/guide/production.mdx

`builtins.minifyOptions` has been removed since v0.5.0. This PR updates the minification guides to use `SwcJsMinimizerRspackPlugin`.

docs: update minification guides

---

Cargo.lock
crates/rspack_plugin_swc_css_minimizer/Cargo.toml
crates/rspack_plugin_swc_css_minimizer/src/lib.rs
crates/rspack_plugin_swc_js_minimizer/src/lib.rs
packages/rspack/tests/configCases/builtins/minify-with-query/index.css
packages/rspack/tests/configCases/builtins/minify-with-query/index.js
packages/rspack/tests/configCases/builtins/minify-with-query/webpack.config.js

fix: should minimize asset with query

---

packages/rspack/etc/api.md
packages/rspack/src/builtin-loader/swc/index.ts
packages/rspack/src/builtin-loader/swc/pluginImport.ts
packages/rspack/src/builtin-loader/swc/react.ts
packages/rspack/src/builtin-loader/swc/relay.ts
packages/rspack/src/builtin-loader/swc/types.ts
packages/rspack/src/exports.ts
packages/rspack/tests/hotCases/context/request-position/snapshot/web/1.snap.txt
website/docs/en/blog/announcing-0.5.mdx
website/docs/en/guide/builtin-swc-loader.mdx
website/docs/en/guide/vue.mdx
website/docs/zh/blog/announcing-0.5.mdx
website/docs/zh/guide/builtin-swc-loader.mdx
website/docs/zh/guide/vue.mdx

Provide type declaration for builtin:swc-loader. Example:
```js
// rspack.config.js
module: {
rules: [
{
test: /\.js$/,
use: {
loader: 'builtin:swc-loader',
/** @type {import('@rspack/core').SwcLoaderOptions} */
options: {
// some options
},
},
},
],
},
};
```
Resolve https://github.com/web-infra-dev/rspack/issues/4485
Some types are modified from https://github.com/swc-project/swc/blob/16a38851/packages/types/index.ts#L647

feat: provide type declaration for builtin:swc-loader

---

diffcases/arco-pro/rspack.config.js
diffcases/arco-pro/webpack.config.js
packages/create-rspack/template-react-ts/rspack.config.js
packages/create-rspack/template-react/rspack.config.js
packages/create-rspack/template-vue/rspack.config.js
packages/rspack-test-tools/rspack.config.js
packages/rspack/tests/configCases/builtin-swc-loader/inline-pitching/webpack.config.js
packages/rspack/tests/configCases/builtin-swc-loader/react-runtime-automic/webpack.config.js
packages/rspack/tests/configCases/builtin-swc-loader/react-runtime-classic/webpack.config.js
packages/rspack/tests/configCases/builtin-swc-loader/swc-plugin/webpack.config.js
packages/rspack/tests/configCases/loader/loader-builtin-swc/webpack.config.js
packages/rspack/tests/configCases/source-map/source-map/webpack.config.js
website/docs/en/blog/announcing-0.3.mdx
website/docs/en/blog/announcing-0.5.mdx
website/docs/en/guide/builtin-swc-loader.mdx
website/docs/en/guide/migrate-from-webpack.mdx
website/docs/en/guide/vue.mdx
website/docs/zh/blog/announcing-0.3.mdx
website/docs/zh/blog/announcing-0.5.mdx
website/docs/zh/guide/builtin-swc-loader.mdx
website/docs/zh/guide/migrate-from-webpack.mdx
website/docs/zh/guide/vue.mdx

Two changes in our templates and documentations:
- Remove `sourceMap: true` of swc-loader, because swc-loader will read the `devtool` option of Rspack and set source map automatically, see: https://github.com/web-infra-dev/rspack/blob/599ce4693c8d184a056a0ba90d64008cf6b564ad/crates/rspack_loader_swc/src/lib.rs#L83-L86
- Rename `sourceMap: false` to `sourceMaps: false`, the `sourceMap` is a legacy name and we should use `sourceMaps`. see: https://github.com/web-infra-dev/rspack/blob/599ce4693c8d184a056a0ba90d64008cf6b564ad/crates/rspack_loader_swc/src/options.rs#L117-L119

fix(create-rspack): remove useless sourceMap option in templates

---

packages/rspack/hot/emitter.js
packages/rspack/package.json
pnpm-lock.yaml

Remove the `events` dependency of `@rspack/core`, it is only used by hot client code and can be replaced with a simple handwritten event emitter:
see: https://github.com/web-infra-dev/rspack/issues/5097

perf(core): remove events dependency

---

Cargo.lock
crates/rspack_core/Cargo.toml

* a logging change https://github.com/oxc-project/oxc-resolver/releases 
* and a fix for on-call https://github.com/oxc-project/oxc-resolver/pull/134

chore: bump oxc_resolver to v1.6.7

---

crates/rspack_core/src/exports_info.rs

Align with webpack, [code](https://github.com/webpack/webpack/blob/b630e21e10f1dbee311dc07b218b49cea4df54a4/lib/ExportsInfo.js#L275)

fix: align get_nested_exports_info with webpack

---

crates/rspack_core/src/compiler/make/repair/build.rs
crates/rspack_core/src/compiler/make/repair/process_dependencies.rs

fix: process dependencies task remove resolve_options

---

packages/rspack-test-tools/tests/configCases/cache/issues-6381/a/a.js
packages/rspack-test-tools/tests/configCases/cache/issues-6381/index.js
packages/rspack-test-tools/tests/configCases/cache/issues-6381/webpack.config.js
packages/rspack/src/config/defaults.ts

close https://github.com/web-infra-dev/rspack/issues/6381
`{ timestamp: true}` should has the same meaning of `{ timestamp: true, hash: false }`
We need to process this default value when we pass it to rust side.

fix(config): snapshot.module accept `{ timestamp: true}`

---

packages/rspack/src/config/defaults.ts

#6381  #6387 
`{ hash: true }` `{ timestamp: true }` and `{ timestamp: true, hash: true }`  should be three different behaviors.
I think this is a very misleading configuration.
https://webpack.js.org/configuration/other-options/#builddependencies
cases
`{}` and `{ timestamp: false, hash: false }` ->  `{ timestamp: false, hash: false }`
`{ hash: true }` -> `{ timestamp: false, hash: true }`
`{ timestamp: true }` -> `{ timestamp: true, hash: false }`
`{ timestamp: true, hash: true }`

fix(config): support snapshot config {timestamp: true} and {hash: true}

---

crates/rspack_core/src/context_module.rs
crates/rspack_core/src/module_graph/mod.rs
crates/rspack_core/src/options/module.rs
packages/rspack-test-tools/tests/runtimeDiffCases/module-context-module/src/index.js
packages/rspack-test-tools/tests/runtimeDiffCases/module-context-module/src/namespace-object-lazy/cjs-esmodule.js
packages/rspack-test-tools/tests/runtimeDiffCases/module-context-module/src/namespace-object-lazy/cjs.js
packages/rspack-test-tools/tests/runtimeDiffCases/module-context-module/src/namespace-object-lazy/dir-cjs/null.js
packages/rspack-test-tools/tests/runtimeDiffCases/module-context-module/src/namespace-object-lazy/dir-cjs/one.js
packages/rspack-test-tools/tests/runtimeDiffCases/module-context-module/src/namespace-object-lazy/dir-cjs/three.js
packages/rspack-test-tools/tests/runtimeDiffCases/module-context-module/src/namespace-object-lazy/dir-cjs/two.js
packages/rspack-test-tools/tests/runtimeDiffCases/module-context-module/src/namespace-object-lazy/dir-harmony/one.js
packages/rspack-test-tools/tests/runtimeDiffCases/module-context-module/src/namespace-object-lazy/dir-harmony/three.js
packages/rspack-test-tools/tests/runtimeDiffCases/module-context-module/src/namespace-object-lazy/dir-harmony/two.js
packages/rspack-test-tools/tests/runtimeDiffCases/module-context-module/src/namespace-object-lazy/dir-mixed/json.json
packages/rspack-test-tools/tests/runtimeDiffCases/module-context-module/src/namespace-object-lazy/dir-mixed/null.js
packages/rspack-test-tools/tests/runtimeDiffCases/module-context-module/src/namespace-object-lazy/dir-mixed/one.js
packages/rspack-test-tools/tests/runtimeDiffCases/module-context-module/src/namespace-object-lazy/dir-mixed/three.js
packages/rspack-test-tools/tests/runtimeDiffCases/module-context-module/src/namespace-object-lazy/dir-mixed/two.js
packages/rspack-test-tools/tests/runtimeDiffCases/module-context-module/src/namespace-object-lazy/index.js
webpack-test/cases/runtime/issue-15518/test.filter.js

refactor: diff context module lazy once mode

---

website/docs/zh/index.md

docs: fix banner link

---

crates/rspack_plugin_javascript/src/webpack_comment.rs
packages/rspack-test-tools/tests/builtinCases/plugin-javascript/magic_comment/index.js
packages/rspack-test-tools/tests/builtinCases/plugin-javascript/magic_comment/snapshot/output.snap.txt
packages/rspack-test-tools/tests/builtinCases/plugin-javascript/magic_comment/with_dot.js

Webpack allows any string for webpackChunkName: https://github.com/webpack/webpack/blob/c586c7b1e027e1d252d68b4372f08a9bce40d96c/lib/javascript/JavascriptParser.js#L4584-L4587
fixes #6358
Just a quick fix.
- will not work with texts containing the character that is same as the quote character, e.g, `"a\\"b"` (rust's regex does not support backreference)
- still does not support all js expressions like `Boolean(1)` which seems to be allowed in webpack

fix: allow all characters for webpackChunkName

---

crates/rspack_binding_values/src/compilation.rs
crates/rspack_core/src/compiler/compilation.rs
crates/rspack_core/src/compiler/hmr.rs
crates/rspack_core/src/compiler/make/mod.rs
crates/rspack_core/src/compiler/make/repair/factorize.rs
crates/rspack_core/src/compiler/make/repair/mod.rs
crates/rspack_core/src/compiler/module_executor/ctrl.rs
crates/rspack_core/src/compiler/module_executor/entry.rs
crates/rspack_core/src/compiler/module_executor/execute.rs
crates/rspack_core/src/compiler/module_executor/mod.rs
crates/rspack_core/src/compiler/module_executor/overwrite.rs
crates/rspack_core/src/utils/task_loop.rs

This PR refactor `execute module` by use make task loop, and it will improve the running speed of `execute module` by sharing module graph.
There are some task added by this PR.
* overwrite task - This task will analyze all tasks and send events to the ctrl task to collect module build status.
* entry task - This task is used to add a new entry for execute module entry dependency.
* execute task - This task is used to execute module.
* ctrl task - This task is used to collect all task status and start other task.

perf: optimize execute module

---

packages/rspack/etc/api.md
packages/rspack/src/exports.ts

I'm migrating [webpack-manifest-plugin](https://github.com/shellscape/webpack-manifest-plugin) to [rspack-manifest-plugin](https://github.com/rspack-contrib/rspack-manifest-plugin), and found that webpack exports the `Chunk` and `Module` types, but Rspack not.
This PR adds `Chunk` and `Module` exports for `@rspack/core`.
See: https://github.com/rspack-contrib/rspack-manifest-plugin/commit/2affdc9a1979d7f858b49250c9de6331bf7ea453

feat: export Chunk and Module types from `@rspack/core`

---

website/docs/en/_meta.json
website/docs/en/blog/_meta.json
website/docs/en/blog/index.mdx
website/docs/zh/_meta.json
website/docs/zh/blog/_meta.json
website/docs/zh/blog/index.mdx

Add blogs overview page to display all announcements and blog posts. This can help Rspack users understand the design philosophy of the Rspack team.

docs: add blogs overview page

---

packages/rspack-test-tools/tests/configCases/container-1-0/init-sharing-without-config/index.js
packages/rspack-test-tools/tests/configCases/container-1-0/init-sharing-without-config/webpack.config.js
packages/rspack/src/container/ModuleFederationPluginV1.ts

fix(mf): __webpack_init_sharing__ with empty config

---

packages/rspack-cli/src/commands/preview.ts
packages/rspack-cli/src/commands/serve.ts
packages/rspack-cli/tests/build/issue-6359/entry.js
packages/rspack-cli/tests/build/issue-6359/index.test.ts
packages/rspack-cli/tests/build/issue-6359/rspack.config.js

fixes #6359 
stop loading `@rspack/dev-server` on `rspack build` to prevent `process.env.WEBPACK_SERVE` being set to `true` on cli's build mode.
```js
// rspack.config.js
console.log(process.env.WEBPACK_SERVE);
// ...
};
```
| command | BEFORE | AFTER |
| --- | --- | --- |
| `rspack build` | `"true"` | `undefined` |
| `rspack serve` | `"true"` | `"true"` |
requiring `@rspack/dev-server` will resolve and load 433 files, so this change will also make the cli bootstrap faster on build mode.
When testing on mac studio m2 max: 
- ~100ms faster (io preheated)

fix(cli): load `@rspack/dev-server` on demand

---

package.json
packages/rspack/etc/api.md

Remove --force flag to fix prebundle.
The `--force` was introduced in https://github.com/web-infra-dev/rspack/pull/5075, and it doesn't seem necessary.
When using `--force` option, the `@rspack/core` package will be built multiple times:
- the first time:  run build script (`tsc` + `tsc-alias`), the outputs are correct.
- the second time: only run `tsc` (triggered by `tsc -b --force` of other packages), the outputs are incorrect because the `tsc-alias` is skipped.
So we should remove the `--force` flag to fix this.

fix: remove --force flag to fix prebundle

---

crates/rspack_core/src/compiler/module_executor/ctrl.rs

fix: add trace log for module executor

---

website/docs/en/plugins/rspack/html-rspack-plugin.mdx
website/docs/zh/plugins/rspack/html-rspack-plugin.mdx

Add comparison and examples for `rspack.HtmlRspackPlugin`, to help users choose HTML plugins and getting started.

docs(html-plugin): add comparison and examples

---

crates/node_binding/src/plugins/interceptor.rs
crates/rspack_core/src/cache/local/code_splitting_cache.rs
crates/rspack_core/src/compiler/compilation.rs
crates/rspack_core/src/compiler/hmr.rs
crates/rspack_core/src/compiler/make/cutout/clean_isolated_module.rs
crates/rspack_core/src/compiler/make/cutout/mod.rs
crates/rspack_core/src/compiler/make/mod.rs
crates/rspack_core/src/compiler/make/repair/mod.rs
crates/rspack_core/src/compiler/mod.rs
crates/rspack_core/src/compiler/module_executor/mod.rs
crates/rspack_core/src/module_graph/mod.rs
crates/rspack_core/src/tree_shaking/optimizer.rs
crates/rspack_plugin_dynamic_entry/src/lib.rs
crates/rspack_plugin_entry/src/lib.rs
crates/rspack_plugin_javascript/src/dependency/esm/harmony_import_specifier_dependency.rs
crates/rspack_plugin_library/src/assign_library_plugin.rs
crates/rspack_plugin_library/src/module_library_plugin.rs
crates/rspack_plugin_mf/src/container/container_plugin.rs
crates/rspack_plugin_progress/src/lib.rs
packages/rspack-test-tools/tests/hotCases/chunk/ensure-chunk-change-to-promise-all/snapshot/web/1.snap.txt
packages/rspack-test-tools/tests/hotCases/harmony/cjs-analyze-changed/snapshot/web/1.snap.txt

* remove some useless fields in compilation, include compilation.has_module_import_export_change and compilation.optimize_analyze_result_map
* make hooks align with webpack and remove make_param

refactor: make hooks remove make_param

---

crates/rspack_plugin_javascript/src/plugin/mod.rs
crates/rspack_plugin_library/src/amd_library_plugin.rs
crates/rspack_plugin_library/src/umd_library_plugin.rs
crates/rspack_plugin_runtime/src/array_push_callback_chunk_format.rs
packages/rspack-test-tools/tests/configCases/library/system-runtime/index.js
packages/rspack-test-tools/tests/configCases/library/system-runtime/test.config.js
packages/rspack-test-tools/tests/configCases/library/system-runtime/webpack.config.js

Compiling with `optimization.runtimeChunk=true` and `library.type="system"` may cause runtime error by an extra semicolon：
Before: 
```js
System.register([], function(__WEBPACK_DYNAMIC_EXPORT__, __system_context__) {
return {
execute: function() {
__WEBPACK_DYNAMIC_EXPORT__((self['webpackChunk'] = self['webpackChunk'] || []).push([["main"], {
"./index.js": (function () {
it("should run", ()=>{
expect(true);
});
}),
},function(__webpack_require__) {
var __webpack_exec__ = function(moduleId) { return __webpack_require__(__webpack_require__.s = moduleId) }
var __webpack_exports__ = (__webpack_exec__("./index.js"));
return __webpack_exports__;
}
]);)} // error occur in runtime
}
})
```

fix: systemjs runtime extra semicolon

---

website/docs/en/plugins/rspack/swc-js-minimizer-rspack-plugin.mdx
website/docs/zh/plugins/rspack/swc-js-minimizer-rspack-plugin.mdx

This option is in the source code but not in official website dcos.
https://github.com/web-infra-dev/rspack/blob/7e15f6816c0ff5f440d2f7eb07235a03b51686e8/crates/rspack_binding_options/src/options/raw_builtins/raw_swc_js_minimizer.rs#L82
Here's the docs on the official website:

docs: add missing `module` option of swc minimizer plugin

---

website/docs/en/plugins/rspack/css-extract-rspack-plugin.mdx

Fix duplicated ignoreOrder option in document:

docs: duplicated ignoreOrder option in CssExtractPlugin

---

crates/rspack_plugin_swc_js_minimizer/src/lib.rs
crates/rspack_plugin_swc_js_minimizer/src/minify.rs
packages/rspack-test-tools/tests/__snapshots__/Config.test.js.snap
packages/rspack-test-tools/tests/configCases/optimization/minimizer-esm-asset/index.js
packages/rspack-test-tools/tests/configCases/optimization/minimizer-esm-asset/pkg/package.json
packages/rspack-test-tools/tests/configCases/optimization/minimizer-esm-asset/pkg/pkg.js
packages/rspack-test-tools/tests/configCases/optimization/minimizer-esm-asset/webpack.config.js

let swc minimizer determine the module type if it is unknown - align with webpack and terser-webpack-plugin.
Fixes: #6513

fix(minimizer): resolve error in minimizing esm asset file

---

crates/rspack_binding_values/src/compilation.rs
crates/rspack_core/src/compiler/compilation.rs
crates/rspack_core/src/compiler/hmr.rs
crates/rspack_core/src/compiler/make/mod.rs
crates/rspack_core/src/compiler/module_executor/mod.rs
crates/rspack_core/src/tree_shaking/optimizer.rs
crates/rspack_plugin_javascript/src/plugin/side_effects_flag_plugin.rs

This PR will remove the behavior that move some data from make_artifact to compilation. it will make make_artifact save all of make data and compilation proxy the data access only.

refactor: make `make_artifact` as raw data

---

crates/rspack_core/src/compiler/hmr.rs
crates/rspack_core/src/compiler/make/mod.rs
crates/rspack_core/src/options/entry.rs

The entry dependencies of compilation should include both `dependencies` and `include_dependencies`

fix: make entry add include dependencies

---

crates/rspack_core/src/build_chunk_graph/code_splitter.rs
crates/rspack_core/src/compiler/hmr.rs
crates/rspack_core/src/compiler/make/cutout/has_module_graph_change.rs
crates/rspack_core/src/exports_info.rs
crates/rspack_plugin_javascript/src/plugin/flag_dependency_exports_plugin.rs
crates/rspack_plugin_split_chunks/src/module_group.rs
crates/rspack_plugin_split_chunks/src/plugin/module_group.rs

Rspack offers 2 approaches for handling hot module replacement (HMR):
1. Fast path: Only modifies content without changing dependencies, allowing for the reuse of the chunk graph.
2. Slow path: Module dependencies or blocks have changed, requiring regeneration of the chunk graph.
Currently, we encounter issues with both scenarios:
1. Users may trigger the slow path even when not altering dependencies (e.g., adding a div in a React app). This occurs because we detect changes in dependencies; for instance, adding a new ImportSpecifierDependency triggers the slow path.
2. When encountering the slow path, the generated chunk graph differs from the original one.
In certain instances, the chunk graph may vary between builds even if there are no modifications to the module graph.
make …

fix: make code-splitting deterministic

---

website/docs/en/api/_meta.json
website/docs/en/api/index.mdx
website/docs/en/api/javascript-api.mdx
website/docs/en/config/stats.mdx
website/docs/zh/api/_meta.json
website/docs/zh/api/index.mdx
website/docs/zh/api/javascript-api.mdx
website/docs/zh/config/stats.mdx
website/theme/components/HomeFooter/index.tsx

Rename Node.js API to JavaScript API, because Rspack also supports JavaScript runtimes other than Node.js, such as Bun.

docs: rename Node.js API to JavaScript API

---

packages/rspack/etc/api.md
packages/rspack/src/builtin-plugin/css-extract/index.ts
packages/rspack/src/builtin-plugin/css-extract/loader.ts
packages/rspack/src/exports.ts

Export two types of CSS extract plugin because Rsbuild needs to use these types:
```ts
import type { CssExtractRspackPluginOptions, CssExtractRspackLoaderOptions } from '@rspack/core';
```
This is equivalent to `mini-css-extract-plugin`:
```ts
import type { PluginOptions, LoaderOptions } from 'mini-css-extract-plugin';
```
See: https://github.com/webpack-contrib/mini-css-extract-plugin/blob/master/types/index.d.ts#L94-L95

feat: export types of CSS extract plugin

---

crates/rspack_plugin_split_chunks/src/module_group.rs

In #6508, we change the `compare_entires` in `SplitChunksPlugin`, at that time I thought cache group index should not be considered before modules, however some users do need the cache group index to make some modules hit certain cache group.
For example, we have 2 cache groups with the same index, and the same test. But we want the first one to be the right cache group.

fix: when comparing, cache group index should consider before modules

---

crates/rspack_plugin_javascript/src/dependency/esm/harmony_export_imported_specifier_dependency.rs

This is an optimization for `TypeScript` repo build hotspot. I did some performance tests before the 5-1, but now the results have been destroyed along with harddisk.
* Use .chain instead of .clone + .push
* eliminate Atom drop by avoiding redundant Atom clone
* eliminate Atom clone
* rewrite collect hidden_exports

perf: improve determine_export_assignments

---

packages/rspack/src/container/ModuleFederationPlugin.ts

Change the data URI type in ModuleFederationPlugin, from `data:application/node` to `data:text/javascript`.
Because `data:text/javascript` is commonly used and can be matched by the builtin JS transform rules of Rsbuild.
See https://github.com/web-infra-dev/rsbuild/issues/2360 for background.

fix: change the data URI type in ModuleFederationPlugin

---

crates/rspack_core/src/compiler/make/repair/mod.rs
crates/rspack_core/src/compiler/module_executor/mod.rs
packages/rspack-test-tools/tests/hotCases/css/recovery/__snapshots__/web/0.snap.txt
packages/rspack-test-tools/tests/hotCases/css/recovery/__snapshots__/web/2.snap.txt
packages/rspack-test-tools/tests/hotCases/css/recovery/changed-file.js
packages/rspack-test-tools/tests/hotCases/css/recovery/index.css
packages/rspack-test-tools/tests/hotCases/css/recovery/index.js
packages/rspack-test-tools/tests/hotCases/css/recovery/rspack.config.js

The MakeTaskContext should retain all of artifact data.

fix: module_executor keep make_failed_module

---

crates/rspack_core/src/normal_module.rs
crates/rspack_plugin_extract_css/src/css_dependency.rs
crates/rspack_plugin_extract_css/src/css_module.rs
crates/rspack_plugin_extract_css/src/parser_and_generator.rs
crates/rspack_plugin_extract_css/src/plugin.rs
packages/playground/cases/react/tailwindcss-with-css-extract/index.test.ts
packages/playground/cases/react/tailwindcss-with-css-extract/rspack.config.js
packages/playground/cases/react/tailwindcss-with-css-extract/src/App.css
packages/playground/cases/react/tailwindcss-with-css-extract/src/App.jsx
packages/playground/cases/react/tailwindcss-with-css-extract/src/index.html
packages/playground/cases/react/tailwindcss-with-css-extract/src/main.jsx
packages/playground/cases/react/tailwindcss-with-css-extract/tailwind.config.js

close #6422
The incremental build requires fileDependencies and contextDependencies. When a file is modified, we remove all affected modules based on these dependencies. Modules are considered affected if their fileDependencies include the modified file. However, CSS modules in CssExtract do not have file dependencies, preventing the module graph from updating the CSS module.

fix: css-extract-plugin should keep file dependencies

---

packages/rspack/etc/api.md
packages/rspack/package.json
packages/rspack/prebundle.config.mjs
packages/rspack/tsconfig.json
pnpm-lock.yaml

Prebundle enhanced-resolve to reduce dependencies,  the motivation is the same as https://github.com/web-infra-dev/rspack/pull/6462

perf(core): prebundle enhanced-resolve to reduce dependencies

---

crates/rspack_core/src/normal_module.rs
crates/rspack_core/src/parser_and_generator.rs
crates/rspack_plugin_asset/src/lib.rs
crates/rspack_plugin_css/src/parser_and_generator/mod.rs
crates/rspack_plugin_javascript/src/parser_and_generator/mod.rs
crates/rspack_plugin_json/src/lib.rs
crates/rspack_plugin_wasm/src/parser_and_generator.rs

remove codegen deps from ParserContext, get it from ParserResult just like other kinds of deps

refactor: create codegen dependencies

---

crates/rspack_core/src/compiler/make/cutout/clean_isolated_module.rs
crates/rspack_core/src/compiler/make/cutout/mod.rs

The connection maybe has been deleted by revoke_module when update entries.

fix: panic when update entry dependency

---

crates/rspack_plugin_javascript/src/visitors/mod.rs
packages/rspack-test-tools/tests/builtinCases/plugin-javascript/builtins-define/__snapshots__/output.snap.txt
packages/rspack-test-tools/tests/builtinCases/plugin-javascript/provide/__snapshots__/output.snap.txt
packages/rspack-test-tools/tests/configCases/parsing/preserve-all-comments/index.js
packages/rspack-test-tools/tests/hookCases/normalModuleFactory#afterResolve/duplicate/output.snap.txt
packages/rspack-test-tools/tests/treeShakingCases/webpack-innergraph-try-globals/__snapshots__/treeshaking.snap.txt
plugin-test/css-extract/enforceEsm.test.js

Revert PR #6389.
Rspack leverages `dropped_comment_preserver` to preserve comments which might be lost in transformation. This is related to rspack's `DefinePlugin` implementation, which means it needs to use transform to drive. The visitor itself has a great time complexity on large projects. (Only 5% on original CI test).
Revert to wait https://github.com/web-infra-dev/rspack/pull/6583 to remove additional transformation instead.

revert: revert swc comment preserver (#6389)

---

crates/rspack_plugin_library/src/module_library_plugin.rs
packages/rspack-test-tools/tests/configCases/output-module/rspack-issue-6572/index.js
packages/rspack-test-tools/tests/configCases/output-module/rspack-issue-6572/lib.js
packages/rspack-test-tools/tests/configCases/output-module/rspack-issue-6572/rspack.config.js

close #6572
`usedName` is the name in exports, which could be mangled.
`infoName` is the real name of export.
We should keep the real name in export.

fix: fix module type export name

---

website/docs/en/guide/migration/storybook.mdx
website/docs/zh/guide/migration/storybook.mdx

Change Storybook usage to Storybook Rsbuild builder https://github.com/rspack-contrib/storybook-rsbuild.

docs: change Storybook migration to storybook-rsbuild

---

crates/rspack_core/src/compiler/make/cutout/has_module_graph_change.rs
packages/rspack-test-tools/tests/hotCases/newTreeshaking/re-export-optimization/bar.js
packages/rspack-test-tools/tests/hotCases/newTreeshaking/re-export-optimization/changed-file.js
packages/rspack-test-tools/tests/hotCases/newTreeshaking/re-export-optimization/entry.js
packages/rspack-test-tools/tests/hotCases/newTreeshaking/re-export-optimization/foo.js
packages/rspack-test-tools/tests/hotCases/newTreeshaking/re-export-optimization/index.js
packages/rspack-test-tools/tests/hotCases/newTreeshaking/re-export-optimization/package.json
packages/rspack-test-tools/tests/hotCases/newTreeshaking/re-export-optimization/reexport.js
packages/rspack-test-tools/tests/hotCases/newTreeshaking/re-export-optimization/rspack.config.js

fix #6532
Detect if chunk graph needs to be recalculated.
In some cases, tree shaking can optimize import chains. For example
```js
import {foo} from 'lib'
```
can be:
```js
import foo from 'lib/dist/foo'
```
But this optimization is applied in `seal` phase. But we determine if module graph change in `make` phase, so if user modifies code like
```js
import { foo, bar } from 'lib'
```
In make phase, the module graph has no change at all, but actually module graph can change later in `seal` phase.
So we have to detect all imported specifiers in ImportDependency.

fix: hmr should consider all imported members

---

website/docs/en/guide/tech/css.mdx
website/docs/zh/guide/tech/css.mdx

Recommend using sass-embedded to improve the Sass compilation performance.
See: 
- https://x.com/rspack_dev/status/1793830951832944676
- https://github.com/webpack-contrib/sass-loader/releases/tag/v14.2.0
- https://github.com/chenjiahan/rsbuild-sass-perf

docs: recommend using sass-embedded for performance

---

website/docs/en/guide/tech/react.mdx
website/docs/zh/guide/tech/react.mdx

Add guide for using React Compiler in Rspack:
- https://react.dev/learn/react-compiler
- https://rsbuild.dev/guide/framework/react#react-compiler

docs(react): add guide for React Compiler

---

packages/rspack/prebundle.config.mjs

Fix browserslist resolve is broken by prebundle.
This PR is part of fixes to support `extends` in browserslist config, see https://github.com/web-infra-dev/rsbuild/issues/2443
The same as https://github.com/web-infra-dev/rsbuild/pull/2446

fix: browserslist resolve is broken by prebundle

---

packages/rspack/etc/api.md
packages/rspack/src/builtin-plugin/css-extract/loader-options.json
packages/rspack/src/builtin-plugin/css-extract/loader.ts
plugin-test/css-extract/cases/custom-loader-with-functional-exports/expected/main.js
plugin-test/css-extract/cases/es-named-export-as-is-output-module/expected/main.css
plugin-test/css-extract/cases/es-named-export-as-is-output-module/expected/main.mjs
plugin-test/css-extract/cases/es-named-export-as-is-output-module/index.js
plugin-test/css-extract/cases/es-named-export-as-is-output-module/style.css
plugin-test/css-extract/cases/es-named-export-as-is-output-module/webpack.config.js
plugin-test/css-extract/cases/es-named-export-as-is/expected/main.css
plugin-test/css-extract/cases/es-named-export-as-is/expected/main.js
plugin-test/css-extract/cases/es-named-export-as-is/index.js
plugin-test/css-extract/cases/es-named-export-as-is/style.css
plugin-test/css-extract/cases/es-named-export-as-is/webpack.config.js
plugin-test/css-extract/cases/es-named-export-output-module/expected/main.mjs
plugin-test/css-extract/cases/es-named-export/webpack.config.js
plugin-test/css-extract/cases/export-only-locals-and-es-named-export/expected/main.js

close #6614
Copied from https://github.com/webpack-contrib/mini-css-extract-plugin/pull/1078 and https://github.com/webpack-contrib/mini-css-extract-plugin/pull/1084

feat(css-extract): add defaultExport and namedExport support

---

webpack-test/package.json

Force render color output when running `test:webpack`.
https://jestjs.io/docs/cli#--colors
before:
after:

chore(test): force colorize Jest output

---

packages/rspack-test-tools/etc/api.md
packages/rspack-test-tools/package.json
packages/rspack-test-tools/src/processor/diagnostic.ts
packages/rspack-test-tools/src/processor/hook.ts
packages/rspack-test-tools/src/processor/hot-step.ts
packages/rspack-test-tools/src/processor/snapshot.ts
packages/rspack-test-tools/src/type.ts

This is another `vitest` compatiblity patch like #6611.
- use `env.expect().toMatchFileSnapshot` just like vitest
- add typings for `toMatchFileSnapshot`

test: use `toMatchFileSnapshot`

---

crates/rspack_core/src/context_module.rs
crates/rspack_core/src/context_module_factory.rs
crates/rspack_core/src/dependency/context_dependency.rs
crates/rspack_core/src/dependency/context_element_dependency.rs
crates/rspack_core/src/dependency/dependency_type.rs
crates/rspack_plugin_javascript/src/dependency/context/common_js_require_context_dependency.rs
crates/rspack_plugin_javascript/src/dependency/context/import_context_dependency.rs
crates/rspack_plugin_javascript/src/dependency/context/import_meta_context_dependency.rs
crates/rspack_plugin_javascript/src/dependency/context/require_context_dependency.rs
crates/rspack_plugin_javascript/src/plugin/impl_plugin_for_js_plugin.rs
crates/rspack_plugin_lazy_compilation/src/plugin.rs

close #6652
Should not lazy compile normal context element dependency

fix: should not lazy static context element dependency

---

crates/rspack_core/src/utils/identifier.rs
crates/rspack_loader_runner/src/loader.rs
packages/rspack-test-tools/src/helper/legacy/parseResource.js
packages/rspack-test-tools/src/helper/util/identifier.js
packages/rspack-test-tools/tests/configCases/loader-import-module/nul-byte/convert-loader.js
packages/rspack-test-tools/tests/configCases/loader-import-module/nul-byte/import-loader.js
packages/rspack-test-tools/tests/configCases/loader-import-module/nul-byte/index.js
packages/rspack-test-tools/tests/configCases/loader-import-module/nul-byte/rspack.config.js
packages/rspack-test-tools/tests/configCases/loader-import-module/nul-byte/source-loader.js
packages/rspack/src/loader-runner/index.ts
packages/rspack/src/util/identifier.js

fix #6643
Webpack use `\0` as seperator of request, but it should crash in oneshot::Reveiver and then caused panic while using `compilation.importModule`.
Replace `\0` with `\u200b` which is a non-length space to prevent this issue

fix: replace `\0` to `\u200b`

---

crates/rspack_core/src/normal_module_factory.rs
packages/rspack-test-tools/tests/configCases/container-1-5/lowing-syntax-with-loader/index.js
packages/rspack-test-tools/tests/configCases/container-1-5/lowing-syntax-with-loader/module.js
packages/rspack-test-tools/tests/configCases/container-1-5/lowing-syntax-with-loader/rspack.config.js
packages/rspack-test-tools/tests/configCases/module/match-resource-mimetype/get-source.js
packages/rspack-test-tools/tests/configCases/module/match-resource-mimetype/index.js
packages/rspack-test-tools/tests/configCases/module/match-resource-mimetype/rspack.config.js
packages/rspack/src/config/normalization.ts
packages/rspack/src/container/ModuleFederationPlugin.ts

fix #6666 
fix #5969
Apply js rule for module federation runtime, if user have babel-loader/swc-loader to transform js code, then the module federation runtime will also transformed by it now

fix: apply js rule on module federation runtime
