web-infra-dev/rspack

.vscode/extensions.json
vscode recommendations: rust-analyzer
=> chore: add rust-analyzer

README.md, README.zh-CN.md
=> chore: update docs for some format error

README.md, README.zh-CN.md
=> chore: fix readme

.github/workflows/bundle-stats.yaml, .github/workflows/check-rs.yaml
=> chore(ci): fix install protoc limit

.github/workflows/release.yml
=> chore: fix release ci for canary release

.github/workflows/test-ignore.yml
=> chore: try to fix dummy status checks

.changeset/silver-cheetahs-tickle.md, crates/rspack_plugin_library/src/umd_library_plugin.rs
- fix: library umd code excute
=> fix: library umd code excute

.github/workflows/bench-history.yaml
=> chore: 🤖 fix benchmark history

crates/node_binding/Cargo.lock, crates/node_binding/binding.d.ts, crates/node_binding/src/utils.rs, crates/rspack_core/src/dependency/code_generatable.rs, packages/create-rspack/package.json, packages/rspack-cli/src/rspack-cli.ts, packages/rspack/src/compilation.ts, packages/rspack/src/compiler.ts, packages/rspack/src/rspack.ts, packages/rspack/src/rspackOptionsApply.ts, packages/rspack/src/stats.ts, packages/rspack/src/util/hash/index.js, packages/rspack/src/watching.ts, packages/rspack/tests/README.md
Add some missing copyright attributions
=> fix: correct license

crates/rspack_plugin_javascript/src/visitors/dependency/code_generation.rs
=> chore: update license

packages/rspack/src/compilation.ts, packages/rspack/src/multiCompiler.ts
=> chore: fix some ts types

README.md
I have a strong feeling that the _ecology_ word is not suitable here. I do not know for sure what was the intention of the author, but it seems he/she wanted to use _ecosystem_.
=> docs: improve wording to better reflect initial idea

scripts/cmd.js, scripts/package.json
=> chore(scripts): remove unused export module

.github/workflows/bench.yaml
related to https://github.com/web-infra-dev/rspack/actions/runs/4398387900/jobs/7702202945
=> chore: 🤖 fix benchmark protoc not found

README.md, README.zh-CN.md
=> docs: fix  README.md logo

.changeset/hungry-paws-fetch.md, crates/rspack_core/src/compiler/queue.rs, crates/rspack_core/src/module.rs, crates/rspack_core/src/normal_module.rs
=> fix: incremental rebuild not work

.github/workflows/release.yml, .github/workflows/test-pr.yml, package.json, packages/rspack-dev-server/package.json
=> chore: add ci workflow for pr

packages/rspack/src/rspack.ts, packages/rspack/src/util/index.ts
Remove unnecessary use of `any`
None
=> refactor: use better typing to remove any

.changeset/silent-falcons-joke.md, packages/rspack-cli/src/rspack-cli.ts, packages/rspack-cli/tests/build/basic/basic.test.ts, packages/rspack-cli/tests/build/basic/entry.function.js, packages/rspack-cli/tests/build/basic/entry.promise.js, packages/rspack/src/util/index.ts
related to https://webpack.js.org/configuration/configuration-types/#exporting-a-promise
=> feat(cli): support config return promise

README.md
=> refactor: ast -> AST in readme

.prettierignore
=> chore: prettierignore complement

.changeset/yellow-keys-breathe.md, Cargo.lock, crates/node_binding/Cargo.lock, crates/rspack_core/src/external_module.rs, crates/rspack_core/src/utils/identifier.rs, crates/rspack_plugin_library/Cargo.toml, crates/rspack_plugin_library/src/umd_library_plugin.rs, packages/rspack/tests/configCases/library/umd-external/webpack.config.js
- fix: normalize identifier for externalsType umd
=> fix: normalize identifier for externalsType umd

.github/workflows/test.yml
1. `.github/workflows/test.yml` only runs in main branch, it should not be canceled.
=> chore: 🤖 remove concurrency cancel in main

.changeset/big-maps-fly.md, crates/rspack_plugin_css/src/plugin.rs
=> fix: postcss modules warning when using postcss-loader

pnpm-lock.yaml
=> chore: fix lockfile problem

.changeset/seven-dancers-melt.md, crates/rspack_plugin_css/src/plugin.rs, crates/rspack_plugin_javascript/src/plugin.rs
=> fix: contenthash should care about ChunkGraphModule#id

.github/workflows/release-pull-request.yml, .github/workflows/release.yml
Release action add ONLY_RELEASE_TAG env to only create release tag
=> feat: release action support only create release tag

examples/solid/package.json, examples/solid/src/App.jsx, examples/solid/src/Message.jsx, pnpm-lock.yaml
latest solid version supports solid-refresh for rspack now https://github.com/solidjs/solid-refresh/pull/39
=> chore: make solid example refresh happen

.changeset/popular-walls-accept.md, crates/rspack_core/src/context_module_factory.rs, crates/rspack_core/src/normal_module_factory.rs, packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
=> fix: fix identifier of missing module

.changeset/stale-lizards-allow.md, crates/rspack_plugin_html/src/parser.rs, packages/rspack/tests/configCases/builtins/html-minify/index.html, packages/rspack/tests/configCases/builtins/html-minify/index.js, packages/rspack/tests/configCases/builtins/html-minify/webpack.config.js
=> fix(html): builtins.html minify not work

.changeset/shaggy-hairs-float.md, packages/rspack-cli/src/commands/build.ts, packages/rspack-cli/src/rspack-cli.ts, packages/rspack/src/index.ts, packages/rspack/src/multiStats.ts
=> fix(cli): rspack build --watch not work (#2280)

packages/rspack/src/config/adapter-rule-use.ts
=> chore: fix typo in adapter-rule-use.ts

.github/workflows/check-rs.yaml
=> ci: cache pnpm in check-rs

.github/workflows/check-rs.yaml
This reverts commit 6aefac8e33109ce98d3a30e10e87a2e598a5f408.
=> Revert "ci: cache pnpm in check-rs (#2308)"

.changeset/polite-rice-search.md, packages/rspack-dev-middleware/src/middleware.ts
- fix: css hmr memory middleware
=> fix: css hmr memory middleware

.changeset/silver-lemons-beg.md, packages/create-rspack/index.js, packages/create-rspack/utils/index.js
=> feat: added the handling of duplicate project names

.changeset/soft-doors-guess.md, crates/node_binding/binding.d.ts, crates/rspack_binding_options/src/options/raw_node.rs, crates/rspack_core/src/options/node.rs, crates/rspack_plugin_javascript/src/visitors/dependency/scanner.rs, crates/rspack_testing/src/test_config.rs, packages/rspack/src/config/adapter.ts, packages/rspack/src/config/defaults.ts, packages/rspack/src/config/schema.js, packages/rspack/src/config/types.ts, packages/rspack/tests/Defaults.unittest.ts, packages/rspack/tests/cases/module-variables/dirname-mock/index.js, packages/rspack/tests/cases/module-variables/dirname-mock/webpack.config.js, packages/rspack/tests/cases/module-variables/dirname-true/child/child.js, packages/rspack/tests/cases/module-variables/dirname-true/index.js, packages/rspack/tests/cases/module-variables/dirname-true/webpack.config.js, packages/rspack/tests/cases/module-variables/dirname-web-default/index.js
=> feat(runtime): support `__filename` polyfill

.changeset/eighty-bugs-cry.md, crates/rspack_core/src/cache/mod.rs, crates/rspack_core/src/cache/snapshot/manager.rs, crates/rspack_core/src/compiler/hmr.rs
=> fix: Tailwind CSS HMR not work

README.zh-CN.md
add feishu group for chinese users
=> chore: add rspack feishu group

.changeset/friendly-peas-fly.md, crates/rspack_plugin_html/src/plugin.rs
=> fix: :bug: fix parsing error in html template path

.changeset/swift-queens-battle.md, crates/rspack_plugin_progress/src/lib.rs
=> fix: progress plugin percent symbol

.github/workflows/release.yml
=> fix: release action node architecture config

.changeset/red-swans-sell.md, packages/rspack/src/compilation.ts
1. related code in webpack5 https://github.com/webpack/webpack/blob/7b63346518a03f9d3eddc7b30cdd31043967929b/lib/Compilation.js#L786-L792
1. resolved https://github.com/web-infra-dev/rspack/issues/2376
=> feat: 🤖 additionalAssets

.changeset/polite-tigers-obey.md, crates/rspack_plugin_javascript/src/visitors/mod.rs, packages/rspack-dev-client/src/reactRefresh.ts, packages/rspack-dev-server/src/server.ts, packages/rspack-dev-server/tests/__snapshots__/normalizeOptions.test.ts.snap, packages/rspack-dev-server/tests/normalizeOptions.test.ts
- fix: react refresh runtime injection
#2262
=> fix: react refresh runtime injection

examples/basic/rspack.config.js
=> fix: set context of basic example to __dirname

.changeset/brown-countries-attack.md, crates/rspack_core/src/runtime_globals.rs, crates/rspack_plugin_javascript/src/plugin.rs, crates/rspack_plugin_library/src/amd_library_plugin.rs, crates/rspack_plugin_library/src/umd_library_plugin.rs, crates/rspack_plugin_runtime/src/array_push_callback_chunk_format.rs, packages/rspack/tests/configCases/library/umd/index.js
- fix: returning exports from runtime for libraries
=> fix: returning exports from runtime for libraries

.changeset/tame-mirrors-act.md, crates/node_binding/package.json, pnpm-lock.yaml
add cross-env for ndoe-binding
=> chore: node binding cross env

.changeset/lemon-clocks-boil.md, packages/rspack-cli/src/globals.d.ts, packages/rspack-cli/src/rspack-cli.ts, packages/rspack-cli/src/types.ts, packages/rspack-cli/src/utils/loadConfig.ts, packages/rspack-cli/tests/build/basic/basic.test.ts, packages/rspack-cli/tests/build/basic/entry.config.mjs, packages/rspack-cli/tsconfig.json, packages/rspack-dev-server/src/server.ts
closes #2124 
we're planning to support .js & .ts & .mjs and not planning to support .mts & .cts yet
=> feat(rspack-cli): support mjs config

.changeset/bright-fishes-raise.md, Cargo.lock, Cargo.toml, crates/node_binding/Cargo.lock
=> chore: update rspack-sources

CONTRIBUTING.md
- add some tips about `corepack enable`
#2441
=> docs: add some tips about corepack enable

packages/rspack/src/watching.ts, packages/rspack/tests/WatchSuspend.test.js
=> fix: skip some tests in watch suspend

Cargo.lock, crates/bench/Cargo.toml, crates/cargo-rst/Cargo.toml, crates/node_binding/Cargo.lock, crates/node_binding/Cargo.toml, crates/rspack/Cargo.toml, crates/rspack_binding_macros/Cargo.toml, crates/rspack_build/Cargo.toml, crates/rspack_core/Cargo.toml, crates/rspack_error/Cargo.toml, crates/rspack_plugin_css/Cargo.toml, crates/rspack_plugin_javascript/Cargo.toml, crates/rspack_testing/Cargo.toml
Having unused dependencies adds noise and slows down compilation speed.
closes #2475
=> chore(rust): remove unused dependencies via cargo-udeps

.github/workflows/check-rs.yaml
This caches pnpm dependencies by using the [documented approach from the pnpm website](https://pnpm.io/continuous-integration#github-actions).
=> ci: cache pnpm dependencies in check-rs workflow

.github/workflows/check-rs.yaml
=> ci: fix check-rs

packages/rspack-cli/src/rspack-cli.ts, packages/rspack-dev-server/src/server.ts, packages/rspack/src/node/nodeConsole.ts, packages/rspack/src/rspack.ts, packages/rspack/tests/Compiler.test.ts
Some ts-ignores are not necessary.
=> fix: remove unnecessary @ts-ignore

packages/rspack-dev-server/src/server.ts, packages/rspack/src/compiler.ts
=> fix(core): change the callback type of compiler.watch to `Callback`

.github/workflows/bench-history.yaml, crates/rspack_fs_node/package.json, packages/playground/package.json, pnpm-lock.yaml
=> chore: fix version bump

.changeset/clean-pugs-relate.md, crates/rspack_core/src/compiler/resolver.rs, crates/rspack_core/src/context_module.rs, crates/rspack_core/src/context_module_factory.rs, packages/rspack/tests/cases/context/ignore-hidden-files/index.js, packages/rspack/tests/cases/context/issue-3873/index.js
- fix: context module request
https://github.com/web-infra-dev/rspack/issues/2417
=> fix: context module request

.github/issue-labeler.yml, test.js
1. issue label bot should use `/ /` syntax to represent regex, you could refer to https://github.com/github/issue-labeler/blob/e24a3eb6b2e28c8904d086302a2b760647f5f45c/src/main.ts#LL201C3-L213C4 for more details
=> CI: use regex to trigger issue labeler

.github/workflows/test-pr.yml, .github/workflows/test.yml, crates/rspack/Cargo.toml
Poor team's PR test workflow :-(
closes #2355
=> chore: pr test workflow

crates/rspack_testing/examples/build-cli.rs, crates/rspack_testing/src/eval_raw.rs
Document how to debug from the Rust side without running node.js.
closes #2140
=> fix(rspack_testing): document on how to run the Rust core

.changeset/late-icons-talk.md, crates/rspack_plugin_library/src/amd_library_plugin.rs, packages/rspack/tests/configCases/library/amd-named/index.js
https://github.com/web-infra-dev/rspack/issues/2443
=> fix: library amd returning

.changeset/bright-roses-cover.md, examples/basic/rspack.config.js, packages/rspack/src/compiler.ts
=> chore: expose `util` for compiler.webpack

.changeset/ninety-kings-report.md, crates/rspack_core/src/runtime_globals.rs, crates/rspack_plugin_javascript/src/dependency/url/mod.rs, crates/rspack_plugin_javascript/tests/fixtures/new_url/inline/expected/main.js, crates/rspack_plugin_javascript/tests/fixtures/new_url/inline/expected/runtime.js, crates/rspack_plugin_javascript/tests/fixtures/new_url/resource/expected/main.js, crates/rspack_plugin_javascript/tests/fixtures/new_url/resource/expected/runtime.js, crates/rspack_plugin_runtime/src/common_js_chunk_loading.rs, crates/rspack_plugin_runtime/src/jsonp_chunk_loading.rs, crates/rspack_plugin_runtime/src/runtime_module/jsonp_chunk_loading.rs, crates/rspack_plugin_runtime/src/runtime_module/require_js_chunk_loading.rs
=> feat: new url dependency in `target: 'node'`

.gitattributes
=> chore: git attributes ignore test related files

.changeset/smart-radios-peel.md, Cargo.lock, crates/node_binding/Cargo.lock, crates/rspack_core/src/chunk.rs, crates/rspack_core/src/chunk_graph.rs, crates/rspack_core/src/chunk_group.rs, crates/rspack_core/src/compiler/compilation.rs, crates/rspack_core/src/options/builtins.rs, crates/rspack_core/src/options/devtool.rs, crates/rspack_core/src/options/output.rs, crates/rspack_core/src/plugin/api.rs, crates/rspack_core/src/plugin/args.rs, crates/rspack_core/src/plugin/plugin_driver.rs, crates/rspack_plugin_devtool/src/lib.rs, crates/rspack_plugin_javascript/src/plugin.rs, crates/rspack_plugin_javascript/src/runtime.rs, crates/rspack_plugin_library/src/amd_library_plugin.rs, crates/rspack_plugin_library/src/assign_library_plugin.rs, crates/rspack_plugin_library/src/umd_library_plugin.rs, crates/rspack_plugin_runtime/Cargo.toml, crates/rspack_plugin_runtime/src/array_push_callback_chunk_format.rs, crates/rspack_plugin_runtime/src/common_js_chunk_format.rs, crates/rspack_plugin_runtime/src/helpers.rs, crates/rspack_plugin_runtime/src/lib.rs
=> fix: add more hash logic

.github/workflows/test-pr.yml, .github/workflows/test.yml, packages/playground/package.json, packages/rspack/src/config/defaults.ts
=> test: add e2e test in linux

.github/workflows/test-pr.yml
try use merge_queue to optimize ci workflow
=> chore: enable merge_queue

.github/workflows/lint-pr.yaml, CONTRIBUTING.md
```
feat(ui): Add `Button` component
^    ^    ^
|    |    |__ Subject
|    |_______ Scope
|____________ Type
```
This PR validate
- Must write a `Type`
- allowing types are https://github.com/web-infra-dev/rspack/compare/hyf_lint_pr?expand=1#diff-fc98139577eb07d54e24aa5d41da856c636f5ad318d0ad700f13a457c136cb80R23-R32
- Optionally write a `Scope`
- `Scope` should be lower-cases
- Must write a `Subject`
Closes #2569.
=> ci: encore PR titles to follow the conventional-commit rules

.changeset/honest-houses-dress.md, packages/rspack-cli/package.json, pnpm-lock.yaml
=> fix(cli): fix semver missing

crates/rspack_plugin_css/src/lib.rs
1. Fixed https://github.com/web-infra-dev/rspack/issues/2595
=> fix: swc css minifier global not set

.changeset/clean-turkeys-dance.md, crates/node_binding/binding.d.ts, crates/rspack_binding_options/src/options/raw_builtins/raw_html.rs, crates/rspack_plugin_html/src/config.rs, crates/rspack_plugin_html/src/plugin.rs, crates/rspack_plugin_html/tests/fixtures/templateContent+templateParameters/expected/index.html, crates/rspack_plugin_html/tests/fixtures/templateContent+templateParameters/index.js, crates/rspack_plugin_html/tests/fixtures/templateContent+templateParameters/test.config.json, packages/rspack/tests/configCases/builtins/html-template-content/index.js, packages/rspack/tests/configCases/builtins/html-template-content/webpack.config.js
=> feat(html): support templateContent in `builtins.html`

examples/arco-pro/package.json, examples/svelte/package.json, examples/svelte/tsconfig.json, package.json, packages/rspack-dev-client/package.json, packages/rspack-dev-server/package.json, packages/rspack/package.json, pnpm-lock.yaml
=> chore: Upgrade typescript

Cargo.lock, Cargo.toml, crates/node_binding/Cargo.lock, crates/rspack_binding_options/src/options/raw_module.rs, crates/rspack_core/Cargo.toml, crates/rspack_core/src/compiler/compilation.rs, crates/rspack_core/src/compiler/queue.rs, crates/rspack_core/src/context_module_factory.rs, crates/rspack_core/src/module.rs, crates/rspack_core/src/module_factory.rs, crates/rspack_core/src/normal_module.rs, crates/rspack_core/src/normal_module_factory.rs, crates/rspack_core/src/options/module.rs, crates/rspack_core/src/tree_shaking/visitor.rs, crates/rspack_core/src/utils/module_rules.rs
=> perf: remove block_in_place for function type RuleSetCondition

examples/library/package.json, examples/library/rspack.config.js, examples/library/src/index.js, pnpm-lock.yaml
shows how to build library using rspack
=> chore: add library example

.github/workflows/lint-pr.yaml
=> ci: add refactor type on lint-pr

crates/rspack_plugin_css/src/utils.rs
=> chore(css): remove unnecessary format

webpack-test/README.md
closed https://github.com/web-infra-dev/rspack/issues/2605
=> test: webpack test credit

.changeset/cuddly-llamas-wave.md, crates/node_binding/binding.d.ts, crates/rspack_binding_options/src/options/raw_output.rs
=> fix: fix typing of raw cross origin loading

crates/rspack_plugin_javascript/src/visitors/swc_visitor/react.rs
=> fix(hmr): should inject react refresh runtime code correctly

.github/ISSUE_TEMPLATE/3-tracking-issue.en-US.yml
add a issue template for creating tracking issue
=> chore: add a issue template for creating tracking issue

.changeset/dull-sheep-argue.md, crates/node_binding/binding.d.ts, crates/rspack_binding_options/src/options/mod.rs, crates/rspack_core/src/dependency/mod.rs, crates/rspack_core/src/dependency/runtime_requirements_dependency.rs, crates/rspack_core/src/options/compiler_options.rs, crates/rspack_core/src/runtime_globals.rs, crates/rspack_plugin_html/tests/fixtures/variant/expected/output.html, crates/rspack_plugin_javascript/src/plugin.rs, crates/rspack_plugin_javascript/src/visitors/dependency/common_js_scanner.rs, crates/rspack_plugin_javascript/src/visitors/dependency/mod.rs, crates/rspack_plugin_javascript/src/visitors/dependency/node_stuff_scanner.rs, crates/rspack_plugin_javascript/src/visitors/dependency/scanner.rs, crates/rspack_plugin_javascript/tests/fixtures/new_url/inline/expected/runtime.js, crates/rspack_plugin_javascript/tests/fixtures/new_url/resource/expected/runtime.js, crates/rspack_testing/src/test_config.rs, packages/rspack/src/config/adapter.ts, packages/rspack/src/config/defaults.ts, packages/rspack/src/config/types.ts, packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap, packages/rspack/tests/configCases/parsing/issue-9156/index.js, packages/rspack/tests/configCases/parsing/issue-9156/webpack.config.js, packages/rspack/tests/configCases/parsing/node-source-plugin-off/index.js, packages/rspack/tests/configCases/parsing/node-source-plugin-off/webpack.config.js, packages/rspack/tests/configCases/parsing/node-stuff-plugin-off/index.js, packages/rspack/tests/configCases/parsing/node-stuff-plugin-off/test.config.js, packages/rspack/tests/configCases/parsing/node-stuff-plugin-off/webpack.config.js, packages/rspack/tests/copyPlugin/build/main.js
- support node false
- refactor node stuff parser aligin to webpack
- support commonjs parser `module.id` + `module.loaded`
close https://github.com/web-infra-dev/rspack/issues/2611
=> feat: support node false

.github/ISSUE_TEMPLATE/3-tracking-issue.en-US.yml
=> chore: fix the format of 3-tracking-issue.en-US

.github/workflows/ecosystem-ci-trigger.yml, package.json, packages/rspack-cli/jest.config.js, packages/rspack-cli/tests/build/json/.gitignore, packages/rspack-cli/tests/build/json/stats.json
Add rspack ecosystem ci comment trigger, and fix a cli test
=> chore: prepare for rspack-ecosystem-ci

.github/workflows/ecosystem-ci-trigger.yml
=> chore: fix ecosystem-ci trigger comment

examples/nestjs/README.md, examples/nestjs/package.json, examples/nestjs/rspack.config.js, examples/nestjs/src/app.controller.ts, examples/nestjs/src/app.module.ts, examples/nestjs/src/app.service.ts, examples/nestjs/src/main.ts, pnpm-lock.yaml
=> chore: add nestjs example

.github/workflows/release.yml
=> fix: 🐛 release ci syntax

.github/workflows/release.yml
=> chore(ci): comment out release-pre-check

crates/rspack_plugin_javascript/src/visitors/dependency/scanner.rs
=> refactor: 🤖 remove unnecessary ignore clippy

.changeset/friendly-pillows-divide.md, packages/rspack/src/config/defaults.ts, packages/rspack/src/config/schema.js, packages/rspack/tests/Defaults.unittest.ts, packages/rspack/tests/configCases/errors/not-fully-specified/fully-specified.mjs, packages/rspack/tests/configCases/errors/not-fully-specified/index.js, packages/rspack/tests/configCases/errors/not-fully-specified/not-fully-specified.mjs
=> feat: enable resolve.fullySpecified for defaultRules

crates/node_binding/binding.d.ts, crates/rspack_binding_options/src/options/raw_output.rs, crates/rspack_build/fixture/test.config.json, crates/rspack_core/src/compiler/mod.rs, crates/rspack_core/src/options/output.rs, crates/rspack_fs/src/async.rs, crates/rspack_fs/src/native.rs, crates/rspack_fs_node/src/async.rs, crates/rspack_fs_node/src/node.rs, crates/rspack_loader_sass/tests/fixtures.rs, crates/rspack_testing/src/test_config.rs, packages/rspack-cli/tests/build/json/stats.json, packages/rspack/src/config/adapter.ts, packages/rspack/src/config/defaults.ts, packages/rspack/src/config/normalization.ts, packages/rspack/src/config/schema.js, packages/rspack/src/config/types.ts, packages/rspack/src/fileSystem.ts, packages/rspack/tests/Defaults.unittest.ts, packages/rspack/tests/Output.test.ts
[[Feature Request]: Support output.clean](https://github.com/web-infra-dev/rspack/issues/2577)
Closes https://github.com/web-infra-dev/rspack/issues/2577
=> feat: Support output.clean

webpack-test/Errors.test.js, webpack-test/HotTestCases.template.js, webpack-test/Stats.test.js, webpack-test/__snapshots__/StatsTestCases.basictest.js.snap.bak, webpack-test/package.json
=> test: 💍 webpack stats test

.typos.toml
fix https://github.com/web-infra-dev/rspack/actions/runs/4658440191/jobs/8244117753
=> ci: 🎡 fix spell check failed

.changeset/warm-snakes-bathe.md
fix release pull request error: https://github.com/web-infra-dev/rspack/actions/runs/4663369570/jobs/8254632533
=> fix: changeset remove not exist package

Cargo.lock, crates/node_binding/Cargo.lock, crates/rspack_core/src/lib.rs, crates/rspack_plugin_javascript/Cargo.toml, crates/rspack_plugin_javascript/src/dependency/mod.rs, crates/rspack_plugin_javascript/src/plugin.rs, crates/rspack_plugin_javascript/src/visitors/dependency/import_meta_scanner.rs, crates/rspack_plugin_javascript/src/visitors/dependency/mod.rs, crates/rspack_plugin_javascript/src/visitors/dependency/util.rs, packages/rspack/tests/cases/esm/import-meta/index.js
- Port webpack ImportMetaPlugin
close https://github.com/web-infra-dev/rspack/issues/2392
=> feat: import meta scanner

package.json, packages/playground/package.json
split test to simplify test workflow
* test:example
* test:unit
* test:e2e
=> chore: split test

.github/ISSUE_TEMPLATE/1-bug-report.en-US.yml, .github/ISSUE_TEMPLATE/2-feature-request.en-US.yml
- We already have `bug`, `feat` tag for marking
- I leave tracking issues template untouched, since there are rare.
=> chore: remove the prefix of title in GitHub issue template

packages/rspack/src/compilation.ts, packages/rspack/src/compiler.ts, packages/rspack/src/config/adapter.ts, packages/rspack/src/normalModule.ts, packages/rspack/src/util/scheme.ts, packages/rspack/src/util/webpack.ts
=> feat: simple normal module hook

Cargo.lock, Cargo.toml, crates/node_binding/Cargo.lock
close https://github.com/web-infra-dev/rspack/issues/3028
bump `nodejs-resolver` to fix #3028 
- tests: https://github.com/web-infra-dev/nodejs_resolver/pull/184/files#diff-24975acf43b4bc39c4c8b57246e4bfbdc0c76428c86ed68f1db0e1b10a6db277R3049-R3055
=> fix(resolve): bump nodejs-resolver to fix baseUrl bug in tsconfig

.cargo/config.toml, crates/rspack_core/src/build_chunk_graph/code_splitter.rs, crates/rspack_core/src/chunk_graph/chunk_graph_module.rs, crates/rspack_core/src/dependency/code_generatable.rs, crates/rspack_plugin_split_chunks/src/chunks_info_item.rs, crates/rspack_plugin_split_chunks/src/split_chunks_plugin.rs, crates/rspack_plugin_split_chunks_new/src/plugin/chunk.rs, crates/rspack_regex/tests/main.rs, crates/rspack_symbol/src/lib.rs, packages/rspack/tests/configCases/builtins/react-runtime-automic/index.jsx, rust-toolchain.toml
https://blog.rust-lang.org/2023/06/01/Rust-1.70.0.html
=> chore(rust): bump rustc to v1.70.0 (nightly-2023-06-01)

GOVERNANCE.md
[Rendered](https://github.com/web-infra-dev/rspack/blob/governance/GOVERNANCE.md)
=> chore: add project governance

crates/rspack_binding_options/src/options/raw_module/mod.rs, crates/rspack_regex/src/algo.rs, crates/rspack_regex/src/lib.rs, crates/rspack_regex/tests/main.rs
- Remove unused code
- Prefer enum instead of trait object for easy debugging.
- Easily understandable naming.
=> refactor(rspack_regex): readability and functionality

.github/workflows/lint-pr.yaml, examples/basic-ts/index.html, examples/basic-ts/package.json, examples/basic-ts/rspack.config.js, examples/basic-ts/src/alias-1/a.ts, examples/basic-ts/src/alias-2/b.ts, examples/basic-ts/src/index.ts, examples/basic-ts/tsconfig.json, pnpm-lock.yaml
=> chore: add basic-ts example

packages/rspack-plugin-minify/src/index.js
1. Passing plugin option into terser minifier
=> chore: 🤖 pass terser options

.github/stale.yml
Some issues should neither close nor reply, it just fits to stay.
=> chore(ci): should not add stale tag for awaiting more feedback issues

crates/node_binding/scripts/build.js
Passing through cargo's non-zero exit code to make the compilation safer.
=> chore: exit if cargo returns any non-zero code

.github/workflows/release-canary.yml, scripts/release/publish.mjs, scripts/release/test.js
=> ci: write a comment to issue when canary release is finished.

.github/workflows/release-canary.yml
fixed https://github.com/web-infra-dev/rspack/actions/runs/5388421321
=> fix: 🤖 pr number

packages/rspack/src/index.ts, packages/rspack/src/lib/EnvironmentPlugin.js, packages/rspack/src/lib/LoaderOptionsPlugin.js, packages/rspack/src/schemas/plugins/LoaderOptionsPlugin.check.js, packages/rspack/src/schemas/plugins/LoaderOptionsPlugin.json, webpack-test/configCases/plugins/loader-options-plugin/test.filter.js, webpack-test/configCases/plugins/loader-options-plugin/webpack.config.js
1. Closed https://github.com/web-infra-dev/rspack/issues/3606
2. Finish the test case webpack-test/configCases/plugins/loader-options-plugin/
=> chore:  loader options plugin

examples/vue/rspack.config.js, examples/vue2-ts/rspack.config.js, examples/vue2/rspack.config.js, examples/vue3-vanilla/rspack.config.js
change matching rule in examples/vue to make less-loader process correct resources.
=> fix(examples/vue): refine module resource matching rule.

crates/node_binding/binding.d.ts, crates/rspack_binding_options/src/options/mod.rs, crates/rspack_binding_options/src/options/raw_entry.rs, crates/rspack_core/src/build_chunk_graph/code_splitter.rs, crates/rspack_core/src/chunk.rs, crates/rspack_core/src/options/entry.rs, crates/rspack_core/src/options/output.rs, crates/rspack_testing/src/test_config.rs, packages/rspack/src/config/adapter.ts, packages/rspack/src/config/normalization.ts, packages/rspack/src/config/types.ts, packages/rspack/src/config/zod/entry.ts, packages/rspack/src/config/zod/output.ts, packages/rspack/tests/configCases/entry/filename/index.js, packages/rspack/tests/configCases/entry/filename/test.config.js, packages/rspack/tests/configCases/entry/filename/webpack.config.js
resolve #3655
`rspack/tests/configCases/entry/filename`
=> feat: filename per entry

packages/rspack/src/config/zod/builtins.ts
=> chore: add build html scheme 

crates/rspack/tests/tree-shaking/rollup-unused-called-import/expected/main.js, crates/rspack/tests/tree-shaking/side-effects-analyzed/expected/main.js, crates/rspack/tests/tree-shaking/side-effects-flagged-only/expected/main.js, crates/rspack/tests/tree-shaking/side-effects-two/expected/main.js, crates/rspack/tests/tree-shaking/webpack-reexport-namespace-and-default/expected/main.js, crates/rspack_plugin_javascript/src/dependency/esm/harmony_export_expression_dependency.rs, crates/rspack_plugin_javascript/src/visitors/dependency/harmony_export_dependency_scanner.rs, packages/rspack/tests/cases/parsing/harmony-export-default-function-decl/a.js, packages/rspack/tests/cases/parsing/harmony-export-default-function-decl/b.js, packages/rspack/tests/cases/parsing/harmony-export-default-function-decl/c.js, packages/rspack/tests/cases/parsing/harmony-export-default-function-decl/d.js, packages/rspack/tests/cases/parsing/harmony-export-default-function-decl/index.js
Also need hoist async or generate anonymous function decl at export default decl
Added test
=> fix: hoist async or generate anonymous function decl at export decl

crates/node_binding/src/plugins/mod.rs, crates/rspack_binding_macros/src/macros.rs, crates/rspack_binding_options/src/options/raw_external.rs, crates/rspack_binding_options/src/options/raw_module/mod.rs
=> chore: fix macro name

Cargo.lock, crates/rspack_core/src/dependency/mod.rs, crates/rspack_core/src/tree_shaking/js_module.rs, crates/rspack_core/src/tree_shaking/visitor.rs, crates/rspack_plugin_javascript/src/visitors/dependency/mod.rs, crates/rspack_plugin_javascript/src/visitors/dependency/url_scanner.rs, crates/rspack_plugin_javascript/src/visitors/dependency/util.rs, crates/rspack_plugin_javascript/src/visitors/dependency/worker_scanner.rs, crates/rspack_plugin_worker/Cargo.toml, examples/worker/rspack.config.js, packages/rspack/tests/configCases/tree-shaking/new-url/b.js, packages/rspack/tests/configCases/tree-shaking/new-url/b.worker.js, packages/rspack/tests/configCases/tree-shaking/new-url/index.js, webpack-test/configCases/worker/node-worker-hmr/test.filter.js, webpack-test/configCases/worker/node-worker-named/test.filter.js, webpack-test/configCases/worker/node-worker/test.filter.js, webpack-test/configCases/worker/worker-contenthash/test.filter.js
fix #3658 
- enable webpack-test
- `webpack-test/configCases/worker/worker-contenthash`
- `webpack-test/configCases/worker/node-worker-named`
- update `rspack/tests/configCases/tree-shaking/new-url`
=> fix: panic when using worker with treeShaking enabled

examples/monaco-editor-js/index.html, examples/monaco-editor-js/index.js, examples/monaco-editor-js/package.json, examples/monaco-editor-js/rspack.config.js, examples/monaco-editor-ts-react/package.json, examples/monaco-editor-ts-react/rspack.config.js, examples/monaco-editor-ts-react/src/components/Editor.tsx, examples/monaco-editor-ts-react/src/index.css, examples/monaco-editor-ts-react/src/index.html, examples/monaco-editor-ts-react/src/index.tsx, examples/monaco-editor-ts-react/tsconfig.json, pnpm-lock.yaml
=> chore: add monaco-editor examples

packages/playground/cases/css/import-empty-css-file/rspack.config.js, packages/playground/cases/hooks/asset-emitted/index.test.ts, packages/playground/cases/hooks/asset-emitted/rspack.config.js, packages/playground/cases/hooks/asset-emitted/src/foo.js, packages/playground/cases/hooks/asset-emitted/src/index.html, packages/playground/cases/hooks/asset-emitted/src/index.js, packages/playground/cases/html/cross-origin-loading/index.test.ts, packages/playground/cases/html/cross-origin-loading/rspack.config.js, packages/playground/cases/react/basic/rspack.config.js, packages/playground/cases/react/tailwindcss/index.test.ts, packages/playground/cases/react/tailwindcss/rspack.config.js, packages/playground/cases/react/tailwindcss/src/App.css, packages/playground/cases/react/tailwindcss/src/App.jsx, packages/playground/cases/react/tailwindcss/src/index.html, packages/playground/cases/react/tailwindcss/src/main.jsx, packages/playground/cases/react/tailwindcss/tailwind.config.js, packages/playground/fixtures/rspack.ts, packages/playground/package.json, pnpm-lock.yaml
* rspack fixture set default value for context and builtins.define.
* crossoriginloading case test __public_path__
* add tailwindcss test case
* add asset-emitted hook test
=> test: add more E2E test case

examples/worker/example.js
=> chore: uncomment worker example

crates/rspack_plugin_javascript/src/visitors/swc_visitor/react.rs
=> fix: rumtime_stmts => runtime_stmts

.github/workflows/reusable-build.yml, packages/rspack-cli/jest.config.js, packages/rspack/jest.config.js, packages/rspack/tests/Compiler.test.ts, packages/rspack/tests/ConfigCase.template.ts, packages/rspack/tests/MultiCompiler.test.ts, packages/rspack/tests/Output.test.ts, packages/rspack/tests/WatchSuspend.test.js
=> chore: increase test timeout

.github/workflows/reusable-build.yml
CI build uses debug mode and runs really slow, this can be improved by compiling all dependencies with optimization turned on, and our crates without any optimizations. This should give us the best build time (since third party crates are cached) + the best test execution time. The only downside is cold build will be really slow on windows and mac, but the trade off is worth because we don't have many cold builds due to how are cache management is setup. 
* CI passes
* tests run less than 10 minutes. See successful run: https://github.com/web-infra-dev/rspack/actions/runs/5451668329/usage, the slowest is 10 minutes from "Test Windows / Test Node 14"
=> ci: compile dependencies with optimization for faster tests

crates/rspack_core/src/cache/local/code_splitting_cache.rs, crates/rspack_core/src/chunk_graph/chunk_graph_chunk.rs, examples/monaco-editor-js/index.js, examples/monaco-editor-js/rspack.config.js, examples/monaco-editor-ts-react/rspack.config.js, examples/monaco-editor-ts-react/src/components/Editor.tsx, examples/monaco-editor-ts-react/tsconfig.json, packages/rspack/tests/hotCases/disposing/remove-chunk-with-shared-in-other-runtime/module.js, packages/rspack/tests/hotCases/worker/remove-add-worker/changed-file.js, packages/rspack/tests/hotCases/worker/remove-add-worker/compute.js, packages/rspack/tests/hotCases/worker/remove-add-worker/index.js, packages/rspack/tests/hotCases/worker/remove-add-worker/test.filter.js, packages/rspack/tests/hotCases/worker/remove-add-worker/worker.js
worker chunk looses runtime modules in incramental rebuild
- `examples/monaco-editor-js` and `examples/monaco-editor-ts-react`
- `packages/rspack/tests/hotCases/worker/remove-add-worker`
=> fix: worker chunk looses runtime modules in incremental rebuild

packages/rspack/tests/cases/hooks/entryOption/package.json, packages/rspack/tests/cases/hooks/stillValidModule/package.json
remove the following jest hastle warning
no test plan related
=> chore: fix jest hastle warning

crates/rspack_core/src/compiler/hmr.rs, packages/rspack/jest.config.js, packages/rspack/tests/configCases/split-chunks/issue-3646/src/shared.js, packages/rspack/tests/hotCases/worker/move-between-runtime/changed-file.js, packages/rspack/tests/hotCases/worker/move-between-runtime/chunk.js, packages/rspack/tests/hotCases/worker/move-between-runtime/chunkS.js, packages/rspack/tests/hotCases/worker/move-between-runtime/index.js, packages/rspack/tests/hotCases/worker/move-between-runtime/module.js, packages/rspack/tests/hotCases/worker/move-between-runtime/moduleA.js, packages/rspack/tests/hotCases/worker/move-between-runtime/moduleAs.js, packages/rspack/tests/hotCases/worker/move-between-runtime/moduleB.js, packages/rspack/tests/hotCases/worker/move-between-runtime/moduleBs.js, packages/rspack/tests/hotCases/worker/move-between-runtime/moduleS.js, packages/rspack/tests/hotCases/worker/move-between-runtime/test.filter.js, packages/rspack/tests/hotCases/worker/move-between-runtime/webpack.config.js, packages/rspack/tests/hotCases/worker/move-between-runtime/worker.js, packages/rspack/tests/hotCases/worker/move-between-runtime/workerA.js, packages/rspack/tests/hotCases/worker/move-between-runtime/workerB.js, packages/rspack/tests/hotCases/worker/update-in-worker/changed-file.js, packages/rspack/tests/hotCases/worker/update-in-worker/index.js, packages/rspack/tests/hotCases/worker/update-in-worker/module.js, packages/rspack/tests/hotCases/worker/update-in-worker/test.filter.js, packages/rspack/tests/hotCases/worker/update-in-worker/worker.js
fix worker HMR
- `packages/rspack/tests/hotCases/worker/update-in-worker`
=> fix: worker HMR

crates/rspack_core/src/chunk_graph/chunk_graph_chunk.rs, crates/rspack_core/src/chunk_graph/chunk_graph_module.rs, crates/rspack_core/src/compiler/compilation.rs, crates/rspack_core/src/dependency/const_dependency.rs, crates/rspack_core/src/dependency/runtime_requirements_dependency.rs, crates/rspack_core/src/dependency/runtime_template.rs, crates/rspack_core/src/external_module.rs, crates/rspack_core/src/raw_module.rs, crates/rspack_core/src/runtime_globals.rs, crates/rspack_plugin_javascript/src/dependency/commonjs/common_js_require_dependency.rs, crates/rspack_plugin_javascript/src/dependency/commonjs/module_decorator_dependency.rs, crates/rspack_plugin_javascript/src/dependency/esm/harmony_compatibility_dependency.rs, crates/rspack_plugin_javascript/src/dependency/esm/harmony_export_imported_specifier_dependency.rs, crates/rspack_plugin_javascript/src/dependency/esm/harmony_export_specifier_dependency.rs, crates/rspack_plugin_javascript/src/dependency/esm/harmony_import_dependency.rs
The bit flags provider `insert` function.
It's a code refactor and pervious test should test it.
=> refactor: use bit flags insert for RuntimeGlobals

crates/rspack_plugin_css/src/parser_and_generator/mod.rs, crates/rspack_plugin_css/src/plugin/impl_plugin_for_css_plugin.rs, crates/rspack_plugin_css/src/swc_css_compiler.rs, crates/rspack_plugin_css/src/visitors/mod.rs
Try to reduce code complexity
No extra tests needed.
=> refactor(css): reduce code complexity

packages/playground/cases/react/worker/index.test.ts, packages/playground/cases/react/worker/src/App.jsx
temporary comment the worker e2e to let the CI happy
=> chore: temporary comment worker e2e

packages/rspack/tests/Stats.test.ts
=> chore: remove version in stats test snapshot

crates/rspack_ast_viewer/Cargo.toml, crates/rspack_ast_viewer/src/main.rs
Add scoping information for AST. 
This helps me tackle down problems related to SWC faster.
Not necessary as this is a simple one and should not be used other than the team
=> feat(ast_viewer): support contexting in ast viewer

GOVERNANCE.md
=> chore: add @ScriptedAlchemy to Rspack core

crates/rspack_plugin_ensure_chunk_conditions/src/lib.rs
Avoid rspack_plugin_ensure_chunk_conditions loop.
=> fix: avoid rspack_plugin_ensure_chunk_conditions loop

crates/node_binding/binding.d.ts, crates/rspack_binding_options/src/options/raw_split_chunks.rs, packages/rspack/src/config/zod/optimization/split-chunks.ts, packages/rspack/tests/configCases/split-chunks/issue-3646/src/index.js
To align generated chunk name with Webpack, this is a pre requirement.
No need.
=> feat(splitChunks): support `splitChunks.{cacheGroup}.idHint`

crates/rspack/tests/tree-shaking/basic/expected/main.js, crates/rspack/tests/tree-shaking/class-extend/app.js, crates/rspack/tests/tree-shaking/class-extend/expected/main.js, crates/rspack/tests/tree-shaking/class-extend/index.js, crates/rspack/tests/tree-shaking/class-extend/lib.js, crates/rspack/tests/tree-shaking/class-extend/test.config.json, crates/rspack/tests/tree-shaking/context-module-elimated/expected/main.js, crates/rspack/tests/tree-shaking/rollup-unused-called-import/expected/main.js, crates/rspack/tests/tree-shaking/static-class/expected/main.js, crates/rspack/tests/tree-shaking/var-function-expr/expected/main.js, crates/rspack/tests/tree-shaking/webpack-inner-graph-export-default-named/expected/main.js, crates/rspack/tests/tree-shaking/webpack-innergraph-circular/expected/main.js, crates/rspack/tests/tree-shaking/webpack-innergraph-no-side-effects/expected/main.js, crates/rspack/tests/tree-shaking/webpack-reexport-namespace-and-default/expected/main.js, crates/rspack_core/src/module_graph/mod.rs, crates/rspack_core/src/tree_shaking/optimizer.rs, crates/rspack_core/src/tree_shaking/symbol_graph.rs, crates/rspack_core/src/tree_shaking/utils.rs, crates/rspack_core/src/tree_shaking/visitor.rs, crates/rspack_plugin_javascript/src/dependency/esm/harmony_import_dependency.rs, crates/rspack_plugin_javascript/src/dependency/esm/harmony_import_specifier_dependency.rs, crates/rspack_plugin_javascript/src/visitors/dependency/harmony_export_dependency_scanner.rs, crates/rspack_plugin_javascript/src/visitors/dependency/harmony_import_dependency_scanner.rs, crates/rspack_plugin_javascript/tests/fixtures/builtins/define/expected/main.js, crates/rspack_symbol/src/lib.rs
Before symbol used check by checking every import symbol used, if they are not used, so every symbol is not used, it isn't correct, the pr is fix it. 
Added.
=> fix: check symbol used

Cargo.lock, Cargo.toml
Bump SWC to fix related issues: 
https://github.com/swc-project/swc/pull/7615
https://github.com/swc-project/swc/issues/7643
Tested in crate SWC
=> chore: bump swc version

crates/rspack_plugin_javascript/src/visitors/mod.rs, packages/rspack/tests/configCases/builtins/react-refresh-false/index.jsx, packages/rspack/tests/configCases/builtins/react-refresh-false/webpack.config.js
close https://github.com/web-infra-dev/rspack/issues/3816
Added
=> fix: react refresh false shouldn't inject react refresh runtime

packages/rspack-cli/src/commands/build.ts, packages/rspack-cli/src/commands/preview.ts, packages/rspack-cli/src/commands/serve.ts, packages/rspack-cli/src/rspack-cli.ts, packages/rspack-cli/src/types.ts, packages/rspack-cli/tests/build/plugin-apply-error/plugin-apply-error.test.ts, packages/rspack-cli/tests/build/plugin-apply-error/rspack.config.js, packages/rspack-cli/tests/build/plugin-apply-error/src/index.js, packages/rspack-cli/tsconfig.json, packages/rspack/src/rspack.ts
fix: error in plugin apply is not be reported when using cli
- `packages/rspack-cli/tests/build/plugin-apply-error`
=> fix: error in plugin apply is not be reported when using cli

crates/rspack_core/src/dependency/mod.rs, crates/rspack_core/src/exports_info.rs, crates/rspack_core/src/lib.rs, crates/rspack_core/src/module_graph/connection.rs, crates/rspack_core/src/module_graph/mod.rs, crates/rspack_core/src/module_graph_module.rs, crates/rspack_plugin_javascript/src/dependency/commonjs/require_resolve_dependency.rs, crates/rspack_plugin_javascript/src/dependency/url/mod.rs, crates/rspack_plugin_javascript/src/dependency/worker/mod.rs
=> feat: add some exports info api

crates/rspack_core/src/compiler/compilation.rs, crates/rspack_core/src/context_module.rs, crates/rspack_core/src/dependency/context_element_dependency.rs, crates/rspack_core/src/dependency/mod.rs, crates/rspack_plugin_javascript/src/dependency/context/common_js_require_context_dependency.rs, crates/rspack_plugin_javascript/src/dependency/context/import_context_dependency.rs, crates/rspack_plugin_javascript/src/dependency/context/require_context_dependency.rs, crates/rspack_plugin_javascript/src/dependency/esm/harmony_import_dependency.rs, packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
It used as an identifier to merge equal requests, it can reduce resolve same request for dependency.
It should be tested for exits test.
=> feat: implement dependency resource_identifier

crates/rspack_plugin_library/src/umd_library_plugin.rs, packages/rspack/tests/configCases/library/umd-named-define/index.js, packages/rspack/tests/configCases/library/umd-named-define/webpack.config.js
close https://github.com/web-infra-dev/rspack/issues/3853
Added
=> fix: generate correct name for library umd define

crates/rspack_core/src/compiler/compilation.rs, crates/rspack_core/src/compiler/queue.rs, crates/rspack_core/src/module.rs, crates/rspack_core/src/module_graph/mod.rs
=> perf: reduce dependency clone at make

crates/rspack_plugin_javascript/src/plugin/mod.rs, crates/rspack_plugin_javascript/src/runtime.rs, crates/rspack_plugin_library/src/amd_library_plugin.rs, crates/rspack_plugin_library/src/assign_library_plugin.rs, crates/rspack_plugin_library/src/export_property_plugin.rs, crates/rspack_plugin_library/src/module_library_plugin.rs, crates/rspack_plugin_library/src/system_library_plugin.rs, crates/rspack_plugin_library/src/umd_library_plugin.rs, crates/rspack_plugin_runtime/src/common_js_chunk_format.rs, packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap, packages/rspack/tests/configCases/library/umd-named-define-runtime-chunk/index.js, packages/rspack/tests/configCases/library/umd-named-define-runtime-chunk/webpack.config.js, webpack-test/configCases/library/a/test.filter.js, webpack-test/configCases/library/array-global/test.filter.js, webpack-test/configCases/library/array-window/test.filter.js, webpack-test/configCases/library/assign-properties/test.filter.js, webpack-test/configCases/library/b/test.filter.js, webpack-test/configCases/library/type-assign-properties/test.filter.js, webpack-test/configCases/library/type-assign-runtime-chunk/test.filter.js, webpack-test/configCases/library/type-assign/test.filter.js, webpack-test/configCases/library/umd-array/test.filter.js, webpack-test/configCases/library/umd/test.filter.js
close https://github.com/web-infra-dev/rspack/issues/3860
added
=> fix: render library runtime for include entry chunks

crates/node_binding/binding.d.ts, crates/node_binding/src/js_values/stats.rs, crates/rspack_core/src/compiler/compilation.rs, crates/rspack_core/src/logger.rs, packages/playground/cases/context/delete-file/index.test.ts, packages/rspack/src/compilation.ts, packages/rspack/src/config/types.ts, packages/rspack/src/loader-runner/index.ts, packages/rspack/src/logging/Logger.ts, packages/rspack/src/stats.ts, packages/rspack/src/stats/DefaultStatsFactoryPlugin.ts, packages/rspack/src/stats/statsFactoryUtils.ts, packages/rspack/tests/Stats.test.ts, packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap, packages/rspack/tests/statsCases/logging/index.js, packages/rspack/tests/statsCases/logging/test-loader.js, packages/rspack/tests/statsCases/logging/webpack.config.js
- loggingDebug and loggingTrace
- merge with js side logging
- `packages/rspack/tests/statsCases/logging`
=> feat: stats logging, part 2

packages/rspack-dev-middleware/README.md
add deprecate message in rspack-dev-middleware readme, we will remove the code in v0.3.0
=> chore: add deprecate message in rspack-dev-middleware readme

crates/rspack/tests/tree-shaking/reexport-all-as-multi-level-nested/expected/main.js, crates/rspack/tests/tree-shaking/reexport-all-as-multi-level-nested/package.json, crates/rspack/tests/tree-shaking/reexport-all-as-multi-level-nested/package/autogen/a.js, crates/rspack/tests/tree-shaking/reexport-all-as-multi-level-nested/package/autogen/aa.js, crates/rspack/tests/tree-shaking/reexport-all-as-multi-level-nested/package/autogen/b.js, crates/rspack/tests/tree-shaking/reexport-all-as-multi-level-nested/package/autogen/c.js, crates/rspack/tests/tree-shaking/reexport-all-as-multi-level-nested/package/autogen/index.js, crates/rspack/tests/tree-shaking/reexport-all-as-multi-level-nested/package/package.json, crates/rspack/tests/tree-shaking/reexport-all-as-multi-level-nested/package/src/index.js, crates/rspack/tests/tree-shaking/reexport-all-as-multi-level-nested/src/index.js, crates/rspack/tests/tree-shaking/reexport-all-as-multi-level-nested/test.config.json, crates/rspack/tests/tree-shaking/simple-namespace-access/expected/main.js, crates/rspack_core/src/tree_shaking/js_module.rs, crates/rspack_core/src/tree_shaking/optimizer.rs, crates/rspack_core/src/tree_shaking/symbol/mod.rs, crates/rspack_core/src/tree_shaking/utils.rs, crates/rspack_core/src/tree_shaking/visitor.rs, crates/rspack_core/src/utils/mod.rs, crates/rspack_core/src/utils/visitor.rs, crates/rspack_plugin_javascript/src/visitors/dependency/export_info_api_scanner.rs
1. refactor: remove unnecessary better usage.
2. Implementing more generic nested import tree shaking。
=> feat: more generic nested import

crates/rspack_plugin_banner/src/lib.rs, crates/rspack_plugin_copy/src/lib.rs, crates/rspack_plugin_ensure_chunk_conditions/src/lib.rs, crates/rspack_plugin_remove_empty_chunks/src/lib.rs, crates/rspack_plugin_split_chunks_new/src/plugin/mod.rs, packages/rspack/tests/Stats.test.ts
add more logger.time in plugins
=> feat: add more logger.time in plugins

crates/rspack_binding_options/src/options/mod.rs, crates/rspack_core/src/utils/find_graph_roots.rs, packages/rspack/tests/configCases/split-chunks/issue-3646/src/index.js
This is an alignment feature. The previous implementation caused some inconsistency, which is not good for debugging.
I have tested in the FS project and everything seems ok.
=> feat(chunkIds): align `chunkIds: 'named'` with Webpack

crates/rspack/tests/tree-shaking/import-export-all-as-a-empty-module/a.js, crates/rspack/tests/tree-shaking/import-export-all-as-a-empty-module/expected/main.js, crates/rspack/tests/tree-shaking/import-export-all-as-a-empty-module/index.js, crates/rspack/tests/tree-shaking/import-export-all-as-a-empty-module/test.config.json, crates/rspack_core/src/tree_shaking/optimizer.rs
1. fixed issue when a side effects free module has no exports used but it is used as a `ImportAllAs` or `ExportAllAs`
added
=> fix: import export all as is empty module

examples/nestjs/package.json, examples/nestjs/rspack.config.js, examples/nestjs/src/main.ts, pnpm-lock.yaml
may people are asking node hmr support, and it seems that we already support it
https://github.com/web-infra-dev/rspack/assets/8898718/3fd1f9ae-5d87-4e81-8117-0f8b4e15e76d
No Test Needed
=> chore: nest example support hmr

crates/node_binding/binding.d.ts, crates/rspack_binding_options/src/options/raw_builtins/mod.rs, crates/rspack_core/src/options/builtins.rs, crates/rspack_plugin_javascript/src/ast/minify.rs, crates/rspack_plugin_javascript/src/lib.rs, crates/rspack_plugin_javascript/src/plugin/impl_plugin_for_js_plugin.rs, crates/rspack_testing/src/test_config.rs, packages/rspack/src/config/builtins.ts, packages/rspack/tests/Defaults.unittest.ts, packages/rspack/tests/Stats.test.ts, packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap, packages/rspack/tests/configCases/builtins/minify-comment-all/a.js, packages/rspack/tests/configCases/builtins/minify-comment-all/index.js, packages/rspack/tests/configCases/builtins/minify-comment-all/webpack.config.js, packages/rspack/tests/configCases/builtins/minify-comment-default-false/a.js, packages/rspack/tests/configCases/builtins/minify-comment-default-false/index.js, packages/rspack/tests/configCases/builtins/minify-comment-default-false/webpack.config.js, packages/rspack/tests/configCases/builtins/minify-comment-some/a.js, packages/rspack/tests/configCases/builtins/minify-comment-some/index.js, packages/rspack/tests/configCases/builtins/minify-comment-some/webpack.config.js
closes: https://github.com/web-infra-dev/rspack/issues/3926
=> feat: support minifyOptions.comments

packages/rspack/src/compilation.ts
=> perf: reduce `compilation.getAssets` overhead

.github/issue-close-require.yml
add issue close bot to close inactive "need reproduction" labeled issue
No Test Needed
=> chore: add close-issues bot

packages/rspack/package.json, pnpm-lock.yaml
related to https://github.com/web-infra-dev/rspack/issues/3867#issuecomment-1672888747, webpack-dev-server is not used in @rspack/core
No Test Needed
=> fix(core): remove webpack-dev-server from @rspack/core

crates/node_binding/binding.d.ts, crates/node_binding/src/lib.rs, crates/node_binding/src/utils.rs, crates/rspack_tracing/src/lib.rs, packages/rspack/src/rspack.ts
Flush chrome tracer on `SIGINT` or node env cleaups.
Not necessary.
=> fix: fix trace subscriber for dev

crates/node_binding/src/lib.rs, crates/node_binding/src/utils.rs
=> chore: move binding utils

.github/PULL_REQUEST_TEMPLATE/minor-release-mr.md
testing add template for release mr template, will add template detail later
No Test needed
=> chore: test multi pull request template

crates/node_binding/binding.d.ts, crates/node_binding/src/js_values/compilation.rs, crates/node_binding/src/js_values/stats.rs, crates/rspack_core/src/context_module.rs, crates/rspack_core/src/external_module.rs, crates/rspack_core/src/missing_module.rs, crates/rspack_core/src/module.rs, crates/rspack_core/src/module_graph/mod.rs, crates/rspack_core/src/normal_module.rs, crates/rspack_core/src/raw_module.rs, crates/rspack_core/src/stats.rs, crates/rspack_plugin_runtime/src/lazy_compilation.rs, crates/rspack_plugin_runtime/src/runtime_module/module_macro.rs, packages/rspack/src/stats/DefaultStatsFactoryPlugin.ts, packages/rspack/tests/watchCases/stats/get-hash-panic/0/changing-file.js, packages/rspack/tests/watchCases/stats/get-hash-panic/0/index.js, packages/rspack/tests/watchCases/stats/get-hash-panic/1/changing-file.js, packages/rspack/tests/watchCases/stats/get-hash-panic/2/changing-file.js, packages/rspack/tests/watchCases/stats/get-hash-panic/webpack.config.js
- add `packages/rspack/tests/watchCases/stats/get-hash-panic`
=> fix: getHash occasionally panic when rebuild

.github/workflows/need-doc.yml
try sync doc issue when add label
=> chore: sync doc when add need documentation label

.github/workflows/need-doc.yml
=> chore: test label

.github/workflows/lint-pr.yaml
we need release scope for release mr
No Test Needed
=> chore: add release scope

packages/rspack-cli/src/rspack-cli.ts, packages/rspack-cli/src/utils/profile.ts, packages/rspack-cli/tests/build/profile/profile.test.ts
add timestamp on profile dist
- update `packages/rspack-cli/tests/build/profile/profile.test.ts`
=> feat: add timestamp on profile dist

examples/postcss-loader/index.html, examples/postcss-loader/package.json, examples/postcss-loader/rspack.config.js, examples/postcss-loader/src/index.css, examples/postcss-loader/src/index.js, pnpm-lock.yaml
add postcss-loader example, so we can reference it 0.3 release note
No need
=> chore: add postcss-loader-example

.github/workflows/bench.yml
`!bench` command remove `reportComment` inputs.
=> chore: benchmark pr remove useless inputs

packages/playground/package.json, pnpm-lock.yaml
`workspace:^0.2.6` cause install failure when release 0.3.0
=> chore: fix workspace dep

crates/rspack_core/src/module.rs, crates/rspack_plugin_javascript/src/plugin/mod.rs, crates/rspack_plugin_javascript/src/plugin/side_effects_flag_plugin.rs
1. port webpack sideEffectsFlagPlugin
=> feat(webpack-tree-shaking): side effects plugin

.github/workflows/bench-merge-queue.yml
Benchmark performance when pushing a pr to merge queue
=> chore: add benchmark test for merge queue

README.md
=> chore: update benchmark website

crates/rspack/tests/tree-shaking/webpack-reexport-namespace-and-default/expected/main.js, crates/rspack_core/src/init_fragment.rs, crates/rspack_plugin_javascript/src/runtime.rs
close  https://github.com/web-infra-dev/rspack/issues/4000
Updated test sanpshot.
=> feat: merge same init fragments

crates/rspack_core/src/chunk.rs, packages/rspack/tests/runtimeCases/runtime/issue-4019/dynamic.js, packages/rspack/tests/runtimeCases/runtime/issue-4019/index.js, packages/rspack/tests/runtimeCases/runtime/issue-4019/index2.js, packages/rspack/tests/runtimeCases/runtime/issue-4019/shared.js, packages/rspack/tests/runtimeCases/runtime/issue-4019/webpack.config.js
=> fix(runtime): should calculate `initial_chunks` correctly

crates/rspack_core/src/dependency/mod.rs, crates/rspack_core/src/module.rs, crates/rspack_core/src/module_graph/connection.rs, crates/rspack_core/src/module_graph/mod.rs, crates/rspack_core/src/normal_module.rs, crates/rspack_plugin_javascript/src/dependency/esm/harmony_export_imported_specifier_dependency.rs, crates/rspack_plugin_javascript/src/dependency/esm/harmony_import_side_effect_dependency.rs, crates/rspack_plugin_javascript/src/dependency/esm/harmony_import_specifier_dependency.rs, crates/rspack_plugin_javascript/src/dependency/esm/mod.rs, crates/rspack_plugin_javascript/src/visitors/dependency/harmony_import_dependency_scanner.rs, packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
Implement HarmonyImportSideEffectDependency.
It isn't enabled.
=> feat: add HarmonyImportSideEffectDependency

packages/rspack/src/index.ts
export Watching and DevServe type for nx-labs, releated to #3861 
No Test Needed
=> feat: export `Watching` type

examples/nestjs/package.json, examples/nestjs/rspack.config.js
No need to run main.js during build and disable minify reduce the build time in ci
=> chore: fix nestjs example

Cargo.lock, crates/rspack_error/Cargo.toml
fix ci cache miss due to use git repo url version, we forked codespan as rspack-codespan in https://github.com/hardfist/rspack-codespan/pull/1 since codespan seems not maintained any more
No Extra Tests needed
=> chore: fix cache problem

packages/rspack/tests/ConfigCase.template.ts, packages/rspack/tests/configCases/css/urls/webpack.config.js
currently rspack try run tests in tests folder, but some folder are moved or ignored on remote branch but the folder is not deleted in local branch, so skip empty folder(without webpack.config.js) for testing
tests are updated
=> chore: skip empty test folder

crates/rspack_plugin_javascript/src/visitors/dependency/common_js_export_scanner.rs, packages/rspack/tests/cases/mjs/cjs-import-default/index.mjs, packages/rspack/tests/cases/mjs/cjs-import-default/umd.js
Fix umd analyze exports type result.
Added.
=> fix: umd analyze

Cargo.lock, Cargo.toml, crates/rspack_plugin_javascript/src/utils.rs, crates/rspack_plugin_javascript/src/visitors/swc_visitor/hygiene.rs, crates/rspack_plugin_swc_js_minimizer/src/minify.rs, crates/swc_plugin_import/src/lib.rs
fix issue caused by https://github.com/swc-project/swc/issues/7798
No Extra Test
=> fix: upgrade swc

packages/rspack/src/Compiler.ts, packages/rspack/src/index.ts
=> feat: export externals plugin and node target plugin, electron target plugin

.github/workflows/ci.yml
Take down windows CI until it's fixed.
=> ci: take down windows test

packages/rspack-cli/package.json, pnpm-lock.yaml
https://github.com/advisories/GHSA-c2qf-rxjj-qqgw
=> chore: Upgraded `semver` to `6.3.1`

.github/workflows/ci.yml, crates/rspack_database/Cargo.toml, crates/rspack_identifier/Cargo.toml, deny.toml
add license check in case introduce unexpected license by accident
=> chore: add license check

packages/playground/cases/react/basic/rspack.config.js, packages/rspack-dev-client/package.json, packages/rspack-dev-client/src/runtimePathRegexp.js, packages/rspack-dev-server/src/server.ts
close https://github.com/web-infra-dev/rspack/issues/3984
Added
=> fix: avoid inject refresh runtime for it self

.github/workflows/ci.yml
See https://github.com/web-infra-dev/rspack/pull/4097#issuecomment-1704741298.
Related https://github.com/web-infra-dev/rspack/pull/4100
=> ci: take down windows test, again

.github/workflows/reusable-build.yml
The release is always timeout https://github.com/web-infra-dev/rspack/actions/runs/6080313608
=> chore: increase windows ci test timeout minutes

crates/node_binding/binding.d.ts, crates/node_binding/src/js_values/stats.rs, crates/rspack_core/src/stats.rs, packages/rspack/tests/Stats.test.ts, packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap, packages/rspack/tests/fixtures/abc-query.js
=> chore: expose statsModule.nameForCondition

.github/PULL_REQUEST_TEMPLATE.md
PR from @web-infra-dev/rspack-core should attach related rspack-website document link if the PR needs documentation
No Test Needed
=> chore: add documenation link notice of pull request template

package.json, packages/rspack/package.json, pnpm-lock.yaml
closes https://github.com/web-infra-dev/rspack/issues/4128
=> chore: use cross-env

packages/rspack/tests/Stats.test.ts, packages/rspack/tests/fixtures/abc-query.js
Jest path serializer seems buggy in some cases: https://github.com/web-infra-dev/rspack/actions/runs/6092704778/job/16531589729#step:8:2044
[X] No
[ ] Yes, the corresponding rspack-website PR is \_\_
=> fix: test snapshot path

.github/PULL_REQUEST_TEMPLATE.md
=> chore: format PR template

packages/rspack-dev-server/src/server.ts
Remove console.
Do we have a way to add a `no-console` rule for `oxclint`? @Boshen
=> fix: console should not appear here

crates/rspack_core/src/exports_info.rs, crates/rspack_core/src/module.rs, crates/rspack_plugin_javascript/src/dependency/esm/harmony_export_imported_specifier_dependency.rs, crates/rspack_plugin_javascript/src/dependency/esm/harmony_export_specifier_dependency.rs, crates/rspack_plugin_javascript/src/dependency/esm/harmony_import_specifier_dependency.rs, crates/rspack_plugin_javascript/src/visitors/dependency/harmony_export_dependency_scanner.rs, crates/rspack_plugin_javascript/src/visitors/dependency/harmony_import_dependency_scanner.rs, crates/rspack_plugin_javascript/src/visitors/dependency/mod.rs, crates/rspack_plugin_javascript/src/visitors/dependency/util.rs
Add star exports info for HarmonyExportImportedSpecifierDependency
Not need.
=> feat: HarmonyExportImportedSpecifierDependency get mode

packages/rspack/src/Compilation.ts, packages/rspack/src/config/zod.ts, packages/rspack/src/stats/DefaultStatsFactoryPlugin.ts, packages/rspack/src/stats/statsFactoryUtils.ts, packages/rspack/tests/Stats.test.ts, packages/rspack/tests/__snapshots__/Stats.test.ts.snap, packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
support stats ids, and resolve #4139 
- Added
=> feat: support stats ids

Cargo.lock, Cargo.toml
more info: https://github.com/web-infra-dev/rspack-sources/pull/62
=> perf: optimize process assets

packages/rspack-plugin-react-refresh/package.json
=> chore: fix publish problems of react-refresh

packages/rspack-plugin-react-refresh/package.json
=> fix: export client dir in react-refresh-plugin

crates/rspack_plugin_runtime/src/runtime_module/runtime/css_loading_with_loading.js, packages/playground/cases/react/basic/index.test.ts, packages/playground/cases/react/basic/src/App.jsx, packages/playground/cases/react/basic/src/LazyComponent.jsx
close https://github.com/web-infra-dev/rspack/issues/4162.
Add e2e
=> fix: resolve async css chunk loading promise

packages/rspack-cli/src/utils/profile.ts
=> chore: add profile syntax comment

crates/rspack_core/src/chunk_graph/chunk_graph_module.rs, crates/rspack_plugin_javascript/src/dependency/worker/mod.rs, crates/rspack_plugin_runtime/src/runtime_module/load_chunk_with_module.rs, packages/rspack/tests/configCases/chunk-loading/false/dynamic.js, packages/rspack/tests/configCases/chunk-loading/false/index.js, packages/rspack/tests/configCases/chunk-loading/false/webpack.config.js
close https://github.com/web-infra-dev/rspack/issues/4150
Added.
=> fix: chunkLoading false

packages/rspack/src/config/zod.ts
Part of https://github.com/web-infra-dev/rspack/discussions/4168.
Not needed.
=> feat(config): warn while using `experiments.newSplitChunks`

packages/rspack/src/config/zod.ts
Fix https://github.com/web-infra-dev/rspack/pull/4169#issuecomment-1715039630
=> feat(config): only warn while `experiments.newSplitChunks` being explicitly setted

scripts/build-npm.cjs
Releases should only include packages for which the artifact is available.
i.e included in the CI build result.
=> ci: refine artifact publishing

crates/node_binding/binding.d.ts, crates/rspack_binding_options/src/options/raw_builtins/mod.rs, crates/rspack_binding_options/src/options/raw_external.rs, crates/rspack_plugin_externals/src/http_externals_plugin.rs, crates/rspack_testing/src/test_config.rs, packages/rspack/src/builtin-plugin/HttpExternalsRspackPlugin.ts, packages/rspack/src/config/zod.ts, packages/rspack/src/rspackOptionsApply.ts
https://github.com/web-infra-dev/rspack/issues/4080
add externalsPresets webAsync target support
=> feat: add externalsPresets webAsync target support

crates/node_binding/src/hook.rs, crates/node_binding/src/plugins/mod.rs, packages/rspack/src/Compiler.ts
=> fix: perf regression caused by optimizeTree hook

crates/rspack_core/src/runtime_module.rs, crates/rspack_plugin_runtime/src/lib.rs, crates/rspack_plugin_runtime/src/runtime_module/auto_public_path.rs, crates/rspack_plugin_runtime/src/runtime_module/css_loading.rs, crates/rspack_plugin_runtime/src/runtime_module/import_scripts_chunk_loading.rs, crates/rspack_plugin_runtime/src/runtime_module/jsonp_chunk_loading.rs, crates/rspack_plugin_runtime/src/runtime_module/mod.rs, crates/rspack_plugin_runtime/src/runtime_module/module_chunk_loading.rs, crates/rspack_plugin_runtime/src/runtime_module/public_path.rs, crates/rspack_plugin_runtime/src/runtime_module/readfile_chunk_loading.rs, crates/rspack_plugin_runtime/src/runtime_module/require_js_chunk_loading.rs, crates/rspack_plugin_runtime/src/runtime_plugin.rs, crates/rspack_plugin_wasm/src/runtime.rs, packages/rspack/tests/cases/css/rewrite-url-auto-public-path/webpack.config.js
- Separate PublicPathRuntimeModule 
- Add RuntimeModuleStage
- Async node async chunk loading should be true
Not need
=> refactor: public path runtime module

examples/nestjs/rspack.config.js, packages/rspack-dev-server/src/server.ts, packages/rspack-dev-server/tests/__snapshots__/normalizeOptions.test.ts.snap, packages/rspack-dev-server/tests/normalizeOptions.test.ts
=> fix: shouldn't always apply react refresh plugin

crates/rspack_plugin_progress/src/lib.rs, packages/rspack/src/stats/DefaultStatsPrinterPlugin.ts, packages/rspack/tests/Stats.test.ts, packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
- Thinner and shorter lines
- Removed progress text
- Green color
Preview:
https://github.com/web-infra-dev/rspack/assets/7237365/b11fd939-560d-4a47-83c3-f81a136bae3d
=> feat(progress): optimize the progress bar style

examples/proxy/package.json, pnpm-lock.yaml
=> chore: fix example dep

examples/emotion/rspack.config.js
=> chore: fix example-emotion

packages/rspack-plugin-react-refresh/client/reactRefreshEntry.js
Related: https://github.com/web-infra-dev/rspack/issues/4190
CI passes
=> fix: fix react-refresh `self` is not defined

examples/worklet/index.html, examples/worklet/loader/worklet-loader.js, examples/worklet/package.json, examples/worklet/rspack.config.js, examples/worklet/src/answer.js, examples/worklet/src/index.js, examples/worklet/src/lib.js, examples/worklet/src/worklet/answer.ts, examples/worklet/src/worklet/complex.worklet.js, examples/worklet/src/worklet/simple.worklet.js, pnpm-lock.yaml
Add worklet and express example
related to https://twitter.com/felix_mosheev/status/1705833556671381890 and discord request
No Need
=> chore: worklet example & express example

packages/rspack-plugin-react-refresh/tests/test.spec.ts
=> fix: react refresh test windows failed

examples/express/package.json, examples/express/rspack.config.js, examples/express/src/api/root.ts, examples/express/src/main.ts, packages/rspack/src/builtin-loader/swc/relay.ts, pnpm-lock.yaml
=> fix(chore): fix node path compatible problem & add express example

crates/rspack_plugin_runtime/src/runtime_module/runtime/css_loading_with_loading.js
=> fix: css chunk loading missing chunkIds

.github/workflows/github-issue-sync.yml
=> chore: move sync workflow

.github/workflows/reusable-build.yml
try free disk to workaround no space problem on ci  see https://github.com/actions/runner-images/issues/2875#issuecomment-1167936457
No Need
=> chore: try free disk for linux

.cargo/config.toml
- Close https://github.com/web-infra-dev/rspack/issues/4274
=> build: static link msvc runtime on Windows x86_64 platform

crates/node_binding/binding.d.ts, crates/node_binding/src/js_values/compilation.rs, packages/rspack/src/Compilation.ts, packages/rspack/tests/Compiler.test.ts
Support `Compilation.namedChunks`.
closes https://github.com/web-infra-dev/rspack/issues/4253
Added
=> feat: support `Compilation.namedChunks`

packages/rspack/src/stats/DefaultStatsPrinterPlugin.ts
=> chore(core): Optimization of compilation duration unit

crates/node_binding/binding.d.ts, crates/rspack_core/src/cache/occasion/code_generate.rs, crates/rspack_core/src/code_generation_results.rs, crates/rspack_core/src/compiler/compilation.rs, crates/rspack_core/src/compiler/hmr.rs, crates/rspack_core/src/context_module.rs, crates/rspack_core/src/dependency/dependency_template.rs, crates/rspack_core/src/external_module.rs, crates/rspack_core/src/missing_module.rs, crates/rspack_core/src/module.rs, crates/rspack_core/src/module_graph/mod.rs, crates/rspack_core/src/normal_module.rs, crates/rspack_core/src/parser_and_generator.rs, crates/rspack_core/src/raw_module.rs, crates/rspack_core/src/runtime.rs, crates/rspack_plugin_css/src/dependency/url.rs, crates/rspack_plugin_css/src/parser_and_generator/mod.rs, crates/rspack_plugin_javascript/src/parser_and_generator/mod.rs, crates/rspack_plugin_runtime/src/lazy_compilation.rs, crates/rspack_plugin_runtime/src/runtime_module/module_macro.rs
1. prerequisite of `Runtime optimization`.
=> feat: Adding runtime param when executing codegen 

webpack-test/cases/chunks/circular-correctness/test.filter.js, webpack-test/cases/chunks/import-circle/test.filter.js, webpack-test/cases/chunks/import-context-exist-chunk/test.filter.js, webpack-test/cases/chunks/import-context/test.filter.js, webpack-test/cases/chunks/import/test.filter.js, webpack-test/cases/chunks/issue-2443/test.filter.js, webpack-test/cases/chunks/issue-5153/test.filter.js
=> chore: enable more webpack-test

examples/vue2/package.json, examples/vue2/rspack.config.js, examples/vue2/src/App.vue, pnpm-lock.yaml
fix https://github.com/web-infra-dev/rspack/issues/3434
No Need
=> chore: update vue2 example using experiments.css

examples/vue2/package.json
vue-loader@15 [support experimental inline match resource pr ](https://github.com/vuejs/vue-loader/issues/2058)merged
=> chore: update vue-loader@15.11.0 stable version

README.md, README.zh-CN.md
add community section so users can find discord channel more easily
No Need
=> chore: expose discord explictly in readme

packages/create-rspack/template-react-ts/index.html
=> chore: set lang to en for react-ts template

.github/workflows/reusable-build.yml
Disable shared rustup cache to avoid failure to install components, more error info see:
https://github.com/web-infra-dev/rspack/actions/runs/6607094047/job/17946280689
=> chore: fix rustup install components failed

crates/node_binding/binding.d.ts, crates/rspack_binding_options/src/options/raw_split_chunks.rs, crates/rspack_plugin_runtime/src/runtime_module/load_chunk_with_module.rs, crates/rspack_plugin_split_chunks_new/src/module_group.rs, crates/rspack_plugin_split_chunks_new/src/plugin/min_size.rs, crates/rspack_plugin_split_chunks_new/src/plugin/mod.rs, crates/rspack_plugin_split_chunks_new/src/plugin/module_group.rs, packages/playground/cases/css/chunk-loading-order/index.test.ts, packages/playground/cases/css/chunk-loading-order/rspack.config.js, packages/playground/cases/css/chunk-loading-order/src/a.css, packages/playground/cases/css/chunk-loading-order/src/async.js, packages/playground/cases/css/chunk-loading-order/src/b.css, packages/playground/cases/css/chunk-loading-order/src/index.js, packages/playground/fixtures/rspack.ts, packages/rspack/src/builtin-plugin/HtmlRspackPlugin.ts, packages/rspack/src/config/adapter.ts
=> fix(splitChunks): not matched cacheGroup should not affect cacheGroupIndex

.github/workflows/reusable-build.yml
The target will be installed in [actions/docker-build/action.xml](https://github.com/web-infra-dev/rspack/blob/f41af0886fa1dcca3c265316b03a8783c7f98075/.github/actions/docker-build/action.yml#L39), so remove this useless code.
=> chore: remove useless rustup target install

packages/create-rspack/template-vue/src/App.vue, packages/create-rspack/template-vue/src/components/HelloWorld.vue
1. Components use setup syntax.
2. Remove unsupported `lang="ts"`.
3. Keep component styles consistent.
=> chore: component style remains consistent

packages/rspack/src/config/adapter.ts
=> fix: loader definition not being exported

Cargo.lock, Cargo.toml, crates/rspack_napi_shared/src/errors.rs, packages/rspack/tests/configCases/errors/asset-module-build-failed/index.js, packages/rspack/tests/configCases/errors/loader-error-async/index.js, packages/rspack/tests/configCases/errors/loader-syntax-error/index.js, packages/rspack/tests/configCases/errors/loader-throw-error/index.js
Fix NAPI error reference issue
Added
=> chore: upgrade napi

Cargo.lock, Cargo.toml, crates/rspack_plugin_html/Cargo.toml, crates/rspack_plugin_html/src/plugin.rs, packages/playground/cases/html/issue-4366/index.test.ts, packages/playground/cases/html/issue-4366/rspack.config.js, packages/playground/cases/html/issue-4366/src/index.html, packages/playground/cases/html/issue-4366/src/index.js
Fixes #4366
Ensure that it has been watched.
=> fix: insert the path of html template to fileDependencies

crates/rspack_core/src/dependency/mod.rs, crates/rspack_core/src/tree_shaking/visitor.rs, crates/rspack_plugin_javascript/src/plugin/infer_async_modules_plugin.rs, crates/rspack_plugin_javascript/src/visitors/dependency/harmony_import_dependency_scanner.rs, packages/rspack/tests/configCases/tree-shaking/multiple-same-export-side-effect/index.js, packages/rspack/tests/configCases/tree-shaking/multiple-same-export-side-effect/lib.js, packages/rspack/tests/configCases/tree-shaking/multiple-same-export-side-effect/reexport.js, packages/rspack/tests/configCases/tree-shaking/multiple-same-export-side-effect/webpack.config.js
Closed https://github.com/web-infra-dev/rspack/issues/4434
=> fix: 🐛 export multiple export

crates/rspack_plugin_javascript/src/visitors/dependency/api_scanner.rs, packages/rspack/tests/cases/parsing/empty-resource-query/a.js, packages/rspack/tests/cases/parsing/empty-resource-query/abc.js, packages/rspack/tests/cases/parsing/empty-resource-query/index.js, webpack-test/cases/parsing/issue-7778/test.filter.js
=> fix: empty __resourceQuery replace

x.mjs
simplify tests process on webpack-tests
No Need
=> chore: add ./x webpack for run tests against webpack-test suites

.github/workflows/issue-close-require.yml, .github/workflows/release-nightly.yml, .github/workflows/release-pull-request.yml
The scheduled GitHub action should not run on forked repositories.
=> fix: the scheduled GitHub action should not run on forked repositories

crates/rspack_core/src/build_chunk_graph/code_splitter.rs, crates/rspack_core/src/chunk_group.rs, packages/rspack/tests/configCases/errors/entry-runtime-error/a.js, packages/rspack/tests/configCases/errors/entry-runtime-error/b.js, packages/rspack/tests/configCases/errors/entry-runtime-error/errors.js, packages/rspack/tests/configCases/errors/entry-runtime-error/test.config.js, packages/rspack/tests/configCases/errors/entry-runtime-error/webpack.config.js
=> fix: duplicate entrypoint files

packages/rspack/tests/StatsTestCases.test.ts, packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap, packages/rspack/tests/statsCases/limit-chunk-count-plugin/test.filter.js
fix https://github.com/web-infra-dev/rspack/actions/runs/6686684114/job/18208870356
=> fix: windows stats snapshot

packages/rspack/tests/runtimeDiffCases/runtime-create-fake-namespace-object/src/async.js, packages/rspack/tests/runtimeDiffCases/runtime-create-fake-namespace-object/src/index.js, packages/rspack/tests/runtimeDiffCases/runtime-create-fake-namespace-object/test.config.js
Alignment of create fake namespace object runtime module
=> chore(runtime-diff): alignment of create fake namespace object runtime module

.github/actions/pnpm-cache/action.yml, .github/workflows/bench-history.yaml.bak, .github/workflows/ci.yml, .github/workflows/release-canary.yml, .github/workflows/release-nightly.yml, .github/workflows/release.yml
=> chore: check pnpm lockfile on ci

crates/rspack_plugin_runtime/src/runtime_module/runtime/global.js, packages/rspack/tests/runtimeDiffCases/runtime-global/rspack.config.js, packages/rspack/tests/runtimeDiffCases/runtime-global/src/index.css, packages/rspack/tests/runtimeDiffCases/runtime-global/src/index.js, packages/rspack/tests/runtimeDiffCases/runtime-global/test.config.js, packages/rspack/tests/runtimeDiffCases/runtime-global/webpack.config.js
Alignment of global runtime module, just format the code
=> chore(runtime-diff): alignment of global runtime module

crates/rspack_plugin_javascript/src/visitors/dependency/harmony_top_level_this.rs, crates/rspack_plugin_javascript/src/visitors/dependency/mod.rs, webpack-test/cases/parsing/es2020/test.filter.js
=> feat: replace top-level this in esm

.github/actions/download-artifact/action.yml, .github/actions/upload-artifact/action.yml
=> chore: release do not use local cache

crates/rspack_plugin_runtime/src/runtime_module/load_script.rs, crates/rspack_plugin_runtime/src/runtime_module/runtime/load_script.js, packages/rspack/tests/runtimeDiffCases/runtime-load-script/rspack.config.js, packages/rspack/tests/runtimeDiffCases/runtime-load-script/src/index.js, packages/rspack/tests/runtimeDiffCases/runtime-load-script/test.config.js, packages/rspack/tests/runtimeDiffCases/runtime-load-script/webpack.config.js
Alignment of load script runtime module
- Format code just the same as webpack
- Do not inject the cross origin code when disabled
=> chore(runtime-diff): alignment of load script runtime module

Cargo.lock, Cargo.toml, crates/rspack_plugin_javascript/src/visitors/swc_visitor/compat.rs
Fixes https://github.com/web-infra-dev/rspack/issues/4525
=> chore: bump swc

crates/rspack_plugin_swc_js_minimizer/src/lib.rs, crates/rspack_plugin_swc_js_minimizer/src/minify.rs, packages/rspack/tests/Compiler.test.ts, packages/rspack/tests/configCases/plugins/swc-js-minifer/extract.js, packages/rspack/tests/configCases/plugins/swc-js-minifer/index.js, packages/rspack/tests/configCases/plugins/swc-js-minifer/webpack.config.js
Fixes https://github.com/web-infra-dev/rspack/issues/4524
=> feat: support banner in extractComments of minify

.github/CODEOWNERS
=> chore(CODEOWNERS): update some owners

packages/playground/cases/vue3/index.test.ts, packages/playground/cases/vue3/rspack.config.js, packages/playground/cases/vue3/src/App.vue, packages/playground/cases/vue3/src/enums.ts, packages/playground/package.json, packages/rspack/src/Compiler.ts, packages/rspack/src/FileSystemInfo.ts, packages/rspack/src/Watching.ts, pnpm-lock.yaml
closes https://github.com/web-infra-dev/rspack/issues/4540
Added for vue
=> feat: support timestamps

crates/node_binding/binding.d.ts, crates/node_binding/package.json, crates/node_binding/scripts/build.js, crates/rspack_binding_options/src/options/raw_builtins/mod.rs, crates/rspack_binding_options/src/options/raw_builtins/raw_banner.rs, crates/rspack_binding_options/src/options/raw_builtins/raw_swc_js_minimizer.rs, crates/rspack_binding_options/src/options/raw_external.rs, crates/rspack_core/src/options/externals.rs, crates/rspack_napi_shared/src/js_values/js_reg_exp.rs, crates/rspack_napi_shared/src/lib.rs, crates/rspack_napi_shared/src/threadsafe_function.rs, crates/rspack_napi_shared/src/utils.rs, crates/rspack_plugin_banner/src/lib.rs, crates/rspack_regex/src/lib.rs, packages/rspack/src/builtin-plugin/BannerPlugin.ts, packages/rspack/src/builtin-plugin/ExternalsPlugin.ts, packages/rspack/src/builtin-plugin/SwcJsMinimizerPlugin.ts, packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap, packages/rspack/tests/configCases/plugins/minify-exclude/test.filter.js, packages/rspack/tests/configCases/plugins/minify-exclude/webpack.config.js, packages/rspack/tests/configCases/plugins/minify-test/test.filter.js, packages/rspack/tests/configCases/plugins/minify-test/webpack.config.js, x.mjs
Enable more test cases. Refactored some cumbersome implementations.
Related https://github.com/web-infra-dev/rspack/issues/4544.
Added.
=> refactor: remove cumbersome type conversions

crates/rspack_napi_shared/src/js_values/js_reg_exp.rs, crates/rspack_napi_shared/src/utils.rs
Fix unsoundness of napi type detection.
See https://nodejs.org/dist/latest-v21.x/docs/api/n-api.html#object-lifetime-management for details
Not needed.
=> fix: fix unsoundness of napi type detection

packages/rspack/src/builtin-plugin/index.ts, packages/rspack/src/config/zod.ts
=> feat: deprecate splitChunks options

crates/rspack_core/src/compiler/queue.rs, crates/rspack_core/src/loader/loader_runner.rs, crates/rspack_loader_sass/tests/fixtures.rs, crates/rspack_loader_swc/tests/fixtures.rs
Add module and context in loaderContext
=> feat: add module and context fields in loader context

crates/rspack_core/src/compiler/compilation.rs, crates/rspack_core/src/plugin/api.rs, crates/rspack_core/src/plugin/args.rs, crates/rspack_core/src/plugin/plugin_driver.rs, crates/rspack_plugin_runtime/src/runtime_plugin.rs, packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
Alignment of module level runtime requirements with webapck
- Handle require scope requirements
- Handle runtime requirements by dependencies
=> feat(runtime): alignment of module runtime requirements

.vscode/launch.json
Adding breakpoints to JS code sometimes does not work as expected.
lldb debugger should wait until JS debugger attached to continue the process.
=> chore: fix `launch.json`

.github/auto_assign.yml, .github/workflows/auto-assign.yaml
auto assign author as assignee so we can filter PR by assignee on Project
No Need
=> chore: auto assign author as assignee

.github/workflows/auto-assign.yaml
=> chore: fix auto-assign workflow

crates/rspack/tests/tree-shaking/tree-shaking-interop/snapshot/new_treeshaking.snap, crates/rspack/tests/tree-shaking/tree-shaking-interop/snapshot/output.snap, crates/rspack_core/src/dependency/runtime_template.rs, crates/rspack_plugin_runtime/src/runtime_module/runtime/compat_get_default_export.js, packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap, packages/rspack/tests/runtimeDiffCases/runtime-compat-get-default-export/src/a.js, packages/rspack/tests/runtimeDiffCases/runtime-compat-get-default-export/src/b.js, packages/rspack/tests/runtimeDiffCases/runtime-compat-get-default-export/src/index.js, packages/rspack/tests/runtimeDiffCases/runtime-compat-get-default-export/test.config.js
Alignment of compat get default export runtime module
=> chore(runtime-diff): alignment of compat get default export runtime module

packages/rspack/src/Stats.ts, packages/rspack/src/stats/statsFactoryUtils.ts
Helpful for rsbuild / rsbuild-doctor using
https://github.com/web-infra-dev/rsbuild/blob/main/packages/shared/src/types/stats.ts#L32
=> chore: export more stats type for users use

packages/rspack-cli/tsconfig.json
add react-refresh reference , so I only need run dev in rspakc-cli package
No Need
=> chore: add react-refresh to rspack-cli reference

Cargo.lock, crates/rspack_core/Cargo.toml, crates/rspack_core/src/resolver/resolver_impl.rs
=> feat(resolver): print detailed error messages for oxc_resolver (#4564)

crates/rspack_core/src/compiler/compilation.rs
Align API with webpack
Some API incoming rely on process_runtime_requirements with custom modules, chunks, and entries
=> refactor(process_runtime_requirements): align api with webpack

Cargo.lock, Cargo.toml
=> chore: bump swc-emotion

crates/node_binding/binding.d.ts, crates/rspack_binding_values/src/chunk.rs, packages/rspack/src/Chunk.ts
Add auxiliary_files in js chunk
=> feat: add auxiliary_files in js chunk

.github/workflows/reusable-build.yml, packages/rspack/package.json
fixes https://github.com/web-infra-dev/rspack/issues/4583
Drop NodeJS 14 Test
=> chore: drop NodeJS 14 support

packages/create-rspack/template-react-ts/package.json, packages/create-rspack/template-react-ts/rspack.config.js, packages/create-rspack/template-react/package.json, packages/create-rspack/template-react/rspack.config.js, packages/create-rspack/template-vue/package.json, packages/create-rspack/template-vue/rspack.config.js, packages/rspack-cli/package.json, pnpm-lock.yaml
closes https://github.com/web-infra-dev/rspack/issues/4644
=> chore: make core a peerDependency of cli in 0.4

package.json, scripts/doctor.js
=> chore: remove useless pnpm:devPreinstall and doctor.js from `package.json`

.github/workflows/reusable-build.yml, .npmrc, Cargo.lock, crates/rspack_core/Cargo.toml, package.json, pnpm-lock.yaml
=> chore: node 20 + pnpm 8

crates/node_binding/binding.d.ts, packages/rspack/package.json, pnpm-lock.yaml
=> fix: @swc/jest type error

packages/rspack/src/exports.ts
=> fix: export StatsCompilation

crates/rspack_core/src/options/output.rs, crates/rspack_ids/src/deterministic_chunk_ids_plugin.rs, crates/rspack_ids/src/deterministic_module_ids_plugin.rs, crates/rspack_ids/src/id_helpers.rs
1. align `assignDeterministicIds` you could refer to https://github.com/webpack/webpack/blob/1f99ad6367f2b8a6ef17cce0e058f7a67fb7db18/lib/ids/IdHelpers.js#L364-L376
=> fix: 🐛assignDeterministicIds alignment

pnpm-lock.yaml
=> chore: remove angular pnpm lock

webpack-test/cases/async-modules/runtime-performance/index.js
=> chore(webpack-test): remove the flaky test which requires on timings

crates/rspack_core/src/compiler/mod.rs, packages/rspack/src/NormalModule.ts
=> chore: fix typos

crates/rspack_core/src/chunk_graph/chunk_graph_chunk.rs
=> chore(chunk_graph): improve chunk_graph perf

packages/rspack/src/Compiler.ts, packages/rspack/src/index.ts
=> fix: remove default export

crates/rspack_core/src/code_generation_results.rs
use eprintln to report error for runtime_requirements
=> chore: use eprintln to report error for runtime_requirements

crates/rspack_ids/src/id_helpers.rs, crates/rspack_testing/src/test_config.rs
=> fix: compare chunks by modules

crates/rspack_plugin_javascript/src/visitors/dependency/harmony_import_dependency_scanner.rs
In webpack, a harmonyImportDependency should be `call` when:
```
foo()
foo.x()
```
but not
```
new foo()
new foo().bar()
```
=> fix(harmony-import-specifier-dep-scanner): add new expr into consideration

packages/create-rspack/template-react-ts/package.json, packages/create-rspack/template-react-ts/rspack.config.js, packages/create-rspack/template-react/package.json, packages/create-rspack/template-react/rspack.config.js, packages/create-rspack/template-vanilla/_gitignore, packages/create-rspack/template-vanilla/index.html, packages/create-rspack/template-vanilla/package.json, packages/create-rspack/template-vanilla/rspack.config.js, packages/create-rspack/template-vanilla/src/index.js, packages/create-rspack/template-vanilla/src/message.js, packages/create-rspack/template-vue/package.json, packages/create-rspack/template-vue/rspack.config.js, packages/create-rspack/template-vue/src/components/HelloWorld.vue, pnpm-lock.yaml, pnpm-workspace.yaml
upgrade template to Rspack 0.4.0
we do need for eco-ci
=> chore: upgrade template to 0.4.0

packages/create-rspack/template-react-ts/package.json, packages/create-rspack/template-react/package.json, packages/create-rspack/template-vanilla/package.json
=> fix: typos

diffcases/arco-pro/tsconfig.json, examples/arco-pro/tsconfig.json, examples/basic-ts/tsconfig.json, examples/react-storybook/tsconfig.json, package.json, packages/create-rspack/template-react-ts/tsconfig.json, packages/rspack-plugin-html/tsconfig.json, packages/rspack-plugin-react-refresh/tsconfig.json, packages/rspack-test-tools/tsconfig.json, packages/rspack/package.json, packages/rspack/tsconfig.json, pnpm-lock.yaml, scripts/tsconfig.json, webpack-test/package.json
This issue is part of https://github.com/web-infra-dev/rspack/issues/4640
* Update zod-validation-error from 1.2.0 to 1.3.1 without change js runtime. see https://diff.intrinsic.com/zod-validation-error/1.2.0/1.3.1
* Update @types/node  to match the new version of typescript
=> fix: zod-validation-error type error

Cargo.lock, crates/rspack_core/Cargo.toml
Fixes #4779 
see https://github.com/web-infra-dev/nodejs_resolver/pull/200/files#diff-24975acf43b4bc39c4c8b57246e4bfbdc0c76428c86ed68f1db0e1b10a6db277R780
=> chore: bump nodejs_resolver

packages/rspack/src/container/ModuleFederationRuntimePlugin.ts
=> fix: mf test on windows

crates/rspack_core/src/tree_shaking/utils.rs, crates/rspack_plugin_javascript/src/visitors/dependency/import_scanner.rs, packages/rspack/tests/configCases/chunk-loading/issue-4800/index.js, packages/rspack/tests/configCases/chunk-loading/issue-4800/logo1.js, packages/rspack/tests/configCases/chunk-loading/issue-4800/logo2.js, packages/rspack/tests/configCases/chunk-loading/issue-4800/webpack.config.js, pnpm-lock.yaml
=> fix: include tpl string into bail out module ident

packages/rspack/tests/configCases/plugins/issue-4757/index.js, packages/rspack/tests/configCases/plugins/issue-4757/webpack.config.js
=> test: test case for #4757

packages/rspack-test-tools/package.json, packages/rspack-test-tools/src/helper/parse-modules.ts, packages/rspack-test-tools/src/index.ts, packages/rspack-test-tools/src/processor/index.ts, packages/rspack-test-tools/src/reporter/diff-stats.ts, packages/rspack-test-tools/src/reporter/index.ts, packages/rspack-test-tools/src/type.ts, pnpm-lock.yaml, scripts/diff.cjs
=> chore: diff stats reporter

Cargo.lock, Cargo.toml, crates/rspack_loader_swc/src/transformer.rs, packages/rspack/tests/configCases/builtin-swc-loader/styled-components/Button2/index.jsx, packages/rspack/tests/configCases/builtin-swc-loader/styled-components/index.jsx
=> fix: bump styled_components and add tests

Cargo.lock, Cargo.toml, packages/rspack/tests/configCases/plugins/issue-4797/index.js, packages/rspack/tests/configCases/plugins/issue-4797/webpack.config.js
=> fix: updated swc to solve the asciionly bug

packages/rspack-test-tools/src/reporter/diff-stats.ts
=> fix: repeat report view link in stats report

packages/playground/cases/hooks/asset-emitted/rspack.config.js, packages/rspack/src/config/defaults.ts, packages/rspack/tests/Defaults.unittest.ts, packages/rspack/tests/Stats.test.ts, packages/rspack/tests/__snapshots__/Stats.test.ts.snap, packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap, webpack-test/configCases/entry/no-chunking/test.config.js, webpack-test/configCases/entry/no-chunking/webpack.config.js
fix https://github.com/web-infra-dev/rspack/issues/4820
webpack logic https://github.com/webpack/webpack/blob/main/lib/config/defaults.js#L1317
=> feat: align chunkIds default value with webpack

.github/workflows/issue-mark-assignee.yml
=> refactor: add comment to claim issue

.github/workflows/diff.yml
1. Use bash to upload diff report to rspack-report-website
2. Remove reports older than one month
3. Fix download binding bugs
=> ci: optimize diff workflow

.github/teams.yml
=> chore: add LingyuCoder to team members

packages/rspack/tests/configCases/plugins/chunk-modules/index.js, packages/rspack/tests/configCases/plugins/chunk-modules/webpack.config.js
=> fix: chunk modules test on windows

.github/workflows/release-nightly.yml
=> fix: eco-ci trigger after nightly release

crates/rspack_plugin_javascript/src/utils/basic_evaluated_expression.rs, crates/rspack_plugin_javascript/src/utils/const.rs, crates/rspack_plugin_javascript/src/utils/mod.rs, crates/rspack_plugin_javascript/src/visitors/dependency/common_js_import_dependency_scanner.rs, crates/rspack_plugin_javascript/src/visitors/dependency/mod.rs, packages/rspack/tests/cases/parsing/issue-4816/index.js
Related to #4424 
support evaluate binary expression
=> feat: eval binary expression

Cargo.lock, crates/rspack_core/Cargo.toml
fixes #4770
Release note: https://github.com/oxc-project/oxc_resolver/releases/tag/0.6.0
- https://github.com/oxc-project/oxc_resolver/pull/8
=> fix(rspack_core): oxc_resolver v0.6.0 - resolve styled-components correctly

Cargo.lock, crates/rspack_core/src/options/output.rs, crates/rspack_plugin_runtime/Cargo.toml, crates/rspack_plugin_runtime/src/runtime_module/get_chunk_filename.rs, crates/rspack_plugin_runtime/src/runtime_module/utils.rs, crates/rspack_plugin_runtime/src/runtime_plugin.rs, packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap, packages/rspack/tests/configCases/split-chunks/custom-filename-chunkname-runtime-module-contenthash/a.js, packages/rspack/tests/configCases/split-chunks/custom-filename-chunkname-runtime-module-contenthash/b.js, packages/rspack/tests/configCases/split-chunks/custom-filename-chunkname-runtime-module-contenthash/test.config.js, packages/rspack/tests/configCases/split-chunks/custom-filename-chunkname-runtime-module-contenthash/webpack.config.js, packages/rspack/tests/configCases/split-chunks/custom-filename-chunkname-runtime-module-fullhash/a.js, packages/rspack/tests/configCases/split-chunks/custom-filename-chunkname-runtime-module-fullhash/b.js, packages/rspack/tests/configCases/split-chunks/custom-filename-chunkname-runtime-module-fullhash/test.config.js, packages/rspack/tests/configCases/split-chunks/custom-filename-chunkname-runtime-module-fullhash/webpack.config.js, packages/rspack/tests/configCases/split-chunks/custom-filename-chunkname-runtime-module/a.js, packages/rspack/tests/configCases/split-chunks/custom-filename-chunkname-runtime-module/b.js, packages/rspack/tests/configCases/split-chunks/custom-filename-chunkname-runtime-module/test.config.js, packages/rspack/tests/configCases/split-chunks/custom-filename-chunkname-runtime-module/webpack.config.js
Optimize get chunk filename runtime module with dynamic+static, just the same as [webpack](https://github.com/webpack/webpack/blob/v5.89.0/lib/runtime/GetChunkFilenameRuntimeModule.js)
before: 
```js
__webpack_require__.u = function(chunkId) {
// return url for filenames based on template
return {
"common-src_common_0_js": "common-common-src_common_0_js-727831.js",
"common-src_common_1_js": "common-common-src_common_1_js-7a51b2.js",
"other-src_other_0_js": "c-other-src_other_0_js.js",
"other-src_other_1_js": "c-other-src_other_1_js.js",
"shared-src_shared_0_js": "shared-shared-src_shared_0_js-86dd.js",
"shared-src_shared_10_js": "shared-shared-src_shared_10_js-29a2.js",
"shared-src_shared_11_js": "shared-shared-src_shared_11_js-b1ef.js",
"shared-src_shared_12_js": …
```
=> feat(runtime): optimize get chunk filename runtime module with dynamic+static 

crates/rspack_core/src/context_module.rs, crates/rspack_core/src/normal_module_factory.rs, crates/rspack_core/src/resolver/factory.rs, crates/rspack_core/src/resolver/mod.rs, crates/rspack_loader_sass/src/lib.rs, crates/rspack_plugin_mf/src/sharing/consume_shared_plugin.rs
Prerequisite for #4945.
Clean up the unnecessary argument in the ﻿resolve.
=> fix: rm dep type for resolve

crates/rspack_core/src/compiler/compilation.rs, crates/rspack_core/src/plugin/api.rs, crates/rspack_core/src/plugin/plugin_driver.rs, packages/rspack/tests/Stats.test.ts, packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap, webpack-test/__snapshots__/StatsTestCases.basictest.js.snap.bak, webpack-test/__snapshots__/StatsTestCases.basictest.js.snap.diff
Align with webpack, assets in build_info should be included in chunk.auxiliary_files
=> feat: add create_module_assets

crates/node_binding/binding.d.ts, crates/rspack_binding_values/src/module.rs, packages/rspack/src/Module.ts
=> fix: module.context is undefined

crates/node_binding/binding.d.ts, crates/rspack_binding_options/src/options/raw_split_chunks/mod.rs, crates/rspack_plugin_split_chunks/src/options/split_chunks_options.rs, crates/rspack_plugin_split_chunks_new/src/plugin/max_size.rs, crates/rspack_plugin_split_chunks_new/src/plugin/mod.rs, packages/rspack/src/config/defaults.ts, packages/rspack/src/config/zod.ts, packages/rspack/tests/Defaults.unittest.ts, packages/rspack/tests/__snapshots__/Defaults.unittest.ts.snap, packages/rspack/tests/configCases/split-chunks/max-size-casing/webpack.config.js
Support `optimization.splitChunks.hidePathInfo` option.
The detail in the webpack documentation: https://webpack.js.org/plugins/split-chunks-plugin/#splitchunkshidepathinfo.
=> feat: support optimization.splitChunks.hidePathInfo option

Cargo.lock, crates/rspack_core/Cargo.toml, webpack-test/TestCases.template.js, webpack-test/cases/resolving/browser-field/errors.js, webpack-test/cases/resolving/browser-field/test.filter.js
closes #4446
oxc_resolver PR: https://github.com/oxc-project/oxc_resolver/pull/17
- Added the same tests to oxc
- Turned on relevant tests in webpack-test
=> chore(webpack-test): enable resolving/browser-field tests

crates/rspack_plugin_runtime/src/runtime_module/utils.rs
=> fix: get js chunk filename

packages/rspack/tests/configCases/split-chunks/custom-filename-chunkname-runtime-module-id/a.js, packages/rspack/tests/configCases/split-chunks/custom-filename-chunkname-runtime-module-id/b.js, packages/rspack/tests/configCases/split-chunks/custom-filename-chunkname-runtime-module-id/test.config.js, packages/rspack/tests/configCases/split-chunks/custom-filename-chunkname-runtime-module-id/webpack.config.js
=> test(runtime): add test case of using [id] in get chunk filename runtime module

packages/create-rspack/template-react-ts/.npmignore, packages/create-rspack/template-react/.npmignore, packages/create-rspack/template-vanilla/.npmignore, packages/create-rspack/template-vue/.npmignore
Fixes https://github.com/web-infra-dev/rspack/issues/4902
Not required
=> fix: add node modules to npmginore in templates

crates/rspack/tests/samples/remove-parent-modules/parent-have-partial-module/exist.js, crates/rspack/tests/samples/remove-parent-modules/parent-have-partial-module/index.js, crates/rspack/tests/samples/remove-parent-modules/parent-have-partial-module/parent-1.js, crates/rspack/tests/samples/remove-parent-modules/parent-have-partial-module/parent-2.js, crates/rspack/tests/samples/remove-parent-modules/parent-have-partial-module/shared.js, crates/rspack/tests/samples/remove-parent-modules/parent-have-partial-module/snapshot/output.snap, crates/rspack/tests/samples/remove-parent-modules/parent-have-partial-module/test.config.json, crates/rspack_core/src/build_chunk_graph/code_splitter.rs, crates/rspack_core/src/build_chunk_graph/remove_parent_modules.rs
Chunk relation should be handled at any time processing chunk group connection
=> fix: handle chunk relation

packages/rspack/src/Module.ts, packages/rspack/tests/__snapshots__/configCase.test.ts.snap, packages/rspack/tests/configCases/plugins/chunk-modules/index.js, packages/rspack/tests/configCases/plugins/chunk-modules/webpack.config.js
=> fix: license-webpack-plugin failed to generate license for some of module

packages/rspack/src/Compilation.ts, packages/rspack/src/config/zod.ts, packages/rspack/src/stats/DefaultStatsFactoryPlugin.ts, packages/rspack/tests/Stats.test.ts, packages/rspack/tests/__snapshots__/Stats.test.ts.snap, packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
=> feat: stats for childCompiler

.github/workflows/bench-main.yaml
Add benchmark test when main branch push
=> chore: run benchmark on main branch

packages/rspack/tests/Stats.test.ts
=> fix: stats childCompiler test

crates/node_binding/binding.d.ts, crates/rspack_binding_options/src/options/raw_optimization.rs, crates/rspack_binding_options/src/options/raw_split_chunks/mod.rs, crates/rspack_binding_options/src/options/raw_split_chunks/raw_split_chunk_chunks.rs, packages/rspack/src/builtin-plugin/SplitChunksPlugin.ts, packages/rspack/src/builtin-plugin/WorkerPlugin.ts, packages/rspack/src/builtin-plugin/base.ts, packages/rspack/src/config/adapter.ts, packages/rspack/src/config/zod.ts, packages/rspack/src/container/ContainerPlugin.ts, packages/rspack/src/container/ContainerReferencePlugin.ts, packages/rspack/src/container/ModuleFederationPlugin.ts, packages/rspack/src/sharing/ProvideSharedPlugin.ts, packages/rspack/tests/configCases/split-chunks/chunks-function/index.js, packages/rspack/tests/configCases/split-chunks/chunks-function/lib1.js, packages/rspack/tests/configCases/split-chunks/chunks-function/lib2.js, packages/rspack/tests/configCases/split-chunks/chunks-function/shared.js, packages/rspack/tests/configCases/split-chunks/chunks-function/webpack.config.js
=> feat: add function type splitChunks chunks

crates/rspack_core/src/chunk.rs, crates/rspack_core/src/compiler/compilation.rs, crates/rspack_core/src/utils/mod.rs, packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
Sort runtime chunk by index to get stable order
=> fix: runtime chunk order

crates/rspack_plugin_javascript/src/visitors/dependency/export_info_api_scanner.rs, webpack-test/cases/cjs-tree-shaking/reexports/test.filter.js, webpack-test/cases/parsing/harmony-deep-exports/test.filter.js, webpack-test/cases/parsing/harmony-duplicate-export/test.filter.js
=> chore: remove #4325 in webpack-test

crates/node_binding/binding.d.ts, crates/rspack_plugin_json/src/lib.rs, crates/rspack_plugin_json/tests/fixtures/simple/json.json, crates/rspack_plugin_json/tests/fixtures/simple/snapshot/output.snap
1. Closed https://github.com/web-infra-dev/rspack/issues/5028
=> fix: 🐛 fix escape json

crates/rspack_core/src/exports_info.rs, crates/rspack_plugin_library/src/export_property_library_plugin.rs, examples/library/rspack.config.js
1. Closed https://github.com/web-infra-dev/rspack/issues/5025
=> fix: umd library integrate with newTreeshaking

crates/rspack_plugin_javascript/src/utils/eval/eval_binary_expr.rs, crates/rspack_plugin_javascript/src/utils/eval/eval_lit_expr.rs, crates/rspack_plugin_javascript/src/utils/eval/mod.rs, packages/rspack/tests/cases/parsing/issue-4816/index.js
=> feat: eval array and regexp in binary expr

webpack-test/configCases/split-chunks/asnyc-entries/test.filter.js
1. Closed https://github.com/web-infra-dev/rspack/issues/4336
=> fix: webpack-test/configCases/split-chunks/async-entries

packages/rspack/src/fileSystem.ts, packages/rspack/src/util/memoize.ts, packages/rspack/tests/Errors.test.ts
closes https://github.com/web-infra-dev/rspack/issues/4999
Old test passes.
=> perf: use async fs

crates/rspack_binding_options/src/options/raw_module/mod.rs, packages/rspack/src/config/adapter.ts, packages/rspack/src/config/zod.ts
=> fix: `ruleSetLogicalConditions.not should not just array

crates/rspack_binding_options/src/options/raw_module/mod.rs, crates/rspack_core/src/lib.rs, crates/rspack_core/src/normal_module_factory.rs, packages/rspack-cli/tests/build/basic/public/main.js, packages/rspack-cli/tests/build/basic/public/main.js.map, packages/rspack/tests/configCases/loader/match-module-type/foo.custom, packages/rspack/tests/configCases/loader/match-module-type/index.js, packages/rspack/tests/configCases/loader/match-module-type/loader-test.js, packages/rspack/tests/configCases/loader/match-module-type/webpack.config.js
Support pseudo webpack extension, eg. .webpack[module_type], often used together with inline match resource
support custom module type
=> feat: support pseudo webpack extension and custom module type

crates/rspack_plugin_javascript/src/utils/const/mod.rs, crates/rspack_plugin_javascript/src/utils/eval/eval_binary_expr.rs, crates/rspack_plugin_javascript/src/utils/eval/mod.rs, packages/rspack/tests/cases/parsing/issue-4816/index.js
=> feat: eval template string in binary expr

packages/rspack/tests/StatsTestCases.test.ts
=> fix: serialize path of stats on windows

Cargo.lock, crates/rspack_plugin_javascript/Cargo.toml, crates/rspack_plugin_javascript/src/utils/const/if_stmt.rs, crates/rspack_plugin_javascript/src/utils/const/logic_expr.rs, crates/rspack_plugin_javascript/src/utils/const/mod.rs, crates/rspack_plugin_javascript/src/visitors/dependency/common_js_import_dependency_scanner.rs, packages/rspack/tests/cases/parsing/issue-4816/index.js
related to #4424
related to #4907
This PR introduces the evaluation of if-else stmt and eliminates dead branche.
=> feat: eval if-else stmt

package.json, packages/rspack-cli/package.json, packages/rspack-dev-server/package.json, packages/rspack-plugin-html/package.json, packages/rspack-plugin-react-refresh/package.json, packages/rspack-test-tools/package.json
Try to fix https://github.com/web-infra-dev/rspack/actions/runs/7243540726/job/19730646297
=> chore: force build JS packages on CI

packages/rspack-cli/package.json, packages/rspack/src/Compiler.ts, packages/rspack/src/config/defaults.ts, packages/rspack/src/config/zod.ts, packages/rspack/src/rspackOptionsApply.ts, packages/rspack/tests/__snapshots__/Defaults.unittest.ts.snap, pnpm-lock.yaml
=> feat: deprecate apply options lazily

crates/rspack_plugin_runtime/src/runtime_module/utils.rs
Fix regexp generatation in boolean matcher
=> fix: boolean matcher regexp

crates/rspack_core/src/code_generation_results.rs, crates/rspack_core/src/options/output.rs, crates/rspack_plugin_asset/src/lib.rs, crates/rspack_plugin_css/src/dependency/url.rs, crates/rspack_plugin_css/src/plugin/impl_plugin_for_css_plugin.rs, packages/rspack/tests/__snapshots__/case.test.ts.snap, packages/rspack/tests/cases/css/rewrite-url-rule-public-path/index.css, packages/rspack/tests/cases/css/rewrite-url-rule-public-path/index.js, packages/rspack/tests/cases/css/rewrite-url-rule-public-path/webpack.config.js
=> fix: asset publicPath in css with rule asset generator

crates/node_binding/binding.d.ts, crates/node_binding/src/hook.rs, crates/node_binding/src/plugins/mod.rs, crates/rspack_binding_values/src/hooks.rs, crates/rspack_core/src/compiler/compilation.rs, crates/rspack_core/src/plugin/api.rs, crates/rspack_core/src/plugin/plugin_driver.rs, packages/rspack/src/Compilation.ts, packages/rspack/src/Compiler.ts, packages/rspack/tests/Compiler.test.ts
=> feat: support `hooks.afterOptimizeModules`

packages/rspack/src/rspackOptionsApply.ts
=> fix: apply entry lazily warning message

crates/rspack_plugin_runtime/src/runtime_module/get_chunk_filename.rs, crates/rspack_plugin_runtime/src/runtime_plugin.rs
CssExtract plugin will reuse this runtime module calculate chunk file name
=> feat: support custom filename for GetChunkFilenameRuntimeModule

crates/rspack_plugin_mf/src/container/container_reference_plugin.rs, crates/rspack_plugin_mf/src/container/remote_module.rs, crates/rspack_plugin_mf/src/container/remote_runtime_module.rs, crates/rspack_plugin_mf/src/container/remotesLoading.js, crates/rspack_plugin_mf/src/sharing/initializeSharing.js, crates/rspack_plugin_mf/src/sharing/share_runtime_module.rs, packages/rspack/package.json, packages/rspack/src/container/ModuleFederationPlugin.ts, packages/rspack/src/container/default.runtime.js, pnpm-lock.yaml
=> fix(mf1.5): remoteInfos when moduleIds is not named

.prettierignore, packages/rspack/src/Compiler.ts, packages/rspack/tests/diagnostics.test.ts, packages/rspack/tests/diagnostics/parse-failed/index.js, packages/rspack/tests/diagnostics/parse-failed/stats.err, pnpm-lock.yaml
This PR introduces ﻿`diagnostics.test.ts`, the purpose of which is to ensure that the error output is readable.
=> feat: add diag test

packages/rspack-dev-server/package.json, pnpm-lock.yaml
It seems we don't use webpack in rspack-dev-server
No Need
=> fix(rspack-dev-server): remove webpack dep

crates/rspack_plugin_javascript/src/visitors/dependency/import_scanner.rs, crates/rspack_plugin_javascript/src/visitors/dependency/mod.rs
Show warnings when type error in magic comments.
=> feat: warning of magic comment

Cargo.toml, crates/rspack_core/src/exports_info.rs, crates/rspack_core/src/module_graph/mod.rs
1. Closed https://github.com/web-infra-dev/rspack/issues/5123
=> perf: exports info hash

crates/rspack_plugin_javascript/src/plugin/impl_plugin_for_js_plugin.rs, webpack-test/configCases/container/2-transitive-overriding/index.js, webpack-test/configCases/container/2-transitive-overriding/test.filter.js, webpack-test/configCases/container/3-container-full/test.filter.js
=> fix(mf): should not have extra empty chunk

packages/rspack/src/config/zod.ts, packages/rspack/tests/ConfigCase.template.ts, packages/rspack/tests/configCases/output/issue-4504/errors.js, packages/rspack/tests/configCases/output/issue-4504/index.js, packages/rspack/tests/configCases/output/issue-4504/webpack.config.js
=> fix: user freindly error msg for output.hashFunction

packages/rspack/src/config/defaults.ts
Align to https://github.com/webpack/webpack/pull/17775
=> perf: delete useless calls

crates/node_binding/binding.d.ts, crates/rspack_binding_options/src/options/raw_builtins/raw_swc_js_minimizer.rs, crates/rspack_plugin_swc_js_minimizer/src/lib.rs, crates/rspack_plugin_swc_js_minimizer/src/minify.rs, packages/rspack/src/builtin-plugin/SwcJsMinimizerPlugin.ts, packages/rspack/tests/configCases/plugins/issue-5068-1/index.js, packages/rspack/tests/configCases/plugins/issue-5068-1/webpack.config.js, packages/rspack/tests/configCases/plugins/issue-5068-2/index.js, packages/rspack/tests/configCases/plugins/issue-5068-2/webpack.config.js, pnpm-lock.yaml
=> feat: support custom banner

examples/module-federation-v1.5/app/package.json, examples/module-federation-v1.5/app/rspack.config.js, examples/module-federation-v1.5/lib1/package.json, examples/module-federation-v1.5/lib1/rspack.config.js, examples/module-federation-v1.5/lib2/package.json, examples/module-federation-v1.5/lib2/rspack.config.js, examples/module-federation-v1.5/package.json, examples/module-federation-v1/app/package.json, examples/module-federation-v1/app/rspack.config.js, examples/module-federation-v1/lib1/package.json, examples/module-federation-v1/lib1/rspack.config.js, examples/module-federation-v1/lib2/package.json, examples/module-federation-v1/lib2/rspack.config.js, examples/module-federation-v1/package.json, pnpm-lock.yaml
=> chore: add hmr and react refresh for module federation example

crates/rspack_plugin_javascript/src/visitors/dependency/common_js_import_dependency_scanner.rs, crates/rspack_plugin_javascript/src/visitors/dependency/util.rs, webpack-test/cases/parsing/issue-7728/test.filter.js
close #4440 and close #5160 
- Reuse `webpack-test/cases/parsing/issue-7728`
=> feat: support module.require

crates/rspack_core/src/build_chunk_graph/code_splitter.rs, crates/rspack_core/src/dependency/runtime_template.rs, packages/rspack/tests/configCases/errors/dynamic-import-non-exist-module/index.js, packages/rspack/tests/configCases/errors/dynamic-import-non-exist-module/webpack.config.js
=> fix: missing module in block

packages/rspack/package.json, packages/rspack/src/container/ModuleFederationPlugin.ts, packages/rspack/src/container/default.runtime.js, packages/rspack/tests/configCases/container/2-container-full/index.js, pnpm-lock.yaml, webpack-test/scripts/test-metric-util.js
=> fix(mf1.5): container name in runtime

crates/rspack_plugin_javascript/src/utils/eval/eval_binary_expr.rs, packages/rspack/tests/cases/parsing/evaluate-logical/index.js
Fix #5038
- Add `packages/rspack/tests/cases/parsing/evaluate-logical`
=> feat: support logical evaluation

crates/rspack_plugin_javascript/src/utils/const/logic_expr.rs, crates/rspack_plugin_javascript/src/utils/eval/eval_lit_expr.rs, crates/rspack_plugin_javascript/src/utils/eval/mod.rs, packages/rspack/tests/cases/parsing/issue-4816/index.js
=> feat: support eval null

crates/rspack_plugin_javascript/src/utils/const/logic_expr.rs, crates/rspack_plugin_javascript/src/utils/eval/eval_lit_expr.rs, crates/rspack_plugin_javascript/src/utils/eval/mod.rs, packages/rspack/tests/cases/parsing/issue-4816/index.js
This is an attempt to determine if the issue with the e2e test is connected to #5191.
=> Revert "feat: support eval null (#5191)"

crates/rspack_plugin_javascript/src/utils/const/logic_expr.rs, packages/rspack/tests/cases/parsing/issue-4816/index.js
I am interested in knowing if there would be any issues with e2e testing.
=> fix: replace null if has not side effect

packages/rspack/src/config/defaults.ts, packages/rspack/tests/__snapshots__/Defaults.unittest.ts.snap, packages/rspack/tests/configCases/container/2-container-full/webpack.config.js, packages/rspack/tests/configCases/container/module-federation-with-shareScope/webpack.config.js, webpack-test/ConfigTestCases.template.js
=> refactor: enable disableApplyEntryLazily by default

crates/rspack/tests/tree-shaking/webpack-inner-graph-switch/snapshot/new_treeshaking.snap, crates/rspack/tests/tree-shaking/webpack-inner-graph-switch/snapshot/output.snap, crates/rspack_core/src/compiler/queue.rs, crates/rspack_core/src/dependency/dependency_type.rs, crates/rspack_core/src/module.rs, crates/rspack_core/src/self_module_factory.rs, crates/rspack_core/src/utils/visitor.rs, crates/rspack_plugin_javascript/src/dependency/commonjs/common_js_full_require_dependency.rs, crates/rspack_plugin_javascript/src/dependency/commonjs/mod.rs, crates/rspack_plugin_javascript/src/visitors/dependency/common_js_export_scanner.rs, crates/rspack_plugin_javascript/src/visitors/dependency/common_js_import_dependency_scanner.rs, crates/rspack_plugin_javascript/src/visitors/dependency/util.rs, packages/rspack/tests/Stats.test.ts, packages/rspack/tests/__snapshots__/Stats.test.ts.snap, packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap, packages/rspack/tests/cases/cjs-tree-shaking/full-require/exports.js, packages/rspack/tests/cases/cjs-tree-shaking/full-require/index.js, packages/rspack/tests/cases/cjs-tree-shaking/full-require/reexport.js
Add CommonJsFullRequireDependency
- Add `packages/rspack/tests/cases/cjs-tree-shaking/full-require`
=> feat: add common_js_full_require_dependency

crates/rspack_core/src/compiler/compilation.rs
change for https://github.com/web-infra-dev/rspack-dev-guide/pull/30
=> chore: filter by arguments for `chunk_asset`

.github/workflows/release-nightly.yml, scripts/alert/discord.js, scripts/alert/lark.js
=> chore: nightly release failed alert to all platform

crates/rspack_core/src/build_chunk_graph/remove_parent_modules.rs, crates/rspack_core/src/compiler/compilation.rs, crates/rspack_plugin_html/src/plugin.rs, crates/rspack_plugin_swc_css_minimizer/src/lib.rs
=> refactor: use glob import for prelude

crates/rspack_plugin_javascript/src/dependency/commonjs/common_js_full_require_dependency.rs
=> fix: use exports_type in module instead of mgm

crates/node_binding/binding.d.ts, crates/rspack_binding_options/src/options/mod.rs, crates/rspack_binding_options/src/options/raw_experiments.rs, packages/playground/cases/hooks/asset-emitted/rspack.config.js, packages/rspack/src/config/adapter.ts, packages/rspack/src/config/defaults.ts, packages/rspack/src/config/normalization.ts, packages/rspack/src/config/zod.ts, packages/rspack/tests/Defaults.unittest.ts, packages/rspack/tests/HotTestCases.template.ts, packages/rspack/tests/HotTestCasesNode.test.ts, packages/rspack/tests/HotTestCasesNodeWithIncRebuild.test.ts, packages/rspack/tests/HotTestCasesWeb.test.ts, packages/rspack/tests/HotTestCasesWebWithIncRebuild.test.ts, packages/rspack/tests/HotTestCasesWebWorker.test.ts, packages/rspack/tests/HotTestCasesWebWorkerWithIncRebuild.test.ts, packages/rspack/tests/Stats.test.ts, packages/rspack/tests/__snapshots__/Defaults.unittest.ts.snap
=> feat: remove experiments.incrementalRebuild option

examples/module-federation-interop/README.md, examples/module-federation-interop/package.json, examples/module-federation-interop/rspack-mf-v1.5/package.json, examples/module-federation-interop/rspack-mf-v1.5/rspack.config.js, examples/module-federation-interop/rspack-mf-v1.5/src/Component.js, examples/module-federation-interop/rspack-mf-v1.5/src/bootstrap.js, examples/module-federation-interop/rspack-mf-v1.5/src/index.js, examples/module-federation-interop/rspack-mf-v1.5/src/runtimePlugins/logger.js, examples/module-federation-interop/rspack-mf-v1/package.json, examples/module-federation-interop/rspack-mf-v1/rspack.config.js, examples/module-federation-interop/rspack-mf-v1/src/Component.js, examples/module-federation-interop/rspack-mf-v1/src/bootstrap.js, examples/module-federation-interop/rspack-mf-v1/src/index.js, examples/module-federation-interop/webpack-mf/package.json, examples/module-federation-interop/webpack-mf/src/Component.js, examples/module-federation-interop/webpack-mf/src/bootstrap.js, examples/module-federation-interop/webpack-mf/src/index.js, examples/module-federation-interop/webpack-mf/webpack.config.js, examples/module-federation-v1/lib1/rspack.config.js, pnpm-lock.yaml
=> chore: add module federation interop example

crates/node_binding/binding.d.ts, crates/rspack_binding_values/src/stats.rs, crates/rspack_core/src/stats.rs, packages/rspack/src/stats/DefaultStatsFactoryPlugin.ts, packages/rspack/tests/__snapshots__/Stats.test.ts.snap, packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
=> feat(stats): support orphan field

crates/rspack_plugin_javascript/src/utils/eval/eval_binary_expr.rs, crates/rspack_plugin_javascript/src/utils/eval/mod.rs, packages/rspack/tests/cases/parsing/issue-4816/index.js
=> feat: more case for eval strict equality

packages/rspack-test-tools/package.json, packages/rspack-test-tools/src/plugin/rspack-diff-config-plugin.ts, packages/rspack-test-tools/src/plugin/webpack-diff-config-plugin.ts, packages/rspack-test-tools/src/plugin/webpack-module-placeholder-plugin.ts, packages/rspack-test-tools/src/processor/diff.ts, pnpm-lock.yaml
- Calculate webpack path and rspack path by node module object
=> chore: remove builder path of diff plugins

packages/playground/fixtures/pathInfo.ts, packages/playground/fixtures/rspack.ts, packages/playground/playwright.config.ts
This PR remove useless worker playwright fixture, and it will fix the bug caused by stop previous rspack.devServer.
=> ci: fix flaky e2e tests

crates/rspack_plugin_javascript/src/visitors/dependency/common_js_export_scanner.rs, packages/rspack/tests/Stats.test.ts, packages/rspack/tests/__snapshots__/Stats.test.ts.snap, packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
Fix module.exports = xxx should not be self reference
=> fix: scan self module

.github/workflows/release-nightly.yml
=> chore: nightly release failed

crates/node_binding/binding.d.ts, crates/node_binding/src/hook.rs, crates/node_binding/src/plugins/mod.rs, crates/rspack_binding_values/src/hooks.rs, packages/rspack/src/Compiler.ts
We forgot some hooks when check disabling
=> fix: some js hooks are always enabled

.github/workflows/reusable-build.yml
=> ci: only linux test all nodejs version

crates/rspack_plugin_runtime/src/runtime_module/get_chunk_filename.rs, crates/rspack_plugin_runtime/src/runtime_plugin.rs, packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
Align GetChunkFilenameRuntimeModule name
=> fix(runtime): align GetChunkFilenameRuntimeModule name

packages/rspack/src/container/default.runtime.js
=> feat: add remoteInitOptions as initContainer params

crates/rspack_core/src/resolver/resolver_impl.rs, crates/rspack_testing/src/test_config.rs, examples/tailwind/l.js, packages/create-rspack/index.js, packages/create-rspack/template-react-ts/rspack.config.js, packages/create-rspack/template-react/rspack.config.js, packages/create-rspack/template-vue/rspack.config.js, packages/rspack-dev-server/package.json, pnpm-lock.yaml
currently template use fixed outdated version which likely breaking in new minor version, we should use latest publish version in template and test against it
integrated it in eco-ci
=> chore: fix template version

Cargo.lock, Cargo.toml, crates/rspack_core/Cargo.toml, crates/rspack_core/src/resolver/resolver_impl.rs, packages/rspack/tests/StatsTestCases.test.ts, packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
closes https://github.com/web-infra-dev/rspack/issues/5151
=> chore: bump oxc_resolver

packages/rspack/package.json, pnpm-lock.yaml
=> chore: fixed mf 1.5 runtime version

packages/rspack-test-tools/src/case/diff.ts
=> chore(diff): fix diff detail output

packages/rspack-cli/src/utils/options.ts
=> fix: fix cli command alias bug

crates/rspack_core/src/diagnostics.rs
=> perf: lazily init help message

Cargo.lock, crates/rspack_core/src/diagnostics.rs, crates/rspack_core/src/loader/rspack_loader.rs, crates/rspack_core/src/normal_module.rs, crates/rspack_core/src/resolver/mod.rs, crates/rspack_error/Cargo.toml, crates/rspack_error/src/diagnostic.rs, crates/rspack_error/src/error.rs, crates/rspack_error/src/ext.rs, crates/rspack_error/src/lib.rs, crates/rspack_error/src/miette_helpers.rs, crates/rspack_loader_runner/src/plugin.rs, crates/rspack_loader_runner/src/runner.rs, crates/rspack_napi_shared/src/errors.rs, packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap, packages/rspack/tests/configCases/loader/loader-error-async/errors.js, packages/rspack/tests/configCases/loader/loader-syntax-error/errors.js, packages/rspack/tests/diagnostics/factorize/asset-module-build-failed/stats.err, packages/rspack/tests/diagnostics/factorize/loader-throw-error/stats.err
See snapshot changes for details.
=> feat: support module build error

packages/rspack/tests/diagnostics.test.ts, packages/rspack/tests/diagnostics/factorize/asset-module-build-failed/stats.err, packages/rspack/tests/diagnostics/factorize/loader-throw-error/stats.err
=> test: replace error stack in test

.github/workflows/release-nightly.yml
=> chore: nightly release alert when failed

crates/rspack_core/src/resolver/mod.rs
=> fix: should not assume module directories always exist

crates/swc_plugin_import/src/lib.rs, packages/rspack/tests/configCases/builtin-swc-loader/issue-5329/errors.js, packages/rspack/tests/configCases/builtin-swc-loader/issue-5329/index.js, packages/rspack/tests/configCases/builtin-swc-loader/issue-5329/lib-entry.js, packages/rspack/tests/configCases/builtin-swc-loader/issue-5329/lib.js, packages/rspack/tests/configCases/builtin-swc-loader/issue-5329/webpack.config.js, packages/rspack/tests/configCases/builtin-swc-loader/plugin-import/src/custom-name-tpl-nopanic/fooBar/index.js
closes https://github.com/web-infra-dev/rspack/issues/5329
added
=> fix: unregistered case handler should not panic

.prettierignore, crates/rspack_plugin_javascript/src/ast/parse.rs, crates/rspack_plugin_javascript/src/parser_and_generator/mod.rs, crates/rspack_plugin_javascript/src/visitors/dependency/common_js_import_dependency_scanner.rs, crates/rspack_plugin_javascript/src/visitors/dependency/harmony_import_dependency_scanner.rs, crates/rspack_plugin_javascript/src/visitors/dependency/mod.rs, crates/rspack_plugin_javascript/src/visitors/dependency/util.rs, packages/rspack/tests/cases/parsing/issue-5120-binding/errors.js, packages/rspack/tests/cases/parsing/issue-5120-binding/fail.js, packages/rspack/tests/cases/parsing/issue-5120-binding/index.js, packages/rspack/tests/cases/parsing/issue-5120-binding/webpack.config.js, packages/rspack/tests/cases/parsing/issue-5120-strict-block/errors.js, packages/rspack/tests/cases/parsing/issue-5120-strict-block/fail.js, packages/rspack/tests/cases/parsing/issue-5120-strict-block/index.js, packages/rspack/tests/cases/parsing/issue-5120-strict-block/webpack.config.js, packages/rspack/tests/cases/parsing/issue-5120-strict/errors.js, packages/rspack/tests/cases/parsing/issue-5120-strict/fail.js, packages/rspack/tests/cases/parsing/issue-5120-strict/index.js, packages/rspack/tests/cases/parsing/issue-5120-strict/webpack.config.js, packages/rspack/tests/cases/parsing/issue-5120-var/index.js, packages/rspack/tests/diagnostics/module-parse-failed/lexically_name_error/index.js, packages/rspack/tests/diagnostics/module-parse-failed/lexically_name_error/stats.err, packages/rspack/tests/diagnostics/module-parse-failed/reserved_name_error/index.js, packages/rspack/tests/diagnostics/module-parse-failed/reserved_name_error/stats.err
Fix #5120 
- Added `packages/rspack/tests/cases/parsing/issue-5120-xxxx`
=> fix(parser): reserved binding name in strict mode

crates/rspack_plugin_javascript/src/visitors/dependency/api_scanner.rs, crates/rspack_plugin_javascript/src/visitors/dependency/import_scanner.rs, crates/rspack_plugin_javascript/src/visitors/dependency/mod.rs, crates/rspack_plugin_javascript/src/visitors/dependency/util.rs, crates/rspack_plugin_javascript/src/webpack_comment.rs, packages/rspack/tests/diagnostics/module-parse-failed/magic_comment_warning/a.js, packages/rspack/tests/diagnostics/module-parse-failed/magic_comment_warning/index.js, packages/rspack/tests/diagnostics/module-parse-failed/magic_comment_warning/stats.err, packages/rspack/tests/diagnostics/module-parse-failed/non_support_warning/index.js, packages/rspack/tests/diagnostics/module-parse-failed/non_support_warning/stats.err
=> refactor: traceable non supported warnings

packages/rspack/tests/Defaults.unittest.ts, packages/rspack/tests/__snapshots__/Defaults.unittest.ts.snap
=> fix: stable version snapshot

crates/rspack_plugin_javascript/src/visitors/dependency/harmony_detection_scanner.rs, crates/rspack_plugin_javascript/src/visitors/dependency/import_meta_scanner.rs, crates/rspack_plugin_javascript/src/visitors/dependency/mod.rs, packages/rspack/tests/diagnostics/module-parse-failed/import_meta_warning/index.js, packages/rspack/tests/diagnostics/module-parse-failed/import_meta_warning/stats.err, packages/rspack/tests/diagnostics/module-parse-failed/tla_disable_error/index.js, packages/rspack/tests/diagnostics/module-parse-failed/tla_disable_error/stats.err, packages/rspack/tests/diagnostics/module-parse-failed/tla_disable_error/webpack.config.js, packages/rspack/tests/diagnostics/module-parse-failed/tla_esm_error/index.js, packages/rspack/tests/diagnostics/module-parse-failed/tla_esm_error/stats.err
=> refactor: traceable harmony scanner errors

packages/rspack-dev-server/package.json, pnpm-lock.yaml
relates #5324
It seems to be added by accident from git blame.
=> chore: remove unused puppeteer

packages/rspack-test-tools/tests/runtimeDiffCases/module-esm-export/rspack.config.js, packages/rspack-test-tools/tests/runtimeDiffCases/module-esm-export/src/esm/export-as.js, packages/rspack-test-tools/tests/runtimeDiffCases/module-esm-export/src/esm/export-class.js, packages/rspack-test-tools/tests/runtimeDiffCases/module-esm-export/src/esm/export-default-class-nameless.js, packages/rspack-test-tools/tests/runtimeDiffCases/module-esm-export/src/esm/export-default-class.js, packages/rspack-test-tools/tests/runtimeDiffCases/module-esm-export/src/esm/export-default-expression.js, packages/rspack-test-tools/tests/runtimeDiffCases/module-esm-export/src/esm/export-default-function-async.js, packages/rspack-test-tools/tests/runtimeDiffCases/module-esm-export/src/esm/export-default-function-generator.js, packages/rspack-test-tools/tests/runtimeDiffCases/module-esm-export/src/esm/export-default-function-nameless.js, packages/rspack-test-tools/tests/runtimeDiffCases/module-esm-export/src/esm/export-default-function-params.js, packages/rspack-test-tools/tests/runtimeDiffCases/module-esm-export/src/esm/export-default-function.js, packages/rspack-test-tools/tests/runtimeDiffCases/module-esm-export/src/esm/export-default.js, packages/rspack-test-tools/tests/runtimeDiffCases/module-esm-export/src/esm/export-function.js, packages/rspack-test-tools/tests/runtimeDiffCases/module-esm-export/src/esm/export-star.js, packages/rspack-test-tools/tests/runtimeDiffCases/module-esm-export/src/esm/export.js, packages/rspack-test-tools/tests/runtimeDiffCases/module-esm-export/src/esm/variables.js, packages/rspack-test-tools/tests/runtimeDiffCases/module-esm-export/src/index.js, packages/rspack-test-tools/tests/runtimeDiffCases/module-esm-export/src/no-strict.js, packages/rspack-test-tools/tests/runtimeDiffCases/module-esm-export/test.config.js, packages/rspack-test-tools/tests/runtimeDiffCases/module-esm-export/webpack.config.js
=> chore(diff): add esm export case

packages/rspack-test-tools/tests/runtimeDiffCases/module-esm-import/rspack.config.js, packages/rspack-test-tools/tests/runtimeDiffCases/module-esm-import/src/esm/default-multiple-rename.js, packages/rspack-test-tools/tests/runtimeDiffCases/module-esm-import/src/esm/default-rename.js, packages/rspack-test-tools/tests/runtimeDiffCases/module-esm-import/src/esm/default.js, packages/rspack-test-tools/tests/runtimeDiffCases/module-esm-import/src/esm/export-default-multiple.js, packages/rspack-test-tools/tests/runtimeDiffCases/module-esm-import/src/esm/export-multiple-rename.js, packages/rspack-test-tools/tests/runtimeDiffCases/module-esm-import/src/esm/export-multiple.js, packages/rspack-test-tools/tests/runtimeDiffCases/module-esm-import/src/esm/export-rename.js, packages/rspack-test-tools/tests/runtimeDiffCases/module-esm-import/src/esm/export-single.js, packages/rspack-test-tools/tests/runtimeDiffCases/module-esm-import/src/esm/star.js, packages/rspack-test-tools/tests/runtimeDiffCases/module-esm-import/src/esm/unuse.js, packages/rspack-test-tools/tests/runtimeDiffCases/module-esm-import/src/index.js, packages/rspack-test-tools/tests/runtimeDiffCases/module-esm-import/src/no-strict.js, packages/rspack-test-tools/tests/runtimeDiffCases/module-esm-import/test.config.js, packages/rspack-test-tools/tests/runtimeDiffCases/module-esm-import/webpack.config.js
=> chore(diff): add esm import case 

packages/rspack/package.json, pnpm-lock.yaml
=> chore: remove unused @types/webpack-dev-server from rspack devDependencies

packages/rspack/src/Compiler.ts
=> fix: return type of `Compiler.shouldEmit` should be boolean

crates/rspack_plugin_devtool/src/lib.rs, packages/rspack/tests/configCases/source-map/relative-source-maps-by-loader/index.js, packages/rspack/tests/configCases/source-map/relative-source-maps-by-loader/loader-no-source-root.js, packages/rspack/tests/configCases/source-map/relative-source-maps-by-loader/loader-pre-relative.js, packages/rspack/tests/configCases/source-map/relative-source-maps-by-loader/loader-source-root-2-slash.js, packages/rspack/tests/configCases/source-map/relative-source-maps-by-loader/loader-source-root-slash.js, packages/rspack/tests/configCases/source-map/relative-source-maps-by-loader/loader-source-root-source-slash.js, packages/rspack/tests/configCases/source-map/relative-source-maps-by-loader/loader-source-root.js, packages/rspack/tests/configCases/source-map/relative-source-maps-by-loader/webpack.config.js
=> feat: handle webpack internal module source map

packages/rspack-test-tools/tests/runtimeDiffCases/module-esm-cjs-mix/src/index.js, packages/rspack-test-tools/tests/runtimeDiffCases/module-esm-cjs-mix/src/mix/bbb.js, packages/rspack-test-tools/tests/runtimeDiffCases/module-esm-cjs-mix/src/mix/cjs.js, packages/rspack-test-tools/tests/runtimeDiffCases/module-esm-cjs-mix/src/mix/cjs1.js, packages/rspack-test-tools/tests/runtimeDiffCases/module-esm-cjs-mix/src/mix/cjs2.js, packages/rspack-test-tools/tests/runtimeDiffCases/module-esm-cjs-mix/src/mix/cjs3.js, packages/rspack-test-tools/tests/runtimeDiffCases/module-esm-cjs-mix/src/mix/cjs4.js, packages/rspack-test-tools/tests/runtimeDiffCases/module-esm-cjs-mix/src/mix/cjs5.js, packages/rspack-test-tools/tests/runtimeDiffCases/module-esm-cjs-mix/src/mix/esm1.js, packages/rspack-test-tools/tests/runtimeDiffCases/module-esm-cjs-mix/src/mix/esm2.js, packages/rspack-test-tools/tests/runtimeDiffCases/module-esm-cjs-mix/src/mix/esm3.js, packages/rspack-test-tools/tests/runtimeDiffCases/module-esm-cjs-mix/src/mix/esm4.js, packages/rspack-test-tools/tests/runtimeDiffCases/module-esm-cjs-mix/src/mix/esm5.js, packages/rspack-test-tools/tests/runtimeDiffCases/module-esm-cjs-mix/src/mix/esm6.js, packages/rspack-test-tools/tests/runtimeDiffCases/module-esm-cjs-mix/test.config.js
Add diff test case for harmony+commonjs mixed modules
- Add `packages/rspack-test-tools/tests/runtimeDiffCases/module-esm-cjs-mix`
=> test(diff): add diff test case for harmony+commonjs mixed modules

crates/rspack_plugin_mf/src/sharing/consume_shared_plugin.rs, packages/rspack/tests/configCases/container/fallback-context/src/index.js, packages/rspack/tests/configCases/container/fallback-context/src/shared.js, packages/rspack/tests/configCases/container/fallback-context/webpack.config.js
=> fix(mf): different fallback module context

crates/rspack/tests/tree-shaking/cjs-export-computed-property/snapshot/snap.diff, crates/rspack/tests/tree-shaking/cyclic-reference-export-all/snapshot/snap.diff, crates/rspack/tests/tree-shaking/issue-4637/snapshot/snap.diff, crates/rspack/tests/tree-shaking/prune-bailout-module/snapshot/snap.diff, crates/rspack/tests/tree-shaking/pure_comments_magic_comments/snapshot/snap.diff, crates/rspack/tests/tree-shaking/reexport_entry_elimination/snapshot/snap.diff, crates/rspack/tests/tree-shaking/side-effects-export-default-expr/snapshot/snap.diff, crates/rspack/tests/tree-shaking/webpack-inner-graph-export-default-named/snapshot/snap.diff, crates/rspack/tests/tree-shaking/webpack-innergraph-no-side-effects/snapshot/snap.diff, crates/rspack/tests/tree-shaking/webpack-reexport-namespace-and-default/snapshot/snap.diff, crates/rspack/tests/tree-shaking/webpack-side-effects-all-used/snapshot/snap.diff, crates/rspack/tests/tree-shaking/webpack-side-effects-simple-unused/snapshot/snap.diff
=> chore: snap.diff changed

Cargo.lock, Cargo.toml, crates/rspack_core/Cargo.toml
closes https://github.com/web-infra-dev/modern.js/issues/5227
See https://github.com/oxc-project/oxc_resolver/pull/54 for details
=> fix(rspack_core): fix resolver returning broken missing dependencies

packages/rspack/src/Compilation.ts
=> fix: remove unnecessary return type of runtime module hook

packages/rspack-dev-server/package.json, pnpm-lock.yaml
=> fix: remove unnecessary react-refreshfrom dev-server's dependencies

.github/renovate.json
=> ci: only update github-actions and cargo dependencies

packages/rspack/src/Stats.ts, packages/rspack/src/stats/DefaultStatsFactoryPlugin.ts, packages/rspack/src/stats/StatsFactory.ts, packages/rspack/tests/Stats.test.ts
=> fix: use correct stats for child compilation

crates/rspack_binding_options/src/options/raw_devtool.rs, crates/rspack_plugin_devtool/src/lib.rs
=> fix: cannot block the current thread from within a runtime

crates/rspack_plugin_devtool/src/lib.rs
Maximize performance by parallelizing tasks wherever possible.
=> refactor: streamline filename creation and context preparation for assets in SourceMapDevToolPlugin

.github/renovate.json, Cargo.toml
`styled_components` also depends on `swc` :-)
=> chore: pin `styled_components` along with the same swc versions

Cargo.lock, crates/swc_plugin_import/Cargo.toml, crates/swc_plugin_import/src/lib.rs, packages/rspack/tests/configCases/builtin-swc-loader/issue-5329/errors.js, packages/rspack/tests/configCases/builtin-swc-loader/issue-5329/index.js
Only a simplified lifetime on `Helpers`
https://github.com/sunng87/handlebars-rust/blob/master/CHANGELOG.md
=> chore: bump handlebars to v5.1.1

.github/workflows/ci.yml, packages/create-rspack/template-react-ts/src/App.tsx, packages/create-rspack/template-react/src/App.jsx
js lint was never trigger when we upgraded oxlint.
=> fix: fix oxlint warning and trigger js when pnpm changes

crates/rspack_plugin_split_chunks_new/src/module_group.rs
=> fix: make split consistant result

packages/rspack/src/Compilation.ts
=> fix: asset source can not be undefined

packages/rspack-plugin-html/src/index.ts
=> typo: Update index.ts

crates/rspack_plugin_javascript/src/visitors/dependency/parser/mod.rs, packages/rspack/tests/cases/parsing/issue-5197/a.mjs, packages/rspack/tests/cases/parsing/issue-5197/index.js
Fixes https://github.com/web-infra-dev/rspack/issues/5197
Align to webpack https://github.com/webpack/webpack/blob/main/lib/dependencies/CommonJsPlugin.js#L235
=> fix: not parse require in esm

packages/rspack/tests/configCases/split-chunks/issue-5485/src/index.js, packages/rspack/tests/configCases/split-chunks/issue-5485/src/lib/a.js, packages/rspack/tests/configCases/split-chunks/issue-5485/test.config.js, packages/rspack/tests/configCases/split-chunks/issue-5485/webpack.config.js
=> chore: add tests for consistent splitChunks output

Cargo.lock, Cargo.toml, crates/rspack_identifier/Cargo.toml, crates/rspack_plugin_html/tests/fixtures/filename/snapshot/output.snap, packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
Forking ustr and let's see how it goes ...
relates #5481
=> feat(rspack_core): use consistent fxhash for ustr instead of inconsistent ahash

.github/workflows/ci.yml
=> chore: remove ci pull_request branches-ignore

crates/rspack_plugin_javascript/src/dependency/context/common_js_require_context_dependency.rs, crates/rspack_plugin_javascript/src/dependency/context/import_context_dependency.rs, packages/rspack/tests/cases/context/rspack-issue-5521/errors.js, packages/rspack/tests/cases/context/rspack-issue-5521/index.js
closes https://github.com/web-infra-dev/rspack/issues/5521
Included
=> fix: module not exist in context modules

.github/PULL_REQUEST_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE/minor-release-mr.md
=> chore: remove "Test Plan" from pull request template

.github/ISSUE_TEMPLATE/1-bug-report.en-US.yml, .github/ISSUE_TEMPLATE/2-feature-request.en-US.yml
add [Bug] and [Feature] prefix to issue title
=> chore: update issue template with title prefix

crates/rspack_core/src/context_module.rs, packages/rspack/tests/cases/context/rspack-issue-5535/index.js, packages/rspack/tests/cases/context/rspack-issue-5535/test-module/index.js, packages/rspack/tests/cases/context/rspack-issue-5535/test-module/modules/test.module.js
=> fix: wrongly generated alternative requests in context modules

crates/rspack_core/src/compiler/compilation.rs, crates/rspack_plugin_javascript/src/parser_and_generator/mod.rs, crates/rspack_plugin_javascript/src/visitors/dependency/mod.rs
=> fix: 🐛 call finish module in rebuild_module instead of update_module_graph

Cargo.lock, Cargo.toml, crates/rspack_plugin_devtool/src/lib.rs, packages/rspack/tests/configCases/plugins/source-map-dev-tool-plugin-source-root/index.js, packages/rspack/tests/configCases/plugins/source-map-dev-tool-plugin-source-root/webpack.config.js
Fix: https://github.com/web-infra-dev/rspack/actions/runs/7737938939/job/21098461031
Related: https://github.com/web-infra-dev/rspack/pull/5522
=> fix: source root error in windows

crates/rspack_plugin_javascript/src/plugin/side_effects_flag_plugin.rs, webpack-test/cases/cjs-tree-shaking/mutate/test.filter.js, webpack-test/cases/inner-graph/extend-class/a.js, webpack-test/cases/inner-graph/extend-class/b.js, webpack-test/cases/inner-graph/extend-class/c.js, webpack-test/cases/inner-graph/extend-class/dep1.js, webpack-test/cases/inner-graph/extend-class/dep2.js, webpack-test/cases/inner-graph/extend-class/dep3.js, webpack-test/cases/inner-graph/extend-class/index.js, webpack-test/cases/inner-graph/extend-class/module3.js, webpack-test/cases/inner-graph/extend-class/module4.js, webpack-test/cases/inner-graph/extend-class/module5.js, webpack-test/cases/inner-graph/extend-class/module6.js, webpack-test/cases/inner-graph/extend-class/module7.js, webpack-test/cases/inner-graph/extend-class/module8.js, webpack-test/cases/inner-graph/extend-class/module9.js, webpack-test/cases/inner-graph/extend-class/test.filter.js
1. related webpack pr: https://github.com/webpack/webpack/pull/17940
=> fix: 🐛 inner graph extend class super with constructor

crates/rspack_core/src/dependency/runtime_template.rs, crates/rspack_plugin_javascript/src/dependency/esm/harmony_import_specifier_dependency.rs
=> chore: 🤖 add comments when the export name is unused

.github/workflows/reusable-build.yml
=> chore: run diff on linux only

crates/rspack_core/src/module.rs
=> fix: buildinfo cacheable default value should be true

crates/rspack_core/src/utils/concatenated_module_visitor.rs
=> fix: missing visitor in concatenate modules

packages/rspack/tests/configCases/module/issue-5548/dynamic.js, packages/rspack/tests/configCases/module/issue-5548/index.js, packages/rspack/tests/configCases/module/issue-5548/webpack.config.js
Fixes https://github.com/web-infra-dev/rspack/issues/5548
=> test: add test case for eager import

crates/rspack_core/src/compiler/compilation.rs, packages/rspack/tests/configCases/errors/bail/errors.js, packages/rspack/tests/configCases/errors/bail/index.js, packages/rspack/tests/configCases/errors/bail/webpack.config.js
=> fix: should gracefully shutdown on bail

Cargo.lock, crates/swc_plugin_import/Cargo.toml
closes https://github.com/web-infra-dev/rspack/issues/5613
=> chore: fix yanked handlebars

crates/rspack_core/src/compiler/queue.rs
=> fix: should not panic while running build_module hook

.github/workflows/ci.yml
=> chore: support open macos & windows ci in PR

crates/rspack_plugin_javascript/src/dependency/context/common_js_require_context_dependency.rs, crates/rspack_plugin_javascript/src/dependency/context/import_context_dependency.rs, crates/rspack_plugin_javascript/src/parser_plugin/common_js_imports_parse_plugin.rs, crates/rspack_plugin_javascript/src/parser_plugin/import_parser_plugin.rs, crates/rspack_plugin_javascript/src/visitors/dependency/context_helper.rs, crates/rspack_plugin_javascript/src/visitors/dependency/import_scanner.rs, crates/rspack_plugin_javascript/src/visitors/dependency/mod.rs, packages/rspack/tests/cases/context/resource-query/a.js, packages/rspack/tests/cases/context/resource-query/abc.js, packages/rspack/tests/cases/context/resource-query/index.js
=> feat: support resource query in context module

.github/renovate.json
=> chore: do not update pnpm with renovate bot

crates/rspack_core/src/chunk_graph/chunk_graph_chunk.rs, crates/rspack_plugin_javascript/src/plugin/module_concatenation_plugin.rs, packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap, packages/rspack/tests/statsCases/css-concat/foo.css, packages/rspack/tests/statsCases/css-concat/index.js, packages/rspack/tests/statsCases/css-concat/webpack.config.js
Fix #5593
Should not disconnect CSS module from original chunk when concate module
=> fix: concate modules with css

packages/rspack/tests/__snapshots__/StatsTestCases.test.ts.snap
=> test: flush snapshot

crates/rspack_core/src/tree_shaking/visitor.rs
Fix can not resolve warning in CI
=> fix: can not resolve warning of cjs export require

Cargo.lock, crates/rspack_core/Cargo.toml
=> chore: bump oxc-resolver

packages/rspack/src/builtin-plugin/EvalSourceMapDevToolPlugin.ts
=> fix: add missing field in EvalSourceMapDevToolPlugin

crates/rspack_binding_options/src/options/mod.rs
=> fix: disable incRebuild when enable new treeshaking

crates/rspack_core/src/utils/compile_boolean_matcher.rs
Fix eco ci error, align with webpack https://github.com/webpack/webpack/blob/651b3d66d10d54da31d4cb7123ea74d10f1f5456/lib/util/compileBooleanMatcher.js#L12
=> fix: quote meta slash error

Cargo.lock, crates/rspack_core/Cargo.toml
=> fix: bump `oxc-resolver` to fix windows path

crates/node_binding/binding.d.ts, crates/node_binding/src/hook.rs, crates/node_binding/src/plugins/mod.rs, crates/rspack_binding_values/src/hooks.rs, crates/rspack_core/src/compiler/compilation.rs, crates/rspack_core/src/compiler/mod.rs, crates/rspack_core/src/plugin/api.rs, crates/rspack_core/src/plugin/plugin_driver.rs, crates/rspack_hook/src/async_parallel.rs, crates/rspack_plugin_entry/src/lib.rs, crates/rspack_plugin_mf/src/container/container_plugin.rs, crates/rspack_plugin_progress/src/lib.rs, packages/rspack/src/Compiler.ts, packages/rspack/tests/Stats.test.ts, packages/rspack/tests/copyPlugin/build/main.js, packages/rspack/tests/copyPlugin/fixtures/watch/_t5/tempfile1.txt, packages/rspack/tests/copyPlugin/fixtures/watch/_t5/tempfile2.txt
=> refactor: make hook

packages/rspack/src/rspack.ts
=> fix: should report validation error if no callback exists

Cargo.lock, crates/rspack_core/Cargo.toml, crates/rspack_core/src/build_chunk_graph/code_splitter.rs, packages/rspack/tests/Stats.test.ts
Inspired from https://github.com/webpack/webpack/pull/18090 by https://github.com/dmichon-msft.
Use bitmap to effectively calculate intersections
=> perf(code-splitting): optimize modules intersection

crates/rspack_plugin_runtime/src/helpers.rs, packages/rspack/tests/hotCases/chunk/multi-chunk-single-runtime/webpack.config.js
=> fix: runtime chunk filename

crates/rspack_core/src/dependency/dependency_type.rs, crates/rspack_core/src/tree_shaking/optimizer.rs, packages/rspack/tests/cases/cjs-tree-shaking/export-require-bailout/index.js, packages/rspack/tests/cases/cjs-tree-shaking/export-require-bailout/package.json, packages/rspack/tests/cases/cjs-tree-shaking/export-require-bailout/reexport.js, packages/rspack/tests/cases/cjs-tree-shaking/export-require-bailout/value.js, packages/rspack/tests/cases/cjs-tree-shaking/export-require-bailout/webpack.config.js
=> fix: cjs export require should bailout in old tree shaking

packages/rspack/tests/Compiler.test.js, webpack-test/Compiler.test.js
=> fix: compiler test error in !windows

crates/rspack_plugin_javascript/src/visitors/dependency/parser/walk.rs, packages/rspack/tests/cases/parsing/issue-5786/index.js
=> fix: fix `this` in ctor default param transform into `undefined`

crates/rspack_core/src/resolver/mod.rs, packages/rspack/tests/diagnostics/builtins/recoverable_syntax_error/stats.err, packages/rspack/tests/diagnostics/factorize/resolve-extensions-error/stats.err
=> feat: polish diagnostic suggestion wordings for module resolution

packages/rspack/tests/HashTestCases.test.js
related https://github.com/web-infra-dev/rspack/issues/5797
=> chore: js hash test

packages/rspack/tests/Output.test.js
=> chore: align output test runners

crates/rspack_plugin_javascript/src/plugin/inner_graph_plugin.rs, packages/rspack/tests/configCases/tree-shaking/issue-5782/index.js, packages/rspack/tests/configCases/tree-shaking/issue-5782/package/index.js, packages/rspack/tests/configCases/tree-shaking/issue-5782/webpack.config.js
Closed https://github.com/web-infra-dev/rspack/issues/5782
=> fix: 🐛 fix 5782

packages/rspack-test-tools/package.json
=> fix: release @rspack/test-tools

packages/rspack/src/Compiler.ts, packages/rspack/tests/configCases/hooks/interceptor/index.js, packages/rspack/tests/configCases/hooks/interceptor/webpack.config.js
=> fix: disable hooks should respect interceptor

crates/rspack_plugin_javascript/src/visitors/dependency/parser/walk.rs, packages/rspack/tests/configCases/parsing/class-method-parameters/foo.js, packages/rspack/tests/configCases/parsing/class-method-parameters/index.js, packages/rspack/tests/configCases/parsing/class-method-parameters/webpack.config.js
should walk parameters in class methods
=> fix(parser): should walk parameters in class methods

packages/rspack/jest.config.js, packages/rspack/tests/Compiler.test.js, packages/rspack/tests/Stats.test.js, packages/rspack/tests/__snapshots__/ConfigTestCases.basictest.js.snap, packages/rspack/tests/__snapshots__/Defaults.unittest.js.snap, packages/rspack/tests/__snapshots__/Stats.test.js.snap, packages/rspack/tests/__snapshots__/StatsTestCases.basictest.js.snap, packages/rspack/tests/copyPlugin/__snapshots__/CopyPlugin.test.js.snap
Related: https://github.com/web-infra-dev/rspack/issues/5685
=> chore: align jest config

Cargo.lock, Cargo.toml
For relevant context, see the pull request at https://github.com/web-infra-dev/rspack-sources/pull/89
=> perf: let CachedSource work right

crates/rspack_binding_options/src/options/raw_devtool.rs, packages/rspack/src/rspackOptionsApply.ts
=> fix: let filename can receive null

packages/rspack-plugin-minify/src/index.js, packages/rspack/tests/configCases/plugins/minify-with-devtool-false/index.js, packages/rspack/tests/configCases/plugins/minify-with-devtool-false/lib.js, packages/rspack/tests/configCases/plugins/minify-with-devtool-false/webpack.config.js
=> fix: should not generate minify plugin based on devtool

.github/actions/pnpm-cache/action.yml
=> chore: set pnpm store-dir to global store-dir + version

.github/workflows/ci.yml
=> feat: run ecosystem ci as merged into main

packages/rspack/jest.config.js
=> fix: jest disable transform node_module

crates/rspack_plugin_javascript/src/parser_plugin/api_plugin.rs, crates/rspack_plugin_javascript/src/parser_plugin/common_js_imports_parse_plugin.rs, crates/rspack_plugin_javascript/src/parser_plugin/compatibility_plugin.rs, crates/rspack_plugin_javascript/src/utils/eval/eval_unary_expr.rs, crates/rspack_plugin_javascript/src/utils/eval/mod.rs, crates/rspack_plugin_javascript/src/visitors/dependency/parser/mod.rs, packages/rspack/tests/cases/warnings/require-as-expression/index.js, packages/rspack/tests/cases/warnings/require-as-expression/warnings.js, packages/rspack/tests/configCases/chunk-loading/startup-async-node-1/index.js, packages/rspack/tests/configCases/chunk-loading/startup-async-node-2/index.js, packages/rspack/tests/configCases/chunk-loading/startup-async-node-3/index.js
=> fix: require as expression

crates/node_binding/binding.d.ts, crates/rspack_binding_values/src/compilation.rs, packages/rspack/src/Compilation.ts, packages/rspack/tests/configCases/asset/rename-asset/chunk.js, packages/rspack/tests/configCases/asset/rename-asset/index.js, packages/rspack/tests/configCases/asset/rename-asset/webpack.config.js
=> feat: support compilation.renameAsset

crates/rspack_plugin_javascript/src/parser_plugin/import_parser_plugin.rs, crates/rspack_plugin_javascript/src/webpack_comment.rs, packages/rspack/tests/configCases/parsing/import-eager/index.js, packages/rspack/tests/configCases/parsing/import-eager/two.js, packages/rspack/tests/configCases/parsing/import-eager/webpack.config.js, webpack-test/cases/scope-hoisting/issue-10308/test.filter.js
=> fix: webpackMode eager for dynamic import

webpack-test/jest.config.js
=> chore: disable webpack-test jest transform

packages/rspack/src/config/adapterRuleUse.ts, packages/rspack/src/loader-runner/index.ts
=> chore: align webpack type

x.mjs
=> chore: x script support force build

Cargo.lock, crates/rspack_core/src/normal_module.rs, crates/rspack_core/src/parser_and_generator.rs, crates/rspack_plugin_javascript/Cargo.toml, crates/rspack_plugin_javascript/src/parser_and_generator/mod.rs, crates/rspack_plugin_javascript/src/plugin/side_effects_flag_plugin.rs, packages/rspack/tests/__snapshots__/StatsTestCases.basictest.js.snap, packages/rspack/tests/statsCases/side-effects-bailouts/lib.js
1. optimization bailout location
=> fix: 🐛 bailout stats location

.github/workflows/ci.yml
=> chore: support test release build in CI and enable windows test in CI

.github/workflows/ci.yml
=> chore: remove duplicate "uses"

crates/rspack_core/src/concatenated_module.rs, crates/rspack_plugin_split_chunks/src/plugin/max_request.rs, packages/rspack/tests/configCases/less-loader/resolve/index.js
=> chore: fix some comments

packages/rspack/tests/configCases/css/urls/index.js
=> test: make sure import not run after it

crates/rspack_plugin_javascript/src/parser_plugin/harmony_export_dependency_parser_plugin.rs, packages/rspack/tests/cases/esm/export-string-name/a.js, packages/rspack/tests/cases/esm/export-string-name/index.js
=> fix: export string name in harmony module

packages/rspack/tests/configCases/split-chunks/chunks-function/webpack.config.js
=> test: run async node library exports may cause error in ci

crates/rspack_core/src/compiler/make/mod.rs
=> refactor(core): add a `UpdateModuleGraph` struct with `cutout` and `repair` steps

.github/workflows/ci.yml
Print eco ci results in commit.
=> chore: print eco ci result in commit

packages/rspack-test-tools/src/processor/multi.ts, packages/rspack-test-tools/src/runner/basic.ts, packages/rspack-test-tools/src/runner/multiple.ts, packages/rspack-test-tools/src/runner/watch.ts, packages/rspack/tests/configCases/runtime/dynamic-css-chunk-with-umd/test.config.js
=> chore(testng): should not share runner between multiple compiler when run same file

crates/rspack_core/src/context_module.rs, packages/rspack/tests/__snapshots__/StatsTestCases.basictest.js.snap, packages/rspack/tests/hotCases/context/request-position/changed-file.js, packages/rspack/tests/hotCases/context/request-position/file.js, packages/rspack/tests/hotCases/context/request-position/index.js, packages/rspack/tests/hotCases/context/request-position/lib/a.js
=> fix: context request position change error

crates/rspack_core/src/compiler/make/mod.rs, crates/rspack_core/src/compiler/make/queue.rs, crates/rspack_core/src/compiler/mod.rs
=> refactor(core): move compiler/queue.rs to compiler/make/queue.rs

crates/node_binding/binding.d.ts, crates/rspack_binding_options/src/options/raw_resolve.rs, packages/rspack/src/config/adapter.ts, packages/rspack/tests/configCases/resolve/alias-order/b.js, packages/rspack/tests/configCases/resolve/alias-order/index.js, packages/rspack/tests/configCases/resolve/alias-order/webpack.config.js
=> fix: alias should have order

Cargo.lock, crates/node_binding/Cargo.toml, crates/node_binding/binding.d.ts, crates/node_binding/src/plugins/mod.rs, crates/rspack_binding_macros/src/macros.rs, crates/rspack_binding_options/src/options/mod.rs, crates/rspack_binding_options/src/options/raw_builtins/raw_banner.rs, crates/rspack_binding_options/src/options/raw_devtool.rs, crates/rspack_binding_options/src/options/raw_external.rs, crates/rspack_binding_options/src/options/raw_module/mod.rs, crates/rspack_binding_options/src/options/raw_split_chunks/mod.rs, crates/rspack_binding_options/src/options/raw_split_chunks/raw_split_chunk_cache_group_test.rs, crates/rspack_binding_options/src/options/raw_split_chunks/raw_split_chunk_chunks.rs, crates/rspack_binding_options/src/options/raw_split_chunks/raw_split_chunk_name.rs, crates/rspack_binding_values/src/hooks.rs, crates/rspack_napi_shared/src/callback.rs, crates/rspack_napi_shared/src/new_tsfn.rs
=> refactor: support new tsfn (stage 2)

Cargo.lock, crates/rspack_core/Cargo.toml
https://github.com/oxc-project/oxc-resolver/releases/tag/1.6.1
=> chore(core): bump oxc_resolver

crates/node_binding/binding.d.ts, crates/rspack_binding_options/src/options/raw_module/mod.rs, packages/rspack/src/config/adapter.ts
=> fix: ci failed caused by unresolved conflict

Cargo.lock, crates/node_binding/Cargo.toml, crates/node_binding/binding.d.ts, crates/node_binding/src/compiler.rs, crates/node_binding/src/lib.rs, crates/node_binding/src/loader.rs, crates/node_binding/src/plugins/interceptor.rs, crates/node_binding/src/plugins/mod.rs, crates/rspack/Cargo.toml, crates/rspack/benches/main.rs, crates/rspack_allocator/Cargo.toml, crates/rspack_allocator/src/lib.rs, crates/rspack_binding_values/Cargo.toml, crates/rspack_binding_values/src/chunk.rs, crates/rspack_binding_values/src/chunk_graph.rs, crates/rspack_binding_values/src/chunk_group.rs, crates/rspack_binding_values/src/compilation.rs, crates/rspack_binding_values/src/module.rs, crates/rspack_binding_values/src/source.rs, crates/rspack_binding_values/src/stats.rs, crates/rspack_binding_values/src/utils.rs, crates/rspack_napi/src/callback.rs, packages/rspack/src/Compiler.ts
=> refactor: support new tsfn (stage 4)

crates/node_binding/src/lib.rs
=> perf(node-binding): lock-free compiler

packages/rspack-test-tools/package.json, packages/rspack-test-tools/src/index.ts, packages/rspack-test-tools/src/processor/index.ts, packages/rspack-test-tools/src/processor/simple.ts, packages/rspack-test-tools/src/test/context.ts, packages/rspack-test-tools/tests/Compiler.test.js, packages/rspack-test-tools/tests/compilerCases/assets-empty.js, packages/rspack-test-tools/tests/compilerCases/assets-exist.js, packages/rspack-test-tools/tests/compilerCases/assets-not-exist.js, packages/rspack-test-tools/tests/compilerCases/assets-update.js, packages/rspack-test-tools/tests/compilerCases/assets.js, packages/rspack-test-tools/tests/compilerCases/bubble-bail.js, packages/rspack-test-tools/tests/compilerCases/compilation.js, packages/rspack-test-tools/tests/compilerCases/error-stack-async.js, packages/rspack-test-tools/tests/compilerCases/error-stack-sync.js, packages/rspack-test-tools/tests/compilerCases/get-cache.js, packages/rspack-test-tools/tests/compilerCases/hooks-after-optimize-modules.js, packages/rspack-test-tools/tests/compilerCases/hooks-optimize-modules.js, packages/rspack-test-tools/tests/compilerCases/named-chunk.js, packages/rspack-test-tools/tests/compilerCases/single-file.js, packages/rspack-test-tools/tests/compilerCases/splitchunks-minchunks.js, pnpm-lock.yaml
=> chore(testng): run compiler cases by new runner

crates/rspack_napi/src/callback.rs
=> perf(node-binding): reduce `JsCallback` lock contentions

packages/rspack-test-tools/src/processor/index.ts, packages/rspack-test-tools/src/processor/stats-api.ts, packages/rspack-test-tools/tests/Stats.test.js, packages/rspack-test-tools/tests/compilerCases/assets-empty.js, packages/rspack-test-tools/tests/compilerCases/assets-exist.js, packages/rspack-test-tools/tests/compilerCases/assets-not-exist.js, packages/rspack-test-tools/tests/compilerCases/assets-update.js, packages/rspack-test-tools/tests/compilerCases/assets.js, packages/rspack-test-tools/tests/compilerCases/bubble-bail.js, packages/rspack-test-tools/tests/compilerCases/compilation.js, packages/rspack-test-tools/tests/compilerCases/error-stack-async.js, packages/rspack-test-tools/tests/compilerCases/error-stack-sync.js, packages/rspack-test-tools/tests/compilerCases/get-cache.js, packages/rspack-test-tools/tests/compilerCases/hooks-after-optimize-modules.js, packages/rspack-test-tools/tests/compilerCases/hooks-optimize-modules.js, packages/rspack-test-tools/tests/compilerCases/named-chunk.js, packages/rspack-test-tools/tests/compilerCases/single-file.js, packages/rspack-test-tools/tests/compilerCases/splitchunks-minchunks.js, packages/rspack-test-tools/tests/statsAPICases/basic.js, packages/rspack-test-tools/tests/statsAPICases/cache-disabled.js, packages/rspack-test-tools/tests/statsAPICases/cache-enabled.js, packages/rspack-test-tools/tests/statsAPICases/child-compiler.js, packages/rspack-test-tools/tests/statsAPICases/exports.js, packages/rspack-test-tools/tests/statsAPICases/ids.js, packages/rspack-test-tools/tests/statsAPICases/modules.js, packages/rspack-test-tools/tests/statsAPICases/placeholders.js, packages/rspack-test-tools/tests/statsAPICases/profile.js, packages/rspack-test-tools/tests/statsAPICases/to-string.js, packages/rspack-test-tools/tests/statsAPICases/verbose-time.js, packages/rspack-test-tools/tests/statsAPICases/with-query.js
=> chore(testng): run stats api cases by new runner

crates/node_binding/binding.d.ts, crates/node_binding/src/hook.rs, crates/node_binding/src/lib.rs, crates/node_binding/src/plugins/mod.rs, crates/rspack_binding_options/src/lib.rs, crates/rspack_binding_options/src/options/raw_builtins/mod.rs, crates/rspack_binding_options/src/plugins/js_loader_resolver.rs, crates/rspack_binding_options/src/plugins/mod.rs, packages/rspack/src/Compiler.ts, packages/rspack/src/builtin-plugin/JsLoaderRspackPlugin.ts, packages/rspack/src/builtin-plugin/index.ts, packages/rspack/src/rspackOptionsApply.ts
=> refactor: support js loader plugin

crates/rspack_core/src/utils/compile_boolean_matcher.rs
`list[1].len` maybe less than 2
=> fix: overflow

Cargo.lock, Cargo.toml, crates/rspack_plugin_css/Cargo.toml, crates/swc_plugin_import/Cargo.toml, crates/swc_plugin_import/src/lib.rs, crates/swc_plugin_import/tests/member_case.rs, packages/rspack/tests/configCases/builtin-swc-loader/plugin-import/src/style-true/lib/with-number3d/index.js, packages/rspack/tests/configCases/builtin-swc-loader/plugin-import/style-true.js
=> fix: plugin import camel case with number

crates/node_binding/src/lib.rs, crates/node_binding/src/plugins/interceptor.rs, crates/node_binding/src/plugins/mod.rs, crates/rspack_core/src/compiler/hmr.rs, crates/rspack_core/src/compiler/mod.rs, crates/rspack_napi/src/threadsafe_function.rs
=> chore: shorten SAFETY comments

crates/node_binding/binding.d.ts, crates/node_binding/src/hook.rs, crates/node_binding/src/plugins/interceptor.rs, crates/node_binding/src/plugins/mod.rs, crates/rspack_binding_values/src/hooks.rs, crates/rspack_core/src/compiler/compilation.rs, crates/rspack_core/src/plugin/api.rs, crates/rspack_core/src/plugin/plugin_driver.rs, crates/rspack_core/src/runtime_module.rs, crates/rspack_hook/src/async_series.rs, crates/rspack_hook/src/lib.rs, crates/rspack_macros/src/runtime_module.rs, crates/rspack_plugin_devtool/src/lib.rs, packages/rspack/src/Compilation.ts, packages/rspack/src/Compiler.ts
=> refactor: runtime module hook

crates/rspack_core/src/exports_info.rs, crates/rspack_core/src/module.rs, crates/rspack_plugin_javascript/src/plugin/flag_dependency_exports_plugin.rs, crates/rspack_plugin_javascript/src/plugin/module_concatenation_plugin.rs, crates/rspack_plugin_javascript/src/plugin/side_effects_flag_plugin.rs
=> fix: remove useless MutexModuleGraph

crates/node_binding/binding.d.ts, crates/node_binding/src/hook.rs, crates/node_binding/src/plugins/interceptor.rs, crates/node_binding/src/plugins/mod.rs, crates/rspack_binding_values/src/hooks.rs, crates/rspack_core/src/compiler/compilation.rs, crates/rspack_core/src/compiler/make/queue.rs, crates/rspack_core/src/plugin/api.rs, crates/rspack_core/src/plugin/plugin_driver.rs, crates/rspack_plugin_progress/src/lib.rs, packages/rspack/src/Compilation.ts, packages/rspack/src/Compiler.ts
=> refactor: succeed module hook

crates/node_binding/binding.d.ts, crates/node_binding/src/hook.rs, crates/node_binding/src/plugins/interceptor.rs, crates/node_binding/src/plugins/mod.rs, crates/rspack_binding_values/src/chunk.rs, crates/rspack_binding_values/src/hooks.rs, crates/rspack_core/src/compiler/compilation.rs, crates/rspack_core/src/plugin/api.rs, crates/rspack_core/src/plugin/args.rs, crates/rspack_core/src/plugin/plugin_driver.rs, packages/rspack/src/Chunk.ts, packages/rspack/src/Compilation.ts, packages/rspack/src/Compiler.ts
=> refactor: chunk asset hook

packages/rspack-test-tools/tests/compilerCases/compilation.js, packages/rspack-test-tools/tests/compilerCases/splitchunks-minchunks.js, packages/rspack-test-tools/tests/statsAPICases/cache-disabled.js, packages/rspack-test-tools/tests/statsAPICases/cache-enabled.js, packages/rspack-test-tools/tests/statsAPICases/verbose-time.js
=> fix(testng): use compiler.run

crates/rspack_plugin_html/src/plugin.rs, crates/rspack_plugin_html/tests/fixtures/inject/index.css, crates/rspack_plugin_html/tests/fixtures/inject/index.html, crates/rspack_plugin_html/tests/fixtures/inject/index.js, crates/rspack_plugin_html/tests/fixtures/inject/snapshot/output.snap, crates/rspack_plugin_html/tests/fixtures/inject/test.config.json
This is pull request to fix #5544
=> fix(rspack_plugin_html): align rspack_plugin_html inject option behavior with html-webpack-plugin

crates/rspack_core/src/cache/mod.rs, crates/rspack_core/src/compiler/make/mod.rs, crates/rspack_plugin_progress/src/lib.rs, crates/rspack_tracing/src/lib.rs
=> perf: cleanup atomics

crates/node_binding/binding.d.ts, crates/node_binding/src/hook.rs, crates/node_binding/src/plugins/interceptor.rs, crates/node_binding/src/plugins/mod.rs, crates/rspack_binding_values/src/hooks.rs, crates/rspack_core/src/compiler/mod.rs, crates/rspack_core/src/plugin/api.rs, crates/rspack_core/src/plugin/plugin_driver.rs, crates/rspack_plugin_progress/src/lib.rs, packages/rspack/src/Compiler.ts
=> refactor: emit and after emit hook

crates/rspack_core/src/plugin/plugin_driver.rs, packages/rspack/src/builtin-plugin/EnableLibraryPlugin.ts, packages/rspack/src/builtin-plugin/base.ts, packages/rspack/src/sharing/ShareRuntimePlugin.ts, packages/rspack/tests/configCases/library/duplicate-module-library/index.js, packages/rspack/tests/configCases/library/duplicate-module-library/test.config.js, packages/rspack/tests/configCases/library/duplicate-module-library/webpack.config.js
=> fix: duplicate library plugin

website/docs/en/guide/builtin-swc-loader.mdx, website/docs/zh/guide/builtin-swc-loader.mdx
add swc experimental plugin usage
=> doc: add swc plugin usage

crates/node_binding/binding.d.ts, crates/node_binding/src/hook.rs, crates/node_binding/src/plugins/interceptor.rs, crates/node_binding/src/plugins/mod.rs, crates/rspack_binding_values/src/hooks.rs, crates/rspack_core/src/compiler/compilation.rs, crates/rspack_core/src/plugin/api.rs, crates/rspack_core/src/plugin/plugin_driver.rs, crates/rspack_plugin_javascript/src/plugin/module_concatenation_plugin.rs, crates/rspack_plugin_progress/src/lib.rs, packages/rspack/src/Compilation.ts, packages/rspack/src/Compiler.ts
=> refactor: optimize tree and optimize chunk modules hook

crates/rspack_plugin_javascript/src/parser_plugin/worker_plugin.rs, crates/rspack_plugin_javascript/src/webpack_comment.rs, packages/rspack/tests/configCases/worker/worker-webpack-chunk-name/a.js, packages/rspack/tests/configCases/worker/worker-webpack-chunk-name/index.js, packages/rspack/tests/configCases/worker/worker-webpack-chunk-name/webpack.config.js
=> feat: support webpackChunkName comment for worker

crates/rspack_binding_options/src/options/mod.rs, packages/rspack/tests/hotCases/newTreeshaking/auto-reexport/changed-file.js, packages/rspack/tests/hotCases/newTreeshaking/auto-reexport/file.js, packages/rspack/tests/hotCases/newTreeshaking/auto-reexport/index.js, packages/rspack/tests/hotCases/newTreeshaking/auto-reexport/reexport.js, packages/rspack/tests/hotCases/newTreeshaking/auto-reexport/webpack.config.js, packages/rspack/tests/hotCases/newTreeshaking/multi-chunk-single-runtime/a/index.js, packages/rspack/tests/hotCases/newTreeshaking/multi-chunk-single-runtime/b/index.js, packages/rspack/tests/hotCases/newTreeshaking/multi-chunk-single-runtime/changed-file.js, packages/rspack/tests/hotCases/newTreeshaking/multi-chunk-single-runtime/file.js, packages/rspack/tests/hotCases/newTreeshaking/multi-chunk-single-runtime/main/index.js, packages/rspack/tests/hotCases/newTreeshaking/multi-chunk-single-runtime/webpack.config.js
=> feat: enable incremental_rebuild when use new treeshaking

website/docs/en/config/other-options.mdx, website/docs/zh/config/other-options.mdx
`ignoreWarnings` is already supported in rspack, add `ignoreWarnings` documentation.
=> docs: add ignoreWarnings option

packages/rspack-test-tools/tests/compilerCases/child-compiler.js, packages/rspack/src/Compiler.ts, packages/rspack/src/builtin-plugin/JsLoaderRspackPlugin.ts, packages/rspack/src/rspackOptionsApply.ts, packages/rspack/tests/fixtures/callback-loader.js
=> fix: `Compiler` and `Compilation` in `LoaderContext` of a childCompiler should be updated

crates/rspack/tests/tree-shaking/array-side-effects/snapshot/output.snap, crates/rspack/tests/tree-shaking/reexport_entry_elimination/snapshot/output.snap, crates/rspack/tests/tree-shaking/webpack-inner-graph-switch/snapshot/output.snap, crates/rspack_plugin_javascript/src/dependency/esm/harmony_export_imported_specifier_dependency.rs, crates/rspack_plugin_javascript/src/dependency/esm/harmony_import_dependency.rs, crates/rspack_plugin_javascript/src/dependency/esm/harmony_import_specifier_dependency.rs
=> fix: disable import stmt opt in old tree shaking

crates/node_binding/binding.d.ts, crates/node_binding/src/hook.rs, crates/node_binding/src/plugins/interceptor.rs, crates/node_binding/src/plugins/mod.rs, crates/rspack_binding_values/src/hooks.rs, crates/rspack_core/src/context_module_factory.rs, crates/rspack_hook/src/async_series_bail.rs, crates/rspack_hook/src/lib.rs, packages/rspack/src/Compiler.ts, packages/rspack/src/ContextModuleFactory.ts
=> refactor: cmf after resolve hook

.github/PULL_REQUEST_TEMPLATE.md
The current PR template is outdated, as `rspack-website` has been merged into the Rspack repo.
So I have updated the checklist in the template to make it clearer.
=> chore(workflow): update PR template

README.md, README.zh-CN.md, website/rspress.config.ts
=> chore: add rspack-compat

Cargo.lock, crates/node_binding/Cargo.toml, crates/node_binding/binding.d.ts, crates/node_binding/src/hook.rs, crates/node_binding/src/plugins/interceptor.rs, crates/node_binding/src/plugins/mod.rs, crates/rspack_binding_values/src/hooks.rs, crates/rspack_binding_values/src/normal_module_factory.rs, crates/rspack_core/src/context_module_factory.rs, crates/rspack_core/src/normal_module_factory.rs, crates/rspack_core/src/plugin/api.rs, crates/rspack_core/src/plugin/args.rs, crates/rspack_core/src/plugin/plugin_driver.rs, crates/rspack_hook/src/async_series_bail.rs, crates/rspack_hook/src/lib.rs, crates/rspack_plugin_mf/src/sharing/consume_shared_plugin.rs, crates/rspack_plugin_mf/src/sharing/provide_shared_plugin.rs, crates/rspack_plugin_runtime/src/lazy_compilation.rs, packages/rspack/src/Compiler.ts, packages/rspack/src/Module.ts, packages/rspack/src/NormalModuleFactory.ts, packages/rspack/tests/configCases/hooks/create-module/index.js, packages/rspack/tests/configCases/hooks/create-module/webpack.config.js
=> refactor: nmf create module hook

README.md, README.zh-CN.md, scripts/alert/discord.js, website/docs/en/misc/branding.mdx, website/docs/en/misc/license.md, website/docs/zh/misc/branding.mdx, website/docs/zh/misc/license.md, website/rspress.config.ts
- Add `rsfamily-design-resources` to website.
- Update the legacy `rspack-website` links.
=> docs: add rsfamily-design-resources

packages/rspack/src/exports.ts
Export MultiStats class:
```js
const { MultiStats } = require('@rspack/core');
```
The same as webpack:
```js
const MultiStats = require('webpack/lib/MultiStats');
```
=> feat: export MultiStats class

Cargo.lock, Cargo.toml, crates/rspack_core/src/tree_shaking/visitor.rs, crates/rspack_core/src/utils/concatenated_module_visitor.rs, crates/rspack_loader_swc/Cargo.toml, crates/rspack_loader_swc/src/lib.rs, crates/rspack_plugin_javascript/src/parser_plugin/common_js_exports_parse_plugin.rs, crates/rspack_plugin_javascript/src/parser_plugin/common_js_imports_parse_plugin.rs, crates/rspack_plugin_javascript/src/parser_plugin/common_js_plugin.rs, crates/rspack_plugin_javascript/src/parser_plugin/harmony_import_dependency_parser_plugin.rs, crates/rspack_plugin_javascript/src/parser_plugin/require_context_dependency_parser_plugin.rs, crates/rspack_plugin_javascript/src/visitors/dependency/parser/mod.rs, crates/rspack_plugin_javascript/src/visitors/dependency/parser/walk.rs, crates/rspack_plugin_javascript/src/visitors/dependency/util.rs, packages/rspack/package.json, pnpm-lock.yaml
This is a BREAKING CHANGE for those who're using swc wasm plugins and should be released as a part of `0.6`. The supported `swc_core` version should be within the range of `0.90.x`.
=> chore: update swc

packages/rspack-dev-server/src/server.ts, packages/rspack-test-tools/tests/statsAPICases/cache-disabled.js, packages/rspack-test-tools/tests/statsAPICases/cache-enabled.js, packages/rspack/src/Compiler.ts
=> chore: remove `compiler.build` and `compiler.rebuild`

crates/rspack_binding_values/src/source.rs, packages/rspack/tests/configCases/hooks/asset-emitted-buffer/index.js, packages/rspack/tests/configCases/hooks/asset-emitted-buffer/webpack.config.js
=> fix: emit asset file with buffer can use in asset emitted hook correctly

.github/actions/docker-build/action.yml, .github/workflows/reusable-build.yml
=> chore: cargo build reuse cache

crates/node_binding/binding.d.ts, crates/rspack_binding_options/src/options/raw_entry.rs, crates/rspack_core/src/build_chunk_graph/code_splitter.rs, crates/rspack_core/src/chunk_group.rs, crates/rspack_core/src/compiler/compilation.rs, crates/rspack_core/src/compiler/execute_module.rs, crates/rspack_core/src/utils/runtime.rs, crates/rspack_plugin_javascript/src/parser_plugin/worker_plugin.rs, crates/rspack_plugin_javascript/src/plugin/flag_dependency_usage_plugin.rs, crates/rspack_plugin_library/src/assign_library_plugin.rs, crates/rspack_plugin_library/src/export_property_library_plugin.rs, crates/rspack_testing/src/test_config.rs, packages/rspack/src/builtin-plugin/EntryPlugin.ts, packages/rspack/src/config/normalization.ts, packages/rspack/src/config/zod.ts, packages/rspack/src/lib/EntryOptionPlugin.ts, packages/rspack/src/rspackOptionsApply.ts, packages/rspack/tests/diagnostics/factorize/entry-runtime-error/stats.err, webpack-test/configCases/entry/depend-on-advanced/test.filter.js, webpack-test/configCases/entry/depend-on-bug/test.filter.js, webpack-test/configCases/entry/depend-on-non-js/test.filter.js, webpack-test/configCases/entry/depend-on-simple/test.filter.js, webpack-test/configCases/entry/issue-12562/test.filter.js, webpack-test/configCases/errors/depend-on-and-runtime/test.filter.js, webpack-test/configCases/errors/depend-on-error/test.filter.js, webpack-test/configCases/runtime/entries-in-runtime/test.filter.js, webpack-test/configCases/split-chunks/move-to-entrypoint/test.filter.js
=> feat: support entry.dependOn

Cargo.lock, crates/rspack_binding_options/src/options/raw_split_chunks/raw_split_chunk_name.rs, crates/rspack_plugin_split_chunks/Cargo.toml, crates/rspack_plugin_split_chunks/src/options/chunk_name.rs, crates/rspack_plugin_split_chunks/src/plugin/mod.rs, crates/rspack_plugin_split_chunks/src/plugin/module_group.rs, packages/rspack/tests/configCases/split-chunks/cache-group-name-function-with-error/errors.js, packages/rspack/tests/configCases/split-chunks/cache-group-name-function-with-error/index.js, packages/rspack/tests/configCases/split-chunks/cache-group-name-function-with-error/webpack.config.js
Related https://github.com/web-infra-dev/rspack/issues/6078
=> fix: handle error of `cacheGroup.name()`

crates/node_binding/binding.d.ts, crates/node_binding/src/plugins/interceptor.rs, crates/node_binding/src/plugins/mod.rs, crates/rspack_core/src/compiler/compilation.rs, packages/rspack-test-tools/tests/statsAPICases/verbose-time.js, packages/rspack/src/Compilation.ts, packages/rspack/src/Compiler.ts, packages/rspack/tests/configCases/hooks/after-seal/index.js, packages/rspack/tests/configCases/hooks/after-seal/webpack.config.js
Relate to #6089, test cases of `entry.dependOn` use this hook to check modules of chunks
=> feat: support compilation.hooks.afterSeal

packages/rspack-test-tools/README.md
add warning notice about @rspack/test-tools
=> chore: add warning notice about @rspack/test-tools

.gitattributes
=> chore: git attributes snap

crates/rspack_plugin_css/src/runtime/css_loading.js, crates/rspack_plugin_css/src/runtime/mod.rs, crates/rspack_plugin_html/tests/fixtures/filename/snapshot/output.snap, crates/rspack_plugin_html/tests/fixtures/variant/snapshot/output.snap, crates/rspack_plugin_runtime/src/runtime_module/load_script.rs, packages/rspack-test-tools/tests/runtimeDiffCases/runtime-load-script/use-credentials/rspack.config.js, packages/rspack-test-tools/tests/runtimeDiffCases/runtime-load-script/use-credentials/src/index.js, packages/rspack-test-tools/tests/runtimeDiffCases/runtime-load-script/use-credentials/test.config.js, packages/rspack-test-tools/tests/runtimeDiffCases/runtime-load-script/use-credentials/webpack.config.js, packages/rspack/tests/__snapshots__/StatsTestCases.basictest.js.snap, packages/rspack/tests/configCases/css/css-cross-origin-loading-use-credentials/chunk.css, packages/rspack/tests/configCases/css/css-cross-origin-loading-use-credentials/index.js, packages/rspack/tests/configCases/css/css-cross-origin-loading-use-credentials/webpack.config.js, packages/rspack/tests/configCases/css/css-cross-origin-loading/chunk.css, packages/rspack/tests/configCases/css/css-cross-origin-loading/index.js, packages/rspack/tests/configCases/css/css-cross-origin-loading/webpack.config.js
=> fix: should add use-credentials into css-loading runtime correctly

crates/rspack_core/src/concatenated_module.rs, crates/rspack_core/src/context_module.rs, crates/rspack_core/src/dependency/dependency_template.rs, crates/rspack_core/src/external_module.rs, crates/rspack_core/src/module.rs, crates/rspack_core/src/normal_module.rs, crates/rspack_core/src/parser_and_generator.rs, crates/rspack_plugin_asset/src/lib.rs, crates/rspack_plugin_css/src/parser_and_generator/mod.rs, crates/rspack_plugin_javascript/src/parser_and_generator/mod.rs, crates/rspack_plugin_javascript/src/parser_plugin/common_js_plugin.rs, crates/rspack_plugin_javascript/src/parser_plugin/hot_module_replacement_plugin.rs, crates/rspack_plugin_javascript/src/plugin/module_concatenation_plugin.rs, crates/rspack_plugin_json/src/lib.rs, crates/rspack_plugin_wasm/src/parser_and_generator.rs
=> fix: 🐛 add concatenation bailout reason

diffcases/arco-pro/rspack.config.js
=> chore: fix diff case

website/docs/en/guide/migrate-storybook.mdx, website/docs/zh/guide/migrate-storybook.mdx
update documentation of integrating with Storybook.
=> docs(storybook): update to use @modern-js/storybook

packages/rspack-test-tools/src/case/watch.ts, packages/rspack-test-tools/src/plugin/webpack-module-placeholder-plugin.ts, packages/rspack-test-tools/src/processor/multi.ts, packages/rspack-test-tools/src/processor/normal.ts, packages/rspack-test-tools/src/runner/basic.ts, packages/rspack-test-tools/src/runner/runner/basic.ts, packages/rspack/src/builtin-plugin/css-extract/index.ts, packages/rspack/src/builtin-plugin/css-extract/loader.ts, packages/rspack/src/builtin-plugin/index.ts
=> chore: run format

crates/rspack_core/src/normal_module_factory.rs, crates/rspack_plugin_css/src/plugin/impl_plugin_for_css_plugin.rs, crates/rspack_util/src/lib.rs, crates/rspack_util/src/merge.rs, diffcases/arco-pro/rspack.config.js, packages/rspack/tests/configCases/module/merge-global-generator/index.js, packages/rspack/tests/configCases/module/merge-global-generator/index.module.css, packages/rspack/tests/configCases/module/merge-global-generator/webpack.config.js
=> fix: merge with global parser generator options

crates/rspack_plugin_javascript/src/utils/eval/eval_binary_expr.rs, packages/rspack/tests/cases/parsing/evaluate-logical/index.js
=> fix: nested `unknown || truthy = unknown truthy` eval logical or

packages/rspack-test-tools/src/runner/hot.ts, packages/rspack-test-tools/src/runner/runner/hot.ts
=> chore: move hot next function from runner to runner factory

crates/rspack_core/src/normal_module_factory.rs, packages/rspack/tests/configCases/loader/rspack-issue-6068/a.js, packages/rspack/tests/configCases/loader/rspack-issue-6068/index.js, packages/rspack/tests/configCases/loader/rspack-issue-6068/loader1.js, packages/rspack/tests/configCases/loader/rspack-issue-6068/loader2.js, packages/rspack/tests/configCases/loader/rspack-issue-6068/loader3.js, packages/rspack/tests/configCases/loader/rspack-issue-6068/webpack.config.js
=> fix: `Rule.enforce` should be applied to `use` of function type

website/components/i18n/en.json, website/components/i18n/zh.json, website/docs/en/config/plugins.mdx, website/docs/en/guide/migrate-from-webpack.mdx, website/docs/zh/config/plugins.mdx, website/docs/zh/guide/migrate-from-webpack.mdx
Add document for CssExtractRspackPlugin
=> docs: cssExtract docs

website/docs/en/config/experiments.mdx, website/docs/zh/config/experiments.mdx
=> docs: enable new tree shaking by default

website/docs/en/config/dev-server.mdx, website/docs/zh/config/dev-server.mdx
Hey, I noticed this while reading the docs and thought I could spend a minute to fix this.
=> docs: fix devServer typo

crates/node_binding/binding.d.ts, crates/rspack_binding_values/src/stats.rs, crates/rspack_core/src/chunk.rs, crates/rspack_core/src/chunk_group.rs, crates/rspack_core/src/stats.rs, packages/rspack/src/stats/DefaultStatsFactoryPlugin.ts, packages/rspack/src/stats/DefaultStatsPrinterPlugin.ts, packages/rspack/tests/__snapshots__/StatsTestCases.basictest.js.snap, packages/rspack/tests/statsCases/prefetch-preload-mixed/a.js, packages/rspack/tests/statsCases/prefetch-preload-mixed/b.js, packages/rspack/tests/statsCases/prefetch-preload-mixed/c.js, packages/rspack/tests/statsCases/prefetch-preload-mixed/index.js, packages/rspack/tests/statsCases/prefetch-preload-mixed/webpack.config.js
=> feat: support stats of prefetch and preload

packages/rspack/src/Compilation.ts
fix: https://github.com/web-infra-dev/rspack/actions/runs/8615403821/job/23610875393
=> fix(ci): compilation file prettier error

website/docs/en/blog/announcing-0.6.mdx, website/docs/zh/blog/announcing-0.6.mdx
=> docs: ✏️ tree shaking

.github/actions/docker-build/action.yml
=> chore: lock corepack

website/theme/components/Announcement/index.tsx
=> docs(webiste): change the hiring link in announcement to /misc/join-us

website/docs/en/plugins/rspack/css-extract-rspack-plugin.mdx
Fix typo in new css-extract-rspack-plugin en doc.
=> docs: fix css-extract-rspack-plugin typos

crates/rspack_core/src/build_chunk_graph/code_splitter.rs, crates/rspack_plugin_split_chunks/src/plugin/module_group.rs
For the internal hug project:
Before:
After:
=> perf: bitwise operation in code splitter

crates/rspack_plugin_javascript/src/visitors/dependency/parser/walk.rs, packages/rspack/tests/cases/parsing/rspack-issue-6164/index.js, packages/rspack/tests/configCases/module-variables/global-true/index.js
closed https://github.com/web-infra-dev/rspack/issues/6197
=> fix: should parse patterns in class

.github/workflows/ci.yml, .github/workflows/reusable-build.yml
=> ci: fix doc reuseable workflow

website/docs/en/blog/announcing-0.6.mdx
Fix a typo in the docs for upgrading to 0.6
=> docs: fix type in guide for upgrading to 0.6

crates/rspack_plugin_split_chunks/src/plugin/chunk.rs, crates/rspack_plugin_split_chunks/src/plugin/max_size.rs, crates/rspack_plugin_split_chunks/src/plugin/min_size.rs
For the internal hug project:
Before:
After:
=> perf: remove bad par_iter

crates/rspack_plugin_mf/src/container/container_entry_dependency.rs, crates/rspack_plugin_mf/src/container/container_entry_module.rs, crates/rspack_plugin_mf/src/container/container_entry_module_factory.rs, crates/rspack_plugin_mf/src/container/container_plugin.rs, crates/rspack_plugin_mf/src/container/expose_runtime_module.rs, packages/rspack/src/stats/DefaultStatsPrinterPlugin.ts, packages/rspack/tests/configCases/container-1-0/multi-container-same-runtime/a.js, packages/rspack/tests/configCases/container-1-0/multi-container-same-runtime/b.js, packages/rspack/tests/configCases/container-1-0/multi-container-same-runtime/bootstrap.js, packages/rspack/tests/configCases/container-1-0/multi-container-same-runtime/index.js, packages/rspack/tests/configCases/container-1-0/multi-container-same-runtime/test.config.js, packages/rspack/tests/configCases/container-1-0/multi-container-same-runtime/webpack.config.js
=> fix(mf-1): conflict module map in multi container

Cargo.lock, crates/node_binding/binding.d.ts, crates/rspack_binding_options/src/options/raw_builtins/raw_css_extract.rs, crates/rspack_plugin_extract_css/Cargo.toml, crates/rspack_plugin_extract_css/src/plugin.rs, crates/rspack_plugin_extract_css/src/runtime.rs, packages/rspack/tests/cssExtract/cases/filename-as-function/test.filter.js
=> feat: support function filename and chunkFilename

website/docs/en/guide/tree-shaking.mdx, website/docs/zh/guide/tree-shaking.mdx
Correct import path `import { b } from './a.js';` to `import { b } from './b.js';` in treeshaking demo.
=> docs: correct import path in treeshaking demo

website/components/CompatibleCard.tsx, website/components/i18n/en.json, website/components/i18n/zh.json, website/docs/en/plugins/webpack/ignore-plugin.mdx, website/docs/zh/plugins/webpack/ignore-plugin.mdx, website/rspress.config.ts
https://github.com/web-infra-dev/rspack/issues/6137
=> docs: add IgnorePlugin introduction

Cargo.lock, Cargo.toml, diffcases/arco-pro/package.json, pnpm-lock.yaml
closes https://github.com/web-infra-dev/rspack/issues/6209
=> fix: swc plugins not being able to spawn threads

website/theme/components/Benchmark/ProgressBar.tsx, website/theme/components/Benchmark/index.module.scss, website/theme/components/Benchmark/index.tsx
=> chore(docs): improve benchmark appearance

.github/workflows/ci.yml
=> feat: split lint-website ci

website/docs/en/plugins/webpack/define-plugin.mdx, website/docs/zh/plugins/webpack/define-plugin.mdx
=> docs: update DefinePlugin docs

website/docs/en/plugins/webpack/provide-plugin.mdx, website/docs/zh/plugins/webpack/provide-plugin.mdx
=> docs: update ProvidePlugin docs

crates/node_binding/binding.d.ts, crates/rspack_binding_values/src/compilation.rs
=> fix: JsPathData type

website/lint-staged.config.mjs, website/package.json
=> chore: use lint-staged in website

packages/rspack/etc/api.md, packages/rspack/src/exports.ts
=> fix: export types of `ModuleFilenameHelpers` and `Template`

website/docs/en/guide/quick-start.mdx, website/docs/zh/guide/quick-start.mdx
Update the scaffolding part of the quick start document, move the Rsbuild introduction to the top, so our users can easily understand why they can use Rsbuild to get started.
=> docs: update scaffolding part of quick start document

website/components/PluginSupportStatusTable.tsx
=> docs: update plugin support status table

website/docs/en/guide/css.mdx, website/docs/en/guide/json.mdx, website/docs/en/guide/nodejs.mdx, website/docs/en/guide/typescript.mdx, website/docs/en/index.md, website/docs/zh/guide/css.mdx, website/docs/zh/guide/json.mdx, website/docs/zh/guide/nodejs.mdx, website/docs/zh/guide/typescript.mdx, website/docs/zh/index.md, website/rspress.config.ts
It was hard finding information regarding different languages and frameworks, they are now consolidated in one seciton.
=> docs(website): consolidate guide / languages and Frameworks

website/components/CompatibleCard.tsx, website/docs/en/plugins/webpack/normal-module-replacement-plugin.mdx, website/docs/zh/plugins/webpack/normal-module-replacement-plugin.mdx, website/rspress.config.ts
Add docs for `NormalModuleReplacementPlugin`
=> docs: NormalModuleReplacementPlugin

crates/rspack_plugin_progress/src/lib.rs
=> fix: progress bar draw interval

website/components/PluginSupportStatusTable.module.scss, website/components/PluginSupportStatusTable.tsx, website/components/builtIns/Table.tsx, website/components/builtIns/mdx-components.tsx, website/theme/index.css
=> docs: make PluginSupportStatusTable responsive

crates/rspack_binding_values/src/compilation.rs, crates/rspack_core/src/compiler/compilation.rs, crates/rspack_core/src/compiler/mod.rs, crates/rspack_core/src/compiler/module_executor.rs
=> fix: compilation.import_module use immutable ref

.github/teams.yml, .github/workflows/issue-pr-trigger.yml, scripts/alert/lark.js
=> chore: Add lark notification for new Issue and PR

crates/rspack_binding_values/src/module.rs, crates/rspack_core/src/module.rs
=> refactor: make trait `Module` `'static`

crates/rspack_plugin_javascript/src/dependency/context/import_context_dependency.rs, crates/rspack_plugin_javascript/src/parser_plugin/import_parser_plugin.rs, crates/rspack_plugin_javascript/src/parser_plugin/initialize_evaluating.rs, crates/rspack_plugin_javascript/src/plugin/mod.rs, crates/rspack_plugin_javascript/src/runtime.rs, crates/rspack_plugin_javascript/src/utils/eval/eval_tpl_expr.rs, crates/rspack_plugin_javascript/src/utils/eval/mod.rs, crates/rspack_plugin_javascript/src/utils/mod.rs, crates/rspack_plugin_javascript/src/visitors/dependency/context_dependency_helper.rs, crates/rspack_plugin_javascript/src/visitors/dependency/parser/mod.rs, crates/rspack_util/src/diff_mode.rs, crates/rspack_util/src/lib.rs, packages/rspack-test-tools/src/plugin/webpack-module-placeholder-plugin.ts, packages/rspack-test-tools/tests/builtinCases/rspack/dynamic-import/snapshot/output.snap.txt, packages/rspack-test-tools/tests/runtimeDiffCases/module-context-module/src/index.js, packages/rspack-test-tools/tests/runtimeDiffCases/module-context-module/src/sub/a.js, packages/rspack-test-tools/tests/runtimeDiffCases/module-context-module/src/sub/a1.js, packages/rspack-test-tools/tests/runtimeDiffCases/module-context-module/src/sub/abc.js
=> refactor: import context dependency param evaluate

.github/workflows/issue-pr-trigger.yml, scripts/alert/lark.js
=> chore: do NOT trigger lark notification for issues from project member

.github/workflows/issue-pr-trigger.yml
=> chore: Use team.yml file to filter team member when sending notification

crates/rspack_core/src/compiler/compilation.rs, crates/rspack_core/src/compiler/make/mod.rs, crates/rspack_core/src/compiler/make/tasks/add.rs, crates/rspack_core/src/module_graph/mod.rs, crates/rspack_plugin_javascript/src/runtime.rs
=> refactor: remove is_new_treeshaking in module_graph

crates/rspack_core/src/module_graph/mod.rs
* rename some fields in module_graph
* add document for module_graph fields
* clean module_graph.block & dependencies in revoke_connection
=> fix: incremental rebuild clean module_graph.block & dependencies

webpack-cli-test/loader/loader.test.js, webpack-cli-test/plugin/plugin.test.js
=> chore: remove repetitive words

api-extractor.json, packages/rspack-dev-server/etc/api.md, packages/rspack-test-tools/etc/api.md, packages/rspack/etc/api.md
=> chore(api-extractor): exclude warning and add forgotten exports to report

Cargo.lock, crates/rspack_core/Cargo.toml, crates/rspack_core/src/resolver/resolver_impl.rs, packages/rspack-test-tools/tests/__snapshots__/Defaults.unittest.js.snap, packages/rspack-test-tools/tests/defaultsCases/cache/non-root.js, packages/rspack-test-tools/tests/defaultsCases/config/browserslist.js, packages/rspack/src/config/defaults.ts, packages/rspack/tests/configCases/resolve/roots/dir/a.js, packages/rspack/tests/configCases/resolve/roots/dir2/b.js, packages/rspack/tests/configCases/resolve/roots/index.js, packages/rspack/tests/configCases/resolve/roots/webpack.config.js
=> fix: default resolve roots

Cargo.lock, crates/rspack_error/Cargo.toml, crates/rspack_error/src/ext.rs, crates/rspack_error/src/miette_helpers.rs
=> feat: diagnostic with labels

website/package.json, website/pnpm-lock.yaml, website/theme/components/Benchmark/index.tsx, website/theme/components/HomeFooter/index.tsx, website/theme/index.css, website/theme/pages/index.tsx
Improve homepage style:
- Consistent background color in dark mode
- Lighter border color in dark mode
- More balanced padding and margin between sections
- Bump Rspress 1.18.4
=> docs: improve homepage style

website/docs/en/guide/tech/react.mdx, website/docs/zh/guide/tech/react.mdx
=> docs: update react doc

crates/rspack_binding_options/src/options/raw_devtool.rs, crates/rspack_binding_options/src/options/raw_split_chunks/raw_split_chunk_cache_group_test.rs, crates/rspack_binding_options/src/options/raw_split_chunks/raw_split_chunk_chunks.rs, crates/rspack_plugin_devtool/src/lib.rs, crates/rspack_plugin_split_chunks/src/common.rs, crates/rspack_plugin_split_chunks/src/options/cache_group_test.rs, crates/rspack_plugin_split_chunks/src/plugin/max_size.rs, crates/rspack_plugin_split_chunks/src/plugin/mod.rs, crates/rspack_plugin_split_chunks/src/plugin/module_group.rs, packages/rspack-test-tools/tests/configCases/split-chunks/chunks-function-with-error/errors.js, packages/rspack-test-tools/tests/configCases/split-chunks/chunks-function-with-error/index.js, packages/rspack-test-tools/tests/configCases/split-chunks/chunks-function-with-error/webpack.config.js, packages/rspack-test-tools/tests/configCases/split-chunks/test-function-with-error/errors.js, packages/rspack-test-tools/tests/configCases/split-chunks/test-function-with-error/index.js, packages/rspack-test-tools/tests/configCases/split-chunks/test-function-with-error/webpack.config.js
=> fix: errors thrown in userland callbacks should not panic

packages/rspack-test-tools/src/runner/hot-step.ts, packages/rspack-test-tools/src/runner/runner/web/jsdom.ts
=> chore: jsdom windows

crates/rspack_plugin_swc_js_minimizer/src/minify.rs, packages/rspack-test-tools/tests/__snapshots__/ConfigTestCases.test.js.snap, packages/rspack-test-tools/tests/configCases/optimization/minimizer-swc-extract-comments/index.js, packages/rspack-test-tools/tests/configCases/optimization/minimizer-swc-extract-comments/node_modules/bar/index.js, packages/rspack-test-tools/tests/configCases/optimization/minimizer-swc-extract-comments/node_modules/bar/package.json, packages/rspack-test-tools/tests/configCases/optimization/minimizer-swc-extract-comments/node_modules/baz/index.js, packages/rspack-test-tools/tests/configCases/optimization/minimizer-swc-extract-comments/node_modules/baz/package.json, packages/rspack-test-tools/tests/configCases/optimization/minimizer-swc-extract-comments/node_modules/foo/index.js, packages/rspack-test-tools/tests/configCases/optimization/minimizer-swc-extract-comments/node_modules/foo/package.json, packages/rspack-test-tools/tests/configCases/optimization/minimizer-swc-extract-comments/relative.js, packages/rspack-test-tools/tests/configCases/optimization/minimizer-swc-extract-comments/webpack.config.js
closes https://github.com/web-infra-dev/rspack/issues/5907
=> fix: swc minimizer extracted comments should be stable

README.md, README.zh-CN.md
=> docs: fix readme.md credits links

crates/rspack_plugin_swc_js_minimizer/src/lib.rs, packages/rspack-test-tools/tests/configCases/builtins/minify-extract-comments-with-query/index.js, packages/rspack-test-tools/tests/configCases/builtins/minify-extract-comments-with-query/webpack.config.js
=> fix: minify comments extract

crates/rspack_plugin_mf/src/container/remote_runtime_module.rs, crates/rspack_plugin_mf/src/sharing/consume_shared_runtime_module.rs
=> fix(mf): remove empty chunk mapping

crates/rspack_plugin_javascript/src/visitors/mod.rs, crates/rspack_plugin_javascript/src/visitors/swc_visitor/dropped_comments_preserver.rs, crates/rspack_plugin_javascript/src/visitors/swc_visitor/mod.rs, packages/rspack-test-tools/tests/builtinCases/plugin-javascript/builtins-define/snapshot/output.snap.txt, packages/rspack-test-tools/tests/builtinCases/plugin-javascript/provide/snapshot/output.snap.txt, packages/rspack-test-tools/tests/configCases/parsing/preserve-all-comments/a.js, packages/rspack-test-tools/tests/configCases/parsing/preserve-all-comments/index.js, packages/rspack-test-tools/tests/configCases/parsing/preserve-all-comments/webpack.config.js, packages/rspack-test-tools/tests/hookCases/normalModuleFactory#afterResolve/duplicate/output.snap.txt, packages/rspack-test-tools/tests/treeShakingCases/tree-shaking-interop/snapshot/new_treeshaking.snap.txt, packages/rspack-test-tools/tests/treeShakingCases/tree-shaking-interop/snapshot/output.snap.txt, packages/rspack-test-tools/tests/treeShakingCases/webpack-innergraph-try-globals/snapshot/new_treeshaking.snap.txt, packages/rspack-test-tools/tests/treeShakingCases/webpack-innergraph-try-globals/snapshot/output.snap.txt, plugin-test/css-extract/enforceEsm.test.js
=> fix: swc parser should always preserve comments

crates/rspack_plugin_javascript/src/parser_and_generator/mod.rs
Module source should be based on the final result before dependency analysis.
=> fix: wrong module source

Cargo.lock, crates/rspack_macros_test/Cargo.toml, crates/rspack_macros_test/tests/runtime_module.rs
=> chore: move rspack_core macro test

crates/rspack_core/src/context_module.rs, packages/rspack-test-tools/tests/runtimeDiffCases/module-context-module/src/namespace-object-lazy/index.js
=> refactor: weak, async-weak, eager mode context module codegen diff

.github/renovate.json
=> chore(deps): fix renovate configuration

crates/rspack_plugin_javascript/src/visitors/mod.rs, packages/rspack-test-tools/tests/configCases/parsing/preserve-all-comments-define/index.js, packages/rspack-test-tools/tests/configCases/parsing/preserve-all-comments-define/webpack.config.js, packages/rspack-test-tools/tests/treeShakingCases/tree-shaking-interop/snapshot/new_treeshaking.snap.txt, packages/rspack-test-tools/tests/treeShakingCases/tree-shaking-interop/snapshot/output.snap.txt
`dropped_comments_preserver` does not aware of the previous pure annotation being removed in define plugin:
[playground](https://play.swc.rs/?version=1.5.2&code=H4sIAAAAAAAAA41VXW%2BbMBR951dYeaigIkTb09SoUz819aFalHRP04Q8uGk8gZ3ZJmkX8d93bQyGlGWN1ATse4%2FPOb73lpVbITU5kF%2FqhdRkLUVJJhJopme4MpUV16yEyTxgbWClYKWphtg8PUIphmn9UKYWUuRVppngXdSVVFsJSs3UhkrIfbxiGu6opi5ux6SuaDE1y9Mc13vIASEm8lZwDS86xtenDZTQe%2BdClrRgf2ApKg0Lqjdm9UaKvQJp12TwhtGI2uvtNiaMM72gzw27NiuZ4R6GZoIrTYDTnwWsVl%2FIZSckUeq53T%2BQHNa0KvRFQ9W6Z5%2BsmYh6SST8rpiEcHKlzcYkmgdUvfKMrCveeCiB5yAfuNMRRtaK5gT81pRxkIiUi6wqgevkGfR9Aebx5vUhDydSCG1w2yTgG8ozyFEKpjWnIerlZwvcRhn9jBadBRi5p0wPfAlt%2FJjx4Z7xXOyTQmTUqEi2uMhpCZFNsWwIStOV5F7qEpkiq49Ooyfz3dRCTBRoc%2BwPJNNWZHjE0yF3iboxHjOt8S7VX0LYJTgys3NylaaLb8v7NCXnM9MjrcxhxSVY5zuGVxN324fuiZAdLSq4aPslbAwOD%2BS …
=> fix: comment preserver should be placed prior to inline globals

website/docs/en/api/modules/module-methods.mdx, website/docs/en/api/modules/module-variables.mdx
=> docs: fix modules docs crash

x.mjs
=> chore: add x test plugin

.github/workflows/ci.yml, .github/workflows/diff.yml.bak, .github/workflows/ecosystem-ci-trigger.yml, .github/workflows/github-issue-sync.yml, .github/workflows/release-nightly.yml
=> chore: remove tokens

website/components/ApiMeta.tsx
=> docs: fix ApiMeta component href

.github/pr-labeler.yml, .github/release.yml
=> chore: add tag to docs pr and release note

website/docs/en/guide/features/plugin.mdx
* Improve docs for plugins guide
* Add links to supported plugins
=> docs: update guide plugins

website/docs/en/guide/features/plugin.mdx, website/docs/zh/guide/features/plugin.mdx
- Translate https://github.com/web-infra-dev/rspack/pull/6466 to Chinese.
- Improve the typography of plugin guide.
=> docs(zh): update guide plugins

website/docs/zh/config/output.mdx
small typo
https://www.rspack.dev/zh/config/output#outputlibrarytarget
=> docs: remove inconsistent title

website/components/CommunityCompatibleTable.tsx, website/components/PluginSupportStatusTable.module.scss, website/components/PluginSupportStatusTable.tsx, website/components/builtIns/mdx-components.tsx, website/components/i18n/en.json, website/components/i18n/zh.json
Improve compat table style:
- Before:
- After:
Ref: https://github.com/web-infra-dev/rspack/pull/6476
=> docs: improve compat table style

packages/rspack-test-tools/tests/configCases/plugins/chunk-group-chunks/test.config.js, packages/rspack-test-tools/tests/configCases/plugins/chunk-group-chunks/webpack.config.js, packages/rspack/etc/api.md, packages/rspack/src/ChunkGroup.ts
=> feat: compat chunkGroup.chunks

website/components/CommunityCompatibleTable.tsx, website/components/i18n/en.json, website/components/i18n/zh.json
Updated plugin compatibility list, and some `resolve plugin` not supported.
=> docs: `resolve plugin` not supported

README.md, README.zh-CN.md, website/docs/en/guide/compatibility/plugin.mdx, website/docs/en/plugins/index.mdx, website/docs/zh/guide/compatibility/plugin.mdx, website/docs/zh/plugins/index.mdx, website/theme/components/HomeFooter/index.tsx
Add some links for awesome-rspack, so that users can find the resources or plugins they need.
https://github.com/web-infra-dev/awesome-rspack
=> docs: add some links for awesome-rspack

crates/rspack_core/src/compiler/make/cutout/clean_isolated_module.rs, crates/rspack_core/src/compiler/make/cutout/mod.rs, crates/rspack_core/src/compiler/make/file_counter.rs, crates/rspack_core/src/compiler/make/mod.rs, crates/rspack_core/src/compiler/make/repair/build.rs, crates/rspack_core/src/compiler/make/repair/factorize.rs, crates/rspack_core/src/compiler/make/repair/mod.rs, crates/rspack_core/src/compiler/module_executor/mod.rs
=> fix: make *_dependencies memory leak

website/components/CommunityCompatibleTable.tsx
add vanilla-extract supported, see https://github.com/web-infra-dev/rspack/issues/2845
=> docs: add vanilla-extract supported

.github/workflows/release-canary.yml
=> ci: release canary by dispatch

.github/workflows/issue-pr-trigger.yml
=> ci: contribution hook

website/docs/zh/plugins/webpack/ignore-plugin.mdx
=> docs: fix wrong heading

website/components/PluginSupportStatusTable.tsx
after:
It should be noted that some plugins supported by Rspack lack documentation.
=> docs: add webpack-aligned plugin link

CONTRIBUTING.md, website/components/RandomMemberList.tsx, website/docs/en/blog/announcing-0-4.mdx, website/docs/en/config/experiments.mdx, website/docs/en/contribute/architecture/builtin-plugin.md, website/docs/en/contribute/architecture/rspack-loader.md, website/docs/en/contribute/development/building.md, website/docs/en/contribute/development/debugging.md, website/docs/en/contribute/development/prerequisites.md, website/docs/en/contribute/index.mdx, website/docs/en/misc/planning/future.mdx, website/docs/zh/blog/announcing-0-2.mdx, website/docs/zh/blog/announcing-0-4.mdx, website/docs/zh/config/experiments.mdx
- update outdated links and contents in dev guide
- update CONTRIBUTING.md and link to the new dev guide
- update Node.js version requirements
=> docs: update outdated links and contents in dev guide

packages/rspack-test-tools/etc/api.md, packages/rspack-test-tools/src/case/hook.ts, packages/rspack-test-tools/src/processor/hook.ts, packages/rspack-test-tools/tests/hookCases/compilation#afterProcessAssets/basic/test.js, packages/rspack-test-tools/tests/hookCases/compilation#processAssets/update-asset/hooks.snap.txt, packages/rspack-test-tools/tests/hookCases/compilation#processAssets/update-asset/output.snap.txt, packages/rspack-test-tools/tests/hookCases/compilation#processAssets/update-asset/test.js, packages/rspack-test-tools/tests/hookCases/compiler#assetEmitted/basic/test.js, packages/rspack-test-tools/tests/hookCases/normalModuleFactory#afterResolve/duplicate/test.js, packages/rspack-test-tools/tests/hookCases/normalModuleFactory#afterResolve/request/test.js, packages/rspack-test-tools/tests/hookCases/normalModuleFactory#afterResolve/resource/test.js
- Fix compiler and check method of hook cases
- Add type comments of hook cases
=> test: add type of hook cases

website/components/CommunityCompatibleTable.tsx, website/components/i18n/en.json, website/components/i18n/zh.json, website/project-words.txt
list `node-polyfill-webpack-plugin` / `workbox-webpack-plugin` / `@pmmmwh/react-refresh-webpack-plugin` compatibility status in Rspack.
=> docs: list workbox & react-refresh webpack plugin compatibility status

.github/workflows/issue-pr-trigger.yml
- Not send message to lark when github.actor is renovate
=> ci: renovate lark trigger

Cargo.lock, Cargo.toml, crates/node_binding/binding.d.ts, crates/rspack_binding_options/Cargo.toml, crates/rspack_binding_options/src/options/mod.rs, crates/rspack_binding_options/src/options/raw_experiments.rs, crates/rspack_binding_options/src/options/raw_optimization.rs, crates/rspack_core/src/options/experiments.rs, packages/rspack-test-tools/tests/__snapshots__/Defaults.test.js.snap, packages/rspack/etc/api.md, packages/rspack/src/config/adapter.ts, packages/rspack/src/config/defaults.ts, packages/rspack/src/config/normalization.ts, packages/rspack/src/config/zod.ts
=> chore: remove new split chunks options

Cargo.lock, packages/rspack-test-tools/tests/builtinCases/plugin-css-modules/modules-composes/snapshot/output.snap.txt
=> chore: revert cargo lock to fix ci

website/components/CommunityCompatibleTable.tsx, website/components/i18n/en.json, website/components/i18n/zh.json
mark some `Incompatible` plugins `Alternative`
=> docs: mark some `Incompatible` plugins `Alternative`

.github/workflows/release.yml
=> ci: support release beta version

crates/node_binding/package.json, npm/darwin-arm64/package.json, npm/darwin-x64/package.json, npm/linux-x64-gnu/package.json, npm/win32-x64-msvc/package.json, package.json, packages/create-rspack/package.json, packages/rspack-cli/package.json, packages/rspack-dev-server/package.json, packages/rspack-plugin-minify/package.json, packages/rspack-plugin-react-refresh/package.json, packages/rspack-test-tools/package.json, packages/rspack/package.json
see changelog: https://github.com/web-infra-dev/rspack/releases/tag/v0.7.0-beta.0
=> release: v0.7.0-beta.0

.github/workflows/release-canary.yml, website/docs/en/contribute/development/releasing.md
- Remove !canary in contribute guide
=> docs: remove canary comment release in contribute guide

crates/node_binding/binding.d.ts, crates/rspack_binding_options/src/options/raw_module/mod.rs, crates/rspack_core/src/options/module.rs, crates/rspack_plugin_css/src/parser_and_generator/mod.rs, crates/rspack_plugin_css/src/plugin/impl_plugin_for_css_plugin.rs, packages/rspack-test-tools/tests/__snapshots__/Defaults.test.js.snap, packages/rspack-test-tools/tests/defaultsCases/experiments/future-defaults-with-css.js, packages/rspack/etc/api.md, packages/rspack/src/config/adapter.ts, packages/rspack/src/config/defaults.ts, packages/rspack/src/config/zod.ts, website/docs/en/config/module.mdx, website/docs/zh/config/module.mdx
checkout https://github.com/webpack/webpack/pull/18341
=> chore: remove exportsConvention for css generator

crates/rspack_core/src/compiler/module_executor/ctrl.rs
for example: CommonJsSelfReferenceDependency
=> fix: finish_module_task skip self reference connection

packages/rspack-test-tools/package.json, pnpm-lock.yaml
=> test: fix dependencies of test tools

website/components/CommunityCompatibleTable.tsx
https://github.com/orgs/webpack-contrib/repositories
=> docs: list more webpack-contrib plugins compatible

packages/rspack-test-tools/etc/api.md, packages/rspack-test-tools/src/case/defaults.ts, packages/rspack-test-tools/src/case/error.ts, packages/rspack-test-tools/src/case/stats-api.ts, packages/rspack-test-tools/src/helper/legacy/createFakeWorker.js, packages/rspack-test-tools/src/helper/legacy/createLazyTestEnv.js, packages/rspack-test-tools/src/processor/defaults.ts, packages/rspack-test-tools/src/processor/diagnostic.ts, packages/rspack-test-tools/src/processor/error.ts, packages/rspack-test-tools/src/processor/hash.ts, packages/rspack-test-tools/src/processor/hook.ts, packages/rspack-test-tools/src/processor/hot-step.ts, packages/rspack-test-tools/src/processor/snapshot.ts, packages/rspack-test-tools/src/processor/stats-api.ts, packages/rspack-test-tools/src/processor/stats.ts, packages/rspack-test-tools/src/runner/runner/cjs.ts, packages/rspack-test-tools/src/runner/runner/web/fake.ts, packages/rspack-test-tools/src/runner/runner/web/jsdom.ts, packages/rspack-test-tools/src/runner/type.ts, packages/rspack-test-tools/src/test/creator.ts, packages/rspack-test-tools/src/test/simple.ts, packages/rspack-test-tools/src/type.ts, packages/rspack-test-tools/tests/Defaults.test.js
- pass expect in test env to make processors work without jest
=> test: pass expect in test env

crates/node_binding/package.json, npm/darwin-arm64/package.json, npm/darwin-x64/package.json, npm/linux-x64-gnu/package.json, npm/win32-x64-msvc/package.json, package.json, packages/create-rspack/package.json, packages/rspack-cli/package.json, packages/rspack-dev-server/package.json, packages/rspack-plugin-minify/package.json, packages/rspack-plugin-react-refresh/package.json, packages/rspack-test-tools/package.json, packages/rspack/package.json
https://github.com/web-infra-dev/rspack/releases/tag/v0.7.0-beta.1
=> release: 0.7.0-beta.1

packages/rspack-test-tools/src/runner/hot-step.ts, packages/rspack-test-tools/tests/hotCases/css/recovery/__snapshots__/web/2.snap.txt, packages/rspack-test-tools/tests/hotCases/css/recovery/index.js
- fix error recovery checker of hot snapshot runner
=> test: fix hot snapshot recovery checker

packages/rspack-test-tools/etc/api.md, packages/rspack-test-tools/src/case/diff.ts, packages/rspack-test-tools/src/case/stats-output.ts, packages/rspack-test-tools/src/helper/directory.ts, packages/rspack-test-tools/src/processor/hot-step.ts, packages/rspack-test-tools/src/processor/hot.ts, packages/rspack-test-tools/src/processor/stats.ts, packages/rspack-test-tools/src/runner/runner/basic.ts, packages/rspack-test-tools/tests/__snapshots__/StatsOutput.test.js.snap, packages/rspack-test-tools/tests/compilerCases/splitchunks-minchunks.js, packages/rspack-test-tools/tests/hotCases/chunk/issue-4476/file.js, packages/rspack-test-tools/tests/hotCases/chunk/multi-chunk-single-runtime/file.js, packages/rspack-test-tools/tests/hotCases/chunk/multi-chunk-single-runtime/main/index.js, packages/rspack-test-tools/tests/hotCases/chunk/multi-chunk/file.js, packages/rspack-test-tools/tests/hotCases/newTreeshaking/multi-chunk-single-runtime/file.js, packages/rspack-test-tools/tests/hotCases/runtime/dispose-removed-chunk/a.js, packages/rspack-test-tools/tests/hotCases/runtime/update-multiple-times/file.js
- make sure hot test can run all steps
- use full relative path as case name to prevent conflict
=> test: check hot step match

website/components/CommunityCompatibleTable.tsx, website/components/i18n/en.json, website/components/i18n/zh.json
`moment-locales-webpack-plugin` is supported and will be available in the next version of rspack (v0.7.0).
https://github.com/web-infra-dev/rspack/issues/6373
=> docs: add moment-locales-webpack-plugin support status

website/docs/en/blog/announcing-0-7.mdx, website/docs/zh/blog/announcing-0-7.mdx
=> docs: remove snapshot

website/docs/en/contribute/development/debugging.mdx, website/docs/zh/contribute/development/debugging.mdx, website/docs/zh/contribute/index.mdx
video link does not take effect in md file.
before
after
=> docs: fix the video component in md

website/docs/en/config/experiments.mdx, website/docs/zh/config/experiments.mdx
Add example and explanation for lazy compilation with custom global entry
=> docs: example for lazy compilation with custom global entry

crates/node_binding/package.json, npm/darwin-arm64/package.json, npm/darwin-x64/package.json, npm/linux-x64-gnu/package.json, npm/win32-x64-msvc/package.json, package.json, packages/create-rspack/package.json, packages/rspack-cli/package.json, packages/rspack-dev-server/package.json, packages/rspack-plugin-minify/package.json, packages/rspack-plugin-react-refresh/package.json, packages/rspack-test-tools/package.json, packages/rspack/package.json
https://github.com/web-infra-dev/rspack/releases/tag/v0.7.0-beta.2
=> release: 0.7.0-beta.2

packages/rspack-test-tools/etc/api.md, packages/rspack-test-tools/src/processor/basic.ts, packages/rspack-test-tools/src/processor/diff.ts, packages/rspack-test-tools/src/test/creator.ts, packages/rspack-test-tools/src/test/simple.ts, packages/rspack-test-tools/src/test/tester.ts, packages/rspack-test-tools/src/type.ts, packages/rspack-test-tools/tests/compilerCases/splitchunks-minchunks.js
Handle test error:
- Errors occured while running the compile will be saved into the test context.
- Errors occured while building will be in stats.
- Check method of basic processor should check both two type of errors.
- Other processors should handle error by themself. 
- Only if test case finished and there is error remained in context, error will be print and the case failed.
=> test: handle test error more friendly

website/package.json, website/pnpm-lock.yaml, website/theme/index.tsx, website/tsconfig.json
- Enable MDX type hints to improve the DX:
see: https://github.com/mdx-js/mdx-analyzer?tab=readme-ov-file#typescript
- Bump Rspress packages
- Remove `@modern-js/tsconfig` dependency
=> chore(workflow): enable MDX type hints

website/components/CommunityCompatibleTable.tsx, website/components/i18n/en.json, website/components/i18n/zh.json
=> docs: list more plugins compatible status

crates/node_binding/binding.d.ts, crates/rspack_binding_options/src/options/raw_builtins/raw_banner.rs, crates/rspack_plugin_banner/src/lib.rs, packages/rspack-test-tools/tests/configCases/builtins/banner-stage/a.js, packages/rspack-test-tools/tests/configCases/builtins/banner-stage/b.js, packages/rspack-test-tools/tests/configCases/builtins/banner-stage/index.js, packages/rspack-test-tools/tests/configCases/builtins/banner-stage/rspack.config.js, packages/rspack-test-tools/tests/configCases/builtins/banner-stage/test.config.js, packages/rspack/etc/api.md, packages/rspack/src/builtin-plugin/BannerPlugin.ts, website/docs/en/plugins/webpack/banner-plugin.mdx, website/docs/zh/plugins/webpack/banner-plugin.mdx
=> feat: support `stage` option of `BannerPlugin`

packages/rspack-test-tools/etc/api.md, packages/rspack-test-tools/src/compiler.ts, packages/rspack-test-tools/src/runner/runner/basic.ts, packages/rspack-test-tools/src/test/context.ts, packages/rspack-test-tools/src/type.ts
- Allow to change compiler factories for custom required webpack&rspack
=> test: add custom compiler factories in context

webpack-test/configCases/split-chunks/chunk-filename-delimiter-default/test.filter.js, webpack-test/configCases/split-chunks/runtime-chunk-async-node/test.filter.js, webpack-test/configCases/split-chunks/runtime-chunk-node-13130/test.filter.js, webpack-test/configCases/split-chunks/runtime-chunk-node/test.filter.js
close #4342
close #4334
enable more webpack tests
=> chore: enable more tests

Cargo.lock, Cargo.toml
update swc_core and swc_minifier
=> chore: update swc-minifier

website/rspress.config.ts
=> docs: fix og image URL

crates/rspack_core/src/compiler/compilation.rs, crates/rspack_core/src/compiler/hmr.rs, crates/rspack_plugin_javascript/src/dependency/esm/harmony_import_specifier_dependency.rs
=> chore: cleanup compilation struct

website/docs/en/blog/announcing-0-7.mdx, website/docs/en/config/experiments.mdx, website/docs/zh/blog/announcing-0-7.mdx, website/docs/zh/config/experiments.mdx
Improve lazy compilation document:
- Add basic example
- improve build performance -> improve dev startup performance
=> docs: improve lazy compilation document

website/docs/en/index.md, website/docs/zh/index.md, website/theme/components/HomeFooter/index.tsx
https://github.com/web-infra-dev/rspack/issues/6651
The Webpack Compatible link should be changed.
=> docs: change compatibility link

website/docs/en/config/module.mdx
* improve documentation for `module.generator["css/auto"].esModule`
* fix version reference for configuration of
* `module.generator["css/auto"].esModule`
*  `module.generator.css.esModule`
* `module.generator["css/module"].esModule`
=> docs: update esModule generator description & version

website/rspress.config.ts
Display edit link in the footer to help documentation contribution.
=> docs: display edit link in the footer

CONTRIBUTING.md, website/docs/en/contribute/index.mdx, website/docs/zh/contribute/index.mdx
- Github -> GitHub
- repack -> Repack
=> docs: correct GitHub spelling

packages/playground/playwright.config.ts
=> chore: fix testDir

packages/rspack-cli/src/rspack-cli.ts, packages/rspack-cli/src/utils/options.ts, packages/rspack-cli/src/utils/profile.ts
=> refactor(cli): Reduce some additional judgments and branch conditions

scripts/release/version.mjs
make canary version match [semver spec](https://semver.org/#spec-item-11)
resolve https://github.com/web-infra-dev/rspack/issues/6438
=> ci: incremental patch version when release canary and nightly

crates/rspack_core/src/compiler/compilation.rs, crates/rspack_core/src/dependency/dependency_trait.rs, crates/rspack_plugin_javascript/src/dependency/esm/harmony_export_imported_specifier_dependency.rs, crates/rspack_plugin_javascript/src/dependency/esm/harmony_import_specifier_dependency.rs
=> perf: parallel collect export presence diagnostics

crates/node_binding/binding.d.ts, crates/rspack_binding_options/src/options/raw_builtins/mod.rs, crates/rspack_ids/src/lib.rs, crates/rspack_ids/src/natural_chunk_ids_plugin.rs, packages/rspack-test-tools/tests/__snapshots__/StatsOutput.test.js.snap, packages/rspack-test-tools/tests/statsOutputCases/optimization-chunk-ids-natural/e1.js, packages/rspack-test-tools/tests/statsOutputCases/optimization-chunk-ids-natural/e2.js, packages/rspack-test-tools/tests/statsOutputCases/optimization-chunk-ids-natural/modules/a.js, packages/rspack-test-tools/tests/statsOutputCases/optimization-chunk-ids-natural/modules/b.js, packages/rspack-test-tools/tests/statsOutputCases/optimization-chunk-ids-natural/modules/c.js, packages/rspack-test-tools/tests/statsOutputCases/optimization-chunk-ids-natural/rspack.config.js, packages/rspack/etc/api.md, packages/rspack/src/builtin-plugin/NaturalChunkIdsPlugin.ts, packages/rspack/src/builtin-plugin/index.ts, packages/rspack/src/config/defaults.ts, packages/rspack/src/config/zod.ts, packages/rspack/src/rspackOptionsApply.ts, website/components/PluginSupportStatusTable.tsx
Add [`optimization.chunkIds: 'natural'`](https://webpack.js.org/configuration/optimization/#optimizationchunkids).
The default value is kept to be `'named'`.
close: https://github.com/web-infra-dev/rspack/issues/4823
=> feat: add `optimization.chunkIds: 'natural'`

website/components/PluginSupportStatusTable.tsx
The `stage` of `BannerPlugin` is supported in #6623. Change it to `FullySupported`.
=> docs: update support status of `BannerPlugin`

website/docs/en/config/module.mdx, website/docs/zh/config/module.mdx
Translate https://github.com/web-infra-dev/rspack/pull/6686 to Chinese.
=> docs: translate exportsOnly description

Cargo.lock, Cargo.toml
fix #6687
https://github.com/ahabhgk/css-module-lexer/commit/f77b6c6cfed7745f02d66c1732edbebbb1f277ca
=> fix: local class with charset

crates/rspack_core/src/dependency/span.rs, crates/rspack_plugin_javascript/src/parser_and_generator/mod.rs, crates/rspack_plugin_javascript/src/parser_plugin/compatibility_plugin.rs
- Moved shebang commenting to `CompatibilityPlugin`
=> refactor: cleanup JavaScript parsing 2

packages/rspack-test-tools/tests/hotCases/css/css-extract/index.css, packages/rspack-test-tools/tests/hotCases/css/css-extract/index.js, packages/rspack-test-tools/tests/hotCases/css/css-extract/rspack.config.js
=> test: pass through cacheable

crates/rspack_core/src/dependency/runtime_template.rs, crates/rspack_core/src/init_fragment.rs, crates/rspack_plugin_javascript/src/dependency/esm/harmony_import_dependency.rs, crates/rspack_plugin_javascript/src/dependency/esm/harmony_import_specifier_dependency.rs, crates/rspack_plugin_javascript/src/dependency/pure_expression_dependency.rs, crates/rspack_plugin_javascript/src/plugin/inner_graph_plugin.rs
=> fix: correct runtime condition expression

packages/rspack-test-tools/etc/api.md, packages/rspack-test-tools/src/processor/basic.ts, packages/rspack-test-tools/src/processor/hot-step.ts, packages/rspack-test-tools/src/runner/basic.ts, packages/rspack-test-tools/src/runner/hot-step.ts, packages/rspack-test-tools/src/runner/hot.ts, packages/rspack-test-tools/src/runner/runner/basic.ts, packages/rspack-test-tools/src/runner/runner/web.ts, packages/rspack-test-tools/src/runner/runner/web/jsdom.ts, packages/rspack-test-tools/src/test/creator.ts, packages/rspack-test-tools/src/test/tester.ts, packages/rspack-test-tools/src/type.ts
=> test: enable jsdom runner by default

crates/rspack_core/src/build_chunk_graph/code_splitter.rs
`changed` and `updated` can be unexpectedly re-assign
=> fix: code splitting won't invalidate in some cases

website/docs/en/api/modules/module-methods.mdx, website/docs/zh/api/modules/module-methods.mdx
rewrite document for `require.context()`, as I find the current documentation incomplete and misleading
=> docs: rewrite document for require.context()

crates/rspack_plugin_css/src/parser_and_generator/mod.rs, crates/rspack_util/src/fx_hash.rs, packages/rspack-test-tools/tests/configCases/css/override-exports/index.js, packages/rspack-test-tools/tests/configCases/css/override-exports/index.module.css, packages/rspack-test-tools/tests/configCases/css/override-exports/rspack.config.js
fix override existing css exports, checkout the test case
=> fix: override existing css exports

website/package.json, website/pnpm-lock.yaml
Bump Rspress v1.23.1 to improve container style
- before:
- after:
> https://github.com/web-infra-dev/rspress/releases
=> docs: bump Rspress to improve container style

Cargo.lock, Cargo.toml
https://github.com/ahabhgk/css-module-lexer/commit/ce756dee3016d5b33cf1b5f5933ceb7318a857ba
=> fix: should clear local classes for invalid composes

crates/rspack_binding_options/src/options/raw_module/mod.rs, crates/rspack_core/src/options/module.rs, crates/rspack_core/src/utils/module_rules.rs, packages/rspack-test-tools/tests/configCases/module/rspack-issue-6739/empty-loader.js, packages/rspack-test-tools/tests/configCases/module/rspack-issue-6739/index.js, packages/rspack-test-tools/tests/configCases/module/rspack-issue-6739/loader.js, packages/rspack-test-tools/tests/configCases/module/rspack-issue-6739/node_modules/bar/package.json, packages/rspack-test-tools/tests/configCases/module/rspack-issue-6739/node_modules/foo/package.json, packages/rspack-test-tools/tests/configCases/module/rspack-issue-6739/rspack.config.js
closes https://github.com/web-infra-dev/rspack/issues/6739
=> fix: `Rule.descriptionData` won't match object types

packages/rspack-test-tools/jest.config.js, packages/rspack-test-tools/package.json, packages/rspack-test-tools/src/helper/expect/to-be-typeof.ts, packages/rspack-test-tools/src/helper/expect/to-end-with.ts, packages/rspack-test-tools/src/helper/expect/to-match-file-snapshot.ts, packages/rspack-test-tools/src/helper/setup-env.ts, packages/rspack-test-tools/src/helper/setup-expect.ts
export setup for plugin testing
=> test: export setup for plugin testing

webpack-test/hotCases/conditional-runtime/accept-conditional/test.filter.js
=> chore: enable runtime condition webpack-test

crates/rspack_core/src/compiler/make/cutout/has_module_graph_change.rs, crates/rspack_core/src/compiler/make/cutout/mod.rs
=> fix: has_module_graph_change miscalculation

crates/rspack_core/src/build_chunk_graph/code_splitter.rs, packages/rspack-test-tools/tests/statsAPICases/verbose-time.js
=> perf: code splitter

crates/rspack_core/src/build_chunk_graph/code_splitter.rs
When removing skipped_connections, remove from left to right is wrong
=> fix: should remove correct connections

crates/rspack_plugin_javascript/src/dependency/context/require_context_dependency.rs, packages/rspack-test-tools/tests/diagnosticsCases/factorize/cannot-resolve-context/index.js, packages/rspack-test-tools/tests/diagnosticsCases/factorize/cannot-resolve-context/stats.err
fix #6735 and #6474
align code generation of require context dependency with runtime template
=> fix: panic when resolve context failed

crates/node_binding/binding.d.ts, crates/rspack_binding_options/src/options/raw_builtins/raw_progress.rs, crates/rspack_plugin_progress/src/lib.rs, packages/rspack/src/builtin-plugin/ProgressPlugin.ts, website/docs/en/plugins/webpack/progress-plugin.mdx, website/docs/zh/plugins/webpack/progress-plugin.mdx, website/project-words.txt
Related: https://github.com/web-infra-dev/rspack/issues/6632
TODOs:
=> feat: `ProgressPlugin` configuration

crates/rspack_core/src/external_module.rs, packages/rspack-test-tools/tests/configCases/concatenate-modules/with-externals/index.js, packages/rspack-test-tools/tests/configCases/concatenate-modules/with-externals/rspack.config.js, packages/rspack-test-tools/tests/configCases/library/esm-external/index.js, packages/rspack-test-tools/tests/hookCases/normalModuleFactory#afterResolve/duplicate/output.snap.txt, packages/rspack-test-tools/tests/hookCases/normalModuleFactory#afterResolve/request/output.snap.txt, packages/rspack-test-tools/tests/hookCases/normalModuleFactory#afterResolve/resource/output.snap.txt
fix using `concatenationModules: true` with externals, before will panic
=> fix: concatenate module with external

packages/rspack-test-tools/src/helper/replace-paths.ts
=> chore: remove console.log in replacePaths

crates/rspack_plugin_mf/src/container/expose_runtime_module.rs, crates/rspack_plugin_mf/src/container/remote_runtime_module.rs, crates/rspack_plugin_mf/src/sharing/consume_shared_runtime_module.rs, crates/rspack_plugin_mf/src/sharing/provide_shared_plugin.rs, crates/rspack_plugin_mf/src/sharing/share_runtime_module.rs
=> fix(mf): avoid error __webpack_require__.f.consume after hmr

.github/teams.yml
=> chore: add congcong to team member list

crates/rspack_plugin_css/src/parser_and_generator/mod.rs, packages/rspack-test-tools/tests/configCases/css/css-modules-composes-same-ident/index.js, packages/rspack-test-tools/tests/configCases/css/css-modules-composes-same-ident/index.module.css, packages/rspack-test-tools/tests/configCases/css/css-modules-composes-same-ident/input.module.css, packages/rspack-test-tools/tests/configCases/css/css-modules-composes-same-ident/rspack.config.js, website/docs/en/config/module.mdx
=> fix: css modules composes same ident with local class

packages/rspack/src/builtin-plugin/BundlerInfoRspackPlugin.ts
Enabling wappalyzer to find rspack.
=> feat(runtime): enable rspack version

packages/rspack/scripts/check-documentation-coverage.mjs, website/docs/en/config/experiments.mdx, website/docs/en/config/externals.mdx, website/docs/en/config/optimization.mdx, website/docs/en/config/output.mdx, website/docs/zh/config/experiments.mdx, website/docs/zh/config/externals.mdx, website/docs/zh/config/optimization.mdx, website/docs/zh/config/output.mdx
complete experiments docs, such as `experiments.rspackFuture`.
=> docs: complete experiments docs

lint-staged.config.mjs, x.mjs
=> fix: generate suggestions if api-extractor failed the test

packages/rspack-cli/src/commands/build.ts
Let `@rspack/cli` close compiler after building.
- close https://github.com/web-infra-dev/rspack/issues/6833
- close https://github.com/web-infra-dev/rspack/issues/6675
- https://webpack.js.org/blog/2020-10-10-webpack-5-release/#compiler-idle-and-close
- https://github.com/web-infra-dev/rsbuild/blob/f6217a6daf70ab3ffa3161e0220b9508d8d8cf5a/packages/core/src/provider/build.ts#L75
=> fix(cli): should close compiler after building

packages/rspack/etc/api.md, packages/rspack/src/Chunk.ts, packages/rspack/src/ChunkGraph.ts, packages/rspack/src/ChunkGroup.ts, packages/rspack/src/Compilation.ts, packages/rspack/src/Compiler.ts, packages/rspack/src/ContextModuleFactory.ts, packages/rspack/src/Entrypoint.ts, packages/rspack/src/FileSystem.ts, packages/rspack/src/Module.ts, packages/rspack/src/RuleSetCompiler.ts
=> refactor: cleanup JavaScript API

packages/rspack/scripts/check-documentation-coverage.mjs
=> fix: docs ci wrong in node 16

Cargo.lock, Cargo.toml, crates/rspack_plugin_devtool/src/lib.rs
=> fix: source map wrong when columns is false

packages/rspack/scripts/check-documentation-coverage.mjs, website/docs/en/config/module.mdx, website/docs/en/config/node.mdx, website/docs/zh/config/module.mdx, website/docs/zh/config/node.mdx
=> docs: complete module docs

packages/rspack-test-tools/tests/__snapshots__/Defaults.test.js.snap, packages/rspack/scripts/check-documentation-coverage.mjs, packages/rspack/src/config/defaults.ts, website/docs/en/config/output.mdx, website/docs/zh/config/output.mdx
=> fix: sourceMapFilename default value

crates/rspack_core/src/module_graph/mod.rs
fix https://github.com/web-infra-dev/rspack/issues/6844
=> fix: panic of module_graph.get_depth

website/docs/en/guide/tech/_meta.json, website/docs/en/guide/tech/preact.mdx, website/docs/zh/guide/tech/_meta.json, website/docs/zh/guide/tech/preact.mdx
- Add guides of preact and preact-refresh
=> docs: add preact refresh

crates/rspack_plugin_javascript/src/visitors/dependency/parser/walk.rs, packages/rspack-test-tools/tests/normalCases/parsing/pre-walk-class-block/a.js, packages/rspack-test-tools/tests/normalCases/parsing/pre-walk-class-block/index.js
should pre walk class blocks to define 'var'
=> fix: pre walk class blocks
