crates/rspack_core/src/compiler/compilation.rs, crates/rspack_core/src/compiler/make/mod.rs, crates/rspack_core/src/compiler/make/repair/add.rs, crates/rspack_core/src/compiler/make/repair/build.rs, crates/rspack_core/src/compiler/make/repair/factorize.rs, crates/rspack_core/src/compiler/make/repair/mod.rs, crates/rspack_core/src/compiler/make/repair/process_dependencies.rs, crates/rspack_core/src/compiler/module_executor/ctrl.rs, crates/rspack_core/src/compiler/module_executor/entry.rs, crates/rspack_core/src/compiler/module_executor/mod.rs
This PR makes it clearer and easier to modify the module graph.
* `make_module_graph` will collect make_params and call `update_module_graph` to regenerate module_graph, and it will only use immutable compilation
* `update_module_graph` will regenerate module_graph by make_params, and it will only use immutable compilation
=> refactor: make_module_graph use immutable compilation

crates/rspack_core/src/compiler/module_executor/mod.rs, crates/rspack_core/src/dependency/entry.rs, crates/rspack_plugin_dynamic_entry/src/lib.rs, crates/rspack_plugin_entry/src/lib.rs, crates/rspack_plugin_lazy_compilation/src/plugin.rs, packages/playground/cases/lazy-compilation/ignore-entry/index.test.ts, packages/playground/cases/lazy-compilation/ignore-entry/rspack.config.js, packages/playground/cases/lazy-compilation/ignore-entry/src/index.js, packages/playground/playwright.config.ts
lazy compilation ignore global entry, so that react-refresh entry and hmr entry can be applied correctly
=> feat: lazy compilation ignore global entry

crates/rspack_core/src/compiler/compilation.rs, crates/rspack_core/src/compiler/make/cutout/mod.rs, crates/rspack_core/src/compiler/make/mod.rs, crates/rspack_core/src/compiler/module_executor/mod.rs, crates/rspack_core/src/module.rs
* split module.is_available to module.need_build and module.depends_on
* add more MakeParams and regenerate module_graph after finish make
=> refactor: regenerate module_graph after finish make

Cargo.lock, crates/rspack_core/src/utils/mod.rs, crates/rspack_plugin_extract_css/Cargo.toml, crates/rspack_plugin_extract_css/src/runtime.rs, crates/rspack_plugin_runtime/src/array_push_callback_chunk_format.rs, plugin-test/css-extract/cases/issue-6649/expected/main.js, plugin-test/css-extract/cases/issue-6649/src/chunk.js, plugin-test/css-extract/cases/issue-6649/src/index.js, plugin-test/css-extract/cases/issue-6649/src/inject.css, plugin-test/css-extract/cases/issue-6649/webpack.config.js
fix #6649
- wrap chunk id with `"{}"` will encouter the unicode issue
- chunk id should render with `serde_json::to_string`
=> fix: installedCssChunks unicode error on windows

crates/rspack_plugin_javascript/src/parser_plugin/define_plugin.rs, crates/rspack_plugin_javascript/src/visitors/semicolon.rs, packages/rspack-test-tools/tests/builtinCases/plugin-javascript/builtins-define/__snapshots__/output.snap.txt, packages/rspack-test-tools/tests/configCases/builtins/define/index.js, packages/rspack-test-tools/tests/configCases/builtins/define/rspack.config.js, packages/rspack-test-tools/tests/normalCases/parsing/asi/a.js, packages/rspack-test-tools/tests/normalCases/parsing/asi/index.js, plugin-test/css-extract/cases/issue-6649/expected/main.js
- Fixed a case where semicolon is not inserted after a variable declaration
- Fixed a case of define plugin using with object
=> fix: should insert semi after variable decl

packages/rspack-test-tools/tests/configCases/builtin-swc-loader/source-map/index.js, packages/rspack-test-tools/tests/configCases/source-map/source-map/index.js
Since we have https://github.com/web-infra-dev/rspack/pull/6554, so this PR (Previously, entry module is not the last one, making the result unpredictable)
=> refactor: cleanup source-map stub

crates/rspack_plugin_lazy_compilation/src/dependency.rs, crates/rspack_plugin_lazy_compilation/src/module.rs, crates/rspack_plugin_lazy_compilation/src/plugin.rs, packages/playground/cases/lazy-compilation/ignore-entry/rspack.config.js, packages/playground/package.json, pnpm-lock.yaml
close: #6701
LazyCompilation utilizes the nmf hook to enable normal module creation. Therefore, we must determine if a module has already undergone lazy compilation before utilizing dependency.request() with the string 'lazy-compilation-proxy-dep'. However, this method is not optimal; instead, we can identify the type of dependency. Additionally, the generated code should escape the quote character.
=> fix: lazy compilation should escape data uri and should not rely on dependency request

crates/rspack_core/src/compiler/compilation.rs, crates/rspack_core/src/compiler/make/mod.rs, crates/rspack_core/src/compiler/make/repair/add.rs, crates/rspack_core/src/compiler/make/repair/factorize.rs, crates/rspack_core/src/compiler/make/repair/mod.rs, crates/rspack_core/src/compiler/make/repair/process_dependencies.rs, crates/rspack_core/src/compiler/module_executor/entry.rs
We collect entry_modules in make addTask, which needs to pass is_entry in multiple tasks. This PR will calculate entry_modules via entry_deps.
=> refactor: entry_modules calculate by entry_deps

website/docs/en/guide/features/module-federation.mdx, website/docs/en/plugins/webpack/module-federation-plugin-v1.mdx, website/docs/en/plugins/webpack/module-federation-plugin.mdx, website/docs/zh/guide/features/module-federation.mdx, website/docs/zh/plugins/webpack/module-federation-plugin-v1.mdx, website/docs/zh/plugins/webpack/module-federation-plugin.mdx
Update Module Federation guide:
- Add Module Federation v2
- Add some comparisons
- Add some basic examples
- No longer recommend to use Module Federation v1.0
=> docs: update Module Federation guide

Cargo.lock, crates/node_binding/binding.d.ts, crates/rspack_binding_values/Cargo.toml, crates/rspack_binding_values/src/asset.rs, crates/rspack_core/src/compiler/compilation.rs, packages/rspack-cli/tests/build/basic/public/main.js.map, packages/rspack-test-tools/tests/compilerCases/assets-update-info.js, packages/rspack/etc/api.md, packages/rspack/src/Compilation.ts, packages/rspack/src/util/AssetInfo.ts, packages/rspack/src/util/index.ts
- compilation.updateAsset does not add additional fields to AssetInfo in Rspack. This PR aims to resolve this/
Type definition of AssetInfo in webpack:
```typescript
type AssetInfo = KnownAssetInfo & Record<string, any>;
declare interface KnownAssetInfo {
/**
* true, if the asset can be long term cached forever (contains a hash)
*/
immutable?: boolean;
/**
* whether the asset is minimized
*/
minimized?: boolean;
/**
* the value(s) of the full hash used for this asset
*/
fullhash?: string | string[];
/**
* the value(s) of the chunk hash used for this asset
*/
chunkhash?: string | string[];
/**
* the value(s) of the module hash used for this asset
*/
modulehash?: string | string[];
/**
* the value(s) of the content hash used for this asset
*/
contenthash?: string | string[];
/**
* when …
```
=> feat: align `AssetInfo` type with webpack

crates/rspack_core/src/build_chunk_graph/code_splitter.rs
Every time when iteratoring a block, there will be a new chunk created, though the chunk is not used, but it will stay in memory
=> perf: code-splitting should not regenerate chunk

website/docs/en/api/modules/module-methods.mdx, website/docs/en/api/modules/module-variables.mdx, website/docs/zh/api/modules/module-methods.mdx, website/docs/zh/api/modules/module-variables.mdx
Add `import.meta.webpackContext` to document.
Compared to `require.context`, `import.meta.webpackContext` is more recommended to use.
- https://github.com/web-infra-dev/rspack/issues/4986
- https://github.com/web-infra-dev/rspack/issues/4305
=> docs: add import.meta.webpackContext

crates/rspack_plugin_javascript/src/visitors/dependency/parser/walk.rs, packages/rspack-test-tools/tests/normalCases/parsing/method-function-in-scope/index.js, packages/rspack-test-tools/tests/normalCases/parsing/method-function-in-scope/utils.js
closes https://github.com/web-infra-dev/rspack/issues/6648.
Maybe some test cases need to be added but I can't find where to add them.
```ts
import { f1 as a } from "./utils";
function authExchange() {
return {
mutate() {
var a = 1;
return a + 1;
},
appendHeaders() {
return a();
},
};
}
```
In this case, if there is no `in_function_scope` for method functions, the variable declaration `var a = 1` will be defined in the scope of the `authExchange` function. When walking `a` identifier in `appendHeaders`, the `a` defined in mutate will be found first. Then, during code generation, the `a` in `appendHeaders` will not be recognized as an import specifier and will not be replaced with harmony import.
This change is aligned with webpack …
=> fix: Add `in_function_scope` for walking method function

.github/actions/pnpm-cache/action.yml, .npmrc, package.json, pnpm-lock.yaml, website/package.json, website/pnpm-lock.yaml
- Bump pnpm from v8 to v9
- Remove `resolution-mode='highest'` as it is the default behavior.
- Handle `undefined` pnpm global_store_path in CI actions.
https://github.com/pnpm/pnpm/releases/tag/v9.0.0
=> chore(infra): bump pnpm v9

Cargo.lock, crates/rspack_plugin_ensure_chunk_conditions/Cargo.toml, crates/rspack_plugin_ensure_chunk_conditions/src/lib.rs
Internal project performance improvement.
Before:
```
LOG from rspack.EnsureChunkConditionsPlugin
<t> ensure chunk conditions: 11436 ms
```
After:
```
LOG from rspack.EnsureChunkConditionsPlugin
<t> ensure chunk conditions: 3463 ms
```
=> perf: put visited_chunk_group_keys out of the loop and use FxHashMap

.github/actions/pnpm-cache/action.yml, .github/workflows/reusable-build.yml
pnpm v9 no longer supports Node 16 (https://github.com/web-infra-dev/rspack/pull/6767)
We can use the [standalone](https://github.com/pnpm/action-setup?tab=readme-ov-file#standalone) option to use `@pnpm/exe` in Node 16 CI.
- Node 16:
- Node 18:
=> ci: use @pnpm/exe in Node 16 CI

crates/rspack_plugin_javascript/src/dependency/esm/harmony_export_imported_specifier_dependency.rs, crates/rspack_plugin_javascript/src/dependency/esm/harmony_import_dependency.rs, packages/rspack-test-tools/tests/diagnosticsCases/factorize/cannot-resolve-with-concatenate-conflict/index.ts, packages/rspack-test-tools/tests/diagnosticsCases/factorize/cannot-resolve-with-concatenate-conflict/node_modules/some-module/a.ts, packages/rspack-test-tools/tests/diagnosticsCases/factorize/cannot-resolve-with-concatenate-conflict/node_modules/some-module/b.ts, packages/rspack-test-tools/tests/diagnosticsCases/factorize/cannot-resolve-with-concatenate-conflict/node_modules/some-module/c.ts, packages/rspack-test-tools/tests/diagnosticsCases/factorize/cannot-resolve-with-concatenate-conflict/node_modules/some-module/package.json, packages/rspack-test-tools/tests/diagnosticsCases/factorize/cannot-resolve-with-concatenate-conflict/reexport.ts, packages/rspack-test-tools/tests/diagnosticsCases/factorize/cannot-resolve-with-concatenate-conflict/rspack.config.js, packages/rspack-test-tools/tests/diagnosticsCases/factorize/cannot-resolve-with-concatenate-conflict/stats.err, packages/rspack-test-tools/tests/diagnosticsCases/factorize/cannot-resolve-with-concatenate-import/index.ts, packages/rspack-test-tools/tests/diagnosticsCases/factorize/cannot-resolve-with-concatenate-import/node_modules/some-module/a.ts, packages/rspack-test-tools/tests/diagnosticsCases/factorize/cannot-resolve-with-concatenate-import/node_modules/some-module/b.ts, packages/rspack-test-tools/tests/diagnosticsCases/factorize/cannot-resolve-with-concatenate-import/node_modules/some-module/package.json, packages/rspack-test-tools/tests/diagnosticsCases/factorize/cannot-resolve-with-concatenate-import/reexport.ts, packages/rspack-test-tools/tests/diagnosticsCases/factorize/cannot-resolve-with-concatenate-import/rspack.config.js, packages/rspack-test-tools/tests/diagnosticsCases/factorize/cannot-resolve-with-concatenate-import/stats.err
When dependency was resolved and failed, the module graph module does not exists during code generation. So 
that can not just use `.expect()` to mgm.
=> fix: panic when resolve failed and enable concatenateModule

Cargo.lock, Cargo.toml, crates/rspack_plugin_css/src/parser_and_generator/mod.rs, crates/rspack_plugin_css/src/utils.rs, packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/at-import-in-the-middle/stats.err, packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/invalid-css-local-class/index.js, packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/invalid-css-local-class/index.module.css, packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/invalid-css-local-class/stats.err
Only treat `Any '@import' rules must precede all other rules` as error, treat others as warning
=> feat: use warning for css parsing

crates/node_binding/src/env.rs, crates/node_binding/src/lib.rs
Increase stack size limit to 4mb for deep recursions.
Limited to **production builds**, otherwise it's too error-prone.
=> fix: increase stack size limit to 4mb

packages/rspack/module.d.ts, packages/rspack/package.json, website/docs/en/guide/tech/typescript.mdx, website/docs/zh/guide/tech/typescript.mdx
Allow to reference client module types, the usage is the same as webpack.
Rspack provides client module types via `@rspack/core/module`, you can add a TypeScript reference directive to declare them:
```ts title="src/index.ts"
/// <reference types="@rspack/core/module" />
console.log(import.meta.webpackContext); // without reference declared above, TypeScript will throw an error
```
You can also add `@rspack/core/module` to the `types` field of tsconfig.json. This way, you no longer need to add the TypeScript reference directive in each file.
```json title="tsconfig.json"
{
"compilerOptions": {
"types": ["@rspack/core/module"]
}
}
```
- https://github.com/webpack/webpack/blob/main/module.d.ts
- https://webpack.js.org/guides/typescript/#client-types
=> feat: allow to reference client module types

crates/rspack_plugin_css/src/parser_and_generator/mod.rs, crates/rspack_plugin_javascript/src/parser_plugin/common_js_exports_parse_plugin.rs, crates/rspack_plugin_javascript/src/parser_plugin/mod.rs, crates/rspack_plugin_javascript/src/parser_plugin/use_strict_plugin.rs, crates/rspack_plugin_javascript/src/visitors/dependency/parser/mod.rs, diffcases/arco-pro/rspack.config.js, diffcases/arco-pro/webpack.config.js, packages/rspack-test-tools/tests/configCases/parsing/eval-cjs-typeof/index.js, packages/rspack-test-tools/tests/configCases/parsing/eval-cjs-typeof/rspack.config.js, packages/rspack-test-tools/tests/hotCases/css/recovery/__snapshots__/web/2.snap.txt, packages/rspack-test-tools/tests/treeShakingCases/cjs-export-computed-property/__snapshots__/treeshaking.snap.txt, packages/rspack-test-tools/tests/treeShakingCases/css/__snapshots__/treeshaking.snap.txt, plugin-test/css-extract/cases/hmr/expected/main.js, scripts/diff.cjs
This PR includes:
- eval `typeof exports` and `typeof module` for cjs
- remove make nsobj (`__webpack_require__.r`) for css module if it's not necessary
- remove `"use strict"` in code and add them together by render module
Remaining inconsistent codegen result for arco-pro:
1. Rspack goes a step further than webpack in analyzing side effect statements, in this case webpack fallback to has side effect but Rspack successfully analyzed it is side effect free 
2. Rspack doesn't support AMD
3. Rspack experiments css is not aligned with webpack currently
=> fix: basically same codegen of arco-pro

README.zh-CN.md, packages/rspack-plugin-preact-refresh/src/index.ts
Fix `@rspack/plugin-preact-refresh` missing plugin type.
- Before:
- After:
=> fix(plugin-preact-refresh): missing plugin type

packages/rspack-test-tools/rspack.config.js, packages/rspack-test-tools/tests/configCases/resolve/tsconfig-paths-map/rspack.config.js, packages/rspack/etc/api.md, packages/rspack/src/config/adapter.ts, packages/rspack/src/config/normalization.ts, packages/rspack/src/config/zod.ts, website/components/i18n/en.json, website/components/i18n/zh.json, website/docs/en/config/resolve.mdx, website/docs/en/guide/tech/typescript.mdx, website/docs/zh/config/resolve.mdx, website/docs/zh/guide/tech/typescript.mdx
- remove `resolve.tsConfigPath`
- supports string for `resolve.tsConfig`
and update example PR: https://github.com/rspack-contrib/rspack-examples/pull/93
=> refactor!: remove resolve tsConfigPath

crates/rspack_plugin_javascript/src/parser_plugin/api_plugin.rs, crates/rspack_plugin_javascript/src/parser_plugin/common_js_exports_parse_plugin.rs, crates/rspack_plugin_javascript/src/parser_plugin/common_js_imports_parse_plugin.rs, crates/rspack_plugin_javascript/src/parser_plugin/drive.rs, crates/rspack_plugin_javascript/src/parser_plugin/harmony_detection_parser_plugin.rs, crates/rspack_plugin_javascript/src/parser_plugin/trait.rs, crates/rspack_plugin_javascript/src/utils/eval/eval_unary_expr.rs, crates/rspack_plugin_javascript/src/visitors/dependency/parser/mod.rs, packages/rspack-test-tools/tests/configCases/parsing/eval-cjs-typeof/index.js, packages/rspack-test-tools/tests/configCases/parsing/eval-exports-in-detection-harmony/index.js, packages/rspack-test-tools/tests/configCases/parsing/eval-exports-in-detection-harmony/rspack.config.js
=> fix: should not eval exports in harmony

website/docs/en/api/javascript-api.mdx
The documentation seems to be showing the wrong import 
The correct import should be something like this
=> docs: fix rspack exports in javascript-api.mdx

.github/workflows/release-canary.yml, .github/workflows/release-nightly.yml, .github/workflows/release.yml, crates/node_binding/package.json, npm/darwin-arm64/package.json, npm/darwin-x64/package.json, npm/linux-x64-gnu/package.json, npm/win32-x64-msvc/package.json, packages/create-rspack/package.json, packages/rspack-cli/package.json, packages/rspack-dev-server/package.json, packages/rspack-plugin-minify/package.json, packages/rspack-plugin-preact-refresh/package.json, packages/rspack-plugin-react-refresh/package.json, packages/rspack-test-tools/package.json, packages/rspack/package.json
Generate NPM provenance statements for all Rspack packages.
This  allows us to publish Rspack packages on GitHub Actions only and increase supply-chain security.
See: https://docs.npmjs.com/generating-provenance-statements
=> feat: generating provenance statements

crates/rspack_plugin_extract_css/src/parser_and_generator.rs
may fix #6871
0.7.5-canary-129960e-20240620181737
=> fix: missing bailout reason after introducing css extract plugin

crates/node_binding/binding.d.ts, crates/rspack_binding_values/src/module.rs, crates/rspack_core/src/loader/loader_runner.rs, crates/rspack_plugin_javascript/src/plugin/inner_graph_plugin.rs, packages/rspack-test-tools/tests/configCases/loader/context-module/rspack.config.js, packages/rspack-test-tools/tests/treeShakingCases/pure-iife-return/__snapshots__/treeshaking.snap.txt, packages/rspack-test-tools/tests/treeShakingCases/pure-iife-return/b.js, packages/rspack-test-tools/tests/treeShakingCases/pure-iife-return/index.js, packages/rspack-test-tools/tests/treeShakingCases/pure-iife-return/rspack.config.js, packages/rspack/etc/api.md, packages/rspack/src/Module.ts
releated: https://github.com/web-infra-dev/rspack/issues/6436
After my debugging, I find some causes: 
1. In the reproduction of this issue, a loader that marks the module as side effect free and a corresponding optimization loader were configured, but factoryMeta is currently not being passed back to the js side.
2. Tree shaking fails for the following code:
```js
// index.js
import { B } from "./b";
let obj = /*#__PURE__*/ (() => {
return B;
})();
// b.js
const B = 1;
export { B };
```
webpack output: 
```js
/******/ (() => { // webpackBootstrap
/******/ 	"use strict";
var __webpack_exports__ = {};
let obj = /*#__PURE__*/ (/* unused pure expression or super */ null && ((() => {
return B;
})()));
/******/ })()
;
```
while rspack output:
```js
(() => { // webpackBootstrap
"use strict"; …
```
=> feat: add `factoryMeta` to `JsModule` and optimize `InnerGraphPlugin` for variable decl with iife

crates/node_binding/binding.d.ts, crates/rspack_binding_options/src/options/raw_module/mod.rs, crates/rspack_core/src/options/module.rs, crates/rspack_plugin_javascript/src/parser_plugin/worker_plugin.rs, crates/rspack_plugin_javascript/src/visitors/dependency/parser/mod.rs, crates/rspack_util/src/merge.rs, packages/rspack-test-tools/tests/__snapshots__/Defaults.test.js.snap, packages/rspack-test-tools/tests/configCases/worker/custom-worker-call-syntax/index.js, packages/rspack-test-tools/tests/configCases/worker/custom-worker-call-syntax/module.js, packages/rspack-test-tools/tests/configCases/worker/custom-worker-call-syntax/test.config.js, packages/rspack-test-tools/tests/configCases/worker/custom-worker-call-syntax/webpack.config.js, packages/rspack-test-tools/tests/configCases/worker/custom-worker-call-syntax/worker.js, packages/rspack/etc/api.md, packages/rspack/src/config/adapter.ts, packages/rspack/src/config/defaults.ts, packages/rspack/src/config/zod.ts, webpack-test/configCases/worker/custom-worker/node_modules/web-worker.js, webpack-test/configCases/worker/custom-worker/test.filter.js
=> feat: simple custom worker syntax

crates/rspack_plugin_javascript/src/plugin/mod.rs
Improve perf issue introduced in #6697. Use Rayon to parallelly parse modules.
=> perf(rspack_plugin_javascript): use Rayon to parse modules parallelly

crates/node_binding/binding.d.ts, crates/rspack_binding_options/src/options/raw_builtins/raw_copy.rs, crates/rspack_plugin_copy/src/lib.rs, plugin-test/copy-plugin/CopyPlugin.test.js, plugin-test/copy-plugin/__snapshots__/CopyPlugin.test.js.snap, website/docs/en/plugins/rspack/copy-rspack-plugin.mdx, website/docs/zh/plugins/rspack/copy-rspack-plugin.mdx
transform input is always `Buffer` type, and the returns support async.
resolve: https://github.com/web-infra-dev/rspack/issues/6895
=> fix: CopyRspackPlugin transform option type

packages/rspack-test-tools/tests/__snapshots__/Defaults.test.js.snap, packages/rspack-test-tools/tests/defaultsCases/target_/electron-main.js, packages/rspack-test-tools/tests/defaultsCases/target_/node.js, packages/rspack-test-tools/tests/defaultsCases/target_/nwjs.js, packages/rspack/etc/api.md, packages/rspack/src/config/defaults.ts, packages/rspack/src/config/zod.ts, packages/rspack/src/rspackOptionsApply.ts, website/docs/en/config/externals.mdx, website/docs/zh/config/externals.mdx
Add nwjs external presets to config
=> feat: add nwjs external preset

crates/rspack_plugin_javascript/src/parser_plugin/compatibility_plugin.rs, crates/rspack_plugin_javascript/src/parser_plugin/drive.rs, crates/rspack_plugin_javascript/src/parser_plugin/harmony_import_dependency_parser_plugin.rs, crates/rspack_plugin_javascript/src/parser_plugin/trait.rs, crates/rspack_plugin_javascript/src/parser_plugin/worker_plugin.rs, crates/rspack_plugin_javascript/src/visitors/dependency/parser/mod.rs, crates/rspack_plugin_javascript/src/visitors/dependency/parser/walk_pre.rs, packages/rspack/src/config/adapter.ts, webpack-test/configCases/worker/issue-17489/index.js, webpack-test/configCases/worker/issue-17489/module.js, webpack-test/configCases/worker/issue-17489/test.config.js, webpack-test/configCases/worker/issue-17489/test.filter.js, webpack-test/configCases/worker/issue-17489/webpack.config.js, webpack-test/configCases/worker/issue-17489/worklet.js, webpack-test/configCases/worker/worklet/index.js, webpack-test/configCases/worker/worklet/module.js, webpack-test/configCases/worker/worklet/test.config.js, webpack-test/configCases/worker/worklet/test.filter.js, webpack-test/configCases/worker/worklet/webpack.config.js, webpack-test/configCases/worker/worklet/worklet-asset-1.js, webpack-test/configCases/worker/worklet/worklet-asset-2.js, webpack-test/configCases/worker/worklet/worklet.js, webpack-test/helpers/createFakeWorker.js, website/components/ApiMeta.module.scss, website/components/ApiMeta.tsx, website/docs/en/config/module.mdx, website/docs/en/guide/features/web-workers.mdx, website/docs/zh/config/module.mdx, website/docs/zh/guide/features/web-workers.mdx
=> feat: custom worker syntax for worklet

crates/rspack_plugin_javascript/src/parser_plugin/compatibility_plugin.rs, webpack-test/configCases/library/1-use-library/test.filter.js, webpack-test/configCases/output-module/reuse-webpack-esm-library/index.js, webpack-test/configCases/output-module/reuse-webpack-esm-library/lib.js, webpack-test/configCases/output-module/reuse-webpack-esm-library/react.js, webpack-test/configCases/output-module/reuse-webpack-esm-library/webpack.config.js
=> feat: support nested __webpack_exports__

Cargo.toml
Panics should not print build system related paths.
See: https://rust-lang.github.io/rfcs/3127-trim-paths.html
=> chore: sanitize file paths

crates/rspack_core/src/compiler/compilation.rs
Aligning `Compilation#assign_runtime_ids` with [webpack implementation](https://github.com/webpack/webpack/blob/dd44b206a9c50f4b4cb4d134e1a0bd0387b159a3/lib/Compilation.js#L3987).
Found this mismatch while experimenting with rspack on the old large project.
Before these changes, the dump of `ChunkGraph.runtime_ids` looked like this:
```
{
"__calculator_worker__": Some("__calculator_worker__"),
"RichTextWebWorker": Some("RichTextWebWorker"),
"__functions_worker__": Some("__functions_worker__"),
"appInlineEntry": Some("runtime~appInlineEntry")
}
```
while in webpack it looked like this:
```
{
'runtime~appInlineEntry' => 'runtime~appInlineEntry',
'a00dc51364804200' => 3,
'56698110d4fe00db' => 'RichTextWebWorker',
'8d8141fedf82c897' => 1,
'92429ff87222e258' => 2,
'65e8ae716b25791d' => 0, …
```
=> fix: use entrypoint.options.runtime as key for chunk_graph.runtime_ids map if possible

website/docs/en/api/_meta.json, website/docs/en/api/stats.mdx, website/docs/zh/api/_meta.json, website/docs/zh/api/stats.mdx
=> docs: add stats data

packages/create-rspack/template-react-ts/package.json, packages/create-rspack/template-react-ts/rspack.config.ts, packages/create-rspack/template-react-ts/tsconfig.json, packages/create-rspack/template-react/rspack.config.mjs, packages/create-rspack/template-vanilla/rspack.config.js, packages/create-rspack/template-vanilla/rspack.config.mjs, packages/create-rspack/template-vue-ts/package.json, packages/create-rspack/template-vue-ts/rspack.config.ts, packages/create-rspack/template-vue-ts/src/main.ts, packages/create-rspack/template-vue-ts/tsconfig.json, packages/create-rspack/template-vue/package.json, packages/create-rspack/template-vue/rspack.config.mjs, packages/create-rspack/template-vue/src/main.js, pnpm-lock.yaml
Improve the templates:
- Enable `experiments.css` to support CSS, see https://github.com/web-infra-dev/rspack/pull/6910
- Use `rspack.config.mjs` for JS templates.
- Use `rspack.config.ts` for TS templates.
- Use `defineConfig` to provide autocomplete.
- Update tsconfig.json and align with Rsbuild.
=> feat(create-rspack): improve the templates

crates/rspack_core/src/compiler/make/repair/factorize.rs, crates/rspack_core/src/normal_module_factory.rs
Partially fixed the compile issue of  https://github.com/web-infra-dev/rspack/issues/5554
This is still not be able to turn on:
```
● ConfigTestCases › inner-graph › basic › exported tests › myFunction should have the correct exports used for ./assert
expect(received).toEqual(expected) // deep equality
Expected: ["__usedExports", "deepEqual", "equal"]
Received: undefined
```
`__webpack_exports_info__.usedExports` is not supported.
=> fix: context passed into the `ModuleFactory` is not correct

packages/rspack-test-tools/tests/Defaults.test.js, packages/rspack-test-tools/tests/__snapshots__/Defaults.test.js.snap, packages/rspack-test-tools/tests/defaultsCases/experiments/both-wasm.js, packages/rspack-test-tools/tests/defaultsCases/experiments/future-defaults-with-css.js, packages/rspack-test-tools/tests/defaultsCases/experiments/future-defaults.js, packages/rspack/src/config/defaults.ts
`asyncWebAssembly` default value depend on `experiments.futureDefaults` to close and open.
=> fix!: align webpack defaults

crates/node_binding/binding.d.ts, crates/rspack_binding_values/src/stats.rs, crates/rspack_core/src/stats.rs, packages/rspack-test-tools/tests/__snapshots__/StatsAPI.test.js.snap, packages/rspack-test-tools/tests/statsAPICases/chunks.js, webpack-test/__snapshots__/StatsTestCases.basictest.js.snap, website/docs/en/api/stats.mdx, website/docs/zh/api/stats.mdx
- Add stats.chunks[].origins[].moduleId
=> feat: stats origin moduleid

crates/rspack_plugin_javascript/src/plugin/module_concatenation_plugin.rs
=> refactor: improve code style in concate module

crates/rspack_plugin_javascript/src/dependency/esm/harmony_export_imported_specifier_dependency.rs, crates/rspack_plugin_javascript/src/parser_plugin/harmony_export_dependency_parser_plugin.rs, packages/rspack-test-tools/tests/configCases/parsing/rspack-issue-6934/a.js, packages/rspack-test-tools/tests/configCases/parsing/rspack-issue-6934/b.js, packages/rspack-test-tools/tests/configCases/parsing/rspack-issue-6934/index.js, packages/rspack-test-tools/tests/configCases/parsing/rspack-issue-6934/rspack.config.js
closes https://github.com/web-infra-dev/rspack/issues/6934
=> fix: fix duplicated harmony exports with named exports and re-exports star

.github/workflows/release.yml
Fix permissions for prod release, see:
https://github.com/web-infra-dev/rspack/actions/runs/9710373465/job/26802316724
=> chore(workflow): fix permissions for prod release

website/docs/en/blog/announcing-1-0-alpha.mdx, website/docs/zh/blog/announcing-1-0-alpha.mdx
=> docs: remove invalid OG image

crates/rspack_plugin_size_limits/src/lib.rs
Due to the typo in `rspack_plugin_size_limits` the `add_entrypoints_over_size_limit_warning` was reported with `max_asset_size` instead of `max_entrypoint_size`. On my project, it looks like this:
```
config.performance = {
maxEntrypointSize: 43000, // 41.992 KiB
maxAssetSize: 30000000, // 28.610 MiB
}
```
```
ERROR in × entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (28.610 MiB). This can impact web performance.
│ Entrypoints:
│   appInlineEntry (42.025 KiB)
│       runtime~appInlineEntry.36a7dc3a8518e752.js
│       appInlineEntry.476b756676281597.js
```
=> fix: use max_entrypoint_size in add_entrypoints_over_size_limit_warning

.github/renovate.json5
swc may introduce breaking during patch update which is not safe to do auto bump for rspack, 
we need to do manually update for swc related crated
=> chore: disable renovate update for swc

crates/node_binding/README.md, packages/rspack-plugin-minify/README.md
since we're compatible with terser-webpack-plugin now, rspack-minify-plugin could be deprecated
=> chore: add deprecated notice for rspack-plugin-minify

crates/node_binding/binding.d.ts, crates/node_binding/src/plugins/interceptor.rs, crates/node_binding/src/plugins/mod.rs, crates/rspack_binding_values/src/normal_module_factory.rs, crates/rspack_core/src/normal_module_factory.rs, packages/rspack-test-tools/tests/hookCases/normalModuleFactory#resolve/resource/a.js, packages/rspack-test-tools/tests/hookCases/normalModuleFactory#resolve/resource/b.js, packages/rspack-test-tools/tests/hookCases/normalModuleFactory#resolve/resource/c.js, packages/rspack-test-tools/tests/hookCases/normalModuleFactory#resolve/resource/output.snap.txt, packages/rspack-test-tools/tests/hookCases/normalModuleFactory#resolve/resource/resource.js, packages/rspack-test-tools/tests/hookCases/normalModuleFactory#resolve/resource/test.js, packages/rspack/etc/api.md, packages/rspack/src/Compiler.ts, packages/rspack/src/NormalModuleFactory.ts, website/components/Columns.tsx, website/docs/en/api/plugin-api/normal-module-factory-hooks.mdx, website/docs/zh/api/plugin-api/normal-module-factory-hooks.mdx
support nmf resolve hook:
- rust side: full support
- js side: limited support, only support modify resolveData in the hook, return any value (1. `false` to ignore the request, 2. module instance) are not supported for now
=> feat: support nmf resolve hook

README.md, README.zh-CN.md, website/docs/en/guide/start/introduction.mdx, website/docs/en/index.md, website/docs/zh/guide/start/introduction.mdx, website/docs/zh/index.md
Add Module Federation to features list and remove `Batteries Included`, since Rspack now aligns with webpack and no longer provides builtin TypeScript / Sass support.
=> docs: add Module Federation to features list

README.md, README.zh-CN.md
- This is a reupload of https://github.com/web-infra-dev/rspack/pull/7020
- The additional whitespace within the `<a>` gets included between the badges. By removing this whitespace, the badges will not show underlines in-between anymore
=> chore(readme): remove underlines between badges

crates/node_binding/binding.d.ts, crates/rspack_binding_values/src/compilation.rs, crates/rspack_core/src/options/target.rs, packages/rspack/etc/api.md, packages/rspack/src/Compilation.ts, packages/rspack/src/Stats.ts
1. Support for `target` to use `'es6'`:
This enhancement is especially useful for frameworks such as Next.js that utilize `'es6'` in their build configurations. For reference, see how Next.js configures their webpack build [here](https://github.com/vercel/next.js/blob/b2625477c002343e7fe083204c45af1fdd7cd407/packages/next/src/build/webpack/config/blocks/base.ts#L20).
2. Add `startTime` and `endTime` in `Stats`:
These timestamps are used for plugins like `friendly-errors-webpack-plugin`, which relies on these metrics for enhanced error reporting. For more details, see the plugin implementation [here](https://github.com/geowarin/friendly-errors-webpack-plugin/blob/51745900c9dcc582aa250033a856216ca2f64377/src/friendly-errors-plugin.js#L126).
=> feat: align webpack target and stats api

website/docs/en/api/modules/module-methods.mdx, website/docs/zh/api/modules/module-methods.mdx
- Add documents of fetch priority
=> docs: add fetch priority

.github/workflows/get-runner-labels.yml, .github/workflows/release-canary.yml, .github/workflows/release-nightly.yml, .github/workflows/release.yml
add `force-use-github-runner` params to `get-runner-labels` workflow and make all of release workflow run on github runner
=> chore: release force use github runner

website/docs/en/guide/start/introduction.mdx, website/docs/zh/guide/start/introduction.mdx, website/project-words.txt
add comparison with parcel section in introduction
=> docs: add compare with parcel section

scripts/release/publish.mjs
We have tried to generate provenance statements in https://github.com/web-infra-dev/rspack/pull/6896, and it worked for most packages like `@rspack/core`.
However, the binding packages (such as `@rspack/binding-darwin-arm64`) are still missing provenance statement, this PR added the `--provenance` option to try to fix this issue.
See:  https://github.com/napi-rs/napi-rs/blob/286c8d0cf46e683e642ce1b01e768d756e013567/cli/src/api/templates/ci-template.ts#L579
=> chore: add provenance option to pnpm publish

packages/rspack/prebundle.config.mjs
Fix zod is pre-bundled twice because we do not configure externals for `zod-validation-error` correctly.
`compiled/zod-validation-error/index.js`: from `157kb` to `8kb`.
=> fix: zod is pre-bundled twice

packages/rspack/src/Compilation.ts
Cache `compilation.entrypoints` to improve performance, it is similar to `compilation.#cachedAssets`.
The performance cost of `compilation.entrypoints` is noticeable when using [html-webpack-plugin](https://github.com/jantimon/html-webpack-plugin/blob/41f4a7b952e80eea4878d96638b4021f4a762750/index.js#L1296).
I have tested it in a MPA project (https://github.com/liangyuetian/rsbuild-hmr-slow-demo) with 200+ entries:
- without cache, it took 500ms (total) to get `compilation.entrypoints`:
- with cache, it took 2.5ms (total) to get `compilation.entrypoints`:
=> perf: cache `compilation.entrypoints`

website/components/RandomMemberList.module.scss, website/components/RandomMemberList.tsx, website/docs/en/misc/team/core-team.mdx, website/docs/zh/misc/team/core-team.mdx, website/project-words.txt
- Update the teams page, add Rsfamily members: @SoonIter @Timeless0911 @fi3ework @easy1090  🎉
- Move `IWANABETHATGUY` to emeriti members, thanks to his great work ❤️
=> docs: update teams page, add Rsfamily members

crates/rspack_core/src/exports_info.rs, packages/rspack-test-tools/tests/configCases/concatenate-modules/get-max-target-panic/index.js, packages/rspack-test-tools/tests/configCases/concatenate-modules/get-max-target-panic/node_modules/mocklib/core.js, packages/rspack-test-tools/tests/configCases/concatenate-modules/get-max-target-panic/node_modules/mocklib/lib.js, packages/rspack-test-tools/tests/configCases/concatenate-modules/get-max-target-panic/node_modules/mocklib/package.json, packages/rspack-test-tools/tests/configCases/concatenate-modules/get-max-target-panic/node_modules/mocklib/queryclient.js, packages/rspack-test-tools/tests/configCases/concatenate-modules/get-max-target-panic/rspack.config.js
fix https://github.com/web-infra-dev/rspack/issues/7057
fix https://github.com/web-infra-dev/rspack/issues/7062
fix https://github.com/web-infra-dev/rspack/issues/7077
fix https://github.com/web-infra-dev/rspack/issues/7078
In webpack, module graph is always mutable and will insert the max target of export info while getting it, even during the code gen.
But in rspack, module graph should be immutable during the code gen. So can only get max target when it has been set. If it is not exists, export info should generate it but not set it into export info.
=> fix: panic when get max target in find target

.github/workflows/release.yml, Cargo.toml, crates/node_binding/package.json, crates/node_binding/scripts/build.js, package.json
- Better performance (according to benchmark): **1% ~ 3% faster**
- Smaller binary size (rspack.darwin-arm64.node): **55.4 MB -> 51.7 MB**
- Longer build time, only affect the production release: **4-5min -> 8-10min**
see: 
- https://github.com/web-infra-dev/rspack/pull/5507
- https://doc.rust-lang.org/cargo/reference/profiles.html#lto
=> perf: enable "fat" LTO for production release

website/package.json, website/pnpm-lock.yaml, website/rspress.config.ts
- Enable sitemap for SEO.
- Bump Rspress v1.26.0
https://github.com/jl917/rspress-plugin-sitemap
=> docs: enable sitemap for SEO

crates/rspack_binding_values/src/compilation.rs, crates/rspack_core/src/code_generation_results.rs, crates/rspack_core/src/compiler/make/repair/process_dependencies.rs, crates/rspack_core/src/compiler/module_executor/execute.rs, crates/rspack_core/src/concatenated_module.rs, crates/rspack_core/src/dependencies_block.rs, crates/rspack_core/src/exports_info.rs, crates/rspack_core/src/external_module.rs, crates/rspack_core/src/module.rs, crates/rspack_core/src/normal_module.rs, crates/rspack_core/src/options/context.rs, crates/rspack_core/src/options/filename.rs, crates/rspack_core/src/template.rs, crates/rspack_core/src/utils/identifier.rs, crates/rspack_plugin_css/src/utils.rs, crates/rspack_plugin_javascript/src/parser_plugin/javascript_meta_info_plugin.rs, crates/rspack_plugin_javascript/src/plugin/mod.rs, crates/rspack_plugin_library/src/assign_library_plugin.rs, crates/rspack_util/src/atom.rs, crates/rspack_util/src/lib.rs, crates/rspack_util/src/merge.rs
=> perf: remove unneeded string clone

packages/create-rspack/index.js
Automatically set the folder name entered by the user to the name of pkg.
Scenario: The package in the monorepo is usually the same as the entered folder name, so there is no need to modify it manually
将用户输入的文件夹名称自动渲染到pkg的name。
场景：monorepo中的包一般和输入的文件夹名称一样，就不需要手动修改了
=> feat(create-rspack): add custom template pkg name

crates/rspack_core/src/external_module.rs, crates/rspack_core/src/module.rs, crates/rspack_core/src/normal_module.rs, crates/rspack_core/src/parser_and_generator.rs, crates/rspack_plugin_asset/src/lib.rs, crates/rspack_plugin_css/src/parser_and_generator/mod.rs, crates/rspack_plugin_javascript/src/parser_and_generator/mod.rs, crates/rspack_plugin_javascript/src/plugin/module_concatenation_plugin.rs, crates/rspack_plugin_json/src/lib.rs, crates/rspack_plugin_wasm/src/parser_and_generator.rs
`String` -> `Cow<'static, str>` for some static values.
=> perf: reduce alloc for bailout reason

website/docs/en/guide/migration/webpack.mdx, website/docs/en/guide/tech/css.mdx, website/docs/en/plugins/rspack/css-extract-rspack-plugin.mdx, website/docs/zh/guide/migration/webpack.mdx, website/docs/zh/guide/tech/css.mdx, website/docs/zh/plugins/rspack/css-extract-rspack-plugin.mdx
Adds description about how to use `CssExtractRspackPlugin` and `experiments.css` together, and how to customize css module type for certain modules
=> docs: use CssExtractRspackPlugin and experiments.css together

packages/rspack-lite-tapable/src/index.ts, packages/rspack/src/loader-runner/index.ts, packages/rspack/src/util/identifier.js, packages/rspack/src/util/identifier.ts
https://github.com/web-infra-dev/rspack/issues/4640
=> refactor: remove identifier.js ts-expect-error

Cargo.lock, crates/node_binding/binding.d.ts, crates/rspack_binding_options/src/options/raw_builtins/mod.rs, crates/rspack_binding_options/src/options/raw_builtins/raw_swc_css_minimizer.rs, crates/rspack_plugin_swc_css_minimizer/Cargo.toml, crates/rspack_plugin_swc_css_minimizer/src/lib.rs, crates/rspack_plugin_swc_css_minimizer/src/swc_css_compiler.rs, packages/rspack-test-tools/tests/configCases/plugins/minify-exclude-css/a.css, packages/rspack-test-tools/tests/configCases/plugins/minify-exclude-css/a.js, packages/rspack-test-tools/tests/configCases/plugins/minify-exclude-css/b.css, packages/rspack-test-tools/tests/configCases/plugins/minify-exclude-css/b.js, packages/rspack-test-tools/tests/configCases/plugins/minify-exclude-css/index.js, packages/rspack-test-tools/tests/configCases/plugins/minify-exclude-css/rspack.config.js, packages/rspack-test-tools/tests/configCases/plugins/minify-exclude-css/test.config.js, packages/rspack/etc/api.md, packages/rspack/src/builtin-plugin/SwcCssMinimizerPlugin.ts, website/docs/en/plugins/rspack/swc-css-minimizer-rspack-plugin.mdx
The PR adds the `test`, `include` and `exclude` options to the `SwcCssMinimizerRspackPlugin`, similar to how it works with the `SwcJsMinimizerRspackPlugin`.
resolve #6898
=> feat: support `test`, `include` and `exclude` options for `SwcCssMinimizerRspackPlugin`

crates/node_binding/binding.d.ts, crates/rspack_plugin_javascript/src/parser_plugin/common_js_exports_parse_plugin.rs, packages/rspack-test-tools/tests/normalCases/parsing/cjs-unset-exports-type/a.js, packages/rspack-test-tools/tests/normalCases/parsing/cjs-unset-exports-type/b.js, packages/rspack-test-tools/tests/normalCases/parsing/cjs-unset-exports-type/cjs.js, packages/rspack-test-tools/tests/normalCases/parsing/cjs-unset-exports-type/index.js
=> fix: unset cjs exports type on access exports directly

.github/workflows/ci.yml, packages/rspack/src/builtin-plugin/SwcCssMinimizerPlugin.ts
use the biome right script to lint on ci
https://github.com/web-infra-dev/rspack/actions/runs/9925906232/job/27419030108
=> ci: fix the action that does not use biome in fact

website/docs/en/misc/benchmark.mdx, website/docs/zh/misc/benchmark.mdx, website/theme/components/Benchmark/ProgressBar.module.scss, website/theme/components/Benchmark/ProgressBar.tsx, website/theme/components/Benchmark/index.module.scss, website/theme/components/Benchmark/index.tsx, website/theme/components/HomeHero/index.module.scss, website/theme/i18n/enUS.ts, website/theme/i18n/zhCN.ts
Update benchmark data and improve UI:
- Use the latest benchmark data from https://github.com/rspack-contrib/performance-compare
- Update the benchmark UI to display all metrics at the same time:
Light mode:
Dark mode:
=> docs: update benchmark data and improve UI

packages/rspack/etc/api.md, packages/rspack/src/ResolverFactory.ts
align resolverFactory resolveOptions parameter with resolve options.
When I pass `compiler.options.resolve` as the resolverFactory parameter, a type error is reported, which is not make sense.
Related PR: https://github.com/web-infra-dev/rspack/pull/4945
=> fix: align resolverFactory resolveOptions parameter with resolve options

packages/rspack-test-tools/tests/configCases/module/generator-js/index.js, packages/rspack-test-tools/tests/configCases/module/generator-js/lib.js, packages/rspack-test-tools/tests/configCases/module/generator-js/rspack.config.js, packages/rspack/src/config/adapter.ts
fix invalid "javascript/auto" rule.type in getRawGeneratorOptions:
No generator options are supported for module type `javascript/auto` / `javascript` / `javascript/dynamic` / `javascript/esm`,  it should be ignored instead of throw an error.
https://github.com/web-infra-dev/rspack/issues/6873#issuecomment-2228082861
=> fix: invalid "javascript/auto" rule.type in getRawGeneratorOptions

website/docs/en/config/output.mdx, website/docs/zh/config/output.mdx, website/project-words.txt
Polish up `output` documentation. The main target is to align with webpack's document if the abilities are aligned. Put legacy / tend to be deprecated fields to the end of the page and only provide a link to its substitute. 
- do not support `output.charset`
- do not support `output.chunkLoadTimeout`
- `output.clean` only supports boolean
- do not support `output.compareBeforeEmit`
- do not support `output.cssHeadDataCompression`
- do not support `output.ignoreBrowserWarnings`
- do not support `output.importMetaName`
- do not support `output.sourcePrefix`
- do not support `output.trustedTypes.onPolicyCreationFailure`
- `output.publicPath` only supports string
- do not support `strictModuleExceptionHandling` (deprecated)
- `output.assetModuleFilename` only supports string
I wonder, do we …
=> docs: polish up output config

packages/rspack-cli/package.json, packages/rspack/scripts/check-documentation-coverage.mjs
^0.4.0 doesn't match 1.0.0-alpha anymore, which will cause npm install error, 
update peerDep @rspack/core to ^1.0.0 to match 1.0.0-alpha
=> fix(cli): update peerDep of rspack-cli

crates/rspack_core/src/options/filename.rs, crates/rspack_util/src/ext.rs
`String::replace` allocates `String` on each iteration and `Regex::replace_all` only returns `Cow::Owned(...)` if there's an actual replacement takes place. Thus, we are moving from `String::replace` to `Regex::replace_all`.
For test cases: 
- 0: "[id].[name].css"
- 1: "[id].[name].[fullhash][ext][[query]"
- 2: "[id].[name].[fullhash][ext][[query][id].[name].[fullhash][ext][[query]"
**Case: "[id].[name].css"** (22% faster)
```
Replace/String::replace/0
time:   [31.403 µs 31.468 µs 31.529 µs]
change: [+0.3228% +0.7846% +1.2319%] (p = 0.00 < 0.05)
Change within noise threshold.
Found 3 outliers among 100 measurements (3.00%)
2 (2.00%) high mild
1 (1.00%) high severe
Replace/Regex::replace/0
time:   [24.505 µs 24.594 µs 24.692 µs]
change: [-0.0425% +0.2968% +0.6560%] (p = 0.11 > 0.05)
No …
```
=> perf: reduce allocation for filename render

crates/rspack_plugin_javascript/src/parser_plugin/common_js_imports_parse_plugin.rs, crates/rspack_plugin_javascript/src/parser_plugin/import_parser_plugin.rs, crates/rspack_plugin_javascript/src/visitors/dependency/context_dependency_helper.rs, packages/rspack-test-tools/tests/builtinCases/rspack/dynamic-import/__snapshots__/output.snap.txt, packages/rspack-test-tools/tests/builtinCases/rspack/dynamic-import/index.js
fix https://github.com/web-infra-dev/rspack/issues/6874
The cause of the problem is the direct walking of import call expression, which led to a conflict between the replacement generated by this walk and the replacement handled by ConstPlugin.
Webpack handles the import call expression in three cases:
TemplateLiteral: walk the parts with odd indices, see https://github.com/webpack/webpack/blob/8241da7f1e75c5581ba535d127fa66aeb9eb2ac8/lib/dependencies/ContextDependencyHelpers.js#L151
Wrapped expr: process the inner expressions, see https://github.com/webpack/webpack/blob/8241da7f1e75c5581ba535d127fa66aeb9eb2ac8/lib/dependencies/ContextDependencyHelpers.js#L218
Other cases: directly walk the import call expression, see https://github.com/webpack/webpack/blob/8241da7f1e75c5581ba535d127fa66ae …
=> refactor: move context dependency `walk_expression` into `create_context_dependency`

biome.jsonc, packages/rspack-cli/src/utils/profile.ts, packages/rspack-test-tools/src/case/diff.ts, packages/rspack-test-tools/src/case/stats-output.ts, packages/rspack-test-tools/src/compare/format-code.ts, packages/rspack-test-tools/src/helper/legacy/createFakeWorker.js, packages/rspack/src/stats/DefaultStatsPrinterPlugin.ts, scripts/meta/check_is_workspace_root.js, scripts/release/publish.mjs, scripts/test/diff.cjs
add biome rule noUnusedTemplateLiteral
https://github.com/web-infra-dev/rspack/pull/7160
https://biomejs.dev/linter/rules/no-unused-template-literal/
=> chore(infra/biome): noUnusedTemplateLiteral

Cargo.lock, crates/rspack_plugin_javascript/Cargo.toml, crates/rspack_plugin_javascript/src/plugin/side_effects_flag_plugin.rs
Fixed #6245 and #6613 
To solve this problem, I have invested a lot of effort in understanding the [`glob_match`](https://crates.io/crates/glob-match). Due to the original author not maintaining it for a long time, I have republished the [`fast_glob`](https://crates.io/crates/fast-glob).
Using `fast_glob`, you can get:
- Faster problem response
- Nearly 60% performance improvement
The original intention of `fast_glob` is only to promptly fix the first issue mentioned above.
=> fix: pattern with wildcard and globstar can't match correctly when using `glob_match`

crates/rspack_error/src/error.rs, crates/rspack_plugin_css/src/parser_and_generator/mod.rs, crates/rspack_plugin_css/src/utils.rs, packages/rspack-test-tools/tests/diagnosticsCases/builtins/html_syntax_error/stats.err, packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/multiple_file_syntax_error/stats.err, packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/non_support_warning/stats.err
Replaced `src: String` with `src: Arc<String>`. `Arc<String>` is an internal representation of `SourceFile` source.
The type should not be `Arc<str>` as it creates additional heap allocations.
Removed duplicated `String` allocations in `TraceableError` of `CssPlugin`.
Removed normalization code for `start` and `end` position.
=> perf: reduce allocation for `TraceableError`

crates/node_binding/binding.d.ts, crates/rspack_binding_options/src/options/raw_output.rs, packages/rspack/etc/api.md, packages/rspack/src/config/zod.ts, tests/webpack-test/configCases/asset-modules/assetModuleFilename/test.filter.js, website/docs/en/config/output.mdx, website/docs/zh/config/output.mdx
Add support for function types to `output.assetModuleFilename`
=> feat: add support for function types to `output.assetModuleFilename`

crates/rspack_core/src/stats.rs
fix: panic in hmr cause by auxiliary_assets
Prevent panic when a file is not found in assets. Aligns with webpack's behavior in https://github.com/webpack/webpack/blob/main/lib/stats/DefaultStatsFactoryPlugin.js#L1007.
=> fix: panic in hmr cause by auxiliary_assets

packages/rspack/etc/api.md, packages/rspack/src/config/zod.ts, packages/rspack/src/stats/DefaultStatsFactoryPlugin.ts, packages/rspack/src/stats/DefaultStatsPresetPlugin.ts, tests/webpack-test/__snapshots__/StatsTestCases.basictest.js.snap, website/docs/en/config/stats.mdx, website/docs/zh/config/stats.mdx
1. Add  `minimal`, `detailed`, `summary` to stats presets's zod type and configuration doc.
2. Fix `assetsSpace: 0` being treated as `Infinity`
3. Fix missing `{count} assets` on console output when assets are filtered
=> refactor: allows minimal/detailed/summary stats presets in configuration

crates/rspack_plugin_javascript/src/dependency/context/import_meta_context_dependency.rs, packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/import-meta-context-error/index.js, packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/import-meta-context-error/stats.err
Fix panic in ImportMetaContextDependency when resolve failed
Relate to https://github.com/web-infra-dev/rspack/issues/7207
=> fix: panic in ImportMetaContextDependency when resolve failed

crates/node_binding/binding.d.ts, crates/rspack_binding_values/src/asset.rs, crates/rspack_binding_values/src/stats.rs, packages/rspack-test-tools/tests/__snapshots__/StatsAPI.test.js.snap, packages/rspack-test-tools/tests/configCases/hooks/update-asset/rspack.config.js, packages/rspack-test-tools/tests/hookCases/compilation#processAssets/update-asset/test.js, packages/rspack-test-tools/tests/statsAPICases/asset-info.js, packages/rspack-test-tools/tests/statsAPICases/child-compiler.js, packages/rspack/src/util/AssetInfo.ts
There're 2 implemented hash related fields in `asset.info`, however their names are varied from which in webpack. They are:
| Rspack | Webpack |
| --- | --- |
| `chunkHash` | `chunkhash` |
| `contentHash` | `contenthash` |
This PR corrects these names.
=> fix!: correct names of hash fields in asset.info

crates/rspack_identifier/src/lib.rs, crates/rspack_plugin_javascript/src/parser_plugin/compatibility_plugin.rs, crates/rspack_plugin_javascript/src/parser_plugin/harmony_import_dependency_parser_plugin.rs, crates/rspack_plugin_javascript/src/parser_plugin/inner_graph/plugin.rs, crates/rspack_plugin_javascript/src/parser_plugin/worker_plugin.rs, crates/rspack_plugin_javascript/src/visitors/dependency/parser/call_hooks_name.rs, crates/rspack_plugin_javascript/src/visitors/dependency/parser/mod.rs, crates/rspack_plugin_javascript/src/visitors/dependency/parser/walk.rs, crates/rspack_plugin_javascript/src/visitors/scope_info.rs
1. Prefer passing a copy than a pointer
```rust
struct DependencyId(u32); // <- 4 bytes
fn foo(d: &DependencyId); // <- usize
⬇️
fn foo(d: DependencyId); // <- 4 bytes
```
Pointers in rust are `usize`. On a 32 bit target, this is 4 bytes and on a 64 bit target, this is 8 bytes. 
A tuple of a `u32` is 4 bytes.
2. Shadowed `Display` of `Identifier` with `to_string`
Like how other structs are shadowed in the standard library for performance, we shadowed `Identifier` to gain performance of calling `to_string` instead of directly calling `display`. 
Calling `display` basically means calling `format!("{}", xxx)`. This creates additional allocation for formatters.
See also: https://github.com/rust-lang/rust/pull/32586.
=> perf: reduce allocation for parsing

.github/workflows/ci.yml, website/components/CommunityCompatibleTable.tsx, website/components/PluginSupportStatusTable.tsx, website/package.json, website/pnpm-lock.yaml, website/theme/components/Benchmark/index.tsx
https://github.com/web-infra-dev/rspack/issues/7182#issuecomment-2236771277
=> ci(website/infra): lint-staged issue in website

crates/rspack_plugin_javascript/src/parser_plugin/import_parser_plugin.rs, packages/rspack-test-tools/tests/configCases/tree-shaking/dynamic-import-unused/index.js, packages/rspack-test-tools/tests/configCases/tree-shaking/dynamic-import-unused/lib.js, packages/rspack-test-tools/tests/configCases/tree-shaking/dynamic-import-unused/rspack.config.js, packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/webpack-exports-warning/index.js, packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/webpack-exports-warning/lib.js, packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/webpack-exports-warning/stats.err, tests/webpack-test/__snapshots__/StatsTestCases.basictest.js.snap
Close https://github.com/web-infra-dev/rspack/issues/5551
Support tree shaking while awaiting dynamic import, just like webpack
```js
(async function() {
const { a, b } = import("./lib");
// only export ["a", "b"] were imported
})();
```
=> feat: support tree shaking with awaiting dynamic import

website/docs/en/api/modules/module-variables.mdx, website/docs/zh/api/modules/module-variables.mdx
Add documentation of `__webpack_get_script_filename__`
=> docs: add __webpack_get_script_filename__

crates/rspack_core/src/runtime.rs
Fixes panic:
```log
packages/rspack-test-tools test: DebugInfo:
packages/rspack-test-tools test: context: /home/runner/work/rspack/rspack/packages/rspack-test-tools/tests/hotCases/worker/issue-5597
packages/rspack-test-tools test: DebugInfo:
packages/rspack-test-tools test: context: /home/runner/work/rspack/rspack/packages/rspack-test-tools/tests/hotCases/worker/issue-5597
packages/rspack-test-tools test: Panic occurred at runtime. Please file an issue on GitHub with the backtrace below: https://github.com/web-infra-dev/rspack/issues
packages/rspack-test-tools test: Message:  Failed to code generation result for /home/runner/work/rspack/rspack/packages/rspack-test-tools/dist/helper/legacy/fake-update-loader.js??ruleSet[1].rules[0].use[0]!/home/runner/work/rspack/rspack/packages/rspack-test …
```
=> fix: fix panic about runtime order

packages/rspack/etc/api.md, packages/rspack/package.json, pnpm-lock.yaml
This patch updated `zod` to `^3.23.8` to fix a type error related to https://github.com/samchon/typia/issues/1166.
Before upgrading, the `EntryDescription` type gives an output like:
```ts
type EntryDescription = {
import: (string | string[]) & (string | string[] | undefined);
}
```
which will make typia complain.
After upgrading, the `EntryDescription` type gives an output like:
```ts
type EntryDescription = {
import: string | string[];
}
```
which is clean and correct.
See the full changelog at https://github.com/colinhacks/zod/releases.
=> chore(deps): update zod to ^3.23.8

biome.jsonc, packages/rspack-dev-server/src/ansiHTML.ts, packages/rspack-dev-server/src/server.ts, packages/rspack-plugin-react-refresh/src/index.ts, packages/rspack-test-tools/src/helper/legacy/copyDiff.js, packages/rspack-test-tools/src/processor/normal.ts, packages/rspack-test-tools/src/processor/stats.ts, packages/rspack/etc/api.md, packages/rspack/src/Compilation.ts, packages/rspack/src/Compiler.ts, packages/rspack/src/builtin-plugin/css-extract/loader.ts, packages/rspack/src/util/fs.ts, scripts/build-npm.cjs, website/components/builtIns/Table.tsx
=> chore(infra/biome): rule noForEach

crates/rspack_core/src/compiler/mod.rs, crates/rspack_fs/src/async.rs, crates/rspack_fs/src/native.rs, crates/rspack_fs/src/sync.rs, crates/rspack_fs_node/src/async.rs, crates/rspack_fs_node/src/sync.rs
rspack_fs is not object safe now which cause it's hard to box it, remove the generic signature since it's not useful right now
=> fix(fs): remove generic in `FileSystem` trait

crates/rspack_plugin_javascript/src/utils/eval/eval_binary_expr.rs, packages/rspack-test-tools/tests/normalCases/parsing/evaluate-logical/index.js
Fixes #7264 
Fixed cases:
```js
"foobar" || undefined || undefined 
// Expected: `'foobar' || 0 || 0`
//           evaluated `'foobar'`
// Received: `true || 0`
//           evaluated `true`
```
```js
undefined && 'foo' && 'bar'
// Expected: `undefined && 'foo' && 'bar'`
//           evaluated `undefined`
// Received: `false && 0`
//           evaluated `false`
```
=> fix: corrects result for `truthy || any` and `falsy && any`

packages/playground/package.json, packages/rspack-dev-server/package.json, packages/rspack-dev-server/tests/__snapshots__/normalizeOptions.test.ts.snap, packages/rspack/package.json, pnpm-lock.yaml, tests/webpack-test/package.json
1. update `webpack-dev-server` `ws` and related deps version
2. release the semver restrictions `^x.x.x`
3. unify the version of express and @types/ws
https://github.com/web-infra-dev/rspack/issues/7030
https://github.com/webpack/webpack-dev-server/blob/master/migration-v5.md
=> feat(deps)!: update`webpack-dev-server` to v5 and no longer lock the versions

packages/rspack-dev-server/package.json, packages/rspack-dev-server/tests/normalizeOptions.test.ts, pnpm-lock.yaml
ci: fix jest error of rspack-dev-server
node20 can pass the test,
in node 18 or 16, jest test process exited caused by devServer tests
=> ci: fix jest error of rspack-dev-server

crates/rspack_plugin_javascript/src/utils/eval/eval_binary_expr.rs, packages/rspack-test-tools/tests/normalCases/parsing/evaluate-nullish-coalescing/index.js
Align evaluation of `&&`, `||` expression with webpack to reuse the evaluation object, and also support `??`
=> refactor: reuse binary evaluation expression and support null coalescing

crates/rspack_core/src/compiler/make/repair/build.rs, crates/rspack_core/src/context_module.rs, crates/rspack_core/src/dependencies_block.rs, crates/rspack_core/src/module.rs, crates/rspack_core/src/module_graph/mod.rs, crates/rspack_core/src/parser_and_generator.rs, crates/rspack_plugin_javascript/src/parser_plugin/import_parser_plugin.rs, crates/rspack_plugin_javascript/src/parser_plugin/worker_plugin.rs, crates/rspack_plugin_javascript/src/visitors/dependency/mod.rs, crates/rspack_plugin_javascript/src/visitors/dependency/parser/mod.rs, crates/rspack_plugin_lazy_compilation/src/module.rs, crates/rspack_plugin_mf/src/container/container_entry_module.rs, crates/rspack_plugin_mf/src/sharing/consume_shared_module.rs, crates/rspack_plugin_mf/src/sharing/provide_shared_module.rs
`AsyncDependenciesBlock` is of the size of 208 bytes. It was pre-allocated for the capacity of 256:
```
size_of::<AsyncDependenciesBlock>() = 208
```
Taking a project with 10000 modules. It will at least allocate (and destroy) the memory of `256 * 208 * 10000` bytes (507Mbs), causing a memory increment and decrement back and forth.
Since the layout `AsyncDependenciesBlock` is quite compat, two approaches remain:
- Change `Vec<AsyncDependenciesBlock>` to `Vec<Box<AsyncDependenciesBlock>>`
- Change initial capacity of the `Vec` to a smaller value
The first solution is to reduce the memory usage from `256 * 208` to `256 * 24`, giving us a significant memory reduce, however with some potential overhead for sending the value to the heap.
With the second capacity change from `256` to `64`. 
I …
=> perf: reduce large pre-allocations for `JavascriptParser::new`

crates/rspack_core/src/concatenated_module.rs, crates/rspack_plugin_javascript/src/plugin/module_concatenation_plugin.rs
😆 This is my practice using the profile tool for the first time, and here is what I do:
1. Remove unnecessary clones.
2. Remove `ModuleInfoOrReference`, as I find `ModuleInfo` is sufficient and `ModuleInfoOrReference` can be queried using the module id.
3. Replaced `LinkedHashSet` with `IndexSet`. Based on my benchmarking, `IndexSet::insert` and `IndexSet::pop` perform better.
4. Replaced the check `self.modules.iter().any(|item| Some(&item.id) == module_id_of_dep)` in each loop with a pre-constructed `HashSet` to reduce time complexity.
Since my local performance test results are very unstable, if there is a performance regression, I will further modify or close this PR.
=> perf: a bunch of small improvement for ConcatenatedModule

crates/rspack_core/src/module_factory.rs
(Also the heavy computation)
Dependency paths returned from oxc-resolver had already been normalized.
See: https://github.com/oxc-project/oxc-resolver/blob/f4c3ef5b4765ec8fcfb0f0d74a7562a6baa1456c/src/lib.rs#L380
Reduced memory cost for about 28.7% (at peak) for the case of [10000 modules](https://github.com/web-infra-dev/rspack-ecosystem-benchmark/tree/main/cases/10000) (Rspack was compiled with debug profile).
Before:
After:
=> perf: reduce allocation for adding dependencies

packages/rspack/package.json
We don't need to run prebundle for every build, but only when dependencies change.
So moving to `prepare` would work and also speed up the build.
=> chore: run `prebundle` when prepare

Cargo.lock, crates/node_binding/binding.d.ts, crates/rspack_binding_options/src/options/raw_builtins/raw_lightning_css_minimizer.rs, crates/rspack_plugin_lightning_css_minimizer/Cargo.toml, crates/rspack_plugin_lightning_css_minimizer/src/lib.rs, packages/rspack-test-tools/tests/__snapshots__/StatsAPI.test.js.snap, packages/rspack-test-tools/tests/configCases/plugins/minify-exclude-lightning-css/a.css, packages/rspack-test-tools/tests/configCases/plugins/minify-exclude-lightning-css/a.js, packages/rspack-test-tools/tests/configCases/plugins/minify-exclude-lightning-css/b.css, packages/rspack-test-tools/tests/configCases/plugins/minify-exclude-lightning-css/b.js, packages/rspack-test-tools/tests/configCases/plugins/minify-exclude-lightning-css/index.js, packages/rspack-test-tools/tests/configCases/plugins/minify-exclude-lightning-css/rspack.config.js, packages/rspack-test-tools/tests/configCases/plugins/minify-exclude-lightning-css/test.config.js, packages/rspack-test-tools/tests/configCases/plugins/minify-include-lightning-css/a.css, packages/rspack-test-tools/tests/configCases/plugins/minify-include-lightning-css/a.js, packages/rspack-test-tools/tests/configCases/plugins/minify-include-lightning-css/b.css, packages/rspack-test-tools/tests/configCases/plugins/minify-include-lightning-css/b.js, packages/rspack-test-tools/tests/configCases/plugins/minify-include-lightning-css/index.js, packages/rspack-test-tools/tests/configCases/plugins/minify-include-lightning-css/rspack.config.js, packages/rspack-test-tools/tests/configCases/plugins/minify-include-lightning-css/test.config.js, packages/rspack-test-tools/tests/statsAPICases/basic.js, packages/rspack-test-tools/tests/statsAPICases/chunks.js, packages/rspack/etc/api.md, packages/rspack/src/builtin-plugin/LightningCssMiminizerRspackPlugin.ts, website/docs/en/plugins/rspack/lightning-css-minimizer-rspack-plugin.mdx
Implements the missing `include`, `exclude` and `test` options for the `LightningCssMinimizerRspackPlugin`.
Fixes #7135
=> feat: support `test`, `include` and `exclude` options for `LightningCssMinimizerRspackPlugin`

crates/rspack_plugin_library/src/module_library_plugin.rs, packages/rspack-test-tools/tests/configCases/output/library-async-module/index.js, packages/rspack-test-tools/tests/configCases/output/library-async-module/lambda.js, packages/rspack-test-tools/tests/configCases/output/library-async-module/rspack.config.js
🤔 It's confusing why this code is missing.
webpack: https://github.com/webpack/webpack/blob/aa7174671e33cb61b52271d0806a0f7c9e0d08df/lib/library/ModuleLibraryPlugin.js#L83
closes https://github.com/web-infra-dev/rspack/issues/7146
=> fix: add `await` to async module export

packages/rspack-test-tools/tests/configCases/builtin-lightningcss-loader/basic-include/index.js, packages/rspack-test-tools/tests/configCases/builtin-lightningcss-loader/basic-include/index.module.css, packages/rspack-test-tools/tests/configCases/builtin-lightningcss-loader/basic-include/rspack.config.js, packages/rspack/etc/api.md, packages/rspack/src/builtin-loader/lightningcss/index.ts, packages/rspack/src/config/adapterRuleUse.ts, packages/rspack/src/exports.ts, website/docs/en/guide/features/builtin-lightningcss-loader.mdx, website/docs/zh/guide/features/builtin-lightningcss-loader.mdx
Introduce LightningcssFeetureOptions, for better user experince, so user don't have to use import anything from @rspack/core
=> refactor: using object form of lightningcss feature options

website/docs/en/blog/announcing-0-4.mdx, website/docs/zh/blog/announcing-0-4.mdx
just an incorrect description that `builtins.decorator 移动到 jsc.parser.decorator` shoule be `jsc.parser.decorators`
=> docs(blog): correcting the description of decorator configuration in v0.4

packages/rspack/prebundle.config.mjs, packages/rspack/src/lib/CacheFacade.js
Rspack only depend on the `CachedInputFileSystem` module of enhanced-resolve, so we can remove the index chunk because it is not used.
- The startup time will be `6ms` faster:
- Reduced 143KB install size:
=> perf: no need to require entire enhanced-resolve

crates/rspack_plugin_javascript/src/dependency/esm/harmony_export_imported_specifier_dependency.rs, tests/webpack-test/configCases/graph/conditional-reexport/a.js, tests/webpack-test/configCases/graph/conditional-reexport/b.js, tests/webpack-test/configCases/graph/conditional-reexport/lib/common/common.js, tests/webpack-test/configCases/graph/conditional-reexport/lib/common/index.js, tests/webpack-test/configCases/graph/conditional-reexport/lib/index.js, tests/webpack-test/configCases/graph/conditional-reexport/lib/util-a.js, tests/webpack-test/configCases/graph/conditional-reexport/lib/util-b.js, tests/webpack-test/configCases/graph/conditional-reexport/test.config.js, tests/webpack-test/configCases/graph/conditional-reexport/webpack.config.js
https://github.com/webpack/webpack/pull/18611
=> fix: add runtime condition for harmony reexport checked

crates/rspack_core/src/compiler/compilation.rs, crates/rspack_core/src/compiler/make/repair/factorize.rs, crates/rspack_core/src/concatenated_module.rs, crates/rspack_core/src/dependency/runtime_template.rs, crates/rspack_core/src/exports_info.rs, crates/rspack_core/src/module.rs, crates/rspack_plugin_javascript/src/dependency/commonjs/common_js_export_require_dependency.rs, crates/rspack_plugin_javascript/src/dependency/commonjs/common_js_full_require_dependency.rs, crates/rspack_plugin_javascript/src/dependency/esm/harmony_import_dependency.rs, crates/rspack_plugin_javascript/src/dependency/esm/import_dependency.rs, crates/rspack_plugin_javascript/src/plugin/flag_dependency_exports_plugin.rs, crates/rspack_plugin_javascript/src/plugin/module_concatenation_plugin.rs, crates/rspack_plugin_javascript/src/plugin/side_effects_flag_plugin.rs
`max_target` is a cache for cacheing the result of `get_max_target`, actually in most cases, `get_max_target` will just return `export_info.target` (the fast path), and in slow path, the calculate is not complex at all (checkout https://github.com/webpack/webpack/pull/13068), so remove the cache to let `get_max_target` require a `&ModuleGraph`, and we don't need the `ModuleGraphAccessor` anymore
=> refactor: remove module graph accessor

website/docs/en/api/objects/compilation.mdx, website/docs/en/api/plugin-api/compiler-hooks.mdx, website/docs/en/types/compilation.mdx, website/docs/zh/api/objects/compilation.mdx, website/docs/zh/api/plugin-api/compiler-hooks.mdx, website/docs/zh/types/compilation.mdx
Update documents of compiler hooks. 
Perhaps we need a overview picture of all compiler/compilation hooks
=> docs: update compiler hooks

website/docs/en/config/optimization.mdx, website/docs/en/guide/tech/solid.mdx, website/docs/en/guide/tech/svelte.mdx, website/docs/en/guide/tech/vue.mdx, website/docs/zh/config/optimization.mdx, website/docs/zh/guide/tech/solid.mdx, website/docs/zh/guide/tech/svelte.mdx, website/docs/zh/guide/tech/vue.mdx
fix: remove outdated builtin config docs
=> fix: remove outdated builtin config docs

packages/rspack/src/stats/StatsFactory.ts, packages/rspack/src/util/comparators.ts
=> refactor(typescript): packages/rspack/src/util/StatsFactory

packages/rspack/src/logging/truncateArgs.ts
=> refactor(typescript): packages/rspack/src/logging-truncateArgs

biome.jsonc, packages/rspack-test-tools/etc/api.md, packages/rspack-test-tools/src/compiler.ts, packages/rspack-test-tools/src/type.ts, packages/rspack/module.d.ts
=> chore(infra/biome): enable noConstEnum

crates/rspack_plugin_library/src/modern_module_library_plugin.rs, packages/rspack-test-tools/tests/__snapshots__/Config.test.js.snap, packages/rspack-test-tools/tests/configCases/library/modern-module-force-concaten/d.mjs, packages/rspack-test-tools/tests/configCases/library/modern-module-force-concaten/e/bar.cjs, packages/rspack-test-tools/tests/configCases/library/modern-module-force-concaten/e/foo.js, packages/rspack-test-tools/tests/configCases/library/modern-module-force-concaten/e/index.js, packages/rspack-test-tools/tests/configCases/library/modern-module-force-concaten/rspack.config.js
- Using module's concatenate bailout reason to filter out module to trigger force concatation.
- Compat with export with `a.b` and `(some_cjs())` final_name. Directly detecting invalid characters to fallback to `module` style export. It's not elegant, but I think it should work in most cases.
```js
var __webpack_exports__bar = (bar_default());
export { foo, __webpack_exports__bar as bar };
```
=> fix(modern-module): compat with more export cases

crates/node_binding/binding.d.ts, crates/rspack_binding_values/src/chunk_group.rs, packages/rspack-test-tools/tests/configCases/plugins/compilation-chunk-groups/rspack.config.js, packages/rspack/etc/api.md, packages/rspack/src/ChunkGroup.ts, website/docs/en/types/chunk-group.mdx, website/docs/en/types/entrypoint.mdx, website/docs/zh/types/chunk-group.mdx, website/docs/zh/types/entrypoint.mdx
Close https://github.com/web-infra-dev/rspack/issues/7334
Add `compilation.chunkGroups[].inInitial()` and `compilation.entrypoints[].inInitial()` to check whether this chunk group / entrypoint will be loaded on initial page load.
=> feat: support `compilation.chunkGroup[].isInitial()`

crates/node_binding/binding.d.ts, crates/rspack_binding_options/src/options/raw_builtins/raw_mf.rs, crates/rspack_plugin_mf/src/sharing/consume_shared_plugin.rs, crates/rspack_plugin_mf/src/sharing/provide_shared_dependency.rs, crates/rspack_plugin_mf/src/sharing/provide_shared_module.rs, crates/rspack_plugin_mf/src/sharing/provide_shared_module_factory.rs, crates/rspack_plugin_mf/src/sharing/provide_shared_plugin.rs, crates/rspack_plugin_mf/src/sharing/share_runtime_module.rs, packages/rspack-test-tools/tests/configCases/container-1-5/provide-sharing-extra-data/App.js, packages/rspack-test-tools/tests/configCases/container-1-5/provide-sharing-extra-data/index.js, packages/rspack-test-tools/tests/configCases/container-1-5/provide-sharing-extra-data/node_modules/react.js, packages/rspack-test-tools/tests/configCases/container-1-5/provide-sharing-extra-data/rspack.config.js, packages/rspack-test-tools/tests/configCases/container-1-5/provide-sharing-extra-data/test.config.js, packages/rspack/etc/api.md, packages/rspack/src/container/default.runtime.js, packages/rspack/src/sharing/ProvideSharedPlugin.ts, packages/rspack/src/sharing/SharePlugin.ts
fix https://github.com/idonava/base-mf-app/issues/1
=> fix(mf2): extra provide sharing data

crates/rspack_plugin_javascript/src/visitors/dependency/parser/walk.rs, packages/rspack-test-tools/tests/normalCases/parsing/ctor-import-asi/index.js, packages/rspack-test-tools/tests/normalCases/parsing/ctor-import-asi/util.js
webpack only directly call `walkBlockStatement` at `walkStatement` and `walkClass`(StaticBlock).
The difference between calling directly and calling via `walk_statement` is that `walk_statement` updates the `statement_path` and `prev_statement` in `enter_statement`.
Omitting to update `prev_statement` results in `asi_safe` error, which causes an unexpected semicolon to be inserted after the comma in the `SequentialStatement`.
closes https://github.com/web-infra-dev/rspack/issues/7397
=> fix: change some `walk_block_statement` to `walk_statement`

packages/playground/cases/react/worker/src/worker.js
This error was introduced by #7387 , which incorrectly used the global `window` object in a `Web Worker` context.
=> fix(playground/cases): replace window.onmessage with self.onmessage in worker test case

website/docs/en/api/javascript-api/_meta.json, website/docs/en/api/javascript-api/cache.mdx, website/docs/en/api/javascript-api/compilation.mdx, website/docs/en/api/javascript-api/compiler.mdx, website/docs/en/api/javascript-api/logger.mdx, website/docs/en/api/javascript-api/stats-json.mdx, website/docs/en/types/input-file-system.mdx, website/docs/en/types/output-file-system.mdx, website/docs/en/types/watch-file-system.mdx, website/docs/zh/api/javascript-api/_meta.json, website/docs/zh/api/javascript-api/compiler.mdx, website/docs/zh/api/javascript-api/logger.mdx, website/docs/zh/types/input-file-system.mdx, website/docs/zh/types/logger.mdx, website/docs/zh/types/output-file-system.mdx, website/docs/zh/types/watch-file-system.mdx, website/project-words.txt
=> docs: add compiler api

packages/rspack/etc/api.md, packages/rspack/src/index.ts, packages/rspack/src/lib/LoaderOptionsPlugin.ts, packages/rspack/src/util/assertNotNil.ts
ci(infra/type): add type-coverage
The type coverage of each file needs to be >= 80%
https://github.com/web-infra-dev/rspack/issues/7225
=> refactor(type): increase type-coverage

README.md, website/package.json, website/pnpm-lock.yaml, website/theme/components/Benchmark/index.tsx, website/theme/components/ToolStack/ToolStack.tsx, website/theme/index.tsx, website/tsconfig.json
Update dependencies and fix tsconfig paths:
- bump Rspress 1.27.0
- Replace doc UI with `@rstack-dev/doc-ui`.
- Fix the alias errors in MDX:
=> docs: update dependencies and fix tsconfig paths

packages/rspack-plugin-react-refresh/src/index.ts, packages/rspack-plugin-react-refresh/src/sockets/WDSSocket.ts, packages/rspack-plugin-react-refresh/src/sockets/utils/getCurrentScriptSource.ts, packages/rspack-plugin-react-refresh/src/sockets/utils/getSocketUrlParts.ts, packages/rspack-plugin-react-refresh/src/sockets/utils/getUrlFromParts.ts, packages/rspack-plugin-react-refresh/src/sockets/utils/getWDSMetadata.ts, packages/rspack-plugin-react-refresh/src/utils/getSocketIntegration.ts
=> refactor(typescript): increase typescript type coverage to 100% for rspack-plugin-react-refresh

packages/rspack-dev-server/etc/api.md, packages/rspack-dev-server/src/server.ts, packages/rspack-dev-server/tsconfig.json, packages/rspack/etc/api.md, packages/rspack/src/exports.ts, packages/rspack/tsconfig.json
I was looking in a convenient way of getting the version of the `@rsapck/dev-server` similar to what is available in `@rspack/core`
Export version from `package.json` (similar to the `@rspack/core`)
=> feat(dev-server): export package version

website/docs/en/config/experiments.mdx, website/docs/en/guide/tech/css.mdx, website/docs/zh/config/experiments.mdx, website/docs/zh/guide/tech/css.mdx
add guide for different CSS usages:
- experiments.css
- CssExtractRspackPlugin
- style-loader
=> docs: add guide for different CSS usages

Cargo.lock, Cargo.toml, packages/rspack-test-tools/tests/configCases/source-map/empty-mapping/index.js, packages/rspack-test-tools/tests/configCases/source-map/empty-mapping/loader.js, packages/rspack-test-tools/tests/configCases/source-map/empty-mapping/rspack.config.js
close #7438
see https://github.com/web-infra-dev/rspack-sources/pull/102
=> fix: map of empty file should have mappings field

crates/rspack_binding_options/src/options/raw_module/mod.rs, crates/rspack_core/src/normal_module_factory.rs, crates/rspack_core/src/options/module.rs, crates/rspack_core/src/utils/module_rules.rs, packages/rspack-test-tools/tests/configCases/module/merge-resolve/index.js, packages/rspack-test-tools/tests/configCases/module/merge-resolve/modules/lib/package.json, packages/rspack-test-tools/tests/configCases/module/merge-resolve/modules/lib/right.js, packages/rspack-test-tools/tests/configCases/module/merge-resolve/modules/lib/wrong.js, packages/rspack-test-tools/tests/configCases/module/merge-resolve/modules/lib2/package.json, packages/rspack-test-tools/tests/configCases/module/merge-resolve/modules/lib2/right.js, packages/rspack-test-tools/tests/configCases/module/merge-resolve/modules/lib2/wrong.js, packages/rspack-test-tools/tests/configCases/module/merge-resolve/reexports.js, packages/rspack-test-tools/tests/configCases/module/merge-resolve/rspack.config.js
- fix deep merge module resolve options
- optimize perf with ModuleRuleEffect, we only need ModuleRuleEffect when calculate_module_xxx, and this will be helpful for debugging `dbg!(rules)`
=> fix: deep merge module resolve options

website/docs/en/guide/optimization/code-splitting.mdx, website/docs/zh/guide/optimization/code-splitting.mdx
Fix some incorrect statements of code splitting and splitChunks. SplitChunks is mainly used for `split` instead of `deduplication`
Remove unnecessary output configuration
Add a description of how name affects the output
=> docs: correct some statements of code splitting and splitChunks

Cargo.lock, crates/rspack_core/src/external_module.rs, crates/rspack_plugin_externals/Cargo.toml, crates/rspack_plugin_externals/src/plugin.rs, packages/rspack-test-tools/tests/defaultsCases/experiments/output-module.js, packages/rspack/etc/api.md, packages/rspack/src/config/defaults.ts, packages/rspack/src/config/zod.ts, tests/webpack-test/configCases/externals/concatenated-module/index.js, tests/webpack-test/configCases/externals/concatenated-module/webpack.config.js, website/docs/en/config/externals.mdx, website/docs/zh/config/externals.mdx
Port https://github.com/webpack/webpack/pull/18620.
Changes overview:
1. add `module-import` external type.
2. change external type to `module-import` by default when `output.module` is enabled (not all cases could be ported as we lack other feature supports at preset).
3. sync up documentation.
**Potentially problematic changes:**
Added `rspack_plugin_javascript` to the dep of `rspack_plugin_externals` to use some variables, is it ok to do so?
```toml
rspack_plugin_javascript = { path = "../rspack_plugin_javascript" }
```
=> feat: port "module-import" external type

crates/rspack_core/src/dependency/dependency_template.rs, crates/rspack_core/src/external_module.rs, crates/rspack_core/src/init_fragment.rs, crates/rspack_plugin_javascript/src/dependency/esm/external_module_dependency.rs, crates/rspack_plugin_javascript/src/dependency/esm/mod.rs, crates/rspack_plugin_javascript/src/dependency/esm/provide_dependency.rs, crates/rspack_plugin_javascript/src/parser_plugin/node_stuff_plugin.rs, crates/rspack_plugin_javascript/src/plugin/api_plugin.rs, crates/rspack_plugin_javascript/src/runtime.rs, packages/rspack/etc/api.md, packages/rspack/src/config/defaults.ts, packages/rspack/src/config/zod.ts, tests/webpack-test/configCases/output-module/node-globals/cjs/file.js, tests/webpack-test/configCases/output-module/node-globals/cjs/package.json, tests/webpack-test/configCases/output-module/node-globals/index.js, tests/webpack-test/configCases/output-module/node-globals/test.config.js, tests/webpack-test/configCases/output-module/node-globals/webpack.config.js, website/docs/en/config/node.mdx, website/docs/zh/config/node.mdx
Port https://webpack.js.org/configuration/node/#root:~:text=%27node%2Dmodule%27%3A%20Replace%20__filename%20in%20CommonJS%20modules%20to%20fileURLToPath(import.meta.url)%20when%20output.module%20is%20enabled.
Rename the former `ExternalModule` enum to `ModuleExternal` in `InitFragmentKey` (https://github.com/webpack/webpack/blob/main/lib/ExternalModule.js#L225), and add new `ExternalModule` type (https://github.com/webpack/webpack/blob/main/lib/dependencies/ExternalModuleInitFragment.js#L20) to comply with webpack's naming.
Resolve https://github.com/web-infra-dev/rslib/issues/32.
=> feat(node-stuff): implement `node-module` shim

biome.jsonc, packages/rspack-test-tools/src/processor/multi.ts, packages/rspack-test-tools/src/test/context.ts, packages/rspack/src/stats/StatsFactory.ts
=> chore(infra/biome): enable noAccumulatingSpread

.github/renovate.json5
Enable the dependency dashboard of renovate, this can help us to have an overview of Rspack's dependency status.
Ref:
- https://docs.renovatebot.com/key-concepts/dashboard/
- https://github.com/web-infra-dev/rsbuild/issues/1316
=> chore(workflow): enable dependency dashboard of renovate

crates/rspack_plugin_library/src/modern_module_library_plugin.rs, packages/rspack-test-tools/tests/configCases/library/modern-module-export-char/foo.cjs, packages/rspack-test-tools/tests/configCases/library/modern-module-export-char/index.js, packages/rspack-test-tools/tests/configCases/library/modern-module-export-char/rspack.config.js
Detect mode invalid chars when exporting in `modern-module` and add test cases.
=> fix(modern-module): export syntax detect more invalid chars

crates/node_binding/binding.d.ts, crates/rspack_binding_options/src/options/raw_split_chunks/mod.rs, crates/rspack_core/src/exports_info.rs, crates/rspack_plugin_split_chunks/src/options/cache_group.rs, crates/rspack_plugin_split_chunks/src/plugin/module_group.rs, packages/rspack-test-tools/tests/__snapshots__/Defaults.test.js.snap, packages/rspack-test-tools/tests/configCases/split-chunks/used-exports/bar.js, packages/rspack-test-tools/tests/configCases/split-chunks/used-exports/foo.js, packages/rspack-test-tools/tests/configCases/split-chunks/used-exports/rspack.config.js, packages/rspack-test-tools/tests/configCases/split-chunks/used-exports/shared.js, packages/rspack-test-tools/tests/defaultsCases/mode/production.js, packages/rspack-test-tools/tests/defaultsCases/mode/undefined.js, packages/rspack/etc/api.md, packages/rspack/src/config/defaults.ts, packages/rspack/src/config/zod.ts, tests/webpack-test/__snapshots__/StatsTestCases.basictest.js.snap, website/docs/en/plugins/webpack/split-chunks-plugin.mdx, website/docs/zh/plugins/webpack/split-chunks-plugin.mdx
We have runtime optimization for used exports, for example when we have two entries named `foo` and `bar`, and a shared module `shared` which exports 2 values `foo` and `bar`.
`foo` imports `foo` from `shared`
`bar` imports `bar` from `shared`
with default behavior, there will be 2 `shared` modules in the final output, one contains only `foo` export for `foo` entry, and one contains only `bar` export for `bar` entry.
This is great. But when it comes to splitChunks, there will be problem.
if we have a cacheGroup that can select `shared`, then the `shared` module maybe extracted into a separate chunk, thus the runtime optimization is gone.
Now if you enable `splitChunks.usedExports`, when `shared` module is selected by a cacheGroup, the cacheGroup will calculate all possible combinations of …
=> feat: splitChunks support usedExports

crates/rspack_plugin_library/src/modern_module_library_plugin.rs, packages/rspack-test-tools/tests/__snapshots__/Config.test.js.snap, packages/rspack-test-tools/tests/configCases/library/modern-module-force-concaten/f/bar.cjs, packages/rspack-test-tools/tests/configCases/library/modern-module-force-concaten/f/foo.js, packages/rspack-test-tools/tests/configCases/library/modern-module-force-concaten/f/index.js, packages/rspack-test-tools/tests/configCases/library/modern-module-force-concaten/rspack.config.js
Should access `optimization_bailout` from mgm to get the final bailout reason vec.
=> fix(modern-module): correct use bailout reason

crates/node_binding/binding.d.ts, crates/rspack_binding_values/src/stats.rs, crates/rspack_core/src/stats/mod.rs, crates/rspack_core/src/stats/struct.rs, crates/rspack_core/src/stats/utils.rs, packages/rspack-test-tools/tests/__snapshots__/StatsAPI.test.js.snap, packages/rspack-test-tools/tests/statsAPICases/chunk-group.js, packages/rspack-test-tools/tests/statsAPICases/placeholders.js, packages/rspack/etc/api.md, packages/rspack/src/stats/DefaultStatsFactoryPlugin.ts, packages/rspack/src/stats/statsFactoryUtils.ts, website/docs/en/api/javascript-api/stats-json.mdx, website/docs/zh/api/javascript-api/stats-json.mdx
- Add `stats.chunkGroups[].childAssets`
- Split the big stats rust file
- Update docs
=> feat: support `stats.chunkGroup[].childAssets`

packages/rspack/etc/api.md, packages/rspack/src/node/NodeWatchFileSystem.ts, packages/rspack/src/util/fs.ts
=> refactor(typescript): packages/rspack/src/node/NodeWatchFileSystem

crates/rspack_core/src/concatenated_module.rs
https://github.com/webpack/webpack/blob/86272e48496d8e958dfdf143c80e9211552540c6/lib/optimize/ConcatenatedModule.js#L1127
I didn't find a case to test it, since I don't know when there will have different runtime here and still didn't bailout for concatenation
=> fix: use intersection runtime for concat module code gen

crates/rspack_plugin_runtime/src/helpers.rs
chunk hash may be unstable when entrypoint has multiple chunks, because hashmap cannot guarrenty the iter order
=> fix: chunk hash unstable

crates/rspack_plugin_javascript/src/visitors/semicolon.rs, packages/rspack-test-tools/tests/normalCases/parsing/asi/index.js
ref: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#automatic_semicolon_insertion and [acorn](https://github.com/acornjs/acorn/blob/master/acorn/src/statement.js) (search `this.semicolon()`)
But I dont know how to construct the test case for ClassField
closes https://github.com/web-infra-dev/rspack/issues/7527
=> fix: should insert semi after import, export, debugger and class field

crates/rspack_plugin_javascript/src/visitors/dependency/parser/walk.rs, packages/rspack-test-tools/tests/normalCases/parsing/super-member-call/a.js, packages/rspack-test-tools/tests/normalCases/parsing/super-member-call/index.js
Webpack reguard `super[foo]()` as MemberExpression, but swc distinguishes them. So there should be an extra check.
closes https://github.com/web-infra-dev/rspack/issues/7477
=> fix: check SuperProp in walk_call_expression

crates/rspack_core/src/external_module.rs
The code deleted in this pull request is located at [here](https://github.com/webpack/webpack/blob/001cab14692eb9a833c6b56709edbab547e291a1/lib/ExternalModule.js#L362) in webpack. However, the code will never be called in Rspack because it is not fully implemented. I am deleting it now to reduce the runtime code for Rslib, and we can reimplement it when we are ready.
Additionally, I attempted to delete the corresponding code in webpack, but no CI tests were broken.
=> fix: remove useless "module" external runtime

crates/node_binding/src/lib.rs, crates/rspack_core/src/compiler/mod.rs
Simplify the rust api interface, generate resolver_factory in compiler
=> fix(rust-core): no need to pass resolve_factory when using rust api

website/components/Columns.tsx, website/components/Mermaid.scss, website/components/Mermaid.tsx, website/docs/en/api/plugin-api/compiler-hooks.mdx, website/docs/zh/api/plugin-api/compiler-hooks.mdx, website/package.json, website/pnpm-lock.yaml, website/rspress.config.ts
Add overview chart for compiler hooks.
=> docs: add overview flow chart for compiler hooks

packages/rspack-cli/src/cli.ts
Fixes #7536 
Since rspack core handles entry defaults well, we no longer need to set a default entry from the cli.
=> fix(cli): wrong entry defaults from cli

website/docs/en/guide/features/loader.mdx, website/docs/en/guide/features/module-resolution.mdx, website/docs/en/guide/start/introduction.mdx, website/docs/zh/guide/features/loader.mdx, website/docs/zh/guide/features/module-resolution.mdx, website/docs/zh/guide/start/introduction.mdx
polish some words in introduction
=> chore: polish some words on introduction

website/docs/en/guide/compatibility/_meta.json, website/docs/en/guide/compatibility/examples.mdx, website/docs/en/guide/compatibility/plugin.mdx, website/docs/zh/guide/compatibility/_meta.json, website/docs/zh/guide/compatibility/examples.mdx, website/docs/zh/guide/compatibility/plugin.mdx
The `examples` page is no longer important, users can directly view the plugin's readme or rspack-example repository.
=> docs: remove examples page

website/package.json, website/pnpm-lock.yaml, website/rspress.config.ts
1. upgrade to 1.28.0
2. use x logo to replace twitter logo
3. enable ssg.strict
=> feat: upgrade rspress version

crates/rspack_plugin_javascript/src/parser_plugin/compatibility_plugin.rs, packages/rspack-test-tools/tests/configCases/parsing/nested-webpack-require/index.js, packages/rspack-test-tools/tests/configCases/parsing/nested-webpack-require/lib.js, packages/rspack-test-tools/tests/configCases/parsing/nested-webpack-require/lib2.js, packages/rspack-test-tools/tests/configCases/parsing/nested-webpack-require/rspack.config.js
=> fix: avoid inner graph top level symbol for nested __webpack_require__

crates/rspack_plugin_javascript/src/parser_plugin/node_stuff_plugin.rs
In previous implementation, when there's a `.` in the path, the `__webpack_fileURLToPath__(temp + '/..').slice(0, -1)
` will change like this:
```txt
file:///Users/abc/.pnpm/index.js
-- after __webpack_fileURLToPath__(temp + '/..') -->
/Users/abc/.pnpm/index.js/..
-- after slice(0, -1) -->
/Users/abc/.pnpm/index.js/.
```
Use the commonly used and battle tested way, also used by tsup https://github.com/egoist/tsup/blob/49c11c3073ce977a01c84e7848fc070d5de0a652/assets/esm_shims.js.
=> fix(node-stuff): use more conventional shim method

website/docs/en/guide/optimization/profile.mdx, website/docs/zh/guide/optimization/profile.mdx
Explain some common performance bottlenecks when using Rspack. It should help users to optimize the build performance when migrating from a webpack-based project.
=> docs: add performance bottlenecks

Cargo.lock, crates/node_binding/binding.d.ts, crates/rspack_binding_options/Cargo.toml, crates/rspack_binding_options/src/options/raw_builtins/mod.rs, crates/rspack_plugin_no_emit_on_errors/Cargo.toml, crates/rspack_plugin_no_emit_on_errors/src/lib.rs, packages/rspack-test-tools/tests/__snapshots__/Defaults.test.js.snap, packages/rspack-test-tools/tests/__snapshots__/StatsOutput.test.js.snap, packages/rspack-test-tools/tests/configCases/hooks/should-emit-1/rspack.config.js, packages/rspack-test-tools/tests/configCases/hooks/should-emit-2/rspack.config.js, packages/rspack-test-tools/tests/defaultsCases/mode/production.js, packages/rspack-test-tools/tests/defaultsCases/mode/undefined.js, packages/rspack/etc/api.md, packages/rspack/src/builtin-plugin/NoEmitOnErrorsPlugin.ts, packages/rspack/src/builtin-plugin/index.ts, packages/rspack/src/config/defaults.ts, packages/rspack/src/config/zod.ts, packages/rspack/src/exports.ts, packages/rspack/src/rspackOptionsApply.ts, tests/webpack-test/TestCases.template.js, tests/webpack-test/__snapshots__/StatsTestCases.basictest.js.snap, tests/webpack-test/checkArrayExpectation.js, website/components/PluginSupportStatusTable.tsx, website/docs/en/config/optimization.mdx, website/docs/en/plugins/webpack/_meta.json, website/docs/en/plugins/webpack/no-emit-on-errors-plugin.mdx, website/docs/zh/config/optimization.mdx, website/docs/zh/plugins/webpack/_meta.json, website/docs/zh/plugins/webpack/no-emit-on-errors-plugin.mdx, website/project-words.txt
- Add NoEmitOnErrorsPlugin to support `optimization.emitOnErrors`
- [Breaking] Enable this plugin when mode=`production`(means not to emit assets when error occurs in production mode)
=> feat!: support `optimization.emitOnErrors`

crates/rspack_binding_options/src/options/raw_builtins/mod.rs, crates/rspack_plugin_html/src/plugin.rs, tests/plugin-test/html-plugin/basic.test.js
=> feat(html): improve error handling

crates/rspack_binding_values/src/codegen_result.rs, crates/rspack_core/src/build_chunk_graph/code_splitter.rs, crates/rspack_core/src/chunk.rs, crates/rspack_core/src/chunk_graph/chunk_graph_module.rs, crates/rspack_core/src/compiler/compilation.rs, crates/rspack_core/src/compiler/hmr.rs, crates/rspack_core/src/compiler/module_executor/execute.rs, crates/rspack_core/src/old_cache/mod.rs, crates/rspack_core/src/old_cache/occasion/code_generate.rs, crates/rspack_core/src/old_cache/occasion/mod.rs, crates/rspack_core/src/old_cache/occasion/process_runtime_requirements.rs, crates/rspack_core/src/runtime.rs, crates/rspack_plugin_runtime/src/runtime_plugin.rs
speed up a little bit about process runtime requirements when hmr
- will improve it to incremental to avoid cache read and cache compare in the future PR
=> feat: add cache for process runtime requirements

Cargo.lock, crates/rspack_plugin_warn_sensitive_module/Cargo.toml, crates/rspack_plugin_warn_sensitive_module/src/lib.rs
For [9000](https://github.com/rspack-contrib/rspack-incremental-bench/tree/2966a89339890c414dcf265fb862a23033d4e5e2/cases/9000) case (without case sensitive path, which is the common case in development), 8ms -> 4ms
And now this plugin will increase 1ms per 2000 modules, which is acceptable for now, we can consider to move it as production only plugin by default when it becomes the bottleneck
=> perf: warn case sensitive plugin

website/docs/en/guide/migration/webpack.mdx, website/docs/en/guide/tech/vue.mdx, website/docs/zh/guide/migration/webpack.mdx, website/docs/zh/guide/tech/vue.mdx
Users should keep webpack dependency in some cases.
resolve https://github.com/web-infra-dev/rspack/issues/7598
=> docs: keep webpack dependency in some cases

crates/rspack_plugin_javascript/src/visitors/semicolon.rs
fix #7611 
1. We don't need to insert a semicolon for ExportDefaultDeclaration:
```js
export default function () {} // No need to insert a semicolon
export default class MyClass {}
```
2. For ExportDeclaration, when a semicolon needs to be inserted, the corresponding Visit will be triggered:
```js
export function foo() {} // No need to insert a semicolon
export const bar = 42 // It will call visit_var_decl to insert a semicolon
```
=> fix: remove the unnecessary logic for inserting semicolons

packages/rspack-test-tools/tests/normalCases/parsing/asi/index.js
Added some case for asi.
The following case is also failed in webpack:
```js
import { foo } from "./a"
export const fooC = foo
d(), foo();
```
which transformed into:
```js
export const fooC = foo
d(), ;(0, xxx.foo)();
```
so as the case:
```js
export default (function Foo() {})
d(), foo();
```
which should be fixed on webpack side as well.
=> test: add more test cases for asi with sequence expressions

packages/rspack/etc/api.md, packages/rspack/src/lib/EnvironmentPlugin.ts
Currently, using `EnvironmentPlugin` from `@rspack/core` will have TS error:
```ts
new EnvironmentPlugin({
FOO: null, // Type 'null' is not assignable to type 'string | undefined'.ts(2345)
})
```
But using `null` as the default value is allowed. Quoted from Rspack website:
> Default values of null and undefined behave differently. Use undefined for variables that must be provided during bundling, or null if they are optional.
> https://rspack.dev/plugins/webpack/environment-plugin
=> fix: allow `null` and `undefined` in EnvironmentPlugin

packages/rspack/src/Compilation.ts
Webpack uses a separate `Compilation.assetInfo` to store `AssetInfo`. An empty object will be passed to the first argument `assetInfoUpdateOrFunction` if it's a `function`. [Ref](https://github.com/webpack/webpack/blob/6be4065ade1e252c1d8dcba4af0f43e32af1bdc1/lib/Compilation.js#L4348).
Rspack will always store a default `AssetInfo` if nothing is provided. This makes these two implementation(webpack and rspack) almost the same(both results in nullish values per request). So here I removed the comment.
=> chore: remove `Compilation.updateAsset` comment

Cargo.lock, Cargo.toml, crates/rspack_plugin_devtool/Cargo.toml, crates/rspack_plugin_devtool/src/eval_dev_tool_module_plugin.rs, crates/rspack_plugin_devtool/src/eval_source_map_dev_tool_plugin.rs
using simd_json to convert string to json string, the improvement is small, but better than current, especially if the number of modules is super large.
encoding url always allocate new string, but in most cases there is no replacement at all, so using Cow to avoid unnessary allocation here.
here is the improvement I saw with my MacBook Pro M1, using this [repo](https://github.com/rspack-contrib/rspack-incremental-bench), CASE=9000
=> perf: improve performance of eval-source-map

crates/rspack_core/src/build_chunk_graph/code_splitter.rs, crates/rspack_core/src/chunk_group.rs, crates/rspack_core/src/context_module.rs, crates/rspack_core/src/dependencies_block.rs, crates/rspack_core/src/dependency/dependency_location.rs, crates/rspack_core/src/lib.rs, crates/rspack_core/src/stats/mod.rs, crates/rspack_plugin_javascript/src/dependency/commonjs/common_js_require_dependency.rs, crates/rspack_plugin_javascript/src/dependency/commonjs/require_header_dependency.rs, crates/rspack_plugin_javascript/src/parser_plugin/common_js_imports_parse_plugin.rs, crates/rspack_plugin_javascript/src/parser_plugin/compatibility_plugin.rs, crates/rspack_plugin_javascript/src/parser_plugin/import_parser_plugin.rs, crates/rspack_plugin_javascript/src/parser_plugin/worker_plugin.rs, crates/rspack_plugin_javascript/src/utils/eval/eval_binary_expr.rs, crates/rspack_plugin_javascript/src/utils/eval/mod.rs, crates/rspack_plugin_lazy_compilation/src/module.rs, packages/rspack-test-tools/tests/diagnosticsCases/factorize/cannot-resolve-with-loader/stats.err, packages/rspack-test-tools/tests/diagnosticsCases/factorize/empty-dependency/stats.err, packages/rspack-test-tools/tests/diagnosticsCases/factorize/mismatched-module-type/stats.err, packages/rspack-test-tools/tests/statsAPICases/chunks.js, tests/webpack-test/__snapshots__/StatsTestCases.basictest.js.snap
=> refactor: resolve conflicts for dependency location

packages/rspack-test-tools/tests/configCases/container-1-5/provide-sharing-extra-data/index.js, packages/rspack/src/container/default.runtime.js
correct mf shared options, align with webpack behavior 
https://github.com/module-federation/core/blob/main/packages/enhanced/src/lib/sharing/ProvideSharedModule.ts#L211
=> fix(mf2): correct mf shared options

Cargo.lock, Cargo.toml, packages/rspack-test-tools/tests/configCases/builtin-swc-loader/input-source-map-cheap-module/a.jsx, packages/rspack-test-tools/tests/configCases/builtin-swc-loader/input-source-map-cheap-module/index.js, packages/rspack-test-tools/tests/configCases/builtin-swc-loader/input-source-map-cheap-module/prev-loader.js, packages/rspack-test-tools/tests/configCases/builtin-swc-loader/input-source-map-cheap-module/rspack.config.js, packages/rspack-test-tools/tests/configCases/builtin-swc-loader/input-source-map-module/a.jsx, packages/rspack-test-tools/tests/configCases/builtin-swc-loader/input-source-map-module/index.js, packages/rspack-test-tools/tests/configCases/builtin-swc-loader/input-source-map-module/prev-loader.js, packages/rspack-test-tools/tests/configCases/builtin-swc-loader/input-source-map-module/rspack.config.js
Synced upstream SWC source map fix.
> [!NOTE]
> Wasm plugins are not being broken as this upgrade does not contain a breaking AST change according to https://swc.rs/docs/plugin/selecting-swc-core
Added `inputSourceMap` test to avoid it being broken again.
closes https://github.com/web-infra-dev/rspack/issues/7636
=> fix: wrong `builtin:swc-loader` source maps if `inputSourceMap` is provided

website/docs/en/plugins/rspack/html-rspack-plugin.mdx, website/docs/zh/plugins/rspack/html-rspack-plugin.mdx
because rspack use dojang in htmlRspackPlugin which implement subset of ejs template engine, but Rspack itself doesn't plan to support or guarantee full ejs syntax in htmlRspackPlugin, add notice about this limitation.
add full supported ejs syntax in docs and add related test in html-plugin tests in following pr
=> docs: add notice about htmlRspackPlugin not support ejs syntax

website/docs/en/guide/start/quick-start.mdx, website/docs/zh/guide/start/quick-start.mdx
=> fix: rslib link should be its github repo

packages/rspack-test-tools/tests/configCases/container-1-5/share-strategy/App.js, packages/rspack-test-tools/tests/configCases/container-1-5/share-strategy/index.js, packages/rspack-test-tools/tests/configCases/container-1-5/share-strategy/node_modules/react.js, packages/rspack-test-tools/tests/configCases/container-1-5/share-strategy/rspack.config.js, packages/rspack-test-tools/tests/configCases/container-1-5/share-strategy/test.config.js, packages/rspack/etc/api.md, packages/rspack/src/container/ModuleFederationPlugin.ts, packages/rspack/src/container/default.runtime.js, website/docs/en/plugins/webpack/module-federation-plugin-v1.mdx, website/docs/en/plugins/webpack/module-federation-plugin.mdx, website/docs/zh/plugins/webpack/module-federation-plugin-v1.mdx, website/docs/zh/plugins/webpack/module-federation-plugin.mdx
Add `shareStrategy` option .
related mf pr: https://github.com/module-federation/core/pull/2870
=> feat(mf2): add shareStrategy

Cargo.lock, crates/rspack_plugin_html/Cargo.toml, crates/rspack_plugin_html/src/plugin.rs, packages/rspack-test-tools/tests/configCases/builtins/html-param-not-found/errors.js, packages/rspack-test-tools/tests/configCases/builtins/html-param-not-found/index.js, packages/rspack-test-tools/tests/configCases/builtins/html-param-not-found/rspack.config.js, tests/plugin-test/html-plugin/basic.test.js
close https://github.com/web-infra-dev/rspack/issues/3770. 
Now rspack will also emit an error into compilation when parameter is not found, just like html-webpack-plugin.
=> fix(html): emit error when param not found

packages/rspack/src/container/default.runtime.js
initializeSharingInitTokens should be object
=> fix(mf2): initializeSharingInitTokens should be object

Cargo.lock, Cargo.toml, crates/node_binding/binding.d.ts, crates/rspack_plugin_html/Cargo.toml, crates/rspack_plugin_html/src/plugin.rs, tests/plugin-test/html-plugin/basic.test.js, website/docs/en/plugins/rspack/html-rspack-plugin.mdx, website/docs/zh/plugins/rspack/html-rspack-plugin.mdx
BREAKING CHANGE:
Rspack's default template syntax is same as ejs and webpack's default template syntax is lodash.template, while rsbuild's default template syntax is same as lodash.template too.
This PR change Rspack's default template syntax about escape | unescape to lodash.template which is consistent with webpack | Rsbuild.
=> feat(core)!: change dojang default escape|unescape to lodash.template syntax

Cargo.lock, Cargo.toml
Release workflow failed with the new introduced `simd-json` https://github.com/web-infra-dev/rspack/actions/workflows/release-canary.yml.
Already fixed in https://github.com/simd-lite/simd-json/pull/376 and released in `0.14.0-rc.2`.
The failed CI will pass with this PR: https://github.com/web-infra-dev/rspack/actions/runs/10519559830/job/29147105799.
cc @JSerFeng
=> ci: bump simd-json

crates/rspack_binding_options/src/plugins/js_loader/resolver.rs, packages/rspack/src/loader-runner/index.ts, tests/webpack-test/cases/loaders/cjs-loader-type/index.js, tests/webpack-test/cases/loaders/cjs-loader-type/loader.cjs, tests/webpack-test/cases/loaders/cjs-loader-type/loader.js, tests/webpack-test/cases/loaders/cjs-loader-type/node_modules/cjs/loader.cjs, tests/webpack-test/cases/loaders/cjs-loader-type/node_modules/cjs/loader.js, tests/webpack-test/cases/loaders/cjs-loader-type/node_modules/cjs/package.json, tests/webpack-test/cases/loaders/cjs-loader-type/node_modules/esm/loader.cjs, tests/webpack-test/cases/loaders/cjs-loader-type/node_modules/esm/package.json
There's an pitfall for [`Path::ends_with`](https://doc.rust-lang.org/std/path/struct.PathBuf.html#method.ends_with). It only matches by components. We need to either convert to `&str` or use `Path::extension`.
Use `Path::as_str` to match extensions instead of `Path::extension` for performance. The second one analyzes `components` first.
=> fix: `Path` pitfall for loader type

website/docs/en/plugins/webpack/module-federation-plugin.mdx, website/docs/zh/plugins/webpack/module-federation-plugin.mdx
Add `@module-federation/sdk` to FAQ, this package now contains ESNext syntax too:
=> docs(mf): add `@module-federation/sdk` to FAQ

packages/rspack-dev-server/package.json, pnpm-lock.yaml
bump webpack-dev-middleware v7.4.2 to fix assetsInfo
- resolve https://github.com/web-infra-dev/rspack/issues/7614
- resolve https://github.com/web-infra-dev/rspack/issues/7618
- ref https://github.com/webpack/webpack-dev-middleware/pull/1927
=> fix(deps): bump webpack-dev-middleware v7.4.2 to fix assetsInfo

packages/create-rspack/index.js
`create-rspack` should not replace the `plugin-react-refresh` version, this package has been moved to a separate repo and does not use the same version of `@rspack/core`.
Fix:
=> fix(create-rspack): should not replace plugin-react-refresh version

crates/rspack_core/src/dependency/mod.rs, crates/rspack_core/src/exports_info.rs, crates/rspack_core/src/module_graph/mod.rs, crates/rspack_plugin_javascript/src/dependency/esm/harmony_export_imported_specifier_dependency.rs, crates/rspack_plugin_javascript/src/dependency/esm/harmony_import_dependency.rs
As we will support persistent cache soon, dependencyConditionFn is Arc<dyn Fn> which cannot be cached, use another trait object for better cacheable
=> refactor: use trait for dependencyConditionFn for better cacheable

crates/rspack_core/src/cgm_hash_results.rs, crates/rspack_core/src/cgm_runtime_requirement_results.rs, crates/rspack_core/src/chunk_graph/chunk_graph_module.rs, crates/rspack_core/src/compiler/compilation.rs, crates/rspack_core/src/compiler/hmr.rs, crates/rspack_core/src/compiler/module_executor/execute.rs, crates/rspack_core/src/lib.rs, crates/rspack_core/src/old_cache/occasion/process_runtime_requirements.rs, crates/rspack_plugin_extract_css/src/plugin.rs, crates/rspack_plugin_javascript/src/plugin/mod.rs, crates/rspack_plugin_javascript/src/runtime.rs
`newIncremental: false`:
`newIncremental: true`:
(case 9000)
=> feat: apply affected modules to all cgm phase

packages/rspack-test-tools/tests/Validation.test.js, packages/rspack/etc/api.md, packages/rspack/src/config/zod.ts, packages/rspack/src/exports.ts, packages/rspack/src/util/validate.ts
Should validate if `context` is an absolute path.
Added `ValidationError` to align with schema-utils of webpack.
Exported `ValidationError` to support rsbuild detecting errors.
closes: #7393
Test template is ported from webpack [`Validation.test.js`](https://github.com/webpack/webpack/blob/b9d9a5d9ffd8d53899a4b198870377090558a32f/test/Validation.test.js).
=> fix: `context` should be an absolute path

crates/rspack_binding_options/src/plugins/js_loader/resolver.rs
Rspack shouldn't panic when load config failed
this error message can be improved
=> fix(core): don't panic when load config failed

website/docs/en/guide/migration/rspack_0.x.mdx, website/docs/zh/guide/migration/rspack_0.x.mdx
Add a tip explaining how to use the `resolve` hook in `NormalModuleFactory` as a replacement for the `resolve` hook in `Resolver`.
=> docs: improve migrating from 0.x

website/theme/components/Landingpage/BuiltWithRspack/index.tsx, website/theme/components/Landingpage/FullyFeatured/index.tsx, website/theme/components/Landingpage/ToolStack/index.tsx
Lazy load images for performance.
- before:
- after:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#loading
=> docs(homepage): lazy load images

Cargo.lock, crates/rspack_core/Cargo.toml, crates/rspack_core/src/resolver/resolver_impl.rs
This PR partially revert https://github.com/web-infra-dev/rspack/pull/7670.
This PR could fix https://github.com/fi3ework-reproduction/rspack-resolver-nested-tsconfig-extends.
In the past, pnp was enabled by default, so many resolve logics followed the pnp logic, but when pnp was disabled, this logic changed. The known problem is that when resolving the following path dependency: `symbol_link_A -> symbol_link_B -> real_path_C`, the relative path of `symbol_link_B` relative to `real_path_C` is obtained, which will lead to the wrong result for the real path (https://github.com/web-infra-dev/rspack-resolver/blob/main/src/file_system.rs#L164-L192).
We enable the pnp feature for now, this issue needs to be resolved in oxc-resolver and rspack-resolver.
=> fix(rspack-resolver): enable pnp feature

crates/rspack_core/src/compiler/compilation.rs, crates/rspack_core/src/exports_info.rs, crates/rspack_core/src/module_graph/mod.rs, crates/rspack_plugin_javascript/src/plugin/side_effects_flag_plugin.rs, tests/webpack-test/configCases/side-effects/side-effects-unsorted-modules/index.js, tests/webpack-test/configCases/side-effects/side-effects-unsorted-modules/node_modules/dep/a.js, tests/webpack-test/configCases/side-effects/side-effects-unsorted-modules/node_modules/dep/b.js, tests/webpack-test/configCases/side-effects/side-effects-unsorted-modules/node_modules/dep/c.js, tests/webpack-test/configCases/side-effects/side-effects-unsorted-modules/node_modules/dep/index.js, tests/webpack-test/configCases/side-effects/side-effects-unsorted-modules/node_modules/dep/package.json, tests/webpack-test/configCases/side-effects/side-effects-unsorted-modules/node_modules/dep/trackModules.js, tests/webpack-test/configCases/side-effects/side-effects-unsorted-modules/webpack.config.js
- use topological order for SideEffectsFlagPlugin when optimize incoming connections
- apply affected modules for SideEffectsFlagPlugin
=> fix: use topological order when SideEffectsFlagPlugin optimize incoming connections

crates/rspack_binding_options/src/plugins/js_loader/resolver.rs, crates/rspack_core/src/compiler/make/repair/factorize.rs, crates/rspack_core/src/diagnostics.rs, crates/rspack_core/src/resolver/resolver_impl.rs, crates/rspack_error/src/error.rs, crates/rspack_loader_lightningcss/src/config.rs, crates/rspack_plugin_css/src/utils.rs, packages/rspack-test-tools/tests/diagnosticsCases/config/builtin-lightningcss-loader/index.css, packages/rspack-test-tools/tests/diagnosticsCases/config/builtin-lightningcss-loader/index.js, packages/rspack-test-tools/tests/diagnosticsCases/config/builtin-lightningcss-loader/rspack.config.js, packages/rspack-test-tools/tests/diagnosticsCases/config/builtin-lightningcss-loader/stats.err, packages/rspack-test-tools/tests/diagnosticsCases/config/builtin-swc-loader/rspack.config.js, packages/rspack-test-tools/tests/diagnosticsCases/config/builtin-swc-loader/stats.err, packages/rspack/src/config/adapterRuleUse.ts
improve error report of serde deserialize error
* before
* after
=> fix(core): improve error report when load builtin:swc-loader and buitin:lightningcss-loader

packages/rspack-test-tools/tests/hotCases/css/recovery/index.js, packages/rspack-test-tools/tests/hotCases/css/recovery/main.js
closes #7683 
It seems that the issue is caused by the CI attempting to perform a hot update on the `index.js` module, but the update fails because it is the entry module.
=> test(infra): improve e2e test stability

crates/rspack_plugin_javascript/src/visitors/dependency/parser/walk.rs, packages/rspack-test-tools/tests/normalCases/parsing/harmony-import-specifier/a.js, packages/rspack-test-tools/tests/normalCases/parsing/harmony-import-specifier/index.js
Closes https://github.com/web-infra-dev/rspack/issues/7722
Currently, the variables used in bodies of getters/setters will be replaced, if the names of some import specifiers are same as them.
=> fix: add `in_function_scope` for getters and setters

.github/workflows/reusable-build.yml
ci: test case have node_modules wrong
=> ci: test case have node_modules wrong

packages/playground/package.json, packages/rspack-dev-server/package.json, packages/rspack/package.json, pnpm-lock.yaml, tests/webpack-test/package.json
fix #7782
rspack-dev-server use some internal api of webpack-dev-server, which cause it's easily broken if webpack-dev-server do some internal refactor
so the temporary solution is to pin the webpack-dev-server version
we need redesign rspack-dev-server implemention and shouldn't rely on internal api
=> fix(dev-server): pin webpack-dev-server version

crates/rspack_core/src/compiler/make/cutout/clean_isolated_module.rs, crates/rspack_core/src/compiler/make/cutout/mod.rs, crates/rspack_core/src/compiler/make/mod.rs, packages/rspack-test-tools/tests/hotCases/make/clean_isolated_module/__snapshots__/web/0.snap.txt, packages/rspack-test-tools/tests/hotCases/make/clean_isolated_module/__snapshots__/web/1.snap.txt, packages/rspack-test-tools/tests/hotCases/make/clean_isolated_module/a.js, packages/rspack-test-tools/tests/hotCases/make/clean_isolated_module/b.js, packages/rspack-test-tools/tests/hotCases/make/clean_isolated_module/c.js, packages/rspack-test-tools/tests/hotCases/make/clean_isolated_module/index.js, packages/rspack-test-tools/tests/hotCases/make/clean_isolated_module/rspack.config.js
Fix the step of clean isolated module in `cutout` will only clean one layer module.
There are a example:
1. if we have a module graph `a` -> `b` -> `c`
2. Edit module `a` so that it does not depend on module `b`
Before this PR the module_graph will only remove module `b`, because of call `revoke_modules` after module isolated check.
=> fix(make): isolated module clean incomplete

package.json, packages/rspack-cli/package.json, patches/graceful-fs@4.2.10.patch, pnpm-lock.yaml
try fix esbusy problem in window ci https://github.com/web-infra-dev/rspack/actions/runs/10700243429/job/29674661766?pr=7744#step:10:206 
related to https://github.com/pnpm/pnpm/issues/6201
the strategy is retry on EBUSY like https://github.com/pnpm/pnpm/blob/main/__patches__/graceful-fs%404.2.11.patch
=> fix(core): try fix EBUSY problem in windows ci

crates/rspack_plugin_javascript/src/utils/eval/eval_binary_expr.rs, packages/rspack-test-tools/tests/normalCases/parsing/evaluate-if-binary/index.js
panic when `1 << 32` in Rspack.
=> fix: overflow panic when shifting left value greater then 31

Cargo.lock, crates/rspack_core/src/dependencies_block.rs, crates/rspack_core/src/external_module.rs, crates/rspack_core/src/module_graph/mod.rs, crates/rspack_plugin_javascript/src/dependency/esm/import_dependency.rs, crates/rspack_plugin_library/Cargo.toml, crates/rspack_plugin_library/src/lib.rs, crates/rspack_plugin_library/src/modern_module/dependency.rs, crates/rspack_plugin_library/src/modern_module/mod.rs, crates/rspack_plugin_library/src/modern_module_library_plugin.rs, packages/rspack-test-tools/tests/configCases/library/modern-module-dynamic-import-runtime/dyn.js, packages/rspack-test-tools/tests/configCases/library/modern-module-dynamic-import-runtime/index.js, packages/rspack-test-tools/tests/configCases/library/modern-module-dynamic-import-runtime/main.js, packages/rspack-test-tools/tests/configCases/library/modern-module-dynamic-import-runtime/rspack.config.js, packages/rspack-test-tools/tests/configCases/library/modern-module-dynamic-import-runtime/test.config.js
`modern-module` reduces the runtime code for external modules with dynamic import.
```js
// source
const react = import('react')
// before
// ---snip---
"357": (function (module) {
module.exports = __WEBPACK_EXTERNAL_MODULE_react_alias__;
}),
// ---snip---
const react = await Promise.resolve(/* import() */ ).then(__webpack_require__.bind(__webpack_require__, 357))
// after
const react = import('react')
```
What did this PR mainly do:
1. In `finish_modules` hook of `modern-module`, find all `ImportDependency` dependencies that point to external modules.
2. In the module graph, find the block to which the dependency belongs and remove this dep; find the connection associated with this dependency and revoke it.
3. Add a new dependency to complete the ID replacement for the external module. …
=> feat(modern-module): make dynamic import runtime-less

crates/rspack_core/src/chunk_graph/chunk_graph_chunk.rs, crates/rspack_plugin_hmr/src/lib.rs, packages/rspack-test-tools/tests/hotCases/stats/chunks/__snapshots__/web/0.snap.txt, packages/rspack-test-tools/tests/hotCases/stats/chunks/__snapshots__/web/1.snap.txt, packages/rspack-test-tools/tests/hotCases/stats/chunks/file.js, packages/rspack-test-tools/tests/hotCases/stats/chunks/index.js, packages/rspack-test-tools/tests/hotCases/stats/chunks/rspack.config.js
1. In webpack, there is no need to add `HotUpdateChunk` to `compilation.chunks`, because `HotUpdateChunk` is no longer used after generating the manifest.
However, in Rspack, we need to add `HotUpdateChunk` to `compilation.chunk_by_ukey` because during the manifest generation, `HotUpdateChunk` is passed to various plugins via the `ukey`. The plugins then use the `ukey` to query `compilation.chunk_by_ukey` to get the `HotUpdateChunk` instance.
Therefore, in Rspack, after the manifest is generated, we need to manually remove the `HotUpdateChunk` from `compilation.chunks`.
2. In webpack, `compilation.chunkGraph` uses a `WeakMap` to maintain the relationship between `Chunk`s and `Module`s.
This means the lifecycle of these data is tied to the `Chunk`, and they are garbage-collected when the …
=> fix: remove HotUpdateChunk in chunks

package.json, packages/rspack-test-tools/jest.config.js, pnpm-lock.yaml, scripts/test/ignore-snapshot-summary-reporter.cjs
Ignore snapshot obsolete warnings while using `-t` to filter cases.
Before:
After:
The warnings can be displayed by `--verbose` if necessary.
=> test: ignore snapshot obsolete warnings while using `-t`

website/docs/en/api/loader-api/context.mdx, website/docs/zh/api/loader-api/context.mdx
Resolved https://github.com/web-infra-dev/rspack/pull/7846#pullrequestreview-2291390202
=> docs: add clarification to loader `this.callback` usage

crates/rspack_core/src/external_module.rs, packages/rspack-test-tools/tests/hookCases/normalModuleFactory#afterResolve/request/output.snap.txt, packages/rspack-test-tools/tests/hookCases/normalModuleFactory#afterResolve/resource/output.snap.txt, packages/rspack-test-tools/tests/hookCases/normalModuleFactory#resolve/resource/output.snap.txt
Align with https://github.com/webpack/webpack/blob/039e8c96338ee98cf37d5035cdd30073a96b4ec5/lib/ExternalModule.js#L878. No coveraged test found in webpack.
=> fix(external_module): use "const" if supported when concatenation

packages/rspack-dev-server/jest.config.js, packages/rspack-dev-server/package.json
Should install chrome before running puppeteer test cases. Chrome is not installed by post install hooks on github runner, not sure why
=> test(dev-server): enable dev server test cases

packages/rspack-test-tools/tests/diagnosticsCases/module-build-failed/loader-emit-error/index.js, packages/rspack-test-tools/tests/diagnosticsCases/module-build-failed/loader-emit-error/lib.js, packages/rspack-test-tools/tests/diagnosticsCases/module-build-failed/loader-emit-error/my-loader.js, packages/rspack-test-tools/tests/diagnosticsCases/module-build-failed/loader-emit-error/rspack.config.js, packages/rspack-test-tools/tests/diagnosticsCases/module-build-failed/loader-emit-error/stats.err, packages/rspack-test-tools/tests/diagnosticsCases/module-build-failed/loader-emit-hide-stack/index.js, packages/rspack-test-tools/tests/diagnosticsCases/module-build-failed/loader-emit-hide-stack/lib.js, packages/rspack-test-tools/tests/diagnosticsCases/module-build-failed/loader-emit-hide-stack/my-loader.js, packages/rspack-test-tools/tests/diagnosticsCases/module-build-failed/loader-emit-hide-stack/rspack.config.js, packages/rspack-test-tools/tests/diagnosticsCases/module-build-failed/loader-emit-hide-stack/stats.err, packages/rspack-test-tools/tests/diagnosticsCases/module-build-failed/loader-emit-warning/index.js, packages/rspack-test-tools/tests/diagnosticsCases/module-build-failed/loader-emit-warning/lib.js, packages/rspack-test-tools/tests/diagnosticsCases/module-build-failed/loader-emit-warning/my-loader.js, packages/rspack-test-tools/tests/diagnosticsCases/module-build-failed/loader-emit-warning/rspack.config.js, packages/rspack-test-tools/tests/diagnosticsCases/module-build-failed/loader-emit-warning/stats.err, packages/rspack/src/loader-runner/index.ts, packages/rspack/src/util/index.ts, tests/plugin-test/css-extract/cases/build-in-css-support/warnings.js
**Before**
```
WARNING in ./lib.js
⚠ Failed to load (from: <PROJECT_ROOT>/tests/diagnosticsCases/module-build-failed/loader-emit-hide-stack/my-loader.js)
ERROR in ./lib.js
× Failed to load (from: <PROJECT_ROOT>/tests/diagnosticsCases/module-build-failed/loader-emit-hide-stack/my-loader.js)
```
**After**
```
WARNING in ./lib.js
⚠ ModuleWarning: Failed to load (from: <PROJECT_ROOT>/tests/diagnosticsCases/module-build-failed/loader-emit-hide-stack/my-loader.js)
ERROR in ./lib.js
× ModuleError: Failed to load (from: <PROJECT_ROOT>/tests/diagnosticsCases/module-build-failed/loader-emit-hide-stack/my-loader.js)
```
=> fix: should provide full error message with error name when `hideStack` is set to `true`

website/docs/en/api/javascript-api/compiler.mdx, website/docs/en/api/javascript-api/index.mdx, website/docs/zh/api/javascript-api/compiler.mdx, website/docs/zh/api/javascript-api/index.mdx
The `compiler.webpack.sources` is a commonly used API and we should document it.
=> docs: add `sources` JavaScript API

.vscode/settings.json
Revert the VS Code workspace settings introduced in https://github.com/web-infra-dev/rspack/pull/7846. Developers could set this field by their global settings.
=> chore: remove "rust-analyzer.checkOnSave" of VS Code

packages/rspack/etc/api.md, packages/rspack/src/Resolver.ts, packages/rspack/src/config/adapterRuleUse.ts, packages/rspack/src/loader-runner/index.ts, packages/rspack/src/node/NodeEnvironmentPlugin.ts, packages/rspack/src/stats/DefaultStatsFactoryPlugin.ts, packages/rspack/src/stats/DefaultStatsPrinterPlugin.ts, packages/rspack/src/stats/StatsFactory.ts, packages/rspack/src/stats/statsFactoryUtils.ts, packages/rspack/src/util/comparators.ts, packages/rspack/src/util/smartGrouping.ts
https://github.com/web-infra-dev/rspack/pull/7824
close https://github.com/web-infra-dev/rspack/issues/4640
https://github.com/web-infra-dev/rspack/issues/7225
=> refactor(types): remove @ts-expect-error in loaderRunner and StatsFactory

packages/rspack-dev-server/src/alias.ts, packages/rspack-dev-server/src/server.ts, packages/rspack-dev-server/tests/fixtures/reload-config/main.css
- should not override private methods, just add some alias
- override the `module.require.resolve` in NodeModule instance of `webpack-dev-server` to redirect webpack server module request to rspack
=> refactor: clean dev server code

crates/rspack_core/src/dependency/dependency_location.rs, crates/rspack_plugin_javascript/src/dependency/esm/provide_dependency.rs, crates/rspack_plugin_javascript/src/parser_plugin/provide_plugin.rs
=> feat(rspack_plugin_javascript): improve provide dependency

packages/rspack-test-tools/package.json
`sh -c 'run-s \"test:* -u -- $*\"' sh` should be `sh -c 'run-s \"test:* -- -u $*\"' sh`.
=> fix(rspack-test-tools): corret script `testu`

crates/rspack_core/src/normal_module_factory.rs
align resource in use with webpack
the use resource(doesn't contain query) is actually misleading here because it has different meaning compared with loaderContext.resource(which contains query)
=> fix(core): use resource shouldn't contain query

crates/rspack_core/src/concatenated_module.rs, crates/rspack_core/src/external_module.rs, packages/rspack-test-tools/etc/api.md, packages/rspack-test-tools/src/helper/read-config-file.ts, packages/rspack-test-tools/src/processor/multi.ts, packages/rspack-test-tools/tests/configCases/externals/0-concatenation-tree-shaking/externals/m.mjs, packages/rspack-test-tools/tests/configCases/externals/0-concatenation-tree-shaking/index.js, packages/rspack-test-tools/tests/configCases/externals/0-concatenation-tree-shaking/rspack.config.js, packages/rspack-test-tools/tests/configCases/externals/0-concatenation-tree-shaking/test.config.js, packages/rspack-test-tools/tests/configCases/externals/1-concatenation-tree-shaking/consume.js, packages/rspack-test-tools/tests/configCases/externals/1-concatenation-tree-shaking/index.js, packages/rspack-test-tools/tests/configCases/externals/1-concatenation-tree-shaking/rspack.config.js, packages/rspack-test-tools/tests/configCases/externals/1-concatenation-tree-shaking/test.config.js, packages/rspack-test-tools/tests/configCases/library/modern-module-export-char/rspack.config.js
This PR will simplify `"module"` external type's runtime like below. When building a package with Rspack, it can be ensured that external modules can be tree shaken.
Changes summary:
1. only changed `"module"` external type.
2. variable name folding theoretically should not cause any potential problems, as there is currently no module remapping, it merely eliminates intermediate variables.
3. `MultiTaskProcessor` could handle function config.
```js
// --- before ---
import * as __WEBPACK_EXTERNAL_MODULE_react_alias__ from "react-alias";
;// CONCATENATED MODULE: external "react-alias"
const external_react_alias_namespaceObject = __WEBPACK_EXTERNAL_MODULE_react_alias__;
;// CONCATENATED MODULE: ./src/main.mjs
function main() {
(0,external_react_alias_namespaceObject.createElement)('div');
} …
```
=> fix: avoid import external module re-assigin in concatenation

crates/rspack_core/src/compiler/make/cutout/has_module_graph_change.rs, crates/rspack_core/src/compiler/make/cutout/mod.rs
`has_module_graph_change` always evaluates to true when running `update_module_graph` multiple times during the make stage
``` rust
fn make(compilation: &Compilation, make_artifact: MakeArtifact) {
// run multi times
let make_artifact = update_module_graph(compilation, make_artifact, params);
let make_artifact = update_module_graph(compilation, make_artifact, params);
assert_eq!(make_artifact.has_module_graph_change, true);
}
```
This PR rewrite the `has_module_graph_change` calculate by check make_artifact.built_module change.
=> fix: make stage has_module_graph_change calculate incorrectly

crates/rspack_core/src/compiler/compilation.rs, crates/rspack_core/src/concatenated_module.rs, packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/concatenate_parse_module/foo.js, packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/concatenate_parse_module/index.js, packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/concatenate_parse_module/rspack.config.js, packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/concatenate_parse_module/stats.err
fix #7382
When `code_generation` returns an `Err`, we should push this error to diagnostics and keep a empty `CodegenerateResult` like webpack
Parse error in concatenatedModule should be added to compilation diagnostics.
=> fix: should create an empty codegen result for module that has failure in codegen

crates/node_binding/binding.d.ts, crates/node_binding/src/plugins/interceptor.rs, crates/node_binding/src/plugins/mod.rs, crates/rspack_binding_values/src/runtime.rs, crates/rspack_core/src/compiler/compilation.rs, crates/rspack_plugin_css/src/plugin/impl_plugin_for_css_plugin.rs, crates/rspack_plugin_extract_css/src/plugin.rs, crates/rspack_plugin_mf/src/container/container_plugin.rs, crates/rspack_plugin_mf/src/container/container_reference_plugin.rs, crates/rspack_plugin_mf/src/sharing/share_runtime_plugin.rs, crates/rspack_plugin_runtime/src/bundler_info.rs, crates/rspack_plugin_runtime/src/common_js_chunk_loading.rs, crates/rspack_plugin_runtime/src/import_scripts_chunk_loading.rs, crates/rspack_plugin_runtime/src/jsonp_chunk_loading.rs, crates/rspack_plugin_runtime/src/module_chunk_loading.rs, crates/rspack_plugin_runtime/src/runtime_plugin.rs, crates/rspack_plugin_runtime/src/startup_chunk_dependencies.rs, crates/rspack_plugin_wasm/src/loading_plugin.rs, packages/rspack-test-tools/tests/configCases/hooks/runtime-requirement-in-tree/index.js, packages/rspack-test-tools/tests/configCases/hooks/runtime-requirement-in-tree/rspack.config.js, packages/rspack/etc/api.md, packages/rspack/src/Compilation.ts, packages/rspack/src/Compiler.ts
Support this hook for adding runtime modules from js side
=> feat: support `compilation.hooks.runtimeRequirementInTree`

.vscode/settings.json, Cargo.lock, crates/node_binding/binding.d.ts, crates/rspack_binding_values/Cargo.toml, crates/rspack_binding_values/src/compilation/mod.rs, crates/rspack_binding_values/src/module.rs, crates/rspack_binding_values/src/runtime.rs, crates/rspack_core/src/runtime_module.rs, crates/rspack_plugin_runtime/Cargo.toml, crates/rspack_plugin_runtime/src/lib.rs, crates/rspack_plugin_runtime/src/runtime_module_from_js.rs, packages/rspack-test-tools/tests/configCases/runtime/add-runtime-module-isolate/index.js, packages/rspack-test-tools/tests/configCases/runtime/add-runtime-module-isolate/rspack.config.js, packages/rspack-test-tools/tests/configCases/runtime/add-runtime-module-stage/index.js, packages/rspack-test-tools/tests/configCases/runtime/add-runtime-module-stage/rspack.config.js, packages/rspack-test-tools/tests/configCases/runtime/add-runtime-module/a.js, packages/rspack-test-tools/tests/configCases/runtime/add-runtime-module/b.js, packages/rspack-test-tools/tests/configCases/runtime/add-runtime-module/c.js, packages/rspack-test-tools/tests/configCases/runtime/add-runtime-module/index.js, packages/rspack-test-tools/tests/configCases/runtime/add-runtime-module/rspack.config.js, packages/rspack/etc/api.md, packages/rspack/src/Chunk.ts, packages/rspack/src/Compilation.ts, packages/rspack/src/RuntimeModule.ts, packages/rspack/src/exports.ts
Support `compilation.addRuntimeModule` to add custom runtime module:
```js
const { RuntimeModule, RuntimeGlobals } = require("@rspack/core");
class CustomRuntimeModule extends RuntimeModule {
constructor(chunk) {
// set name and stage of this runtime module
super("module-name", RuntimeModule.STAGE_NORMAL);
}
shouldIsolate() {
// if false, will not be wrapped by IIFE
return true;
}
generate(compilation) {
return `
// content of this runtime module
__webpack_require__.xxx = xxx;
`;
}
}
// ...
plugins: [
compiler => {
compiler.hooks.thisCompilation.tap("CustomRuntimePlugin", (compilation) => {
compilation.hooks.runtimeRequirementInTree.tap("CustomRuntimePlugin", (chunk, set) => {
// add dependent runtime globals
set.add(RuntimeGlobals.publicPath);
// add custom runtime …
```
=> feat: support `compilation.addRuntimeModule`

packages/rspack-test-tools/tests/configCases/runtime/add-runtime-module/rspack.config.js, packages/rspack/etc/api.md, packages/rspack/src/Compilation.ts, packages/rspack/src/RuntimeModule.ts
Just attach `chunk`, `compilation` and `chunkGraph` to runtime module when added
=> fix: attach when add runtime module

package.json
When I only change files ignored by biome (such as files in `tests/**/*`) and trigger lint-stage by executing `git commit`, I get an error saying `No files were processed in the specified paths`.
=> chore(infra/biome): enable no-errors-on-unmatched

Cargo.lock, Cargo.toml, crates/node_binding/Cargo.toml, crates/node_binding/src/lib.rs, crates/node_binding/src/resolver_factory.rs, crates/rspack_core/Cargo.toml, crates/rspack_core/src/compiler/compilation.rs, crates/rspack_core/src/compiler/hmr.rs, crates/rspack_core/src/compiler/make/repair/add.rs, crates/rspack_core/src/compiler/make/repair/build.rs, crates/rspack_core/src/compiler/make/repair/mod.rs, crates/rspack_core/src/compiler/mod.rs, crates/rspack_core/src/external_module.rs, crates/rspack_core/src/module.rs, crates/rspack_core/src/normal_module.rs, crates/rspack_core/src/resolver/boxfs.rs, crates/rspack_core/src/resolver/factory.rs, crates/rspack_core/src/resolver/mod.rs, crates/rspack_core/src/resolver/resolver_impl.rs, crates/rspack_fs/Cargo.toml, crates/rspack_fs/src/error.rs, crates/rspack_fs/src/lib.rs, crates/rspack_fs/src/native.rs, crates/rspack_fs/src/sync.rs, crates/rspack_fs_node/Cargo.toml, crates/rspack_fs_node/src/lib.rs, crates/rspack_fs_node/src/node.rs, crates/rspack_loader_runner/Cargo.toml, crates/rspack_loader_runner/src/runner.rs, crates/rspack_plugin_javascript/src/plugin/module_concatenation_plugin.rs
> [!CAUTION]
> since the performance regression is not acceptable for inputFilesystem binding, won't  export input filesystem to js side now
related to #7478 
This PR support input_filesystem api in rust side and bridge with resolver's filesystem: this will not introduce performance regression
=> feat(core): integrate rspack_resolver with input_filesystem

.cargo/config.toml, Cargo.lock, crates/node_binding/Cargo.toml, crates/rspack_tracing/Cargo.toml, crates/rspack_tracing/src/lib.rs, justfile
support debug scheduler problem using tokio console
we can spot which task takes long time using tokio-console
```sh
$ cargo install tokio-console
$ RSPACK_PROFILE=trace rspack dev -c rspack.config.js
$ tokio-console
```
=> feat(core): support using tokio-console

crates/node_binding/binding.d.ts, crates/rspack_binding_options/src/options/raw_module/mod.rs, crates/rspack_core/src/options/module.rs, crates/rspack_plugin_javascript/src/dependency/esm/harmony_export_imported_specifier_dependency.rs, crates/rspack_plugin_javascript/src/dependency/esm/harmony_import_specifier_dependency.rs, crates/rspack_plugin_javascript/src/parser_plugin/import_parser_plugin.rs, crates/rspack_plugin_javascript/src/visitors/dependency/context_dependency_helper.rs, crates/rspack_plugin_javascript/src/visitors/dependency/parser/mod.rs, packages/rspack-test-tools/tests/__snapshots__/Defaults.test.js.snap, packages/rspack/src/config/adapter.ts, packages/rspack/src/config/defaults.ts
After #7812, we should not return the default value in getRawJavascriptParserOptions, as it will break the merging logic.
I want to write test cases, but I found that the createParser hook of NormalModuleFactory is not yet supported.
=> fix: change javascript parser options to properly merge

.github/renovate.json5
Fix: 
> The renovate configuration file contains some invalid settings
Message: packageRules[7]: packageRules cannot combine both matchUpdateTypes and rangeStrategy
Ref: https://github.com/renovatebot/renovate/discussions/10165
resolve https://github.com/web-infra-dev/rspack/issues/6172
=> chore(workflow): remove rangeStrategy from renovate config

website/docs/en/config/resolve.mdx, website/docs/zh/config/resolve.mdx
Add use case for `extensionAlias`, see:
- https://github.com/web-infra-dev/rsbuild/discussions/3529
- https://github.com/vercel/next.js/discussions/32237
- https://www.typescriptlang.org/docs/handbook/modules/theory.html
=> docs: add use case for `extensionAlias`

website/docs/en/blog/announcing-1-0.mdx, website/docs/zh/blog/announcing-1-0.mdx, website/project-words.txt
Add missing innovator to credits
=> docs(website): update blog credit

packages/rspack/src/config/browserslistTargetHandler.ts
In most cases, Rspack does not need to require the `browserslist` package, it is only be used if `target` contains "browserslist".
Lazy require `browserslist` can make Rspack startup **17ms** faster.
- before:
- after:
=> perf: lazy require `browserslist` package

packages/rspack-cli/tsconfig.json
when use local build rspack bin to debug other projects, rspack will auto do typecheck which may fail
=> chore: not allow run typecheck when run node bin/rspack for other project

crates/rspack_core/Cargo.toml, crates/rspack_core/src/compiler/make/repair/add.rs, crates/rspack_core/src/compiler/make/repair/build.rs, crates/rspack_core/src/compiler/make/repair/factorize.rs, crates/rspack_core/src/compiler/make/repair/process_dependencies.rs, crates/rspack_core/src/compiler/module_executor/ctrl.rs, crates/rspack_core/src/compiler/module_executor/entry.rs, crates/rspack_core/src/compiler/module_executor/execute.rs, crates/rspack_core/src/compiler/module_executor/overwrite.rs, crates/rspack_core/src/utils/task_loop.rs
add task name for every task for better display in tokio-console
=> refactor(core): add task name for tokio-console better display

crates/node_binding/binding.d.ts, crates/node_binding/src/lib.rs, crates/rspack_tracing/src/lib.rs, packages/rspack-cli/src/utils/profile.ts
enable tokio_console by separate tracing layer
=> refactor(core): use separate tokio_console layer

packages/rspack/src/Compilation.ts
Fix proxied typo.
https://github.com/web-infra-dev/rspack/pull/7973
=> chore: fix proxied typo

crates/node_binding/src/lib.rs, crates/rspack_binding_options/src/lib.rs, crates/rspack_binding_options/src/plugins/buildtime_plugins.rs, crates/rspack_binding_options/src/plugins/mod.rs, crates/rspack_core/src/compiler/compilation.rs, crates/rspack_core/src/compiler/hmr.rs, crates/rspack_core/src/compiler/make/repair/mod.rs, crates/rspack_core/src/compiler/mod.rs, crates/rspack_core/src/compiler/module_executor/entry.rs, crates/rspack_core/src/compiler/module_executor/execute.rs, crates/rspack_core/src/compiler/module_executor/mod.rs, crates/rspack_core/src/dependency/loader_import.rs, packages/rspack-test-tools/tests/configCases/runtime/add-runtime-module-with-import-module/a.js, packages/rspack-test-tools/tests/configCases/runtime/add-runtime-module-with-import-module/b.js, packages/rspack-test-tools/tests/configCases/runtime/add-runtime-module-with-import-module/c.js, packages/rspack-test-tools/tests/configCases/runtime/add-runtime-module-with-import-module/execute-module.js, packages/rspack-test-tools/tests/configCases/runtime/add-runtime-module-with-import-module/index.js, packages/rspack-test-tools/tests/configCases/runtime/add-runtime-module-with-import-module/loader.js, packages/rspack-test-tools/tests/configCases/runtime/add-runtime-module-with-import-module/rspack.config.js, packages/rspack/src/Compilation.ts, packages/rspack/src/loader-runner/index.ts
import module should use different plugin_driver compare to main compilation, so that plugins won't operate incorrect compilation
=> refactor: import module hooks

crates/node_binding/binding.d.ts, crates/rspack_binding_values/src/compilation/mod.rs, packages/rspack-test-tools/tests/watchCases/compilation/built-modules/0/foo.js, packages/rspack-test-tools/tests/watchCases/compilation/built-modules/0/index.js, packages/rspack-test-tools/tests/watchCases/compilation/built-modules/1/foo.js, packages/rspack-test-tools/tests/watchCases/compilation/built-modules/rspack.config.js, packages/rspack/etc/api.md, packages/rspack/src/Compilation.ts, website/docs/en/api/javascript-api/compilation.mdx, website/docs/zh/api/javascript-api/compilation.mdx
Support `compilation.builtModules`, these modules will be collected after calling finishModules hook and then eslint-rspack-plugin can use it to implement [`lintDirtyModulesOnly`](https://github.com/rspack-contrib/eslint-rspack-plugin/pull/5).
=> feat: support `compilation.builtModules`

website/components/RandomMemberList.tsx, website/docs/en/misc/team/core-team.mdx, website/docs/zh/misc/team/core-team.mdx, website/project-words.txt
Thanks @shulaoda for your contribution to Rspack!
I am delighted to invite you to join the Rspack core team and enjoy the open source ^_^
Contributions:
- https://github.com/web-infra-dev/rspack/commits?author=shulaoda
- https://github.com/web-infra-dev/rspress/commits?author=shulaoda
- https://github.com/web-infra-dev/rspack/issues?q=commenter:shulaoda
suxin2017 will join Emeriti members as he is no longer active in the Rspack ecosystem. We are grateful for suxin2017's outstanding contributions in the early days of Rspack. ❤️
=> docs: update team members, add @shulaoda

packages/rspack-test-tools/tests/configCases/runtime/add-runtime-module-isolate/rspack.config.js, packages/rspack-test-tools/tests/configCases/runtime/add-runtime-module-stage/rspack.config.js, packages/rspack-test-tools/tests/configCases/runtime/add-runtime-module/rspack.config.js, packages/rspack/etc/api.md, packages/rspack/src/RuntimeModule.ts, website/docs/en/api/javascript-api/compilation.mdx, website/docs/en/api/plugin-api/compilation-hooks.mdx, website/docs/zh/api/javascript-api/compilation.mdx, website/docs/zh/api/plugin-api/compilation-hooks.mdx
Should get the `compilation` object through `this.compilation` in `RuntimeModule.generate`. Pass compilation as param is not aligned with webpack. This is a bug
=> fix: generate params of runtime module

packages/rspack/etc/api.md, packages/rspack/src/builtin-plugin/BannerPlugin.ts, website/docs/en/plugins/webpack/banner-plugin.mdx, website/docs/zh/plugins/webpack/banner-plugin.mdx
Zod types system is not easy to understand by user. 
We tend use raw ts provider intellisense and jsDoc for user in ide, 
=> refactor: add JSDoc to improve BannerPlugin options types

packages/rspack/etc/api.md, packages/rspack/src/builtin-plugin/HtmlRspackPlugin.ts, packages/rspack/src/builtin-plugin/IgnorePlugin.ts, website/docs/en/plugins/rspack/html-rspack-plugin.mdx, website/docs/zh/plugins/rspack/html-rspack-plugin.mdx
- Add type & JSDoc fro HtmlRspackPlugin.
- Add JSDoc for IgnorePlugin.
=> refactor: add JSDoc & types to improve HtmlRspackPlugin, IgnorePlugin options types

website/docs/en/blog/announcing-1-0.mdx, website/docs/zh/blog/announcing-1-0.mdx
give more accurate definition of breaking change
=> docs: upgrade breaking change description

.github/actions/upload-artifact/action.yml, .github/workflows/ci.yml, .github/workflows/preview-commit.yml, Cargo.toml
=> chore(ci): support pkg.pr.new

packages/rspack-cli/tests/build/issue-6359/index.test.ts, packages/rspack-cli/tests/build/issue-6359/rspack.config.js
Just add an 1s delay to make sure that the assets have been generated.
=> test: try to fix the randomly failed of @rspack/cli test cases

packages/rspack/etc/api.md, packages/rspack/src/config/types.ts, packages/rspack/src/config/zod.ts
- Add type & JSDoc for config.externals
=> refactor: add JSDoc to improve configuration.externals types

packages/rspack/etc/api.md, packages/rspack/src/config/types.ts, packages/rspack/src/config/zod.ts
…context] types.
- Add type & JSDoc for config.entry
- Add type & JSDoc for config.context
- Add type & JSDoc for config.dependencies
- Add type & JSDoc for config.mode
=> refactor: add JSDoc to improve Rspack configuration.entry|context|mode types

crates/rspack_core/src/concatenated_module.rs, packages/rspack-test-tools/tests/__snapshots__/StatsAPI.test.js.snap, packages/rspack-test-tools/tests/__snapshots__/StatsOutput.test.js.snap, packages/rspack-test-tools/tests/configCases/concatenate-modules/chunk-hash/app.js, packages/rspack-test-tools/tests/configCases/concatenate-modules/chunk-hash/m1.js, packages/rspack-test-tools/tests/configCases/concatenate-modules/chunk-hash/m2.js, packages/rspack-test-tools/tests/configCases/concatenate-modules/chunk-hash/main.js, packages/rspack-test-tools/tests/configCases/concatenate-modules/chunk-hash/mock-loader.js, packages/rspack-test-tools/tests/configCases/concatenate-modules/chunk-hash/rspack.config.js, packages/rspack-test-tools/tests/configCases/concatenate-modules/chunk-hash/test.confg.js
Fix https://github.com/web-infra-dev/rspack/issues/7937
Cause code generation hash of concatenated module is `None`, if contents its of inner modules change, the chunk hash will not change.
=> fix: should set code generation hash to concatenated module

Cargo.lock, crates/rspack_binding_values/Cargo.toml, crates/rspack_binding_values/src/compilation/mod.rs, crates/rspack_binding_values/src/path_data.rs, crates/rspack_core/src/options/filename.rs, packages/rspack-test-tools/tests/configCases/hooks/get-path-custom-chunk/rspack.config.js, packages/rspack-test-tools/tests/configCases/hooks/get-path-custom-chunk/test.config.js, packages/rspack-test-tools/tests/configCases/hooks/get-path-existing-chunk/rspack.config.js, packages/rspack-test-tools/tests/configCases/hooks/get-path-existing-chunk/test.config.js, packages/rspack/etc/api.md, packages/rspack/src/Chunk.ts, packages/rspack/src/Compilation.ts
fix https://github.com/web-infra-dev/rspack/issues/7960
Not support chunk contenthash yet, need to add [contentHashType](https://github.com/webpack/webpack/blob/b4924e0b371c3e609958954cf616aa030c1ef5f5/lib/Compilation.js#L301) field, perhaps should support it in the future
=> fix: should use chunk in path data of `compilation.getPath`

packages/rspack/src/Compilation.ts
related to TS5.6 breaking changes
https://devblogs.microsoft.com/typescript/announcing-typescript-5-6/#iterator-helper-methods
fix when using `skipLibCheck: false`
=> fix(type): be compitable to ts5.6

crates/node_binding/binding.d.ts, crates/rspack_binding_values/src/module.rs, crates/rspack_core/src/loader/loader_runner.rs, packages/rspack-test-tools/tests/configCases/source-map/custom-loader/index.js, packages/rspack-test-tools/tests/configCases/source-map/custom-loader/loader.js, packages/rspack-test-tools/tests/configCases/source-map/custom-loader/rspack.config.js, packages/rspack/src/loader-runner/index.ts
=> fix: the value of this.sourceMap in LoaderContext is incorrect when using SourceMapDevToolPlugin

Cargo.lock, Cargo.toml
Fix: #7914
Relative: https://github.com/web-infra-dev/rspack/issues/7914
=> fix: source map is not works with Sentry

packages/rspack/etc/api.md, packages/rspack/src/config/types.ts, packages/rspack/src/config/zod.ts, website/docs/en/plugins/webpack/split-chunks-plugin.mdx, website/docs/zh/plugins/webpack/split-chunks-plugin.mdx
- Add type & JSDoc for config.optimization
=> refactor: add JSDoc to improve Rspack configuration.optimization types.

packages/rspack-cli/tests/build/issue-6359/index.test.ts
This test case is not stable on CI. Disable it now and will delve into it in the future
=> test: disable unstable test case of rspack-cli

crates/rspack_plugin_css/webpack_css_cases_to_be_migrated/hmr/expected/main.js, packages/rspack-test-tools/tests/hotCases/css/recovery/__snapshots__/web/2.snap.txt, packages/rspack/src/builtin-plugin/css-extract/hmr/hotModuleReplacement.ts, tests/plugin-test/css-extract/__snapshots__/HMR.test.js.snap, tests/plugin-test/css-extract/cases/hmr-locals/expected/main.js, tests/plugin-test/css-extract/cases/hmr/expected/main.js
polish CSS HMR logs and correct the case:
- `css` -> `CSS`
- `css modules` -> `CSS Modules`
=> chore: polish CSS HMR logs and correct the case

.github/workflows/preview-commit.yml
I noticed that `pkg-pr-new` has been consistently skipped because I mistakenly set the `predicate-quantifier` to `every`. This caused files to only be filtered if they met all conditions, which resulted in the intended files being excluded.
=> fix(ci/preview-commit): remove predicate-quantifier

crates/rspack_core/src/build_chunk_graph/code_splitter.rs, crates/rspack_core/src/chunk_graph/chunk_graph_chunk.rs, crates/rspack_core/src/chunk_graph/chunk_graph_module.rs, crates/rspack_core/src/compiler/make/cutout/fix_issuers.rs, crates/rspack_core/src/compiler/make/cutout/has_module_graph_change.rs, crates/rspack_core/src/compiler/make/cutout/mod.rs, crates/rspack_core/src/compiler/make/repair/add.rs, crates/rspack_core/src/compiler/module_executor/ctrl.rs, crates/rspack_core/src/concatenated_module.rs, crates/rspack_core/src/exports_info.rs, crates/rspack_core/src/module_graph/connection.rs, crates/rspack_core/src/module_graph/mod.rs, crates/rspack_core/src/module_graph/module.rs, crates/rspack_core/src/normal_module.rs, crates/rspack_core/src/stats/mod.rs, crates/rspack_core/src/unaffected_cache/mod.rs, crates/rspack_plugin_javascript/src/dependency/commonjs/common_js_export_require_dependency.rs, crates/rspack_plugin_javascript/src/dependency/esm/harmony_export_imported_specifier_dependency.rs, crates/rspack_plugin_javascript/src/dependency/esm/harmony_import_dependency.rs, crates/rspack_plugin_javascript/src/dependency/esm/harmony_import_specifier_dependency.rs, crates/rspack_plugin_javascript/src/dependency/esm/provide_dependency.rs, crates/rspack_plugin_javascript/src/dependency/is_included_dependency.rs, crates/rspack_plugin_javascript/src/plugin/flag_dependency_usage_plugin.rs, crates/rspack_plugin_javascript/src/plugin/module_concatenation_plugin.rs, crates/rspack_plugin_javascript/src/plugin/side_effects_flag_plugin.rs, crates/rspack_plugin_library/src/modern_module_library_plugin.rs, tests/webpack-test/__snapshots__/StatsTestCases.basictest.js.snap
Currently we use `ModuleIdentifier` to access `Module` and `ModuleGraphModule`, but need to convert the dependency_id to the connection_id to access the `Connection`, which will cause additional performance loss.
``` rust
impl ModuleGraph {
fn connection_by_dependency_id(&self, dep_id: &DependencyId) -> Option<Connection> {
let con_id = self.dependency_id_to_connection_id.get(dep_id)?;
self.connections.get(con_id)
}
}
```
This PR will remove ConnectionId and use DependencyId to access Connection.
``` rust
impl ModuleGraph {
fn connection_by_dependency_id(&self, dep_id: &DependencyId) -> Option<Connection> {
self.connections.get(dep_id)
}
}
```
NOTE: There are some inactive connections in the module graph that cannot be found from the dependency ID. This is useful when you need to print …
=> refactor: remove connection id

crates/rspack_plugin_runtime/src/runtime_plugin.rs
Align with webpack: https://github.com/webpack/webpack/blob/e7121fe9972b182832d401cabaf9d5ca489b1713/lib/RuntimePlugin.js#L286
=> fix: avoid extra runtime for get javascript chunk filename

packages/rspack/etc/api.md, packages/rspack/src/config/types.ts, packages/rspack/src/config/zod.ts, website/docs/en/config/output.mdx, website/docs/zh/config/output.mdx
- Add type & JSDoc for config.output
=> refactor: add JSDoc & types to improve Rspack configuration.output types.

crates/rspack_core/src/exports_info.rs, crates/rspack_plugin_javascript/src/plugin/side_effects_flag_plugin.rs
Add cache for getting sideEffectState, `get_side_effect_state` has some costs now, it affects performance if invoke too many times
=> perf: add cache for getting sideEffectState

packages/rspack-cli/package.json
- Add exports field to the `@rspack/cli` package, align with `@rspack/core` and `@rspack/dev-server`.
- Use `sort-package-json` to sort the package.json file.
=> feat(cli): add exports field

.github/workflows/ci.yml, crates/rspack_binding_values/src/stats.rs, crates/rspack_core/src/diagnostics.rs, crates/rspack_core/src/options/filename.rs, crates/rspack_core/src/stats/struct.rs, crates/rspack_core/src/stats/utils.rs, crates/rspack_regex/src/algo.rs, crates/rspack_util/src/infallible.rs, rust-toolchain.toml
Upgrade to the latest Rust v1.81.0 release https://blog.rust-lang.org/2024/09/05/Rust-1.81.0.html
=> chore: upgrade rust to 1.81.0 nightly

crates/rspack_core/src/exports_info.rs, crates/rspack_core/src/module.rs, crates/rspack_plugin_javascript/src/plugin/flag_dependency_exports_plugin.rs, crates/rspack_plugin_javascript/src/plugin/module_concatenation_plugin.rs, crates/rspack_plugin_javascript/src/plugin/side_effects_flag_plugin.rs, packages/rspack-test-tools/tests/configCases/tree-shaking/side-effects-consume-shared/index.js, packages/rspack-test-tools/tests/configCases/tree-shaking/side-effects-consume-shared/lib/a.js, packages/rspack-test-tools/tests/configCases/tree-shaking/side-effects-consume-shared/lib/b.js, packages/rspack-test-tools/tests/configCases/tree-shaking/side-effects-consume-shared/lib/c.js, packages/rspack-test-tools/tests/configCases/tree-shaking/side-effects-consume-shared/lib/package.json, packages/rspack-test-tools/tests/configCases/tree-shaking/side-effects-consume-shared/rspack.config.js, packages/rspack-test-tools/tests/configCases/tree-shaking/side-effects-dynamic-cjs/index.js, packages/rspack-test-tools/tests/configCases/tree-shaking/side-effects-dynamic-cjs/lib/a.js, packages/rspack-test-tools/tests/configCases/tree-shaking/side-effects-dynamic-cjs/lib/b.js, packages/rspack-test-tools/tests/configCases/tree-shaking/side-effects-dynamic-cjs/lib/c.js, packages/rspack-test-tools/tests/configCases/tree-shaking/side-effects-dynamic-cjs/lib/package.json, packages/rspack-test-tools/tests/configCases/tree-shaking/side-effects-dynamic-cjs/rspack.config.js, tests/webpack-test/cases/side-effects/dynamic-reexports/index.js, tests/webpack-test/cases/side-effects/dynamic-reexports/test.config.js, tests/webpack-test/cases/side-effects/dynamic-reexports/test.filter.js
Fix side effects optimize for dynamic reexports, should generate correct import specifiers,  checkout the test cases for more detail
=> fix: side effects optimize for dynamic reexports

crates/rspack_plugin_json/src/lib.rs, tests/webpack-test/__snapshots__/StatsTestCases.basictest.js.snap
Align to https://github.com/webpack/webpack/blob/c801ebb253ecda87f8613e040ba1b86a1dcaa70a/lib/json/JsonGenerator.js#L192.
Snapshot is correctly, align with webpack https://github.com/webpack/webpack/blob/c801ebb253ecda87f8613e040ba1b86a1dcaa70a/test/__snapshots__/StatsTestCases.basictest.js.snap#L1277.
=> fix(json): only add RuntimeGlobals::MODULE for concatenation

package.json, packages/rspack-test-tools/jest.config.js, scripts/test/ignore-snapshot-default-reporter.cjs, scripts/test/ignore-snapshot-summary-reporter.cjs, tests/webpack-test/jest.config.js
There is no need to output all the obsoleted snapshots when test with `-t` which filters the test cases.
Before:
After:
=> test: not to display obsoleted snapshots when test with `-t`

crates/rspack_binding_options/src/options/raw_devtool.rs, crates/rspack_plugin_devtool/src/source_map_dev_tool_plugin.rs, packages/rspack-test-tools/tests/configCases/plugins/source-map-dev-tool-plugin/rspack.config.js
Passing the `test` option to `SourceMapDevToolPlugin` now results in the following error:
Panic occurred at runtime. Please file an issue on GitHub with the backtrace below: https://github.com/web-infra-dev/rspack/issues
Message:  Cannot start a runtime from within a runtime. This happens because a function (like `block_on`) attempted to block the current thread while the thread is being used to drive asynchronous tasks.
Location: crates/rspack_binding_options/src/options/raw_devtool.rs:99
=> fix: should not panic when passing `test` option to SourceMapDevToolPlugin

packages/rspack/tsup.config.ts
Should external package.json from bundle, this ensures that the Rspack canary package can read the correct version.
=> fix(core): should external package.json from bundle

packages/rspack/etc/api.md, packages/rspack/src/config/types.ts, packages/rspack/src/config/zod.ts, website/docs/en/config/module.mdx, website/docs/zh/config/module.mdx
- Add type & JSDoc for config.module
=> refactor: add JSDoc for configuration.module

website/components/CommunityCompatibleTable.tsx, website/components/i18n/en.json, website/components/i18n/zh.json
Updated `webpack-assets-manifest` compatibility status to PartiallyCompatible since rspack only supports basic usage of `webpack-assets-manifest`.
Related issue: https://github.com/web-infra-dev/rspack/issues/8058
=> docs: update `webpack-assets-manifest` compatibility status

Cargo.lock, Cargo.toml
=> fix: rspack source for stream_chunks_of_source_map_full

.github/renovate.json5, api-extractor.json, crates/node_binding/package.json, package.json, packages/create-rspack/package.json, packages/create-rspack/template-react-ts/package.json, packages/create-rspack/template-vanilla-ts/package.json, packages/create-rspack/template-vue-ts/package.json, packages/playground/package.json, packages/rspack-cli/package.json, packages/rspack-test-tools/etc/test-tools.api.md, packages/rspack-test-tools/package.json, packages/rspack/etc/core.api.md, packages/rspack/package.json, pnpm-lock.yaml, scripts/package.json, tsconfig.base.json, website/package.json
chore(deps): update ts 5.6
close https://github.com/web-infra-dev/rspack/pull/7211
after https://github.com/web-infra-dev/rspack/pull/8072, we don't rely on tsc to generate js files, so we can upgrade the version of typescript.
1. upgrade and unify the ts version `^5.6.3`
2. add renovate to revert https://github.com/web-infra-dev/rspack/pull/5470/files
=> chore(deps): update typescript to v5.6

crates/rspack_plugin_devtool/src/source_map_dev_tool_plugin.rs
=> fix: perf degradation in devtool plugin

website/docs/en/guide/optimization/profile.mdx, website/docs/zh/guide/optimization/profile.mdx
[Docs] Rsdoctor add the note for CssExtractRspackPlugin
=> chore(docs): rsdoctor add the note for CssExtractRspackPlugin

packages/rspack/etc/core.api.md, packages/rspack/src/builtin-plugin/HtmlRspackPlugin.ts
Currently, the latest published version of `html-webpack-plugin` is `5.6.0` and need to get hooks by `HtmlWebpackPlugin.getHooks`.
=> fix: compatible static methods with html-webpack-plugin 5.6.0

crates/rspack_binding_options/src/plugins/js_loader/resolver.rs
Assume: 
1. Creating an `SwcLoaderJsOptions` is costly
2. Most modules are created with same swc loader options
Cost:
1. `RwLock` and concurrent runtime.
Maybe there is a better cache strategy.
🙏 Help me run the benchmark.
=> perf: cache swc loader

packages/rspack/etc/core.api.md, packages/rspack/src/config/types.ts, packages/rspack/src/config/zod.ts
- Add type & JSDoc for config.target
- Add type & JSDoc for config.devtool
- Add type & JSDoc for config.node
- Add type & JSDoc for config.cache
- Add type & JSDoc for config.externalsPresets
=> refactor: add JSDoc to improve config.target, devtool, node, cache types.

crates/rspack_plugin_javascript/src/parser_plugin/worker_plugin.rs, packages/rspack-test-tools/tests/configCases/trusted-types/web-worker/index.js, packages/rspack-test-tools/tests/configCases/trusted-types/web-worker/module.js, packages/rspack-test-tools/tests/configCases/trusted-types/web-worker/rspack.config.js, packages/rspack-test-tools/tests/configCases/trusted-types/web-worker/test.config.js, packages/rspack-test-tools/tests/configCases/trusted-types/web-worker/worker.js
fix https://github.com/web-infra-dev/rspack/issues/8134
When `output.trustedTypes` is set, the `new Worker(new URL(xxx))`  should be compiled to `new Worker(__webpack_reuqire__.tu(new URL(xxx)))`, but now it is compiled to `new Worker(new URL(__webpack_require__.tu(xxx)))`
The `webpack-test/configCases/trusted-types/web-worker` case can pass because the mock environment does not have  `trustedTypes.createPolicy` so that the `__webpack_require__.tu(xxx)` will return `xxx` directly.
=> fix: generate correct worker expression with trusted types

crates/rspack_core/src/options/filename.rs, tests/webpack-test/configCases/asset-modules/data-url-extract/index.js, tests/webpack-test/configCases/asset-modules/data-url-extract/webpack.config.js, tests/webpack-test/configCases/asset-modules/resource-from-data-uri/index.js
See https://github.com/webpack/webpack/pull/18778 for more details.
=> fix: use content hash as [base] and [name] for extracted DataURIs

crates/rspack_plugin_javascript/src/dependency/esm/esm_export_expression_dependency.rs, crates/rspack_plugin_javascript/src/parser_plugin/esm_export_dependency_parser_plugin.rs, packages/rspack-test-tools/tests/__snapshots__/Config.test.js.snap, packages/rspack-test-tools/tests/configCases/parsing/harmony-export-comment/index.js, packages/rspack-test-tools/tests/configCases/parsing/harmony-export-comment/rspack.config.js, packages/rspack-test-tools/tests/configCases/parsing/harmony-export-comment/share.js, packages/rspack-test-tools/tests/configCases/parsing/harmony-export-comment/used.js, packages/rspack-test-tools/tests/treeShakingCases/pure_comments_magic_comments/__snapshots__/treeshaking.snap.txt
Should keep comments like `/* #__PURE__ */` of esm export
=> fix: should keep comments of esm export

website/docs/zh/plugins/webpack/module-federation-plugin.mdx
shareScope should be rename to shareStrategy in Chinese docs.
Ref: https://rspack.dev/zh/plugins/webpack/module-federation-plugin#sharescope-1
=> docs: rename shareScope to shareStrategy

packages/rspack/etc/core.api.md, packages/rspack/src/config/types.ts, packages/rspack/src/config/zod.ts
- Add type & JSDoc for config.stats
=> refactor: add JSDoc to improve config.stats types

Cargo.lock, Cargo.toml, crates/rspack_loader_lightningcss/Cargo.toml, crates/rspack_plugin_lightning_css_minimizer/Cargo.toml
Lightincss have a bug about minimizing CSS may shuffle the CSS property order.
The css code: 
```css
.foo { 
height: auto; 
height: calc(100vh - var(--header-height, 0rem)); 
}
```
After lightningcss minify, css code would like this
```css
.foo { 
height: calc(100vh - var(--header-height, 0rem)); 
height: auto; 
}
```
care the lightingcss publish cycle. we publish a new crate named `lightingcss_rs`;
So we update lightingcss to lightingcss_rs for fix this issues https://github.com/web-infra-dev/rspack/issues/7921
=> fix: temporarily use `lightingcss_rs` to fix CSS property order

packages/rspack/etc/core.api.md, packages/rspack/src/config/types.ts, packages/rspack/src/config/zod.ts
- Add type & JSDoc for config.experiments 
=> refactor: add JSDoc to improve config.experiments types

packages/rspack-test-tools/tests/errorCases/error-test-set.js, packages/rspack-test-tools/tests/errorCases/warning-test-set.js, packages/rspack/etc/core.api.md, packages/rspack/src/Compilation.ts
close #8109 
Enhance compatibility with ts-loader: https://github.com/TypeStrong/ts-loader/blob/6a4e29c729fd6727c1c625fad3a65d509c2c37eb/src/after-compile.ts#L464-L466
=> feat: add setters for errors and warnings in Compilation

packages/create-rspack/rslib.config.ts, packages/rspack-cli/bin/rspack, packages/rspack-cli/bin/rspack.js, packages/rspack-cli/package.json, packages/rspack-cli/rslib.config.ts, packages/rspack-cli/src/bootstrap.ts, packages/rspack-cli/src/cli.ts, packages/rspack-cli/src/utils/crossImport.ts, packages/rspack-cli/src/utils/profile.ts, packages/rspack-cli/tests/utils/test-utils.ts, pnpm-lock.yaml
Use Rslib to bundle `@rspack/cli` and output both ESM/CJS bundles, this means that `@rspack/cli` is now a dual package with better ESM support.
=> feat(CLI): make `@rspack/cli` dual package and bundle with Rslib

website/docs/en/blog/index.mdx, website/docs/en/config/index.mdx, website/docs/en/config/module.mdx, website/docs/en/config/output.mdx, website/docs/en/plugins/rspack/css-extract-rspack-plugin.mdx, website/docs/zh/blog/index.mdx, website/docs/zh/config/index.mdx, website/docs/zh/config/module.mdx, website/docs/zh/config/output.mdx, website/docs/zh/guide/features/web-workers.mdx, website/docs/zh/plugins/webpack/hot-module-replacement-plugin.mdx
Correct ES modules and some other spellings (Top-level await, CommonJS, etc)
=> docs: correct ES modules and some other spellings

packages/rspack/etc/core.api.md, packages/rspack/src/config/types.ts, packages/rspack/src/config/zod.ts
- Add type & JSDoc for config.watch
- Add type & JSDoc for config.watchOptions
=> refactor: add JSDoc to improve config.wath types

packages/rspack-test-tools/tests/configCases/split-chunks/rspack-issue-5657/rspack.config.js
Rspack project folder path in my pc contains `lib`, splitChunks split my normal chunks by mistake
So make this test case filter regex more accurate
=> fix: should correct cacheGroups test regex

crates/rspack_plugin_library/src/modern_module_library_plugin.rs, packages/rspack-test-tools/tests/__snapshots__/Config.test.js.snap, packages/rspack-test-tools/tests/configCases/library/modern-module-force-concaten/g/foo.js, packages/rspack-test-tools/tests/configCases/library/modern-module-force-concaten/g/index.js, packages/rspack-test-tools/tests/configCases/library/modern-module-force-concaten/rspack.config.js
If the root module is empty, it will store all bailout reasons of current config https://github.com/web-infra-dev/rspack/blob/ddd7eb9d3042a80df57fda2f1321e7d3091e0dae/crates/rspack_plugin_javascript/src/plugin/module_concatenation_plugin.rs#L982 Previously, this will make root module won't be force concatenated (see new added test case `g`)
=> fix(modern-module): concatenate entry module regardless bail reasons

packages/rspack-cli/tests/api/type/js-api-cjs.test.ts, packages/rspack-cli/tests/api/type/js-api-esm.test.mts
enhance the test of https://github.com/web-infra-dev/rspack/pull/8169
at present, we use `module.exports = rspack` to overrides the tsup output to not to export the `rspack.default`
`rspack.default.rspack` is not expected by all of us
=> test: add `rspack.default` should not exist test

.github/workflows/ci.yml
Trigger `pkg-preview` when the dependent jobs are skipped as well.
I noticed that sometimes `pkg-preview` gets skipped because the dependent jobs `rust_check` and `rust_test` are skipped.
=> fix(ci): trigger `pkg-preview` when the needs are skipped

crates/rspack_core/src/exports_info.rs, crates/rspack_plugin_javascript/src/plugin/flag_dependency_exports_plugin.rs, packages/rspack-test-tools/tests/watchCases/provided-exports/reexport-chain-strict/0/a.js, packages/rspack-test-tools/tests/watchCases/provided-exports/reexport-chain-strict/0/b.js, packages/rspack-test-tools/tests/watchCases/provided-exports/reexport-chain-strict/0/c.js, packages/rspack-test-tools/tests/watchCases/provided-exports/reexport-chain-strict/0/index.js, packages/rspack-test-tools/tests/watchCases/provided-exports/reexport-chain-strict/1/c.js, packages/rspack-test-tools/tests/watchCases/provided-exports/reexport-chain-strict/2/a.js, packages/rspack-test-tools/tests/watchCases/provided-exports/reexport-chain-strict/2/c.js
incremental provided exports should rebuild clean exports info
=> fix: incremental provided exports should rebuild clean exports info

packages/rspack/etc/core.api.md, packages/rspack/src/config/types.ts, packages/rspack/src/config/zod.ts
- Add JSDoc for config.ignoreWarnings.
- Add JSDoc for config.profile.
- Add JSDoc for config.bail.
=> refactor: add JSDoc to improve config.ignoreWarnings, profile, bail types

packages/rspack/etc/core.api.md, packages/rspack/src/config/types.ts, packages/rspack/src/config/zod.ts
- Add JSDoc for config.performance
=> refactor: add JSDoc to improve config.performance

crates/rspack_core/src/compiler/module_executor/ctrl.rs, crates/rspack_core/src/compiler/module_executor/entry.rs, crates/rspack_core/src/compiler/module_executor/execute.rs, crates/rspack_core/src/compiler/module_executor/mod.rs, packages/rspack-test-tools/tests/configCases/loader-import-module/with-layer/banner.js, packages/rspack-test-tools/tests/configCases/loader-import-module/with-layer/index.js, packages/rspack-test-tools/tests/configCases/loader-import-module/with-layer/loader.js, packages/rspack-test-tools/tests/configCases/loader-import-module/with-layer/rspack.config.js
This PR will pass layer arguments to factorize task when use import module.
=> fix: module_executor support layer

packages/rspack/etc/core.api.md, packages/rspack/src/builtin-plugin/SplitChunksPlugin.ts, packages/rspack/src/config/adapter.ts, packages/rspack/src/config/adapterRuleUse.ts, packages/rspack/src/config/defaults.ts, packages/rspack/src/config/index.ts, packages/rspack/src/config/normalization.ts, packages/rspack/src/config/types.ts, packages/rspack/src/config/zod.ts
=> refactor: add JSDoc to improve rspack config types

Cargo.lock, crates/node_binding/binding.d.ts, crates/rspack_binding_options/Cargo.toml, crates/rspack_binding_options/src/options/raw_builtins/mod.rs, crates/rspack_plugin_remove_duplicate_modules/Cargo.toml, crates/rspack_plugin_remove_duplicate_modules/LICENSE, crates/rspack_plugin_remove_duplicate_modules/src/lib.rs, packages/rspack/etc/core.api.md, packages/rspack/src/builtin-plugin/RemoveDuplicateModulesPlugin.ts, packages/rspack/src/builtin-plugin/index.ts, packages/rspack/src/exports.ts
Introduce RemoveDuplicateModulesPlugin.
This plugin can help you remove duplicated modules without SplitChunksPlugin. Some projects may meet problem that rebuild costs too much time, and SplitChunksPlugin is one of the reasons. But without SplitChunksPlugin there are many duplicated modules, so this plugin comes out.
You can use this in development to speed up your rebuild time, and disable splitChunks.
```javascript
const rspack = require('@rspack/core')
optimization: { splitChunks: false },
plugins: [new rspack.experiments.RemoveDuplicateModulesPlugin()]
}
```
=> feat: introduce RemoveDuplicateModulesPlugin

.github/workflows/get-runner-labels.yml
The github runners will be busy while publishing, we can use the self host runners to get runner labels and not to wait for the github runners
=> ci: allow to get label from self host runner

website/docs/en/config/module.mdx, website/docs/zh/config/module.mdx
`keepImportAttributes` is undocumented in swc doc, only [keepImportAssertions](https://swc.rs/docs/configuration/compilation#jscexperimentalkeepimportassertions).
https://github.com/tc39/proposal-import-attributes
=> docs: should enable swc `keepImportAttributes` configuration when use `Rule.with`

crates/rspack_plugin_javascript/src/parser_plugin/require_ensure_dependencies_block_parse_plugin.rs, tests/webpack-test/cases/parsing/typeof/index.js
Should handle `typeof require.ensure` with compile time evaluation and not throw a warning
=> fix: compile time evaluation of require.ensure

packages/rspack-cli/src/cli.ts, packages/rspack-cli/tests/serve/plugin-apply-error/rspack.config.js, packages/rspack-cli/tests/serve/plugin-apply-error/serve-plugin-apply-error.test.ts
fix https://github.com/web-infra-dev/rspack/issues/8103
=> fix(cli): display the error which is thrown by the plugin during the starting of `rspack serve`

Cargo.lock, crates/rspack_binding_options/src/options/raw_builtins/raw_ignore.rs, crates/rspack_binding_options/src/options/raw_module/mod.rs, crates/rspack_binding_options/src/options/raw_split_chunks/raw_split_chunk_size.rs, crates/rspack_core/src/compiler/compilation.rs, crates/rspack_core/src/compiler/make/repair/build.rs, crates/rspack_core/src/compiler/mod.rs, crates/rspack_core/src/compiler/module_executor/ctrl.rs, crates/rspack_core/src/compiler/module_executor/overwrite.rs, crates/rspack_core/src/options/module.rs, crates/rspack_core/src/utils/task_loop.rs, crates/rspack_fs/src/async.rs, crates/rspack_fs/src/native.rs, crates/rspack_fs/src/sync.rs, crates/rspack_fs_node/src/async.rs, crates/rspack_fs_node/src/sync.rs, crates/rspack_plugin_context_replacement/Cargo.toml, crates/rspack_plugin_context_replacement/src/lib.rs, crates/rspack_plugin_schemes/Cargo.toml, crates/rspack_plugin_schemes/src/http_uri.rs, crates/rspack_plugin_schemes/src/lockfile.rs
This PR will add `Debug` trait for FileSystem and Make Tasks to make the struct which use them easy to use `#[derive(Debug)]`
=> chore: add Debug trait for FileSystem and Make Task

.github/workflows/preview-commit.yml
Not sure why it is failed to compile aarch64&gnu on self-host runner, use github runner to avoid main branch ci failure
=> ci: allow aarch64 gnu compile on github runner in pkg preview

website/rspress.config.ts, website/theme/pages/index.tsx
Add Rspack's license to the footer of Rspack website.
=> docs: add license to website footer

website/docs/en/guide/features/builtin-swc-loader.mdx, website/docs/zh/guide/features/builtin-swc-loader.mdx
I've found that many users have trouble dealing with browser compatibility. Usually we recommend reading the SWC documentation or using Rsbuild, but it can be helpful if we can add some examples to the `builtin:swc-loader` documentation,
The SWC documentation also needs more work, it is too simple compared to the Babel documentation.
=> docs(swc-loader): add example for syntax lowering and polyfill

.github/workflows/ci.yml, .github/workflows/ecosystem-ci-trigger.yml, .github/workflows/release-nightly.yml
The rspack-ecosystem-ci repo has been moved to https://github.com/rspack-contrib/rspack-ecosystem-ci and we need to change the repo owner to match this change.
=> chore(ci): change repo owner of rspack-ecosystem-ci

packages/rspack-test-tools/tests/diagnosticsCases/config/builtin-swc-loader/stats.err, packages/rspack/src/builtin-loader/swc/types.ts, packages/rspack/src/config/adapterRuleUse.ts
Enable SWC `disableAllLints` by default to reduce overhead. We prefer to use ESLint or Biome as a linter rather than run lint rules during the JavaScript transformation.
- SWC lint rules: https://github.com/swc-project/swc/tree/b94a0e1fd2b900b05c5f18d3d993a74ff9cc6e7d/crates/swc_ecma_lints/src/rules
- https://x.com/kdy1dev/status/1840556491650240730
- https://x.com/kdy1dev/status/1841275955190616329
- 10000 modules: **4% faster**
```bash
hyperfine --warmup 1 --runs 3 'SWC_LINTS=true node --run build:rspack' 'SWC_LINTS=false node --run build:rspack'
Benchmark 1: SWC_LINTS=true node --run build:rspack
Time (mean ± σ):      2.382 s ±  0.027 s    [User: 4.496 s, System: 9.262 s]
Range (min … max):    2.359 s …  2.412 s    3 runs
Benchmark 2: SWC_LINTS=false node --run build:rspack
Time (mean …
```
=> perf: enable SWC `disableAllLints` by default to reduce overhead

packages/rspack/src/Compilation.ts, packages/rspack/src/util/ArrayQueue.ts
Use `ReturnType<>` to avoid explicitly naming the types of builtin iterators that have changed in 5.6, and convert manually implemented iterators to generators so they are compatible with builtin iterators under `--target ESNext`.
- Fixes part of #8277.
=> fix(type): Make iterators compatible with TS 5.6 `--target ESNext`

crates/node_binding/binding.d.ts, crates/rspack_core/src/compiler/mod.rs, crates/rspack_fs/src/async.rs, crates/rspack_fs/src/lib.rs, crates/rspack_fs/src/native.rs, crates/rspack_fs_node/src/async.rs, crates/rspack_fs_node/src/node.rs, packages/rspack/src/FileSystem.ts
Align output file sytem with https://github.com/webpack/webpack/blob/main/lib/util/fs.js#L344-L355
=> feat: add read API to output file system

crates/rspack_binding_values/src/module.rs, crates/rspack_core/src/chunk_graph/chunk_graph_chunk.rs, crates/rspack_core/src/compiler/make/cutout/has_module_graph_change.rs, crates/rspack_core/src/concatenated_module.rs, crates/rspack_core/src/context_module.rs, crates/rspack_core/src/external_module.rs, crates/rspack_core/src/module.rs, crates/rspack_core/src/normal_module.rs, crates/rspack_core/src/raw_module.rs, crates/rspack_core/src/self_module.rs, crates/rspack_core/src/stats/mod.rs, crates/rspack_macros/src/runtime_module.rs, crates/rspack_plugin_extract_css/src/css_module.rs, crates/rspack_plugin_javascript/src/plugin/module_concatenation_plugin.rs, crates/rspack_plugin_lazy_compilation/src/module.rs, crates/rspack_plugin_mf/src/container/container_entry_module.rs, crates/rspack_plugin_mf/src/container/fallback_module.rs, crates/rspack_plugin_mf/src/container/remote_module.rs, crates/rspack_plugin_mf/src/sharing/consume_shared_module.rs, crates/rspack_plugin_mf/src/sharing/provide_shared_module.rs, crates/rspack_plugin_split_chunks/src/module_group.rs, crates/rspack_plugin_split_chunks/src/plugin/max_size.rs
Only RuntimeModule depended on the Compilation to calculate the size.
=> refactor: module.size fn should a option compilation

crates/rspack_plugin_library/src/utils.rs, packages/rspack-test-tools/tests/configCases/externals/item-value-object/rspack.config.js, packages/rspack/etc/core.api.md, packages/rspack/src/config/types.ts, packages/rspack/src/config/zod.ts, website/docs/en/config/externals.mdx, website/docs/zh/config/externals.mdx
relate to https://github.com/web-infra-dev/rspack/issues/8248
Cause the external object value can only be used when libraryTarget or externalTarget is `umd`, and if it will throw error when `commonjs` or `commonjs2` or `root` is not set. So we can use zod to validate the external object value. 
The `amd` field is optional because it can generate `define([])` when not set, but there is a bug here in rspack that generated `define([null])`. This pr also fix it.
Not close the issue because when libraryTarget is not `umd`, the external object value is also valid but will generate a wired code. For example, `libraryTarget: "var"` and `react: { root: "React", commonjs: "react"  }` will generate `var external_react_root_react_commonjs_react = undefined` which can not actually work. 
So we may …
=> fix: types and docs of umd external object

website/docs/en/config/experiments.mdx, website/docs/zh/config/experiments.mdx
=> docs: add docs for incremental

Cargo.lock, crates/rspack_plugin_progress/Cargo.toml, crates/rspack_plugin_progress/src/lib.rs
close #4214 improve progress plugin support for multi config 
* before
* after
=> feat(core): improve progress plugin for multi compiler

package.json, patches/rollup-plugin-dts.patch, pnpm-lock.yaml
- Apply the patch I submitted upstream to Swatinem/rollup-plugin-dts#323.
- Fixes #8277.
- Closes #8300 (an alternate workaround for the same issue).
=> fix(type): Patch rollup-plugin-dts bug that broke prebundled zod

crates/rspack_plugin_hmr/src/lib.rs, packages/rspack-test-tools/tests/hotCases/runtime/add-runtime/index.js, packages/rspack-test-tools/tests/hotCases/runtime/add-runtime/lib/a.js, packages/rspack-test-tools/tests/hotCases/runtime/add-runtime/lib/b.js, packages/rspack-test-tools/tests/hotCases/runtime/add-runtime/lib/package.json, packages/rspack-test-tools/tests/hotCases/runtime/add-runtime/module.js, packages/rspack-test-tools/tests/hotCases/runtime/add-runtime/rspack.config.js, packages/rspack-test-tools/tests/hotCases/runtime/add-runtime/test.filter.js, packages/rspack-test-tools/tests/hotCases/runtime/add-runtime/worker.js
fix #7962
related: https://github.com/webpack/webpack/pull/18901
=> fix: hotUpdate chunk should have correct runtime

website/docs/en/guide/features/builtin-swc-loader.mdx, website/docs/zh/guide/features/builtin-swc-loader.mdx
Add swc cacheRoot guide to `swc-loader` documentation.
=> docs: add swc cacheRoot guide

crates/node_binding/binding.d.ts, crates/rspack_binding_values/src/module.rs, crates/rspack_core/src/normal_module.rs, packages/rspack/etc/core.api.md, packages/rspack/src/Module.ts
In monaco-editor-webpack-plugin, a new value is set for module.userRequest to avoid a bug in the NamedModulesPlugin.
See https://github.com/webpack/webpack/issues/4613#issuecomment-325178346 for details
However, the NamedModulesPlugin is outdated, and internally,
Rspack doesn't depend on module.userRequest to generate the identifier of the module.
=> fix: error for set user request

packages/rspack-test-tools/tests/configCases/module/falsy/index.js, packages/rspack-test-tools/tests/configCases/module/falsy/lib.js, packages/rspack-test-tools/tests/configCases/module/falsy/loader.js, packages/rspack-test-tools/tests/configCases/module/falsy/loader1.js, packages/rspack-test-tools/tests/configCases/module/falsy/loader2.js, packages/rspack-test-tools/tests/configCases/module/falsy/rspack.config.js, packages/rspack/etc/core.api.md, packages/rspack/src/config/adapter.ts, packages/rspack/src/config/types.ts, packages/rspack/src/config/zod.ts, website/docs/en/config/module.mdx, website/docs/zh/config/module.mdx
Close https://github.com/web-infra-dev/rspack/issues/8238
=> fix: falsy rule should be filtered

packages/playground/cases/hooks/asset-emitted/rspack.config.js, packages/rspack-test-tools/tests/defaultsCases/mode/production.js, packages/rspack-test-tools/tests/defaultsCases/mode/undefined.js, packages/rspack/src/builtin-plugin/FlagDependencyUsagePlugin.ts, packages/rspack/src/builtin-plugin/MangleExportsPlugin.ts, packages/rspack/src/builtin-plugin/ModuleConcatenationPlugin.ts, packages/rspack/src/config/defaults.ts, website/docs/en/config/experiments.mdx, website/docs/zh/config/experiments.mdx
fix https://github.com/web-infra-dev/rspack/issues/8106#issuecomment-2451220535
Before using `incremental: true` will panic in production build, caused by concatenateModules, this is expected but we should have better experience, so this PR will disable `incremental.moduleHashes/moduleCodegen/moduleRuntimeRequirements` when using with concatenateModules/usedExports/mangleExports, and log warnings.
And the docs is also updated to recommend user to only enable incremental in development mode.
=> fix: use incremental in production build

package.json, x.mjs
Using single quotes in `pnpm --filter '@rspack/*'` results in `"No projects matched the filters"`. Instead, we should use double quotes for proper functionality. (This issue may only occur on `Windows`, I don't have a `Mac` to verify)
=> fix: correct usage of `pnpm --filter` in package scripts

.github/renovate.json5
Typically, we do not want to let renovate to bump peer dependencies. Peer dependencies should be bumped manually with care.
Such as https://github.com/web-infra-dev/rspack/pull/8314
=> chore(renovate): manually update peer dependencies

Cargo.lock, Cargo.toml
bump swc to 4.0.2 
https://github.com/swc-project/swc/pull/9706 this will reduce rayon mutex contention during make phase
=> feat(core): bump swc to 4.0.2

packages/rspack-cli/bin/rspack.js
Enable Node.js 22 new compile cache in Rspack CLI, this makes Node.js startup faster.
- before:
- after:
- https://nodejs.org/id/blog/release/v22.8.0
- https://github.com/nodejs/node/pull/54501
- https://github.com/web-infra-dev/rsbuild/pull/3627
=> perf(cli): enable Node.js compile cache

crates/rspack_binding_values/src/chunk.rs, crates/rspack_binding_values/src/chunk_graph.rs, crates/rspack_binding_values/src/chunk_group.rs, crates/rspack_binding_values/src/compilation/mod.rs, crates/rspack_binding_values/src/module.rs, packages/rspack-test-tools/tests/compilerCases/access-outdated-compilation.js, packages/rspack-test-tools/tests/hotCases/stats/chunks/rspack.config.js, packages/rspack/src/Compiler.ts, tests/plugin-test/css-extract/TestMemoryFS.test.js
The Rspack compilation instance will be dropped on the Rust side after the compilation stage.
Before this PR, since the memory address of the compilation instance on the Rust side didn't change across multiple compilation cycles, when properties and methods on an outdated compilation instance on the JavaScript side were called, the data from the current Rust instance was retrieved, which was not as expected.
Now, Rspack will throw an error when an outdated JavaScript side compilation instance is accessed.
The compilation instance of Rspack will be dropped on the Rust side after compilation.
=> feat: throw error for outdated compilation

crates/node_binding/binding.d.ts, crates/rspack_binding_values/src/module.rs, packages/rspack-test-tools/tests/configCases/compilation/modules/index.js, packages/rspack-test-tools/tests/configCases/compilation/modules/rspack.config.js, packages/rspack/src/Module.ts
https://discord.com/channels/977448667919286283/1076017776583516220/1291085434042060931
=> feat: support compilation.modules[i].dependencies

crates/rspack_plugin_extract_css/src/css_module.rs, crates/rspack_plugin_extract_css/src/parser_plugin.rs
cssExtract turns css module into normal javascript module, this module should have strict buildInfo like native css module and other asset module
=> refactor: css-module should have strict buildInfo

packages/rspack-cli/package.json
`@rspack/cli` has been converted to a "dual package" and the `exports.types` is required to provide typing for the `dist/index.mjs`.
https://github.com/web-infra-dev/rspack/pull/8187
=> fix(cli): missing `exports.types` field

packages/rspack-cli/src/cli.ts
When the config is a function, we need to match `--config-name` on its return value, not the function itself.
- `tests/webpack-cli-test/build/config-name/config-name.test.js` seems to already have tests for this (`"should work with config as a function"`, `"should work with multiple values for --config-name when the config is a function"`), but it seems we never run those tests.
=> fix(cli): Run config function before looking for `--config-name`

crates/rspack_binding_options/src/options/raw_module/mod.rs, crates/rspack_core/src/options/module.rs, crates/rspack_plugin_asset/src/lib.rs, crates/rspack_util/src/merge.rs, tests/webpack-test/configCases/asset-modules/data-url/index.js, tests/webpack-test/configCases/asset-modules/data-url/test.filter.js
Passing Infinity to `parser.asset.dataUrlCondition.maxSize` currently has no effect, causing the [asset-modules/data-url](https://github.com/web-infra-dev/rspack/blob/84c4efa6253b8f48d735349c1fc5e25f369cdd1d/tests/webpack-test/configCases/asset-modules/data-url/webpack.config.js#L17-L21) test to fail.
=> fix: allow passing Infinity to parser.asset.dataUrlCondition.maxSize

crates/rspack_core/src/compiler/mod.rs, crates/rspack_core/src/resolver/boxfs.rs, crates/rspack_fs/Cargo.toml, crates/rspack_fs/src/async.rs, crates/rspack_fs/src/file_metadata.rs, crates/rspack_fs/src/lib.rs, crates/rspack_fs/src/native_fs.rs, crates/rspack_fs/src/sync.rs, crates/rspack_fs_node/src/async.rs, crates/rspack_fs_node/src/node.rs, crates/rspack_fs_node/src/sync.rs, crates/rspack_loader_runner/src/runner.rs
* update `ReadableFileSystem` trait to use `Utf8Path` and `Utf8PathBuf`
In rspack we use `Utf8Path` and `Utf8PathBuf` instead of `Path` and `PathBuf`. more info see https://github.com/web-infra-dev/rspack/pull/7570
* define `FileMetadata` to replace `Metadata` to make Async and Sync trait return same struct
=> refactor: rspack_fs use `Utf8Path` and `FileMetadata`

packages/rspack-test-tools/tests/configCases/externals/umd-array-externals/rspack.config.js, packages/rspack-test-tools/tests/configCases/externals/umd-validation-failed-no-externals-type/errors.js, packages/rspack-test-tools/tests/configCases/externals/umd-validation-failed-no-externals-type/index.js, packages/rspack-test-tools/tests/configCases/externals/umd-validation-failed-no-externals-type/lodash.js, packages/rspack-test-tools/tests/configCases/externals/umd-validation-failed-no-externals-type/rspack.config.js, packages/rspack-test-tools/tests/configCases/externals/umd-validation-failed/errors.js, packages/rspack-test-tools/tests/configCases/externals/umd-validation-failed/index.js, packages/rspack-test-tools/tests/configCases/externals/umd-validation-failed/lodash.js, packages/rspack-test-tools/tests/configCases/externals/umd-validation-failed/rspack.config.js, packages/rspack-test-tools/tests/configCases/externals/umd-validation-with-external-type/index.js, packages/rspack-test-tools/tests/configCases/externals/umd-validation-with-external-type/lodash.js, packages/rspack-test-tools/tests/configCases/externals/umd-validation-with-external-type/rspack.config.js, packages/rspack-test-tools/tests/configCases/externals/umd-validation/index.js, packages/rspack-test-tools/tests/configCases/externals/umd-validation/lodash.js, packages/rspack-test-tools/tests/configCases/externals/umd-validation/rspack.config.js, packages/rspack/etc/core.api.md, packages/rspack/src/config/types.ts, packages/rspack/src/config/utils.ts, packages/rspack/src/config/zod.ts, scripts/test/ignore-snapshot-default-reporter.cjs, website/docs/en/config/externals.mdx, website/docs/zh/config/externals.mdx
https://github.com/web-infra-dev/rspack/pull/8286/files#r1831012797
Cause lots of projects use object item of `externals` when not `umd` and it can actually work well. For example:
```js
output: {
library: {
type: "commonjs"
}
},
externalsType: "commonjs",
externals: {
// actually same as: `react: "REACT"` or `react: "commonjs REACT"`
react: {
commonjs: "REACT"
}
}
};
```
so if we just add a strict object validation to object item of `externals`, it will be a breaking change to these projects.
The object item of `externals` should be validate according to the values of `output.library.type/output.libraryTarget` and `externalsType`. Only if `output.library.type/output.libraryTarget` is set to `umd` and `externalsType` is not set or also set to `umd`, the object item in …
=> fix: required amd in umd external object

Cargo.lock, crates/rspack_binding_options/src/options/raw_builtins/raw_banner.rs, crates/rspack_plugin_banner/Cargo.toml, crates/rspack_plugin_banner/src/lib.rs
The current rule match is async, but it seems unnecessary. We can reuse existing AssetConditions to simplify the existing code.
=> refactor: reuse AssetConditions for banner plugin

crates/rspack_plugin_javascript/src/parser_plugin/api_plugin.rs, crates/rspack_plugin_javascript/src/utils/eval/mod.rs, packages/rspack-test-tools/tests/configCases/parsing/rspack-issue-7848-disable-layer/index.js, packages/rspack-test-tools/tests/configCases/parsing/rspack-issue-7848-disable-layer/rspack.config.js, packages/rspack-test-tools/tests/configCases/parsing/rspack-issue-7848-enable-layer/index.js, packages/rspack-test-tools/tests/configCases/parsing/rspack-issue-7848-enable-layer/rspack.config.js
see #7848 and test cases for more details.
I found that there are also issues with the evaluation of typeof. It should check whether the layer exists. I fixed this in this PR as well.
=> fix: compile time evaluation of `__webpack_layer__`

crates/rspack_core/src/compiler/compilation.rs, crates/rspack_plugin_extract_css/src/plugin.rs, crates/rspack_plugin_extract_css/src/runtime.rs, packages/playground/cases/lazy-compilation/css-update/index.test.ts, packages/playground/cases/lazy-compilation/css-update/rspack.config.js, packages/playground/cases/lazy-compilation/css-update/src/blue.css, packages/playground/cases/lazy-compilation/css-update/src/change.js, packages/playground/cases/lazy-compilation/css-update/src/index.js, packages/playground/cases/lazy-compilation/css-update/src/red.css, tests/plugin-test/css-extract/cases/runtime/expected/runtime~main.js
The hook `runtimeRequirementInTree` is different compared to webpack, we have current `runtime_requirements` represents current runtime_requirements, `all_runtime_requirements` represents all runtime_requirements, when insert a new RuntimeModule, the module should not depend on runtimeGlobals on runtime_requirements, it should use correct runtime_requirements at codegen phase
=> fix: css runtime should have hmr handler when lazy-compilation

packages/rspack/src/Compiler.ts, tests/webpack-test/hotCases/esm-dependency-import/import-meta-webpack-hot/index.js
closes https://github.com/web-infra-dev/rspack/issues/3169
Fixed an issue when constantly creating compilers and the memory is not getting freed after use.
This issue was fixed with `WeakRef` and function expression which does not capture `this`, which is `Compiler` in this case. But still, I'm not able to create a MRE with both minimal Rust and JS code. So this issue might be appropriately tackled once a MRE is created.
Tests will be added in up-coming PRs. We might need to take https://github.com/napi-rs/napi-rs/tree/main/memory-testing as a reference.
=> fix: fix `Compiler` not getting freed after use

crates/rspack_core/src/external_module.rs, packages/rspack-test-tools/tests/configCases/externals/commonjs-import/case.js, packages/rspack-test-tools/tests/configCases/externals/commonjs-import/index.js, packages/rspack-test-tools/tests/configCases/externals/commonjs-import/rspack.config.js, packages/rspack-test-tools/tests/configCases/externals/commonjs-import/test.config.js, packages/rspack/etc/core.api.md, packages/rspack/src/config/types.ts, packages/rspack/src/config/zod.ts, website/docs/en/config/externals.mdx, website/docs/zh/config/externals.mdx
Fix https://github.com/web-infra-dev/rslib/issues/121.
Introducing `'commonjs-import'`, a new Rspack exclusive external type for Rslib. It will turn all external module into `commonjs` type unless the ones with `import()`.
Keeping `import()` will allowing import ESM modules from CJS module, esbuild also do this by default when node target is above `13.2.0`.
=> feat(externals): support 'commonjs-import' type

packages/rspack-cli/package.json, pnpm-lock.yaml
After cloning project && pnpm install, then run `x ready`,  `rspack-cli`'s tests failed due to strip-ansi can't be resolved. 
just add it in the dev deps.
=> chore(rspack-cli):  add strip-ansi in dev deps

crates/rspack_core/src/compiler/make/repair/add.rs, crates/rspack_core/src/compiler/make/repair/build.rs, crates/rspack_core/src/compiler/make/repair/factorize.rs, crates/rspack_core/src/compiler/make/repair/process_dependencies.rs, crates/rspack_core/src/compiler/module_executor/ctrl.rs, crates/rspack_core/src/compiler/module_executor/entry.rs, crates/rspack_core/src/compiler/module_executor/execute.rs, crates/rspack_core/src/compiler/module_executor/overwrite.rs, crates/rspack_core/src/utils/task_loop.rs
`sync_run` is actually a async function now, so the `sync_run` name is kind of awkward, what `async_run` and `sync_run` actually means is 
* `sync_run`: can only be running in main thread(the thread drives task_loop), cause it can exclusively access mutable global state
* `async_run`: can be running in background threads
so I think run_in_main_thread and run_in_backgrund_thread is more accurate, but it's too verbose
so change `sync_run` to `main_run` and `async_run` to `background_run`
I'm open to better name cause I don't think these two names are perfect
=> refactor: rename async_run to background_run & sync_run to main_run

crates/rspack_core/src/compiler/module_executor/mod.rs, crates/rspack_core/src/utils/task_loop.rs
rspack may have hang risk when contains too much task in join_all and block_on, and the automatic cooperative task yielding is useless in rspack scenario(we don't care task latency), it also may bring litter performance benefits(cause no need to do automatically yield)
some users report rspack may block infinitely and I'm not sure related to it.
* https://github.com/rust-lang/futures-rs/issues/2157
* https://tokio.rs/blog/2020-04-preemption
=> fix(core): remove hang risk caused by coop budget in tokio

packages/rspack/src/Compiler.ts
Fixed `MultiCompiler` test. Some of the cases tested scenarios where closing the compiler when it is still running. However in previous memory leak fix PR, we freed the native compiler when `compiler.close` is called. Thus, causing a segmentation fault.
To fix this issue, we need to add a compiler status check to free only if it's not running.
=> fix: should not free native compiler while compiler is running

.github/workflows/ci.yml, crates/rspack_cacheable/src/deserialize.rs, crates/rspack_cacheable_test/tests/macro/cacheable_dyn.rs, crates/rspack_cacheable_test/tests/macro/manual_cacheable_dyn.rs, crates/rspack_cacheable_test/tests/macro/manual_cacheable_dyn_with_generics.rs, crates/rspack_macros_test/tests/compiletest.rs
1. cacheable::from_byte align bytes ptr address. This will fix `UnalignedPointer` error in rkyv when miri test.
2. skip `cacheable_dyn` miri test. The global register crate like `inventory` not work in miri test.
=> fix: align bytes ptr address for `cacheable::from_byte`

crates/node_binding/binding.d.ts, crates/rspack_binding_options/src/options/raw_builtins/raw_lightning_css_minimizer.rs, crates/rspack_loader_lightningcss/src/config.rs, packages/rspack/etc/core.api.md, packages/rspack/src/builtin-loader/lightningcss/index.ts, packages/rspack/src/builtin-plugin/LightningCssMinimizerRspackPlugin.ts, website/docs/en/guide/features/builtin-lightningcss-loader.mdx, website/docs/en/plugins/rspack/lightning-css-minimizer-rspack-plugin.mdx, website/docs/zh/guide/features/builtin-lightningcss-loader.mdx, website/docs/zh/plugins/rspack/lightning-css-minimizer-rspack-plugin.mdx
In lightningcss, the [draft syntax options](https://lightningcss.dev/transpilation.html#draft-syntax) is drafts. 
We should align the type with lightningcss, while have not break change. So we maintain `options.draft` and `options.drafts`, then we use drafts firstly if user provide both drafts and draft options.
It's the product of another hand, [This PR](https://github.com/web-infra-dev/rspack/pull/8197) from @zackarychapple
=> fix(lightningcss): align type with lightningcss

crates/rspack_binding_values/src/html.rs, packages/rspack-test-tools/tests/configCases/builtins/html-issue-8410/index.js, packages/rspack-test-tools/tests/configCases/builtins/html-issue-8410/rspack.config.js, packages/rspack-test-tools/tests/configCases/builtins/html-issue-8410/test.config.js
fix #8410
In fact, attr_name should not be converted to lowercase either, as this is the job of the minifier. However, it seems that swc_html_minifier currently does not support the caseSensitive configuration.
=> fix: the attribute values of HTML tags should not be converted to lowercase

crates/rspack_plugin_split_chunks/src/plugin/max_size.rs, packages/rspack-test-tools/tests/configCases/split-chunks/max-size-fit/400k.js, packages/rspack-test-tools/tests/configCases/split-chunks/max-size-fit/50k-1.js, packages/rspack-test-tools/tests/configCases/split-chunks/max-size-fit/50k-2.js, packages/rspack-test-tools/tests/configCases/split-chunks/max-size-fit/50k-3.js, packages/rspack-test-tools/tests/configCases/split-chunks/max-size-fit/50k-4.js, packages/rspack-test-tools/tests/configCases/split-chunks/max-size-fit/50k-5.js, packages/rspack-test-tools/tests/configCases/split-chunks/max-size-fit/50k-6.js, packages/rspack-test-tools/tests/configCases/split-chunks/max-size-fit/50k-7.js, packages/rspack-test-tools/tests/configCases/split-chunks/max-size-fit/50k-8.js, packages/rspack-test-tools/tests/configCases/split-chunks/max-size-fit/50k.js, packages/rspack-test-tools/tests/configCases/split-chunks/max-size-fit/index.js, packages/rspack-test-tools/tests/configCases/split-chunks/max-size-fit/rspack.config.js, packages/rspack-test-tools/tests/configCases/split-chunks/max-size-fit/test.config.js
close #8310
There is a bug in splitChunks `ensureMaxSizeFit`, ignored some corner situation while detecting which modules should be placed to which chunk, causing some modules are not split.
Test cases are from https://github.com/bigbossx/split-chunk-bug, by @bigbossx
=> fix: should respect max size correctly

crates/rspack_fs/src/file_metadata.rs
Some linux musl can not get create time, and it will make resolve failed because of `metadata` return err.
This PR will specify a default value of 0 for the creation time when the platform does not support it.
=> fix: linux musl resolve failed

.cargo/config.toml
Use Hybrid CRT (Linking `vcruntime` and `ucrtbase` statically).
See: https://github.com/web-infra-dev/rspack/pull/8451
For aarch64 msvc, it is not required to install VS CRT manually as a dependency anymore.
It's recommended to use Windows 10 or newer with rspack.
=> build(windows): static linking VS CRT on aarch64 msvc !windows

Cargo.lock, crates/node_binding/src/resolver_factory.rs, crates/rspack_core/src/cache/mod.rs, crates/rspack_core/src/cache/persistent/mod.rs, crates/rspack_core/src/cache/persistent/snapshot/mod.rs, crates/rspack_core/src/cache/persistent/snapshot/strategy.rs, crates/rspack_core/src/compiler/compilation.rs, crates/rspack_core/src/compiler/make/repair/build.rs, crates/rspack_core/src/compiler/make/repair/mod.rs, crates/rspack_core/src/compiler/mod.rs, crates/rspack_core/src/module.rs, crates/rspack_core/src/resolver/boxfs.rs, crates/rspack_core/src/resolver/factory.rs, crates/rspack_core/src/resolver/resolver_impl.rs, crates/rspack_fs/src/lib.rs, crates/rspack_fs/src/memory_fs.rs, crates/rspack_fs/src/native_fs.rs, crates/rspack_fs/src/sync.rs, crates/rspack_loader_runner/src/runner.rs
rename `FileSystem` to `SyncFileSystem` since we plan to introduce `FileSystem` as `SyncFileSystem` + `AsyncFileSystem`
=> refactor: rename FileSystem to SyncFileSystem

crates/node_binding/src/resolver_factory.rs, crates/rspack_core/src/cache/mod.rs, crates/rspack_core/src/cache/persistent/mod.rs, crates/rspack_core/src/cache/persistent/snapshot/mod.rs, crates/rspack_core/src/cache/persistent/snapshot/strategy.rs, crates/rspack_core/src/compiler/compilation.rs, crates/rspack_core/src/compiler/make/repair/build.rs, crates/rspack_core/src/compiler/make/repair/mod.rs, crates/rspack_core/src/compiler/mod.rs, crates/rspack_core/src/module.rs, crates/rspack_core/src/resolver/boxfs.rs, crates/rspack_core/src/resolver/factory.rs, crates/rspack_core/src/resolver/resolver_impl.rs, crates/rspack_fs/src/async.rs, crates/rspack_fs/src/fs.rs, crates/rspack_fs/src/lib.rs, crates/rspack_fs/src/memory_fs.rs, crates/rspack_fs/src/native_fs.rs, crates/rspack_loader_runner/src/runner.rs, crates/rspack_plugin_schemes/src/http_cache.rs, crates/rspack_plugin_schemes/src/lockfile.rs
It's not necessary to distinguish different filesystem trait in rust side, which only cause maintenance burden, 
we just need to distinguish input & output & intermediate filesystem in ThreadsafeNodeFS
=> refactor: unify to filesystem in rspack_core

package.json, packages/rspack-test-tools/package.json, packages/rspack-test-tools/tests/configCases/chunk-loading/worker-loader/index.js, packages/rspack-test-tools/tests/configCases/chunk-loading/worker-loader/rspack.config.js, packages/rspack-test-tools/tests/configCases/chunk-loading/worker-loader/worker-async.js, packages/rspack-test-tools/tests/configCases/chunk-loading/worker-loader/worker.js, packages/rspack/etc/core.api.md, packages/rspack/src/builtin-plugin/WebWorkerTemplatePlugin.ts, pnpm-lock.yaml
Fixed an issue where dynamic chunk manually created by worker-loader is failed to load.
See: https://github.com/webpack/webpack/blob/89dfc9a5c575dc691e3ac6a965d39c854fca3986/lib/webworker/WebWorkerTemplatePlugin.js#L20
=> fix: `WebWorkerTemplatePlugin` should generate import-scripts chunk loading runtime

crates/rspack_plugin_library/src/assign_library_plugin.rs, tests/webpack-test/configCases/library/issue-18932/index.js, tests/webpack-test/configCases/library/issue-18932/webpack.config.js
See https://github.com/webpack/webpack/issues/18932 for background.
=> fix: variable name conflict with concatenate and runtime code

crates/rspack_core/src/utils/task_loop.rs
`tx` is the sender of a channel for `TaskResult<Ctx>`.
=> chore: update error message for task loop

crates/node_binding/binding.d.ts, crates/rspack_binding_options/src/options/raw_output.rs, crates/rspack_core/src/external_module.rs, crates/rspack_core/src/options/output.rs, crates/rspack_plugin_javascript/src/dependency/esm/external_module_dependency.rs, crates/rspack_plugin_javascript/src/plugin/api_plugin.rs, packages/rspack-test-tools/tests/__snapshots__/Config.test.js.snap, tests/webpack-test/configCases/node/prefix-in-runtime/index.js, tests/webpack-test/configCases/node/prefix-in-runtime/test.filter.js, tests/webpack-test/configCases/node/prefix-in-runtime/webpack.config.js
I found this option in the [documentation](https://rspack.dev/config/output#outputenvironment), but it is not currently supported. It is intended to control whether the node: prefix is added when importing Node.js modules in the generated runtime code, enabling the code to run on other platforms such as Deno and Bun.
=> feat: support output.environment.nodePrefixForCoreModules

crates/rspack_cacheable/src/context.rs, crates/rspack_cacheable/src/with/as.rs, crates/rspack_cacheable/src/with/as_cacheable.rs, crates/rspack_cacheable/src/with/as_inner.rs, crates/rspack_cacheable/src/with/as_map.rs, crates/rspack_cacheable/src/with/as_ref_str.rs, crates/rspack_cacheable/src/with/as_string.rs, crates/rspack_cacheable/src/with/as_tuple2.rs, crates/rspack_cacheable/src/with/as_tuple3.rs, crates/rspack_cacheable/src/with/as_vec.rs, crates/rspack_cacheable/src/with/inline.rs, crates/rspack_cacheable/src/with/unsupported.rs, crates/rspack_cacheable_test/tests/macro/cacheable/as_attr.rs, crates/rspack_cacheable_test/tests/macro/manual_cacheable/as_attr.rs, crates/rspack_macros/src/cacheable/impl_as.rs
1. Add `?Size` for all of `Serializer` and `Deserializer` in `rspack_cacheable`
2. `as` attr support use with `dyn Trait`
=> feat(rspack_cacheable): `as` attr support use with dyn trait

crates/rspack_napi/src/callback.rs, crates/rspack_napi/src/threadsafe_function.rs
Reduce memory cost for tsfn error resolver
=> perf: create tsfn error resolver once

crates/rspack_core/src/compiler/mod.rs, crates/rspack_core/src/old_cache/occasion/chunk_render.rs, crates/rspack_plugin_copy/src/lib.rs, packages/rspack-test-tools/tests/watchCases/css/chunk-render-cache-css-extract/0/a.css, packages/rspack-test-tools/tests/watchCases/css/chunk-render-cache-css-extract/0/ab.js, packages/rspack-test-tools/tests/watchCases/css/chunk-render-cache-css-extract/0/b.css, packages/rspack-test-tools/tests/watchCases/css/chunk-render-cache-css-extract/0/ba.js, packages/rspack-test-tools/tests/watchCases/css/chunk-render-cache-css-extract/0/warnings.js, packages/rspack-test-tools/tests/watchCases/css/chunk-render-cache-css-extract/1/ab.js, packages/rspack-test-tools/tests/watchCases/css/chunk-render-cache-css-extract/1/warnings.js, packages/rspack-test-tools/tests/watchCases/css/chunk-render-cache-css-extract/2/ab.js, packages/rspack-test-tools/tests/watchCases/css/chunk-render-cache-css-extract/rspack.config.js, packages/rspack-test-tools/tests/watchCases/css/chunk-render-cache-css-extract/test.config.js, packages/rspack-test-tools/tests/watchCases/css/chunk-render-cache-experiments-css/0/a.css, packages/rspack-test-tools/tests/watchCases/css/chunk-render-cache-experiments-css/0/ab.js, packages/rspack-test-tools/tests/watchCases/css/chunk-render-cache-experiments-css/0/b.css, packages/rspack-test-tools/tests/watchCases/css/chunk-render-cache-experiments-css/0/ba.js, packages/rspack-test-tools/tests/watchCases/css/chunk-render-cache-experiments-css/0/warnings.js, packages/rspack-test-tools/tests/watchCases/css/chunk-render-cache-experiments-css/1/ab.js, packages/rspack-test-tools/tests/watchCases/css/chunk-render-cache-experiments-css/1/warnings.js, packages/rspack-test-tools/tests/watchCases/css/chunk-render-cache-experiments-css/2/ab.js, packages/rspack-test-tools/tests/watchCases/css/chunk-render-cache-experiments-css/rspack.config.js, packages/rspack-test-tools/tests/watchCases/css/chunk-render-cache-experiments-css/test.config.js
Don't cache diagnostics for chunk render cache
=> fix: chunk render cache panic on css extract diagnostics

packages/rspack-test-tools/tests/compilerCases/compiler-stats-shutdown.js, packages/rspack/etc/core.api.md, packages/rspack/src/Compilation.ts, packages/rspack/src/Compiler.ts, packages/rspack/src/Stats.ts
Fixed an issue where the compiler/compilation was accessed after it was closed. 
Otherwise, it might report segmentation faults.
EDIT: use `process.nextTick` to postpone cleanups to the next tick to support accessing stats within the same tick.
=> fix: should report errors if stats was being accessed after the compiler was closed

crates/rspack_core/src/build_chunk_graph/incremental.rs, packages/rspack-test-tools/tests/watchCases/build-chunk-graph/keep-order-index/0/ab.js, packages/rspack-test-tools/tests/watchCases/build-chunk-graph/keep-order-index/0/ba.js, packages/rspack-test-tools/tests/watchCases/build-chunk-graph/keep-order-index/0/index.js, packages/rspack-test-tools/tests/watchCases/build-chunk-graph/keep-order-index/1/ab.js, packages/rspack-test-tools/tests/watchCases/build-chunk-graph/keep-order-index/rspack.config.js, packages/rspack-test-tools/tests/watchCases/build-chunk-graph/keep-order-index/test.config.js
build chunkGroup from cache should rebuild `post/pre_order_index` as well
=> fix: should have module-post-order-index when incremental build

crates/node_binding/binding.d.ts, crates/node_binding/src/plugins/interceptor.rs, crates/rspack_binding_values/src/compilation/mod.rs, crates/rspack_binding_values/src/module.rs, crates/rspack_binding_values/src/source.rs, packages/rspack/src/Compilation.ts, packages/rspack/src/util/source.ts
Use `BufferSlice`.
The main difference between `BufferSlice` and `Buffer` is the prior one is zero-copy if passing from JS runtimes to Rust.
However, the second one does not have this benefit. Under the hood, `Buffer` leverages thread-safe function to free when it's no longer needed. `BufferSlice`s are just collected by finalizers registered on the fly.
`BufferSlice` cannot be used between functions and `Buffer` can.
=> perf: move from `Buffer` to zero-copy `BufferSlice`

crates/rspack_core/src/old_cache/local/code_splitting_cache.rs, crates/rspack_ids/src/deterministic_module_ids_plugin.rs, packages/rspack-test-tools/tests/watchCases/split-chunks-incremental/pre-order-index/0/index.js, packages/rspack-test-tools/tests/watchCases/split-chunks-incremental/pre-order-index/0/lib.js, packages/rspack-test-tools/tests/watchCases/split-chunks-incremental/pre-order-index/1/lib.js, packages/rspack-test-tools/tests/watchCases/split-chunks-incremental/pre-order-index/rspack.config.js, packages/rspack-test-tools/tests/watchCases/split-chunks-incremental/pre-order-index/test.config.js
close #7031
mgm.preOrderIndex is set by buildChunkGraph, which is skipped during incremental rebuild.
When enable `newIncremental.buildChunkGraph`, preOrderIndex is wrong by design, I'll refactor module.preOrderIndex soon in another PR
=> fix: rebuild should reset module.preOrderIndex

crates/node_binding/binding.d.ts, crates/rspack_binding_options/src/options/raw_builtins/raw_html.rs, crates/rspack_plugin_html/src/asset.rs, crates/rspack_plugin_html/src/config.rs, crates/rspack_plugin_html/src/lib.rs, packages/rspack/etc/core.api.md, packages/rspack/src/builtin-plugin/HtmlRspackPlugin.ts, tests/plugin-test/html-plugin/basic.test.js, website/docs/en/plugins/rspack/html-rspack-plugin.mdx, website/docs/zh/plugins/rspack/html-rspack-plugin.mdx
close #8533 
This PR adds support for the `chunksSortMode` option in the HtmlRspackPlugin. When chunksSortMode is set to `manual`, the chunks in the HTML will be sorted according to the order specified in the `chunks` option.
=> feat: support chunksSortMode option to HtmlRspackPlugin

website/docs/en/plugins/webpack/define-plugin.mdx, website/docs/zh/plugins/webpack/define-plugin.mdx
Before #7108 there was a [`JSON.stringify()` call](https://github.com/web-infra-dev/rspack/pull/7108/files#diff-5f4e45b52caf136609c5147f1223fae8f4bfaada72f088bab2e4487b0dbb8510R2) in `DefinePlugin`
The change landed in https://github.com/web-infra-dev/rspack/releases/tag/v1.0.0-alpha.3
A couple of alpha versions do not require `JSON.stringify()`
=> docs: align `DefinePlugin` with #7108 in v0.x

crates/rspack_plugin_css/src/parser_and_generator/mod.rs, crates/rspack_plugin_css/src/utils.rs, packages/rspack-test-tools/tests/builtinCases/plugin-css-modules/modules-composes/__snapshots__/output.snap.txt, packages/rspack-test-tools/tests/builtinCases/plugin-css-modules/modules-ident-name/__snapshots__/output.snap.txt, packages/rspack-test-tools/tests/hotCases/css/css-modules/__snapshots__/web/1.snap.txt, packages/rspack-test-tools/tests/hotCases/css/css-modules/index.js, packages/rspack-test-tools/tests/hotCases/css/parser-and-generator-states/__snapshots__/web/1.snap.txt, packages/rspack-test-tools/tests/hotCases/css/parser-and-generator-states/index.js, packages/rspack-test-tools/tests/treeShakingCases/css/__snapshots__/treeshaking.snap.txt
refactor css hmr, see https://github.com/webpack/webpack/pull/19021.
Previous:
All css modules are self-accepted, but once modifies its classNames, importers won't know the css modules have changes.
This PR:
css modules are self-accepted if they have no className changes or if the css type is not `css/modules`. This way the importers are easily informed that the css has updates
=> refactor: css hmr

Cargo.lock, crates/rspack_binding_values/src/compilation/mod.rs, crates/rspack_core/src/cache/persistent/mod.rs, crates/rspack_core/src/cache/persistent/snapshot/mod.rs, crates/rspack_core/src/cache/persistent/snapshot/strategy.rs, crates/rspack_core/src/compiler/compilation.rs, crates/rspack_core/src/compiler/hmr.rs, crates/rspack_core/src/compiler/make/mod.rs, crates/rspack_core/src/compiler/make/repair/factorize.rs, crates/rspack_core/src/compiler/module_executor/execute.rs, crates/rspack_core/src/context_module.rs, crates/rspack_core/src/module.rs, crates/rspack_core/src/module_factory.rs, crates/rspack_core/src/normal_module.rs, crates/rspack_core/src/utils/file_counter/incremental_info.rs, crates/rspack_core/src/utils/file_counter/mod.rs, crates/rspack_paths/src/lib.rs, crates/rspack_plugin_copy/src/lib.rs, crates/rspack_plugin_extract_css/Cargo.toml, crates/rspack_plugin_extract_css/src/css_dependency.rs, crates/rspack_plugin_extract_css/src/css_module.rs, crates/rspack_plugin_html/src/plugin.rs, crates/rspack_plugin_lazy_compilation/src/module.rs, crates/rspack_plugin_mf/src/sharing/consume_shared_plugin.rs
Reduced a big amount of memory of copying `PathBuf`s.
=> perf: reduce memory consumption of paths

crates/rspack_core/src/incremental/mutations.rs
I changed a `par_iter` to `iter` in last PR for better debugging and forgot change it back..
=> fix(incremental): get affected modules with chunk graph perf regression

crates/rspack_binding_values/src/compilation/mod.rs, crates/rspack_core/src/compiler/compilation.rs, crates/rspack_core/src/compiler/make/mod.rs, crates/rspack_core/src/compiler/module_executor/mod.rs, crates/rspack_core/src/stats/mod.rs
This PR will remove `compilation.built_module` and use `built_module()` method to proxy it to `compilation.make_artifact.built_module`.
=> refactor: remove compilation.built_module

crates/rspack_core/src/compiler/compilation.rs, crates/rspack_plugin_devtool/src/eval_dev_tool_module_plugin.rs, crates/rspack_plugin_devtool/src/eval_source_map_dev_tool_plugin.rs, packages/rspack-test-tools/tests/configCases/trusted-types/module-runtime-requirement/index.js, packages/rspack-test-tools/tests/configCases/trusted-types/module-runtime-requirement/rspack.config.js, packages/rspack-test-tools/tests/configCases/trusted-types/module-runtime-requirement/test.config.js, packages/rspack-test-tools/tests/configCases/trusted-types/module-runtime-requirement/worker.js
Relate to https://github.com/web-infra-dev/rspack/issues/8512
This pr fix the missing `__webpack_require__` error. `RuntimeGlobal.createScript` should be added to module runtime requirements.
=> fix: trusted type should add module runtime requirements

tests/webpack-test/configCases/clean/ignore-fn/test.filter.js, tests/webpack-test/configCases/clean/ignore-hook/test.filter.js, tests/webpack-test/configCases/clean/ignore-rx/test.filter.js, tests/webpack-test/configCases/code-generation/require-context-id/test.filter.js, tests/webpack-test/configCases/code-generation/use-strict/index.js, tests/webpack-test/configCases/code-generation/use-strict/test.filter.js, tests/webpack-test/configCases/concatenate-modules/split-chunk-entry-module/test.filter.js, tests/webpack-test/configCases/concatenate-modules/split-chunk-entry-module/webpack.config.js, tests/webpack-test/configCases/contenthash/assets/test.filter.js, tests/webpack-test/configCases/contenthash/assets/webpack.config.js, tests/webpack-test/configCases/contenthash/include-chunk-id/test.filter.js, tests/webpack-test/configCases/context-exclusion/simple/test.filter.js, tests/webpack-test/configCases/context-replacement/c/node_modules/d.js, tests/webpack-test/configCases/context-replacement/c/test.filter.js, tests/webpack-test/configCases/context-replacement/d/test.filter.js
- remove test.filter.js for passed webpack test
- create issues for failed webpack test
=> test: create issues for failed webpack test

crates/node_binding/binding.d.ts, crates/rspack_binding_options/src/options/raw_output.rs, crates/rspack_core/src/options/output.rs, crates/rspack_plugin_runtime/src/runtime_module/get_trusted_types_policy.rs, crates/rspack_plugin_runtime/src/runtime_module/runtime/get_trusted_types_policy.js, packages/rspack-test-tools/tests/defaultsCases/output/unique-name.js, packages/rspack-test-tools/tests/runtimeDiffCases/runtime-module/get-trusted-types-policy#policy-failure-continue/rspack.config.js, packages/rspack-test-tools/tests/runtimeDiffCases/runtime-module/get-trusted-types-policy#policy-failure-continue/src/chunk.js, packages/rspack-test-tools/tests/runtimeDiffCases/runtime-module/get-trusted-types-policy#policy-failure-continue/src/index.js, packages/rspack-test-tools/tests/runtimeDiffCases/runtime-module/get-trusted-types-policy#policy-failure-continue/test.config.js, packages/rspack-test-tools/tests/runtimeDiffCases/runtime-module/get-trusted-types-policy#policy-failure-continue/webpack.config.js, packages/rspack/etc/core.api.md, packages/rspack/src/config/defaults.ts, packages/rspack/src/config/types.ts, packages/rspack/src/config/zod.ts, website/docs/en/config/output.mdx, website/docs/zh/config/output.mdx
close https://github.com/web-infra-dev/rspack/issues/8512
support `output.trustedTypes.onPolicyCreationFailure`
=> feat: support `output.trustedTypes.onPolicyCreationFailure`

crates/rspack_plugin_devtool/src/source_map_dev_tool_plugin.rs, packages/rspack-test-tools/tests/configCases/output/source-map-filename-contenthash/chunk.js, packages/rspack-test-tools/tests/configCases/output/source-map-filename-contenthash/index.js, packages/rspack-test-tools/tests/configCases/output/source-map-filename-contenthash/rspack.config.js, packages/rspack-test-tools/tests/configCases/output/source-map-filename-contenthash/test.config.js
fix https://github.com/web-infra-dev/rspack/issues/8597
https://github.com/webpack/webpack/blob/main/lib/SourceMapDevToolPlugin.js#L497-L502
=> fix: source map file should use contenthash itself

crates/rspack_core/src/build_chunk_graph/code_splitter.rs, crates/rspack_core/src/chunk_graph/chunk_graph_module.rs, crates/rspack_core/src/compiler/make/cutout/mod.rs, crates/rspack_core/src/concatenated_module.rs, crates/rspack_core/src/incremental/mutations.rs, crates/rspack_core/src/module_graph/mod.rs, crates/rspack_plugin_dll/src/lib_manifest_plugin.rs, crates/rspack_plugin_javascript/src/plugin/infer_async_modules_plugin.rs, crates/rspack_plugin_library/src/modern_module_library_plugin.rs, crates/rspack_plugin_warn_sensitive_module/src/lib.rs
avoid heap allocation for getting connections
=> perf: avoid heap allocation for getting connections

Cargo.lock, crates/rspack_loader_swc/src/compiler.rs, crates/rspack_plugin_swc_js_minimizer/src/minify.rs, crates/rspack_util/Cargo.toml, crates/rspack_util/src/swc.rs, packages/rspack-test-tools/tests/builtinCases/swc-loader/minify/__snapshots__/output.snap.txt, packages/rspack-test-tools/tests/builtinCases/swc-loader/minify/index.js, packages/rspack-test-tools/tests/builtinCases/swc-loader/minify/rspack.config.js, packages/rspack-test-tools/tests/configCases/plugins/minify-comment-some-preserve-annotations/a.js, packages/rspack-test-tools/tests/configCases/plugins/minify-comment-some-preserve-annotations/index.js, packages/rspack-test-tools/tests/configCases/plugins/minify-comment-some-preserve-annotations/rspack.config.js, packages/rspack-test-tools/tests/configCases/plugins/minify-comment-some-preserve-annotations/test.config.js
Fix https://github.com/web-infra-dev/rslib/issues/418.
The behavior of the new `minify_file_comments` function in `swc_loader` remains consistent with the current implementation:
1. `preserveAllComments: true`
2. `preserveAllComments: false`:
1. `minify.format.comments: "all"`: true
2. `minify.format.comments: "some"`: false
3. `minify.format.comments: false`: false
In the future, you can directly use [`preserve_annotations`](https://github.com/swc-project/swc/blob/e6fc5327b1a309eae840fe1ec3a2367adab37430/crates/swc/src/config/mod.rs#L808) here.
=> fix: sync minify file comments from SWC

crates/rspack_plugin_runtime/src/runtime_module/get_chunk_filename.rs, packages/rspack-test-tools/tests/configCases/output/chunk-filename-win32/a.js, packages/rspack-test-tools/tests/configCases/output/chunk-filename-win32/b.js, packages/rspack-test-tools/tests/configCases/output/chunk-filename-win32/index.js, packages/rspack-test-tools/tests/configCases/output/chunk-filename-win32/rspack.config.js
fix https://github.com/web-infra-dev/rspack/issues/8601
=> fix: generate wrong chunk filename runtime code on win32

crates/rspack_plugin_split_chunks/src/plugin/chunk.rs, crates/rspack_plugin_split_chunks/src/plugin/max_size.rs, packages/rspack-test-tools/tests/configCases/split-chunks/external-modules/external.js, packages/rspack-test-tools/tests/configCases/split-chunks/external-modules/index.js, packages/rspack-test-tools/tests/configCases/split-chunks/external-modules/rspack.config.js
fix: external module move out initial chunk
=> fix: external module move out initial chunk

crates/node_binding/binding.d.ts, crates/node_binding/src/lib.rs, crates/node_binding/src/plugins/interceptor.rs, crates/rspack_binding_options/src/options/raw_builtins/raw_banner.rs, crates/rspack_binding_options/src/options/raw_split_chunks/raw_split_chunk_chunks.rs, crates/rspack_binding_options/src/options/raw_split_chunks/raw_split_chunk_name.rs, crates/rspack_binding_values/src/chunk.rs, crates/rspack_binding_values/src/chunk_graph.rs, crates/rspack_binding_values/src/chunk_group.rs, crates/rspack_binding_values/src/compilation/mod.rs, crates/rspack_binding_values/src/module.rs, crates/rspack_binding_values/src/module_graph.rs, crates/rspack_binding_values/src/runtime.rs, packages/rspack-test-tools/tests/configCases/chunk-graph/get-module-chunks/index.js, packages/rspack-test-tools/tests/configCases/chunk-graph/get-module-chunks/rspack.config.js, packages/rspack/etc/core.api.md, packages/rspack/src/Chunk.ts, packages/rspack/src/ChunkGraph.ts, packages/rspack/src/ChunkGroup.ts, packages/rspack/src/Compilation.ts, packages/rspack/src/Compiler.ts, packages/rspack/src/Entrypoint.ts, packages/rspack/src/builtin-plugin/SplitChunksPlugin.ts
Refactor chunk graph binding API and support `chunkGraph.getModuleChunksIterable()`
=> refactor: chunk graph binding API

crates/node_binding/binding.d.ts, crates/node_binding/src/lib.rs, crates/rspack_core/src/compiler/mod.rs, packages/rspack/src/Compiler.ts
This PR will make `compiler_path` accessible to the Rust Compiler, and this field is useful in persistent cache.
=> feat: pass compiler_path to rust Compiler

Cargo.lock, crates/node_binding/binding.d.ts, crates/rspack_fs/Cargo.toml, crates/rspack_fs/src/memory_fs.rs, crates/rspack_fs/src/native_fs.rs, crates/rspack_fs/src/read.rs, crates/rspack_fs/src/write.rs, crates/rspack_fs_node/Cargo.toml, crates/rspack_fs_node/src/node.rs, crates/rspack_fs_node/src/write.rs, packages/rspack/src/FileSystem.ts
cherry pick refactor changes in #8643
- refactor: Unify the return values of `ThreadsafeNodeFS` methods into promises to simplify the code
- refactor: change `fn <'a>() -> BoxFuture<'a, Result<()>>;` to `async fn() -> Result<()>`
- refactor: remove unnecessary async blocks
- refactor(rspack_fs_node): create map_error_to_fs_error util to replace duplicate closures
- refactor(rspack_fs_node): create new_fs_error to simplify code
- fix: `NodeFileStats` lacks the `is_symlink` field
=> refactor: simplify file system code

Cargo.lock, crates/rspack_fs/src/memory_fs.rs, crates/rspack_fs/src/native_fs.rs, crates/rspack_storage/src/pack/data/meta.rs, crates/rspack_storage/src/pack/data/mod.rs, crates/rspack_storage/src/pack/data/options.rs, crates/rspack_storage/src/pack/data/scope.rs, crates/rspack_storage/src/pack/manager/mod.rs, crates/rspack_storage/src/pack/mod.rs, crates/rspack_storage/src/pack/strategy/mod.rs, crates/rspack_storage/src/pack/strategy/split/handle_file.rs, crates/rspack_storage/src/pack/strategy/split/mod.rs, crates/rspack_storage/src/pack/strategy/split/read_scope.rs, crates/rspack_storage/src/pack/strategy/split/util.rs, crates/rspack_storage/src/pack/strategy/split/validate_scope.rs, crates/rspack_storage/src/pack/strategy/split/write_pack.rs, crates/rspack_storage/src/pack/strategy/split/write_scope.rs, crates/rspack_storage/tests/build.rs, crates/rspack_storage/tests/dev.rs, crates/rspack_storage/tests/error.rs
- Add `version` to storage path.
- Validate expiration for the whole storage, not only one scope.
- Clean expired versions and unused scopes.
---
> Generate by copilot
This pull request introduces several changes to improve the functionality and structure of the `rspack_storage` module. The main changes include the addition of `RootMeta` and `RootOptions` structures, updates to the `ScopeManager` to handle root metadata, and various modifications to ensure proper functionality and testing.
* Added `RootMeta` and `RootOptions` structures to manage root metadata and configuration. (`crates/rspack_storage/src/pack/data/meta.rs`, `crates/rspack_storage/src/pack/data/options.rs`, `crates/rspack_storage/src/pack/manager/mod.rs`) [[1]](diffhunk://#diff-2a74a786f96b99d0dea97760c878ab13e0bb3e6f9fe0 …
=> feat: improve cache storage

website/components/PluginSupportStatusTable.tsx
Currently the plugin support table claims full support for `JavascriptModulesPlugin`, but that's not correct.  The static `getCompilationHooks` method only returns the `chunkHash` hook, but there are quite a few more.
For example, my plugin [`transform-async-modules-webpack-plugin`](https://github.com/steverep/transform-async-modules-webpack-plugin) cannot be `rspack` compatible because it uses the `renderModuleContent` tap.  Here's the full list of hooks:
https://github.com/webpack/webpack/blob/8a04c64e5e8e1b7ed1fd4b942a3d277296f14ef9/lib/javascript/JavascriptModulesPlugin.js#L175-L190
=> docs: clarify support for JavaScriptModulesPlugin as partial

.cargo/config.toml, Cargo.lock, crates/node_binding/binding.d.ts, crates/node_binding/src/lib.rs, crates/rspack_tracing/Cargo.toml, crates/rspack_tracing/src/lib.rs, justfile, packages/rspack-cli/src/utils/profile.ts
Remove `tokio-console` to reduce Rspack binary size (about 2MB).
- background: https://github.com/web-infra-dev/rspack/pull/7945#issuecomment-2490192579
- revert https://github.com/web-infra-dev/rspack/pull/7945
- revert https://github.com/web-infra-dev/rspack/pull/7982
=> perf: remove tokio-console to reduce binary size

website/docs/en/guide/optimization/analysis.mdx
Even for the English locale, the link points to the Chinese documentation. This fixes the link back.
=> docs: fix link for bundle size link in English locale

website/docs/en/config/resolve.mdx, website/docs/zh/config/resolve.mdx
Improve clarity and consistency in the `resolve.mainFields` configuration.
The changes include better formatting and additional examples to help users understand the options more easily.
=> docs: improve `resolve.mainFields`

website/docs/en/guide/tech/react.mdx, website/docs/zh/guide/tech/react.mdx
Provide additional instructions for using the React Compiler with React versions prior to 19 by installing the `react-compiler-runtime` package and specifying the `target` in the configuration.
- https://github.com/web-infra-dev/rsbuild/discussions/4197
- https://github.com/web-infra-dev/rsbuild/pull/4198
=> docs: React Compiler for React 17 and 18

Cargo.lock, crates/rspack_core/Cargo.toml, crates/rspack_core/src/dependency/dependency_location.rs, crates/rspack_plugin_javascript/src/dependency/commonjs/common_js_full_require_dependency.rs, crates/rspack_plugin_javascript/src/dependency/commonjs/common_js_require_dependency.rs, crates/rspack_plugin_javascript/src/dependency/commonjs/require_header_dependency.rs, crates/rspack_plugin_javascript/src/dependency/commonjs/require_resolve_header_dependency.rs, crates/rspack_plugin_javascript/src/dependency/esm/esm_export_expression_dependency.rs, crates/rspack_plugin_javascript/src/dependency/esm/esm_export_header_dependency.rs, crates/rspack_plugin_javascript/src/dependency/esm/esm_export_imported_specifier_dependency.rs, crates/rspack_plugin_javascript/src/dependency/esm/esm_export_specifier_dependency.rs, crates/rspack_plugin_javascript/src/dependency/esm/esm_import_dependency.rs, crates/rspack_plugin_javascript/src/dependency/esm/esm_import_specifier_dependency.rs, crates/rspack_plugin_javascript/src/dependency/esm/provide_dependency.rs, crates/rspack_plugin_javascript/src/dependency/hmr/esm_accept_dependency.rs, crates/rspack_plugin_javascript/src/dependency/module_argument_dependency.rs, crates/rspack_plugin_javascript/src/parser_and_generator/mod.rs, crates/rspack_plugin_javascript/src/parser_plugin/amd_require_dependencies_block_parser_plugin.rs, crates/rspack_plugin_javascript/src/parser_plugin/import_parser_plugin.rs, crates/rspack_plugin_javascript/src/parser_plugin/require_ensure_dependencies_block_parse_plugin.rs, crates/rspack_plugin_javascript/src/parser_plugin/worker_plugin.rs
I have unified this logic into `dependency_location.rs`.
https://github.com/web-infra-dev/rspack/blob/8646ecf26004a5c99ff09cab2b49e457d5d9ca09/crates/rspack_plugin_javascript/src/parser_and_generator/mod.rs#L379-L380
=> refactor: unify the logic of `span_to_location` into trait `SourcePosition`

.github/renovate.json5
Renovate does not update indirect transitive dependencies without this option.
- renovatebot/renovate#15762
=> chore(renovate): Enable lockFileMaintenance

Cargo.toml
Reverts web-infra-dev/rspack#6931
Fixing https://github.com/renovatebot/renovate/discussions/32898
=> revert: Revert "chore: sanitize file paths"

crates/rspack_storage/src/pack/data/meta.rs, crates/rspack_storage/src/pack/data/mod.rs, crates/rspack_storage/src/pack/fs/mod.rs, crates/rspack_storage/src/pack/manager/mod.rs, crates/rspack_storage/src/pack/strategy/mod.rs, crates/rspack_storage/src/pack/strategy/split/handle_file.rs, crates/rspack_storage/src/pack/strategy/split/mod.rs, crates/rspack_storage/src/pack/strategy/split/write_scope.rs, crates/rspack_storage/tests/build.rs, crates/rspack_storage/tests/dev.rs, crates/rspack_storage/tests/error.rs, crates/rspack_storage/tests/expire.rs, crates/rspack_storage/tests/lock.rs
Add a `move.lock` file to make sure that a batch of move operations can be atomic
---
> Generate by copilot
This pull request includes several changes to the `rspack_storage` crate that enhance the handling of file operations, scope management, and root metadata. The most important changes include the introduction of a new `RootMetaFrom` enum, improved error handling, and the addition of new methods for managing file operations.
Improvements to root metadata and scope management:
* [`crates/rspack_storage/src/pack/data/meta.rs`](diffhunk://#diff-2a74a786f96b99d0dea97760c878ab13e0bb3e6f9fe022e4d65537e47c046e6bR16-R35): Introduced the `RootMetaFrom` enum and modified the `RootMeta` struct to include an `expire_time` field and a `from` field of type `RootMetaFrom`. Updated the `new` method …
=> feat: cache storage move lock file

crates/rspack_binding_options/src/options/raw_experiments/raw_cache/mod.rs, crates/rspack_core/src/cache/persistent/mod.rs, crates/rspack_core/src/cache/persistent/version.rs, packages/rspack/etc/core.api.md, packages/rspack/src/config/normalization.ts, packages/rspack/src/config/types.ts, packages/rspack/src/config/zod.ts
1. make `experiments.cache.storage` optional
2. move `experiments.cache.buildBependencies` normalization to js side
=> feat: update experiments.cache signature

crates/rspack_core/src/compiler/mod.rs, packages/rspack-test-tools/tests/configCases/hooks/rspack-issue-8676/index.css, packages/rspack-test-tools/tests/configCases/hooks/rspack-issue-8676/index.js, packages/rspack-test-tools/tests/configCases/hooks/rspack-issue-8676/rspack.config.js
fix #8676
The filename passed in here should include the query, as the content will be retrieved using `getAsset(filename)` on the JavaScript side.
https://github.com/web-infra-dev/rspack/blob/2e65ed6a9c779be9f796dfdc8b693c767e24f355/crates/rspack_core/src/compiler/mod.rs#L412-L417
https://github.com/web-infra-dev/rspack/blob/2e65ed6a9c779be9f796dfdc8b693c767e24f355/packages/rspack/src/Compiler.ts#L925-L935
=> fix: the wrong filename was passed when calling the assetEmitted hook

crates/rspack_core/src/concatenated_module.rs, crates/rspack_core/src/exports_info.rs, crates/rspack_plugin_javascript/src/plugin/side_effects_flag_plugin.rs, packages/rspack-test-tools/tests/configCases/concatenate-modules/consume-shared/index.js, packages/rspack-test-tools/tests/configCases/concatenate-modules/consume-shared/lib/a.js, packages/rspack-test-tools/tests/configCases/concatenate-modules/consume-shared/lib/b.js, packages/rspack-test-tools/tests/configCases/concatenate-modules/consume-shared/lib/c.js, packages/rspack-test-tools/tests/configCases/concatenate-modules/consume-shared/rspack.config.js, packages/rspack-test-tools/tests/configCases/concatenate-modules/dynamic-cjs/index.js, packages/rspack-test-tools/tests/configCases/concatenate-modules/dynamic-cjs/lib/a.js, packages/rspack-test-tools/tests/configCases/concatenate-modules/dynamic-cjs/lib/b.js, packages/rspack-test-tools/tests/configCases/concatenate-modules/dynamic-cjs/lib/c.js, packages/rspack-test-tools/tests/configCases/concatenate-modules/dynamic-cjs/rspack.config.js
`get_export_info` needs mutable module graph for dynamic export info, but we use immutable module graph in codegen phase for some reasons, we can't easily change it to mutable, so introduce `get_export_info_without_mut_module_graph` for these cases.
=> fix: module concatenation for dynamic export info

crates/rspack_storage/src/pack/manager/mod.rs, crates/rspack_storage/src/pack/strategy/mod.rs, crates/rspack_storage/src/pack/strategy/split/handle_file.rs, crates/rspack_storage/src/pack/strategy/split/mod.rs, crates/rspack_storage/src/pack/strategy/split/util.rs, crates/rspack_storage/src/pack/strategy/split/validate_scope.rs, crates/rspack_storage/src/pack/strategy/split/write_scope.rs, crates/rspack_storage/tests/multi.rs
1. should not generate move.lock for every scope
2. add lock for removing
3. add test case for multiple scopes
---
> generate by copilot
This pull request refactors the scope management and file handling logic in the `rspack_storage` crate. The changes aim to simplify the code, improve efficiency, and ensure better error handling. The key changes include modifying the scope writing strategy, adding new utility functions, and updating test cases accordingly.
* [`crates/rspack_storage/src/pack/manager/mod.rs`](diffhunk://#diff-7ee17253ffd9ac23b524cf783f06f220bbd76c2a661480c10b5ded7c24102dc4L233-R235): Refactored the `save_scopes` function to streamline the process by merging the `before_all` and `after_all` steps and introducing the `merge_changed` method. …
=> fix: duplicate move lock files

packages/rspack-test-tools/tests/compilerCases/compare-before-emit-disable.js
fix nightly release compare-before-emit-disable test failed.
https://github.com/web-infra-dev/rspack/actions/runs/12343546612/job/34445632494
=> fix: fix nightly release compare-before-emit-disable test failed

crates/node_binding/binding.d.ts, crates/rspack_binding_options/src/options/raw_module/mod.rs, crates/rspack_core/src/options/module.rs, crates/rspack_plugin_asset/src/lib.rs, packages/rspack/etc/core.api.md, packages/rspack/src/config/adapter.ts, packages/rspack/src/config/types.ts, tests/webpack-test/configCases/asset-modules/rule-generator-outputPath/test.filter.js, website/docs/en/config/module.mdx, website/docs/zh/config/module.mdx
close #8539
`module.generator.outputPath` is used to specify the output folder for generated assets. While `filename` can achieve a similar result, it also modifies the associated URL. For example:
```js
generator: {
// put emitted files under `assets/*.png`
// runtime request from `https://xxx/cdn/assets/*.png`
filename: 'assets/[hash][ext][query]',
publicPath: 'https://xxx/cdn/'
}
generator: {
// put emitted files under `assets/*.png`
// runtime request from `https://xxx/cdn/*.png`
filename: '[hash][ext][query]',
outputPath: 'assets'
publicPath: 'https://xxx/cdn/'
}
```
=> feat: support module.generator.outputPath

.github/renovate.json5
The latest version of inventory is not compatible with persistent cache. cc @jerrykingxyz @LingyuCoder
=> chore(deps): stop updating inventory with renovate ci

.github/workflows/reusable-build.yml
linux-musl will build failed when release nightly.
https://github.com/web-infra-dev/rspack/actions/runs/12343546612/job/34444800048
This bug is caused by enable static linking for clang-sys, which swc depends on.
https://github.com/wasmerio/wasmer/blob/main/lib/api/Cargo.toml#L172
Install `llvm19-dev` and `clang19-static` will provide the environment to static build.
=> ci: linux-musl build failed

.github/workflows/reusable-build.yml
Fix the CI when only changed some docs, such as:
https://github.com/web-infra-dev/rspack/actions/runs/12374467008/job/34537086579?pr=8745
Ref: https://github.com/web-infra-dev/rspack/pull/8722
=> ci: should skip trim paths for doc changes

Cargo.lock, crates/rspack_core/src/cache/mod.rs, crates/rspack_core/src/cache/persistent/mod.rs, crates/rspack_core/src/cache/persistent/version.rs, crates/rspack_macros/Cargo.toml, crates/rspack_macros/src/lib.rs, crates/rspack_macros/src/rspack_version.rs
1. Add `rspack_version!()` macro to get rspack current version
2. Persistent cache version calculation depends on rspack version
=> feat: add macro to get rspack version

crates/rspack_core/src/cache/disable.rs, crates/rspack_core/src/cache/mod.rs, crates/rspack_core/src/cache/persistent/mod.rs, crates/rspack_core/src/cache/persistent/occasion/make/dependencies.rs, crates/rspack_core/src/cache/persistent/occasion/make/meta.rs, crates/rspack_core/src/cache/persistent/occasion/make/mod.rs, crates/rspack_core/src/cache/persistent/occasion/make/module_graph.rs, crates/rspack_core/src/cache/persistent/snapshot/mod.rs, crates/rspack_core/src/cache/persistent/snapshot/strategy.rs, crates/rspack_core/src/cache/persistent/version.rs, crates/rspack_core/src/compiler/hmr.rs, crates/rspack_core/src/compiler/mod.rs
Upgrade `Cache` trait methods allow them to return `Result`, and compiler will add returned errors to `compilation.diagnostic`.
Note: SerializeError and DeserializeError are considered unexpected errors and panic directly.
=> feat: persistent cache expose error to compilation.diagnostic

.github/workflows/ci.yml, .github/workflows/get-runner-labels.yml, .github/workflows/reusable-build.yml
`ubuntu-latest` is rolling out with ubuntu-24. Some glibc versions are no longer supported in the latest version.
Downgrade `ubuntu-latest` to `ubuntu-22.04` to make it compatible with playwright docker `jammy`. I didn't choose
to upgrade playwright docker as it makes us dropping the support for older glibc versions. This is not acceptable.
Ref: https://github.com/actions/runner-images/issues/10636
Failing CI: https://github.com/web-infra-dev/rspack/actions/runs/12408927487/job/3464188805
This is also related to this PR switching us from self-hosted runner to GitHub runner: https://github.com/web-infra-dev/rspack/pull/7243
=> ci: use ubuntu-22.04

crates/rspack_core/src/cache/persistent/mod.rs
1. Persistent cache waits for storage saves to complete in production mode and exposes errors to compile diagnostics.
2. Persistent cache in development mode does not wait for save to complete, only prints storage errors when it ends.
=> feat: persistent cache in production mode wait for save to complete

crates/rspack_plugin_split_chunks/src/common.rs, crates/rspack_plugin_split_chunks/src/plugin/max_size.rs, packages/rspack-test-tools/tests/configCases/split-chunks/max-size-split/rspack.config.js, packages/rspack-test-tools/tests/configCases/split-chunks/max-size-split/src/aaa/50k-1.js, packages/rspack-test-tools/tests/configCases/split-chunks/max-size-split/src/aaa/50k-2.js, packages/rspack-test-tools/tests/configCases/split-chunks/max-size-split/src/aaa/50k-3.js, packages/rspack-test-tools/tests/configCases/split-chunks/max-size-split/src/aaa/50k-4.js, packages/rspack-test-tools/tests/configCases/split-chunks/max-size-split/src/bbb/50k-1.js, packages/rspack-test-tools/tests/configCases/split-chunks/max-size-split/src/bbb/50k-2.js, packages/rspack-test-tools/tests/configCases/split-chunks/max-size-split/src/bbb/50k-3.js, packages/rspack-test-tools/tests/configCases/split-chunks/max-size-split/src/bbb/50k-4.js, packages/rspack-test-tools/tests/configCases/split-chunks/max-size-split/src/ccc/50k-1.js, packages/rspack-test-tools/tests/configCases/split-chunks/max-size-split/src/ccc/50k-2.js, packages/rspack-test-tools/tests/configCases/split-chunks/max-size-split/src/ccc/50k-3.js, packages/rspack-test-tools/tests/configCases/split-chunks/max-size-split/src/ccc/50k-4.js, packages/rspack-test-tools/tests/configCases/split-chunks/max-size-split/src/index.js, packages/rspack-test-tools/tests/configCases/split-chunks/max-size-split/test.config.js
Webpack has an heuristic algorithm that splits big chunks into small ones based on their path similarities. For example, if user's project structure is like:
```
src
|-aaa
|   index_1.js
|   index_2.js
|   index_3.js
|-bbb
|   index_1.js
|   index_2.js
|   index_3.js
```
let's say there is one chunk that contains all modules in /aaa and /bbb folders, and it's too big, we set maxSize to split it into smaller pieces, webpack will split them based on path similarities, I assume it's based on one assumption: users modify files that are closed to each other, for example you usually make some changes in some specific sub folders, and don't affect other folders, so other chunks should not change.
we can split them by their paths like, 'aaa.js' and `bbb.js`, or `aaa_1.js` `aaa_2.js` `bbb_1.js` …
=> feat: split big chunks based on modules path similarities

packages/rspack/etc/core.api.md, packages/rspack/src/config/adapterRuleUse.ts, packages/rspack/src/loader-runner/index.ts
Align the `loaderContext.importModule()` type definition with webpack and add generics to specify the type of export.
Ref: https://github.com/webpack/webpack/blob/964c0315df0ee86a2b4edfdf621afa19db140d4f/declarations/LoaderContext.d.ts#L90-L95
=> fix: correct type for `loaderContext.importModule`

.github/workflows/ci.yml
Because self-hosted runners are offline, the rspack team does not have enough runners. So disable the pkg preview action temporarily.
=> ci: disable pkg preview

.github/workflows/ci.yml
Because self-hosted runners are offline, the rspack team does not have enough runners. So disable the miri action temporarily.
=> ci: disable miri, eco-ci and benchmark check

Cargo.lock, crates/rspack_plugin_javascript/Cargo.toml
Related to https://github.com/shulaoda/fast-glob/pull/6
@SyMind further optimized the brace expansion match functionality, achieving a performance improvement of nearly `35%` on my local machine and approximately `49%` on `CodSpeed`.
=> chore(deps): bump `fast-glob` to v0.4.1

crates/node_binding/binding.d.ts, crates/rspack_binding_values/src/raw_options/raw_split_chunks/mod.rs, packages/rspack-test-tools/tests/configCases/split-chunks/custom-filename-function/a.js, packages/rspack-test-tools/tests/configCases/split-chunks/custom-filename-function/b.js, packages/rspack-test-tools/tests/configCases/split-chunks/custom-filename-function/rspack.config.js, packages/rspack-test-tools/tests/configCases/split-chunks/custom-filename-function/test.config.js, packages/rspack/etc/core.api.md, packages/rspack/src/config/types.ts, packages/rspack/src/config/zod.ts, website/docs/en/plugins/webpack/split-chunks-plugin.mdx, website/docs/zh/plugins/webpack/split-chunks-plugin.mdx
support function type filename for splitChunks
=> feat: splitChunks.cacheGroups.filename supports function

crates/node_binding/binding.d.ts, crates/rspack_binding_values/src/raw_options/raw_experiments/mod.rs, crates/rspack_binding_values/src/raw_options/raw_experiments/raw_cache/mod.rs
Allow empty persistent cache options.
=> fix: allow empty persistent cache options

crates/node_binding/scripts/build.js
Previously, I disabled dts cache to keep dts generation stable. However, this might has impact on cases where some crate is built incrementally so that the binding of these crates are failed to generate.
=> build: remove no-dts-cache

website/docs/en/api/loader-api/context.mdx, website/docs/zh/api/loader-api/context.mdx
Add `loaderContext.importModule()` documentation. Rspack has implemented it, but lacks API documentation.
=> docs: add `loaderContext.importModule()`

crates/node_binding/binding.d.ts, crates/rspack_binding_values/src/raw_options/raw_module/mod.rs, crates/rspack_core/src/options/module.rs, crates/rspack_plugin_json/src/json_exports_dependency.rs, crates/rspack_plugin_json/src/lib.rs, packages/rspack-test-tools/tests/__snapshots__/Defaults.test.js.snap, packages/rspack-test-tools/tests/defaultsCases/cache/cache-filesystem-dev.js, packages/rspack-test-tools/tests/defaultsCases/mode/development.js, packages/rspack/etc/core.api.md, packages/rspack/src/config/adapter.ts, packages/rspack/src/config/defaults.ts, packages/rspack/src/config/types.ts, tests/webpack-test/configCases/json/bailout-flag-dep-export-perf/data.json, tests/webpack-test/configCases/json/bailout-flag-dep-export-perf/index.js, tests/webpack-test/configCases/json/bailout-flag-dep-export-perf/webpack.config.js, tests/webpack-test/configCases/json/flag-dep-export-perf/data.json, tests/webpack-test/configCases/json/flag-dep-export-perf/index.js, tests/webpack-test/configCases/json/flag-dep-export-perf/webpack.config.js
Aligned with https://github.com/webpack/webpack/pull/19058.
I will update doc later.
=> perf: improve FlagDependencyExportsPlugin for large JSON by depth

crates/rspack_binding_values/src/raw_options/raw_module/mod.rs, crates/rspack_core/src/options/module.rs, crates/rspack_core/src/utils/module_rules.rs, packages/rspack-test-tools/tests/configCases/loader/match-when-empty/a.js, packages/rspack-test-tools/tests/configCases/loader/match-when-empty/index.js, packages/rspack-test-tools/tests/configCases/loader/match-when-empty/loader.js, packages/rspack-test-tools/tests/configCases/loader/match-when-empty/rspack.config.js
Closes https://github.com/web-infra-dev/rspack/issues/8267
Align with webpack https://github.com/webpack/webpack/blob/main/lib/rules/RuleSetCompiler.js#L237
Considering the `match_when_empty` is only calculated once and `TryFrom` can't be async, I use `RwLock` for cache. It's better to run benchmarks to see if there's performance regression.
=> feat: support `match_when_empty` for rule condition 

crates/rspack_core/src/build_chunk_graph/code_splitter.rs, crates/rspack_core/src/chunk_graph/chunk_graph_module.rs, crates/rspack_core/src/module_graph/mod.rs, crates/rspack_plugin_javascript/src/dependency/esm/esm_import_dependency.rs, crates/rspack_plugin_javascript/src/plugin/mod.rs, packages/rspack-test-tools/tests/statsAPICases/cache-enabled.js, packages/rspack-test-tools/tests/watchCases/side-effects/two-to-one/0/foo.js, packages/rspack-test-tools/tests/watchCases/side-effects/two-to-one/0/index.js, packages/rspack-test-tools/tests/watchCases/side-effects/two-to-one/0/module.js, packages/rspack-test-tools/tests/watchCases/side-effects/two-to-one/0/package.json, packages/rspack-test-tools/tests/watchCases/side-effects/two-to-one/0/reexports-deep.js, packages/rspack-test-tools/tests/watchCases/side-effects/two-to-one/0/reexports.js, packages/rspack-test-tools/tests/watchCases/side-effects/two-to-one/1/module.js, packages/rspack-test-tools/tests/watchCases/side-effects/two-to-one/rspack.config.js
Use ChunkGraph module hash to verify the `rename_module_cache`, `build_info().hash` represents the module's `originalSource`, but it's possible to generate different result with the same `originalSource` (checkout added test).
=> fix: use cgm hash to verify rename inline modules cache

crates/rspack_plugin_css/src/parser_and_generator/mod.rs, packages/rspack-test-tools/tests/builtinCases/plugin-css/simple-url/__snapshots__/output.snap.txt, packages/rspack-test-tools/tests/builtinCases/plugin-css/simple-url/index.js, packages/rspack-test-tools/tests/builtinCases/plugin-css/simple-url/style.css
fix [issue 8788](https://github.com/web-infra-dev/rspack/issues/8788)
=> fix: Rspack cssParser will parse failed when url(' ')

.github/workflows/release-canary.yml, scripts/release/version.mjs
use separate token and scope for canary release for security reason
=> chore: split canary to separate scope

website/docs/en/errors/swc-plugin-version.mdx, website/docs/en/guide/features/builtin-swc-loader.mdx, website/docs/zh/errors/swc-plugin-version.mdx, website/docs/zh/guide/features/builtin-swc-loader.mdx
Rspack's FAQ documentation is similar to React errors documentation or Next.js FAQ documentation, for example:
- https://react.dev/errors/421
- https://nextjs.org/docs/messages/react-hydration-error
Which means:
- The URL of the FAQ document is fixed and will not change.
- The URL of the FAQ document can be included in the Rspack core error logs
This PR adds https://rspack.dev/errors/swc-plugin-version for SWC Wasm plugins.
=> docs: add FAQ for SWC plugin version unmatched

crates/rspack_plugin_copy/src/lib.rs, tests/plugin-test/copy-plugin/CopyPlugin.test.js
**Attention: This PR includes a breaking change, but it is necessary to align with webpack's behavior.**
fix #8801 
A glob pattern ending with /** should match all files within a directory, not just the directory itself.
Since the standard glob only matches directories (refer to https://github.com/rust-lang/glob/issues/129), we append /* to align with webpack's behavior.
=> fix!: handle glob patterns ending with /** in CopyRspackPlugin

crates/node_binding/binding.d.ts, crates/rspack_binding_values/src/raw_options/raw_external.rs, crates/rspack_core/src/options/externals.rs, crates/rspack_plugin_externals/src/plugin.rs, packages/rspack-test-tools/tests/configCases/externals/context-info/index.js, packages/rspack-test-tools/tests/configCases/externals/context-info/other-layer.js, packages/rspack-test-tools/tests/configCases/externals/context-info/rspack.config.js, packages/rspack/etc/core.api.md, packages/rspack/src/Module.ts, packages/rspack/src/builtin-plugin/ExternalsPlugin.ts
Add context info issuer layer for external function
=> feat: add context info issuer layer for external function

crates/rspack_core/src/external_module.rs, packages/rspack-test-tools/tests/__snapshots__/Config.test.js.snap, packages/rspack-test-tools/tests/configCases/externals/rslib-issue-580/_a/foo.mjs, packages/rspack-test-tools/tests/configCases/externals/rslib-issue-580/a/foo.mjs, packages/rspack-test-tools/tests/configCases/externals/rslib-issue-580/index.js, packages/rspack-test-tools/tests/configCases/externals/rslib-issue-580/rspack.config.js, packages/rspack-test-tools/tests/configCases/externals/rslib-issue-580/test.config.js, packages/rspack-test-tools/tests/configCases/library/modern-module-dynamic-import-runtime/index.js, packages/rspack-test-tools/tests/configCases/library/modern-module-export-char/rspack.config.js
Fix https://github.com/web-infra-dev/rslib/issues/580, port https://github.com/webpack/webpack/blob/7701ae43203e9d93d661c9a663c41fccd8e242aa/lib/ExternalModule.js#L239-L244 of webpack.
=> fix(exernals): add hash to distinguish conflict id

packages/rspack-test-tools/src/helper/expect/placeholder.ts
In #8161, the snapshot is serialized by `path-serializer`. But it cannot serialize paths correctly when using `@rspack/test-tools` in an external project:
```diff
- fileName: "<PROJECT_ROOT>/path/to/index.js",
+ fileName: "<HOME>/project/path/to/index.js",
```
In this patch, we use `process.cwd()` when `@rspack/test-tools` is in `node_modules`, which would work as expected.
```diff
- fileName: "<PROJECT_ROOT>/path/to/index.js",
+ fileName: "<ROOT>/path/to/index.js",
```
=> fix(rspack-test-tools): use `process.cwd()` when outside Rspack

crates/rspack_core/src/artifacts/side_effects_do_optimize_artifact.rs, crates/rspack_plugin_javascript/src/plugin/side_effects_flag_plugin.rs, packages/rspack-test-tools/tests/statsAPICases/verbose-time.js, website/docs/en/config/experiments.mdx, website/docs/zh/config/experiments.mdx
follow up https://github.com/web-infra-dev/rspack/pull/8799
=> perf(incremental): better parallel for side effects plugin rebuild

packages/rspack-cli/package.json, packages/rspack-cli/src/cli.ts, pnpm-lock.yaml
Since Rspack already uses the `engines` filed to limit the minimal Node.js version, it seems unnecessary to run `semver` to check the Node.js version at runtime.
Removing the `semver()` calls can make Rspack CLI 30~40ms faster in all cases.
=> perf(cli): remove Node.js semver checker

packages/rspack-cli/src/utils/loadConfig.ts
`rechoir` and `interpret` are only used when loading `rspack.config.ts` or `rspack.config.mts`.
Lazy importing them can make Rspack CLI 20ms faster in most cases.
=> perf(cli): lazy import rechoir and interpret

packages/rspack-test-tools/etc/test-tools.api.md, packages/rspack-test-tools/src/case/cache.ts, packages/rspack-test-tools/src/case/index.ts, packages/rspack-test-tools/src/helper/loaders/hot-update.ts, packages/rspack-test-tools/src/helper/plugins/hot-update.ts, packages/rspack-test-tools/src/helper/plugins/index.ts, packages/rspack-test-tools/src/processor/cache.ts, packages/rspack-test-tools/src/processor/index.ts, packages/rspack-test-tools/src/runner/cache.ts, packages/rspack-test-tools/src/runner/index.ts, packages/rspack-test-tools/tests/Cache.test.js, packages/rspack-test-tools/tests/cacheCases/snapshot/basic/file.js, packages/rspack-test-tools/tests/cacheCases/snapshot/basic/index.js, packages/rspack-test-tools/tests/cacheCases/snapshot/basic/rspack.config.js
This PR will add `cacheCases` to test persistent cache, and it contains some new built-in test methods and variables:
* `NEXT_HMR` will run with hmr update, and it works same as `NEXT(require("../../update.js")(done))` in hot cases.
* `NEXT_START` will generate a new compiler to rebuild, and rerun the assets code.
* `COMPILER_INDEX` is used to distinguish different compilers.
see the `basic` test case for more info.
=> test: add cache test cases

packages/create-rspack/package.json, packages/create-rspack/rslib.config.ts, packages/rspack-cli/package.json, packages/rspack-cli/rslib.config.ts, packages/rspack-cli/src/utils/crossImport.ts, packages/rspack-cli/src/utils/loadConfig.ts, packages/rspack-cli/src/utils/profile.ts, pnpm-lock.yaml
Bump Rslib from v0.0.15 to v0.2.2:
- Remove `target: 'node'` as it's the default value now.
- Remove `dynamicImport` helper, no longer needed.
- Details: https://github.com/web-infra-dev/rslib/releases
=> chore(deps): bump Rslib to v0.2.2

crates/rspack_core/src/options/compiler_options_builder.rs, crates/rspack_core/src/options/entry.rs, crates/rspack_core/src/options/experiments/cache.rs, crates/rspack_core/src/options/filename.rs, crates/rspack_core/src/options/mod.rs, crates/rspack_core/src/options/module.rs, crates/rspack_core/src/options/optimizations.rs, crates/rspack_core/src/options/target.rs
This is the first PR of aligning rust options with JS. 
This feature is still under development. APIs added in this PR are still unusable.
Things are subject to change.
This PR includes:
- Initialize `CompilerOptionsBuilder` on rust side.
Should sync https://github.com/web-infra-dev/rspack/pull/8802/files#diff-55e0fbd74437dff4e251152f5d93efd7f5871cbad72a7959dddb6add8fbf60cc later.
=> feat: initialize compiler options builder

packages/rspack-test-tools/src/helper/util/refreshModifyTime.ts, packages/rspack-test-tools/src/processor/cache.ts, packages/rspack-test-tools/src/runner/cache.ts, packages/rspack-test-tools/tests/cacheCases/snapshot/basic/index.js
`NEXT_START` in cache case will generate a new compiler to rebuild, we should refresh the modified file mtime to test the snapshot module in persistent cache
=> test: refresh modified file mtime when run NEXT_START

website/docs/en/api/loader-api/context.mdx, website/docs/zh/api/loader-api/context.mdx
This pull request primarily focus on adding type annotations, examples, and clarifications to the loader API documentation.
These changes enhance the readability and usability of the loader API documentation, providing developers with clearer guidance and practical examples.
=> docs: make LoaderContext documentation more friendly

crates/rspack_plugin_javascript/src/dependency/module_argument_dependency.rs, crates/rspack_plugin_javascript/src/parser_plugin/api_plugin.rs, crates/rspack_plugin_javascript/src/parser_plugin/hot_module_replacement_plugin.rs, packages/rspack-test-tools/etc/test-tools.api.md, packages/rspack-test-tools/src/processor/cache.ts, packages/rspack-test-tools/tests/Cache.test.js, packages/rspack-test-tools/tests/cacheCases/snapshot/basic/file.js, packages/rspack-test-tools/tests/cacheCases/snapshot/basic/index.js, packages/rspack-test-tools/tests/cacheCases/snapshot/basic/rspack.config.js
* cacheCase clean cache.storage.directory before first run
* save ModuleArgumentDependency.id to avoid wrong replacement of "module.hot.accept".
=> fix: persistent cache save ModuleArgumentDependency.id

crates/rspack_ids/src/named_module_ids_plugin.rs, packages/rspack-test-tools/tests/watchCases/module-ids/activate-inactive-module/0/a.js, packages/rspack-test-tools/tests/watchCases/module-ids/activate-inactive-module/0/index.js, packages/rspack-test-tools/tests/watchCases/module-ids/activate-inactive-module/1/index.js, packages/rspack-test-tools/tests/watchCases/module-ids/activate-inactive-module/2/index.js, packages/rspack-test-tools/tests/watchCases/module-ids/activate-inactive-module/rspack.config.js
Activate an inactive module in rebuild, the module don't have codeGenerationResult
=> fix(incremental): activate inactive module not codegen

crates/rspack_core/src/chunk_group.rs, crates/rspack_core/src/options/module.rs, crates/rspack_plugin_javascript/src/visitors/dependency/util.rs, packages/rspack-test-tools/tests/configCases/web/fetch-priority-2/index.js, tests/webpack-test/__snapshots__/StatsTestCases.basictest.js.snap
`webpackPreload` and `webpackPrefetch` magic comments can set preload and prefetch to script tag, the value of these comments determine the priority and the order of preloaded chunks. The value can also be negative, as it is only for ordering.
=> fix: should recognize negative preload value

crates/rspack_plugin_css/src/utils.rs, packages/rspack-test-tools/tests/__snapshots__/Config.test.js.snap, packages/rspack-test-tools/tests/builtinCases/plugin-css-modules/modules-composes/__snapshots__/output.snap.txt, packages/rspack-test-tools/tests/configCases/css/rspack-issue-6435-xxhash64/index.js, packages/rspack-test-tools/tests/configCases/css/rspack-issue-6435/index.js, packages/rspack-test-tools/tests/configCases/mangle-exports/skipping-mangle-css-modules/index.js, packages/rspack-test-tools/tests/treeShakingCases/css/__snapshots__/treeshaking.snap.txt, tests/webpack-test/__snapshots__/ConfigTestCases.basictest.js.snap
As detailed in #8735 Rspack is currently out of sync with a recent change in Webpack around how css module hashes that lead with a digit are handled. 
Current Rspack functionality removes all digits from the start of the hash so that hashed classnames never start with a digit, however this produces an edge case where when the hash is entirely digits it is reduced down to an empty string.
Webpack fixed this issue recently to instead prepend hashes starting with a digit with a underscore character ("_") - https://github.com/webpack/webpack/blob/964c0315df0ee86a2b4edfdf621afa19db140d4f/lib/dependencies/CssLocalIdentifierDependency.js#L81
This commit updates the regex/replace functionality to match Webpack's implementation.
=> fix: correct css modules hashing to match Webpack when leading digit #8735

package.json, packages/rspack/etc/core.api.md, packages/rspack/src/util/source.ts, pnpm-lock.yaml, tests/webpack-test/package.json, website/package.json
- Another little issue blocking #8805.
=> chore(deps): Upgrade @types/node 20.12.7 to 20.17.10

.github/workflows/release-canary.yml, package.json
sometimes we need to do profile for users which we don't have access permission, so release with debug info will help we collect more profile info about it
=> chore: add profile choice for release canary

crates/rspack_macros/src/rspack_version.rs
`rspack_version!()` macro support match alpha version like `1.2.0-alpha.0`
=> fix: rspack_version macro support match alpha version

Cargo.lock, crates/rspack_macros/Cargo.toml, crates/rspack_macros/src/rspack_version.rs
Use json crate to parse package.json to get version field in `rspack_version!()` macro.
=> fix: rspack_version macro use json to parse package.json

crates/rspack_plugin_progress/src/lib.rs
fix https://github.com/web-infra-dev/rspack/issues/8690
This pull request includes updates to the `ProgressPlugin` in the `crates/rspack_plugin_progress` library to improve the progress bar functionality. The most important changes involve the initialization and usage of the `MultiProgress` instance and the handling of progress bars.
Improvements to progress bar functionality:
* [`crates/rspack_plugin_progress/src/lib.rs`](diffhunk://#diff-74d45e75be91aa846fb37ea837a09fb96f501229aaa991892ccd11f12da006beL44-R45): Modified the `MULTI_PROGRESS` initialization to use `MultiProgress::with_draw_target` with a higher refresh rate for smoother updates.
* [`crates/rspack_plugin_progress/src/lib.rs`](diffhunk://#diff-74d45e75be91aa846fb37ea837a09fb96f501229aaa991892ccd11f12da006beL86-R87): Updated …
=> fix: add stdout draw target to multi progress

crates/rspack_plugin_devtool/src/source_map_dev_tool_plugin.rs, packages/rspack-test-tools/tests/configCases/plugins/source-map-dev-tool-plugin-file-context/index.js, packages/rspack-test-tools/tests/configCases/plugins/source-map-dev-tool-plugin-file-context/rspack.config.js
=> fix: source-map-devtool-plugin file context option

website/docs/en/config/experiments.mdx, website/docs/zh/config/experiments.mdx
In production mode, `root.cache` will automatically be set to false, which will make persistent caching ineffective and hard to spot. This PR will set cache to true in the example code to avoid this.
=> docs: persistent cache example set root.cache to true

.github/workflows/ecosystem-benchmark.yml
Running `ecosystem-benchmark` with a PR number will fail due to invalid references in action/checkout.
https://github.com//web-infra-dev/rspack/actions/runs/12547386222
=> ci: fix ecosystem-benchmark test pr failed

crates/rspack_plugin_javascript/src/parser_plugin/compatibility_plugin.rs, packages/rspack-test-tools/tests/configCases/parsing/nested-webpack-exports/index.js, packages/rspack-test-tools/tests/configCases/parsing/nested-webpack-exports/lib.js, packages/rspack-test-tools/tests/configCases/parsing/nested-webpack-exports/lib2.js, packages/rspack-test-tools/tests/configCases/parsing/nested-webpack-exports/rspack.config.js
fix: #8647
CompatiblePlugin parser hook relies on hookMap `for_name`, `for_name` is identifier name usually, but when the variable is tagged, `for_name` is the tagged name.
InnerGraph will tag all pure variables, and skip other plugins to continue handing the same identifier. InnerGraph treats `var __webpack_exports__ = {}` as pure declarator, it tags the variable `__webpack_exports__`, make CompatiblePlugin not able to transform it
=> fix: transform nested webpack require with innerGraph enabled

crates/rspack_storage/src/error.rs, crates/rspack_storage/src/fs/error.rs
just do not show too much nested error info
---
This pull request includes several changes to improve error handling and formatting in the `rspack_storage` crate. The most important changes include making the `ErrorReason` enum public, implementing the `Display` trait for `ErrorReason`, and modifying the `Display` implementation for `Error` and `BatchFSError` to enhance error message formatting.
Error handling and formatting improvements:
* [`crates/rspack_storage/src/error.rs`](diffhunk://#diff-30e3d1454b1f75b32cc703d5d35daa438d8e153413d48bcee123a2bd48c104a4L37-R69): Made the `ErrorReason` enum public and implemented the `Display` trait for it to provide better error message formatting.
* [`crates/rspack_storage/src/error.rs`](diffhunk://#diff-30e3d1454b1f75b32cc703d5d35daa438d8e153413d48 …
=> refactor: better storage error format

crates/rspack_binding_values/src/module_graph.rs, crates/rspack_core/src/module_graph/connection.rs, packages/rspack-test-tools/tests/configCases/module-graph/get-module/foo.js, packages/rspack-test-tools/tests/configCases/module-graph/get-module/index.js, packages/rspack-test-tools/tests/configCases/module-graph/get-module/rspack.config.js, packages/rspack/etc/core.api.md, packages/rspack/src/Module.ts
`moduleGraph.getResolvedModule(dependency)` is used to access the module that is constructed through the dependency during the build phase. 
`moduleGraph.getModule(dependency)` is utilized to access the module corresponding to the dependency in the current module graph. For instance, during the `processAssets` phase, the `concatenateModules` optimization is performed, and multiple dependencies might point to the same concatenated module.
=> fix: get resolved module

website/docs/en/config/output.mdx, website/docs/zh/config/output.mdx
close https://github.com/web-infra-dev/rspack/issues/8904
This pull request includes updates to the documentation files in both English and Chinese versions to improve clarity and consistency. The changes primarily focus on formatting template strings and adding warnings about potential issues when debugging locally.
Documentation improvements:
* [`website/docs/en/config/output.mdx`](diffhunk://#diff-d01ce2a5c8cbd0d1c619c856a42b43b7b88c7cde064eb59a3f06c3d28962a435L510-R553): Formatted template strings by enclosing them in backticks for better readability and consistency.
* [`website/docs/zh/config/output.mdx`](diffhunk://#diff-5f25b9fbab228930729efa5d88021a4e0fc51ab2dcdc6a6e5a691687b75e573dL507-R549): Formatted template strings by enclosing them in backticks for better readability and …
=> docs: add warning about hmr fails when filename has hash

.github/workflows/reusable-build.yml, packages/rspack/package.json, packages/rspack/scripts/check-documentation-coverage.mjs, packages/rspack/scripts/check-documentation-coverage.ts, pnpm-lock.yaml, website/docs/en/plugins/webpack/internal-plugins.mdx, website/docs/zh/plugins/webpack/internal-plugins.mdx
The documentation coverage check CI has been skipped since https://github.com/web-infra-dev/rspack/pull/8072.
This PR added it back and use `tsx` to ensure it can get the zod meta data from the source code.
=> ci: fix documentation coverage check

crates/node_binding/binding.d.ts, crates/rspack_binding_values/src/raw_options/mod.rs, crates/rspack_core/src/cache/persistent/mod.rs, crates/rspack_core/src/cache/persistent/version.rs, crates/rspack_core/src/options/compiler_options.rs, crates/rspack_core/src/options/compiler_options_builder.rs, crates/rspack_core/src/options/mode.rs, packages/rspack-test-tools/tests/cacheCases/invalidation/config-mode/file.js, packages/rspack-test-tools/tests/cacheCases/invalidation/config-mode/index.js, packages/rspack-test-tools/tests/cacheCases/invalidation/config-mode/rspack.config.js, packages/rspack-test-tools/tests/cacheCases/invalidation/config-name/file.js, packages/rspack-test-tools/tests/cacheCases/invalidation/config-name/index.js, packages/rspack-test-tools/tests/cacheCases/invalidation/config-name/rspack.config.js, packages/rspack/src/config/adapter.ts
Support invalidate persistent cache using config.mode and config.name.
=> feat: support invalidate persistent cache using `config.mode` and `config.name`

package.json, packages/rspack-test-tools/package.json, pnpm-lock.yaml, tests/plugin-test/css-extract/cases/pathinfo-devtool-source-map/expected/main.css, tests/plugin-test/css-extract/cases/pathinfo/expected/main.css
5.96.0 introduces TypeScript changes and test failures that we will need to deal with later.
- This should be enough to fix #8875.
=> chore(deps): Upgrade and pin webpack to 5.95.0

.github/actions/pnpm-cache/action.yml, .github/workflows/reusable-build.yml
The pnpm/action-setup will install pnpm with an immutable version. However, in ecosystem-benchmark and ecosystem-ci, we need to clone the repo and run `pnpm i`. Using corepack can avoid the problem of inconsistent pnpm versions.
=> ci: use corepack instead of pnpm/action-setup

website/docs/en/api/loader-api/index.mdx, website/docs/en/api/loader-api/inline-match-resource.mdx, website/docs/en/api/loader-api/rspack-specific-properties.mdx, website/docs/en/blog/announcing-0-4.mdx, website/docs/en/plugins/index.mdx, website/docs/zh/api/loader-api/index.mdx, website/docs/zh/api/loader-api/inline-match-resource.mdx, website/docs/zh/blog/announcing-0-3.mdx, website/docs/zh/plugins/index.mdx
The current loader index page is too simple, this PR updates the page to make it as an overview page.
=> docs: add loader API overview page

.github/actions/pnpm-cache/action.yml
pnpm@9 does not support node16, use pnpm/exe instead.
=> ci: pnpm cache install pnpm/exe when node16

packages/rspack/src/builtin-plugin/lazy-compilation/plugin.ts
There is an option [`experiments.lazyCompilation.backend.client`](https://rspack.dev/config/experiments#experimentslazycompilation) that can specify custom client of LazyCompilation.
But it doesn't seem to work since it will always be overwritten by `hot/lazy-compilation-web.js` or `hot/lazy-compilation-node.js`
=> fix: allow custom `lazyCompilation.backend.client`

crates/rspack_plugin_lazy_compilation/src/module.rs, tests/e2e/cases/lazy-compilation/persistent-cache/index.test.ts, tests/e2e/cases/lazy-compilation/persistent-cache/rspack.config.js, tests/e2e/cases/lazy-compilation/persistent-cache/src/component.js, tests/e2e/cases/lazy-compilation/persistent-cache/src/index.js, tests/e2e/fixtures/rspack.ts
The client field in `LazyCompilationProxyModule` will contains port info which can not be shared between different compiler.
=> fix: lazy compilation use persistent cache restart failure

website/docs/en/config/experiments.mdx, website/docs/zh/config/experiments.mdx
This pull request includes updates to the documentation for cache invalidation. The changes aim to provide additional tips on persistent cache invalidation and the conditions under which the cache is invalidated.
=> docs: add persistent cache invalidation notes

Cargo.lock, crates/rspack/Cargo.toml, crates/rspack/src/options/builder.rs, crates/rspack/src/options/devtool.rs, crates/rspack/src/options/mod.rs, crates/rspack_core/src/options/output.rs
=> feat: initialize builtin plugins in compiler options builder

website/docs/en/contribute/development/releasing.md, website/docs/zh/contribute/development/releasing.md
Canary version package name has changed from `@rspack/core-canary` to `@rspack-canary/core`
=> docs: fix canary package name

crates/node_binding/binding.d.ts, crates/rspack_binding_values/src/chunk_group.rs, crates/rspack_core/src/chunk_group.rs, packages/rspack-test-tools/tests/configCases/chunks/module-order-index/index.js, packages/rspack-test-tools/tests/configCases/chunks/module-order-index/rspack.config.js, packages/rspack/etc/core.api.md, packages/rspack/src/ChunkGroup.ts
close #8548
Support `ChunkGroup.getModulePreOrderIndex` and `ChunkGroup.getModulePostOrderIndex`
=> feat: support chunkGroup.getModulePreOrderIndex

Cargo.lock, Cargo.toml
Swc v10.0.1 make performance optimize, about minify specially.
When compile large project that has many modules, it would be fastest in production mode.
So we upgrade Swc to v10.0.1
=> feat(core): bump swc_core to 10.0.1

crates/rspack_core/src/build_chunk_graph/code_splitter.rs, tests/plugin-test/css-extract/cases/dependOn-multiple-files-per-entry/expected/entry1.css
Code splitting will re-calculate modules' order index of outdated chunk group, however the entrypoints can have dependOn, and thus they can be outdated as well, we need to make sure we can re-calculate order indices of them as well.
For specific fixed case, you can see modified test case
=> fix: should recalculate order indices in outdated entrypoint

packages/rspack/etc/core.api.md, packages/rspack/src/config/types.ts, packages/rspack/src/config/zod.ts
Add missing argument to type declaration of `OptimizationSplitChunksNameFunction`.
:information_source: I have found this only empirically while migrating a webpack project to Rspack, but I have no experience with Rspack codebase, so it'd be appreciated if reviewers verified if the type declaration is appropriate.
The following excerpt of `rspack.config.ts` works correctly, but yields TS error (it is used to group shared chunks, e.g. `shared/main-app~subprocess-app.js`):
```
optimization: {
splitChunks: {
chunks: 'all',
// Rspack type declaration is missing the 2nd argument
// @ts-expect-error Target signature provides too few arguments. Expected 2 or more, but got 1.
name: (_module, chunks: Chunk[]) => {
return chunks.length === 1
? chunks[0].name
: `shared/${chunks.map((item: any) => …
```
=> fix(type): Add missing OptimizationSplitChunksNameFunction param

website/docs/en/api/loader-api/context.mdx, website/docs/zh/api/loader-api/context.mdx
Fixing the inaccurate documentation for the loader api `getLogger()`.
=> docs: fix loader API getLogger types documentation

crates/rspack_loader_runner/src/runner.rs
`run_loaders` takes a single plugin only.
=> chore: `run_loaders` takes a single plugin only

Cargo.lock, Cargo.toml
According to [SWC ChangeLog](https://github.com/swc-project/swc/blob/main/CHANGELOG.md#1107---2025-01-10), swc_core v10.1.0 improve DCE, it will reduce js production size. 
So we upgrade SWC to v10.1.0
=> feat(core): bump swc_core to 10.1.0

crates/rspack_plugin_extract_css/src/plugin.rs, packages/rspack-test-tools/tests/compilerCases/invalidation-multi-times.js, packages/rspack/src/Watching.ts
Align with webpack.
If invalidate after watching is running, watching should invalidate again when invalidate is done.
For example: there are 2 files.
Once invalidate on file one, the compiler is running, then I invoke invalidate file two, watching is invalid as there are another files to be invalidated. Watching should invoke invalidate again
=> fix: should run invalidation when watching is invalid

packages/rspack/etc/core.api.md, packages/rspack/src/builtin-plugin/lazy-compilation/backend.ts, packages/rspack/src/config/types.ts, website/docs/en/config/experiments.mdx, website/docs/zh/config/experiments.mdx
Fix missing `lazyCompilation.backend.server` option. This option is implemented, but lacks a definition in the public types.
We can reuse the `LazyCompilationDefaultBackendOptions` type to fix this.
=> fix(types): missing `lazyCompilation.backend.server` option

packages/rspack-cli/package.json, packages/rspack-tracing/package.json, packages/rspack/package.json, packages/rspack/src/exports.ts, packages/rspack/src/loader-runner/index.ts, pnpm-lock.yaml
Mark `@rspack/tracing` as peer dependency. For users using `otel` as their tracing layer, make sure `@rspack/tracing` is installed.
=> feat: mark `@rspack/tracing` as peer dependency

crates/rspack_core/src/cache/persistent/occasion/make/module_graph.rs, crates/rspack_core/src/cache/persistent/snapshot/mod.rs, crates/rspack_core/src/cache/persistent/snapshot/strategy.rs
persistent cache use multi-thread on serialize and deserialize.
=> perf: persistent cache use multi-thread

Cargo.lock, Cargo.toml
Lightning Css v1.0.0-alpha.63 fix a lot bugs and support parsing the `@font-feature-values` rule .
See more detail: https://github.com/parcel-bundler/lightningcss/releases/tag/v1.29.0
So we upgrade it to v1.0.0-alpha.63
=> chore(deps): update lightningcss to v1.0.0-alpha.63

.github/workflows/ci.yml, .github/workflows/ecosystem-benchmark.yml, .github/workflows/ecosystem-ci.yml, .github/workflows/label-auto-comment.yml, .github/workflows/lint-pr.yaml, .github/workflows/preview-commit.yml, .github/workflows/release-canary.yml, .github/workflows/release.yml, .github/workflows/reusable-build.yml, tests/webpack-test/scripts/generate.js
Declare minimal permissions for GitHub Actions, and remove some unused `GITHUB_TOKEN`.
Ref: https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/controlling-permissions-for-github_token
=> ci: declare minimal permissions for Actions

.github/workflows/ecosystem-benchmark.yml, .github/workflows/ecosystem-ci.yml, .github/workflows/reusable-build.yml
Fix permission issues:
- Add `pull-requests: write` to allow commenting on pull requests
- Disable `Update main branch test compatibility metric` because this step requires push permission and should be refactored, @LingyuCoder 
Related: https://github.com/web-infra-dev/rspack/pull/9018
=> ci: fix workflow permission issues

packages/rspack/package.json, pnpm-lock.yaml
Bump prebundle v1.2.7 to disable ncc CI cache and fix our CI.
Related:
- https://github.com/rspack-contrib/prebundle/releases
- https://github.com/web-infra-dev/rspack/actions/runs/12821935790/job/35754068062?pr=8833
=> chore(deps): bump prebundle v1.2.7 to disable CI cache

crates/node_binding/src/plugins/js_loader/context.rs, crates/rspack_napi/src/ext/js_string_ext.rs
rspack shouldn't panic when accept invalid sourcemap
=> fix(core): don't panic when accept invalid sourcemap

.github/workflows/ecosystem-ci.yml
This PR will ignore all failed Ecosystem-ci in the workflow, but comment them in the PR or commit.
=> ci: ecosystem ci shows errors only on comment

Cargo.lock, Cargo.toml
Use patched mimalloc to use `MADV_DONTNEED` instead of `MADV_FREE` on reseting memory.
This also takes effect on macOS.
While `MADV_FREE` is faster than `MADV_DONTNEED`, it does not affect the `RSS` as `MADV_DONTNEED` does.
To reiterate, using `MADV_DONTNEED` means process-level memory statistics like RSS will be more 
accurately reflect the amount of physical memory being used by rspack.
Even this does not show any evidence that it would cause OOM issues, the fact seems stay the opposite 
with [reported incidents in go](https://github.com/golang/go/issues/42354).  GoLang team and many have encountered this issue and have reverted the option to `MADV_DONTNEED` in https://github.com/golang/go/issues/42330.
Rspack uses mimalloc for memory management.
The default strategy of mimalloc@2 is to …
=> fix: patched mimalloc to use `MADV_DONTNEED` than `MADV_FREE` on Linux

crates/node_binding/src/plugins/js_loader/context.rs, crates/rspack_loader_next_app/src/create_tree_code_from_path.rs, crates/rspack_loader_next_app/src/is_metadata_route.rs
Fixes infinite loop occurring with parallel routes and applies source map fix to sources content as well. Also fixes tiny typo in metadata regex for favicon.
=> fix: parallel routes handling

packages/rspack/src/loader-runner/index.ts
import('@rspack/tracing') doesn't have cache, so it runs every time tryTrace executes, add cache for performance
=> perf: caching require @rspack/tracing

packages/rspack-test-tools/tests/NewCodeSplitting-config.test.js
Skip MF config test case for parallel code splitting, as it fails for unknown reason and I can't repro in my local dev environment, I will enable this test case once I figure this out
=> fix: skip mf tests for new code splitting

crates/node_binding/binding.d.ts, crates/rspack_binding_values/src/stats.rs, crates/rspack_core/src/module_graph/mod.rs, crates/rspack_core/src/stats/mod.rs, crates/rspack_core/src/stats/struct.rs, crates/rspack_core/src/stats/utils.rs, crates/rspack_plugin_javascript/src/plugin/side_effects_flag_plugin.rs, packages/rspack-test-tools/tests/__snapshots__/NewCodeSplitting-stats-output.test.js.snap, packages/rspack-test-tools/tests/__snapshots__/StatsAPI.test.js.snap, packages/rspack-test-tools/tests/__snapshots__/StatsOutput.test.js.snap, packages/rspack-test-tools/tests/statsAPICases/build-time-executed.js, packages/rspack-test-tools/tests/statsAPICases/chunks.js, packages/rspack-test-tools/tests/statsAPICases/nested-modules.js, packages/rspack/etc/core.api.md, packages/rspack/src/stats/DefaultStatsFactoryPlugin.ts, packages/rspack/src/stats/statsFactoryUtils.ts, pnpm-lock.yaml, tests/webpack-test/__snapshots__/StatsTestCases.basictest.js.snap, tests/webpack-test/package.json
close https://github.com/web-infra-dev/rspack/issues/8953
close https://github.com/web-infra-dev/rspack/issues/7487
=> feat(stats): add module reason locations and module trace dependencies

crates/node_binding/binding.d.ts, crates/rspack_binding_values/src/chunk_graph.rs, crates/rspack_core/src/chunk_graph/chunk_graph_chunk.rs, packages/rspack-test-tools/tests/configCases/chunk-graph/get-number-of-entry-modules/bar.js, packages/rspack-test-tools/tests/configCases/chunk-graph/get-number-of-entry-modules/baz.js, packages/rspack-test-tools/tests/configCases/chunk-graph/get-number-of-entry-modules/foo.js, packages/rspack-test-tools/tests/configCases/chunk-graph/get-number-of-entry-modules/rspack.config.js, packages/rspack/etc/core.api.md, packages/rspack/src/ChunkGraph.ts
Implement the `chunkGraph.getNumberOfEntryModules` API of Webpack.
See: https://github.com/webpack/webpack/blob/3919c844eca394d73ca930e4fc5506fb86e2b094/lib/ChunkGraph.js#L1187
This allows getting the number of entry modules without iterating over it(which has better performance).
=> feat: add chunkGraph.getNumberOfEntryModules

.typos.toml, website/docs/en/blog/announcing-1-2.mdx, website/docs/zh/blog/announcing-1-2.mdx, website/project-words.txt
This pull request includes updates to the blog documentation to announce improvements in the Rspack ecosystem. The most important changes include the addition of Angular support, the release of Rsbuild v1.2, and updates to the SWC plugin upgrade guide.
=> docs: add v1.2 ecosystem updates

crates/node_binding/binding.d.ts, crates/rspack_binding_values/src/module.rs, packages/rspack/src/Module.ts
=> fix: resolve the inconsistent type issue in `JsModule`

crates/rspack_core/src/exports_info.rs, crates/rspack_plugin_dll/src/dll_reference/delegated_module.rs, packages/rspack-test-tools/tests/configCases/dll/no-warning-for-cjs/a.js, packages/rspack-test-tools/tests/configCases/dll/no-warning-for-cjs/lib.js, packages/rspack-test-tools/tests/configCases/dll/no-warning-for-cjs/main.js, packages/rspack-test-tools/tests/configCases/dll/no-warning-for-cjs/rspack.config.js, packages/rspack-test-tools/tests/configCases/dll/no-warning-for-cjs/warnings.js, tests/webpack-test/configCases/dll-plugin/1-use-dll/index.js, tests/webpack-test/configCases/dll-plugin/2-use-dll-without-scope/index.js
fix https://github.com/web-infra-dev/rspack/issues/9016
=> fix: should not have warnings for cjs when using dll 

packages/rspack-tracing/types/index.d.ts, packages/rspack/src/loader-runner/index.ts
Only cache `@rspack/tracing` instead of tracing instance to avoid tracing being written to the incorrect context.
After:
=> fix: should not cache tracing instance

crates/rspack_plugin_javascript/src/parser_plugin/amd/amd_define_dependency_parser_plugin.rs, crates/rspack_plugin_javascript/src/parser_plugin/common_js_imports_parse_plugin.rs, packages/rspack-test-tools/src/helper/legacy/checkArrayExpectation.js, tests/webpack-test/cases/parsing/issue-4940/test.filter.js, tests/webpack-test/cases/parsing/local-modules/test.filter.js, tests/webpack-test/cases/parsing/unsupported-amd/errors.js, tests/webpack-test/cases/parsing/unsupported-amd/test.filter.js, tests/webpack-test/cases/parsing/unsupported-amd/warnings.js, tests/webpack-test/cases/resolving/commomjs-local-module/test.filter.js, tests/webpack-test/checkArrayExpectation.js
fix `require("AMDLocalModule")` and support `new require("./cjs")`
=> fix: require local module and support new require

Cargo.lock, Cargo.toml
Update `swc_core` to v10.7.0, which should improve the performance of the SWC minimizer.
See https://github.com/swc-project/swc/blob/main/CHANGELOG.md
=> chore(deps): update `swc_core` to v10.7.0

website/docs/en/guide/optimization/code-splitting.mdx, website/docs/zh/guide/optimization/code-splitting.mdx
Fix an invalid `cacheGroups` example in the documentation.
resolve https://github.com/web-infra-dev/rspack/issues/8993
=> docs: fix invalid `cacheGroups` example

.github/ISSUE_TEMPLATE/1-bug-report.en-US.yml, .github/ISSUE_TEMPLATE/2-feature-request.en-US.yml
The GitHub issue types work well and we can remove the issue label to reduce duplicated information.
https://github.com/web-infra-dev/rspack/pull/8663
=> chore(workflow): remove duplicated issue label

packages/rspack/src/builtin-plugin/html-plugin/options.ts, website/docs/en/plugins/rspack/html-rspack-plugin.mdx, website/docs/zh/plugins/rspack/html-rspack-plugin.mdx
Changes:
* Fixes the description of `HtmlRspackPluginOptions.meta` and `HtmlRspackPluginOptions.hash` fields (previously these were mixed up in places).
* Improve descriptions and default values of other fields from `HtmlRspackPluginOptions`.
* Align the docs on `HtmlRspackPluginOptions` with the updated type.
* Apply other minor formatting and wording updates to HtmlRspackPlugin documentation.
=> docs: improve HtmlRspackPlugin docs and types

website/docs/en/api/plugin-api/compiler-hooks.mdx, website/docs/zh/api/plugin-api/compiler-hooks.mdx
Add the missing documentation for `compiler.hooks.finishMake`.
https://github.com/web-infra-dev/rspack/blob/98d1c37b7c6ee4a36e49d26ffc69880f9ba9971e/packages/rspack/src/Compiler.ts#L130
=> docs: add `compiler.hooks.finishMake`

website/rspress.config.ts
This pull request includes changes to the `website/rspress.config.ts` file to dynamically generate Open Graph images based on the route path. The most important changes include adding a function to determine the appropriate Open Graph image and removing the hardcoded image URL.
- https://rspress.dev/api/config/config-basic#head
- https://github.com/rspack-contrib/rstack-design-resources/tree/main/rspack/assets
=> docs: set Open Graph images based on page routes

.github/actions/docker-build/action.yml, .github/actions/pnpm-cache/action.yml, package.json
Fix corepack key id mismatch, see https://github.com/web-infra-dev/rslib/pull/728, https://github.com/nodejs/corepack/issues/612 and https://github.com/pnpm/pnpm/issues/9029 for background.
This PR should fix all the failed CI, such as https://github.com/web-infra-dev/rspack/actions/runs/13118033695/job/36638142714?pr=9152
=> ci: fix corepack key id mismatch

packages/rspack/etc/core.api.md, packages/rspack/src/config/zod.ts
The zod schema for the `lazyCompilation.backend` configuration is out of date and this PR updates the schema to match with the type declaration.
See: https://rspack.dev/config/experiments#experimentslazycompilation
=> fix: correct lazy compilation backend options schema
