crates/node_binding/binding.d.ts, crates/rspack_binding_options/src/options/raw_builtins/raw_copy.rs, crates/rspack_plugin_copy/src/lib.rs, plugin-test/copy-plugin/CopyPlugin.test.js, plugin-test/copy-plugin/__snapshots__/CopyPlugin.test.js.snap, website/docs/en/plugins/rspack/copy-rspack-plugin.mdx, website/docs/zh/plugins/rspack/copy-rspack-plugin.mdx
CopyRspackPlugin support function `to` option.
resolve: https://github.com/web-infra-dev/rspack/issues/6836
=> feat: CopyRspackPlugin support function `to` option

website/docs/en/guide/compatibility/plugin.mdx
=> docs: fixed typo on compatibility list header

website/docs/en/api/javascript-api.mdx, website/docs/zh/api/javascript-api.mdx
Same as https://github.com/web-infra-dev/rspack/pull/6889
Related PR: https://github.com/web-infra-dev/rspack/pull/4728
=> docs: fix rspack exports in zh javascript-api.mdx

Cargo.lock, Cargo.toml, crates/rspack_core/src/build_chunk_graph/code_splitter.rs, crates/rspack_loader_swc/Cargo.toml, crates/rspack_plugin_javascript/src/plugin/mod.rs, crates/rspack_plugin_javascript/src/plugin/module_concatenation_plugin.rs, packages/rspack-test-tools/tests/configCases/plugins/internal-processAssets-param-assets/index.js, packages/rspack-test-tools/tests/diagnosticsCases/factorize/mismatched-module-type/stats.err, packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/lack-equal/stats.err, plugin-test/css-extract/cases/simple-async-source-map/expected/async_css.css.map, plugin-test/css-extract/cases/simple-async-source-map/expected/main.css.map
=> revert: chore(deps): update crates (major) (#6855)

packages/rspack/etc/api.md, packages/rspack/src/builtin-plugin/css-extract/index.ts, website/docs/en/plugins/rspack/css-extract-rspack-plugin.mdx, website/docs/zh/plugins/rspack/css-extract-rspack-plugin.mdx
=> fix: fix type of CssExtractRspackPluginOptions.{filename,chunkFilename}

crates/rspack_plugin_devtool/src/eval_dev_tool_module_plugin.rs, packages/rspack-test-tools/tests/configCases/source-map/eval-only/test.js
=> feat: encode filename in EvalDevToolModulePlugin

crates/rspack_plugin_devtool/src/eval_dev_tool_module_plugin.rs, crates/rspack_plugin_devtool/src/eval_source_map_dev_tool_plugin.rs
=> fix: devtool plugin cache conflict !macos

crates/node_binding/binding.d.ts, crates/rspack_binding_values/src/stats.rs, crates/rspack_core/src/stats.rs, packages/rspack-test-tools/tests/__snapshots__/StatsAPI.test.js.snap, packages/rspack-test-tools/tests/statsAPICases/chunks.js, packages/rspack/src/stats/DefaultStatsFactoryPlugin.ts, webpack-test/__snapshots__/StatsTestCases.basictest.js.snap
=> feat: add idHints and hash of stats.chunk

crates/rspack_plugin_javascript/src/visitors/scope_info.rs
=> docs: explain `VariableInfo`

crates/rspack_loader_swc/src/lib.rs
=> fix: fix release build

website/docs/en/guide/migration/webpack.mdx, website/docs/zh/guide/migration/webpack.mdx
=> docs: improve webpack migration

README.md, README.zh-CN.md
=> docs: fix license badge and add node badge

website/docs/en/config/optimization.mdx, website/docs/zh/config/optimization.mdx
- Resolves https://github.com/web-infra-dev/rspack/issues/6890
=> docs(config): temporary fix for mdx display bug

crates/rspack_core/src/normal_module_factory.rs, crates/rspack_loader_runner/src/scheme.rs, webpack-test/cases/resolving/data-uri/test.filter.js, webpack-test/configCases/asset-modules/resource-from-data-uri/test.filter.js
closes https://github.com/web-infra-dev/rspack/issues/4445
=> feat: support use data uri with inline loaders

website/docs/en/api/stats.mdx, website/docs/zh/api/stats.mdx
- Use type instead of json to describe stats data structure
=> docs: describe stats data structure with ts types

website/docs/en/config/externals.mdx, website/docs/zh/config/externals.mdx
Changes to note:
- Didn't document out `byLayer`, this isn't supported yet.
=> docs: polish up external config

crates/node_binding/binding.d.ts, crates/node_binding/src/plugins/interceptor.rs, crates/node_binding/src/plugins/mod.rs, crates/rspack_binding_values/src/normal_module_factory.rs, crates/rspack_macros/src/hook.rs, packages/rspack-test-tools/tests/configCases/hooks/stage-0-factorize/index.js, packages/rspack-test-tools/tests/configCases/hooks/stage-0-factorize/rspack.config.js, packages/rspack-test-tools/tests/hookCases/compilation#processAssets/update-asset/hooks.snap.txt, packages/rspack/etc/api.md, packages/rspack/src/Compiler.ts, packages/rspack/src/Module.ts, packages/rspack/src/NormalModuleFactory.ts, packages/rspack/src/config/zod.ts, packages/rspack/src/lite-tapable/index.ts
Compat unplugin
- add contextInfo on resolveData
- add factorize js hook, only update resolveData for now, not support return module
- factorize stage 0 hook should bail by external plugin for external request
=> feat: add contextInfo on resolveData

packages/rspack-test-tools/src/processor/hook.ts, packages/rspack/declarations/webpack-sources.d.ts, packages/rspack/etc/api.md, packages/rspack/package.json, packages/rspack/prebundle.config.mjs, packages/rspack/src/exports.ts, packages/rspack/tsconfig.json, pnpm-lock.yaml
=> fix: sources types

crates/rspack_core/src/options/filename.rs
closes https://github.com/web-infra-dev/rspack/issues/6943
=> feat: optimize filename function diagnostic

packages/rspack-cli/src/cli.ts, packages/rspack-cli/src/commands/build.ts, packages/rspack-cli/src/types.ts
=> feat(cli): add --profile to enable stats module profile

website/docs/en/contribute/index.mdx, website/docs/zh/contribute/index.mdx
Explain the breaking change PR format in our contributing guide.
=> docs(contributing): breaking change PR format

README.md, README.zh-CN.md, crates/node_binding/README.md, packages/create-rspack/README.md, packages/playground/README.md, packages/rspack-cli/README.md, packages/rspack-dev-server/README.md, packages/rspack-plugin-minify/README.md, packages/rspack-plugin-preact-refresh/README.md, packages/rspack-plugin-react-refresh/README.md, packages/rspack-test-tools/README.md, packages/rspack/README.md, scripts/build-npm.cjs, website/docs/en/blog/module-federation-added-to-rspack.mdx, website/docs/en/misc/team/join-us.mdx, website/docs/zh/blog/module-federation-added-to-rspack.mdx, website/docs/zh/misc/team/join-us.mdx, website/rspress.config.ts
Update assets URLs, prefer using https://assets.rspack.dev/.
See https://github.com/rspack-contrib/rsfamily-design-resources for all assets.
=> docs: update assets URLs

.github/workflows/release.yml
=> chore(workflow): should allow alpha npm tag

website/docs/en/contribute/index.mdx, website/docs/en/guide/start/introduction.mdx, website/docs/en/misc/team/join-us.mdx, website/docs/zh/contribute/index.mdx, website/docs/zh/guide/start/introduction.mdx, website/docs/zh/misc/team/join-us.mdx, website/rspress.config.ts, website/theme/components/HomeFooter/index.tsx
update the discord invitation link
=> docs: upgrade latest discord invitation link

website/docs/en/contribute/development/releasing.md, website/docs/zh/contribute/development/releasing.md
add new way to override rspack version in document
https://github.com/rspack-contrib/install-rspack
https://github.com/web-infra-dev/modern.js/pull/5883
=> docs: use of nightly/canary version and install-rspack script

crates/node_binding/package.json, npm/darwin-arm64/package.json, npm/darwin-x64/package.json, npm/linux-x64-gnu/package.json, npm/win32-x64-msvc/package.json, package.json, packages/create-rspack/package.json, packages/rspack-cli/package.json, packages/rspack-dev-server/package.json, packages/rspack-plugin-minify/package.json, packages/rspack-plugin-preact-refresh/package.json, packages/rspack-plugin-react-refresh/package.json, packages/rspack-test-tools/package.json, packages/rspack-test-tools/tests/statsAPICases/bundler-info.js, packages/rspack/package.json
See announcement: https://github.com/web-infra-dev/rspack/pull/6945
=> release: 1.0.0-alpha.0

packages/rspack/etc/api.md, packages/rspack/src/config/zod.ts, website/docs/en/config/entry.mdx, website/docs/zh/config/entry.mdx
Should allow entry function to return promise:
see: https://www.rspack.dev/config/entry#dynamic-entry
=> fix(config): allow entry function to return promise

packages/rspack-test-tools/tests/configCases/hooks/stage-0-factorize/index.js, packages/rspack-test-tools/tests/configCases/hooks/stage-0-factorize/rspack.config.js
=> test: stable stage-0-factorize test

website/docs/en/blog/announcing-1-0-alpha.mdx, website/docs/zh/blog/announcing-1-0-alpha.mdx
add doc about how to switch back to `SwcCssMinimizerRspackPlugin` in case people met problem when use lightningcss
=> docs: add doc about switch back to SwcCssMinimizerRspackPlugin

website/components/PluginSupportStatusTable.tsx
`ContextExclusionPlugin` and `ContextReplacementPlugin` were listed twice.
=> docs: deduplicate plugin support status list

packages/rspack/src/loader-runner/index.ts
=> refactor: resolve nodejs 22 deprecation warning

crates/rspack_plugin_css/src/dependency/export.rs, crates/rspack_plugin_css/src/dependency/local_ident.rs, crates/rspack_plugin_css/src/parser_and_generator/mod.rs, packages/rspack-test-tools/tests/configCases/css/exports-convention-prod/index.js, packages/rspack-test-tools/tests/configCases/css/exports-convention-prod/style.module.css, packages/rspack-test-tools/tests/configCases/css/exports-convention-prod/test.config.js, packages/rspack-test-tools/tests/configCases/css/exports-convention-prod/webpack.config.js, packages/rspack/src/config/adapter.ts
=> fix: experiments css exports convention tree shaking

website/docs/en/api/modules/module-methods.mdx, website/docs/zh/api/modules/module-methods.mdx
Update documents of module methods
=> docs: complete the module methods

website/components/Columns.tsx, website/docs/en/api/modules/module-variables.mdx, website/docs/zh/api/modules/module-variables.mdx, website/project-words.txt
Update documents of module variables
=> docs: module variables

website/components/ApiMeta.module.scss, website/components/ApiMeta.tsx, website/docs/en/api/loader-api/rspack-specific-properties.mdx, website/docs/en/api/modules/module-methods.mdx, website/docs/en/api/modules/module-variables.mdx, website/docs/en/plugins/rspack/copy-rspack-plugin.mdx, website/docs/en/plugins/rspack/css-extract-rspack-plugin.mdx, website/docs/en/plugins/rspack/html-rspack-plugin.mdx, website/docs/en/plugins/rspack/lightning-css-minimizer-rspack-plugin.mdx, website/docs/en/plugins/rspack/swc-css-minimizer-rspack-plugin.mdx, website/docs/en/plugins/rspack/swc-js-minimizer-rspack-plugin.mdx, website/docs/zh/api/loader-api/rspack-specific-properties.mdx, website/docs/zh/api/modules/module-variables.mdx, website/docs/zh/plugins/rspack/copy-rspack-plugin.mdx, website/docs/zh/plugins/rspack/css-extract-rspack-plugin.mdx, website/docs/zh/plugins/rspack/html-rspack-plugin.mdx, website/docs/zh/plugins/rspack/lightning-css-minimizer-rspack-plugin.mdx, website/docs/zh/plugins/rspack/swc-css-minimizer-rspack-plugin.mdx, website/docs/zh/plugins/rspack/swc-js-minimizer-rspack-plugin.mdx
- Add specifics tags to distinguish from webpack and standards.
=> docs: add specifics for api meta

crates/rspack_plugin_javascript/src/plugin/module_concatenation_plugin.rs
Detect which modules can be concatenated in parallel
=> perf: make picking concatenable modules parallel

website/docs/en/plugins/webpack/externals-plugin.mdx, website/docs/zh/plugins/webpack/externals-plugin.mdx
=> docs: improve externals plugin doc

website/docs/en/api/modules/module-methods.mdx, website/docs/en/guide/optimization/code-splitting.mdx, website/docs/zh/api/modules/module-methods.mdx, website/docs/zh/guide/optimization/code-splitting.mdx
- Add documents for prefetch&preload
=> docs: add prefetch&preload modules

crates/rspack_plugin_javascript/src/visitors/dependency/parser/walk.rs, packages/rspack-test-tools/tests/configCases/parsing/rspack-issue-7012/index.js, packages/rspack-test-tools/tests/configCases/parsing/rspack-issue-7012/rspack.config.js
closes https://github.com/web-infra-dev/rspack/issues/7012
=> fix: should not generate pure expression if test is failed

website/docs/en/_meta.json, website/docs/en/config/node.mdx, website/docs/zh/_meta.json, website/docs/zh/config/node.mdx
=> docs: default value in node config

packages/rspack-cli/src/utils/profile.ts, packages/rspack/etc/api.md, packages/rspack/src/exports.ts, website/docs/en/contribute/development/profiling.md, website/docs/zh/contribute/development/profiling.md
=> refactor!: move global trace export to experiments

packages/rspack-lite-tapable/etc/api.md, packages/rspack-lite-tapable/src/index.ts, packages/rspack-lite-tapable/temp/api.md, packages/rspack/etc/api.md, packages/rspack/prebundle.config.mjs, packages/rspack/src/Compilation.ts, packages/rspack/src/stats/StatsFactory.ts
=> fix: use lite-tapable for enhanced-resolve

tests/webpack-test/cases/cjs-tree-shaking/reexports/test.filter.js
=> test: enable webpack cjs-treeshaking reexport cases

packages/create-rspack/template-react-ts/package.json, packages/create-rspack/template-react/package.json, packages/create-rspack/template-vanilla/package.json, packages/create-rspack/template-vue-ts/package.json, packages/create-rspack/template-vue/package.json, pnpm-lock.yaml
fix #4798  starter template's npm script is not work well  in windows.
=> fix: fix npm script in window

website/docs/en/api/plugin-api/_meta.json, website/docs/en/api/plugin-api/compilation-hooks.mdx, website/docs/en/api/plugin-api/stats-hooks.mdx, website/docs/zh/api/plugin-api/_meta.json, website/docs/zh/api/plugin-api/compilation-hooks.mdx, website/docs/zh/api/plugin-api/stats-hooks.mdx
- Update documents of compilation hooks
- Add documents of stats hooks (need to add more content, some hooks are missing in the webpack documentation yet)
=> docs: update compilation hooks

crates/rspack_plugin_javascript/src/dependency/esm/harmony_import_dependency.rs, crates/rspack_plugin_javascript/src/parser_plugin/common_js_exports_parse_plugin.rs, crates/rspack_plugin_javascript/src/visitors/dependency/parser/mod.rs, crates/rspack_plugin_javascript/src/visitors/dependency/parser/walk.rs, packages/rspack-plugin-preact-refresh/tests/hotCases/hook/useContext#initial/__snapshots__/web/1.snap.txt, packages/rspack-plugin-preact-refresh/tests/hotCases/hook/useContext#keep/__snapshots__/web/1.snap.txt, packages/rspack-plugin-preact-refresh/tests/hotCases/hook/useContext#provide/__snapshots__/web/1.snap.txt, packages/rspack-test-tools/tests/normalCases/parsing/cjs-unset-exports-type/cjs.js, packages/rspack-test-tools/tests/normalCases/parsing/cjs-unset-exports-type/index.js
=> fix: wrong cjs exports type caused unexpected exports presence

tests/webpack-test/cases/context/issue-10969/index.js, tests/webpack-test/cases/context/issue-10969/test.filter.js
=> test: enable cases/context/issue-10969

crates/rspack_plugin_swc_js_minimizer/src/minify.rs, packages/rspack-test-tools/tests/configCases/plugins/minify-extract-comments/index.js
fix https://github.com/web-infra-dev/rspack/issues/6971
=> fix: deduplicate extracted comments

.github/workflows/reusable-build.yml
=> chore: release run macos test when arch match

tests/webpack-test/scripts/generate.js
=> chore: nightly release upload webpack-test metric data

crates/rspack_plugin_javascript/src/webpack_comment.rs, tests/webpack-test/configCases/trusted-types/custom-policy-name/test.filter.js, tests/webpack-test/configCases/trusted-types/default-policy-name/test.filter.js, tests/webpack-test/configCases/trusted-types/no-policy-name/test.filter.js, tests/webpack-test/configCases/trusted-types/no-trusted-types/test.filter.js
=> fix: detect magic comments around expr

.github/workflows/release-nightly.yml
=> chore: nightly release add write contents permission

packages/rspack/src/node/nodeConsole.ts
Fix
```
Error:   × TypeError: truncateArgs is not a function
```
=> fix: truncateArgs is not a function

Cargo.lock, crates/rspack_core/Cargo.toml, crates/rspack_core/src/options/resolve/mod.rs, crates/rspack_core/src/resolver/resolver_impl.rs, website/docs/en/contribute/development/debugging.mdx, website/docs/zh/contribute/development/debugging.mdx
migrate oxc_resolver to [rspack_resover](https://github.com/web-infra-dev/rspack-resolver), the current implementation is same as oxc_resolver, but we will add new feature to rspack_resolve in the future
=> fix(core): migrate to rspack_resolver

crates/rspack_plugin_javascript/src/webpack_comment.rs, packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/magic_comment_warning/index.js, packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/magic_comment_warning/stats.err, tests/webpack-test/__snapshots__/StatsTestCases.basictest.js.snap
=> fix: magic comment warning

crates/rspack_plugin_javascript/src/visitors/dependency/parser/walk.rs, packages/rspack-plugin-preact-refresh/tests/hotCases/hook/useContext#initial/__snapshots__/web/1.snap.txt, packages/rspack-plugin-preact-refresh/tests/hotCases/hook/useContext#keep/__snapshots__/web/1.snap.txt, packages/rspack-plugin-preact-refresh/tests/hotCases/hook/useContext#provide/__snapshots__/web/1.snap.txt, packages/rspack-plugin-preact-refresh/tests/hotCases/hook/useState#keep/__snapshots__/web/1.snap.txt, packages/rspack-plugin-preact-refresh/tests/hotCases/hook/useState#reset/__snapshots__/web/1.snap.txt, packages/rspack-plugin-preact-refresh/tests/hotCases/jsx/basic/__snapshots__/web/1.snap.txt, packages/rspack-plugin-preact-refresh/tests/hotCases/jsx/basic/__snapshots__/web/2.snap.txt, packages/rspack-plugin-preact-refresh/tests/hotCases/jsx/child/__snapshots__/web/1.snap.txt, packages/rspack-plugin-preact-refresh/tests/hotCases/jsx/child/__snapshots__/web/2.snap.txt, packages/rspack-plugin-preact-refresh/tests/hotCases/jsx/value/__snapshots__/web/1.snap.txt, packages/rspack-plugin-preact-refresh/tests/hotCases/jsx/value/__snapshots__/web/2.snap.txt, packages/rspack-test-tools/tests/normalCases/parsing/asi-sequence-expression/a.js, packages/rspack-test-tools/tests/normalCases/parsing/asi-sequence-expression/index.js
=> fix: revert detect statement level sequence expression

website/docs/public/baidu_verify_codeva-bE2dFTowhk.html
I found some SEO issues on [baidu.com](https://www.baidu.com/) and want to fix it. We need to add the baidu verify file to get the required permissions.
=> docs: add baidu verify file for SEO optimization

website/docs/public/_redirects, website/docs/public/baidu_verify_codeva-bE2dFTowhk.html, website/project-words.txt, website/rspress.config.ts
Fix netlify redirect cause baidu verify failed (see https://github.com/web-infra-dev/rspack/pull/7073 for background)
This PR uses another approach instead.
=> docs: fix netlify redirect cause baidu verify failed

website/components/webpack-license.tsx
Display title in the corresponding language according to the current document language (en /zh).
before:
after:
=> docs: update license ui

crates/rspack_plugin_javascript/src/parser_plugin/compatibility_plugin.rs, packages/rspack-test-tools/tests/configCases/plugins/compatibility-plugin/a.js, packages/rspack-test-tools/tests/configCases/plugins/compatibility-plugin/b.js, packages/rspack-test-tools/tests/configCases/plugins/compatibility-plugin/index.js
fix https://github.com/web-infra-dev/rspack/issues/6909
related webpack code: https://github.com/webpack/webpack/blob/8241da7f1e75c5581ba535d127fa66aeb9eb2ac8/lib/CompatibilityPlugin.js#L92
=> fix: Add missing code for compatibility plugin

.prettierignore, crates/rspack_core/src/code_generation_results.rs, crates/rspack_core/src/concatenated_module.rs, crates/rspack_core/src/lib.rs, crates/rspack_core/src/module.rs, crates/rspack_core/src/plugin/context.rs, crates/rspack_core/src/plugin/plugin_driver.rs, crates/rspack_plugin_javascript/src/dependency/esm/harmony_export_specifier_dependency.rs, crates/rspack_plugin_javascript/src/plugin/module_concatenation_plugin.rs, crates/rspack_plugin_library/src/lib.rs, crates/rspack_plugin_library/src/modern_module_library_plugin.rs, tests/webpack-test/configCases/library/0-create-library/webpack.config.js, tests/webpack-test/configCases/library/1-use-library/default-test-modern-module.js, tests/webpack-test/configCases/library/1-use-library/test.filter.js, tests/webpack-test/configCases/library/1-use-library/webpack.config.js
Port https://github.com/webpack/webpack/pull/18272
=> feat: tree shakable output for module library

crates/node_binding/binding.d.ts, crates/rspack_binding_options/src/options/raw_builtins/raw_copy.rs
here: https://github.com/webpack-contrib/copy-webpack-plugin/blob/master/src/index.js#L482
=> feat: to function can return Promise

crates/rspack_loader_runner/src/scheme.rs
=> perf: reduce `get_scheme` allocation

crates/rspack_core/src/concatenated_module.rs, crates/rspack_core/src/context_module.rs, crates/rspack_core/src/dependency/runtime_template.rs, crates/rspack_plugin_javascript/src/plugin/mod.rs, crates/rspack_plugin_mf/src/container/container_entry_module.rs, crates/rspack_plugin_mf/src/container/expose_runtime_module.rs, packages/rspack-test-tools/tests/__snapshots__/StatsAPI.test.js.snap, packages/rspack-test-tools/tests/builtinCases/rspack/dynamic-import/__snapshots__/output.snap.txt, packages/rspack-test-tools/tests/configCases/container-1-0/environment-es5/a.js, packages/rspack-test-tools/tests/configCases/container-1-0/environment-es5/bootstrap.js, packages/rspack-test-tools/tests/configCases/container-1-0/environment-es5/index.js, packages/rspack-test-tools/tests/configCases/container-1-0/environment-es5/rspack.config.js, packages/rspack-test-tools/tests/configCases/container-1-0/environment-es5/test.config.js, packages/rspack-test-tools/tests/statsAPICases/exports.js, packages/rspack-test-tools/tests/statsAPICases/nested-modules.js, tests/webpack-test/__snapshots__/StatsTestCases.basictest.js.snap
mf runtime should respect output environment
=> fix(mf): runtime should respect output environment

website/docs/en/blog/announcing-0-6.mdx, website/docs/en/guide/migration/cra.mdx, website/docs/en/guide/migration/storybook.mdx, website/docs/en/guide/migration/webpack.mdx
=> docs: polish migration wordings

crates/rspack_plugin_javascript/src/dependency/esm/harmony_export_expression_dependency.rs, crates/rspack_plugin_javascript/src/dependency/esm/harmony_export_imported_specifier_dependency.rs, crates/rspack_plugin_javascript/src/dependency/esm/harmony_import_dependency.rs, crates/rspack_plugin_javascript/src/dependency/esm/mod.rs, crates/rspack_plugin_javascript/src/parser_and_generator/mod.rs, crates/rspack_plugin_javascript/src/parser_plugin/drive.rs, crates/rspack_plugin_javascript/src/parser_plugin/harmony_export_dependency_parser_plugin.rs, crates/rspack_plugin_javascript/src/parser_plugin/harmony_import_dependency_parser_plugin.rs, crates/rspack_plugin_javascript/src/parser_plugin/inner_graph/plugin.rs, crates/rspack_plugin_javascript/src/parser_plugin/trait.rs, crates/rspack_plugin_javascript/src/visitors/dependency/mod.rs, crates/rspack_plugin_javascript/src/visitors/dependency/parser/estree.rs, crates/rspack_plugin_javascript/src/visitors/dependency/parser/mod.rs, crates/rspack_plugin_javascript/src/visitors/dependency/parser/walk.rs, crates/rspack_plugin_javascript/src/visitors/dependency/parser/walk_block_pre.rs, packages/rspack-test-tools/tests/statsAPICases/chunk-group.js
=> refactor: harmony export parser plugin

crates/rspack_plugin_javascript/src/parser_plugin/compatibility_plugin.rs, crates/rspack_plugin_javascript/src/parser_plugin/drive.rs, crates/rspack_plugin_javascript/src/parser_plugin/inner_graph/plugin.rs, crates/rspack_plugin_javascript/src/parser_plugin/trait.rs, crates/rspack_plugin_javascript/src/visitors/dependency/parser/estree.rs, crates/rspack_plugin_javascript/src/visitors/dependency/parser/mod.rs, crates/rspack_plugin_javascript/src/visitors/dependency/parser/walk.rs, crates/rspack_plugin_javascript/src/visitors/dependency/parser/walk_block_pre.rs, crates/rspack_plugin_javascript/src/visitors/dependency/parser/walk_pre.rs
=> refactor: remove clone in js walk

packages/rspack-test-tools/src/processor/hot-step.ts
Fix the unstable type in test tools, it breaks our benchmark CI:
See: https://github.com/web-infra-dev/rspack-ecosystem-benchmark/actions/runs/9916621315/job/27399141909
=> chore(test-tools): fix type issue for benchmark CI

website/docs/en/guide/start/quick-start.mdx, website/docs/zh/guide/start/quick-start.mdx
Update the quick start guide:
- Update Rsbuild description.
- Translate `Manual installation` to Chinese
- Add Vite migration link
=> docs: update the quick start guide

packages/rspack-cli/package.json
https://github.com/web-infra-dev/rspack/pull/7173#issuecomment-2229918269
=> fix(release): alpha peerDependencies in @rspack/cli

crates/node_binding/binding.d.ts, crates/node_binding/src/plugins/interceptor.rs, crates/rspack_binding_values/src/module.rs, crates/rspack_binding_values/src/normal_module_factory.rs, crates/rspack_binding_values/src/resource_data.rs, crates/rspack_core/src/dependency/dependency_type.rs, crates/rspack_core/src/loader/loader_runner.rs, crates/rspack_core/src/module_graph/mod.rs, crates/rspack_core/src/normal_module_factory.rs, crates/rspack_core/src/options/context.rs, crates/rspack_core/src/utils/module_rules.rs, crates/rspack_loader_runner/src/content.rs, crates/rspack_loader_runner/src/context.rs, crates/rspack_loader_runner/src/runner.rs, crates/rspack_loader_swc/src/lib.rs, crates/rspack_plugin_asset/src/lib.rs, crates/rspack_plugin_css/src/parser_and_generator/mod.rs, crates/rspack_plugin_extract_css/src/css_module.rs, crates/rspack_plugin_extract_css/src/plugin.rs, crates/rspack_plugin_javascript/src/parser_and_generator/mod.rs, crates/rspack_plugin_javascript/src/parser_plugin/node_stuff_plugin.rs, crates/rspack_plugin_javascript/src/plugin/side_effects_flag_plugin.rs, crates/rspack_plugin_schemes/src/file_uri.rs, packages/rspack-test-tools/tests/configCases/externals/external-fn-datauri-context/index.js, packages/rspack-test-tools/tests/configCases/externals/external-fn-datauri-context/rspack.config.js, packages/rspack/src/builtin-plugin/SwcCssMinimizerPlugin.ts
should have correct context for resource within scheme, checkout the test for more detail
=> fix: resource within scheme context

package.json, pnpm-lock.yaml, scripts/alert/lark.js, scripts/diff.cjs, scripts/package.json, scripts/test/add-config-type.cjs
chore(deps): Phantom dependencies of x.mjs and scripts
1. add dependencies
2. format some files
`npx scan-deps --directory alert,debug,meta,release,test --extension ts,jsx,tsx,cjs,mjs,js --debug`
https://github.com/chengcyber/scan-deps
=> chore(deps): Phantom dependencies of x.mjs and scripts

website/docs/en/contribute/development/testing-rspack.mdx, website/docs/zh/api/loader-api/rspack-specific-properties.mdx, website/docs/zh/blog/announcing-1-0-alpha.mdx, website/docs/zh/contribute/architecture/rspack-loader.md, website/docs/zh/contribute/development/profiling.md, website/docs/zh/contribute/development/testing-rspack.mdx
docs(format): run prettier --write
=> docs(format): run prettier --write

README.md, README.zh-CN.md, website/docs/en/blog/index.mdx, website/docs/zh/blog/index.mdx, website/theme/components/Benchmark/ProgressBar.tsx, website/theme/components/Benchmark/index.module.scss, website/theme/components/Benchmark/index.tsx, website/theme/components/Featured/index.module.scss, website/theme/components/Featured/index.tsx, website/theme/i18n/enUS.ts, website/theme/i18n/index.ts, website/theme/i18n/zhCN.ts, website/theme/pages/index.tsx
- Add a new features section to home page
- Fix some mistakes in the documentation
=> docs: add new features section to home page

crates/rspack_plugin_javascript/src/parser_plugin/common_js_imports_parse_plugin.rs, crates/rspack_plugin_javascript/src/utils/eval/eval_cond_expr.rs, packages/rspack-test-tools/tests/configCases/parsing/eval-condition-inside-require/a.js, packages/rspack-test-tools/tests/configCases/parsing/eval-condition-inside-require/index.js, packages/rspack-test-tools/tests/configCases/parsing/eval-condition-inside-require/rspack.config.js, website/theme/components/Benchmark/index.tsx
=> fix: eval condition expr range

.github/workflows/ci.yml, website/theme/components/Benchmark/ProgressBar.tsx
=> ci: add document lint changed check

crates/node_binding/binding.d.ts, crates/rspack_binding_values/src/stats.rs, crates/rspack_core/src/compiler/mod.rs, crates/rspack_core/src/stats.rs, packages/rspack-test-tools/tests/__snapshots__/StatsAPI.test.js.snap, packages/rspack-test-tools/tests/__snapshots__/StatsOutput.test.js.snap, packages/rspack-test-tools/tests/hashCases/real-content-hash-md4/test.config.js, packages/rspack-test-tools/tests/hashCases/real-content-hash-xxhash64/test.config.js, packages/rspack-test-tools/tests/statsAPICases/asset-info.js, packages/rspack-test-tools/tests/statsAPICases/child-compiler.js, packages/rspack/etc/api.md, packages/rspack/src/stats/DefaultStatsFactoryPlugin.ts, packages/rspack/src/stats/statsFactoryUtils.ts, tests/webpack-test/__snapshots__/StatsTestCases.basictest.js.snap
Align `chunkIdHints`, `auxiliaryChunks`, `auxiliaryChunkIdHints`, `auxiliaryChunkNames` of StatsAsset with webpack
=> feat: align StatsAsset with webpack

website/docs/en/api/stats.mdx, website/docs/zh/api/stats.mdx
Update documentations of StatsError and StatsAsset
=> docs: update stats data

Cargo.lock, crates/node_binding/src/plugins/interceptor.rs, crates/rspack_binding_values/src/resolver.rs, crates/rspack_core/src/context_module_factory.rs, crates/rspack_core/src/lib.rs, crates/rspack_core/src/normal_module_factory.rs, crates/rspack_core/src/resolver/mod.rs, crates/rspack_core/src/utils/identifier.rs, crates/rspack_loader_runner/Cargo.toml, crates/rspack_loader_runner/src/lib.rs, crates/rspack_loader_runner/src/loader.rs, crates/rspack_util/src/identifier.rs, packages/rspack-test-tools/tests/configCases/schemes/nmf-update-resource/index.js, packages/rspack-test-tools/tests/configCases/schemes/nmf-update-resource/rspack.config.js, packages/rspack-test-tools/tests/hookCases/normalModuleFactory#afterResolve/duplicate/duplicate.js, packages/rspack-test-tools/tests/hookCases/normalModuleFactory#afterResolve/duplicate/output.snap.txt, packages/rspack-test-tools/tests/hookCases/normalModuleFactory#afterResolve/request/output.snap.txt, packages/rspack-test-tools/tests/hookCases/normalModuleFactory#afterResolve/request/request.js, packages/rspack-test-tools/tests/hookCases/normalModuleFactory#afterResolve/resource/output.snap.txt, packages/rspack-test-tools/tests/hookCases/normalModuleFactory#afterResolve/resource/resource.js, packages/rspack-test-tools/tests/hookCases/normalModuleFactory#resolve/resource/output.snap.txt, packages/rspack-test-tools/tests/hookCases/normalModuleFactory#resolve/resource/resource.js, website/theme/components/Benchmark/ProgressBar.tsx
=> fix: update resource in nmf resolve hook

tests/webpack-test/hotCases/chunks/update-chunk-loading-runtime/node_modules/vendor.js, tests/webpack-test/hotCases/chunks/update-chunk-loading-runtime/test.filter.js, tests/webpack-test/hotCases/recover/recover-after-self-error/test.filter.js
Fix https://github.com/web-infra-dev/rspack/issues/5596, import.meta.webpackHot had been implemented, enable related webpack test cases
=> test: enable webpack test cases of webpackHot.data

crates/node_binding/binding.d.ts, crates/rspack_binding_options/src/options/raw_external.rs, crates/rspack_core/src/options/externals.rs, crates/rspack_plugin_externals/src/plugin.rs, packages/rspack/etc/api.md, packages/rspack/src/config/zod.ts
Align with https://webpack.js.org/configuration/externals/#function, type here https://github.com/webpack/webpack/blob/main/types.d.ts#L8192
=> feat: external callbacks receive contextInfo.issuer

packages/rspack-plugin-preact-refresh/package.json, packages/rspack-plugin-preact-refresh/tests/hotCases/hook/useContext#initial/__snapshots__/web/1.snap.txt, packages/rspack-plugin-preact-refresh/tests/hotCases/hook/useContext#keep/__snapshots__/web/1.snap.txt, packages/rspack-plugin-preact-refresh/tests/hotCases/hook/useContext#provide/__snapshots__/web/1.snap.txt, packages/rspack-plugin-preact-refresh/tests/hotCases/hook/useState#keep/__snapshots__/web/1.snap.txt, packages/rspack-plugin-preact-refresh/tests/hotCases/hook/useState#reset/__snapshots__/web/1.snap.txt, packages/rspack-plugin-preact-refresh/tests/hotCases/jsx/basic/__snapshots__/web/1.snap.txt, packages/rspack-plugin-preact-refresh/tests/hotCases/jsx/basic/__snapshots__/web/2.snap.txt, packages/rspack-plugin-preact-refresh/tests/hotCases/jsx/child/__snapshots__/web/1.snap.txt, packages/rspack-plugin-preact-refresh/tests/hotCases/jsx/child/__snapshots__/web/2.snap.txt, packages/rspack-plugin-preact-refresh/tests/hotCases/jsx/value/__snapshots__/web/1.snap.txt, packages/rspack-plugin-preact-refresh/tests/hotCases/jsx/value/__snapshots__/web/2.snap.txt
Enable snapshot test of preact refresh plugin
=> test: enable preact refresh snapshot test

tests/webpack-test/configCases/inner-graph/basic/test.filter.js
Close https://github.com/web-infra-dev/rspack/issues/5554, the `__webpack_exports_info__.usedExports ` had been supported
=> test: enable inner graph basic webpack test case

crates/node_binding/package.json, packages/playground/package.json, packages/rspack-cli/package.json, packages/rspack-dev-server/package.json, packages/rspack-lite-tapable/package.json, packages/rspack-plugin-preact-refresh/package.json, packages/rspack-plugin-react-refresh/package.json, packages/rspack-test-tools/package.json, packages/rspack/package.json, packages/rspack/src/lib/CacheFacade.js, pnpm-lock.yaml, scripts/package.json
typescript is also a phantom dependence, we are using the surprising version of tsc which caused local build failed
#7211 
https://github.com/web-infra-dev/rspack/pull/7211#issuecomment-2238700491
https://github.com/web-infra-dev/rspack/issues/7156
=> chore(deps): typescript phantom dependence

.github/workflows/reusable-build.yml
Refer to https://github.com/jlumbroso/free-disk-space/pull/26 for more
=> ci: speedup free disk space job

packages/rspack-dev-server/src/ansiHTML.ts, packages/rspack-dev-server/tests/ansiHTML.test.ts, packages/rspack-dev-server/tests/tsconfig.json
=> refactor: change ansiHTML to ts and esm

crates/rspack_plugin_schemes/src/http_cache.rs, crates/rspack_plugin_schemes/src/http_uri.rs
=> refactor: rspack http plugin cache

Cargo.lock, Cargo.toml, crates/rspack_binding_options/Cargo.toml, crates/rspack_binding_options/src/plugins/js_loader/resolver.rs, crates/rspack_loader_lightningcss/Cargo.toml, crates/rspack_loader_lightningcss/LICENSE, crates/rspack_loader_lightningcss/src/config.rs, crates/rspack_loader_lightningcss/src/lib.rs, crates/rspack_plugin_lightning_css_minimizer/Cargo.toml, packages/rspack-test-tools/tests/configCases/builtin-lightningcss-loader/basic/index.js, packages/rspack-test-tools/tests/configCases/builtin-lightningcss-loader/basic/index.module.css, packages/rspack-test-tools/tests/configCases/builtin-lightningcss-loader/basic/rspack.config.js, packages/rspack/etc/api.md, packages/rspack/src/builtin-loader/lightningcss/index.ts, packages/rspack/src/config/adapterRuleUse.ts, packages/rspack/src/exports.ts, website/docs/en/guide/features/builtin-lightningcss-loader.mdx, website/docs/zh/guide/features/builtin-lightningcss-loader.mdx
Support builtin:lightningcss-loader
🌟 Builtin support for lightningcss. Use lightningcss to replace postcss-loader for better build performance
=> feat: support lightningcss-loader

packages/rspack-test-tools/tests/configCases/runtime/runtime-condition/a.js, packages/rspack-test-tools/tests/configCases/runtime/runtime-condition/ax.js, packages/rspack-test-tools/tests/configCases/runtime/runtime-condition/b.js, packages/rspack-test-tools/tests/configCases/runtime/runtime-condition/bx.js, packages/rspack-test-tools/tests/configCases/runtime/runtime-condition/concatenated-shared.js, packages/rspack-test-tools/tests/configCases/runtime/runtime-condition/dep.js, packages/rspack-test-tools/tests/configCases/runtime/runtime-condition/dep2.js, packages/rspack-test-tools/tests/configCases/runtime/runtime-condition/rspack.config.js, packages/rspack-test-tools/tests/configCases/runtime/runtime-condition/shared.js, packages/rspack-test-tools/tests/configCases/runtime/runtime-condition/super.js, packages/rspack-test-tools/tests/configCases/runtime/runtime-condition/test.config.js
Close https://github.com/web-infra-dev/rspack/issues/6935
=> test: add test case for runtime condition

packages/rspack/src/config/browserslistTargetHandler.ts, packages/rspack/src/config/target.ts
Task `packages/rspack/src/config` of:
https://github.com/web-infra-dev/rspack/issues/7225
=> refactor(typescript): `packages/rspack/src/config` from js to ts/esm

packages/rspack/src/loader-runner/LoaderLoadingError.ts, packages/rspack/src/loader-runner/loadLoader.ts
=> refactor(typescript): loader runner to ts

biome.jsonc, packages/rspack-test-tools/src/runner/type.ts, packages/rspack/etc/api.md
=> chore(infra/biome): rule useEnumInitializers

biome.jsonc, packages/rspack-test-tools/src/compare/comparator.ts, packages/rspack-test-tools/src/helper/legacy/createLazyTestEnv.js, packages/rspack-test-tools/src/plugin/rspack-diff-config-plugin.ts, packages/rspack-test-tools/src/processor/diff.ts, packages/rspack-test-tools/src/processor/hot-step.ts, packages/rspack-test-tools/src/runner/hot-step.ts, packages/rspack-test-tools/src/runner/hot.ts, packages/rspack-test-tools/src/runner/runner/cjs.ts, packages/rspack-test-tools/src/runner/runner/esm.ts, packages/rspack-test-tools/src/runner/runner/watch.ts, packages/rspack-test-tools/src/runner/runner/web/fake.ts, packages/rspack-test-tools/src/runner/runner/web/jsdom.ts, packages/rspack/etc/api.md, packages/rspack/src/config/defaults.ts, scripts/diff.cjs, scripts/test/patch-node-env.cjs
=> chore(infra/biome): rule useLiteralKeys

biome.jsonc, packages/rspack/etc/api.md, packages/rspack/scripts/check-documentation-coverage.mjs, packages/rspack/src/config/adapter.ts, scripts/build-npm.cjs, scripts/meta/check_is_workspace_root.js, website/components/webpack-license.tsx, website/theme/components/Announcement/index.tsx
=> chore(infra/biome): rule noDoubleEquals

biome.jsonc, packages/create-rspack/template-react-ts/src/App.tsx, packages/create-rspack/template-react/src/App.jsx, packages/playground/cases/react/basic/src/App.jsx, packages/playground/cases/react/class-component/src/App.jsx, packages/playground/cases/react/with-babel/src/App.jsx, packages/playground/cases/react/worker/src/Button.jsx, website/theme/components/MenuGroup/index.tsx
=> chore(infra/biome): rule useButtonType

website/docs/en/api/plugin-api/compilation-hooks.mdx, website/docs/zh/api/plugin-api/compilation-hooks.mdx
Complete the processAssets document, add some examples and list all the available stages.
=> docs: complete processAssets document

packages/rspack/etc/api.md, packages/rspack/src/Compilation.ts, packages/rspack/src/Template.ts, packages/rspack/src/config/defaults.ts, packages/rspack/src/exports.ts
=> refactor(typescript): packages/rspack/src/template from js to ts and esm

packages/rspack-dev-server/jest.config.js, packages/rspack-dev-server/tests/normalizeOptions.test.ts, packages/rspack-dev-server/tests/tsconfig.json
ci(fix): jest error in rspack-dev-server
=> ci(fix): jest error in rspack-dev-server

crates/node_binding/binding.d.ts, crates/rspack_binding_options/src/options/raw_entry.rs, crates/rspack_core/src/build_chunk_graph/code_splitter.rs, crates/rspack_core/src/chunk_group.rs, crates/rspack_plugin_mf/src/container/container_plugin.rs, packages/rspack-test-tools/tests/configCases/builtins/entry-plugin-filename-function/a.js, packages/rspack-test-tools/tests/configCases/builtins/entry-plugin-filename-function/index.js, packages/rspack-test-tools/tests/configCases/builtins/entry-plugin-filename-function/rspack.config.js, packages/rspack-test-tools/tests/configCases/builtins/entry-plugin-filename-function/test.config.js, packages/rspack-test-tools/tests/configCases/builtins/entry-plugin-filename-string/a.js, packages/rspack-test-tools/tests/configCases/builtins/entry-plugin-filename-string/index.js, packages/rspack-test-tools/tests/configCases/builtins/entry-plugin-filename-string/rspack.config.js, packages/rspack-test-tools/tests/configCases/builtins/entry-plugin-filename-string/test.config.js, packages/rspack/etc/api.md, packages/rspack/src/builtin-plugin/EntryPlugin.ts, packages/rspack/src/config/zod.ts, website/components/PluginSupportStatusTable.tsx
Allow EntryPlugin filename configuration to be a function.
fix https://github.com/web-infra-dev/rspack/issues/5971
Related PR: https://github.com/web-infra-dev/rspack/pull/6607
=> feat: support EntryPlugin filename function 

crates/rspack_core/src/concatenated_module.rs, packages/rspack-test-tools/etc/api.md, packages/rspack-test-tools/src/case/diff.ts, packages/rspack-test-tools/src/compare/compare.ts, packages/rspack-test-tools/src/helper/parse-modules.ts, packages/rspack-test-tools/src/plugin/rspack-diff-config-plugin.ts, packages/rspack-test-tools/src/plugin/webpack-diff-config-plugin.ts, packages/rspack-test-tools/src/processor/diff.ts, packages/rspack-test-tools/tests/hookCases/normalModuleFactory#afterResolve/request/output.snap.txt, packages/rspack-test-tools/tests/hookCases/normalModuleFactory#afterResolve/resource/output.snap.txt, packages/rspack-test-tools/tests/hookCases/normalModuleFactory#resolve/resource/output.snap.txt, packages/rspack-test-tools/tests/runtimeDiffCases/module-interop/interop-test/rspack.config.js, packages/rspack-test-tools/tests/runtimeDiffCases/module-interop/interop-test/webpack.config.js, packages/rspack-test-tools/tests/runtimeDiffCases/scope-hoisting/runtime-condition/a.mjs, packages/rspack-test-tools/tests/runtimeDiffCases/scope-hoisting/runtime-condition/b.mjs, packages/rspack-test-tools/tests/runtimeDiffCases/scope-hoisting/runtime-condition/package.json, packages/rspack-test-tools/tests/runtimeDiffCases/scope-hoisting/runtime-condition/rspack.config.js, packages/rspack-test-tools/tests/runtimeDiffCases/scope-hoisting/runtime-condition/shared.mjs, packages/rspack-test-tools/tests/runtimeDiffCases/scope-hoisting/runtime-condition/test.config.js, packages/rspack-test-tools/tests/runtimeDiffCases/scope-hoisting/runtime-condition/utils.cjs, packages/rspack-test-tools/tests/runtimeDiffCases/scope-hoisting/runtime-condition/value.mjs, packages/rspack-test-tools/tests/runtimeDiffCases/scope-hoisting/runtime-condition/webpack.config.js, tests/webpack-test/__snapshots__/StatsTestCases.basictest.js.snap
add diff test case of concatenated runtime condition
=> test: add diff test case of concatenated runtime condition

.github/workflows/reusable-build.yml
=> chore(ci): fix ci wrong

.github/FUNDING.yml
show open-collective button in rspack repo, we can donate all we get to contributors and upstream projects.
=> chore: add funding page

website/docs/en/config/dev-server.mdx, website/docs/zh/config/dev-server.mdx
add tips for updating webpack-dev-server v5
😂 document has already been migrated to v5 before implementation by @SyMind, lol
=> docs(devServer): update webpack-dev-server v5

Cargo.lock, Cargo.toml, crates/rspack_regex/Cargo.toml
renovate is not supporting nightly rust now, so I open a pr manually
https://github.com/web-infra-dev/rspack/pull/6596
=> chore(deps): crates update

website/components/CommunityCompatibleTable.tsx
add `serwist` to the list of compatible plugins for `Rspack`.
compatibility was fixed in the following PR: https://github.com/serwist/serwist/pull/166
=> docs: add `serwist` in community compatibility table

website/components/Collapse.tsx
import antd on demand to avoid kill process slowly.
=> docs: import antd on demand

website/docs/en/api/plugin-api/compilation-hooks.mdx
=> docs: bad symbol in compilation-hooks.mdx

.typos.toml, biome.jsonc
=> chore(infra/biome): switch the biome.jsonc to "off"

website/docs/en/config/experiments.mdx, website/docs/en/plugins/rspack/css-extract-rspack-plugin.mdx, website/docs/zh/config/experiments.mdx, website/docs/zh/plugins/rspack/css-extract-rspack-plugin.mdx
- Improve the document of CssExtractRspackPlugin, adjusted the order of content.
- Fix the default value of `experiments.css`.
Our CSS documents are outdated, I will send several PRs to improve it. See https://github.com/web-infra-dev/rspack/issues/7358
=> docs: improve CssExtractRspackPlugin

packages/rspack/etc/api.md, packages/rspack/src/builtin-plugin/LightningCssMiminizerRspackPlugin.ts
Remove `test`, `exclude`, and `include` from `LightningCssMinimizerRspackPluginOptions`.
These fields already have the type `string | RegExp | (string | RegExp)[]`. Adding another intersection type is unnecessary and incorrect.
Before this change:
```ts
type MinifyCondition = string | RegExp;
type MinifyConditions = MinifyCondition | MinifyCondition[];
type LightningCssMinimizerRspackPluginOptions = {
errorRecovery?: boolean | undefined;
unusedSymbols?: string[] | undefined;
removeUnusedLocalIdents?: boolean | undefined;
browserslist?: string[] | undefined;
test?: ((string | RegExp | (string | RegExp)[]) & MinifyConditions) | undefined;
include?: ((string | RegExp | (string | RegExp)[]) & MinifyConditions) | undefined;
exclude?: ((string | RegExp | (string | RegExp)[]) & MinifyConditions) …
```
=> fix: remove nonsensical intersection types

website/docs/en/api/objects/_meta.json, website/docs/en/api/objects/logger.mdx, website/docs/en/types/logger.mdx, website/docs/zh/api/objects/_meta.json, website/docs/zh/api/objects/logger.mdx, website/docs/zh/types/logger.mdx
=> docs: add Logger API

packages/rspack/src/lib/Dependency.ts, packages/rspack/src/lib/formatLocation.ts
=> refactor(typescript): packages/rspack/src/lib/formatLocation

website/docs/en/contribute/development/profiling.md, website/docs/en/guide/optimization/analysis.mdx, website/docs/en/guide/optimization/profile.mdx, website/docs/en/guide/optimization/use-rsdoctor.mdx, website/docs/zh/contribute/development/profiling.md, website/docs/zh/guide/optimization/analysis.mdx, website/docs/zh/guide/optimization/profile.mdx, website/docs/zh/guide/optimization/use-rsdoctor.mdx, website/project-words.txt
chore(docs): add Rsdoctor documents.
=> docs: add Rsdoctor documents

website/docs/en/guide/tech/_meta.json, website/docs/en/guide/tech/html.mdx, website/docs/zh/guide/tech/_meta.json, website/docs/zh/guide/tech/html.mdx
=> docs: add doc for html

packages/rspack/etc/api.md, packages/rspack/src/builtin-plugin/EnableChunkLoadingPlugin.ts, packages/rspack/src/builtin-plugin/EnableWasmLoadingPlugin.ts
=> refactor(typescript): packages/rspack/src/builtin-plugin

packages/rspack/src/util/memoize.ts
=> refactor(typescript): packages/rspack/src/util/memoize

packages/rspack/src/util/webpack.ts
=> refactor(typescript): packages/rspack/src/util/webpack

biome.jsonc, packages/rspack/src/rspackOptionsApply.ts
=> chore(infra/biome): enable noUselessTernary

biome.jsonc, packages/rspack-dev-server/src/ansiHTML.ts, packages/rspack-test-tools/src/helper/update-snapshot.ts, packages/rspack-test-tools/src/processor/hot-step.ts, packages/rspack-test-tools/src/runner/hot-step.ts, packages/rspack-test-tools/src/runner/hot.ts, packages/rspack-test-tools/tests/hotCases/css/recovery/__snapshots__/web/2.snap.txt, packages/rspack-test-tools/viewer/pages/diff-report.tsx, packages/rspack/src/Compiler.ts, packages/rspack/src/builtin-plugin/css-extract/hmr/hotModuleReplacement.ts, packages/rspack/src/builtin-plugin/css-extract/hmr/normalizeUrl.ts, packages/rspack/src/loader-runner/index.ts, packages/rspack/src/loader-runner/loadLoader.ts, tests/plugin-test/css-extract/cases/hmr-locals/expected/main.js, tests/plugin-test/css-extract/cases/hmr/expected/main.js
https://github.com/web-infra-dev/rspack/issues/7182
=> chore(infra/biome): enable noVar

.github/workflows/reusable-build.yml
=> ci: git clean exclude

.github/workflows/reusable-build.yml
fix: other git clean command wrong
=> fix: other git clean command wrong

packages/rspack/src/Stats.ts
fix: stats perf degradation in hmr
=> fix: stats perf degradation in hmr

CONTRIBUTING.md, website/docs/en/contribute/index.mdx
=> docs: grammar fix

crates/rspack_loader_lightningcss/src/config.rs
closes https://github.com/web-infra-dev/rspack/issues/7399
=> fix(rspack_loader_lightningcss): customMedia camelCase option

tests/webpack-test/__snapshots__/ConfigTestCases.basictest.js.snap, tests/webpack-test/configCases/chunk-index/order-multiple-entries/test.filter.js, tests/webpack-test/configCases/css/basic-initial-only/test.filter.js, tests/webpack-test/configCases/css/basic/test.filter.js, tests/webpack-test/configCases/css/conflicting-order/test.filter.js, tests/webpack-test/configCases/css/conflicting-order/webpack.config.js, tests/webpack-test/configCases/css/css-modules-in-node/test.filter.js, tests/webpack-test/configCases/css/css-modules/test.filter.js, tests/webpack-test/configCases/css/exports-in-node/test.filter.js, tests/webpack-test/configCases/css/exports/test.filter.js, tests/webpack-test/configCases/css/external/test.filter.js, tests/webpack-test/configCases/css/large/index.js, tests/webpack-test/configCases/css/large/test.filter.js, tests/webpack-test/configCases/css/urls/test.filter.js, tests/webpack-test/helpers/FakeDocument.js
=> test: enable more webpack-tests

.github/workflows/reusable-build.yml
=> ci: fix git clean wrong by filename too long

crates/rspack_core/src/compiler/compilation.rs
Recheck entry should called before finish_modules hook, to ensure provided exports effects on new added modules (add by add_entry in finish_make).
=> fix: provided exports for add entry modules

packages/rspack-test-tools/tests/errorCases/error-test-push.js, packages/rspack-test-tools/tests/errorCases/error-test-shift.js, packages/rspack-test-tools/tests/errorCases/error-test-splice-1.js, packages/rspack-test-tools/tests/errorCases/error-test-splice-2.js, packages/rspack-test-tools/tests/errorCases/warning-test-push.js, packages/rspack-test-tools/tests/errorCases/warning-test-shift.js, packages/rspack-test-tools/tests/errorCases/warning-test-splice-1.js, packages/rspack-test-tools/tests/errorCases/warning-test-splice-2.js, packages/rspack/etc/api.md, packages/rspack/src/Compiler.ts
Add `compiler.rspack`, just same as `compiler.webpack`
=> feat: add `compiler.rspack`

website/components/Collapse.scss, website/docs/en/api/javascript-api/_meta.json, website/docs/en/api/javascript-api/stats.mdx, website/docs/en/types/stats.mdx, website/docs/zh/api/javascript-api/_meta.json, website/docs/zh/api/javascript-api/stats.mdx, website/docs/zh/types/stats.mdx
=> docs: add Stats API

crates/rspack_core/src/options/module.rs, crates/rspack_core/src/utils/module_rules.rs
Before: 
```
`resource_path` -> `into_owned` -> `String` (allocation +1)
```
After:
```
`resource_path` -- valid UTF-8 -->  `Cow<'s, str>` (no allocation)
-- invalid UTF-8 -> `Cow<'s, str>` (allocation +1)
```
=> perf: rule matcher allocates only if `resource_path` is not a valid UTF-8 sequence

website/docs/en/api/javascript-api/index.mdx, website/docs/zh/api/javascript-api/index.mdx
- Remove duplicated part in document of JavaScript API
=> docs: remove duplicated part in document of JavaScript API

website/package.json, website/pnpm-lock.yaml
bump `@rstack-dev/doc-ui` to add Rslib and awesome Rspack
=> docs: bump `@rstack-dev/doc-ui` to add Rslib and awesome Rspack

.github/workflows/ci.yml, deny.toml
- fix this error https://github.com/web-infra-dev/rspack/actions/runs/10247801425/job/28347733633?pr=7444#step:5:19
- use a fixed version cargo-deny
=> fix: update deny.toml

packages/rspack-test-tools/tests/configCases/container-1-5/provide-sharing-extra-data/index.js, packages/rspack-test-tools/tests/configCases/container-1-5/provide-sharing-extra-data/rspack.config.js
=> chore: remove log in mf test

website/docs/en/config/optimization.mdx, website/docs/zh/config/optimization.mdx
the performance issue is already fixed by #6749
=> docs: remove perf note for mergeDuplicateChunks

website/docs/en/config/optimization.mdx, website/docs/zh/config/optimization.mdx
Explain the usage of InnerGraph by an example
=> docs: explain usage of inner graph

crates/rspack_core/src/chunk_graph/chunk_graph_module.rs, crates/rspack_core/src/concatenated_module.rs, crates/rspack_core/src/context_module.rs, crates/rspack_core/src/module_graph/module.rs, crates/rspack_core/src/stats.rs, crates/rspack_ids/src/id_helpers.rs, crates/rspack_plugin_css/src/parser_and_generator/mod.rs, crates/rspack_plugin_devtool/src/module_filename_helpers.rs, crates/rspack_plugin_javascript/src/dependency/commonjs/module_decorator_dependency.rs, crates/rspack_plugin_javascript/src/runtime.rs, crates/rspack_plugin_mf/src/container/fallback_module.rs, crates/rspack_plugin_mf/src/container/remote_module.rs, crates/rspack_plugin_mf/src/container/remote_runtime_module.rs, crates/rspack_plugin_mf/src/sharing/consume_shared_runtime_module.rs, crates/rspack_plugin_runtime/src/helpers.rs, packages/rspack-test-tools/tests/configCases/entry/dynamic-entry-layer/index.js, packages/rspack-test-tools/tests/configCases/entry/dynamic-entry-layer/rspack.config.js, packages/rspack/etc/api.md, packages/rspack/src/builtin-plugin/DynamicEntryPlugin.ts, packages/rspack/src/config/zod.ts
- fix DynamicEntryPlugin descriptionToOptions
- refactor get_module_id returns Option<&str>
=> fix: dynamic entry plugin desc to options

packages/rspack-test-tools/etc/api.md, packages/rspack-test-tools/src/processor/error.ts, packages/rspack/etc/api.md, packages/rspack/src/Stats.ts, packages/rspack/src/exports.ts, packages/rspack/src/stats/statsFactoryUtils.ts
Fix: #7449
Explicitly define the TypeScript types related to `Stats` to avoid type definition errors.
=> fix: stats typescript wrong

website/docs/en/api/plugin-api/normal-module-factory-hooks.mdx, website/docs/zh/api/plugin-api/normal-module-factory-hooks.mdx
Add detailed explanation for NormalModuleFactory hooks, some content is written via GPT.
=> docs: add detailed explanation for NormalModuleFactory hooks

crates/rspack_plugin_javascript/src/webpack_comment.rs, packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/magic_comment_warning/index.js, packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/magic_comment_warning/stats.err, tests/webpack-test/__snapshots__/StatsTestCases.basictest.js.snap
Magic comment diagnostics are now more precise.
=> feat(diagnostic): prettier diagnostics of magic comments

website/components/property-type.tsx, website/docs/en/config/stats.mdx, website/docs/zh/config/stats.mdx
Update documents of stats options
=> docs: update stats options

website/components/CommunityCompatibleTable.tsx, website/components/i18n/en.json, website/components/i18n/zh.json
=> docs: list plugin compatible +5

website/components/CommunityCompatibleTable.tsx, website/components/i18n/en.json, website/components/i18n/zh.json
list plugin compatible +3
- critters-webpack-plugin. NotCompatible
- @loadable/webpack-plugin. Compatible
- html-webpack-tags-plugin. PartiallyCompatible
=> docs: list compatibility status of more plugins

website/docs/en/guide/optimization/code-splitting.mdx
=> docs: fix website error

Cargo.toml, justfile
add justfile recipe for release rust crates
=> chore: increase publish limitation

website/docs/en/guide/start/quick-start.mdx, website/docs/zh/guide/start/quick-start.mdx
Add a simple guide for MarsCode to the online examples section.
=> docs: add MarsCode to online examples

website/theme/components/Benchmark/index.tsx
Update benchmark data, update all packages to the latest version.
https://github.com/rspack-contrib/performance-compare/commit/ad57e88cb96a0fdf64882d650d04acab5295ede2
=> docs: update benchmark data

website/docs/en/config/optimization.mdx, website/docs/zh/config/optimization.mdx
correct LightningCssMinimizerRspackPlugin link
=> docs: correct LightningCssMinimizerRspackPlugin link

website/docs/en/types/chunk.mdx, website/docs/zh/types/chunk.mdx
=> docs: update chunk type

crates/rspack_binding_options/src/options/raw_devtool.rs, packages/rspack-test-tools/tests/configCases/source-map/plugin-defaults/App.jsx, packages/rspack-test-tools/tests/configCases/source-map/plugin-defaults/index.js, packages/rspack-test-tools/tests/configCases/source-map/plugin-defaults/rspack.config.js
=> fix: source map plugin module should enable by default

website/components/CommunityCompatibleTable.tsx, website/components/i18n/en.json, website/components/i18n/zh.json, website/project-words.txt
Currently, rspack is compatible with 35 of the top 50 most commonly community plugins, or offers alternatives.
=> docs: list top50 plugins compatibility

website/docs/en/guide/features/module-federation.mdx, website/docs/zh/guide/features/module-federation.mdx
- docs(module-federation): optimize module federation version selection
=> docs(module-federation): optimize module federation version selection

packages/rspack/etc/api.md, packages/rspack/src/NormalModule.ts, packages/rspack/src/loader-runner/index.ts
feat: second param for loader hook
=> feat: second param for loader hook

website/components/Columns.tsx, website/components/Mermaid.scss, website/docs/en/api/plugin-api/compilation-hooks.mdx, website/docs/en/config/optimization.mdx, website/docs/zh/api/plugin-api/compilation-hooks.mdx, website/docs/zh/config/optimization.mdx
Add flow chart for compilation hooks
=> docs: add overview flow chart for compilation hooks

website/docs/en/config/output.mdx, website/docs/en/guide/features/builtin-swc-loader.mdx, website/docs/en/guide/features/module-federation.mdx, website/docs/en/plugins/webpack/module-federation-plugin-v1.mdx, website/docs/en/plugins/webpack/module-federation-plugin.mdx, website/docs/zh/config/output.mdx, website/docs/zh/guide/features/module-federation.mdx, website/docs/zh/plugins/webpack/module-federation-plugin-v1.mdx, website/docs/zh/plugins/webpack/module-federation-plugin.mdx
some of options are already stable, so remove the experimental tips
=> docs: remove experiments flags

packages/rspack-test-tools/tests/__snapshots__/StatsOutput.test.js.snap, packages/rspack-test-tools/tests/configCases/output/library-truthy/index.js, packages/rspack-test-tools/tests/configCases/output/library-truthy/rspack.config.js, packages/rspack-test-tools/tests/configCases/output/library-undefined/index.js, packages/rspack-test-tools/tests/configCases/output/library-undefined/rspack.config.js, packages/rspack-test-tools/tests/defaultsCases/library/library.js, packages/rspack-test-tools/tests/defaultsCases/library/name-placeholder.js, packages/rspack-test-tools/tests/defaultsCases/library/name-root-placeholder.js, packages/rspack-test-tools/tests/defaultsCases/library/placeholder.js, packages/rspack-test-tools/tests/defaultsCases/library/root-placeholder.js, packages/rspack/src/config/defaults.ts
fix #7563, don't inject bundlerInfo in library mode
=> feat(core): don't inject bundlerInfo in library mode

website/docs/en/guide/optimization/tree-shaking.mdx, website/docs/zh/guide/optimization/tree-shaking.mdx
rewrite tree-shaking doc, make it more clear, and introduce each tree shaking configuration by examples
=> docs: rewrite tree-shaking doc

crates/rspack_plugin_warn_sensitive_module/Cargo.toml
=> chore: fix version in case sensitive plugin

Cargo.lock, crates/rspack_core/Cargo.toml, crates/rspack_core/src/resolver/resolver_impl.rs
https://github.com/web-infra-dev/rspack-resolver/pull/15
=> feat(core): bump rspack_resolver 0.2.0

Cargo.lock, crates/rspack_plugin_javascript/Cargo.toml, crates/rspack_plugin_javascript/src/plugin/side_effects_flag_plugin.rs
=> chore(rspack_plugin_javascript): bump fast-glob 0.4.0

website/components/CommunityCompatibleTable.tsx, website/components/i18n/en.json, website/components/i18n/zh.json
https://github.com/web-infra-dev/rspack/issues/6432
=> docs: update eslint-webpack-plugin compatible status

website/docs/en/contribute/development/testing-rspack.mdx, website/docs/zh/contribute/development/testing-rspack.mdx
add example about how to filter rspack specific test cases.
=> docs: filter rspack specific test cases

crates/rspack_core/src/resolver/resolver_impl.rs
we only have one resolver implementation now so it's unnecessary to use enum to wrap resolver
=> refactor(core): remove unnecessary enum for resolver

website/docs/en/guide/migration/_meta.json, website/docs/en/guide/migration/rspack_0.x.mdx, website/docs/zh/guide/migration/_meta.json, website/docs/zh/guide/migration/rspack_0.x.mdx
docs: migrating from rspack 0.x
=> docs: migrating from rspack 0.x

crates/rspack_plugin_javascript/src/dependency/commonjs/common_js_full_require_dependency.rs, crates/rspack_plugin_javascript/src/parser_plugin/common_js_imports_parse_plugin.rs, crates/rspack_plugin_javascript/src/visitors/dependency/util.rs
=> refactor: remove extra CommonJs dependency locations

packages/rspack/package.json, pnpm-lock.yaml
Bump @module-federation/runtime-tools to the latest version before releasing Rspack 1.0.
See: https://github.com/module-federation/core/releases
=> feat(deps): bump @module-federation/runtime-tools 0.5.1

crates/rspack_plugin_javascript/src/visitors/dependency/parser/walk.rs, tests/webpack-test/cases/parsing/sequence-expression-asi/a.js, tests/webpack-test/cases/parsing/sequence-expression-asi/index.js
Synced with webpack: https://github.com/webpack/webpack/pull/18699
=> fix: unexpected ASI generation with sequence expression

website/docs/en/config/index.mdx, website/docs/zh/config/index.mdx
add guide about use `experimental-transform-types` to load config
=> docs: use --experimental-transform-types load tsconfig

crates/rspack_plugin_library/src/umd_library_plugin.rs, packages/rspack-test-tools/tests/configCases/externals/umd-array-externals/index.js, packages/rspack-test-tools/tests/configCases/externals/umd-array-externals/rspack.config.js, packages/rspack-test-tools/tests/configCases/externals/umd-array-externals/test.config.js
=> fix: resolve issue with external array not working in UMD libraryTarget

packages/rspack-cli/package.json
allow @rspack/cli peerDep  match @rspack/core@1.0.0
=> fix(cli): peerDep allows @rspack/core@1.0

crates/rspack_core/src/compiler/hmr.rs
=> fix: reuse codegen results only for new incremental

Cargo.lock, crates/rspack_core/Cargo.toml, crates/rspack_core/src/resolver/resolver_impl.rs, packages/rspack-test-tools/tests/configCases/resolve/main-field-fallback/index.js, packages/rspack-test-tools/tests/configCases/resolve/main-field-fallback/node_modules/invalid-pkg/exist.js, packages/rspack-test-tools/tests/configCases/resolve/main-field-fallback/node_modules/invalid-pkg/package.json, packages/rspack-test-tools/tests/configCases/resolve/main-field-fallback/rspack.config.js
fix https://github.com/web-infra-dev/rspack/issues/7665
- should fallback to next main field when resolve failed
- remove pnp feature of resolver, it is not used yet
related https://github.com/web-infra-dev/rspack-resolver/pull/17
=> fix: fallback to next main field when resolve failed

crates/node_binding/package.json, npm/darwin-arm64/package.json, npm/darwin-x64/package.json, npm/linux-x64-gnu/package.json, npm/win32-x64-msvc/package.json, package.json, packages/create-rspack/package.json, packages/rspack-cli/package.json, packages/rspack-dev-server/package.json, packages/rspack-test-tools/package.json, packages/rspack/package.json
* feat: cache unaffected for cgm code gen by @ahabhgk in https://github.com/web-infra-dev/rspack/pull/7646
* fix: should resolve aliased loader module with query by @h-a-n-a in https://github.com/web-infra-dev/rspack/pull/7660
* fix: `Path` pitfall for loader type by @h-a-n-a in https://github.com/web-infra-dev/rspack/pull/7666
* fix(security): DOM clobbering in auto public path by @LingyuCoder in https://github.com/web-infra-dev/rspack/pull/7664
* fix: resolve issue with external array not working in UMD libraryTarget by @inottn in https://github.com/web-infra-dev/rspack/pull/7675
* fix(deps): bump webpack-dev-middleware v7.4.2 to fix assetsInfo by @chenjiahan in https://github.com/web-infra-dev/rspack/pull/7676
* fix(create-rspack): should not replace plugin-react-refresh version by …
=> release: 1.0.0-rc.1

website/theme/components/Landingpage/FullyFeatured/index.module.scss, website/theme/components/Landingpage/FullyFeatured/index.tsx, website/theme/i18n/enUS.ts, website/theme/i18n/zhCN.ts
=> docs(landingpage): remove "show all features" button

website/theme/components/Landingpage/FullyFeatured/index.module.scss, website/theme/components/Landingpage/WhyRspack/index.module.scss, website/theme/components/Landingpage/WhyRspack/index.tsx, website/theme/components/Landingpage/shared.module.scss
=> docs(landingpage): fix the section width

website/theme/components/Landingpage/Hero/BackgroundStar.tsx, website/theme/components/Landingpage/Hero/index.module.scss, website/theme/components/Landingpage/Hero/index.tsx
=> docs(landingpage): add star animation

website/theme/components/Landingpage/Benchmark/index.module.scss, website/theme/components/Landingpage/FullyFeatured/index.tsx, website/theme/components/Landingpage/Hero/index.module.scss, website/theme/components/Landingpage/ToolStack/index.module.scss, website/theme/components/Landingpage/WhyRspack/index.module.scss, website/theme/components/Landingpage/WhyRspack/useCardAnimation.tsx, website/theme/components/Landingpage/shared.module.scss
Including several small changes:
- fix hero button vertical align
- make the hero card border lighter
- reduce hero card font size
- improve tools card padding and font-size
- fix multi compiler link
- increase sections margin
- add button active feedback
- reduce hero card scale
- reduce card shine color
- improve hero card background color
=> docs(landingpage): UI improvements

website/theme/components/Landingpage/Hero/index.module.scss
=> docs(landingpage): fix center button text

packages/rspack-cli/jest.config.js, packages/rspack-cli/src/cli.ts, packages/rspack-cli/src/commands/preview.ts, packages/rspack-cli/tests/build/config/config.test.ts, packages/rspack-cli/tests/build/config/loose-unrecognized-keys-other-error/rspack.config.js, packages/rspack-cli/tests/build/config/loose-unrecognized-keys/rspack.config.js, packages/rspack-test-tools/tests/Validation.test.js, packages/rspack/package.json, packages/rspack/src/util/validate.ts, pnpm-lock.yaml
Support `"loose-unrecognized-keys"` for `RSPACK_CONFIG_VALIDATE`.
- `"loose-silent"`: ignore every config validation errors
- `"loose"`: warn every config validation errors
- `"loose-unrecognized-keys"`: only warn unrecognized keys(this is for compatibility for webpack configs) and treat other errors as `"strict"` mode does.
- `"strict"`: return every config validation errors
There's no breaking changes in this PR: `"loose"` is the default value of `RSPACK_CONFIG_VALIDATE` in rspack-cli. `"strict"` is the default value for calling compiler programmatically.
=> feat: support `"loose-unrecognized-keys"` for config validation

website/docs/en/config/dev-server.mdx, website/docs/zh/config/dev-server.mdx
=> docs: fix type of `devServer.hot`

crates/rspack_plugin_javascript/src/dependency/hmr/harmony_accept_dependency.rs, crates/rspack_plugin_javascript/src/parser_plugin/hot_module_replacement_plugin.rs
=> refactor: improve HarmonyAcceptDependency

crates/rspack_core/src/dependency/dependency_location.rs, crates/rspack_plugin_css/src/dependency/compose.rs, crates/rspack_plugin_css/src/dependency/import.rs, crates/rspack_plugin_css/src/dependency/url.rs, crates/rspack_plugin_css/src/parser_and_generator/mod.rs, crates/rspack_plugin_javascript/src/dependency/commonjs/common_js_export_require_dependency.rs, crates/rspack_plugin_javascript/src/dependency/commonjs/require_resolve_dependency.rs, crates/rspack_plugin_javascript/src/dependency/context/common_js_require_context_dependency.rs, crates/rspack_plugin_javascript/src/dependency/context/import_context_dependency.rs, crates/rspack_plugin_javascript/src/dependency/context/import_meta_context_dependency.rs, crates/rspack_plugin_javascript/src/dependency/context/require_context_dependency.rs, crates/rspack_plugin_javascript/src/dependency/esm/import_dependency.rs, crates/rspack_plugin_javascript/src/dependency/esm/import_eager_dependency.rs, crates/rspack_plugin_javascript/src/dependency/hmr/import_meta_hot_accept.rs, crates/rspack_plugin_javascript/src/dependency/hmr/import_meta_hot_decline.rs, crates/rspack_plugin_javascript/src/dependency/hmr/module_hot_accept.rs, crates/rspack_plugin_javascript/src/dependency/hmr/module_hot_decline.rs, crates/rspack_plugin_javascript/src/dependency/module_argument_dependency.rs, crates/rspack_plugin_javascript/src/dependency/url/mod.rs, crates/rspack_plugin_javascript/src/dependency/worker/mod.rs, crates/rspack_plugin_javascript/src/parser_plugin/api_plugin.rs, crates/rspack_plugin_javascript/src/parser_plugin/common_js_exports_parse_plugin.rs, crates/rspack_plugin_javascript/src/parser_plugin/common_js_imports_parse_plugin.rs, crates/rspack_plugin_javascript/src/parser_plugin/hot_module_replacement_plugin.rs, crates/rspack_plugin_javascript/src/parser_plugin/import_meta_context_dependency_parser_plugin.rs, crates/rspack_plugin_javascript/src/parser_plugin/import_parser_plugin.rs, crates/rspack_plugin_javascript/src/parser_plugin/require_context_dependency_parser_plugin.rs, crates/rspack_plugin_javascript/src/parser_plugin/url_plugin.rs, crates/rspack_plugin_javascript/src/parser_plugin/worker_plugin.rs, crates/rspack_plugin_wasm/src/dependency/wasm_import_dependency.rs
=> refactor: remove ErrorSpan in dependencies

packages/rspack-cli/src/commands/serve.ts, packages/rspack-cli/tests/serve/flags/rspack.config.js, packages/rspack-cli/tests/serve/flags/serve-flags.test.ts, packages/rspack-cli/tests/serve/flags/src/index.js
=> feat(rspack-cli): support more flags for command serve

packages/create-rspack/template-react-js/src/App.css, packages/create-rspack/template-react-ts/src/App.css
The react logo in the react-template animation was not working because of wrong CSS 
Now it is fixed and the logo animation works.
=> fix: template react logo animation css selector

website/docs/en/config/module.mdx, website/docs/zh/config/module.mdx
=> docs: correct asset generator filename property type

website/docs/en/config/experiments.mdx, website/docs/zh/config/experiments.mdx
=> docs: disable bundler info injection by set `force: false`

crates/rspack_plugin_css/src/dependency/local_ident.rs, crates/rspack_plugin_css/src/parser_and_generator/mod.rs, crates/rspack_plugin_css/src/utils.rs, packages/rspack-test-tools/tests/__snapshots__/Config.test.js.snap, packages/rspack-test-tools/tests/configCases/css/escape-ident/index.js, packages/rspack-test-tools/tests/configCases/css/escape-ident/index.module.css, packages/rspack-test-tools/tests/configCases/css/escape-ident/rspack.config.js
=> fix: escape css ident

crates/rspack_plugin_javascript/src/parser_plugin/harmony_export_dependency_parser_plugin.rs, crates/rspack_plugin_javascript/src/visitors/dependency/parser/mod.rs, tests/webpack-test/cases/parsing/harmony-export-import-specifier-asi/a.js, tests/webpack-test/cases/parsing/harmony-export-import-specifier-asi/index.js, tests/webpack-test/cases/parsing/harmony-export-specifier-asi/a.js, tests/webpack-test/cases/parsing/harmony-export-specifier-asi/index.js
port https://github.com/webpack/webpack/pull/18683
=> fix: handle ASI for export declaration

website/package.json, website/pnpm-lock.yaml
https://github.com/web-infra-dev/rspack/pull/7771
https://github.com/web-infra-dev/rsbuild/pull/3349
https://github.com/web-infra-dev/rspress/pull/1384
https://github.com/web-infra-dev/rsdoctor/pull/497
=> docs(deps): upgrade @rstack-dev/doc-ui 1.4.2

website/docs/en/guide/features/asset-module.mdx, website/docs/zh/guide/features/asset-module.mdx
修复使用 Optimizer Loader中的代码片段和下面的说明不一致的问题
=> docs: Update asset-module.mdx

website/docs/zh/blog/announcing-0-6.mdx
=> docs: fix migrate-from-builtins.css example codes

crates/node_binding/binding.d.ts, crates/rspack_binding_values/src/chunk_group.rs, packages/rspack-test-tools/tests/configCases/plugins/compilation-chunk-groups/rspack.config.js, packages/rspack/etc/api.md, packages/rspack/src/ChunkGroup.ts, website/docs/en/types/chunk-group.mdx, website/docs/en/types/entrypoint.mdx, website/docs/zh/types/chunk-group.mdx, website/docs/zh/types/entrypoint.mdx
solve https://github.com/web-infra-dev/rspack/issues/7766
> The `origins[].loc` is not supported yet, related to https://github.com/web-infra-dev/rspack/issues/7422
=> feat: support `compilation.chunkGroups[].origins`

crates/rspack_core/src/build_chunk_graph/code_splitter.rs
Improve performance of code-splitting
see following module-graph
if module `other` has a lots of sub modules, we can avoid revisit those modules if minAvailableModules stays the same
module a dyn imports module b, buildChunkGraph will first create chunk a for module a, fills chunk a, then create chunk b for module b, fills chunk b.
if module b has another parent, then chunk b will be outdated and will be visited again, and **fills chunk b again**. But if chunk b has no minAvailableModules changes, we can skip visiting it, as it won't have any differences
see https://github.com/webpack/webpack/pull/18730
=> perf(buildChunkGraph): avoid unneeded visit

crates/rspack_core/src/module_graph/module.rs, crates/rspack_core/src/normal_module.rs
=> chore: cleanup unused module syntax

Cargo.lock, Cargo.toml
Relative: https://github.com/rspack-contrib/storybook-rsbuild/issues/83
=> fix: cheap source map

website/docs/en/plugins/rspack/html-rspack-plugin.mdx, website/docs/zh/plugins/rspack/html-rspack-plugin.mdx, website/project-words.txt
Update the docs of html plugin
=> docs: update html plugin

Cargo.lock, Cargo.toml, packages/rspack-cli/package.json
=> fix: panic when identity mapping with different char indices

Cargo.lock, crates/rspack_core/Cargo.toml, crates/rspack_core/src/resolver/resolver_impl.rs, packages/rspack-test-tools/tests/normalCases/resolve/pnpm-workspace/.gitignore, packages/rspack-test-tools/tests/normalCases/resolve/pnpm-workspace/index.js, packages/rspack-test-tools/tests/normalCases/resolve/pnpm-workspace/package.json, packages/rspack-test-tools/tests/normalCases/resolve/pnpm-workspace/packages/app/index.js, packages/rspack-test-tools/tests/normalCases/resolve/pnpm-workspace/packages/app/package.json, packages/rspack-test-tools/tests/normalCases/resolve/pnpm-workspace/packages/lib/package.json, pnpm-lock.yaml, pnpm-workspace.yaml
bump rspack_resolver to 0.3.1 and Fix recursive resolve symlink in pnpm-workspace
related to https://github.com/web-infra-dev/rspack-resolver/pull/21
=> fix(core): fix resolve faild when do recursive symbol link

website/docs/zh/api/javascript-api/index.mdx
=> docs: fix typo in zh docs

packages/rspack-test-tools/tests/__snapshots__/StatsOutput.test.js.snap, packages/rspack-test-tools/tests/statsOutputCases/match-resource-data-url/index.js, packages/rspack-test-tools/tests/statsOutputCases/match-resource-data-url/rspack.config.js, packages/rspack/src/stats/DefaultStatsPrinterPlugin.ts
fix https://github.com/web-infra-dev/rspack/issues/7326
=> fix: improve stats string for match resource with long data url

crates/rspack_core/src/concatenated_module.rs, crates/rspack_core/src/context_module_factory.rs, crates/rspack_core/src/dependency/dependency_trait.rs, crates/rspack_core/src/dependency/module_dependency.rs, crates/rspack_plugin_css/src/dependency/compose.rs, crates/rspack_plugin_css/src/dependency/import.rs, crates/rspack_plugin_css/src/dependency/url.rs, crates/rspack_plugin_extract_css/src/css_dependency.rs, crates/rspack_plugin_extract_css/src/parser_plugin.rs, crates/rspack_plugin_javascript/src/dependency/commonjs/common_js_full_require_dependency.rs, crates/rspack_plugin_javascript/src/dependency/commonjs/common_js_require_dependency.rs, crates/rspack_plugin_javascript/src/dependency/commonjs/require_resolve_dependency.rs, crates/rspack_plugin_javascript/src/dependency/context/common_js_require_context_dependency.rs, crates/rspack_plugin_javascript/src/dependency/context/import_context_dependency.rs, crates/rspack_plugin_javascript/src/dependency/context/import_meta_context_dependency.rs, crates/rspack_plugin_javascript/src/dependency/context/require_context_dependency.rs, crates/rspack_plugin_javascript/src/dependency/esm/harmony_export_imported_specifier_dependency.rs, crates/rspack_plugin_javascript/src/dependency/esm/harmony_import_dependency.rs, crates/rspack_plugin_javascript/src/dependency/esm/harmony_import_specifier_dependency.rs, crates/rspack_plugin_javascript/src/dependency/esm/import_dependency.rs, crates/rspack_plugin_javascript/src/dependency/esm/import_eager_dependency.rs, crates/rspack_plugin_javascript/src/dependency/esm/provide_dependency.rs, crates/rspack_plugin_javascript/src/dependency/hmr/import_meta_hot_accept.rs, crates/rspack_plugin_javascript/src/dependency/hmr/import_meta_hot_decline.rs, crates/rspack_plugin_javascript/src/dependency/hmr/module_hot_accept.rs, crates/rspack_plugin_javascript/src/dependency/hmr/module_hot_decline.rs, crates/rspack_plugin_javascript/src/dependency/url/mod.rs, crates/rspack_plugin_javascript/src/dependency/worker/mod.rs, crates/rspack_plugin_library/src/modern_module/dependency.rs
=> feat: remove `ErrorSpan` in dependency trait

crates/rspack_plugin_javascript/src/dependency/commonjs/mod.rs, crates/rspack_plugin_javascript/src/dependency/commonjs/require_resolve_dependency.rs, crates/rspack_plugin_javascript/src/dependency/commonjs/require_resolve_header_dependency.rs, crates/rspack_plugin_javascript/src/dependency/context/mod.rs, crates/rspack_plugin_javascript/src/dependency/context/require_resolve_context_dependency.rs, crates/rspack_plugin_javascript/src/parser_plugin/common_js_imports_parse_plugin.rs, packages/rspack-test-tools/tests/__snapshots__/StatsOutput.test.js.snap, tests/webpack-test/cases/chunks/weak-dependencies-context/index.js, tests/webpack-test/cases/chunks/weak-dependencies-context/test.filter.js, tests/webpack-test/cases/parsing/complex-require/cjs.js, tests/webpack-test/cases/parsing/resolve-weak-context/test.filter.js
=> feat: support context for resolve and resolveWeak

biome.jsonc, packages/rspack-cli/src/cli.ts, packages/rspack-dev-server/src/ansiHTML.ts, packages/rspack-dev-server/src/middleware.ts, packages/rspack-test-tools/src/compare/format-code.ts, packages/rspack-test-tools/src/plugin/webpack-module-placeholder-plugin.ts, packages/rspack-test-tools/src/processor/defaults.ts, packages/rspack-test-tools/src/processor/hook.ts, packages/rspack/etc/api.md, packages/rspack/src/MultiCompiler.ts, packages/rspack/src/builtin-plugin/HtmlRspackPlugin.ts, packages/rspack/src/builtin-plugin/css-extract/hmr/hotModuleReplacement.ts, packages/rspack/src/builtin-plugin/css-extract/loader.ts, packages/rspack/src/config/adapterRuleUse.ts, packages/rspack/src/lib/HookWebpackError.ts, packages/rspack/src/lib/cache/getLazyHashedEtag.ts, packages/rspack/src/stats/DefaultStatsPrinterPlugin.ts, packages/rspack/src/stats/statsFactoryUtils.ts, packages/rspack/src/util/IterableHelpers.ts, packages/rspack/src/util/bindingVersionCheck.ts, packages/rspack/src/util/cleverMerge.ts, packages/rspack/src/util/hash/wasm-hash.ts, website/components/builtIns/Table.tsx
=> chore(infra/biome): enable `noImplicitAnyLet` and `noArrayIndexKey` rules

packages/rspack-test-tools/tests/configCases/plugins/compilation-chunk-groups/rspack.config.js, packages/rspack/src/Compilation.ts, packages/rspack/src/util/createReadonlyMap.ts
=> feat: make namedChunkGroups iterable

.github/workflows/reusable-build.yml, packages/rspack-dev-server/jest.config.js
disable dev server cases because they will timeout on github runner
=> ci: disable dev server test cases

.github/workflows/reusable-build.yml
Dev server test can not run on github runner even after installing firefox, so remove it and disable dev server test until this issue is solved
=> ci: remove firefox

website/docs/en/config/module.mdx, website/docs/en/guide/tech/react.mdx, website/docs/zh/config/module.mdx, website/docs/zh/guide/tech/react.mdx
`disableTransformByDefault` has been removed in version 0.x.
=> docs: remove disableTransformByDefault

crates/rspack_loader_preact_refresh/src/lib.rs, crates/rspack_loader_react_refresh/src/lib.rs, packages/rspack-test-tools/package.json, packages/rspack-test-tools/tests/configCases/builtin-swc-loader/preact-refresh/index.jsx, packages/rspack-test-tools/tests/configCases/builtin-swc-loader/preact-refresh/rspack.config.js, packages/rspack-test-tools/tests/configCases/builtin-swc-loader/react-refresh/index.jsx, packages/rspack-test-tools/tests/configCases/builtin-swc-loader/react-refresh/rspack.config.js, pnpm-lock.yaml
=> fix: should forward sourcemaps for refresh loaders

packages/rspack-dev-server/tests/e2e/__snapshots__/api.test.js.snap.webpack5, packages/rspack-dev-server/tests/e2e/api.test.js, packages/rspack-dev-server/tests/e2e/web-socket-server-url.test.js, packages/rspack-dev-server/tests/fixtures/reload-config/main.css
- disable dev-server snapshot cases which is not stable on `rspack-linux-x` runner
=> test: disable unstable dev server snapshot case

crates/node_binding/binding.d.ts, crates/rspack_binding_options/src/options/raw_builtins/raw_progress.rs, crates/rspack_plugin_progress/src/lib.rs, packages/rspack-dev-server/jest.config.js, packages/rspack-dev-server/src/server.ts, packages/rspack/etc/api.md, packages/rspack/src/builtin-plugin/ProgressPlugin.ts
Close https://github.com/web-infra-dev/rspack/issues/7728
- Support custom handler of progress plugin to send progress message to dev server client.
- Added a 200ms interval to module updating events to avoid performance regression.
=> feat(progress-plugin): support custom handler

website/docs/zh/guide/features/builtin-swc-loader.mdx
update how to use swc plugin in rspack rule. `experimental` should be used in `jsc`
=> docs: update how to use swc plugin in rspack rule

website/package.json, website/pnpm-lock.yaml
=> docs(landingpage): update @rstack-dev/doc-ui

crates/rspack_plugin_javascript/src/visitors/dependency/parser/walk.rs, packages/rspack-test-tools/tests/normalCases/parsing/harmony-import-specifier/index.js
=> fix: preserve variable names declared with `var`

packages/rspack-dev-server/jest.config.js
Dont know why CI report errors with code `EMFILE: too many open files`
=> test: disable dev server e2e test

packages/rspack/src/node/NodeEnvironmentPlugin.ts
=> fix: eco-ci prebundled enhanced-resolve

website/docs/en/config/index.mdx, website/docs/zh/config/index.mdx
=> docs: webpack-merge also applies to rspack

crates/node_binding/binding.d.ts, crates/rspack_binding_options/src/options/mod.rs, crates/rspack_binding_options/src/options/raw_experiments.rs, crates/rspack_core/src/compiler/compilation.rs, crates/rspack_core/src/compiler/hmr.rs, crates/rspack_core/src/compiler/mod.rs, crates/rspack_core/src/old_cache/local/code_splitting_cache.rs, crates/rspack_core/src/options/compiler_options.rs, crates/rspack_core/src/options/experiments.rs, crates/rspack_core/src/unaffected_cache/mutations.rs, crates/rspack_plugin_javascript/src/plugin/flag_dependency_exports_plugin.rs, crates/rspack_plugin_javascript/src/plugin/infer_async_modules_plugin.rs, packages/rspack-test-tools/src/case/new-incremental.ts, packages/rspack-test-tools/src/processor/hot-new-incremental.ts, packages/rspack-test-tools/tests/__snapshots__/Defaults.test.js.snap, packages/rspack/etc/api.md, packages/rspack/scripts/check-documentation-coverage.mjs, packages/rspack/src/config/adapter.ts, packages/rspack/src/config/defaults.ts, packages/rspack/src/config/normalization.ts, packages/rspack/src/config/zod.ts
add switcher to enable or disable incremental for compilation phases
=> refactor: phases level switcher for incremental options

packages/playground/package.json, packages/rspack-cli/package.json, pnpm-lock.yaml
1.0.6 is buggy pin to 1.0.5 for hotfix
=> fix(core): ping @rspack/dev-server to 1.0.5

packages/create-rspack/template-vanilla-ts/tsconfig.json
Fix missing tsconfig.json in vanilla-ts template.
=> fix(create-rspack): missing vanilla-ts tsconfig.json

crates/rspack_plugin_progress/src/lib.rs
https://github.com/web-infra-dev/rspack/pull/7989#issuecomment-2375590913
=> fix: the progress values for the make and sealing statuses are inaccurate

crates/rspack_plugin_progress/src/lib.rs
=> fix: correctly display the progress bar when it reaches 100%

crates/rspack_core/Cargo.toml, crates/rspack_core/src/compiler/make/repair/add.rs, crates/rspack_core/src/compiler/make/repair/build.rs, crates/rspack_core/src/compiler/make/repair/factorize.rs, crates/rspack_core/src/compiler/make/repair/process_dependencies.rs, crates/rspack_core/src/compiler/module_executor/ctrl.rs, crates/rspack_core/src/compiler/module_executor/entry.rs, crates/rspack_core/src/compiler/module_executor/execute.rs, crates/rspack_core/src/compiler/module_executor/overwrite.rs, crates/rspack_core/src/utils/task_loop.rs
Reverts web-infra-dev/rspack#7966
=> revert: refactor(core) add task name for tokio-console better display

Cargo.lock, Cargo.toml, crates/rspack_plugin_swc_js_minimizer/src/minify.rs, packages/rspack-test-tools/tests/__snapshots__/StatsOutput.test.js.snap, packages/rspack-test-tools/tests/configCases/parsing/rspack-issue-5120-binding/errors.js, packages/rspack-test-tools/tests/configCases/parsing/rspack-issue-5120-binding/index.js, packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/lexically_name_error/stats.err
=> fix: swc minifier source map

website/components/CommunityCompatibleTable.tsx, website/components/i18n/en.json, website/components/i18n/zh.json, website/docs/en/plugins/webpack/progress-plugin.mdx, website/docs/zh/blog/announcing-1-0.mdx, website/docs/zh/plugins/webpack/progress-plugin.mdx
https://github.com/web-infra-dev/rspack/pull/7896
=> docs(progress-plugin): support custom handler 

.github/workflows/preview-commit.yml
=> chore(ci): skip preview if no relevant code changes

packages/rspack/etc/api.md, packages/rspack/src/config/types.ts, packages/rspack/src/config/zod.ts
- Add type & JSDoc for configuration.resolve 
=> refactor: add JSDoc & types to improve configuration.resolve types.

crates/rspack_core/src/dependency/runtime_template.rs, crates/rspack_core/src/external_module.rs, packages/rspack-test-tools/tests/builtinCases/samples/cycle-entry/__snapshots__/output.snap.txt, packages/rspack-test-tools/tests/builtinCases/samples/self-import/__snapshots__/output.snap.txt, packages/rspack-test-tools/tests/treeShakingCases/webpack-inner-graph-switch/__snapshots__/treeshaking.snap.txt, tests/webpack-test/ConfigTestCases.template.js, tests/webpack-test/configCases/externals/module-import/a.js, tests/webpack-test/configCases/externals/module-import/index.js
Port https://redirect.github.com/webpack/webpack/pull/18790.
=> fix(externals): distinguish "module" and "import" in "module-import"

.github/renovate.json5, .github/workflows/reusable-build.yml, packages/playground/package.json, pnpm-lock.yaml
we need to seperate the playwright  from devDependencies because of the image update
=> chore(deps): update playwright to 1.47.0

Cargo.lock, Cargo.toml
bump swc to 1.0.0 and close #8101 
related change https://github.com/swc-project/swc/compare/swc_core@v0.109.1...swc_core@v1.0.0
=> feat(core): bump swc to 1.0.0

website/package.json, website/pnpm-lock.yaml
https://github.com/web-infra-dev/rspress/pull/1472
=> chore(website/deps): bump 1.33.1

crates/rspack_core/src/options/filename.rs, crates/rspack_core/src/utils/hash.rs, crates/rspack_core/src/utils/runtime.rs
=> feat(rspack_core): use simple string parsing instead of regex

packages/create-rspack/package.json, packages/create-rspack/src/index.ts, packages/create-rspack/tsconfig.json, pnpm-lock.yaml
Bump Rslib 0.0.12 and adjust dirname, Rslib no longer inject shims by default for `__dirname`.
See https://github.com/web-infra-dev/rslib/pull/291
=> chore(create-rspack): bump Rslib 0.0.12 and adjust dirname

website/docs/en/blog/announcing-0-1.mdx, website/docs/en/blog/announcing-0-2.mdx, website/docs/en/blog/announcing-0-3.mdx, website/docs/en/blog/announcing-0-4.mdx, website/docs/en/blog/announcing-0-5.mdx, website/docs/en/blog/announcing-0-6.mdx, website/docs/en/blog/announcing-0-7.mdx, website/docs/en/blog/announcing-1-0-alpha.mdx, website/docs/en/blog/announcing-1-0.mdx, website/docs/en/blog/index.mdx, website/docs/en/blog/module-federation-added-to-rspack.mdx, website/docs/zh/blog/announcing-0-1.mdx, website/docs/zh/blog/announcing-0-2.mdx, website/docs/zh/blog/announcing-0-3.mdx, website/docs/zh/blog/announcing-0-4.mdx, website/docs/zh/blog/announcing-0-5.mdx, website/docs/zh/blog/announcing-0-6.mdx, website/docs/zh/blog/announcing-0-7.mdx, website/docs/zh/blog/announcing-1-0-alpha.mdx, website/docs/zh/blog/announcing-1-0.mdx, website/docs/zh/blog/index.mdx, website/docs/zh/blog/module-federation-added-to-rspack.mdx
=> docs: disable doc blog sidebar

website/components/CommunityCompatibleTable.tsx, website/components/i18n/en.json, website/components/i18n/zh.json
Update plugin compatibility docs
=> docs: add `html-rspack-tags-plugin` as an alternative

crates/rspack_binding_options/src/options/mod.rs, crates/rspack_binding_options/src/options/raw_experiments.rs, crates/rspack_core/src/compiler/compilation.rs, crates/rspack_core/src/compiler/hmr.rs, crates/rspack_core/src/compiler/make/mod.rs, crates/rspack_core/src/compiler/mod.rs, crates/rspack_core/src/compiler/module_executor/mod.rs, crates/rspack_core/src/old_cache/local/code_splitting_cache.rs, crates/rspack_core/src/options/compiler_options.rs, crates/rspack_core/src/options/experiments.rs, crates/rspack_core/src/unaffected_cache/incremental.rs, crates/rspack_core/src/unaffected_cache/mod.rs, crates/rspack_plugin_javascript/src/plugin/flag_dependency_exports_plugin.rs, crates/rspack_plugin_javascript/src/plugin/infer_async_modules_plugin.rs
mutations read write permission from incremental options, avoid direct depend on compiler options inside compilation
=> refactor: mutations read write permission from incremental options

crates/rspack_plugin_javascript/src/parser_plugin/node_stuff_plugin.rs, packages/rspack-test-tools/tests/configCases/parsing/rspack-issue-8170/dir1/dir2/file.js, packages/rspack-test-tools/tests/configCases/parsing/rspack-issue-8170/index.js, packages/rspack-test-tools/tests/configCases/parsing/rspack-issue-8170/rspack.config.js
=> fix: escape node.__dirname

packages/rspack/etc/core.api.md, packages/rspack/src/exports.ts
export `ResolveData` type for user use.
=> feat(types): export `ResolveData` type

website/docs/en/api/plugin-api/context-module-factory-hooks.mdx, website/docs/zh/api/plugin-api/context-module-factory-hooks.mdx
update `ContextModuleFactory` hook docs.
=> docs: update ContextModuleFactory hook

.github/renovate.json5, Cargo.lock, Cargo.toml, packages/rspack-test-tools/tests/configCases/resolve/extension-alias/errors.js, packages/rspack-test-tools/tests/configCases/resolve/extension-alias/index.js, packages/rspack-test-tools/tests/configCases/resolve/extension-alias/src/m1.mjs, packages/rspack-test-tools/tests/configCases/resolve/matched-alias-not-found/errors.js, packages/rspack-test-tools/tests/configCases/resolve/matched-alias-not-found/index.js, packages/rspack-test-tools/tests/configCases/resolve/matched-alias-not-found/warnings.js, packages/rspack-test-tools/tests/treeShakingCases/cjs-tree-shaking-basic/package.json, packages/rspack-test-tools/tests/treeShakingCases/reexport-all-as-multi-level-nested/package.json, packages/rspack-test-tools/tests/treeShakingCases/reexport-all-as/package.json
chore(deps): upgrade rspack_resolver 0.3.5
<details>
<summary>web-infra-dev/rspack-resolver (rspack_resolver)</summary>
[Compare Source](https://redirect.github.com/web-infra-dev/rspack-resolver/compare/rspack_resolver-v0.3.4...rspack_resolver-v0.3.5)
-   resolve mathjs error when using `extensionAlias` ([#&#8203;31](https://redirect.github.com/web-infra-dev/rspack-resolver/pull/31))
[Compare Source](https://redirect.github.com/web-infra-dev/rspack-resolver/compare/rspack_resolver-v0.3.3...rspack_resolver-v0.3.4)
-   rebase and refine extension-alias error format ([#&#8203;30](https://redirect.github.com/web-infra-dev/rspack-resolver/pull/30))
</details>
=> fix(deps): upgrade rspack_resolver 0.3.5 to fix extensionAlias edge cases

website/docs/en/config/experiments.mdx, website/docs/zh/config/experiments.mdx
Add tips and examples for the `experiments` configs.
=> docs: add tips and examples for experiments configs

README.md, README.zh-CN.md
Update links in README:
- Add [rspack-dev-server](https://github.com/web-infra-dev/rspack-dev-server) as it is a core package of Rspack.
- Fix missing Rsbuild link in English README.
=> docs: update links in README

website/docs/en/config/entry.mdx, website/docs/en/config/module.mdx, website/docs/zh/config/entry.mdx, website/docs/zh/config/module.mdx
- Add some examples for configuring `rule.layer` and `rule.issuerLayer`.
- Correct some types.
=> docs: add layer examples and correct types

crates/node_binding/binding.d.ts, crates/rspack_binding_options/src/options/raw_module/mod.rs, crates/rspack_core/src/options/module.rs, crates/rspack_plugin_javascript/src/visitors/dependency/context_dependency_helper.rs, crates/rspack_util/src/merge.rs, packages/rspack-test-tools/tests/__snapshots__/Defaults.test.js.snap, packages/rspack-test-tools/tests/configCases/context-module/wrapped-context-reg-exp/index.js, packages/rspack-test-tools/tests/configCases/context-module/wrapped-context-reg-exp/rspack.config.js, packages/rspack-test-tools/tests/configCases/context-module/wrapped-context-reg-exp/sub/a1.js, packages/rspack-test-tools/tests/configCases/context-module/wrapped-context-reg-exp/sub/a2.js, packages/rspack/etc/core.api.md, packages/rspack/src/config/adapter.ts, packages/rspack/src/config/defaults.ts, packages/rspack/src/config/types.ts, packages/rspack/src/config/zod.ts, website/docs/en/config/module.mdx, website/docs/zh/config/module.mdx
=> feat: support wrappedContextRegExp

website/docs/en/guide/migration/storybook.mdx, website/docs/en/guide/tech/vue.mdx, website/docs/zh/guide/migration/storybook.mdx, website/docs/zh/guide/tech/vue.mdx
I found some broken links in the Guide and have corrected them.
I kindly ask for your confirmation.
=> docs: fix link is 404 in Guide

website/docs/en/config/module.mdx, website/docs/zh/config/module.mdx
=> docs: correct the format of defaultValue

.github/workflows/preview-commit.yml
=> ci: allow to use self-host runner when preview package

crates/node_binding/binding.d.ts, crates/rspack_binding_options/src/options/mod.rs, crates/rspack_binding_options/src/options/raw_experiments.rs, packages/rspack-test-tools/tests/__snapshots__/Defaults.test.js.snap, packages/rspack/etc/core.api.md, packages/rspack/src/config/adapter.ts, packages/rspack/src/config/defaults.ts, packages/rspack/src/config/normalization.ts, packages/rspack/src/config/types.ts, packages/rspack/src/config/zod.ts
Expose `buildChunkGraph` to `experiments.incremental`
=> fix: expose incremental.buildChunkGraph

website/components/ApiMeta.tsx
=> https://github.com/web-infra-dev/rspack/releases/tag/v1.0.0-beta.1
=> docs: addedVersion should link to release tag

website/docs/en/misc/planning/roadmap.mdx, website/docs/zh/misc/planning/roadmap.mdx
Update Rspack roadmap documentation.
=> docs: update Rspack roadmap

.github/workflows/release-pull-request.yml, scripts/release/version.mjs, x.mjs
Create prerelease pull request through github ci workflow
=> ci: create prerelease pull request

.github/workflows/release-pull-request.yml, scripts/release/version.mjs
Github workflow will select the first option even if `required` is false.
=> ci: fix pretag default value

crates/rspack_core/src/cgm_hash_results.rs, crates/rspack_core/src/code_generation_results.rs, crates/rspack_core/src/compiler/compilation.rs, crates/rspack_plugin_javascript/src/plugin/infer_async_modules_plugin.rs, packages/rspack-test-tools/src/case/new-incremental.ts, packages/rspack-test-tools/src/case/watch.ts
Free space for revoked modules, add it v1.1.0 for finding related bugs.
=> feat(incremental): free space for revoked modules

.gitignore, Cargo.lock, Cargo.toml, crates/rspack_loader_swc/src/compiler.rs, crates/rspack_loader_swc/src/transformer.rs, crates/rspack_plugin_javascript/src/plugin/side_effects_flag_plugin.rs, crates/rspack_plugin_javascript/src/visitors/swc_visitor/dropped_comments_preserver.rs, crates/rspack_plugin_javascript/src/visitors/swc_visitor/hygiene.rs, crates/rspack_plugin_swc_js_minimizer/src/minify.rs, crates/swc_plugin_import/src/lib.rs
bump swc to latest 3.0.1 version， swc changelog https://github.com/swc-project/swc/compare/swc_core%40v1.0.0...swc_core%40v3.0.1
=> feat(core): bump swc to 3.0.1

.github/workflows/ci.yml
=> chore(ci): fix the syntax error

website/docs/en/config/stats.mdx, website/docs/zh/config/stats.mdx
chore(docs): add groupModulesByLayer doc
related mr:  #8283
=> chore(docs): add groupModulesByLayer doc

website/docs/zh/api/loader-api/inline-match-resource.mdx
=> docs: fix inline match resource typo

.github/renovate.json5, .github/workflows/release-pull-request.yml
add some new groups
1. rspress
2. typescript and api-extractor
3. napi @napi-rs/cli
4. @biomejs/biome and prettie
5. "@rspack/dev-server", "@rspack/plugin-react-refresh", "@rspack/plugin-preact-refresh"
=> chore(ci/deps): update renovate

crates/rspack_plugin_devtool/src/eval_source_map_dev_tool_plugin.rs, crates/rspack_plugin_mf/src/sharing/consume_shared_module.rs, crates/rspack_plugin_mf/src/sharing/provide_shared_module.rs
chore: prevent clone when create ModuleIdentifier
=> chore: prevent clone when create ModuleIdentifier

Cargo.lock, crates/rspack_core/src/context_module.rs, crates/rspack_plugin_css/src/plugin/impl_plugin_for_css_plugin.rs, crates/rspack_plugin_css/src/utils.rs, crates/rspack_plugin_extract_css/src/plugin.rs, crates/rspack_plugin_html/Cargo.toml, crates/rspack_plugin_html/src/asset.rs, crates/rspack_plugin_javascript/src/parser_plugin/define_plugin/parser.rs, crates/rspack_util/Cargo.toml, crates/rspack_util/src/identifier.rs
Some regex patterns can be completely replaced with native string methods to enhance performance.
=> perf: remove unnecessary regex

.github/workflows/ci.yml, .github/workflows/preview-commit.yml, package.json
1. fix the ci error of json parsing 
2. fix the api-extractor wrong script
=> fix(ci): pkg.pr.preview not work

website/docs/en/guide/start/quick-start.mdx, website/docs/zh/guide/start/quick-start.mdx, website/project-words.txt
Add Nuxt to ecosystem section.
https://nuxt.com/blog/v3-14
=> docs: add Nuxt to ecosystem

crates/rspack_binding_values/src/module.rs
fix: code auto merging error from #8050
=> fix: code auto merging error

Cargo.lock, Cargo.toml, crates/rspack_loader_swc/Cargo.toml, crates/rspack_plugin_javascript/src/visitors/swc_visitor/hygiene.rs
bump swc to 5.0.0 to fix styled-components compatible bug
=> feat(core): bump swc to 5.0.0

Cargo.lock, Cargo.toml, crates/rspack_loader_swc/Cargo.toml
bump swc to 5.0.1 to fix https://github.com/swc-project/swc/pull/9720
=> fix(core): bump swc to 5.0.1

website/docs/public/.well-known/atproto-did
Add bluesky file for verification.
The current account: https://bsky.app/profile/rspack.bsky.social
=> docs: add bluesky file

crates/rspack_core/src/exports_info.rs, packages/rspack-test-tools/tests/configCases/tree-shaking/side-effects-same-target-export/const.js, packages/rspack-test-tools/tests/configCases/tree-shaking/side-effects-same-target-export/index.js, packages/rspack-test-tools/tests/configCases/tree-shaking/side-effects-same-target-export/lib/const.js, packages/rspack-test-tools/tests/configCases/tree-shaking/side-effects-same-target-export/lib/error.js, packages/rspack-test-tools/tests/configCases/tree-shaking/side-effects-same-target-export/lib/index.js, packages/rspack-test-tools/tests/configCases/tree-shaking/side-effects-same-target-export/lib/package.json, packages/rspack-test-tools/tests/configCases/tree-shaking/side-effects-same-target-export/rspack.config.js, tests/webpack-test/__snapshots__/StatsTestCases.basictest.js.snap
=> fix(side effects): should optimize for same target export

crates/rspack_fs/Cargo.toml, crates/rspack_fs/src/file_metadata.rs, crates/rspack_fs/src/lib.rs, crates/rspack_fs/src/memory_fs.rs
This PR will provide MemoryFileSystem in `rspack_fs`, other crate can use it to write unit test case.
=> feat: add memory fs

crates/rspack_binding_values/src/compilation/mod.rs
fix: prevent depend on ClassInstance
=> refactor(napi): prevent depend on ClassInstance

crates/rspack_binding_options/src/options/raw_split_chunks/raw_split_chunk_cache_group_test.rs, crates/rspack_binding_options/src/options/raw_split_chunks/raw_split_chunk_name.rs, crates/rspack_binding_values/src/chunk_group.rs, crates/rspack_binding_values/src/stats.rs
chore: rm unreachable FromNapiValue
=> refactor(napi): rm unreachable FromNapiValue

.npmrc
See: https://pnpm.io/npmrc#prefer-symlinked-executables
=> build: use symlinked executables instead of command shims

crates/rspack_plugin_limit_chunk_count/src/chunk_combination.rs, tests/webpack-test/__snapshots__/StatsTestCases.basictest.js.snap
fix https://github.com/web-infra-dev/rspack/issues/8337
> https://github.com/webpack/webpack/blob/main/lib/optimize/LimitChunkCountPlugin.js#L108-L109
=> fix: panic in sort of chunk combination bucket

crates/rspack_core/src/normal_module.rs, crates/rspack_plugin_json/src/lib.rs, packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/empty-json/index.js, packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/empty-json/rspack.config.js, packages/rspack-test-tools/tests/diagnosticsCases/module-parse-failed/empty-json/stats.err
fix https://github.com/web-infra-dev/rspack/issues/8390
Not sure why built failed module is also been concatenated, this pr only fixes the panic
=> fix: panic when imported json file is empty

crates/rspack_plugin_split_chunks/src/plugin/max_size.rs, packages/rspack-test-tools/tests/compilerCases/consistent.js, packages/rspack-test-tools/tests/fixtures/split-chunks/src/400k.js, packages/rspack-test-tools/tests/fixtures/split-chunks/src/50k-1.js, packages/rspack-test-tools/tests/fixtures/split-chunks/src/50k-2.js, packages/rspack-test-tools/tests/fixtures/split-chunks/src/50k-3.js, packages/rspack-test-tools/tests/fixtures/split-chunks/src/50k-4.js, packages/rspack-test-tools/tests/fixtures/split-chunks/src/50k-5.js, packages/rspack-test-tools/tests/fixtures/split-chunks/src/50k-6.js, packages/rspack-test-tools/tests/fixtures/split-chunks/src/50k-7.js, packages/rspack-test-tools/tests/fixtures/split-chunks/src/50k-8.js, packages/rspack-test-tools/tests/fixtures/split-chunks/src/50k.js, packages/rspack-test-tools/tests/fixtures/split-chunks/src/index.js
When using maxSize of splitChunks, we will split chunk that size exceeds maxSize into multiple chunks, we split modules inside original chunk, however modules' order matters, for example we may split A, B, C into AB and C, the next time we see B C A, we split them into BC and A, that's because the iterator of modules comes from HashMap which has no guarantee of iterate order, so we need to sort modules before splitting
Test case comes from https://github.com/bigbossx/split-chunk-bug by @bigbossx
=> fix: output should be consistent when using splitChunks

website/docs/en/api/cli.mdx, website/docs/en/api/runtime-api/module-methods.mdx, website/docs/en/api/runtime-api/module-variables.mdx, website/docs/en/guide/optimization/code-splitting.mdx, website/docs/en/guide/tech/react.mdx, website/docs/zh/api/cli.mdx, website/docs/zh/api/runtime-api/module-methods.mdx, website/docs/zh/guide/optimization/code-splitting.mdx, website/docs/zh/guide/tech/react.mdx
Polish module methods documentation, add more links for better navigation.
=> docs: polish module methods documentation

packages/rspack-test-tools/tests/__snapshots__/StatsAPI.test.js.snap, packages/rspack-test-tools/tests/statsAPICases/layer-stats.js
fix(test): fix some tests error for layer stats
=> test: fix some unstable test cases for layer stats

crates/rspack_plugin_javascript/src/parser_plugin/define_plugin/parser.rs, packages/rspack-test-tools/tests/configCases/parsing/rspack-issue-8120/index.js, packages/rspack-test-tools/tests/configCases/parsing/rspack-issue-8120/rspack.config.js
=> feat: align webpack DefinePlugin for destructuring optimization

website/components/RandomMemberList.tsx, website/project-words.txt
Thanks @inottn for your contribution to Rspack stack!
I am delighted to invite you to join the Rspack core team! Your outstanding contributions to the project have truly impressed us. We'd love to have you on board to help shape the future of Rspack stack. ❤️
We have prepared a Rspack gift box for you. If it's convenient, please contact me via email: <jait.chen@foxmail.com>
Contributions:
- https://github.com/web-infra-dev/rspack/commits?author=inottn
- https://github.com/web-infra-dev/rsbuild/commits?author=inottn
- https://github.com/web-infra-dev/rspack/issues?q=commenter:inottn
- https://github.com/web-infra-dev/rsbuild/issues?q=commenter:inottn
=> docs: invite @inottn to Rspack core team

website/docs/en/api/javascript-api/index.mdx, website/docs/en/guide/start/quick-start.mdx, website/docs/zh/api/javascript-api/index.mdx, website/docs/zh/guide/start/quick-start.mdx
Deno and Bun are also supported by Rspack.
See also https://github.com/web-infra-dev/rsbuild/pull/4009
=> docs: add more JavaScript runtimes

crates/node_binding/binding.d.ts, crates/rspack_binding_options/src/options/raw_devtool.rs, crates/rspack_plugin_devtool/src/source_map_dev_tool_plugin.rs, packages/rspack/etc/core.api.md, packages/rspack/src/builtin-plugin/EvalSourceMapDevToolPlugin.ts, packages/rspack/src/builtin-plugin/SourceMapDevToolPlugin.ts
Move matching logic in source map plugin to rust side and update the relevant types.
=> perf: move matching logic in source map plugin to rust side

Cargo.lock, Cargo.toml
fix https://github.com/web-infra-dev/rspack/pull/8492
=> fix: css escape when consume string

website/docs/en/api/loader-api/examples.mdx, website/docs/en/guide/features/loader.mdx, website/docs/zh/api/loader-api/examples.mdx, website/docs/zh/guide/features/loader.mdx
Rspack supports ESM loader and we should document this.
=> docs: add examples for ESM loader

website/docs/en/config/experiments.mdx, website/docs/zh/config/experiments.mdx
=> docs: chunk level incremental

crates/rspack_plugin_schemes/src/data_uri.rs, tests/webpack-test/configCases/asset-modules/data-url/index.js
port https://github.com/webpack/webpack/pull/18904
=> fix: handle DataURI without base64 word

website/docs/en/config/watch.mdx, website/docs/zh/config/watch.mdx
This pull request includes updates to the documentation for the `watch` and `watchOptions` configurations. The changes aim to provide clearer explanations and additional examples for better understanding.
=> docs: add examples for watchOptions

crates/rspack_plugin_asset/src/lib.rs, crates/rspack_plugin_schemes/src/data_uri.rs, tests/webpack-test/configCases/asset-modules/data-url/index.js, tests/webpack-test/configCases/asset-modules/input-data-url-encoding/test.filter.js
fix #8537 fix https://github.com/web-infra-dev/rspack/pull/8344#discussion_r1831074027
=> fix: get encoded asset content correctly

packages/rspack/etc/core.api.md, packages/rspack/src/Module.ts
fix: missing dependencies type in Module class
=> fix: missing dependencies type in Module class

website/docs/en/config/module.mdx, website/docs/zh/config/module.mdx
- Add some examples.
- `typescript` and `jsx` should be removed from `Rule.type`.
=> docs: polish Rule configuration

packages/rspack-cli/bin/rspack.js
Set `process.title` to make it easier to identify the process via activity monitor or other tools.
- resolve https://github.com/web-infra-dev/rspack/issues/8566
- ref: https://github.com/web-infra-dev/rsbuild/pull/4083
=> feat(cli): set default `process.title`

crates/rspack_napi/src/js_values/one_shot_value_ref.rs
Only call `add_env_cleanup_hook` in Rspack constructor to reduce memory usage.
=> perf: register cleanup hook on global

crates/rspack_napi/src/js_values/one_shot_value_ref.rs, packages/rspack/src/Compilation.ts, packages/rspack/src/util/MergeCaller.ts, packages/rspack/src/util/fake.ts
Relative: https://github.com/rspack-contrib/ts-checker-rspack-plugin/issues/9
=> fix: prevent from accessing outdated compilation

Cargo.lock, Cargo.toml, crates/rspack_error/Cargo.toml, crates/rspack_loader_swc/Cargo.toml, crates/rspack_loader_swc/src/options.rs, crates/rspack_loader_swc/src/transformer.rs, crates/rspack_plugin_remove_duplicate_modules/Cargo.toml, crates/swc_plugin_import/Cargo.toml, justfile, tasks/release-check/Cargo.toml, tasks/release-check/src/main.rs
add release-check to check whether all crates have all required fields before publish and fix some publish bugs
=> chore: add release-check task

.github/ISSUE_TEMPLATE/3-tracking-issue.en-US.yml
=> chore: remove tracking subjects

website/docs/en/plugins/rspack/copy-rspack-plugin.mdx, website/docs/zh/plugins/rspack/copy-rspack-plugin.mdx
Rewrite CopyRspackPlugin documentation to make the description and examples of each option clearer.
=> docs: rewrite `CopyRspackPlugin` documentation

.github/workflows/ci.yml
=> ci: run miri on main

crates/rspack_ids/src/named_module_ids_plugin.rs, packages/rspack-test-tools/tests/watchCases/module-ids/ignored-module/0/index.js, packages/rspack-test-tools/tests/watchCases/module-ids/ignored-module/1/index.js, packages/rspack-test-tools/tests/watchCases/module-ids/ignored-module/rspack.config.js
Try our best to avoid unnamed module ids
=> fix: avoid unnamed module ids

website/docs/zh/blog/announcing-1-1.mdx
https://docusaurus.io/blog/docusaurus-v3.6 is 404
=> docs: fix error links

crates/rspack_plugin_javascript/src/parser_and_generator/mod.rs
Related to #7043 
This code was originally written a year ago and refactored five months ago. After reviewing the relevant context, it is clear that the code is unnecessary. Keeping it would only increase the complexity and maintenance cost.
=> chore: remove unnecessary code

.github/ISSUE_TEMPLATE/1-bug-report.en-US.yml, .github/ISSUE_TEMPLATE/2-feature-request.en-US.yml, .github/ISSUE_TEMPLATE/3-tracking-issue.en-US.yml
> Issues types allow you to classify and manage your issues with a shared and consistent language across all repositories in the organization, such as bugs or tasks.
https://github.com/orgs/community/discussions/139933
=> chore(workflow): set Issue types

packages/rspack/etc/core.api.md, packages/rspack/src/Compilation.ts, packages/rspack/src/Compiler.ts, packages/rspack/src/Watching.ts, tests/webpack-test/configCases/additional-pass/simple/test.filter.js
feat: support additional-pass hook
Close #8485
=> feat: support additional-pass hook

crates/node_binding/binding.d.ts, crates/rspack_binding_values/src/chunk_graph.rs, packages/rspack-test-tools/tests/configCases/chunk-graph/get-module-id/rspack.config.js, packages/rspack/etc/core.api.md, packages/rspack/src/ChunkGraph.ts
Support `chunkGraph.getModuleId` binding API used in RSC.
=> feat: chunkGraph.getModuleId binding API

website/components/PluginSupportStatusTable.tsx
fix: webpack plugins overview docs panic for zh lang
=> docs: fix webpack plugins overview docs panic for zh lang

packages/rspack/etc/core.api.md
Fixing https://github.com/web-infra-dev/rspack/actions/runs/12311203727/job/34361384919
=> chore: update API change

website/docs/en/config/cache.mdx, website/docs/en/config/experiments.mdx, website/docs/zh/config/cache.mdx, website/docs/zh/config/experiments.mdx
Add document for `persistent_cache` feature.
=> docs: persistent cache

packages/rspack-test-tools/tests/configCases/container-1-5/2-container-full/index.js, packages/rspack/package.json, pnpm-lock.yaml
Bump `@module-federation/runtime-tools` from 0.5.1 to 0.8.4
See https://github.com/module-federation/core/releases for detailed changes.
=> feat(mf): bump @module-federation/runtime-tools to 0.8.4

crates/rspack_core/src/exports_info.rs, crates/rspack_plugin_javascript/src/plugin/side_effects_flag_plugin.rs
Improve performance for side effects plugin especially when there aren't too many dependencies are optimizable, time costing on side effects plugin:
- 20000 modules: 4.3ms -> 2.7ms
- internal project: 190ms -> 180ms
=> perf: side effects when there aren't too many optimizable dependencies

crates/node_binding/package.json, npm/darwin-arm64/package.json, npm/darwin-x64/package.json, npm/linux-x64-gnu/package.json, npm/win32-x64-msvc/package.json, package.json, packages/create-rspack/package.json, packages/rspack-cli/package.json, packages/rspack-test-tools/package.json, packages/rspack/package.json
Release 1.1.8 hotfix for security reason
See https://github.com/web-infra-dev/rspack/issues/8767 for more details
=> release: release v1.1.8 to prevent the attacked version from being installed

.github/workflows/ecosystem-ci-trigger.yml
Remove all issue_comment trigger for safety.
=> chore: remove issue_comment trigger from CI

.github/workflows/release-pull-request.yml
The `rspack-contrib/rspack-action` need GITHUB_TOKEN only, remove other useless variables.
=> ci: remove useless variable in release-pull-request.yml

packages/rspack/src/util/bindingVersionCheck.ts
=> feat: add help message for version check

crates/node_binding/package.json, crates/node_binding/scripts/build.js, pnpm-lock.yaml
Bump napi cli to the latest version.
Disable dts cache to fix unstable dts generation.
=> chore(napi/build): disable dts cache of napi build

.github/workflows/lint-pr.yaml
=> ci: add security pr type

.github/teams.yml
This pull request includes a small change to the `team:` section in the `.github/teams.yml` file. The change adds a new team member to the list.
* Added `@GiveMe-A-Name` to the `team:` section in the `.github/teams.yml` file.
=> ci: add @GiveMe-A-Name to team label

website/docs/en/config/output.mdx, website/docs/zh/config/output.mdx
```rust
// https://github1s.com/web-infra-dev/rspack/blob/main/crates/rspack_binding_values/src/clean_options.rs#L13
#[napi(object, object_to_js = false)]
#[derive(Debug)]
pub struct JsCleanOptions {
pub keep: Option<String>,
// todo:
// - support RegExp type
//   if path match the RegExp, keep the file
// - support function type
//    if the fn returns true on path str, keep the file
}
```
=> docs: update output.clean type declaration

crates/rspack_core/src/context_module.rs, crates/rspack_plugin_extract_css/src/css_dependency.rs
I have researched and found that these TODOs are no longer necessary.
=> chore: remove unnecessary TODOs

crates/rspack_core/src/build_chunk_graph/incremental.rs, crates/rspack_core/src/chunk_group.rs, packages/rspack-test-tools/tests/watchCases/build-chunk-graph/runtime-chunk/0/index.js, packages/rspack-test-tools/tests/watchCases/build-chunk-graph/runtime-chunk/0/lib.js, packages/rspack-test-tools/tests/watchCases/build-chunk-graph/runtime-chunk/1/index.js, packages/rspack-test-tools/tests/watchCases/build-chunk-graph/runtime-chunk/2/index.js, packages/rspack-test-tools/tests/watchCases/build-chunk-graph/runtime-chunk/rspack.config.js, packages/rspack-test-tools/tests/watchCases/build-chunk-graph/runtime-chunk/test.config.js
=> fix(incremental): build chunk graph with runtime chunk true

Cargo.lock, packages/rspack-test-tools/tests/__snapshots__/StatsOutput.test.js.snap, packages/rspack-test-tools/tests/diagnosticsCases/builtins/recoverable_syntax_error/stats.err
- Fixes one of the little issues blocking #8805.
=> chore(deps): upgrade miette 7.2.0 to 7.4.0

.github/workflows/ecosystem-benchmark.yml
Add workflow to run rspack-ecosystem-benchmark
=> ci: add ecosystem benchmark

crates/node_binding/package.json, npm/darwin-arm64/package.json, npm/darwin-x64/package.json, npm/linux-x64-gnu/package.json, npm/win32-x64-msvc/package.json, package.json, packages/create-rspack/package.json, packages/rspack-cli/package.json, packages/rspack-test-tools/package.json, packages/rspack/package.json
Update version in package.json to match the latest v1.1.8 release. This makes the canary `version 1.19-canary` instead of `1.1.7-canary`.
https://github.com/web-infra-dev/rspack/issues/8480#issuecomment-2563609964
=> chore: update version to match the latest release

crates/node_binding/src/resolver_factory.rs, crates/rspack_core/src/cache/mod.rs, crates/rspack_core/src/cache/persistent/cacheable_context.rs, crates/rspack_core/src/cache/persistent/mod.rs, crates/rspack_core/src/cache/persistent/snapshot/mod.rs, crates/rspack_core/src/cache/persistent/snapshot/strategy.rs, crates/rspack_core/src/cache/persistent/version.rs, crates/rspack_core/src/compiler/compilation.rs, crates/rspack_core/src/compiler/make/repair/build.rs, crates/rspack_core/src/compiler/make/repair/mod.rs, crates/rspack_core/src/compiler/mod.rs, crates/rspack_core/src/module.rs, crates/rspack_core/src/resolver/boxfs.rs, crates/rspack_core/src/resolver/factory.rs, crates/rspack_core/src/resolver/resolver_impl.rs, crates/rspack_fs/src/fs.rs, crates/rspack_fs/src/lib.rs, crates/rspack_fs/src/memory_fs.rs, crates/rspack_fs/src/native_fs.rs, crates/rspack_loader_runner/src/runner.rs, crates/rspack_plugin_schemes/src/http_cache.rs, crates/rspack_plugin_schemes/src/http_uri.rs, crates/rspack_plugin_schemes/src/lockfile.rs
it's unsafe to use write related method for input_filesystem so change the interface to ReadableFileSystem
=> chore: change input_filesystem to ReadableFileSystem

website/docs/en/config/experiments.mdx, website/docs/zh/config/experiments.mdx
* Update experiments.cache available version to `1.2.0-alpha.0`
* Fix typo, `experiment` -> `experiments`
=> docs: update persistent cache available version and configuration

crates/rspack_core/src/compiler/compilation.rs, crates/rspack_core/src/compiler/module_executor/mod.rs, crates/rspack_core/src/incremental/mutations.rs, crates/rspack_ids/src/named_module_ids_plugin.rs, crates/rspack_plugin_javascript/src/plugin/infer_async_modules_plugin.rs, crates/rspack_plugin_javascript/src/plugin/side_effects_flag_plugin.rs
Split `Mutation::ModuleBuild` into `Mutation::ModuleAdd` and `Mutation::ModuleUpdate`
=> refactor(incremental): introduce mutation update module

website/docs/en/config/optimization.mdx, website/docs/zh/config/optimization.mdx
=> docs: correct `avoidEntryIife` added version

website/docs/en/contribute/architecture/builtin-plugin.md, website/docs/zh/contribute/architecture/builtin-plugin.md
=> docs: fix typo in builtin-plugin.md

website/docs/en/plugins/webpack/warn-case-sensitive-modules-plugin.mdx, website/docs/zh/plugins/webpack/warn-case-sensitive-modules-plugin.mdx
This pull request includes updates to the documentation for the `WarnCaseSensitiveModulesPlugin`. The changes improve the clarity of the descriptions and include additional examples and tips for using the plugin.
=> docs: complete `WarnCaseSensitiveModulesPlugin`

packages/rspack-test-tools/tests/configCases/module/build-info/loader.js, packages/rspack-test-tools/tests/configCases/module/build-info/rspack.config.js, packages/rspack/etc/core.api.md, packages/rspack/src/Compilation.ts, packages/rspack/src/Compiler.ts, packages/rspack/src/Module.ts, packages/rspack/src/builtin-plugin/SplitChunksPlugin.ts, packages/rspack/src/loader-runner/index.ts
feat: support set build info in js side
=> feat: support set build info in js side

.github/workflows/ecosystem-benchmark.yml
checkout action should accept refs/pull/{pr}/head.
=> ci: ecosystem-benchmark checkout failed

.github/workflows/ecosystem-ci.yml
Add workflow to run rspack-ecosystem-ci.
=> ci: add ecosystem ci

crates/rspack_core/src/options/compiler_options_builder.rs, crates/rspack_core/src/options/devtool.rs, crates/rspack_core/src/options/mod.rs
Added `devtool` to compiler options builder.
=> feat: support `devtool` to compiler options builder

.github/workflows/ecosystem-ci.yml
Downgrade ecosystem-ci runs-on to ubuntu-22.04.
=> ci: ecosystem-ci runs on ubuntu-22.04

website/docs/en/blog/index.mdx, website/docs/zh/blog/index.mdx
Updated our blog list, added two new blog posts.
Ref: https://github.com/orgs/web-infra-dev/discussions
=> docs: update blog list

Cargo.lock, Cargo.toml, crates/rspack/Cargo.toml, crates/rspack/src/builder/mod.rs, crates/rspack/src/builder/target.rs
=> feat: make builtin plugin options ordered in compiler options builder

crates/rspack_core/src/normal_module_factory.rs, crates/rspack_core/src/options/module.rs, packages/rspack-test-tools/tests/configCases/module/merge-global-asset-generator/index.js, packages/rspack-test-tools/tests/configCases/module/merge-global-asset-generator/rspack.config.js
=> fix: merge global parser and generator options

website/docs/en/config/experiments.mdx, website/docs/zh/config/experiments.mdx
Add persistent cache config migration example.
=> docs: add persistent cache migration

Cargo.lock, crates/rspack_core/src/cache/persistent/occasion/make/dependencies.rs, crates/rspack_core/src/cache/persistent/occasion/make/meta.rs, crates/rspack_core/src/cache/persistent/occasion/make/mod.rs, crates/rspack_core/src/cache/persistent/occasion/make/module_graph.rs, crates/rspack_core/src/cache/persistent/snapshot/mod.rs, crates/rspack_storage/Cargo.toml, crates/rspack_storage/src/pack/manager/mod.rs
Add tracing instrument for persistent cache.
=> feat: add tracing instrument for persistent cache

crates/rspack_loader_next_swc/src/lib.rs
Fixes failing conditions from testing
=> Fix un-needed panic and flipped ssg condition

crates/rspack_core/src/cache/persistent/occasion/make/module_graph.rs, crates/rspack_core/src/cache/persistent/snapshot/mod.rs, crates/rspack_core/src/utils/iterator_consumer/future.rs, crates/rspack_core/src/utils/iterator_consumer/rayon.rs, crates/rspack_core/src/utils/iterator_consumer/rayon_fut.rs
Consume data while processing the storage loading data.
=> perf: persistent cache recovery use consumer mode

crates/next-custom-transforms/src/chain_transforms.rs
Fixes this transform not running since we aren't threading the config all the way through right now and isn't really needed.
=> Ensure styled-jsx transform always runs

website/docs/en/api/runtime-api/hmr.mdx, website/docs/en/api/runtime-api/module-methods.mdx, website/docs/en/guide/tech/preact.mdx, website/docs/en/guide/tech/react.mdx, website/docs/en/plugins/webpack/hot-module-replacement-plugin.mdx, website/docs/zh/api/cli.mdx, website/docs/zh/api/runtime-api/hmr.mdx, website/docs/zh/api/runtime-api/module-methods.mdx, website/docs/zh/guide/tech/preact.mdx, website/docs/zh/guide/tech/react.mdx, website/docs/zh/plugins/webpack/hot-module-replacement-plugin.mdx
This pull request includes several updates to the documentation for HMR and related plugins.
The changes enhance the clarity and completeness of the documentation. The most important changes include updates to the HMR API examples, additions of new plugins, and improvements to translation consistency.
=> docs: improve hot module replacement

website/docs/en/config/experiments.mdx, website/docs/zh/config/experiments.mdx
Add docs about new parallel code splitting algorithm
=> docs: add parallel code splitting docs

Cargo.lock, crates/rspack/Cargo.toml, crates/rspack/src/builder/mod.rs, crates/rspack_binding_values/src/raw_options/mod.rs, crates/rspack_binding_values/src/raw_options/raw_node.rs, crates/rspack_core/src/compiler/mod.rs, crates/rspack_core/src/options/entry.rs, crates/rspack_core/src/options/node.rs, crates/rspack_plugin_javascript/src/parser_plugin/node_stuff_plugin.rs
Added `resolve`, `resolveLoader`, `stats`, etc to compiler builder.
=> feat: support more options in compiler builder

.github/workflows/reusable-build.yml, Cargo.lock, tasks/benchmark/Cargo.toml, tasks/benchmark/benches/basic.rs
=> test: add basic rust benchmark

.github/workflows/release.yml
=> fix: add issue permission for release workflow

crates/node_binding/binding.d.ts, crates/node_binding/src/plugins/interceptor.rs, crates/node_binding/src/plugins/mod.rs, packages/rspack-tracing/index.d.ts, packages/rspack/etc/core.api.md, packages/rspack/src/Compiler.ts, packages/rspack/src/builtin-plugin/html-plugin/hooks.ts, packages/rspack/src/builtin-plugin/html-plugin/index.ts, packages/rspack/src/builtin-plugin/html-plugin/options.ts, packages/rspack/src/builtin-plugin/html-plugin/plugin.ts, packages/rspack/src/builtin-plugin/html-plugin/taps.ts, packages/rspack/src/builtin-plugin/index.ts, packages/rspack/src/taps/compilation.ts, packages/rspack/src/taps/compiler.ts, packages/rspack/src/taps/contextModuleFactory.ts, packages/rspack/src/taps/index.ts, packages/rspack/src/taps/javascriptModules.ts, packages/rspack/src/taps/normalModuleFactory.ts, packages/rspack/src/taps/types.ts
Split compiler hook registers into multiple files
=> refactor: split compiler hook registers into multiple files

crates/rspack/src/builder/builder_context.rs, crates/rspack/src/builder/devtool.rs, crates/rspack/src/builder/mod.rs, crates/rspack/src/builder/target.rs, crates/rspack/src/lib.rs, crates/rspack_core/src/options/experiments/mod.rs, crates/rspack_core/src/options/module.rs, crates/rspack_core/src/options/optimizations.rs, crates/rspack_core/src/options/output.rs
This PR implemented `From` trait for compiler options to options builder, 
also added docs for compiler option APIs and turned on `missing_docs` check.
=> feat: improve compatibility with compiler options

crates/rspack_plugin_javascript/src/parser_plugin/amd/amd_define_dependency_parser_plugin.rs, crates/rspack_plugin_javascript/src/parser_plugin/amd/amd_plugin.rs, crates/rspack_plugin_javascript/src/parser_plugin/amd/amd_require_dependencies_block_parser_plugin.rs, crates/rspack_plugin_javascript/src/parser_plugin/amd/mod.rs, crates/rspack_plugin_javascript/src/parser_plugin/mod.rs, crates/rspack_plugin_javascript/src/visitors/dependency/parser/mod.rs, crates/rspack_plugin_javascript/src/visitors/dependency/parser/walk.rs, crates/rspack_plugin_javascript/src/visitors/dependency/util.rs, packages/rspack-test-tools/tests/normalCases/amd/real-amd-libs/define-in-params.js, packages/rspack-test-tools/tests/normalCases/amd/real-amd-libs/index.js
fix https://github.com/web-infra-dev/rspack/issues/9078
=> fix: amd define in function params

Cargo.lock, Cargo.toml
revert: rspack sources substring algo
=> revert: rspack sources substring heuristic algorithm

crates/node_binding/package.json, npm/darwin-arm64/package.json, npm/darwin-x64/package.json, npm/linux-x64-gnu/package.json, npm/win32-x64-msvc/package.json, package.json, packages/create-rspack/package.json, packages/rspack-cli/package.json, packages/rspack-test-tools/package.json, packages/rspack-tracing/package.json, packages/rspack/package.json
Ref: https://github.com/web-infra-dev/rspack/releases/tag/v1.2.1
=> chore: release packages 1.2.1

crates/rspack_core/src/old_cache/local/code_splitting_cache.rs, packages/rspack-test-tools/tests/watchCases/chunk-ids/update-module/0/a.js, packages/rspack-test-tools/tests/watchCases/chunk-ids/update-module/0/a1.js, packages/rspack-test-tools/tests/watchCases/chunk-ids/update-module/0/b.js, packages/rspack-test-tools/tests/watchCases/chunk-ids/update-module/0/b1.js, packages/rspack-test-tools/tests/watchCases/chunk-ids/update-module/0/c.js, packages/rspack-test-tools/tests/watchCases/chunk-ids/update-module/0/index.js, packages/rspack-test-tools/tests/watchCases/chunk-ids/update-module/1/a.js, packages/rspack-test-tools/tests/watchCases/chunk-ids/update-module/1/a1.js, packages/rspack-tracing/index.d.ts
Expose some incremental bugs as early as possible.
=> feat(incremental): don't use has_module_import_export_change when incremental code splitting enabled

crates/rspack/src/builder/mod.rs, crates/rspack_core/src/options/module.rs
=> perf(options): replace `Regexp` with `ends_with` match

crates/rspack/src/builder/builder_context.rs, crates/rspack/tests/basic.rs, tasks/benchmark/benches/basic.rs
Fixed an issue of source map plugin not being added.
Added a bench case.
=> test(benchmark): add basic sourcemap bench case

crates/node_binding/package.json, npm/darwin-arm64/package.json, npm/darwin-x64/package.json, npm/linux-x64-gnu/package.json, npm/win32-x64-msvc/package.json, package.json, packages/create-rspack/package.json, packages/rspack-cli/package.json, packages/rspack-test-tools/package.json, packages/rspack-tracing/package.json, packages/rspack/package.json
https://github.com/web-infra-dev/rspack/releases/tag/v1.2.2
=> chore: release packages 1.2.2

packages/rspack-test-tools/tests/configCases/dll/numeric-module-id/errors.js, packages/rspack-test-tools/tests/configCases/dll/numeric-module-id/lib.js, packages/rspack-test-tools/tests/configCases/dll/numeric-module-id/main.js, packages/rspack-test-tools/tests/configCases/dll/numeric-module-id/rspack.config.js, packages/rspack/etc/core.api.md, packages/rspack/src/lib/DllReferencePlugin.ts
=> fix: dll manifest zod validation

README.md, README.zh-CN.md
Update Rslib description in README.md.
=> chore: update Rslib description in README.md

crates/rspack_plugin_javascript/src/dependency/amd/amd_define_dependency.rs, crates/rspack_plugin_javascript/src/dependency/amd/amd_require_array_dependency.rs, crates/rspack_plugin_javascript/src/dependency/amd/amd_require_item_dependency.rs, crates/rspack_plugin_javascript/src/parser_plugin/amd/amd_define_dependency_parser_plugin.rs, crates/rspack_plugin_javascript/src/parser_plugin/amd/amd_require_dependencies_block_parser_plugin.rs, crates/rspack_plugin_javascript/src/parser_plugin/initialize_evaluating.rs, crates/rspack_plugin_javascript/src/utils/eval/mod.rs, tests/webpack-test/cases/amd/namedModulesConstArrayDep/test.filter.js, tests/webpack-test/cases/mjs/type-module/package.json, tests/webpack-test/cases/mjs/type-module/test.filter.js
fix amd require or define an array of dependencies
=> fix: amd require array

website/docs/en/guide/features/builtin-swc-loader.mdx, website/docs/zh/guide/features/builtin-swc-loader.mdx
This pull request includes updates to the SWC loader documentation. The changes primarily focus on providing additional notes for better clarity.
resolve https://github.com/web-infra-dev/rspack/issues/9115
=> docs: add notes for injecting core-js polyfill

crates/rspack_plugin_javascript/src/parser_plugin/amd/amd_require_dependencies_block_parser_plugin.rs, crates/rspack_plugin_javascript/src/parser_plugin/require_ensure_dependencies_block_parse_plugin.rs, crates/rspack_plugin_javascript/src/visitors/dependency/parser/mod.rs, packages/rspack-test-tools/tests/configCases/amd/define-wrapper/lib1.js, tests/webpack-test/ConfigTestCases.template.js, tests/webpack-test/StatsTestCases.basictest.js, tests/webpack-test/TestCases.template.js, tests/webpack-test/__snapshots__/StatsTestCases.basictest.js.snap, tests/webpack-test/cases/parsing/issue-2641/index.js, tests/webpack-test/cases/parsing/issue-2641/test.filter.js, tests/webpack-test/cases/parsing/renaming/test.filter.js, tests/webpack-test/configCases/async-commons-chunk/all-selected/test.filter.js, tests/webpack-test/configCases/async-commons-chunk/existing-name/test.filter.js, tests/webpack-test/configCases/async-commons-chunk/simple/test.filter.js, tests/webpack-test/statsCases/async-commons-chunk/test.filter.js
=> fix: amd alias define renaming

website/docs/en/config/module.mdx, website/docs/zh/config/module.mdx
This pull request add examples for all module parser and generator options, which can allow users to copy example codes to simplify the configuration process.
=> docs: add examples for all module parser and generator options

website/docs/en/config/plugins.mdx, website/docs/en/guide/features/plugin.mdx, website/docs/en/plugins/webpack/hot-module-replacement-plugin.mdx, website/docs/zh/config/plugins.mdx, website/docs/zh/guide/features/plugin.mdx, website/docs/zh/plugins/webpack/hot-module-replacement-plugin.mdx
This pull request includes several updates to the Rspack plugins documentation, specifically enhancing the explanation of the `plugins` option and providing more detailed usage examples.
The changes focus on clarifying plugin types, usage, and compatibility, as well as adding instructions for disabling plugins.
=> docs: rewrite plugins usage guide

.github/workflows/label-auto-comment.yml
https://github.com/web-infra-dev/rspack/actions/workflows/label-auto-comment.yml
=> chore(ci): remove invalid field

website/docs/en/contribute/development/profiling.md, website/docs/zh/contribute/development/profiling.md, website/project-words.txt
add profiling guide using samply
=> docs: add profile guide using samply

crates/node_binding/binding.d.ts, crates/rspack_binding_values/src/chunk_graph.rs, crates/rspack_binding_values/src/dependency_block.rs, packages/rspack-test-tools/tests/configCases/chunk-graph/get-block-chunk-group/index.js, packages/rspack-test-tools/tests/configCases/chunk-graph/get-block-chunk-group/rspack.config.js, packages/rspack/etc/core.api.md, packages/rspack/src/ChunkGraph.ts
=> feat: get block chunk group

packages/rspack/etc/core.api.md, packages/rspack/prebundle.config.mjs
=> fix(types): prebundle `@swc/types` to fix missing dts files

crates/node_binding/binding.d.ts, crates/rspack_binding_values/src/module_graph.rs, crates/rspack_core/src/cache/persistent/occasion/make/module_graph.rs, crates/rspack_core/src/compiler/make/repair/build.rs, crates/rspack_core/src/module_graph/mod.rs, packages/rspack-test-tools/tests/configCases/module-graph/get-parent-block-index/index.js, packages/rspack-test-tools/tests/configCases/module-graph/get-parent-block-index/rspack.config.js, packages/rspack-test-tools/tests/configCases/module-graph/get-parent-module/index.js, packages/rspack-test-tools/tests/configCases/module-graph/get-parent-module/rspack.config.js, packages/rspack/etc/core.api.md, packages/rspack/src/ModuleGraph.ts
1. getIncomingConnections(module: Module): ModuleGraphConnection[]
2. getParentModule(dependency: Dependency): Module | null
3. getParentBlockIndex(dependency: Dependency): number
4. isAsync(module: Module): boolean
=> feat: support missing module graph js api

crates/rspack_binding_values/src/raw_options/raw_builtins/raw_copy.rs, crates/rspack_binding_values/src/runtime.rs, crates/rspack_plugin_devtool/src/module_filename_helpers.rs, crates/rspack_plugin_schemes/src/http_cache.rs, crates/rspack_plugin_warn_sensitive_module/src/lib.rs, crates/rspack_storage/src/fs/error.rs, crates/swc_plugin_import/src/lib.rs
Related to https://github.com/oxc-project/oxc/issues/8659
Is there any special consideration for `Unicode` in this PR?
=> refactor(rust): use `cow_to_ascii_uppercase` and `cow_to_ascii_lowercase`

crates/node_binding/binding.d.ts, crates/rspack_binding_values/src/module.rs, crates/rspack_plugin_javascript/src/dependency/commonjs/common_js_export_require_dependency.rs, packages/rspack-test-tools/tests/configCases/module/lib-ident/rspack.config.js, packages/rspack-test-tools/tests/configCases/module/match-resource/loader.js, packages/rspack-test-tools/tests/configCases/module/match-resource/rspack.config.js, packages/rspack-test-tools/tests/configCases/module/resource-resolve-data/rspack.config.js, packages/rspack/etc/core.api.md, packages/rspack/src/Module.ts
1. libIdent(options: JsLibIdentOptions): string | null
2. get resourceResolveData(): JsResourceData | undefined
3. get matchResource(): string | undefined
=> feat: support missing module js api

crates/node_binding/binding.d.ts, crates/rspack_binding_values/src/raw_options/raw_split_chunks/mod.rs, crates/rspack_plugin_split_chunks/src/common.rs, crates/rspack_plugin_split_chunks/src/plugin/module_group.rs, packages/rspack-test-tools/tests/configCases/split-chunks/cache-group-layer-function/index.js, packages/rspack-test-tools/tests/configCases/split-chunks/cache-group-layer-function/rspack.config.js, packages/rspack-test-tools/tests/configCases/split-chunks/cache-group-layer-function/test.config.js, packages/rspack/etc/core.api.md, packages/rspack/src/config/types.ts, packages/rspack/src/config/zod.ts
feat: layer option support function
=> feat: layer option support function

website/docs/en/config/output.mdx, website/docs/zh/config/output.mdx
=> docs: fix `output.workerChunkLoading` link

crates/node_binding/binding.d.ts, packages/rspack-test-tools/tests/configCases/code-generation/path-ends-with-star/star*/a.js, packages/rspack-test-tools/tests/configCases/hooks/after-environment/rspack.config.js, packages/rspack/etc/core.api.md, packages/rspack/src/Compiler.ts, packages/rspack/src/config/defaults.ts
initialize resolverFactory early so ensure it's accessible in hooks
=> fix(core): initialize resolverFactory early

.cargo/config.toml
speedup compile by enable parallel compile and shared-generic, this is borrowed from https://github.com/vercel/next.js/blob/b9277bf371c8ad77e495b9874f62c080583d40d8/.cargo/config.toml#L12-L13 thanks @bgw great advice
* before
* after
=> perf: speedup compile

website/docs/en/contribute/development/profiling.md, website/docs/zh/contribute/development/profiling.md
add `--interpreted-frames-native-stack` args when do node.js profiling, more detail in https://blogs.igalia.com/dape/2023/11/16/v8-profiling-instrumentation-overhead/
=> docs: update profiling guide

crates/node_binding/binding.d.ts, packages/rspack-test-tools/tests/configCases/hooks/after-environment/rspack.config.js, packages/rspack-test-tools/tests/configCases/hooks/normal-module-factory/rspack.config.js, packages/rspack/etc/core.api.md, packages/rspack/src/Compiler.ts, packages/rspack/src/NormalModuleFactory.ts
close #8584
With the implementation of #9193, this feature is now achievable.
=> feat: add getResolver method for NormalModuleFactory

packages/rspack/src/Stats.ts
=> fix(core): don't swallowing exceptions in stats.toJson

website/docs/en/config/module.mdx, website/docs/zh/config/module.mdx
https://github.com/web-infra-dev/rspack/pull/8802 introduced one option in v1.2.0. Let we update the docs.
=> docs: improve FlagDependencyExportsPlugin for large JSON by depth

website/docs/en/plugins/webpack/split-chunks-plugin.mdx, website/docs/zh/plugins/webpack/split-chunks-plugin.mdx
=> docs: correct splitChunks chunk.name

Cargo.lock, Cargo.toml
Bump rspack_dojang to `0.1.11` to support `index` in `for-loop`
=> chore: bump rspack_dojang to 0.1.11

crates/rspack_plugin_css/src/dependency/import.rs, crates/rspack_plugin_css/src/parser_and_generator/mod.rs, crates/rspack_plugin_css/src/plugin/impl_plugin_for_css_plugin.rs, packages/rspack-test-tools/tests/__snapshots__/Config.test.js.snap, packages/rspack-test-tools/tests/__snapshots__/NewCodeSplitting-config.test.js.snap, packages/rspack-test-tools/tests/configCases/css/at-import/a.css, packages/rspack-test-tools/tests/configCases/css/at-import/b.css, packages/rspack-test-tools/tests/configCases/css/at-import/c.css, packages/rspack-test-tools/tests/configCases/css/at-import/index.js, packages/rspack-test-tools/tests/configCases/css/at-import/rspack.config.js
close #9142
Native CSS should handle `@import` syntax with layer, supports and media.
=> feat(plugin-css): should handle css layer supports media

Cargo.lock, crates/node_binding/binding.d.ts, crates/rspack/src/builder/mod.rs, crates/rspack/tests/snapshots/defaults__default_options.snap, crates/rspack_binding_values/src/raw_options/raw_optimization.rs, crates/rspack_core/src/options/optimizations.rs, crates/rspack_plugin_real_content_hash/Cargo.toml, crates/rspack_plugin_real_content_hash/src/drive.rs, crates/rspack_plugin_real_content_hash/src/lib.rs
Relate to https://github.com/web-infra-dev/rspack/issues/4381
- Support native `updateHash` hook of RealContentHashPlugin.
- Add `real_content_hash` to `compilation.options.optimization`.
---
This pull request introduces a new feature to support real content hashing in the `rspack` project. The changes involve modifications to several files to integrate the `real_content_hash` option and the implementation of the `RealContentHashPlugin`.
* [`crates/rspack/src/builder/mod.rs`](diffhunk://#diff-3a58b8bbfd3686a216e44b3b9be5b27e6b85535502cd0b1493e4d1d722849a39R3553): Added `real_content_hash` to the `OptimizationOptionsBuilder`.
* [`crates/rspack/tests/snapshots/defaults__default_options.snap`](diffhunk://#diff-dfa5eb372b3071ccaa7b4172bc616a4781a7765b2a5da09552ef407558cebcdcR1362): Added …
=> feat: add native hook of real content hash plugin

crates/node_binding/binding.d.ts, crates/rspack_binding_values/src/chunk_graph.rs, crates/rspack_binding_values/src/dependency.rs, crates/rspack_binding_values/src/exports_info.rs, crates/rspack_binding_values/src/runtime.rs, packages/rspack-test-tools/tests/configCases/chunk-graph/get-module-hash/rspack.config.js, packages/rspack/etc/core.api.md, packages/rspack/src/ChunkGraph.ts, packages/rspack/src/ExportsInfo.ts, packages/rspack/src/util/runtime.ts
feat: chunk graph get module hash
=> feat: chunk graph get module hash

crates/rspack_core/src/external_module.rs, crates/rspack_core/src/module.rs
align with webpack implementation here https://github.com/webpack/webpack/blob/3919c844eca394d73ca930e4fc5506fb86e2b094/lib/ExternalModule.js#L603
=> fix(core): fix module external not treated as async

pnpm-lock.yaml, website/docs/en/misc/planning/roadmap.mdx, website/docs/zh/misc/planning/roadmap.mdx, website/package.json, website/theme/components/Landingpage/Hero/index.tsx
Display GitHub button on homepage:
=> docs: display GitHub button on homepage

crates/rspack_core/src/chunk.rs, packages/rspack-test-tools/tests/configCases/chunk-loading/depend-on-with-chunk-load/index.js, packages/rspack-test-tools/tests/configCases/chunk-loading/depend-on-with-chunk-load/rspack.config.js, packages/rspack-test-tools/tests/configCases/chunk-loading/depend-on-with-chunk-load/test.config.js
=> fix: has async chunks

Cargo.lock, crates/rspack_core/src/build_chunk_graph/code_splitter.rs, crates/rspack_plugin_dynamic_entry/Cargo.toml, crates/rspack_plugin_dynamic_entry/src/lib.rs, crates/rspack_plugin_entry/src/lib.rs, crates/rspack_util/src/fx_hash.rs, packages/rspack-test-tools/tests/watchCases/entries/dynamic-entries/0/index0.js, packages/rspack-test-tools/tests/watchCases/entries/dynamic-entries/2/index0.js, packages/rspack-test-tools/tests/watchCases/entries/dynamic-entries/2/index2.js, packages/rspack-test-tools/tests/watchCases/entries/dynamic-entries/rspack.config.js
fix: dynamic entry dependency reuse
=> fix: dynamic entry dependency reuse

.github/workflows/reusable-build.yml
2.8.0 failed due to incompatible glibc version
https://github.com/web-infra-dev/rspack/actions/runs/13311512891/job/37198732218?pr=9288#step:10:1
=> chore: pin codspeed version

package.json
wrongly broken by previous PR https://github.com/web-infra-dev/rspack/pull/9288/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R46 which cause bench failed
=> chore: fix bench ci

README.md, README.zh-CN.md
=> chore: add codspeed badge

.github/actions/rustup/action.yml, .github/workflows/ci.yml, .github/workflows/reusable-build.yml
* enable rust-cache for PR
* remove unused !{linux,windows,mac} test
=> chore: continue clean up workflow

crates/rspack_core/src/utils/hash.rs
Reverts web-infra-dev/rspack#9289 cc @shulaoda 
Performance regression:
https://github.com/web-infra-dev/rspack/commit/7d4c6c2edb21822f0b065271f1d297c20b17e6b2#commitcomment-152531518
=> revert: Revert "refactor(rust): improve `replace_all_placeholder`"

crates/node_binding/binding.d.ts, crates/node_binding/src/lib.rs, packages/rspack/src/Compiler.ts
rename Rspack to JsCompiler to follow binding naming convention
=> refactor: rename Rspack to JsCompiler

Cargo.toml
This pull request includes a small change to the `Cargo.toml` file. The change increases the `codegen-units` value to 16 for the development profile to improve build performance.
* [`Cargo.toml`](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542R204): Increased `codegen-units` to 16 in the `[profile.dev]` section to enhance build performance.
=> fix: build cli dev failed

packages/rspack-test-tools/tests/configCases/split-chunks/cache-group-test/rspack.config.js, packages/rspack/etc/core.api.md, packages/rspack/src/ChunkGraph.ts, packages/rspack/src/ModuleGraph.ts, packages/rspack/src/builtin-plugin/SplitChunksPlugin.ts, packages/rspack/src/config/types.ts, packages/rspack/src/config/zod.ts, website/docs/en/plugins/webpack/split-chunks-plugin.mdx, website/docs/zh/plugins/webpack/split-chunks-plugin.mdx
close #8988
Supports chunkGraph and moduleGraph for `cacheGroup.test`, and update document
=> feat: supports chunkGraph and moduleGraph for cacheGroup.test

.github/workflows/ecosystem-benchmark.yml
using release profile to run bench
=> chore: run bench using release profile

.cargo/config.toml, Cargo.toml
related to https://github.com/web-infra-dev/rspack/pull/9334, this is a more formal solution thanks to @Brooooooklyn 
borrow from https://github.com/toeverything/AFFiNE/blob/57213781a88cea5b8e33d888a0f71419368b820e/.cargo/config.toml#L8 to avoid MacOS linker bug, 
related info: https://stackoverflow.com/questions/2906147/what-does-the-all-load-linker-flag-do
=> fix: force load all symbol

Cargo.toml
opt-level "s" cause 30% size reduction and 5% performance regression, we will find another way to reduce size while keep runtime performance
=> perf: revert opt-level to 3

website/docs/en/guide/start/quick-start.mdx
Fixed letter casing of Re.Pack in the docs to be consistent and right
=> docs: fix letter casing of Re.Pack

packages/rspack/src/loader-runner/index.ts
=> fix: allow loaderContext methods to be called independently of context

.github/workflows/release.yml, crates/node_binding/package.json, npm/darwin-arm64/package.json, npm/darwin-x64/package.json, npm/linux-x64-gnu/package.json, npm/win32-x64-msvc/package.json, package.json, packages/create-rspack/package.json, packages/rspack-cli/package.json, packages/rspack-test-tools/package.json, packages/rspack-tracing/package.json, packages/rspack/package.json
=> chore: release 1.2.4

website/docs/en/api/javascript-api/index.mdx, website/docs/en/api/plugin-api/compiler-hooks.mdx, website/docs/en/contribute/development/releasing.md, website/docs/zh/api/javascript-api/index.mdx, website/docs/zh/api/plugin-api/compiler-hooks.mdx, website/docs/zh/contribute/development/releasing.md
1. Enhance compiler run hooks documentation, add some examples and notes.
2. Update release workflow, should run ecosystem CI before releasing.
=> docs: enhance compiler run hooks documentation

crates/node_binding/binding.d.ts, crates/node_binding/src/compilation/entries.rs, crates/node_binding/src/context_module_factory.rs, crates/node_binding/src/dependency.rs, crates/node_binding/src/dependency_block.rs, crates/node_binding/src/lib.rs, crates/node_binding/src/module.rs, crates/node_binding/src/module_graph_connection.rs, crates/rspack_core/src/context_module_factory.rs, packages/rspack/etc/core.api.md, packages/rspack/src/Compilation.ts, packages/rspack/src/DependenciesBlock.ts, packages/rspack/src/Dependency.ts, packages/rspack/src/Module.ts, packages/rspack/src/ModuleGraph.ts, packages/rspack/src/ModuleGraphConnection.ts
Reverts web-infra-dev/rspack#9352 as it panic in some cases
=> Revert "perf: reuse js dependency"

crates/node_binding/package.json, npm/darwin-arm64/package.json, npm/darwin-x64/package.json, npm/linux-x64-gnu/package.json, npm/win32-x64-msvc/package.json, package.json, packages/create-rspack/package.json, packages/rspack-cli/package.json, packages/rspack-test-tools/package.json, packages/rspack-tracing/package.json, packages/rspack/package.json
Release routine, 1.2.4 has Glibc version issue
=> chore: release 1.2.5

crates/rspack_plugin_extract_css/src/plugin.rs
=> fix: sort group by group index

packages/rspack/src/loader-runner/index.ts
=> perf(loader-runner): memoize resolver creation for improved performance

crates/rspack_core/src/compiler/compilation.rs
ModuleGraph should be stable when run compilation.finish, and there are a lot of information collection steps when running hooks.finishModules, so we should clean up entry dependencies at the beginning of compilation.finish.
=> fix: clean up deps at the beginning of compilation.finish

.github/renovate.json5
=> chore: enable renovate webpack

.github/CODEOWNERS
- Update code ownership to match the current repository structure.
- Removed some directories that no longer exist.
=> chore(codeowners): update code ownership to match repository structure

crates/rspack_plugin_css/src/utils.rs, packages/rspack-test-tools/tests/configCases/css/rspack-issue-9432/index.js, packages/rspack-test-tools/tests/configCases/css/rspack-issue-9432/index.module.css, packages/rspack-test-tools/tests/configCases/css/rspack-issue-9432/rspack.config.js
=> fix: build error with reserved keywords in CSS modules

crates/rspack_plugin_runtime/src/runtime_module/create_script.rs, crates/rspack_plugin_runtime/src/runtime_module/create_script_url.rs, crates/rspack_plugin_runtime/src/runtime_module/define_property_getters.rs, crates/rspack_plugin_runtime/src/runtime_module/ensure_chunk.rs, crates/rspack_plugin_runtime/src/runtime_module/runtime/create_script.ejs, crates/rspack_plugin_runtime/src/runtime_module/runtime/create_script_url.ejs, crates/rspack_plugin_runtime/src/runtime_module/runtime/define_property_getters.ejs, crates/rspack_plugin_runtime/src/runtime_module/runtime/ensure_chunk.ejs, crates/rspack_plugin_runtime/src/runtime_module/runtime/ensure_chunk_with_inline.ejs, packages/rspack-test-tools/tests/__snapshots__/Config.test.js.snap, packages/rspack-test-tools/tests/__snapshots__/NewCodeSplitting-config.test.js.snap, packages/rspack-test-tools/tests/__snapshots__/NewCodeSplitting-stats-output.test.js.snap, packages/rspack-test-tools/tests/__snapshots__/StatsAPI.test.js.snap, packages/rspack-test-tools/tests/__snapshots__/StatsOutput.test.js.snap, packages/rspack-test-tools/tests/configCases/rsdoctor/assets/rspack.config.js, packages/rspack-test-tools/tests/hookCases/normalModuleFactory#afterResolve/duplicate/output.snap.txt, packages/rspack-test-tools/tests/hookCases/normalModuleFactory#afterResolve/request/output.snap.txt, packages/rspack-test-tools/tests/hookCases/normalModuleFactory#afterResolve/resource/output.snap.txt, packages/rspack-test-tools/tests/hookCases/normalModuleFactory#resolve/resource/output.snap.txt, packages/rspack-test-tools/tests/statsAPICases/build-time-executed-runtime.js, packages/rspack-test-tools/tests/statsAPICases/exports.js, packages/rspack-test-tools/tests/statsAPICases/nested-modules.js, tests/webpack-test/__snapshots__/StatsTestCases.basictest.js.snap
Use [dojang](https://github.com/rspack-contrib/rspack-dojang) to render runtime modules, related to https://github.com/web-infra-dev/rspack/issues/5316
More detail summary see: https://github.com/web-infra-dev/rspack/pull/9079
- render create_script with dojang.
- render create_script_url with dojang.
- render define_property_getters with dojang
- render ensure_chunk with dojang
=> feat: render runtime template with dojang

crates/rspack_plugin_runtime/src/runtime_module/require_js_chunk_loading.rs, crates/rspack_plugin_runtime/src/runtime_module/runtime/require_chunk_loading.ejs, crates/rspack_plugin_runtime/src/runtime_module/runtime/require_chunk_loading_with_external_install_chunk.ejs, crates/rspack_plugin_runtime/src/runtime_module/runtime/require_chunk_loading_with_external_install_chunk.js, crates/rspack_plugin_runtime/src/runtime_module/runtime/require_chunk_loading_with_hmr.ejs, crates/rspack_plugin_runtime/src/runtime_module/runtime/require_chunk_loading_with_hmr_manifest.ejs, crates/rspack_plugin_runtime/src/runtime_module/runtime/require_chunk_loading_with_hmr_manifest.js, crates/rspack_plugin_runtime/src/runtime_module/runtime/require_chunk_loading_with_loading.ejs, crates/rspack_plugin_runtime/src/runtime_module/runtime/require_chunk_loading_with_loading.js, crates/rspack_plugin_runtime/src/runtime_module/runtime/require_chunk_loading_with_loading_matcher.ejs, crates/rspack_plugin_runtime/src/runtime_module/runtime/require_chunk_loading_with_on_chunk_load.ejs, crates/rspack_plugin_runtime/src/runtime_module/runtime/require_chunk_loading_with_on_chunk_load.js
Use [dojang](https://github.com/rspack-contrib/rspack-dojang) to render runtime modules, related to https://github.com/web-infra-dev/rspack/issues/5316
More detail summary see: https://github.com/web-infra-dev/rspack/pull/9079
- render require_chunk_loading runtime template with dojang
=> feat: render require_chunk_loading template with dojang

packages/rspack-cli/tests/api/type/js-api-cjs.test.ts, packages/rspack-cli/tests/api/type/js-api-esm.test.mts, packages/rspack-cli/tests/build/basic/basic.test.ts, packages/rspack-cli/tests/build/config/config.test.ts, packages/rspack-cli/tests/build/issue-4467/index.test.ts, packages/rspack-cli/tests/build/issue-6214/index.test.ts, packages/rspack-cli/tests/build/issue-6359/index.test.ts, packages/rspack-cli/tests/build/json/json.test.ts, packages/rspack-cli/tests/build/plugin-apply-error/plugin-apply-error.test.ts, packages/rspack-cli/tests/preview/basic/index.test.ts, packages/rspack-cli/tests/preview/ts-config-file/index.test.ts, packages/rspack-cli/tests/serve/basic/serve-basic.test.ts, packages/rspack-cli/tests/serve/flags/serve-flags.test.ts, packages/rspack-cli/tests/serve/plugin-apply-error/serve-plugin-apply-error.test.ts
This pull request focuses on improving the test suite by making the test cases run concurrently. This change aims to enhance the efficiency and speed of the test execution process. The most important changes include modifying test cases in various files to use the `it.concurrent` method.
=> test: improve cli test performance

crates/rspack_plugin_javascript/src/dependency/context/amd_require_context_dependency.rs, crates/rspack_plugin_javascript/src/dependency/context/import_context_dependency.rs, crates/rspack_plugin_javascript/src/dependency/context/mod.rs, crates/rspack_plugin_javascript/src/parser_plugin/amd/amd_define_dependency_parser_plugin.rs, crates/rspack_plugin_javascript/src/parser_plugin/amd/amd_require_dependencies_block_parser_plugin.rs, crates/rspack_plugin_javascript/src/parser_plugin/common_js_imports_parse_plugin.rs, crates/rspack_plugin_javascript/src/parser_plugin/import_parser_plugin.rs, crates/rspack_plugin_javascript/src/plugin/impl_plugin_for_js_plugin.rs, crates/rspack_plugin_javascript/src/utils/eval/eval_binary_expr.rs, crates/rspack_plugin_javascript/src/visitors/dependency/context_dependency_helper.rs, packages/rspack-test-tools/tests/configCases/amd/define-require-context/circular.js, packages/rspack-test-tools/tests/configCases/amd/define-require-context/index.js, packages/rspack-test-tools/tests/configCases/amd/define-require-context/rspack.config.js, packages/rspack-test-tools/tests/configCases/amd/define-require-context/templates/a.js, tests/webpack-test/cases/parsing/complex-require/test.filter.js, tests/webpack-test/cases/parsing/extract-amd.nominimize/test.filter.js, tests/webpack-test/cases/parsing/extract-amd.nominimize/warnings.js, tests/webpack-test/cases/parsing/extract-amd/test.filter.js, tests/webpack-test/cases/parsing/extract-amd/warnings.js, tests/webpack-test/cases/parsing/issue-2641/test.filter.js, tests/webpack-test/cases/parsing/issue-345/test.filter.js
support amd require a context dependency: `require(["./dir/" + file])`
=> feat: amd context require

website/docs/en/api/javascript-api/compiler.mdx, website/docs/zh/api/javascript-api/compiler.mdx
Add docs for `compiler.run` new arguments.
related PR: https://github.com/web-infra-dev/rspack/pull/9475
=> docs: compiler.run add option param

crates/node_binding/binding.d.ts, crates/node_binding/src/normal_module_factory.rs, crates/node_binding/src/plugins/interceptor.rs, packages/rspack-test-tools/tests/configCases/plugins/normal-module-replacement-plugin-args/index.js, packages/rspack-test-tools/tests/configCases/plugins/normal-module-replacement-plugin-args/request.v1.js, packages/rspack-test-tools/tests/configCases/plugins/normal-module-replacement-plugin-args/request.v2.js, packages/rspack-test-tools/tests/configCases/plugins/normal-module-replacement-plugin-args/rspack.config.js, packages/rspack/etc/core.api.md, packages/rspack/src/Module.ts, packages/rspack/src/taps/normalModuleFactory.ts
add contextInfo.issuerLayer for nmf resolve hooks
=> feat: add contextInfo.issuerLayer for nmf resolve hooks

website/docs/en/guide/migration/cra.mdx, website/docs/en/guide/start/quick-start.mdx, website/docs/zh/api/plugin-api/compiler-hooks.mdx, website/docs/zh/guide/migration/cra.mdx
Update CRA migration guide to use the latest Rsbuild introduction and image.
=> docs: update CRA migration guide

website/docs/en/contribute/development/building.md, website/docs/en/contribute/development/debugging.mdx, website/docs/zh/contribute/development/building.md, website/docs/zh/contribute/development/debugging.mdx
Update doc to reflect command renaming
Renaming happened in commit 5458f293e0
=> docs: update local debugging command

crates/node_binding/src/compilation/mod.rs, packages/rspack-test-tools/tests/configCases/compilation/add-include/rspack.config.js, packages/rspack/src/Compilation.ts
feat: improve add include error msg
=> feat: improve add include error msg

crates/node_binding/binding.d.ts, crates/node_binding/src/compilation/mod.rs, packages/rspack-test-tools/tests/configCases/hooks/update-asset-return-undefined/rspack.config.js, packages/rspack-test-tools/tests/configCases/hooks/update-asset-return-undefined/test.config.js, packages/rspack/etc/core.api.md, packages/rspack/src/Compilation.ts
fix: update asset can return undefined
=> fix: update asset can return undefined

crates/node_binding/package.json, npm/darwin-arm64/package.json, npm/darwin-x64/package.json, npm/linux-x64-gnu/package.json, npm/win32-x64-msvc/package.json, package.json, packages/create-rspack/package.json, packages/rspack-cli/package.json, packages/rspack-test-tools/package.json, packages/rspack-tracing/package.json, packages/rspack/package.json
=> chore: release v1.2.7

website/components/RandomMemberList.module.scss, website/components/RandomMemberList.tsx
1. Invite @stormslowly to join the Rspack core team 🎉
Contributions:
- https://github.com/web-infra-dev/rspack/commits?author=stormslowly
- https://github.com/web-infra-dev/rspack/issues?q=commenter:stormslowly
2. Display Bluesky icons for some of the members.
=> docs: invite @stormslowly to Rspack core team

website/docs/zh/guide/start/quick-start.mdx
Remove MarsCode, see https://x.com/MarsCode_Team/status/1894930404312015066
=> docs: update quick start guide

crates/node_binding/src/module.rs, crates/rspack_core/src/external_module.rs, crates/rspack_plugin_library/src/modern_module_library_plugin.rs, packages/rspack-test-tools/tests/configCases/externals/user-request/index.js, packages/rspack-test-tools/tests/configCases/externals/user-request/rspack.config.js, packages/rspack-test-tools/tests/configCases/externals/user-request/test.config.js
=> fix: support access to userRequest of ExternalModule

crates/rspack_core/src/cache/persistent/version.rs, crates/rspack_fs/src/memory_fs.rs, crates/rspack_fs/src/native_fs.rs, crates/rspack_fs/src/read.rs, packages/rspack-test-tools/tests/cacheCases/common/build-dependencies-dir/file.js, packages/rspack-test-tools/tests/cacheCases/common/build-dependencies-dir/index.js, packages/rspack-test-tools/tests/cacheCases/common/build-dependencies-dir/rspack.config.js
Persistent cache support buildDependencies are directory. https://github.com/web-infra-dev/rspack/issues/9204
=> feat(core): enhanced version hashing to support directory build dependencies

website/docs/en/api/runtime-api/module-variables.mdx, website/docs/en/config/output.mdx, website/docs/zh/api/runtime-api/module-variables.mdx, website/docs/zh/config/output.mdx
Improve publicPath with more details and examples:
- Add "Automatic publicPath"
- Improve "Dynamically set publicPath"
=> docs: improve publicPath with more details and examples

packages/rspack-test-tools/src/case/config.ts, packages/rspack-test-tools/src/case/new-code-splitting.ts
This pull request includes changes to the `packages/rspack-test-tools` to improve the configuration of test cases by modifying the `concurrent` property.
=> test: modify concurrent to 5 to increase the config test concurrency

website/docs/en/types/entrypoint.mdx, website/docs/zh/types/entrypoint.mdx
follow up docs for https://github.com/web-infra-dev/rspack/pull/9625
=> docs: add `entrypoint.getEntrypointChunk` to documentation

crates/rspack_plugin_javascript/src/parser_plugin/define_plugin/parser.rs, packages/rspack-test-tools/tests/configCases/parsing/recursion-define/index.js, packages/rspack-test-tools/tests/configCases/parsing/recursion-define/rspack.config.js
Avoid endless recursion, for example: `new DefinePlugin({ "typeof a": "typeof a" })`
=> fix: define with recursion value

website/docs/en/api/plugin-api/index.mdx, website/docs/zh/api/plugin-api/index.mdx
=> docs: Writing Plugins Compatible with Rspack and Webpack

packages/rspack-cli/package.json, packages/rspack/package.json, pnpm-lock.yaml, tests/e2e/package.json
- upgrade @rspack/dev-server to `1.1.0`
- upgrade webpack-dev-server to `5.2.0` which is the latest version
- dedupe pnpm dependencies
=> chore: upgrade @rspack/dev-server and webpack-dev-server

crates/node_binding/binding.d.ts, crates/node_binding/scripts/banner.d.ts, crates/node_binding/src/modules/normal_module.rs, crates/node_binding/src/plugins/js_loader/mod.rs, crates/node_binding/src/plugins/mod.rs, packages/rspack-test-tools/tests/configCases/normal-module/module-instance/passthrough-loader.js, packages/rspack-test-tools/tests/configCases/normal-module/module-instance/rspack.config.js, website/docs/zh/types/module.mdx
support read `NormalModule.loaders`
=> feat: support read `NormalModule.loaders`

tests/webpack-test/ConfigTestCases.template.js, tests/webpack-test/StatsTestCases.basictest.js, tests/webpack-test/TestCases.template.js, website/docs/en/config/other-options.mdx, website/docs/zh/config/other-options.mdx
=> docs: improve docs for amd

Cargo.lock, Cargo.toml, packages/rspack/scripts/prepare-container-runtime.js
Upgrade SWC from 14.0.1 to 16.5.0.
More ChangeLog see:  https://github.com/swc-project/swc/blob/main/CHANGELOG.md#changelog
=> feat(deps)!: update SWC version to 16.5.0

website/docs/zh/contribute/index.mdx
=> docs(zh): fix typo in contribute/index.mdx

Cargo.lock, Cargo.toml
remove unsed feature for lightningcss and it save 20s compile time in my computer for release build
=> chore: remove unused feature for lightningcss

.github/workflows/ecosystem-ci.yml
plugin test is missed ecosystem ci workflow, so add it
=> test: ecosystem CI add plugin test

crates/node_binding/binding.d.ts, crates/node_binding/src/resolver.rs, crates/node_binding/src/resource_data.rs, crates/rspack_core/src/normal_module_factory.rs, crates/rspack_core/src/resolver/mod.rs, crates/rspack_loader_runner/src/content.rs, packages/rspack-test-tools/tests/configCases/externals/resolve-callback/index.js, packages/rspack-test-tools/tests/configCases/externals/resolve-callback/node_modules/package.json, packages/rspack-test-tools/tests/configCases/externals/resolve-callback/webpack.config.js, packages/rspack/etc/core.api.md, packages/rspack/src/Module.ts, packages/rspack/src/Resolver.ts, packages/rspack/src/builtin-plugin/ExternalsPlugin.ts, packages/rspack/src/config/adapterRuleUse.ts, packages/rspack/src/config/types.ts, packages/rspack/src/config/zod.ts
Support externals getResolve callback third argument, checkout added test for usage
=> feat: externals getResolve callback third argument

Cargo.lock, crates/rspack_core/src/compiler/compilation.rs, crates/rspack_core/src/compiler/make/cutout/has_module_graph_change.rs, crates/rspack_core/src/compiler/module_executor/execute.rs, crates/rspack_core/src/concatenated_module.rs, crates/rspack_core/src/context_module.rs, crates/rspack_core/src/external_module.rs, crates/rspack_core/src/module.rs, crates/rspack_core/src/normal_module.rs, crates/rspack_core/src/old_cache/occasion/code_generate.rs, crates/rspack_core/src/raw_module.rs, crates/rspack_core/src/self_module.rs, crates/rspack_macros/src/runtime_module.rs, crates/rspack_macros_test/Cargo.toml, crates/rspack_plugin_dll/src/dll_entry/dll_module.rs, crates/rspack_plugin_dll/src/dll_reference/delegated_module.rs, crates/rspack_plugin_extract_css/src/css_module.rs, crates/rspack_plugin_lazy_compilation/src/module.rs, crates/rspack_plugin_mf/src/container/container_entry_module.rs, crates/rspack_plugin_mf/src/container/fallback_module.rs, crates/rspack_plugin_mf/src/container/remote_module.rs, crates/rspack_plugin_mf/src/sharing/consume_shared_module.rs, crates/rspack_plugin_mf/src/sharing/provide_shared_module.rs, crates/rspack_plugin_sri/Cargo.toml
Modify `module.code_generation` to async function to prevent using `block_on` during code generation.
=> refactor: modify `module.code_generation` to async fn

.github/actions/pnpm/install-dependencies/action.yml
frozen-lockfile should be true by default in CI, it's wrongly set to false now
=> chore: change frozen-lockfile default value to true

Cargo.lock, Cargo.toml
See https://github.com/web-infra-dev/rspack-resolver/releases/tag/v0.5.3
=> chore: update rspack-resolver

crates/node_binding/binding.d.ts, crates/node_binding/src/plugins/js_loader/context.rs, crates/node_binding/src/raw_options/raw_builtins/raw_copy.rs, packages/rspack-test-tools/tests/configCases/normal-module/module-instance/rspack.config.js, packages/rspack/src/loader-runner/index.ts
Align with https://github.com/webpack/webpack/blob/3aa6b6bc3a6452b36df8eb8324b466a7d218e143/types.d.ts#L8318
=> fix: rename loader item request to loader

crates/node_binding/package.json, npm/darwin-arm64/package.json, npm/darwin-x64/package.json, npm/linux-x64-gnu/package.json, npm/wasm32-wasi/package.json, npm/win32-x64-msvc/package.json, package.json, packages/create-rspack/package.json, packages/rspack-cli/package.json, packages/rspack-test-tools/package.json, packages/rspack-tracing/package.json, packages/rspack/package.json
=> release: 1.3.0-beta.0

crates/rspack_plugin_devtool/Cargo.toml, crates/rspack_plugin_devtool/src/eval_dev_tool_module_plugin.rs, crates/rspack_plugin_devtool/src/eval_source_map_dev_tool_plugin.rs
Remove `block_on` in devtool to prevent deadlock.
=> refactor: remove `block_on` in devtool

Cargo.lock, Cargo.toml
- update swc_core versions to 16.7.0
- update swc_ecma_minifier version to v12.2.0
=> chore: bump swc to v16.7.0

crates/rspack_plugin_sri/src/asset.rs, crates/rspack_plugin_sri/src/lib.rs
Improve the clarity and accuracy of diagnostic messages related to SSRI plugin. The changes focus on refining warning and error messages to provide more precise guidance to developers.
=> fix: improve diagnostic messages for Subresource Integrity plugin

packages/rspack-test-tools/tests/configCases/asset/filename/test.config.js, packages/rspack-test-tools/tests/configCases/builtins/entry-plugin-filename-string/test.config.js, packages/rspack-test-tools/tests/configCases/split-chunks-common/rspack-issue-4376/test.config.js
Enable concurrent mode of `block_on` releatd test cases
=> test: enable concurrent mode of `block_on` related test cases

website/docs/en/api/plugin-api/compilation-hooks.mdx, website/docs/en/api/plugin-api/compiler-hooks.mdx, website/docs/zh/api/plugin-api/compilation-hooks.mdx, website/docs/zh/api/plugin-api/compiler-hooks.mdx
docs: update shouldEmit hook type and add afterProcessAssets & shouldEmit example
=> docs: add afterProcessAssets and shouldEmit example

crates/node_binding/src/raw_options/raw_split_chunks/mod.rs, crates/rspack_plugin_split_chunks/src/common.rs, crates/rspack_plugin_split_chunks/src/plugin/module_group.rs
Remove `blocking_call_with_sync` in module layer filter
=> refactor: remove blocking_call_with_sync in module layer filter

Cargo.lock, crates/node_binding/src/raw_options/raw_builtins/raw_progress.rs, crates/rspack_core/src/compiler/compilation.rs, crates/rspack_ids/src/deterministic_chunk_ids_plugin.rs, crates/rspack_ids/src/deterministic_module_ids_plugin.rs, crates/rspack_ids/src/named_chunk_ids_plugin.rs, crates/rspack_ids/src/named_module_ids_plugin.rs, crates/rspack_ids/src/natural_chunk_ids_plugin.rs, crates/rspack_ids/src/natural_module_ids_plugin.rs, crates/rspack_ids/src/occurrence_chunk_ids_plugin.rs, crates/rspack_plugin_dll/src/flag_all_modules_as_used_plugin.rs, crates/rspack_plugin_javascript/src/plugin/flag_dependency_usage_plugin.rs, crates/rspack_plugin_javascript/src/plugin/side_effects_flag_plugin.rs, crates/rspack_plugin_progress/Cargo.toml, crates/rspack_plugin_progress/src/lib.rs, crates/rspack_plugin_rsdoctor/src/plugin.rs, tasks/benchmark/benches/groups/build_chunk_graph.rs
- Modify `module_ids` hook to async
- Modify `chunk_ids` hook to async
- Modify `optimize_dependencies` hook to async
- Modify progress plugin methods to async and remove `blocking_call_with_sync` of handler tsfn
=> refactor: async ids hooks and remove blocking in progress plugin

crates/node_binding/src/raw_options/raw_builtins/raw_sri.rs, crates/node_binding/src/raw_options/raw_module/mod.rs, crates/rspack_core/src/compiler/compilation.rs, crates/rspack_core/src/normal_module.rs, crates/rspack_core/src/options/module.rs, crates/rspack_core/src/parser_and_generator.rs, crates/rspack_plugin_asset/src/lib.rs, crates/rspack_plugin_css/src/parser_and_generator/mod.rs, crates/rspack_plugin_javascript/src/parser_and_generator/mod.rs, crates/rspack_plugin_javascript/src/plugin/mangle_exports_plugin.rs, crates/rspack_plugin_json/src/lib.rs, crates/rspack_plugin_rsdoctor/src/plugin.rs, crates/rspack_plugin_sri/src/asset.rs, crates/rspack_plugin_sri/src/config.rs, crates/rspack_plugin_wasm/src/parser_and_generator.rs
- Modify codegen hooks to async
- Remove `blocking_call_with_sync` in json parser
- Remove `blocking_call_with_sync` in sri plugin
=> refactor: remove blocking call in json parser and SRI plugin

tests/webpack-test/configCases/externals/import-assertion/test.filter.js
=> fix: import-assertion test case should not run in node 16

tests/webpack-test/configCases/externals/import-assertion/test.filter.js
=> chore: import-assertion test case run failed

crates/rspack_plugin_library/src/modern_module_library_plugin.rs, packages/rspack-test-tools/tests/configCases/externals/reexport-star/__snapshot__/case5.txt, packages/rspack-test-tools/tests/configCases/externals/reexport-star/__snapshot__/case6.txt, packages/rspack-test-tools/tests/configCases/externals/reexport-star/case5.js, packages/rspack-test-tools/tests/configCases/externals/reexport-star/case6.js, packages/rspack-test-tools/tests/configCases/externals/reexport-star/index.js, packages/rspack-test-tools/tests/configCases/externals/reexport-star/rspack.config.js
Fix https://github.com/web-infra-dev/rslib/issues/859.
=> fix(modern-module): correct count non export star connections

packages/rspack/src/builtin-plugin/css-extract/utils.ts
=> refactor(rspack): simplify relative path check in stringifyRequest function

packages/rspack/src/config/adapter.ts
=> chore: fix typo

crates/node_binding/src/raw_options/raw_builtins/raw_lazy_compilation.rs, crates/rspack_plugin_lazy_compilation/src/plugin.rs
Remove `blocking_call_with_sync` in lazy compilation
=> refactor: async lazy compilation test tsfn

crates/rspack_core/src/normal_module.rs, crates/rspack_core/src/parser_and_generator.rs, crates/rspack_plugin_asset/src/lib.rs, crates/rspack_plugin_css/src/parser_and_generator/mod.rs
- Remove sync `update_hash` and use async `get_runtime_hash` instead
=> refactor: async parser_and_generator hashing

website/docs/en/config/output.mdx, website/docs/zh/config/output.mdx
add `modern-module` docs
https://webpack.js.org/configuration/output/#type-modern-module
=> docs: add `modern-module` docs

crates/rspack_core/src/build_chunk_graph/available_modules.rs, crates/rspack_core/src/build_chunk_graph/new_code_splitter.rs
Fix useless iterator and reduce some small allocations.
eg.
change 
```
for i in 0..100 { 
let mut v = vec![];
}
```
to
```
let mut v = vec![];
for i in 0..100 { 
v.clear()
}
```
=> perf: remove useless iterator in new code splitting and some allocations

crates/node_binding/package.json, npm/darwin-arm64/package.json, npm/darwin-x64/package.json, npm/linux-x64-gnu/package.json, npm/wasm32-wasi/package.json, npm/win32-x64-msvc/package.json, package.json, packages/create-rspack/package.json, packages/rspack-cli/package.json, packages/rspack-test-tools/package.json, packages/rspack-tracing/package.json, packages/rspack/package.json
=> chore: release v1.3.0

website/docs/en/blog/announcing-1-3.mdx, website/docs/zh/blog/announcing-1-3.mdx
- add banner to 1.3 blog
- fix `builtHttp` example
=> docs: add banner to 1.3 blog

website/docs/en/blog/announcing-1-3.mdx
docs: fix lynx link in en blog
=> docs: fix lynx link in en blog

Cargo.lock, Cargo.toml
See: https://github.com/napi-rs/napi-rs/pull/2523
This is necessary for rspack wasi to run with node.js.
=> chore: bump napi-build 2.1.4 -> 2.1.6

crates/rspack_core/src/build_chunk_graph/available_modules.rs
close #9833
If a chunk is removed as its modules are all removed, all its children should be removed as well
=> fix: should remove all sub chunks if chunk is removed

crates/rspack_storage/src/fs/error.rs, crates/rspack_storage/src/fs/mod.rs, crates/rspack_storage/src/pack/manager/mod.rs, crates/rspack_storage/src/pack/strategy/split/handle_file.rs, crates/rspack_storage/src/pack/strategy/split/read_pack.rs, crates/rspack_storage/src/pack/strategy/split/read_scope.rs, crates/rspack_storage/src/pack/strategy/split/validate_scope.rs, crates/rspack_storage/src/pack/strategy/split/write_pack.rs, crates/rspack_storage/src/pack/strategy/split/write_scope.rs, crates/rspack_storage/tests/build.rs, crates/rspack_storage/tests/dev.rs, crates/rspack_storage/tests/error.rs, crates/rspack_storage/tests/expire.rs, crates/rspack_storage/tests/lock.rs, crates/rspack_storage/tests/multi.rs, crates/rspack_storage/tests/release.rs
improve error and result of rspack_storage crate
=> refactor: improve storage error and result

crates/node_binding/package.json, npm/darwin-arm64/package.json, npm/darwin-x64/package.json, npm/linux-x64-gnu/package.json, npm/wasm32-wasi/package.json, npm/win32-x64-msvc/package.json, package.json, packages/create-rspack/package.json, packages/rspack-cli/package.json, packages/rspack-test-tools/package.json, packages/rspack-tracing/package.json, packages/rspack/package.json
=> chore: release v1.3.1

website/components/RandomMemberList.tsx, website/docs/en/misc/planning/roadmap.mdx, website/docs/en/misc/team/core-team.mdx, website/docs/en/misc/team/emeriti.mdx, website/docs/zh/misc/planning/roadmap.mdx, website/docs/zh/misc/team/core-team.mdx, website/docs/zh/misc/team/emeriti.mdx
Invite @CPunisher to join the Rspack core team 🎉
CPunisher has made significant contributions to both Rspack and SWC. He is the primary contributor to Rspack's Wasm support. Thank you for your invaluable contributions to Rstack ecosystem! ❤️
- https://github.com/web-infra-dev/rspack/commits?author=CPunisher
- https://github.com/web-infra-dev/rspack/issues?q=commenter:CPunisher
=> docs: invite @CPunisher to Rspack core team

packages/rspack-test-tools/tests/configCases/loader-parallel/parallel-option/index.js, packages/rspack-test-tools/tests/configCases/loader-parallel/parallel-option/rspack.config.js
=> test(loader-parallel): test `parallel-option` would only recieve `true` in parallel mode

website/docs/en/guide/tech/next.mdx, website/docs/zh/guide/tech/next.mdx
This PR adds basic guide for Next.js, the content still needs polishing, so we did not add this page to the sidebar.
More content will be added in subsequent PRs.
=> docs: add basic guide for Next.js

crates/rspack_core/src/build_chunk_graph/new_code_splitter.rs, packages/rspack-test-tools/tests/configCases/chunk-graph/merge-chunks/entry1.js, packages/rspack-test-tools/tests/configCases/chunk-graph/merge-chunks/entry2.js, packages/rspack-test-tools/tests/configCases/chunk-graph/merge-chunks/lib1.js, packages/rspack-test-tools/tests/configCases/chunk-graph/merge-chunks/lib2.js, packages/rspack-test-tools/tests/configCases/chunk-graph/merge-chunks/rspack.config.js, packages/rspack-test-tools/tests/configCases/chunk-graph/merge-chunks/test.config.js, tests/webpack-test/__snapshots__/StatsTestCases.basictest.js.snap
fix #9870
example: 
```
import(/*webpackChunkName: page*/'page1')
import(/*webpackChunkName: page*/'page2')
```
If there are multiple blocks points to the same chunk, there should be only 1 chunk.
Now we merge the inputs instead of merge created chunks, this way we can skip re-calculating chunk-index.
=> fix: should merge chunkCreateRoot instead of merge chunks later

crates/node_binding/package.json, npm/darwin-arm64/package.json, npm/darwin-x64/package.json, npm/linux-x64-gnu/package.json, npm/wasm32-wasi/package.json, npm/win32-x64-msvc/package.json, package.json, packages/create-rspack/package.json, packages/rspack-cli/package.json, packages/rspack-test-tools/package.json, packages/rspack-tracing/package.json, packages/rspack/package.json
=> chore: release 1.3.2

website/docs/en/blog/announcing-1-3.mdx, website/docs/en/guide/features/lazy-compilation.mdx, website/docs/zh/blog/announcing-1-3.mdx, website/docs/zh/guide/features/lazy-compilation.mdx
fix the incorrect parameters used when creating the DevServer
Actually, compiler is second parameter.
=> docs: fix the incorrect parameters used when creating the DevServer

.vscode/settings.json
three linked projects will cause triple check during checkonSave in RA which make the check much slower and is unnecessary, so remove it
=> chore: remove unnecessary linked project

website/docs/zh/config/experiments.mdx
Document content display error
=> docs: Document content display error in 'experiments.mdx'

.github/actions/docker/linux-build/action.yml, .github/actions/pnpm/install-binding-dependencies/action.yml, .github/actions/rustup/action.yml
This PR will install clippy, miri, rustfmt when setup rustup.
=> ci: rustup install clippy

.github/workflows/ci.yml, .github/workflows/ecosystem-benchmark.yml, .github/workflows/reusable-build-bench.yml, .github/workflows/reusable-build-build.yml, .github/workflows/reusable-build-test.yml, .github/workflows/reusable-build.yml
1. split reusable-build.yml to reusable-build-{build, test, bench}.yml
2. run rust checks when workflow files are changed
=> ci: split reusable-build.yml

crates/node_binding/package.json, npm/darwin-arm64/package.json, npm/darwin-x64/package.json, npm/linux-x64-gnu/package.json, npm/wasm32-wasi/package.json, npm/win32-x64-msvc/package.json, package.json, packages/create-rspack/package.json, packages/rspack-cli/package.json, packages/rspack-test-tools/package.json, packages/rspack-tracing/package.json, packages/rspack/package.json
=> chore: release v1.3.4

crates/rspack_core/src/dependency/dependency_template.rs, crates/rspack_plugin_javascript/src/dependency/esm/esm_compatibility_dependency.rs, crates/rspack_plugin_javascript/src/dependency/esm/esm_export_expression_dependency.rs, crates/rspack_plugin_javascript/src/dependency/esm/esm_export_header_dependency.rs, crates/rspack_plugin_javascript/src/dependency/esm/esm_export_imported_specifier_dependency.rs, crates/rspack_plugin_javascript/src/dependency/esm/esm_export_specifier_dependency.rs, crates/rspack_plugin_javascript/src/dependency/esm/esm_import_dependency.rs, crates/rspack_plugin_javascript/src/dependency/esm/esm_import_specifier_dependency.rs, crates/rspack_plugin_javascript/src/dependency/esm/external_module_dependency.rs, crates/rspack_plugin_javascript/src/dependency/esm/import_eager_dependency.rs, crates/rspack_plugin_javascript/src/dependency/esm/mod.rs, crates/rspack_plugin_javascript/src/dependency/esm/provide_dependency.rs, crates/rspack_plugin_javascript/src/plugin/impl_plugin_for_js_plugin.rs
relate to https://github.com/web-infra-dev/rspack/pull/9924
Add dynamic templates of javascript esm dependencies
=> refactor: dynamic templates of javascript esm dependencies

crates/node_binding/Cargo.toml, crates/node_binding/binding.d.ts, crates/node_binding/scripts/banner.d.ts, crates/node_binding/src/asset.rs, crates/node_binding/src/module.rs, crates/node_binding/src/modules/external_module.rs, crates/node_binding/src/modules/normal_module.rs, crates/node_binding/src/plugins/js_loader/context.rs, crates/rspack_napi/Cargo.toml, crates/rspack_napi/src/js_values/mod.rs, crates/rspack_napi/src/js_values/weak_ref.rs, crates/rspack_napi/src/lib.rs, packages/rspack-test-tools/tests/configCases/context-module/module-instance/rspack.config.js, packages/rspack-test-tools/tests/configCases/externals/module-instance/rspack.config.js, packages/rspack-test-tools/tests/configCases/normal-module/module-instance/rspack.config.js, tests/bench/ts-react.bench.ts
Using cache to improve module.loaders perf.
=> perf: js module loaders getter

crates/rspack_core/src/dependency/cached_const_dependency.rs, crates/rspack_core/src/dependency/const_dependency.rs, crates/rspack_core/src/dependency/mod.rs, crates/rspack_core/src/dependency/runtime_requirements_dependency.rs, crates/rspack_plugin_asset/src/asset_exports_dependency.rs, crates/rspack_plugin_css/src/dependency/export.rs, crates/rspack_plugin_css/src/dependency/import.rs, crates/rspack_plugin_css/src/dependency/local_ident.rs, crates/rspack_plugin_css/src/dependency/self_reference.rs, crates/rspack_plugin_css/src/dependency/url.rs, crates/rspack_plugin_css/src/plugin/impl_plugin_for_css_plugin.rs, crates/rspack_plugin_javascript/src/plugin/impl_plugin_for_js_plugin.rs, crates/rspack_plugin_json/src/json_exports_dependency.rs, crates/rspack_plugin_library/src/modern_module/import_dependency.rs, crates/rspack_plugin_library/src/modern_module/reexport_star_external_dependency.rs, crates/rspack_plugin_library/src/modern_module_library_plugin.rs
relate to https://github.com/web-infra-dev/rspack/pull/9924
Add dynamic templates of all dependencies
=> refactor: dynamic templates of all dependencies

packages/rspack-test-tools/etc/test-tools.api.md, packages/rspack-test-tools/src/processor/builtin.ts, packages/rspack-test-tools/src/processor/cache.ts, packages/rspack-test-tools/src/processor/defaults.ts, packages/rspack-test-tools/src/processor/diagnostic.ts, packages/rspack-test-tools/src/processor/hash.ts, packages/rspack-test-tools/src/processor/hook.ts, packages/rspack-test-tools/src/processor/normal.ts, packages/rspack-test-tools/src/processor/stats-api.ts, packages/rspack-test-tools/src/processor/stats.ts, packages/rspack-test-tools/src/processor/treeshaking.ts, packages/rspack-test-tools/tests/diagnosticsCases/plugins/circular-dependency-plugin/rspack.config.js
=> test: not to print unnecessary message when testing

.github/workflows/ecosystem-ci.yml
Following up https://github.com/rspack-contrib/rspack-ecosystem-ci/pull/76
=> ci: add lynx-stack to ecosystem-ci

website/docs/en/blog/_meta.json, website/docs/en/blog/index.mdx, website/docs/en/blog/rspack-next-partner.mdx, website/project-words.txt, website/rspress.config.ts
=> docs: add rspack & next.js partner annoucement

crates/rspack_core/src/external_module.rs, tests/webpack-test/configCases/externals/externals-array/test.filter.js, tests/webpack-test/configCases/externals/externals-array/webpack.config.js
fix https://github.com/web-infra-dev/rspack/issues/9976
=> fix: external with properties array list in module format

crates/rspack_core/src/external_module.rs, crates/rspack_plugin_library/src/umd_library_plugin.rs, tests/webpack-test/configCases/externals/async-externals/test.filter.js, tests/webpack-test/configCases/externals/externals-in-commons-chunk/test.filter.js, tests/webpack-test/configCases/externals/externals-system-custom/test.filter.js, tests/webpack-test/configCases/externals/optional-externals-root/test.filter.js, tests/webpack-test/configCases/externals/optional-externals-umd/test.filter.js, tests/webpack-test/configCases/externals/optional-externals-umd2-mixed/test.filter.js, tests/webpack-test/configCases/externals/optional-externals-umd2/test.filter.js
- should not throw error when a external module is optional
- support properties when using import format
=> fix: external module to pass webpack test cases

crates/rspack_plugin_javascript/src/dependency/esm/esm_export_imported_specifier_dependency.rs, crates/rspack_plugin_javascript/src/dependency/esm/esm_import_dependency.rs, crates/rspack_plugin_javascript/src/dependency/esm/external_module_dependency.rs, crates/rspack_plugin_javascript/src/parser_plugin/esm_export_dependency_parser_plugin.rs, crates/rspack_plugin_javascript/src/parser_plugin/esm_import_dependency_parser_plugin.rs, crates/rspack_plugin_json/src/lib.rs
=> refactor: remove useless code

.gitignore, .vscode/settings.json, crates/rspack_core/src/chunk_graph/chunk_graph_module.rs, crates/rspack_core/src/compiler/compilation.rs, crates/rspack_core/src/compiler/mod.rs, crates/rspack_core/src/normal_module.rs, crates/rspack_plugin_javascript/src/plugin/side_effects_flag_plugin.rs, crates/rspack_plugin_swc_js_minimizer/src/lib.rs, crates/rspack_plugin_swc_js_minimizer/src/minify.rs, crates/rspack_tracing/src/chrome.rs
there're some key steps missing trace so add more tracing to these steps
also propagate parent span to rayon to keep parent relation
* before: 
* after
=> chore: add more tracing data

crates/rspack_fs/src/native_fs.rs
Follow https://github.com/web-infra-dev/rspack/pull/9747
=> fix(wasm): align trait methods for `native_fs`

pnpm-lock.yaml, website/package.json
https://github.com/web-infra-dev/rspress/releases/tag/v2.0.0-alpha.11
1. fix the firefox white screen
2. fix ssg rendering error
resolve https://github.com/web-infra-dev/rspack/issues/10023
=> chore(deps): update rspress to 2.0.0-alpha.11

crates/rspack_core/src/chunk_graph/chunk_graph_chunk.rs, crates/rspack_core/src/incremental/mutations.rs, crates/rspack_plugin_merge_duplicate_chunks/src/lib.rs
If the chunk id changes, the chunk is affected:
https://github.com/web-infra-dev/rspack/blob/a257f44c28815e11a1eb3f37b19f87eabaebb4c7/crates/rspack_core/src/chunk.rs#L687-L688
=> fix(incremental): chunk id change should affect associate chunk

website/docs/en/blog/rspack-next-partner.mdx, website/docs/en/guide/optimization/profile.mdx, website/docs/en/guide/optimization/use-rsdoctor.mdx, website/docs/en/guide/tech/next.mdx, website/docs/zh/guide/optimization/profile.mdx, website/docs/zh/guide/optimization/use-rsdoctor.mdx
- Updated Rsdoctor introduction, copied from https://rsdoctor.dev/guide/start/intro.
- Added Windows `cross-env` guide.
- Removed duplicate content from Rsdoctor documentation to reduce maintenance costs
=> docs: enhance Rsdoctor analysis guide

crates/node_binding/binding.d.ts, crates/node_binding/src/lib.rs, crates/rspack_core/src/compiler/mod.rs, crates/rspack_plugin_progress/src/lib.rs, packages/rspack/src/Compiler.ts
fix https://github.com/web-infra-dev/rspack/issues/8444
=> fix: remove progressbar instance when closing compiler

crates/rspack_plugin_javascript/src/visitors/dependency/context_dependency_helper.rs, tests/webpack-test/cases/parsing/complex-require/cjs.js
Fix panic when:
```js
require(String.raw`./a.js`);
```
Relate #10003
=> fix: require with string raw

packages/rspack-test-tools/tests/diagnosticsCases/module-build-failed/asset-module-build-failed/stats.err, packages/rspack-test-tools/tests/diagnosticsCases/module-build-failed/loader-emit-diagnostic/stats.err, packages/rspack-test-tools/tests/diagnosticsCases/module-build-failed/loader-emit-error/stats.err, packages/rspack-test-tools/tests/diagnosticsCases/module-build-failed/loader-emit-warning/stats.err, packages/rspack-test-tools/tests/diagnosticsCases/module-build-failed/loader-throw-error/stats.err, packages/rspack-test-tools/tests/hotCases/css/recovery/__snapshots__/web/2.snap.txt, packages/rspack/rslib.config.ts
custom Rslib minify options for `@rspack/core` to output a smaller bundle size.
- `dist/cssExtractHmr.js`: 6.2 kB  ->  5.6 kB
- `dist/cssExtractLoader.js`: 10.6 kB  ->  9.6 kB
- `dist/worker.js`: 71.5 kB  ->  62.5 kB
- `dist/index.js`: 772.0 kB  ->  705.9 kB
**tsup**:
- `dist/cssExtractHmr.js`: 5.70 KB = 5.57 kB
- `dist/cssExtractLoader.js`: 10.27 KB = 10.03 kB
- `dist/worker.js`: 66.83 KB = 65.26 kB
- `dist/index.js`: 695.87 KB = 712.57 kB
https://github.com/web-infra-dev/rspack/pull/9899#issuecomment-2805135559
=> perf(build): custom Rslib minify options for `@rspack/core`

crates/rspack_plugin_hmr/src/lib.rs, tests/webpack-test/hotCases/disposing/runtime-independent-filename/test.filter.js
warning when hot update main content filename is conflicted, and merge the hot update content
=> fix: conflict hot update main content warning

crates/node_binding/binding.d.ts, crates/node_binding/scripts/banner.d.ts, crates/node_binding/src/module.rs, crates/node_binding/src/modules/macros.rs, packages/rspack/etc/core.api.md, packages/rspack/src/ChunkGraph.ts, packages/rspack/src/ConcatenatedModule.ts, packages/rspack/src/ContextModule.ts, packages/rspack/src/ExternalModule.ts, packages/rspack/src/Module.ts, packages/rspack/src/NormalModule.ts
close https://github.com/web-infra-dev/rspack/issues/5766
- support setter of `loaderContext.module.factoryMeta`
- support readableIdentifier of `Module`
- support `chunkGraph.getOrderedChunkModulesIterable()`
=> feat: support svg-chunk-webpack-plugin

website/docs/en/guide/features/builtin-lightningcss-loader.mdx, website/docs/zh/guide/features/builtin-lightningcss-loader.mdx
Add docs for lightningcss `errorRecovery` option.
Ref: https://github.com/web-infra-dev/rspack/pull/10076#pullrequestreview-2777492705
=> docs: lightningcss errorRecovery option

crates/rspack_plugin_javascript/src/parser_plugin/common_js_imports_parse_plugin.rs, packages/rspack-test-tools/tests/configCases/parsing/rspack-issue-10005/index.js, packages/rspack-test-tools/tests/configCases/parsing/rspack-issue-10005/rspack.config.js
=> fix: allow assignment of `require` identifier

Cargo.lock, crates/rspack_core/Cargo.toml, crates/rspack_core/src/chunk_graph/chunk_graph_module.rs, crates/rspack_core/src/compiler/compilation.rs, crates/rspack_core/src/compiler/mod.rs, crates/rspack_hook/Cargo.toml, crates/rspack_hook/src/lib.rs, crates/rspack_macros/src/hook.rs, crates/rspack_macros/src/plugin.rs
=> chore: add tracing for hook call in define_hook macro

packages/rspack-cli/src/utils/profile.ts, website/docs/en/contribute/development/_meta.json, website/docs/en/contribute/development/debugging.mdx, website/docs/en/contribute/development/profiling.md, website/docs/en/contribute/development/tracing.md, website/docs/zh/contribute/development/_meta.json, website/docs/zh/contribute/development/debugging.mdx, website/docs/zh/contribute/development/profiling.md, website/docs/zh/contribute/development/tracing.md
rewrite tracing doc and make it into a separate section
=> docs: rewrite tracing section

website/docs/en/contribute/development/tracing.md, website/docs/zh/contribute/development/tracing.md
use `##Tracing` will cause render wrong title 
* before
* after
=> docs: fix tracing title

website/docs/en/config/optimization.mdx, website/docs/zh/config/optimization.mdx
This PR adds the  `optimization.removeAvailableModules` config to documentation.
See https://github.com/web-infra-dev/rspack/issues/9834 for background.
resolve https://github.com/web-infra-dev/rspack/issues/9834
=> docs: add `optimization.removeAvailableModules` config

crates/rspack_core/src/artifacts/chunk_hashes_artifact.rs, crates/rspack_core/src/artifacts/mod.rs, crates/rspack_core/src/chunk.rs, crates/rspack_core/src/compiler/compilation.rs, crates/rspack_core/src/compiler/make/repair/mod.rs, crates/rspack_core/src/compiler/mod.rs, crates/rspack_core/src/compiler/rebuild.rs, crates/rspack_core/src/incremental/mod.rs, crates/rspack_core/src/incremental/mutations.rs, packages/rspack-test-tools/tests/NewIncremental-watch.test.js, packages/rspack-test-tools/tests/watchCases/hashes/runtimeChunkFullHash/0/warnings.js, tasks/benchmark/benches/groups/build_chunk_graph.rs
disable incremental for chunk hashes when chunk depend on full hash
=> fix(incremental): fallback when chunk depend on full hash

crates/rspack_core/src/chunk.rs, crates/rspack_core/src/compiler/compilation.rs, crates/rspack_core/src/incremental/mutations.rs
This should avoid some chunk re-render that its hash actually doesn't change
=> refactor(incremental): use ChunkSetHashes for chunk render

.github/workflows/ci.yml, .prettierrc.js, package.json, packages/create-rspack/template-react-js/src/main.jsx, scripts/build-npm.cjs
add missing cjs mjs in CI format checking
=> ci: add more JS extensions to workflow filters and format script

crates/rspack_core/src/compiler/compilation.rs, crates/rspack_core/src/compiler/make/mod.rs, crates/rspack_core/src/compiler/module_executor/ctrl.rs, crates/rspack_core/src/compiler/module_executor/execute.rs, crates/rspack_core/src/compiler/module_executor/mod.rs, crates/rspack_plugin_extract_css/src/plugin.rs, packages/rspack-test-tools/tests/configCases/css-extract/rebuild-module/index.js, packages/rspack-test-tools/tests/configCases/css-extract/rebuild-module/loader.js, packages/rspack-test-tools/tests/configCases/css-extract/rebuild-module/render.css, packages/rspack-test-tools/tests/configCases/css-extract/rebuild-module/render.js, packages/rspack-test-tools/tests/configCases/css-extract/rebuild-module/rspack.config.js
fix https://github.com/web-infra-dev/rspack/issues/9778
=> fix: should rebuild css module when rebuild css extract entry

crates/rspack_loader_runner/src/runner.rs, packages/rspack/src/exports.ts, packages/rspack/src/loader-runner/index.ts, packages/rspack/src/trace/index.ts
add more trace for loaders
* after
=> fix(core): add more trace for loaders

crates/node_binding/package.json, npm/darwin-arm64/package.json, npm/darwin-x64/package.json, npm/linux-x64-gnu/package.json, npm/wasm32-wasi/package.json, npm/win32-x64-msvc/package.json, package.json, packages/create-rspack/package.json, packages/rspack-cli/package.json, packages/rspack-test-tools/package.json, packages/rspack/package.json
=> chore: release v1.3.6

crates/rspack_storage/src/pack/strategy/split/mod.rs, crates/rspack_storage/src/pack/strategy/split/validate_scope.rs, crates/rspack_storage/tests/error.rs
The persistent cache checks whether the saved file is invalid by mtime and size, and it will cause download cache storage invalidate.
This PR will make storage check whether the saved file is invalid by file hash.
=> fix: storage validate hash with content

crates/rspack_core/src/utils/fast_actions.rs, tasks/benchmark/benches/groups/build_chunk_graph.rs
use spawn_blocking for fast_drop & remove dead code
=> refactor: remove dead_code and use spawn_blocking for fast_set

pnpm-lock.yaml, website/package.json, website/project-words.txt, website/rspress.config.ts
docs(llms): add llms.txt with @rspress/plugin-llms
https://github.com/web-infra-dev/rspress/releases/tag/v2.0.0-beta.1
=> docs(llms): bump to Rspress@2.0.0-beta.1 and add llms.txt

.github/workflows/issue-close-require.yml
Close inactive issues with `need more info` or `awaiting more feedback` label.
=> ci: close inactive issues with `need more info` or `awaiting more feedback`

crates/node_binding/src/lib.rs, crates/rspack_macros/src/hook.rs
Just an occasional discovery when doing other works.
=> perf: use `Vec::with_capacity` for hooks and plugins

website/rspress.config.ts
docs(llms.txt): add more description
=> docs(llms.txt): add more description

crates/node_binding/package.json, npm/darwin-arm64/package.json, npm/darwin-x64/package.json, npm/linux-x64-gnu/package.json, npm/wasm32-wasi/package.json, npm/win32-x64-msvc/package.json, package.json, packages/create-rspack/package.json, packages/rspack-cli/package.json, packages/rspack-test-tools/package.json, packages/rspack/package.json
=> chore: release v1.3.7

crates/rspack_plugin_javascript/src/webpack_comment.rs, packages/rspack-test-tools/tests/configCases/runtime/get-chunk-filename-runtime/test.config.js
fix https://github.com/web-infra-dev/rspack/issues/10183
=> fix: slash in char match pattern of magic comments

crates/rspack_plugin_javascript/src/webpack_comment.rs
Add test case of magic comments regex matching in #10195 
close #10195
=> test: add test case of issue #10195

website/docs/en/api/runtime-api/module-methods.mdx, website/docs/zh/api/runtime-api/module-methods.mdx
add `require.resolveWeak` doc.
reference: https://webpack.js.org/api/module-methods/#requireresolveweak
=> docs: add `require.resolveWeak` module method

crates/node_binding/binding.d.ts, crates/node_binding/src/chunk_group.rs, crates/rspack_core/src/dependency/dependency_location.rs, packages/rspack-test-tools/tests/configCases/compilation/chunk-groups/index.js, packages/rspack-test-tools/tests/configCases/compilation/chunk-groups/rspack.config.js, packages/rspack/etc/core.api.md, packages/rspack/src/ChunkGroup.ts
close https://github.com/web-infra-dev/rspack/issues/7922
=> feat: support `origin.loc` on chunkgroup

website/docs/en/guide/features/builtin-lightningcss-loader.mdx, website/docs/zh/guide/features/builtin-lightningcss-loader.mdx
add warning notice about lightningcss handling none standard-compatible input, more background in https://github.com/parcel-bundler/lightningcss/issues/960#issuecomment-2814515405
=> docs: add notice about lightningcss

Cargo.lock, crates/rspack_plugin_circular_dependencies/Cargo.toml, crates/rspack_plugin_circular_dependencies/src/lib.rs
fix https://github.com/web-infra-dev/rspack/issues/10208
=> fix: dead loop of circular dependency plugin

.github/teams.yml, .github/workflows/ci-rust.yaml
when only docs changed, no need to run rust checks.
=> refactor:  merge rust check and test into one require check job require condtion

Cargo.toml, crates/rspack_core/src/compiler/compilation.rs, crates/rspack_core/src/compiler/rebuild.rs, crates/rspack_core/src/incremental/mod.rs, crates/rspack_ids/src/named_chunk_ids_plugin.rs, crates/rspack_ids/src/named_module_ids_plugin.rs, crates/rspack_plugin_javascript/src/plugin/flag_dependency_exports_plugin.rs, crates/rspack_plugin_javascript/src/plugin/side_effects_flag_plugin.rs
More tracing for debugging incremental
=> feat(incremental): add more tracing for debugging

tests/bench/ts-react.bench.ts
should pass all: true to stats.toJson()
=> chore: improve stats.toJson() bench case

crates/node_binding/package.json, npm/darwin-arm64/package.json, npm/darwin-x64/package.json, npm/linux-x64-gnu/package.json, npm/wasm32-wasi/package.json, npm/win32-x64-msvc/package.json, package.json, packages/create-rspack/package.json, packages/rspack-cli/package.json, packages/rspack-test-tools/package.json, packages/rspack/package.json
=> chore: release v1.3.8

.github/workflows/ci-rust.yaml
=> refactor: CI better fallback runner label

crates/rspack_plugin_circular_dependencies/src/lib.rs
fix https://github.com/web-infra-dev/rspack/issues/10208
=> fix: circular seen relations

.vscode/settings.json
RA will call cargo check which share same lock with cargo build, so change RA's targetDir to avoid conflict
=> chore: change RA targetdir

.github/workflows/ci-lint.yaml
=> refactor:  CI lint add required check

Cargo.lock, Cargo.toml
1. update pnp-rs to 0.9.4 for https://github.com/yarnpkg/pnp-rs/pull/8 to close https://github.com/web-infra-dev/rspack/issues/10127
2. improve yarn pnp project resolve performance, [5 times faster](https://github.com/web-infra-dev/rspack-resolver/pull/69)
=> chore: bump rspack resolver 0.5.6

crates/node_binding/package.json, npm/darwin-arm64/package.json, npm/darwin-x64/package.json, npm/linux-x64-gnu/package.json, npm/wasm32-wasi/package.json, npm/win32-x64-msvc/package.json, package.json, packages/create-rspack/package.json, packages/rspack-cli/package.json, packages/rspack-test-tools/package.json, packages/rspack/package.json
https://github.com/web-infra-dev/rspack/releases/tag/v1.3.9
=> chore: release v1.3.9

website/docs/en/api/loader-api/context.mdx, website/docs/zh/api/loader-api/context.mdx
closes https://github.com/web-infra-dev/rspack/issues/10065
=> docs(diagnostic): add loader experimental diagnostic API

website/docs/en/api/runtime-api/module-variables.mdx, website/docs/zh/api/runtime-api/module-variables.mdx
=> docs: fix invalid link

crates/node_binding/binding.d.ts, crates/node_binding/src/raw_options/raw_module/mod.rs, crates/rspack_core/src/module.rs, crates/rspack_core/src/normal_module.rs, crates/rspack_core/src/options/module.rs, crates/rspack_plugin_asset/src/lib.rs, crates/rspack_plugin_devtool/src/source_map_dev_tool_plugin.rs, packages/rspack/src/config/adapter.ts, packages/rspack/src/config/types.ts, tests/webpack-test/configCases/asset-modules/keep-source-maps/index.js, tests/webpack-test/configCases/asset-modules/keep-source-maps/test.filter.js, website/docs/en/config/module.mdx, website/docs/zh/config/module.mdx
Support binary option of asset generator
=> feat: support binary option of asset generator

crates/rspack_plugin_runtime/src/runtime_module/export_webpack_require.rs, packages/rspack/src/config/defaults.ts, tests/webpack-test/configCases/output/chunk-format-with-runtimeChunk/test.filter.js
align with webpack, https://github.com/webpack/webpack/blob/main/lib/config/defaults.js#L1208
=> fix: chunk loading should be import by default when chunk format is module

tests/webpack-test/configCases/asset-emitted/normal/test.filter.js, tests/webpack-test/configCases/asset-emitted/normal/webpack.config.js, tests/webpack-test/configCases/async-commons-chunk/existing-name/test.filter.js, tests/webpack-test/configCases/code-generation/require-context-id/test.filter.js, tests/webpack-test/configCases/context-exclusion/simple/test.filter.js, tests/webpack-test/configCases/context-replacement/a/test.filter.js, tests/webpack-test/configCases/context-replacement/d/test.filter.js, tests/webpack-test/configCases/css/async-chunk-node/index.js, tests/webpack-test/configCases/css/async-chunk-node/test.filter.js, tests/webpack-test/configCases/css/basic-esm-target-web/test.filter.js, tests/webpack-test/configCases/css/contenthash/test.filter.js
Enable more webpack config test cases that reverted by https://github.com/web-infra-dev/rspack/pull/10300
=> test: enable more webpack config test cases

tests/webpack-test/ConfigTestCases.template.js
=> fix: test no setTimeout

crates/rspack_plugin_javascript/src/parser_plugin/node_stuff_plugin.rs, tests/webpack-test/cases/loaders/utils/test.filter.js
Support compile time evaluation of `__filename`
=> fix: compile time evaluation of `__filename`

crates/node_binding/package.json, npm/darwin-arm64/package.json, npm/darwin-x64/package.json, npm/linux-x64-gnu/package.json, npm/wasm32-wasi/package.json, npm/win32-x64-msvc/package.json, package.json, packages/create-rspack/package.json, packages/rspack-cli/package.json, packages/rspack-test-tools/package.json, packages/rspack/package.json
See: https://github.com/web-infra-dev/rspack/releases/tag/v1.3.10
=> chore: release v1.3.10

crates/rspack_plugin_ensure_chunk_conditions/src/lib.rs
we met some performance issue in ensure_chunk_condition_plugin which is hard to analyze, so add some tracing to get the rough compute complexity of this plugin
=> chore: add complexity tracing for  ensure_chunk_conditions plugin

website/docs/zh/config/module.mdx
=> docs: fix typos in zh/config/module.mdx

website/docs/en/config/experiments.mdx, website/docs/en/config/optimization.mdx, website/docs/zh/config/experiments.mdx, website/docs/zh/config/optimization.mdx
improve the parallelCodeSplitting description, and emphasis not turn off removeAvailableModule option
=> docs: clarify the parallelCodeSplitting and removeAvailableModules options

crates/rspack_plugin_javascript/src/parser_plugin/common_js_exports_parse_plugin.rs, crates/rspack_plugin_javascript/src/parser_plugin/common_js_imports_parse_plugin.rs, crates/rspack_plugin_javascript/src/parser_plugin/drive.rs, crates/rspack_plugin_javascript/src/parser_plugin/esm_import_dependency_parser_plugin.rs, crates/rspack_plugin_javascript/src/parser_plugin/inner_graph/plugin.rs, crates/rspack_plugin_javascript/src/parser_plugin/trait.rs, crates/rspack_plugin_javascript/src/visitors/dependency/parser/walk.rs, packages/rspack-test-tools/tests/configCases/parsing/rspack-issue-10005/warnings.js, tests/webpack-test/configCases/inner-graph/class/test.filter.js, tests/webpack-test/configCases/inner-graph/const/test.filter.js, tests/webpack-test/configCases/inner-graph/varNotWritten/test.filter.js, tests/webpack-test/configCases/inner-graph/varWritten/test.filter.js
improve inner graph
- handle assignment expression
- handle class body value
=> fix: improve inner graph assignment analysis

website/docs/en/config/module.mdx, website/docs/en/guide/start/quick-start.mdx, website/docs/zh/config/module.mdx, website/docs/zh/guide/optimization/tree-shaking.mdx
- Updated the documentation for `RuleSetCondition` type definition.
- Added code examples for various `Rule` options (e.g., `exclude`, `include`, `resource`, `resourceQuery`, `resourceFragment`, `test`, `issuer`) to demonstrate their usage.
=> docs: add examples for Rule conditions

crates/rspack_core/src/context_module.rs, crates/rspack_core/src/dependency/context_element_dependency.rs, tests/webpack-test/cases/chunks/destructuring-assignment/test.filter.js, tests/webpack-test/configCases/web/fetch-priority/index.js, tests/webpack-test/configCases/web/fetch-priority/test.filter.js, tests/webpack-test/configCases/web/fetch-priority/warnings.js
fix dynamic import default value from json, align with [webpack](contextelementDependency)
=> fix: dynamic import json with default name

crates/rspack_core/src/logger.rs
fix panic problem in release build, related https://github.com/web-infra-dev/rspack/actions/runs/14987517090/job/42104660167#step:7:171
=> fix(core): fix release panic problem

crates/rspack_core/src/concatenated_module.rs
Scan identifier parallel for concatenated module.
=> perf: scan scope idents parallel for concate module

Cargo.lock
Fix https://rustsec.org/advisories/RUSTSEC-2025-0024.html and some other cargo-audit warning.
=> chore(deps): Update some Rust dependencies

packages/rspack-test-tools/tests/errorCases/error-test-set-with-index.js
=> test: fix snapshot of main branch

packages/rspack/etc/core.api.md, packages/rspack/src/builtin-plugin/DefinePlugin.ts, website/docs/en/plugins/webpack/define-plugin.mdx, website/docs/zh/plugins/webpack/define-plugin.mdx
```diff
type CodeValuePrimitive =
| null
| undefined
| RegExp
| Function
| string
| number
| boolean
| bigint
-	| undefined;
```
=> docs: remove duplicate undefined types

.github/workflows/ci-rust.yaml, deny.toml
run duplicate version check in CI to avoid accidentally introduce more duplicate version in the future, we also need to investigate duplicate version
=> chore: run duplicate version check in ci

website/docs/en/config/optimization.mdx, website/docs/en/guide/optimization/tree-shaking.mdx, website/docs/zh/config/optimization.mdx, website/docs/zh/guide/optimization/tree-shaking.mdx
Add description about how to write sideEffects properly
=> docs: simplify the description of optimization.sideEffects

.github/workflows/reusable-build-build.yml
1. faster build time
2. no cache access problem
=> chore: CI build wasm in runner directly

.github/workflows/ci-lint.yaml, .github/workflows/ci-rust.yaml, .github/workflows/ci.yml, .github/workflows/issue-close-require.yml, .github/workflows/release-otp.yml, lint-staged.config.mjs
for less diffs in yaml PR
just prettier all yaml/yml under .github
=> chore: 🔧 prettier yaml files

pnpm-lock.yaml, website/docs/en/contribute/development/testing-rspack.mdx, website/docs/zh/contribute/development/testing-rspack.mdx, website/package.json, website/project-words.txt, website/rspress.config.ts
https://github.com/web-infra-dev/rspress/releases/tag/v2.0.0-beta.5
https://github.com/web-infra-dev/rspress/releases/tag/v2.0.0-beta.6
=> docs(rspress): upgrade to Rspress v2.0.0-beta.6

website/components/RandomMemberList.tsx, website/project-words.txt
Invite @quininer to join the Rspack core team 🎉
Currently, quininer is focused on optimizing Rspack's performance, memory usage, and Rust code quality. We look forward to the further improvements he will bring to Rspack. ❤️
- https://github.com/web-infra-dev/rspack/commits?author=quininer
- https://github.com/web-infra-dev/rspack/issues?q=commenter:quininer
=> docs: invite @quininer to Rspack core team

website/docs/en/blog/announcing-0-3.mdx, website/docs/en/guide/features/builtin-swc-loader.mdx, website/docs/en/guide/tech/typescript.mdx, website/docs/zh/blog/announcing-0-3.mdx, website/docs/zh/guide/tech/typescript.mdx
=> docs: update docs, remove unused useBuiltins

packages/rspack-cli/package.json, pnpm-lock.yaml, tests/e2e/package.json
upgrade @rspack/dev-server to fix typing issue
=> fix(cli): upgrade @rspack/dev-server

crates/node_binding/package.json, npm/darwin-arm64/package.json, npm/darwin-x64/package.json, npm/linux-x64-gnu/package.json, npm/wasm32-wasi/package.json, npm/win32-x64-msvc/package.json, package.json, packages/create-rspack/package.json, packages/rspack-cli/package.json, packages/rspack-test-tools/package.json, packages/rspack/package.json
=> chore: release v1.3.11

crates/node_binding/rspack.wasi-browser.js, crates/node_binding/rspack.wasi.cjs, crates/node_binding/src/exports_info.rs, crates/rspack_core/src/concatenated_module.rs, crates/rspack_core/src/dependency/runtime_template.rs, crates/rspack_core/src/exports_info.rs, crates/rspack_plugin_javascript/src/dependency/commonjs/common_js_export_require_dependency.rs, crates/rspack_plugin_javascript/src/dependency/commonjs/common_js_exports_dependency.rs, crates/rspack_plugin_javascript/src/dependency/commonjs/common_js_full_require_dependency.rs, crates/rspack_plugin_javascript/src/dependency/commonjs/common_js_self_reference_dependency.rs, crates/rspack_plugin_javascript/src/dependency/esm/esm_export_expression_dependency.rs, crates/rspack_plugin_javascript/src/dependency/esm/esm_export_imported_specifier_dependency.rs, crates/rspack_plugin_javascript/src/dependency/esm/esm_export_specifier_dependency.rs, crates/rspack_plugin_javascript/src/dependency/esm/esm_import_specifier_dependency.rs, crates/rspack_plugin_javascript/src/dependency/esm/provide_dependency.rs, crates/rspack_plugin_javascript/src/dependency/export_info_dependency.rs, crates/rspack_plugin_javascript/src/dependency/pure_expression_dependency.rs, crates/rspack_plugin_wasm/src/parser_and_generator.rs, packages/rspack-test-tools/tests/builtinCases/plugin-wasm/imports-multiple/__snapshots__/output.snap.txt
small refactor, avoid some small vec clone
=> refactor: replaced used name to slice for `exports_info.get_used_name`

crates/rspack_plugin_devtool/src/eval_source_map_dev_tool_plugin.rs, crates/rspack_plugin_devtool/src/generate_debug_id.rs, crates/rspack_plugin_devtool/src/lib.rs, crates/rspack_plugin_devtool/src/source_map_dev_tool_plugin.rs, tests/webpack-test/configCases/source-map/eval-source-map-debugids/test.filter.js, tests/webpack-test/configCases/target/system-named-assets-path/test.filter.js
fix missing debug ids of eval sourcemap
=> fix: eval sourcemap debugids

packages/rspack/src/config/adapterRuleUse.ts, tests/webpack-test/configCases/custom-hash-function/debug-hash/test.filter.js, tests/webpack-test/configCases/loaders-and-plugins-falsy/basic/test.filter.js, tests/webpack-test/configCases/mangle/mangle-with-destructuring-assignment/index.js, tests/webpack-test/configCases/mangle/mangle-with-destructuring-assignment/test.filter.js, tests/webpack-test/configCases/optimization/issue-19184/test.filter.js, tests/webpack-test/configCases/records/with-readRecords-hook/test.filter.js, tests/webpack-test/configCases/resolve/function-plugins/test.filter.js, tests/webpack-test/configCases/resolve/unsafe-cache-proxy/test.filter.js, tests/webpack-test/configCases/rule-set/oneOf/test.filter.js, tests/webpack-test/statsCases/split-chunks-dedup/test.filter.js, tests/webpack-test/statsCases/split-chunks-dedup/webpack.config.js, tests/webpack-test/statsCases/track-returned/test.filter.js
Enable more webpack test cases
=> test: enable more webpack test cases

Cargo.lock, crates/node_binding/Cargo.toml, crates/node_binding/src/lib.rs
add rspack_version and related options to tracing
=> chore: add rspack_version and options to tracing

packages/rspack/src/exports.ts, packages/rspack/src/trace/index.ts
fix not awaiting profiler stop, which may cause tracing is truncated
=> fix(core): fix tracing async exit early

crates/rspack_core/src/normal_module_factory.rs, crates/rspack_core/src/utils/identifier.rs, packages/rspack-test-tools/tests/configCases/normal-module/module-instance/rspack.config.js, tests/webpack-test/__snapshots__/StatsTestCases.basictest.js.snap, tests/webpack-test/cases/loaders/no-string/errors.js
Loader in module user request should be resolved path.
```js
import "loader!resource";
```
the module.userRequest should be `/path/to/loader.js!/path/to/resource`.
=> fix: loader in module user request should be resolved path

crates/rspack_core/src/utils/fs_trim.rs
fix https://github.com/web-infra-dev/rspack/issues/10364
=> fix: check directory before reading when running clean options 

crates/rspack_plugin_javascript/src/plugin/module_concatenation_plugin.rs
=> fix: wrong warning sort

crates/node_binding/binding.d.ts, crates/node_binding/scripts/banner.d.ts, packages/rspack/etc/core.api.md, packages/rspack/src/exports.ts, tests/bench/ts-react.bench.ts
New bench case for record chunk group logic in Next.js.
=> chore: bench record chunk group

crates/node_binding/binding.d.ts, crates/node_binding/src/resolver.rs, packages/rspack-test-tools/tests/configCases/resolver/resolve/rspack.config.js, packages/rspack/src/Resolver.ts
Change js api resolver.resolve to async implementation to improve the performance.
=> perf: js api resolver.resolve

crates/node_binding/package.json, npm/darwin-arm64/package.json, npm/darwin-x64/package.json, npm/linux-x64-gnu/package.json, npm/wasm32-wasi/package.json, npm/win32-x64-msvc/package.json, package.json, packages/create-rspack/package.json, packages/rspack-cli/package.json, packages/rspack-test-tools/package.json, packages/rspack/package.json
=> chore:  release 1.3.13

Cargo.lock, Cargo.toml
closes https://github.com/web-infra-dev/rspack/issues/10548
changelog: https://github.com/h-a-n-a/mimalloc_rust/releases/tag/v0.2.4
=> chore(allocator): bump mimalloc to v3.0.3

crates/rspack_core/src/build_chunk_graph/code_splitter.rs, crates/rspack_core/src/build_chunk_graph/new_code_splitter.rs, crates/rspack_core/src/compiler/compilation.rs, packages/rspack-test-tools/etc/test-tools.api.md, packages/rspack-test-tools/src/case/new-incremental.ts, packages/rspack-test-tools/src/processor/hot-new-incremental.ts, packages/rspack-test-tools/tests/NewIncremental-node.test.js, packages/rspack-test-tools/tests/NewIncremental-web.test.js, packages/rspack-test-tools/tests/NewIncremental-webworker.test.js, packages/rspack-test-tools/tests/watchCases/hashes/runtimeChunkFullHash/1/warnings.js, packages/rspack-test-tools/tests/watchCases/hashes/runtimeChunkGetChunkFilename/1/warnings.js, packages/rspack-test-tools/tests/watchCases/hashes/runtimeChunkHash/1/warnings.js
fullhash chunk filename should disable incremental for chunk render
=> fix(incremental): fullhash chunk filename should disable incremental for chunk render

.github/workflows/release-debug.yml
=> chore(ci): fix debug release not triggered

Cargo.lock, Cargo.toml, crates/node_binding/src/module.rs, crates/node_binding/src/modules/external_module.rs, crates/node_binding/src/modules/macros.rs, crates/node_binding/src/modules/normal_module.rs, crates/node_binding/src/plugins/js_cleanup_plugin.rs, crates/node_binding/src/plugins/js_loader/mod.rs, crates/node_binding/src/resource_data.rs, crates/rspack_napi/src/threadsafe_function.rs
bump napi to 3.0.0-beta.5
Details https://github.com/napi-rs/napi-rs/releases/tag/napi%403.0.0-beta.5
=> chore: bump napi to 3.0.0-beta.5

crates/node_binding/package.json, npm/darwin-arm64/package.json, npm/darwin-x64/package.json, npm/linux-x64-gnu/package.json, npm/wasm32-wasi/package.json, npm/win32-x64-msvc/package.json, package.json, packages/create-rspack/package.json, packages/rspack-cli/package.json, packages/rspack-test-tools/package.json, packages/rspack/package.json
=> release: 1.3.14

crates/rspack_core/src/artifacts/cgm_hash_artifact.rs, crates/rspack_core/src/build_chunk_graph/new_code_splitter.rs, crates/rspack_core/src/compiler/compilation.rs, crates/rspack_core/src/old_cache/local/code_splitting_cache.rs, packages/rspack-test-tools/tests/NewIncremental-node.test.js, packages/rspack-test-tools/tests/NewIncremental-web.test.js, packages/rspack-test-tools/tests/NewIncremental-webworker.test.js
When incremental rebuild, should rebuild chunk's outgoings once runtime changes
=> fix: should rebuild chunk outgoings when incremental runtime change

crates/node_binding/package.json, npm/darwin-arm64/package.json, npm/darwin-x64/package.json, npm/linux-x64-gnu/package.json, npm/wasm32-wasi/package.json, npm/win32-x64-msvc/package.json, package.json, packages/create-rspack/package.json, packages/rspack-cli/package.json, packages/rspack-test-tools/package.json, packages/rspack/package.json
=> chore: release v1.3.15

crates/node_binding/binding.d.ts, crates/rspack_core/src/external_module.rs, packages/rspack-test-tools/tests/configCases/externals/umd-triple-with-other-external-type/concated.js, packages/rspack-test-tools/tests/configCases/externals/umd-triple-with-other-external-type/index.js, packages/rspack-test-tools/tests/configCases/externals/umd-triple-with-other-external-type/rspack.config.js
fix https://github.com/web-infra-dev/rspack/issues/10361
=> fix: panic when concat external module request is undefined

Cargo.lock, Cargo.toml, crates/node_binding/src/resolver.rs, crates/node_binding/src/utils.rs, deny.toml
Reverts web-infra-dev/rspack#10562
=> Revert "chore(deps): update napi to 3.0.0-beta.8"

crates/node_binding/binding.d.ts, crates/node_binding/src/swc.rs, packages/rspack-test-tools/tests/compilerCases/swc-api.js, packages/rspack/etc/core.api.md, packages/rspack/src/exports.ts, packages/rspack/src/swc.ts, website/docs/en/api/javascript-api/swc.mdx, website/docs/zh/api/javascript-api/swc.mdx
Support swc transformSync and minifySync api so that user can call it in sync function.
=> feat: add swc transformSync and minifySync api

.github/pr-labeler.yml, .github/release.yml
Introduces a new release label for refactoring changes and updates the configuration files to support it.
=> chore(workflow): update changelog generator to include refactor label

.github/teams.yml
Updates the `.github/teams.yml` file to include more team members, added `@zoolsher`, `@quininer` and `@CPunisher` to the list.
=> chore: update team members

crates/rspack_core/src/compiler/make/cutout/mod.rs
MakeParam::ModifiedFiles and MakeParam::RemovedFiles have the same process at cutout, this PR will merge them.
=> refactor: make merge modified files and removed files

.github/workflows/release-canary.yml, .github/workflows/release-otp.yml, .github/workflows/release.yml, .github/workflows/reusable-build-build.yml, npm/wasm32-wasi/package.json, scripts/build-npm.cjs
Missing parts of https://github.com/web-infra-dev/rspack/pull/10617
Starter with canary: https://stackblitz.com/~/github.com/CPunisher/rspack-starter-stackblitz
=> chore(wasm): publish wasi binding 2

crates/node_binding/binding.d.ts, crates/node_binding/scripts/banner.d.ts, crates/node_binding/src/module.rs, crates/node_binding/src/modules/macros.rs, packages/rspack/src/ConcatenatedModule.ts, packages/rspack/src/ContextModule.ts, packages/rspack/src/ExternalModule.ts, packages/rspack/src/Module.ts, packages/rspack/src/NormalModule.ts
Refactor readableIdentifier to method in napi.
=> refactor: js api readableIdentifier in module

.github/workflows/preview-commit.yml, .github/workflows/release-canary.yml, .github/workflows/release-otp.yml, .github/workflows/release.yml, .github/workflows/reusable-build-all.yml, .github/workflows/reusable-build-test.yml
=> refactor:  fast fail  matrix testing  to better utilizing CI runner

website/docs/public/netlify.toml
temporarily fix rspack.rs down problem
=> chore: remove rspack.dev redirect

.github/workflows/ecosystem-benchmark.yml, .github/workflows/reusable-build-build.yml
Fix commit performance data downgrade. Using `inputs.profile` other than hard coded.
=> fix(ci): linux x86 native build hardcoded profile

website/docs/en/guide/features/lazy-compilation.mdx, website/docs/zh/guide/features/lazy-compilation.mdx
LazyCompilation has update its interface, should update document as well
=> docs: update lazyCompilationMiddleware interface

crates/node_binding/src/compilation/mod.rs, crates/node_binding/src/lib.rs, crates/node_binding/src/resolver.rs, crates/node_binding/src/utils.rs
remove unnecessary callback call in callbackify
=> refactor: remove unnecessary callback

website/docs/zh/contribute/development/tracing.md
fix little typo  https://github.com/web-infra-dev/rspack/pull/10549#discussion_r2142382836_
=> docs: update tracing doc typo

crates/rspack_javascript_compiler/src/compiler/stringify.rs, packages/rspack-test-tools/tests/configCases/plugins/minify-preamble/index.js, packages/rspack-test-tools/tests/configCases/plugins/minify-preamble/rspack.config.js, packages/rspack/src/builtin-plugin/SwcJsMinimizerPlugin.ts
closes https://github.com/web-infra-dev/rspack/issues/10707#event-18201615024
=> feat: support preamble in swc minifier 

packages/rspack/src/config/zod.ts
Following up https://github.com/web-infra-dev/rspack/pull/10678. Replace the deprecated `.superRefine()` with `.check()`.
issue: #10467
> In Zod 4, `.superRefine()` has been deprecated in favor of `.check()`
> https://zod.dev/api?id=superrefine
=> refactor(zod/v4): replace deprecated `.superRefine()`

crates/rspack_core/src/concatenated_module.rs
Parallel calculating runtime hashes of concatenated modules
=> perf: parallel get runtime hash of concatenated modules

crates/rspack_core/src/concatenated_module.rs
Parallel getting concatenated imports when enter module
=> perf: parallel get concatenated imports when enter module

website/docs/en/config/experiments.mdx, website/docs/zh/config/experiments.mdx
adjust incremental docs for v1.4.0
=> docs: adjust incremental docs for v1.4.0

pnpm-lock.yaml
Ref: https://github.com/web-infra-dev/rspack/pull/10770#discussion_r2163425743
=> chore: update pnpm lockfile

tasks/benchmark/src/lib.rs
Hope to make benchmark more stable
=> chore: add `NeverGrowInPlaceAllocator` for benchmark

crates/rspack_plugin_sri/src/runtime.rs, packages/rspack-test-tools/tests/configCases/sri/runtime-requirement/index.js, packages/rspack-test-tools/tests/configCases/sri/runtime-requirement/rspack.config.js
=> fix: add `_webpack_require_` while using SRI plugin

.github/workflows/reusable-build-test.yml, packages/rspack/src/trace/index.ts
workaround for node.js 16 crash bug
=> fix: try fix node.js 16 crash

crates/rspack_plugin_ignore/src/lib.rs
we should never panic when user pass wrong configuration which makes error report unreadable,
also need to further improve napi error report when signature not match
* before
* after
#10827
=> fix(core): improve ignorePlugin error report

crates/rspack_plugin_devtool/src/source_map_dev_tool_plugin.rs
Parallel creating map assets 
Before:
After:
=> perf: parallel create map assets

Cargo.lock, crates/rspack_core/Cargo.toml, crates/rspack_core/src/options/filename.rs, crates/rspack_core/src/utils/hash.rs, packages/rspack-test-tools/tests/configCases/css/local-ident-name/index.js, packages/rspack-test-tools/tests/configCases/css/local-ident-name/index.module.css, packages/rspack-test-tools/tests/configCases/css/local-ident-name/rspack.config.js, website/docs/en/config/output.mdx, website/docs/zh/config/output.mdx
=> feat: support base64 hash digest for css local ident name

Cargo.lock, Cargo.toml
upgrade swc to check whether  https://github.com/swc-project/swc/pull/10764 reduce binary size
=> fix: upgrade swc_core to 30.0.2

crates/rspack_plugin_javascript/src/dependency/esm/esm_import_dependency.rs, packages/rspack-test-tools/tests/configCases/type-reexports-presence/no-tolerant/index.ts, packages/rspack-test-tools/tests/configCases/type-reexports-presence/no-tolerant/reexport-cycle.ts, packages/rspack-test-tools/tests/configCases/type-reexports-presence/no-tolerant/warnings.js, packages/rspack-test-tools/tests/configCases/type-reexports-presence/no-tolerant/with-cycle.ts, packages/rspack-test-tools/tests/configCases/type-reexports-presence/tolerant/warnings.js
=> fix: break cycle for type reexports check

crates/rspack_ids/src/deterministic_module_ids_plugin.rs
=> perf: parallelize getting full module names in the deterministic module ids plugin

crates/node_binding/package.json, npm/darwin-arm64/package.json, npm/darwin-x64/package.json, npm/linux-x64-gnu/package.json, npm/wasm32-wasi/package.json, npm/win32-x64-msvc/package.json, package.json, packages/create-rspack/package.json, packages/rspack-cli/package.json, packages/rspack-test-tools/package.json, packages/rspack/package.json
This is a hotfix for https://github.com/web-infra-dev/rspack/pull/10916
I plan to trigger the ecosystem CI first and release it on Saturday.
=> chore: release v1.4.4

.vscode/settings.json
enable plugin feature for ra, so we can get LSP for plugin related code
=> chore: enable plugin feature for RA

.github/workflows/reusable-build-test.yml
Wait all tests finish, to determine if it's a node version based bug or general bug.
=> chore(ci): config testing `fail-fast` to false

Cargo.lock, crates/rspack_tracing_perfetto/Cargo.toml, deny.toml
add rule to forbid wildcard to avoid casual update
=> chore: disable wildcard version

crates/rspack_core/src/build_chunk_graph/available_modules.rs, crates/rspack_core/src/build_chunk_graph/new_code_splitter.rs, crates/rspack_core/src/lib.rs
Improve performance of remove_available_modules
=> perf: improve remove_available_modules

.github/workflows/reusable-rust-test.yml, Cargo.toml, crates/rspack_core/Cargo.toml, crates/rspack_error/Cargo.toml, crates/rspack_fs/Cargo.toml, crates/rspack_javascript_compiler/Cargo.toml, crates/rspack_loader_swc/Cargo.toml, crates/rspack_plugin_javascript/Cargo.toml, crates/rspack_plugin_json/Cargo.toml, crates/rspack_plugin_schemes/Cargo.toml, deny.toml, tasks/release-check/Cargo.toml
enforce workspace duplicate check and enable all features for cargo deny
=> chore: check workspace duplicate version

crates/rspack_plugin_javascript/src/parser_plugin/esm_import_dependency_parser_plugin.rs, packages/rspack-test-tools/tests/normalCases/parsing/destructuring-assignment/index.js, packages/rspack-test-tools/tests/normalCases/parsing/destructuring-assignment/module.js, packages/rspack-test-tools/tests/normalCases/parsing/destructuring-assignment/reexport.js
=> fix: destructuring assignment a call expr

crates/node_binding/package.json, npm/darwin-arm64/package.json, npm/darwin-x64/package.json, npm/linux-x64-gnu/package.json, npm/wasm32-wasi/package.json, npm/win32-x64-msvc/package.json, package.json, packages/create-rspack/package.json, packages/rspack-cli/package.json, packages/rspack-test-tools/package.json, packages/rspack/package.json
=> chore: release v1.4.6

crates/rspack_loader_swc/src/lib.rs
Just add more info for the warning, to help inspect why the warning exists
=> fix: add more info for collect ts info warning

xtask/src/deny_ext/mod.rs
add default-features=false check for workspace.depencencies
=> chore: add default-feaults=false check

website/docs/en/misc/glossary.mdx, website/docs/en/plugins/webpack/split-chunks-plugin.mdx, website/docs/zh/misc/glossary.mdx, website/docs/zh/plugins/webpack/split-chunks-plugin.mdx
- Include a detailed explanation of `SplitChunksPlugin` behavior and examples for the `chunks` option.
- Add tips for build performance and Module Federation.
- Add definitions for "async chunk" and "initial chunk" in the glossary.
- https://github.com/webpack/webpack/discussions/18040
=> docs: improve `splitChunks.chunks` and update glossary

Cargo.lock, crates/rspack_plugin_progress/Cargo.toml
=> fix: compat non ascii for progress plugin

scripts/release/version.mjs
=> chore: bump crate versions in non-debug non-snapshot releases only

.github/renovate.json5
Try to make renovate only update the lock file when possible
=> chore: renovate update lock for cargo

README.md, README.zh-CN.md
Maybe we need to adjust the styles.
=> docs: add open in stacklitz button in README

Cargo.lock, crates/node_binding/Cargo.toml, crates/node_binding/scripts/build.js
Test to reduce the code generated by tracing
=> perf: Use release_max_level_info for tracing

crates/rspack_binding_api/src/chunk.rs, crates/rspack_binding_api/src/chunk_group.rs, crates/rspack_binding_api/src/codegen_result.rs, crates/rspack_binding_api/src/html.rs, crates/rspack_binding_api/src/options/raw_resolve.rs, crates/rspack_binding_api/src/plugins/context_replacement.rs, crates/rspack_binding_api/src/plugins/js_loader/context.rs, crates/rspack_binding_api/src/raw_options/raw_builtins/raw_css_extract.rs, crates/rspack_binding_api/src/raw_options/raw_builtins/raw_html.rs, crates/rspack_binding_api/src/raw_options/raw_builtins/raw_http_uri.rs, crates/rspack_binding_api/src/raw_options/raw_external.rs, crates/rspack_binding_api/src/raw_options/raw_module/mod.rs, crates/rspack_binding_api/src/raw_options/raw_split_chunks/raw_split_chunk_size.rs, crates/rspack_binding_api/src/trace_event.rs, crates/rspack_plugin_html/src/config.rs, crates/rspack_plugin_html/src/tag.rs, crates/rspack_plugin_schemes/src/http_uri/http_cache.rs, packages/rspack/src/ChunkGraph.ts
This PR needs https://github.com/napi-rs/napi-rs/pull/2374.
=> perf: use fxhash for HashMap in napi

crates/node_binding/scripts/build.js, rust-toolchain.toml
=> perf: Use build-std for release

Cargo.lock, Cargo.toml, crates/rspack_binding_api/src/raw_options/raw_module/mod.rs, crates/rspack_core/src/parser_and_generator.rs, deny.toml
dedupe unnecessary derive_more crate
=> perf: dedupe derive_more

crates/rspack_plugin_javascript/src/plugin/infer_async_modules_plugin.rs
Parallize get outoings of sync modules. Because most of modules dont have top-level-await so they can be parallelized safely.
Before:
After:
=> perf: parallel set sync modules

.github/CODEOWNERS
no need to add code owner for test cases folder
=> chore: no need to add code owner for test cases folder

package.json, packages/rspack/src/builtin-plugin/EnableLibraryPlugin.ts, packages/rspack/src/builtin-plugin/ExternalsPlugin.ts, packages/rspack/src/builtin-plugin/HttpUriPlugin.ts, packages/rspack/src/builtin-plugin/WorkerPlugin.ts, packages/rspack/src/trace/index.ts
ensure no lint warnings in ci
we met some biome's bug so need to workaround it
https://github.com/biomejs/biome/issues/6933
https://github.com/biomejs/biome/issues/6974
=> chore: check lint warning in ci

Cargo.lock, crates/node_binding/napi-binding.d.ts, crates/rspack_binding_api/Cargo.toml, crates/rspack_binding_api/src/build_info.rs, crates/rspack_binding_api/src/compilation/mod.rs, crates/rspack_binding_api/src/dependency.rs, crates/rspack_binding_api/src/module.rs, crates/rspack_binding_api/src/module_graph.rs, crates/rspack_binding_api/src/modules/concatenated_module.rs, crates/rspack_binding_api/src/modules/context_module.rs, crates/rspack_binding_api/src/modules/external_module.rs, crates/rspack_binding_api/src/modules/macros.rs, crates/rspack_binding_api/src/modules/normal_module.rs, crates/rspack_binding_api/src/normal_module_factory.rs, crates/rspack_binding_api/src/plugins/interceptor.rs, crates/rspack_binding_api/src/raw_options/raw_external.rs, crates/rspack_binding_api/src/resource_data.rs, crates/rspack_core/src/module_graph/mod.rs, packages/rspack/etc/core.api.md, packages/rspack/src/builtin-plugin/ExternalsPlugin.ts, packages/rspack/src/taps/normalModuleFactory.ts
Performance degradation observed when switching from FxHashMap to UkeyMap.
The efficiency loss stems from the tag-based SIMD optimization failure in hashbrown's lookup mechanism.
References:
[hashbrown/src/raw/mod.rs at master · rust-lang/hashbrown](https://github.com/rust-lang/hashbrown/blob/master/src/raw/mod.rs#L1895)
[hashbrown/src/control/tag.rs at master · rust-lang/hashbrown](https://github.com/rust-lang/hashbrown/blob/master/src/control/tag.rs#L36)
[hashbrown/src/control/group/generic.rs at master · rust-lang/hashbrown](https://github.com/rust-lang/hashbrown/blob/master/src/control/group/generic.rs#L107)
=> revert: "revert: perf: napi communication (#11132) (#11162)" 

crates/rspack_ids/src/id_helpers.rs, tests/webpack-test/watchCases/cache/reexport-mangle/webpack.config.js
Correct cache config to rspack specific config
=> fix: correct cache option in tests

crates/rspack_plugin_split_chunks/src/plugin/module_group.rs
=> perf: improve prepare group by used exports

Cargo.lock, Cargo.toml, crates/rspack_binding_api/src/plugins/js_hooks_plugin.rs, crates/rspack_plugin_css/Cargo.toml, crates/rspack_plugin_css/src/plugin/impl_plugin_for_css_plugin.rs, crates/rspack_plugin_html/Cargo.toml, crates/rspack_plugin_html/src/plugin.rs, crates/rspack_plugin_module_info_header/src/lib.rs, crates/rspack_plugin_real_content_hash/Cargo.toml, crates/rspack_plugin_real_content_hash/src/lib.rs, crates/rspack_plugin_rsdoctor/Cargo.toml, crates/rspack_plugin_rsdoctor/src/plugin.rs, crates/rspack_plugin_runtime/Cargo.toml, crates/rspack_plugin_runtime/src/runtime_module/jsonp_chunk_loading.rs, crates/rspack_plugin_runtime/src/runtime_module/load_script.rs, crates/rspack_plugin_runtime/src/runtime_module/module_chunk_loading.rs, crates/rspack_plugin_runtime/src/runtime_plugin.rs, crates/rspack_plugin_sri/src/lib.rs
We should make sure that there's no read-write and write-write conflicts for each hook instance.
=> perf: replace rwlock with `atomic_refcell`

crates/rspack_plugin_extract_css/src/css_dependency.rs, crates/rspack_plugin_extract_css/src/css_module.rs, crates/rspack_plugin_extract_css/src/parser_plugin.rs, crates/rspack_plugin_extract_css/src/plugin.rs, crates/rspack_plugin_javascript/src/visitors/dependency/parser/mod.rs, packages/rspack-test-tools/tests/configCases/css-extract/module-layer/index.js, packages/rspack-test-tools/tests/configCases/css-extract/module-layer/rspack.config.js, packages/rspack-test-tools/tests/configCases/css-extract/module-layer/test.config.js
Fix #11168
Support moduleLayer for css-extract-plugin
=> feat: support moduleLayer for css-extract

.gitignore
Prevent adding rustc ICE report files
=> chore: ignore rustc ice reports

.github/actions/rustup/cargo/action.yml
Use zstd will benefit both self-hosted's cache saving and restoring.
Here is the comparasion.
| Cache Size \~458 MB     | save Cache                                                                                                | restore Cache                                                                                          |
| ----------------------- | ---------------------------------------------------------------------------------------------------------: | ------------------------------------------------------------------------------------------------------: |
| zstd                    | 13s  [ref](https://github.com/web-infra-dev/rspack/actions/runs/16518484573/job/46714645794#step:45:126)  | 38s [ref](https://github.com/web-infra-dev/rspack/actions/runs/16518484573/job/4671571 …
=> feat: use zstd to cache compress

packages/rspack/src/config/types.ts, website/docs/en/config/resolve.mdx, website/docs/zh/config/resolve.mdx
Expanded the explanation of `resolve.conditionNames`, detailing default values based on mode, target, and module type. Added examples for condition matching, priority rules, and extending default values.
- https://github.com/web-infra-dev/rsbuild/issues/5697
=> docs: improve `resolve.conditionNames` documentation

crates/rspack_cacheable_test/Cargo.toml, crates/rspack_loader_testing/Cargo.toml, crates/rspack_macros_test/Cargo.toml
should not publish testing crates
=> chore(releasing): should not publish testing crates

README.md
=> chore: add crates.io badge

crates/rspack_binding_api/src/raw_options/raw_external.rs, tests/bench/ts-react.bench.ts
add bench case for external getResolve in codspeed
=> refactor: bench external getResolve & remove ResolveClosureContext

crates/rspack_core/src/chunk_graph/chunk_graph_module.rs
Fix lifetime error on main branch
=> fix: lifetime error

package.json, pnpm-lock.yaml
=> chore: upgrade rslint to 0.1.1

crates/rspack_plugin_javascript/src/dependency/esm/esm_import_dependency.rs
Align with https://github.com/webpack/webpack/blob/de79ee457eb921e6e1b186c90c65590789a013ca/lib/dependencies/HarmonyImportDependency.js#L314-L323, and add early return for lazy
Fix the render differences after enable `lazyBarrel`
=> fix: avoid render weak import dependency

packages/rspack-test-tools/tests/configCases/externals/resolve-with-query/rspack.config.js, packages/rspack/src/builtin-plugin/ExternalsPlugin.ts
fix: get resolve in externals should return query
=> fix: get resolve in externals should return query

crates/rspack_core/src/cache/persistent/occasion/make/mod.rs, crates/rspack_core/src/cache/persistent/occasion/make/module_graph.rs, crates/rspack_core/src/compilation/make/lazy_barrel_artifact.rs, packages/rspack-test-tools/tests/cacheCases/common/basic/rspack.config.js, packages/rspack-test-tools/tests/cacheCases/common/update-file/rspack.config.js, packages/rspack-test-tools/tests/cacheCases/make/lazy-barrel/index.js, packages/rspack-test-tools/tests/cacheCases/make/lazy-barrel/lib/a.js, packages/rspack-test-tools/tests/cacheCases/make/lazy-barrel/lib/b.js, packages/rspack-test-tools/tests/cacheCases/make/lazy-barrel/lib/c.js, packages/rspack-test-tools/tests/cacheCases/make/lazy-barrel/lib/index.js, packages/rspack-test-tools/tests/cacheCases/make/lazy-barrel/lib/package.json, packages/rspack-test-tools/tests/cacheCases/make/lazy-barrel/rspack.config.js, packages/rspack-test-tools/tests/cacheCases/make/lazy-barrel/test.js
support persistent cache for lazy barrel
=> feat: support persistent cache for lazy barrel

package.json, pnpm-lock.yaml
=> chore: upgrade rslint to 0.1.3

crates/rspack_core/src/module_graph/mod.rs, crates/rspack_plugin_javascript/src/plugin/module_concatenation_plugin.rs
Before:
After:
This pull request introduces significant performance improvements to module graph operations in the module concatenation plugin by batching and parallelizing updates. The main changes are the addition of new batch methods for updating connections in the `ModuleGraph`, and refactoring the plugin to use these batch methods, which simplifies and speeds up the handling of module connections during concatenation.
**Performance improvements and refactoring:**
* Added new batch methods to `ModuleGraph` for setting original module identifiers, setting module identifiers, adding connections, and removing connections, all using parallel iteration via Rayon for improved performance. (`crates/rspack_core/src/module_graph/mod.rs`) …
=> perf: improve add concatenated modules by parallelizing conneciton modifications

crates/rspack_binding_build/README.md, crates/rspack_binding_build/src/lib.rs, crates/rspack_binding_builder/README.md, crates/rspack_binding_builder/src/lib.rs, crates/rspack_binding_builder_macros/README.md, crates/rspack_binding_builder_macros/src/lib.rs
add docs for custom binding crates
=> docs: add docs for custom binding crates

.github/CODEOWNERS
=> chore: remove from `rspack_binding_api` in CODEOWNERS

package.json, pnpm-lock.yaml, rslint.json
more rules more warnings, warning increase to 2457
=> chore: upgrade rslint@0.1.5

packages/rspack-cli/tests/serve/basic/serve-basic.test.ts
Fix test failure when port is used.
=> chore(ci): fix flaky serve test

website/docs/en/config/output.mdx
=> docs(config): output.filename link fix

packages/rspack-test-tools/src/plugin/lazy-compilation-test-plugin.ts, packages/rspack-test-tools/src/processor/hot.ts, packages/rspack-test-tools/tests/hotCases/lazy-compilation/context/webpack.config.js, packages/rspack-test-tools/tests/hotCases/lazy-compilation/module-test/webpack.config.js, packages/rspack-test-tools/tests/hotCases/lazy-compilation/only-entries/webpack.config.js, packages/rspack-test-tools/tests/hotCases/lazy-compilation/simple/webpack.config.js, packages/rspack-test-tools/tests/hotCases/lazy-compilation/unrelated/webpack.config.js, tests/e2e/cases/lazy-compilation/css-update/rspack.config.js, tests/e2e/cases/lazy-compilation/custom-prefix/rspack.config.js, tests/e2e/cases/lazy-compilation/default-prefix/index.test.ts, tests/e2e/cases/lazy-compilation/default-prefix/rspack.config.js, tests/e2e/cases/lazy-compilation/ignore-entry/rspack.config.js, tests/e2e/cases/lazy-compilation/persistent-cache/rspack.config.js, tests/e2e/fixtures/rspack.ts, tests/webpack-examples/lazy-compilation/README.md, tests/webpack-examples/lazy-compilation/webpack.config.js, tests/webpack-test/hotCases/lazy-compilation/context/webpack.config.js, tests/webpack-test/hotCases/lazy-compilation/https/webpack.config.js, tests/webpack-test/hotCases/lazy-compilation/module-test/webpack.config.js, tests/webpack-test/hotCases/lazy-compilation/only-entries/webpack.config.js, tests/webpack-test/hotCases/lazy-compilation/simple/webpack.config.js, tests/webpack-test/hotCases/lazy-compilation/unrelated/webpack.config.js
lazyCompilation config has been moved to top level of configuration, modify them in test cases
=> fix: modify lazy compilation tests

website/docs/en/config/output.mdx, website/docs/en/guide/features/asset-module.mdx, website/docs/zh/config/output.mdx
Fix typos and incorrect links.
=> docs: fix typos in asset modules

website/docs/en/_nav.json, website/docs/zh/_nav.json
After https://github.com/rspack-contrib/rspack-repl/issues/5, I think the REPL is generally usable.
=> docs: add playground to navbar

crates/rspack_plugin_javascript/src/parser_plugin/amd/amd_define_dependency_parser_plugin.rs, crates/rspack_plugin_javascript/src/parser_plugin/inner_graph/plugin.rs, crates/rspack_plugin_javascript/src/visitors/dependency/parser/call_hooks_name.rs, crates/rspack_plugin_javascript/src/visitors/dependency/parser/mod.rs, crates/rspack_plugin_javascript/src/visitors/dependency/parser/walk.rs, crates/rspack_plugin_javascript/src/visitors/scope_info.rs
Port https://github.com/webpack/webpack/pull/19795
Currently no way to test this for rspack since we didn't expose `buildInfo.topLevelDeclarations` to js side
=> refactor: distinguish free variable and tagged variable

crates/rspack_plugin_devtool/src/eval_dev_tool_module_plugin.rs, crates/rspack_plugin_devtool/src/eval_source_map_dev_tool_plugin.rs, crates/rspack_plugin_javascript/src/parser_and_generator/mod.rs, crates/rspack_plugin_javascript/src/parser_plugin/check_var_decl.rs, crates/rspack_plugin_javascript/src/parser_plugin/compatibility_plugin.rs, crates/rspack_plugin_javascript/src/parser_plugin/drive.rs, crates/rspack_plugin_javascript/src/parser_plugin/inline_const.rs, crates/rspack_plugin_javascript/src/parser_plugin/inner_graph/plugin.rs, crates/rspack_plugin_javascript/src/parser_plugin/trait.rs, crates/rspack_plugin_javascript/src/parser_plugin/worker_plugin.rs, crates/rspack_plugin_javascript/src/visitors/dependency/parser/estree.rs, crates/rspack_plugin_javascript/src/visitors/dependency/parser/walk.rs, crates/rspack_plugin_javascript/src/visitors/dependency/parser/walk_block_pre.rs, crates/rspack_plugin_javascript/src/visitors/dependency/parser/walk_pre.rs, packages/rspack-test-tools/tests/__snapshots__/StatsOutput.test.js.snap, tests/webpack-test/cases/parsing/using/index.js, tests/webpack-test/cases/parsing/using/module.js, tests/webpack-test/cases/parsing/using/test.filter.js, tests/webpack-test/configCases/source-map/exclude-modules-source-map/index.js, tests/webpack-test/helpers/supportsUsing.js
Port https://github.com/webpack/webpack/pull/19626
=> feat: support using declaration

website/docs/en/contribute/development/building.md, website/docs/en/contribute/development/testing-rspack.mdx, website/docs/zh/contribute/development/building.md, website/docs/zh/contribute/development/testing-rspack.mdx
Add building and testing guide for rspack wasm
=> docs: add building and testing guide for rspack wasm

crates/rspack_plugin_javascript/src/visitors/dependency/parser/mod.rs, crates/rspack_plugin_javascript/src/visitors/dependency/parser/walk_block_pre.rs, crates/rspack_plugin_javascript/src/visitors/dependency/parser/walk_module_pre.rs
Port: https://github.com/webpack/webpack/pull/19804
For now we still don't support createRequire, so no new tests is added, only passes existing tests
=> refactor: add module pre walk

packages/rspack-browser/package.json, packages/rspack/etc/core.api.md, packages/rspack/package.json, pnpm-lock.yaml, website/docs/en/config/experiments.mdx, website/docs/en/config/module.mdx, website/docs/en/guide/features/builtin-swc-loader.mdx, website/docs/zh/config/experiments.mdx, website/docs/zh/config/module.mdx, website/docs/zh/guide/features/builtin-swc-loader.mdx
=> chore: update swc types and docs

crates/rspack_plugin_javascript/src/parser_plugin/define_plugin/parser.rs, crates/rspack_plugin_javascript/src/parser_plugin/drive.rs, crates/rspack_plugin_javascript/src/parser_plugin/esm_import_dependency_parser_plugin.rs, crates/rspack_plugin_javascript/src/parser_plugin/import_meta_plugin.rs, crates/rspack_plugin_javascript/src/parser_plugin/import_parser_plugin.rs, crates/rspack_plugin_javascript/src/parser_plugin/trait.rs, crates/rspack_plugin_javascript/src/visitors/dependency/parser/mod.rs, crates/rspack_plugin_javascript/src/visitors/dependency/parser/walk_pre.rs, packages/rspack-test-tools/tests/configCases/plugins/define-plugin/index.js, packages/rspack-test-tools/tests/configCases/plugins/define-plugin/webpack.config.js, tests/webpack-test/cases/esm/import-meta/index.js, tests/webpack-test/configCases/plugins/define-plugin/index.js, tests/webpack-test/configCases/plugins/define-plugin/webpack.config.js
Port: https://github.com/webpack/webpack/pull/19811
=> refactor: only collect destructuring assignment properties for specific expression

packages/rspack/src/browser/BrowserHttpImportPlugin.ts, packages/rspack/src/browser/BrowserImportEsmPlugin.ts, packages/rspack/src/browser/index.ts, packages/rspack/src/builtin-plugin/HttpUriPlugin.ts
Add `BrowserImportEsmPlugin` that converts imports of dependencies in node modules to http imports from esm cdn.
<details>
<summary>Link to playground demo</summary>
https://playground.rspack.rs/#eyJyc3BhY2tWZXJzaW9uIjoiMS41LjAtYmV0YS4xIiwiaW5wdXRGaWxlcyI6W3siZmlsZW5hbWUiOiJyc3BhY2suY29uZmlnLmpzIiwidGV4dCI6ImltcG9ydCAqIGFzIHJzcGFjayBmcm9tIFwiQHJzcGFjay9icm93c2VyXCJcblxuZXhwb3J0IGRlZmF1bHQge1xuICBtb2RlOiBcImRldmVsb3BtZW50XCIsXG4gIGRldnRvb2w6IGZhbHNlLFxuICBlbnRyeTogXCIuL3NyYy9tYWluLmpzeFwiLFxuICByZXNvbHZlOiB7XG4gICAgZXh0ZW5zaW9uczogW1wiLmpzXCIsIFwiLmpzeFwiLCBcIi5qc29uXCJdLFxuICB9LFxuICBtb2R1bGU6IHtcbiAgICBydWxlczogW1xuICAgICAge1xuICAgICAgICB0ZXN0OiAvLmpzeCQvLFxuICAgICAgICB1c2U6IHtcbiAgICAgICAgICBsb2FkZXI6IFwiYnVpbHRpbjpzd2MtbG9hZGVyXCIsXG4gICAgICAgICAgb3B0aW9uczoge1xuICAgICAgICAgICAganNjOiB7 …
=> feat(browser): add `BrowserImportEsmPlugin`

scripts/release/publish.mjs, scripts/release/version.mjs
Check package name when checking if there a mistake in pre-release
=> fix(ci): should check package name in pre-release check

website/components/i18n/en.json, website/components/i18n/zh.json, website/docs/en/plugins/index.mdx, website/docs/en/plugins/rspack/virtual-modules-plugin.mdx, website/docs/zh/plugins/index.mdx, website/docs/zh/plugins/rspack/virtual-modules-plugin.mdx
Improve virtual-modules-plugin documentation:
- Add version info to `ApiMeta`
- Update config examples to use ES modules syntax
=> docs: improve virtual-modules-plugin documentation

crates/rspack_binding_api/src/raw_options/raw_builtins/mod.rs
I think `ProgressPlugin`, `RsdoctorPlugin` and `RstestPlugin` will not be used in browser.
Noted that I keep `RslibPlugin` because we may show rslib cases in browser?
Before: 27.01MB
After: 26.63MB
=> perf(browser): disable `ProgressPlugin`, `RsdoctorPlugin` and `RstestPlugin`

crates/rspack_core/src/build_chunk_graph/incremental.rs, tests/e2e/cases/chunk/recover-error/index.test.ts, tests/e2e/cases/chunk/recover-error/rspack.config.js, tests/e2e/cases/chunk/recover-error/src/App.jsx, tests/e2e/cases/chunk/recover-error/src/AppIndex.jsx, tests/e2e/cases/chunk/recover-error/src/index.html, tests/e2e/cases/chunk/recover-error/src/main.jsx, tests/e2e/cases/hooks/asset-emitted/index.test.ts, tests/e2e/fixtures/fileAction.ts, tests/e2e/fixtures/rspack.ts
affected modules should update in code splitting
=> fix: code splitting incremental missing module to update

crates/rspack_plugin_javascript/src/parser_plugin/drive.rs, crates/rspack_plugin_javascript/src/parser_plugin/import_meta_plugin.rs, crates/rspack_plugin_javascript/src/parser_plugin/trait.rs, crates/rspack_plugin_javascript/src/utils/eval/eval_member_expr.rs, crates/rspack_plugin_javascript/src/visitors/dependency/parser/mod.rs, packages/rspack-test-tools/tests/configCases/plugins/define-plugin-import-meta/index.js, packages/rspack-test-tools/tests/configCases/plugins/define-plugin-import-meta/webpack.config.js
fix https://github.com/web-infra-dev/rspack/issues/11504
=> fix: import.meta.prop with define plugin

website/docs/en/blog/index.mdx, website/docs/zh/blog/index.mdx
- Add new article blog tree shaking principles to the blog list
- Fix capitalization in "RSC and Server Action bundle practice" title
=> docs: add tree shaking blog to the blog list

crates/rspack_core/src/chunk_graph/chunk_graph_chunk.rs, crates/rspack_core/src/chunk_graph/chunk_graph_module.rs, crates/rspack_core/src/dependency/runtime_template.rs, crates/rspack_plugin_runtime/src/runtime_module/runtime_id.rs
A little improvement of `for_each_runtime` which is used during `create_module_hashes`
=> perf: improve for each runtime

packages/rspack-test-tools/tests/configCases/inline-const/dev/index.js, packages/rspack-test-tools/tests/configCases/inline-const/dev/rspack.config.js, packages/rspack/src/config/defaults.ts, website/docs/en/config/module.mdx, website/docs/en/guide/features/builtin-swc-loader.mdx, website/docs/zh/config/module.mdx, website/docs/zh/guide/features/builtin-swc-loader.mdx
fix https://github.com/web-infra-dev/rspack/issues/11589
=> fix: only enable inline const in production

website/docs/en/guide/features/esm.mdx, website/docs/zh/guide/features/esm.mdx
=> docs: fix esm syntax error

packages/rspack-test-tools/tests/configCases/css-chunking-plugin/base-global-css-chunking/rspack.config.js
=> fix: flaky css chunking test case

tests/e2e/cases/lazy-compilation/default-prefix/index.test.ts, tests/e2e/cases/lazy-compilation/default-prefix/rspack.config.js, tests/e2e/cases/lazy-compilation/default-prefix/src/index.js
One of the e2e cases (lazy-compilation/default-prefix) has flasky, this may fix that
=> fix: e2e lazy-compialtion/default-prefix flasky

tests/rspack-test/package.json
=> chore: make @rspack/tests private

crates/node_binding/binding.js
sync change from https://github.com/napi-rs/napi-rs/pull/2907
=> fix(core): support NAPI_RS_NATIVE_LIBRARY_PATH

tests/rspack-test/cacheCases/common/build-dependencies-resolve/file.js, tests/rspack-test/cacheCases/common/build-dependencies-resolve/index.js, tests/rspack-test/cacheCases/common/build-dependencies-resolve/node_modules/lib/package.json, tests/rspack-test/cacheCases/common/build-dependencies-resolve/rspack.config.js
This PR does not update build dependency files immediately to avoid probabilistic failures.
=> ci: fix build-dependencies-resolve test case

website/docs/en/misc/team/join-us.mdx, website/docs/zh/misc/team/join-us.mdx
Update join-us page content and structure:
- Update location information, team description and project listings.
- Move team member details to core-team page.
=> docs: update join-us page content and structure

crates/rspack_core/src/cache/persistent/occasion/make/module_graph.rs, crates/rspack_core/src/dependency/mod.rs, crates/rspack_core/src/exports/export_info_getter.rs, crates/rspack_core/src/exports/exports_info_getter.rs, crates/rspack_core/src/module_graph/connection.rs, crates/rspack_core/src/module_graph/mod.rs, crates/rspack_core/src/stats/mod.rs, crates/rspack_plugin_javascript/src/dependency/esm/esm_export_imported_specifier_dependency.rs, crates/rspack_plugin_javascript/src/dependency/esm/esm_export_specifier_dependency.rs, crates/rspack_plugin_javascript/src/dependency/esm/esm_import_dependency.rs, crates/rspack_plugin_javascript/src/dependency/esm/esm_import_specifier_dependency.rs, crates/rspack_plugin_javascript/src/dependency/export_info_dependency.rs, crates/rspack_plugin_javascript/src/dependency/url/mod.rs, crates/rspack_plugin_javascript/src/parser_plugin/inline_const.rs, crates/rspack_plugin_javascript/src/parser_plugin/inner_graph/mod.rs, crates/rspack_plugin_javascript/src/parser_plugin/mod.rs, crates/rspack_plugin_javascript/src/plugin/module_concatenation_plugin.rs, tests/rspack-test/__snapshots__/StatsAPI.test.js.snap, tests/rspack-test/__snapshots__/StatsOutput.test.js.snap, tests/rspack-test/configCases/inline-const/connection-active/a.js, tests/rspack-test/configCases/inline-const/connection-active/index.js, tests/rspack-test/configCases/inline-const/connection-active/lib.js, tests/rspack-test/configCases/inline-const/connection-active/reexport.js, tests/rspack-test/configCases/inline-const/connection-active/rspack.config.js, tests/webpack-test/__snapshots__/StatsTestCases.basictest.js.snap
fix https://github.com/web-infra-dev/rspack/issues/11697
=> fix: inline value condition connection active for re-export

crates/rspack_plugin_mf/src/container/hoist_container_references_plugin.rs, tests/rspack-test/watchCases/async-modules/top-level-await/0/case1/index.js, tests/rspack-test/watchCases/chunks/mf-hoisting-multi-entries/0/a.js, tests/rspack-test/watchCases/chunks/mf-hoisting-multi-entries/0/b.js, tests/rspack-test/watchCases/chunks/mf-hoisting-multi-entries/0/getWorker.js, tests/rspack-test/watchCases/chunks/mf-hoisting-multi-entries/0/main.js, tests/rspack-test/watchCases/chunks/mf-hoisting-multi-entries/0/worker.js, tests/rspack-test/watchCases/chunks/mf-hoisting-multi-entries/1/main.js, tests/rspack-test/watchCases/chunks/mf-hoisting-multi-entries/rspack.config.js, tests/rspack-test/watchCases/chunks/mf-hoisting-multi-entries/test.config.js, tests/rspack-test/watchCases/chunks/mf-hoisting/0/main.js
fix https://github.com/web-infra-dev/rspack/issues/11735
=> fix: mf should correctly hoist modules

crates/rspack_plugin_javascript/src/parser_plugin/import_parser_plugin.rs, tests/rspack-test/normalCases/chunks/statical-dynamic-import-then/index.js
fix https://github.com/web-infra-dev/rspack/issues/11759
=> fix: should always walk import then arguments

tests/rspack-test/cacheCases/invalidation/lib-symlink/file.js, tests/rspack-test/cacheCases/invalidation/lib-symlink/index.js, tests/rspack-test/cacheCases/invalidation/lib-symlink/libs/tools_v1/index.js, tests/rspack-test/cacheCases/invalidation/lib-symlink/libs/tools_v1/package.json, tests/rspack-test/cacheCases/invalidation/lib-symlink/libs/tools_v2/index.js, tests/rspack-test/cacheCases/invalidation/lib-symlink/libs/tools_v2/package.json, tests/rspack-test/cacheCases/invalidation/lib-symlink/rspack.config.js
Test case for https://github.com/web-infra-dev/rspack/issues/11595
=> test: add persistent cache symlink test case

packages/rspack/src/builtin-plugin/URLPlugin.ts
fix: URLPlugin in child compiler
TODO: should add a test case @JSerFeng
=> fix: URLPlugin in child compiler
