web-infra-dev/rspack

- Cargo.lock
- Cargo.toml
- crates/rspack_cacheable/Cargo.toml
- crates/rspack_cacheable/src/dyn/mod.rs
- crates/rspack_cacheable/src/dyn/validation.rs
- crates/rspack_cacheable/src/dyn/vtable_ptr.rs
- crates/rspack_cacheable/src/lib.rs
- crates/rspack_cacheable_test/Cargo.toml
- crates/rspack_cacheable_test/tests/macro/manual_cacheable_dyn.rs
- crates/rspack_cacheable_test/tests/macro/manual_cacheable_dyn_with_generics.rs
- crates/rspack_macros/src/cacheable_dyn.rs
Rspack persistent cache depends on [inventory](https://github.com/dtolnay/inventory/releases) v0.1. But it supports wasm in v0.3. The main barrier to upgrade is https://github.com/dtolnay/inventory/releases/tag/0.2.0. So this pr makes the following changes:
1. Mark the functions used in `inventory!` with `const`.
2. Calculate `__DYN_ID` with `xxhash-rust`, which supports calculating hash in const context(compile time). I think this also improves the performance.
3. Transmute dyn vtable to a new `VTablePtr` struct with `Send` and `Sync` rather than `usize`, and use `unsafe` to guarantee the safety. The reason is that transmuting a vtable address to `usize` is not permitted by rustc since it is unknown in compile time.
This pr does not mean there is no other problem to use persistent cache …
> chore: bump inventory 0.1 -> 0.3

- packages/rspack-test-tools/tests/configCases/plugins/source-map-dev-tool-plugin-child-compiler/test.config.js
- packages/rspack-test-tools/tests/configCases/plugins/source-map-dev-tool-plugin-file-context/test.config.js
Partially fixes #9056.
The `findBundle` option also needs to be added to a few other test cases, but those tests are a bit more tricky to fix. See #9056.
> test: add missing `findBundle` option to ensure test cases are executed

- crates/rspack/src/builder/mod.rs
- crates/rspack_binding_values/src/compilation/entries.rs
- crates/rspack_core/src/options/output.rs
- crates/rspack_plugin_runtime/src/lib.rs
- packages/rspack-test-tools/tests/__snapshots__/Config.test.js.snap
- packages/rspack-test-tools/tests/__snapshots__/NewCodeSplitting-config.test.js.snap
- packages/rspack-test-tools/tests/configCases/builtins/enable-chunk-loading/index.js
- packages/rspack-test-tools/tests/configCases/builtins/enable-chunk-loading/rspack.config.js
- packages/rspack/etc/core.api.md
- packages/rspack/src/builtin-plugin/EnableChunkLoadingPlugin.ts
- website/docs/en/config/output.mdx
- website/docs/en/plugins/webpack/enable-chunk-loading-plugin.mdx
- website/docs/zh/config/output.mdx
- website/docs/zh/plugins/webpack/enable-chunk-loading-plugin.mdx
Implement `EnableChunkLoadingPlugin.setEnabled` and `EnableChunkLoadingPlugin.checkEnabled` APIs.
These APIs are useful for making custom chunk loading.
> feat: add `EnableChunkLoadingPlugin.{setEnabled,checkEnabled}`

- crates/rspack_plugin_css/src/parser_and_generator/mod.rs
- crates/rspack_plugin_css/src/plugin/impl_plugin_for_css_plugin.rs
- packages/rspack-test-tools/tests/configCases/css/minify-lightning-css-remove-unused-local-idents/index.js
- packages/rspack-test-tools/tests/configCases/css/minify-lightning-css-remove-unused-local-idents/style.module.css
When we remove unused css local ident, we should only remove those whose `UseState` is explicit `Unused`
Eg.
```css
.foo {}
.bar {
composes: foo
}
```
If `bar` is unused, we should not remove its composes
> fix: should not tree shaking used ident accidentally in composes

- .github/renovate.json5
Rspack's npm updates have not been merged for a long time, see:
https://github.com/web-infra-dev/rspack/pull/8419
https://github.com/web-infra-dev/rspack/pull/8420
These PRs contains too many updates, making them difficult to merge. We can split npm updates into fine-grained PRs to make them eaiser to merge.
> chore(renovate): split npm updates into fine-grained PRs

- crates/rspack_core/src/normal_module.rs
The `last_successful_build_meta` is used to avoid parent module interop code error when current module rebuild failed, but rspack will always remove the module which need rebuild and use [fix_build_meta](https://github.com/web-infra-dev/rspack/blob/main/crates/rspack_core/src/compiler/make/cutout/fix_build_meta.rs) to achieve the same effect.
> refactor: remove `NormalModule` last_successful_build_meta field

- website/docs/en/guide/tech/nestjs.mdx
- website/docs/zh/guide/tech/nestjs.mdx
After executing `cross-env BUILD=true rspack build`, it will appear
```
Invalid configuration object. Rspack has been initialized using a configuration object that does not match the API schema.
- Unrecognized key(s) in object: 'rule' at "module"
```
After comparing the [example content](https://github.com/rspack-contrib/rspack-examples/blob/03aa9913fe1208173111488860a56bfd56d15aaf/rspack/nestjs/rspack.config.js#L15), I found that `rule` should be `rules`.
> docs(typo): Fix rspack.config typo in nestjs

- pnpm-lock.yaml
- website/docs/en/config/context.mdx
- website/docs/en/config/devtool.mdx
- website/docs/en/config/module.mdx
- website/docs/en/guide/start/quick-start.mdx
- website/docs/en/types/logger.mdx
- website/docs/zh/config/context.mdx
- website/docs/zh/config/devtool.mdx
- website/docs/zh/config/module.mdx
- website/docs/zh/guide/start/quick-start.mdx
- website/docs/zh/types/logger.mdx
- website/package.json
- website/rspress.config.ts
- website/theme/index.css
- website/theme/index.tsx
- Support for tabbed code blocks for ESM/CJS toggle, this allows us to provide more ESM configuration examples for users.
- Update Rspress to v1.41.1, see https://github.com/web-infra-dev/rspress/releases/tag/v1.41.1
- Improve Collapse border color in dark mode:
- Added Bluesky social icon.
> docs: support for tabbed code blocks for ESM/CJS toggle

- crates/rspack_storage/src/pack/manager/mod.rs
- crates/rspack_storage/src/pack/strategy/mod.rs
- crates/rspack_storage/src/pack/strategy/split/util.rs
- crates/rspack_storage/src/pack/strategy/split/write_scope.rs
- crates/rspack_storage/tests/release.rs
After loading data from storage, release pack contents based on generation to reduce memory consumption
---
This pull request introduces several changes to the `rspack_storage` crate, focusing on enhancing the scope management and release strategy. The most significant updates include adding a new method for releasing scopes, integrating this method into various parts of the codebase, and updating tests to reflect these changes.
Enhancements to scope management:
* [`crates/rspack_storage/src/pack/manager/mod.rs`](diffhunk://#diff-7ee17253ffd9ac23b524cf783f06f220bbd76c2a661480c10b5ded7c24102dc4L149-R151): Modified `ScopeManager` to release scopes after getting their contents and saving them. [[1]](diffhunk://#diff-7ee17253ffd9ac23b524cf783f06f220bbd76c2a661480c10b5ded7c24102dc4L149-R151) …
> perf(storage): release pack contents after loading

- crates/rspack/src/builder/mod.rs
- crates/rspack/src/builder/target.rs
- tasks/benchmark/benches/build_chunk_graph.rs
Only expose `Compiler::builder().build` and `CompilerBuilder::default().build`.
> fix: do not expose `build()` for level-2 options builder

- .taplo.toml
- Cargo.lock
- Cargo.toml
- crates/rspack/Cargo.toml
- crates/rspack/src/builder/mod.rs
- crates/rspack/tests/defaults.rs
- crates/rspack/tests/snapshots/defaults__default_options-2.snap
- crates/rspack/tests/snapshots/defaults__default_options.snap
- crates/rspack_binding_values/src/raw_options/raw_output.rs
- crates/rspack_core/src/options/entry.rs
- crates/rspack_core/src/options/output.rs
This PR adds default option test. Default option of `Compiler::builder` should be aligned with JS.
This was done by compare Rust options with JS options manually.
> fix: align default options with JS

- website/docs/en/config/externals.mdx
- website/docs/en/config/index.mdx
- website/docs/zh/config/externals.mdx
- website/docs/zh/config/index.mdx
Rewrite configure Rspack section, major changes:
1. Add guide for Node.js v23.6.0+, the `--experimental-transform-types` flag is no longer required.
2. Use `<Tabs>` to better display different configuration formats.
3. Improve "Type checking" guide.
> docs: rewrite configure Rspack section

- packages/rspack/src/config/adapter.ts
- tests/webpack-test/configCases/contenthash/assets/test.filter.js
Fixes #8604 
For the `asset/source` module type, the generator options will not used and therefore can be safely ignored in the config adapter.
> fix: ignore generator options for `asset/source` module type

- website/docs/en/guide/tech/css.mdx
- website/docs/zh/guide/tech/css.mdx
Tailwind CSS v4 has been released and Rspack's Tailwind CSS guide is out of date.
This PR adds links to the official Tailwind CSS guide for both v3 and v4, so we no longer need to maintain the guides.
> docs: link to Tailwind CSS v4 documentation

- crates/node_binding/src/plugins/mod.rs
- crates/rspack_plugin_devtool/src/eval_dev_tool_module_plugin.rs
- crates/rspack_plugin_devtool/src/eval_source_map_dev_tool_plugin.rs
- crates/rspack_plugin_html/src/plugin.rs
- crates/rspack_plugin_javascript/src/plugin/api_plugin.rs
- crates/rspack_plugin_javascript/src/plugin/mod.rs
- crates/rspack_plugin_javascript/src/runtime.rs
- crates/rspack_plugin_library/src/amd_library_plugin.rs
- crates/rspack_plugin_library/src/assign_library_plugin.rs
- crates/rspack_plugin_library/src/export_property_library_plugin.rs
- crates/rspack_plugin_library/src/modern_module_library_plugin.rs
- crates/rspack_plugin_library/src/module_library_plugin.rs
- crates/rspack_plugin_library/src/system_library_plugin.rs
- crates/rspack_plugin_library/src/umd_library_plugin.rs
- crates/rspack_plugin_rsdoctor/src/plugin.rs
- crates/rspack_plugin_runtime/src/array_push_callback_chunk_format.rs
- crates/rspack_plugin_runtime/src/common_js_chunk_format.rs
- crates/rspack_plugin_runtime/src/module_chunk_format.rs
- crates/rspack_plugin_runtime/src/runtime_plugin.rs
- crates/rspack_plugin_swc_js_minimizer/src/lib.rs
Get plugin hooks by compilation id. Some hooks may not pass the whole compilation through its arguments
---
This pull request includes several changes to the `get_compilation_hooks_mut` and `get_compilation_hooks` methods across multiple plugins to use `compilation.id()` instead of passing the entire `compilation` object. This change aims to standardize how compilation hooks are retrieved by using the compilation ID directly.
Changes to `get_compilation_hooks_mut` and `get_compilation_hooks` methods:
* [`crates/node_binding/src/plugins/mod.rs`](diffhunk://#diff-de65e35cd9f7b92416361921863c2eeb8b86694203ddd217395f16ce4e8164a1L446-R446): Updated `js_hooks_adapter_compilation`, `html_hooks_adapter_compilation`, `runtime_hooks_adapter_compilation`, and `rsdoctor_hooks_adapter_compilation` …
> refactor: get plugin hooks by compilation id

- packages/rspack/etc/core.api.md
- packages/rspack/src/builtin-plugin/lazy-compilation/backend.ts
- tests/e2e/cases/css/css-filename/index.test.ts
- website/docs/en/config/experiments.mdx
- website/docs/zh/config/experiments.mdx
The requestHandler of lazyCompilation should only handle request from lazy-compilation client.
If user defines `lazyCompilation.backend.server`, setup of the server should be handled by user who provide the server, so the listen method should be called by user as well.
But if user specify the listen behavior explicitly, lazyCompilation will use that listen
> fix: lazy compilation request handler should filter lazy-compilation request

- crates/rspack_plugin_lazy_compilation/src/module.rs
- crates/rspack_plugin_lazy_compilation/src/plugin.rs
Support more readable infomation when using lazy-compilation.
Before, the id of module that is lazy compiled is unreadable, eg: `?45ab`, now is module's `lib_ident` plus `!lazy-compilation-proxy`
> feat(lazy-compilation): support module id for LazyCompilationProxyModule

- crates/node_binding/binding.d.ts
- crates/rspack_binding_values/src/compilation/mod.rs
- crates/rspack_binding_values/src/module.rs
- crates/rspack_cacheable/src/with/as_preset/serde_json.rs
- crates/rspack_core/src/compiler/compilation.rs
- crates/rspack_core/src/compiler/module_executor/execute.rs
- crates/rspack_core/src/compiler/module_executor/mod.rs
- crates/rspack_core/src/concatenated_module.rs
- crates/rspack_core/src/module.rs
- crates/rspack_core/src/module_graph/mod.rs
- crates/rspack_core/src/stats/mod.rs
- crates/rspack_plugin_javascript/src/plugin/module_concatenation_plugin.rs
- packages/rspack-test-tools/tests/cacheCases/common/module-asset/file.js
- packages/rspack-test-tools/tests/cacheCases/common/module-asset/index.js
- packages/rspack-test-tools/tests/cacheCases/common/module-asset/loader.js
- packages/rspack-test-tools/tests/cacheCases/common/module-asset/rspack.config.js
- packages/rspack-test-tools/tests/runtimeDiffCases/module-interop/interop-test/plugin.js
- packages/rspack/etc/core.api.md
- packages/rspack/src/Compilation.ts
- packages/rspack/src/Module.ts
- packages/rspack/src/loader-runner/index.ts
1. move module assets to module.build_info.
``` rust
struct BuildInfo {
..
assets: HashMap<String, CompilationAsset>
}
```
2. compilaiton.create_module_assets emit module asset to compilation.assets
``` rust
impl Compilation {
fn create_module_assets(&mut self) {
for (mid, m) in mg.modules() {
for (filename, asset) in m.build_info().assets {
self.emit_asset(filename.clone(), asset.clone())
}
}
}
}
```
> refactor: build info save module asset

- Cargo.toml
- crates/node_binding/binding.d.ts
- crates/rspack_binding_values/src/html.rs
- crates/rspack_core/src/compiler/compilation.rs
- crates/rspack_core/src/options/output.rs
- crates/rspack_plugin_html/Cargo.toml
- crates/rspack_plugin_html/src/asset.rs
- crates/rspack_plugin_html/src/drive.rs
- crates/rspack_plugin_html/src/plugin.rs
- packages/rspack/src/builtin-plugin/html-plugin/taps.ts
Relate to https://github.com/web-infra-dev/rspack/issues/4381
Add compilation id to data structures of html plugin hooks.
---
This pull request includes several changes to the `rspack` project, primarily focusing on adding support for integrity attributes and incorporating `CompilationId` in various structures. The most important changes are summarized below:
* Added the `sha2` crate to the `Cargo.toml` file. [[1]](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542R74) [[2]](diffhunk://#diff-ff5d3405535927b7df3b3d04126df21b25ff5576d92e57440a7c91b0b112810cL28-R28)
* Introduced `CompilationId` in the `rspack_core` crate and updated its visibility to `pub`. [[1]](diffhunk://#diff-d63651f60ea732097aa6b9c63bf329e9c4b1bda6ef71e7ceec7d87ba5ece14aeR6) …
> refactor: add compilation id to html hook data

- Cargo.lock
- Cargo.toml
close https://github.com/web-infra-dev/rspack/issues/9224
close https://github.com/web-infra-dev/rspack/issues/9183
close https://github.com/web-infra-dev/rspack/issues/9135
The root cause is that rspack resolver unexpectedly enables yarn's pnp mode by default; if there is a `.pnp.cjs` file in the parent folder (or parent of parent folder),  resolving will fail.
In rspack_resolver@0.5.1 the pnp feature is enabled by respecting `options.enable_pnp`, thus disabled by default in rspack.
> fix(deps): ⬆️ rspack_resolver 0.5.1

- website/docs/en/api/javascript-api/index.mdx
- website/docs/en/guide/start/introduction.mdx
- website/docs/en/guide/start/quick-start.mdx
- website/docs/en/misc/planning/roadmap.mdx
- website/docs/zh/api/javascript-api/index.mdx
- website/docs/zh/guide/start/introduction.mdx
- website/docs/zh/guide/start/quick-start.mdx
- website/docs/zh/misc/planning/roadmap.mdx
- website/project-words.txt
- Updated Rspack roadmap to include Wasm build, Rstest and more.
- Updated the introduction page to link to the roadmap.
- Add [Re.pack](https://github.com/callstack/repack) to ecosystem.
> docs: update Rspack roadmap

- packages/rspack-cli/src/types.ts
- packages/rspack-cli/src/utils/loadConfig.ts
- packages/rspack-cli/src/utils/options.ts
According to my issue #9176 I prepare PR with implementation of `--disable-interpret` CLI option. 
This CLI option is analogue of same option in Webpack.
For myself this option is wery helpful because in my projects I use tsimp as main loader for TS.
> feat: add `--config-loader` CLI option

- crates/rspack_binding_values/src/compilation/mod.rs
- crates/rspack_core/src/compiler/compilation.rs
- packages/rspack-test-tools/tests/configCases/compilation/rebuild-module-multi-times/a.js
- packages/rspack-test-tools/tests/configCases/compilation/rebuild-module-multi-times/index.js
- packages/rspack-test-tools/tests/configCases/compilation/rebuild-module-multi-times/loader.js
- packages/rspack-test-tools/tests/configCases/compilation/rebuild-module-multi-times/rspack.config.js
- packages/rspack/etc/core.api.md
- packages/rspack/src/Compilation.ts
- packages/rspack/src/util/AsyncTask.ts
- website/docs/en/api/javascript-api/compilation.mdx
- website/docs/zh/api/javascript-api/compilation.mdx
close #9058
Introduce AsyncTask to replace MergeCaller, which is more robust. Make rebuildModule safe to use.
ModuleExecutor's `hook_after_make` should be called **after** `finish_modules` done
> fix: introduce AsyncTask, make rebuildModule safer

- Cargo.lock
- crates/node_binding/scripts/build.js
- crates/rspack_binding_values/Cargo.toml
- crates/rspack_binding_values/build.rs
when dts-cache enabled bindind.d.ts will wrongly generate empty definition which will cause ts error
the missing dts is caused by there're some crate napi which doesn't contain build.rs so we add build.rs for every crate which contains napi, thank you @Brooooooklyn's help
> chore: enable no-dts-cache by default

- .github/workflows/ci.yml
- Cargo.lock
- crates/rspack/Cargo.toml
- crates/rspack/src/builder/mod.rs
- crates/rspack/tests/fixtures/lightningcss/src/index.css
- crates/rspack/tests/fixtures/lightningcss/src/index.js
- crates/rspack/tests/fixtures/preact-refresh/src/index.jsx
- crates/rspack/tests/fixtures/react-refresh/src/index.jsx
- crates/rspack/tests/fixtures/swc/src/index.jsx
- crates/rspack/tests/loader.rs
- crates/rspack_loader_lightningcss/Cargo.toml
- crates/rspack_loader_lightningcss/src/lib.rs
- crates/rspack_loader_lightningcss/src/plugin.rs
- crates/rspack_loader_preact_refresh/Cargo.toml
- crates/rspack_loader_preact_refresh/src/lib.rs
- crates/rspack_loader_preact_refresh/src/plugin.rs
- crates/rspack_loader_react_refresh/Cargo.toml
- crates/rspack_loader_react_refresh/src/lib.rs
- crates/rspack_loader_react_refresh/src/plugin.rs
- crates/rspack_loader_swc/Cargo.toml
- crates/rspack_loader_swc/src/lib.rs
- crates/rspack_loader_swc/src/plugin.rs
Support enabling builtin loaders in compiler builder. 
Under the hood, rspack registers enabled loader plugins for loader resolving. 
Otherwise, an failed to resolve error will be reported.
Check out tests to see examples: https://github.com/web-infra-dev/rspack/blob/605d8ac816b4142492c239ac04e65bd59a746e6b/crates/rspack/tests/loader.rs
> feat: support enabling builtin loaders in compiler builder

- crates/rspack_core/src/compiler/make/cutout/has_module_graph_change.rs
- crates/rspack_core/src/compiler/make/repair/build.rs
- crates/rspack_core/src/concatenated_module.rs
- crates/rspack_core/src/context_module.rs
- crates/rspack_core/src/external_module.rs
- crates/rspack_core/src/module.rs
- crates/rspack_core/src/normal_module.rs
- crates/rspack_core/src/raw_module.rs
- crates/rspack_core/src/self_module.rs
- crates/rspack_error/src/diagnostic.rs
- crates/rspack_macros/src/runtime_module.rs
- crates/rspack_plugin_dll/src/dll_entry/dll_module.rs
- crates/rspack_plugin_dll/src/dll_reference/delegated_module.rs
- crates/rspack_plugin_extract_css/src/css_module.rs
- crates/rspack_plugin_javascript/src/dependency/esm/esm_import_dependency.rs
- crates/rspack_plugin_lazy_compilation/src/module.rs
- crates/rspack_plugin_mf/src/container/container_entry_module.rs
- crates/rspack_plugin_mf/src/container/fallback_module.rs
- crates/rspack_plugin_mf/src/container/remote_module.rs
- crates/rspack_plugin_mf/src/sharing/consume_shared_module.rs
- crates/rspack_plugin_mf/src/sharing/provide_shared_module.rs
- crates/rspack_plugin_mf/src/sharing/provide_shared_module_factory.rs
1. use &mut self for add_* method in Diagnosable trait, and remove useless method
``` diff
trait Diagnosable {
-  fn add_diagnostic(&self, _diagnostic: Diagnostic);
+ fn add_diagnostic(&mut self, _diagnostic: Diagnostic);
-  fn add_diagnostics(&self, _diagnostics: Vec<Diagnostic>);
+ fn add_diagnostics(&mut self, _diagnostics: Vec<Diagnostic>);
-  fn clone_diagnostics(&self) -> Vec<Diagnostic>;
-  fn take_diagnostics(&self) -> Vec<Diagnostic>;
-  fn pipe_diagnostics(&self, target: &dyn Diagnosable);
}
```
2. move diagnostics action from Module trait to Diagnosable trait
``` diff
trait Module {
-  fn get_diagnostics(&self) -> Vec<Diagnostic>;
}
trait Diagnosable {
+  fn diagnostics(&self) -> Cow<[Diagnostic]>;
}
```
> refactor: module diagnostic action move to `Diagnosable` trait

- crates/rspack_binding_values/src/chunk.rs
- crates/rspack_binding_values/src/chunk_group.rs
- crates/rspack_binding_values/src/compilation/mod.rs
- crates/rspack_binding_values/src/dependency.rs
- crates/rspack_binding_values/src/dependency_block.rs
- crates/rspack_binding_values/src/module.rs
- crates/rspack_binding_values/src/module_graph_connection.rs
- crates/rspack_binding_values/src/stats.rs
- crates/rspack_napi/src/js_values/mod.rs
- crates/rspack_napi/src/js_values/one_shot_instance_ref.rs
- crates/rspack_napi/src/js_values/one_shot_value_ref.rs
- crates/rspack_napi/src/lib.rs
`OneShotInstranceRef` will store the raw pointer for value which napi wrap. It will reduce a napi unwrap call, when get the wrapped value.
> perf: one shot ref for class instance

- crates/rspack_plugin_devtool/src/eval_source_map_dev_tool_plugin.rs
- packages/rspack-test-tools/tests/configCases/source-map/eval-source-map/index.js
- packages/rspack-test-tools/tests/configCases/source-map/eval-source-map/rspack.config.js
fix missing sourceURL field when devtool equals to `eval-source-map`, related to https://github.com/vercel/next.js/pull/75981#discussion_r1953463762
> fix(core): add sourceURL when devtool set to 'eval-source-map'

- pnpm-lock.yaml
- website/components/Collapse.tsx
- website/package.json
- website/theme/index.tsx
The `antd` package has a lot of npm dependencies.
This PR let the Rspack website to reuse antd from `@rstack-dev/doc-ui` to reduce npm dependencies and make CI faster.
> docs: reuse antd from `@rstack-dev/doc-ui`

- .github/workflows/ci.yml
- .github/workflows/ecosystem-benchmark.yml
- .github/workflows/ecosystem-ci.yml
- .github/workflows/reusable-build.yml
current build workflow is kind of too complex to maintain, remove unnecessary conditions(like native) to simplify workflow
* remove native condition: it's used to diff self-hosted runner and github runner since self-hosted not run in isolated environment, after it migrate to k8s there's no need to use docker to do isolate( and we all run in github runner now actually)
* explicitly tell difference between docker build and native build
* run in docker if we don't have related github runner machine
* run in native if we have related github runner machine
> chore: simplify ci workflow

- website/docs/en/api/cli.mdx
Docs for new CLI option that was added previously here:
https://github.com/web-infra-dev/rspack/pull/9210
> docs: config-loader CLI option

- crates/node_binding/binding.d.ts
- crates/rspack_binding_values/src/module.rs
- crates/rspack_core/src/concatenated_module.rs
- crates/rspack_core/src/module.rs
- crates/rspack_plugin_javascript/src/parser_plugin/esm_detection_parser_plugin.rs
- crates/rspack_plugin_javascript/src/plugin/module_concatenation_plugin.rs
Background: https://github.com/web-infra-dev/rspack/issues/9094#issuecomment-2642106741
> refactor: move module_argument and exports_argument to BuildInfo struct

- crates/rspack_core/src/utils/hash.rs
- To avoid incorrect matches, prevent matching `[ext]` as `[extname]`.
- Ensure placeholders like `[hash:]` or `[hash:o]` are not matched.
> refactor(rust): improve `replace_all_placeholder`

- crates/rspack_core/src/cache/persistent/occasion/make/mod.rs
The ModuleGraph generated from the persistent cache only contains modules that support serialization. Therefore, we need to filter make_failed_module to keep only the existing ones.
> fix: persistent cache remove non-existent modules from make_failed_module

- packages/rspack/scripts/check-documentation-coverage.ts
- website/docs/en/plugins/rspack/subresource-integrity-plugin.mdx
- website/docs/zh/plugins/rspack/subresource-integrity-plugin.mdx
This pull request includes significant additions to the documentation for the `SubresourceIntegrityPlugin` in both English and Chinese. The changes detail the usage, configuration, and features of the plugin.
Documentation Enhancements:
* [`website/docs/en/plugins/rspack/subresource-integrity-plugin.mdx`](diffhunk://#diff-55abaab5f1ba6905f2b665c40bf48109c1ae41cca197fdff822514df0e81997aR1-R184): Added comprehensive documentation for the `SubresourceIntegrityPlugin`, including usage examples, configuration options, and integration with HTML plugins.
* [`website/docs/zh/plugins/rspack/subresource-integrity-plugin.mdx`](diffhunk://#diff-aea840d68fed1c5cef3b284b81c54dd41151ba0e25a29d8613a85e38cb8bce1eR1-R176): Added Chinese translation of the documentation for the `SubresourceIntegrityPlugin`, …
> docs: add `SubresourceIntegrityPlugin`

- website/docs/en/config/output.mdx
Fixes a line of Chinese in the English docs
From what I can tell, this was accidentally added in https://github.com/web-infra-dev/rspack/pull/7167
> docs: fix Chinese comment in English docs

- .github/workflows/ci.yml
This pull request includes a small change to the `.github/workflows/ci.yml` file. The change modifies the command used to install `cargo-shear` to include the `--force` option.
* [`.github/workflows/ci.yml`](diffhunk://#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fL247-R247): Added the `--force` option to the `cargo binstall` command for `cargo-shear`.
> ci: cargo shear not found

- packages/rspack/src/builtin-plugin/lazy-compilation/backend.ts
- packages/rspack/src/builtin-plugin/lazy-compilation/plugin.ts
The lazy compilation backend needs to listen to the server's "listening" event, and we need to ensure that the backend is initialized before the `listen()` call.
There are two cases:
1. When using Rspack's default lazy compilation server, we can ensure this.
2. When users configured `backend.server`, the `listen()` method is called by the user, which is usually earlier than `compiler.hooks.beforeCompile` hook.
This PR moves up the timing of the backend initialization to avoid the second case.
> fix: initialize lazy compilation backend earlier

- packages/rspack/src/ExecuteModulePlugin.ts
Remove execution results cache when there is a new compilation to avoid mem leak
> fix: clear module_execution_results every compilation

- .github/workflows/release-canary.yml
This pull request includes updates to the GitHub Actions workflow configuration in the `.github/workflows/release-canary.yml` file. The most important changes involve adding a new input parameter for running tests and modifying the job configuration to use this new parameter.
Updates to GitHub Actions workflow:
* [`.github/workflows/release-canary.yml`](diffhunk://#diff-9f4438d00ff0b9f13896fd034278896ec94153fc2a5733b1852cbfce7ecaff77R10-R14): Added a new input parameter `test` to optionally run tests, which is not required and defaults to `false`.
* [`.github/workflows/release-canary.yml`](diffhunk://#diff-9f4438d00ff0b9f13896fd034278896ec94153fc2a5733b1852cbfce7ecaff77L64-R69): Modified the `jobs` section to use the new `test` input parameter instead of hardcoding the value to `false`.
> ci: add option to test when releasing canary

- website/docs/en/plugins/rspack/subresource-integrity-plugin.mdx
- website/docs/zh/plugins/rspack/subresource-integrity-plugin.mdx
This pull request includes updates to the `SubresourceIntegrityPlugin` usage examples in both the English and Chinese documentation files for the `rspack` plugin. The changes primarily involve refactoring the import statements and updating code formatting for consistency.
Refactoring and formatting updates:
* [`website/docs/en/plugins/rspack/subresource-integrity-plugin.mdx`](diffhunk://#diff-55abaab5f1ba6905f2b665c40bf48109c1ae41cca197fdff822514df0e81997aL49-R54): Updated import statements to use destructuring assignment for `experiments` and adjusted code formatting for consistency. [[1]](diffhunk://#diff-55abaab5f1ba6905f2b665c40bf48109c1ae41cca197fdff822514df0e81997aL49-R54) [[2]](diffhunk://#diff-55abaab5f1ba6905f2b665c40bf48109c1ae41cca197fdff822514df0e81997aL66-R88)
* …
> docs: fix import SRI statement

- .github/workflows/reusable-build.yml
fix https://github.com/web-infra-dev/rspack/issues/9372
we switch to native publish to save some build time in https://github.com/web-infra-dev/rspack/pull/9283/files but it cause glibc compatible problem, so revert back to docker publish workflow
> fix: revert linux x86_64 publish to docker

- .github/CODEOWNERS
The rspack-dev-middleware package was deprecated, this reference was missed.
Was helping someone debug an issue and was looking for this package. Was not able to find it in the codebase even though it looked like it was being published still. After verifying on NPM the package is deprecated.
> chore(codeowners): removing deprecated package

- packages/rspack/etc/core.api.md
- packages/rspack/src/config/types.ts
Change the `module` in the `LazyCompilationOptions` from `any` to `Module`.
```typescript
export type LazyCompilationOptions = {
// other properties
test?: RegExp | ((module: Module) => boolean);
};
```
Documentation has been updated: 
- https://rspack.dev/config/experiments#experimentslazycompilation
- https://github.com/web-infra-dev/rspack/blob/main/website/docs/en/config/experiments.mdx
> fix(type): Change the module in the LazyCompilationOptions from any to Module

- crates/node_binding/src/plugins/interceptor.rs
- crates/rspack_core/src/compiler/compilation.rs
- crates/rspack_core/src/compiler/module_executor/execute.rs
Remove the blocking call that running under make phase
> perf: remove blocking for execute module hook

- .github/workflows/reusable-build.yml
This pull request includes a minor change to the `.github/workflows/reusable-build.yml` file. The change modifies the `shared-key` parameter to include the prefix `build-bench` instead of `build`.
* [`.github/workflows/reusable-build.yml`](diffhunk://#diff-951765131741a39f193f7387e405bafacb9b9e836a17986e6c7480d6dc448cc3L393-R393): Changed `shared-key` from `build-${{ inputs.target }}-${{ inputs.profile }}` to `build-bench-${{ inputs.target }}-${{ inputs.profile }}`.
> ci: use different shared key between normal build and codspeed build

- .github/workflows/reusable-build.yml
- Start building codspeed in parallel
- Use `wait-on-check-action` to make sure the binary of build task is ready before running codspeed task
---
This pull request includes several updates to the `jobs` section in the `.github/workflows/reusable-build.yml` file. The key changes involve modifying the conditions and steps for the bench job, specifically around the installation of tools and the build process.
* **Modification of job dependencies and conditions:**
- Changed the `runs-on` condition for the `bench` job to use the `inputs.runner` instead of the output from the `build` job.
* **Addition of new steps for the `bench` job:**
- Added steps to install the Rust toolchain, install the `cargo-codspeed` binary, build the benchmark, and wait for the build job to complete.
* **Removal of …
> ci: run codspeed build in parallel

- crates/rspack_core/src/build_chunk_graph/incremental.rs
- crates/rspack_core/src/compiler/make/cutout/has_module_graph_change.rs
- crates/rspack_core/src/old_cache/local/code_splitting_cache.rs
- packages/rspack-test-tools/tests/watchCases/entries/dynamic-entries-remove/0/index0.js
- packages/rspack-test-tools/tests/watchCases/entries/dynamic-entries-remove/0/index1.js
- packages/rspack-test-tools/tests/watchCases/entries/dynamic-entries-remove/1/index0.js
- packages/rspack-test-tools/tests/watchCases/entries/dynamic-entries-remove/rspack.config.js
- packages/rspack-test-tools/tests/watchCases/entries/dynamic-entries-remove/test.config.js
Remove a dynamic entry should re-build chunk graph
> fix: remove dynamic entry should re-build chunk graph

- crates/rspack_core/src/compiler/compilation.rs
- crates/rspack_plugin_library/src/modern_module_library_plugin.rs
finish_modules means the module graph (modules, connections, dependencies) are frozen and start to optimize (provided exports, infer async, etc.) based on the module graph, so any kind of change that affect these should be done before the finish_modules.
> chore: move modern module library finish_modules to finish_make

- crates/rspack_core/src/incremental/mutations.rs
Use partition_map to avoid once unnecessary clone
Equal to:
```rust
let mut a = vec![];
let mut b = vec![];
c.for_each(|item| => {
match item {
Left(v) => a.push(v);
Right(v) => b.push(v);
}
})
```
> perf: use partition_map to avoid clone

- .github/workflows/ci.yml
It seems we do not need to run pnpm cache in some Rust jobs. Remove this step should make these workflows 30s faster.
For example:
> chore(workflow): no need to run pnpm cache in rust jobs

- .github/actions/pnpm-cache/action.yml
- .github/workflows/ci.yml
- .github/workflows/reusable-build.yml
There is no need to install the whole pnpm workspace dependencies when building binary
This pull request includes updates to the GitHub Actions workflows and custom actions to add more control over dependency installation and caching. The changes introduce a new input parameter to conditionally run the installation steps and update the workflows to use this new parameter.
Key changes:
* Added `run-install` input parameter to control whether the installation steps should be executed.
* Modified the steps to conditionally run based on the `run-install` input parameter. [[1]](diffhunk://#diff-703261f283281b1446d87cf7f07bc488f0ce5f0d7fc9162b04baf83bce29f5c7L43-R55) [[2]](diffhunk://#diff-703261f283281b1446d87cf7f07bc488f0ce5f0d7fc9162b04baf83bce29f5c7L65-R70) …
> ci: only install binding dependencies when building binary

- packages/rspack-test-tools/etc/test-tools.api.md
- packages/rspack-test-tools/src/case/stats-output.ts
- packages/rspack-test-tools/src/processor/basic.ts
- packages/rspack-test-tools/src/processor/hash.ts
- packages/rspack-test-tools/src/processor/hot-step.ts
- packages/rspack-test-tools/src/processor/simple.ts
- packages/rspack-test-tools/src/processor/snapshot.ts
- packages/rspack-test-tools/src/processor/stats-api.ts
- packages/rspack-test-tools/src/processor/stats.ts
- packages/rspack-test-tools/src/processor/watch.ts
- packages/rspack-test-tools/src/type.ts
- packages/rspack-test-tools/tests/configCases/module/rspack-issue-1652/test.config.js
- packages/rspack-test-tools/tests/configCases/module/rspack-issue-5548/test.config.js
- packages/rspack-test-tools/tests/configCases/output/rspack-issue-4338/test.config.js
- packages/rspack-test-tools/tests/configCases/plugins/swc-js-minifier/test.config.js
- packages/rspack-test-tools/tests/configCases/split-chunks/max-size-fit/test.config.js
- packages/rspack-test-tools/tests/watchCases/chunk-ids/id-equals-name/test.config.js
- packages/rspack-test-tools/tests/watchCases/chunk-ids/update-module/test.config.js
- packages/rspack-test-tools/tests/watchCases/module-ids/ignored-module/test.config.js
- packages/rspack-test-tools/tests/watchCases/module-ids/update-module/test.config.js
Not to call `stats.toJson` if it is not necessary. This may improve the performance of CI on windows. The following comparison is just a sample. It may also be affected by machine fluctuations.  
Before:
After:
---
This pull request introduces several enhancements and fixes to the `rspack-test-tools` package, focusing on improved handling and output of compiler statistics. The most important changes include the addition of new types for multi-stats, updates to various processors to handle these types, and the introduction of new configuration options for writing stats output and JSON files.
* Added new types `TCompilerMultiStats` to handle multi-stats for both `Rspack` and `Webpack` compilers. (`packages/rspack-test-tools/etc/test-tools.api.md` …
> test: should not call stats toJson if not necessary

- packages/rspack-cli/src/cli.ts
- packages/rspack-cli/src/types.ts
- packages/rspack-cli/src/utils/loadConfig.ts
- packages/rspack-cli/src/utils/options.ts
- packages/rspack-cli/tests/build/basic/basic.test.ts
- website/docs/en/api/cli.mdx
- website/docs/zh/api/cli.mdx
This PR updates the Rspack CLI flags to use camelCase consistently.
The [yargs](https://www.npmjs.com/package/yargs) package will convert camelCase to kebab-case, so both the two cases are supported:
> fix: update CLI flags to use camelCase consistently

- crates/rspack_core/src/utils/property_access.rs
- crates/rspack_core/src/utils/property_name.rs
They are redundantly defined in `property_name` and `property_access`, so one of them can be removed.
> refactor: remove duplicate static variable definitions

- crates/rspack_plugin_mf/src/sharing/consume_shared_module.rs
- packages/rspack-test-tools/src/helper/loaders/hot-update.ts
- packages/rspack-test-tools/tests/cacheCases/mf/issue-9150/file.js
- packages/rspack-test-tools/tests/cacheCases/mf/issue-9150/index.js
- packages/rspack-test-tools/tests/cacheCases/mf/issue-9150/rspack.config.js
The Module foundation plugin collects the consumption location and use `compilation.add_includes` to generate them as entry, but the plugin state cannot be saved to the persistent cache, which will cause bug when hot start.
https://github.com/web-infra-dev/rspack/blob/main/crates/rspack_plugin_mf/src/sharing/provide_shared_plugin.rs#L85
This PR will make the ConsumeSharedModule non-cacheable so that it is always regenerated on hot start to restore plugin state.
> fix: use persistent cache with module foundation

- crates/rspack_core/src/cache/persistent/mod.rs
- crates/rspack_core/src/compiler/compilation.rs
- crates/rspack_core/src/compiler/make/repair/mod.rs
- crates/rspack_core/src/compiler/mod.rs
- crates/rspack_core/src/compiler/rebuild.rs
- tasks/benchmark/benches/build_chunk_graph.rs
Persistent cache calculation of modified_files should only be run in `compilation.build`. This PR will add a field at compilation to mark whether it is in a rebuild.
``` rust
struct Compilation {
// A flag indicating whether the current compilation is being rebuilt.
is_rebuild: bool
}
```
> fix: persistent cache skip calc modified_files when rebuild

- crates/node_binding/package.json
- npm/darwin-arm64/package.json
- npm/darwin-x64/package.json
- npm/linux-x64-gnu/package.json
- npm/win32-x64-msvc/package.json
- package.json
- packages/create-rspack/package.json
- packages/rspack-cli/package.json
- packages/rspack-test-tools/package.json
- packages/rspack-tracing/package.json
- packages/rspack/package.json
* perf(loader-runner): memoize resolver creation for improved performance by @inottn in https://github.com/web-infra-dev/rspack/pull/9403
* perf: remove blocking for execute module hook by @ahabhgk in https://github.com/web-infra-dev/rspack/pull/9406
* perf: use partition_map to avoid clone by @JSerFeng in https://github.com/web-infra-dev/rspack/pull/9427
* feat: render chunk runtime template with dojang by @GiveMe-A-Name in https://github.com/web-infra-dev/rspack/pull/9407
* feat: using dojang to render runtime_template by @GiveMe-A-Name in https://github.com/web-infra-dev/rspack/pull/9422
* fix(incremental): enable incremental for full hash test by @ahabhgk in https://github.com/web-infra-dev/rspack/pull/9377
* fix: sort group by group index by @JSerFeng in …
> chore: release v1.2.6

- crates/rspack_core/src/chunk_graph/chunk_graph_module.rs
- crates/rspack_core/src/compiler/compilation.rs
- crates/rspack_core/src/module_graph/connection.rs
- crates/rspack_plugin_javascript/src/dependency/esm/esm_export_imported_specifier_dependency.rs
module hash should calculate connection's active state in each runtime, to avoid have same hash when connection's runtime condition is different
related: follow up fix for this workaround https://github.com/web-infra-dev/rspack/pull/9412/commits/d10ff9c408701f549be5fa7504addbbba54bb214
> fix: hash runtime condition for connection

- Cargo.toml
reduce profiling size  because npm publish has size limitation
> chore: reduce debug symbol size

- crates/rspack_plugin_library/src/assign_library_plugin.rs
- packages/rspack-test-tools/tests/configCases/library/cjs-static/index.js
- packages/rspack-test-tools/tests/configCases/library/cjs-static/rspack.config.js
- tests/webpack-test/configCases/library/1-use-library/webpack.config.js
Fixes https://github.com/web-infra-dev/rslib/issues/714#issuecomment-2668032852
> fix: commonjs static library mode

- packages/rspack-cli/src/commands/build.ts
- packages/rspack-cli/src/commands/preview.ts
- packages/rspack-cli/src/commands/serve.ts
- packages/rspack-cli/src/utils/options.ts
- packages/rspack-cli/tests/preview/basic/index.test.ts
- packages/rspack-cli/tests/preview/basic/rspack.config.js
- packages/rspack-cli/tests/preview/basic/src/index.js
- packages/rspack-cli/tests/preview/ts-config-file/index.test.ts
- packages/rspack-cli/tests/preview/ts-config-file/rspack.config.ts
- packages/rspack-cli/tests/preview/ts-config-file/src/index.js
- packages/rspack-cli/tests/utils/test-utils.ts
This PR fixes the failure of `rspack preview' to run with `rspack.config.ts'.
The preview command should inherit all common CLI flags to have the default value of `--configLoader`.
fix https://github.com/web-infra-dev/rspack/issues/9460
related https://github.com/web-infra-dev/rspack/pull/9210
> fix(cli): failed to run preview with TS config file

- packages/rspack/etc/core.api.md
- packages/rspack/src/Compiler.ts
- website/docs/en/api/javascript-api/compiler.mdx
- website/docs/zh/api/javascript-api/compiler.mdx
`compiler.compile` is an internal low-level method and should not be used by Rspack users.
This PR removes `compiler.compile` from the documentation and marks it as `@private`.
> chore: mark `compiler.compile` as private method

- .github/workflows/reusable-build.yml
Pnpm cache of CI is not updated because the cache saving is skipped in `build` task. So change saving to `test` task.
This pull request includes updates to the `.github/workflows/reusable-build.yml` file to improve the caching mechanism for node dependencies.
Improvements to caching conditions:
* [`.github/workflows/reusable-build.yml`](diffhunk://#diff-951765131741a39f193f7387e405bafacb9b9e836a17986e6c7480d6dc448cc3L71): Removed the `save-if` condition for saving the cache if the branch is `main` under certain conditions.
* [`.github/workflows/reusable-build.yml`](diffhunk://#diff-951765131741a39f193f7387e405bafacb9b9e836a17986e6c7480d6dc448cc3L311-R310): Updated the `save-if` condition to save the cache only if the branch is `main` and the node version is `18`.
> ci: save cache in test task

- packages/rspack/etc/core.api.md
- packages/rspack/src/config/adapterRuleUse.ts
- website/docs/en/api/loader-api/context.mdx
- website/docs/en/api/loader-api/examples.mdx
- website/docs/zh/api/loader-api/context.mdx
- website/docs/zh/api/loader-api/examples.mdx
- website/project-words.txt
- Complete loader context API documentation.
- Add JSDoc for the `LoaderContext` type.
- Add an example of TypeScript loader.
> docs: complete loader context API doc and JSDoc

- .github/actions/docker-build/action.yml
- .github/workflows/reusable-build.yml
use temp dir to avoid release debug eats all tmpfs memory, related to https://github.com/rust-lang/rust/issues/64276#issuecomment-529203825
> chore: use tmpdir to avoid no space left error

- website/docs/en/api/plugin-api/compilation-hooks.mdx
- website/docs/zh/api/plugin-api/compilation-hooks.mdx
When using process assets examples provided by the document, I encountered the following TS error: **Property 'PROCESS_ASSETS_STAGE_ADDITIONS' does not exist on type 'Compilation'.** 
Actually, asset processing stages are exported by `compiler.webpack.Compilation` instead of `compilation`. See [Webpack docs](https://webpack.js.org/api/compilation-hooks/#processassets).
> docs: fix the reference to process asset stages in examples

- crates/rspack_core/src/normal_module.rs
- tests/e2e/cases/make/failed_module_by_builtin_loader/index.test.ts
- tests/e2e/cases/make/failed_module_by_builtin_loader/rspack.config.js
- tests/e2e/cases/make/failed_module_by_builtin_loader/src/index.js
- tests/e2e/cases/make/failed_module_by_js_loader/index.test.ts
- tests/e2e/cases/make/failed_module_by_js_loader/loader.js
- tests/e2e/cases/make/failed_module_by_js_loader/rspack.config.js
- tests/e2e/cases/make/failed_module_by_js_loader/src/index.js
Builtin loaders throw error will make normal module does not contains  any file_dependencies and mark as cacheable, those modules will never rebuild forever with memory cache. This PR will mark those module as cacheable and set they resourcePath as file_dependencies.
> fix: rebuild ignore modules contain built-in loader errors

- tests/webpack-test/ConfigTestCases.template.js
- tests/webpack-test/TestCases.template.js
- tests/webpack-test/WatchTestCases.template.js
- Should not call `stats.toJson` or `stats.toString` if not necessary
- Remove timeout in watch test
Before:
After:
---
This pull request includes various changes to the test case templates in the `webpack-test` directory. The main focus of the changes is to remove the generation of `stats.txt` and `stats.json` files, streamline error and warning checks, and improve the handling of statistics in test cases.
Key changes include:
* [`tests/webpack-test/ConfigTestCases.template.js`](diffhunk://#diff-343c7fa0b0e89965b19d34f707ad05e30e3c0030d4da01dcccef9b8fd82c5f5aL337-R361): Commented out the code that writes `stats.txt` and `stats.json` files as they are not used in any test cases. [[1]](diffhunk://#diff-343c7fa0b0e89965b19d34f707ad05e30e3c0030d4da01dcccef9b8fd82c5f5aL337-R361) …
> test: improve webpack test performance

- .github/workflows/ci.yml
- Cargo.lock
- crates/rspack_loader_runner/src/loader.rs
- crates/rspack_plugin_copy/Cargo.toml
- crates/rspack_plugin_copy/src/lib.rs
cleanup for avoiding meaningless diff with more-js-api-v2
> chore: cleanup for avoiding meaningless diff with more-js-api-v2

- packages/rspack-test-tools/tests/errorCases/error-test-push.js
- packages/rspack-test-tools/tests/errorCases/error-test-set.js
- packages/rspack-test-tools/tests/errorCases/error-test-shift.js
- packages/rspack-test-tools/tests/errorCases/error-test-splice-1.js
- packages/rspack-test-tools/tests/errorCases/error-test-splice-2.js
- packages/rspack-test-tools/tests/errorCases/warning-test-push.js
- packages/rspack-test-tools/tests/errorCases/warning-test-set.js
- packages/rspack-test-tools/tests/errorCases/warning-test-shift.js
- packages/rspack-test-tools/tests/errorCases/warning-test-splice-1.js
- packages/rspack-test-tools/tests/errorCases/warning-test-splice-2.js
- packages/rspack/etc/core.api.md
- packages/rspack/src/Compiler.ts
- packages/rspack/src/MultiCompiler.ts
- packages/rspack/src/Watching.ts
Rspack `compiler.run` has the same functionality as webpack, the first call will cold start the build, subsequent calls will rebuild using the memory cache. The difference is that Rspack relies on `compiler.modifiedFiles` and `compiler.removedFiles` to invalidate the memory cache.
This PR will add a params to allow user to set `compiler.modifiedFiles` and `compiler.removedFiles` when call run.
> feat: compiler.run add options to set modifiedFiles and removedFiles

- package.json
- packages/rspack-cli/tests/build/basic/basic.test.ts
- packages/rspack-cli/tests/build/config/config.test.ts
This pull request includes several changes to the `package.json` scripts and test cases in the `rspack-cli` package to improve parallel execution and output path handling.
* Updated the `build:js` script to run in parallel for better performance.
* Updated the `test:unit` script to run tests in parallel.
> test: run cli test cases parallel

- crates/rspack_core/src/concatenated_module.rs
- packages/rspack-test-tools/tests/configCases/concatenate-modules/runtime-specific-external/a.js
- packages/rspack-test-tools/tests/configCases/concatenate-modules/runtime-specific-external/b.js
- packages/rspack-test-tools/tests/configCases/concatenate-modules/runtime-specific-external/comp.js
- packages/rspack-test-tools/tests/configCases/concatenate-modules/runtime-specific-external/rspack.config.js
- packages/rspack-test-tools/tests/configCases/concatenate-modules/runtime-specific-external/should-concat/connect.js
- packages/rspack-test-tools/tests/configCases/concatenate-modules/runtime-specific-external/should-concat/lib.js
- packages/rspack-test-tools/tests/configCases/concatenate-modules/runtime-specific-external/should-concat/value.js
- packages/rspack-test-tools/tests/configCases/concatenate-modules/runtime-specific-external/test.config.js
close #8649
Runtime Condition is used when an export is utilized in one runtime but not in another. Rspack will generate code like this:
```js
if (__webpack_require__.j === 'main') {
var lib = __webpack_require__('./foo');
}
```
This means that if users enter this code, the execution of 'foo' and its sub-modules will only occur if they go through the main runtime; otherwise, it can be skipped.
In our architecture, modules are connected through various connections. Some connections point to the same module, where one may be active in a particular runtime while others are not. This scenario can occur.
When this happens, we need to ensure that all connections are valid for the concatenated module to function properly.
```js
if (__webpack_require__.j === 'bar') {
var lib = …
```
> fix: concate with external runtime specific modules

- tests/webpack-test/cases/large/big-assets/index.js
- tests/webpack-test/cases/large/big-assets/test.filter.js
- tests/webpack-test/cases/large/many-replacements/test.filter.js
Add reason about why skip big-assets test, this test is toooooo slow and will create multiple >500mb files, always skip for saving my computer's disk
> chore: add reason about why skip big-assets test

- crates/node_binding/binding.d.ts
- crates/node_binding/src/raw_options/raw_cache.rs
- crates/rspack/src/builder/mod.rs
- crates/rspack_core/src/old_cache/mod.rs
- crates/rspack_core/src/old_cache/occasion/chunk_render.rs
- crates/rspack_core/src/old_cache/occasion/code_generate.rs
- crates/rspack_core/src/old_cache/occasion/process_runtime_requirements.rs
- crates/rspack_core/src/old_cache/storage/memory.rs
- crates/rspack_core/src/old_cache/storage/mod.rs
- crates/rspack_core/src/options/cache.rs
Close https://github.com/web-infra-dev/rspack/issues/9405
Added `maxGenerations` support for memory cache. By default, `maxGenerations` is set to 1.
The option is used to define how many cycles will memory cache survive if it's not being accessed to in future generations:
With `max_generations` set to x, the cache was generated on generation y, will be removed on generation x + y + 1. 
For example: Cache created on generation 0 will be removed on generation 2 with `max_generations` set to 1, if it's not accessed on generation 1.
This option is not being exposed to users for now, as the cache key is encoded with hash, resulting it's not likely to be reused between compilations if it's source was changed.
Lifting memory consumption in …
> feat(memory-cache): add `maxGenerations` support

- website/docs/en/plugins/webpack/module-federation-plugin.mdx
- website/docs/zh/plugins/webpack/module-federation-plugin.mdx
Update Module Federation syntax downgrade FAQ, add all `@module-federation/*` packages to `source.include` to avoid browser compatibility issues.
This change is to fix a syntax issue introduced in `@module-federation/webpack-bundler-runtime` in 0.9.1.
- https://github.com/module-federation/core/pull/3565
- https://github.com/web-infra-dev/rsbuild/actions/runs/13622050663/job/38073072909?pr=4690#step:7:920
> docs: update Module Federation syntax downgrade FAQ

- Cargo.lock
- crates/rspack_plugin_runtime/src/module_chunk_format.rs
Skip rendering chunks that do not exist / do not contain Module Type: 'javascript' 
This prevents rendering virtual chunks like provide, share-init etc from module federation.
> fix(rspack_plugin_runtime): do not render chunks that only contain non-js module types

- crates/node_binding/src/lib.rs
inspired by https://x.com/jarredsumner/status/1893195528764076534 
it seems result is not bad,15% faster(bench based on https://github.com/rspack-contrib/build-tools-performance on macOS) with 20% memory reduction, and I think the cause is
* every thread will allocation 2M memory, even the thread is lazy initialized we still get about hundreds of threads sometimes which bloat memory
* less thread with less lock contention
> perf: try reduce max_blocking_threads to save memory and reduce fs contention

- crates/node_binding/binding.d.ts
- crates/node_binding/src/module.rs
- crates/rspack_core/src/normal_module.rs
- packages/rspack-test-tools/tests/configCases/asset/change-filename-by-match-resource/index.js
- packages/rspack-test-tools/tests/configCases/asset/change-filename-by-match-resource/loader.js
- packages/rspack-test-tools/tests/configCases/asset/change-filename-by-match-resource/rspack.config.js
- packages/rspack/src/Module.ts
In https://github.com/web-infra-dev/rspack/pull/9177 we add a getter for `Module.matchResource`, which means we can't modify matchResource in loader by `this._module` anymore, this breaks [image-minimizer-webpack-plugin](https://github.com/webpack-contrib/image-minimizer-webpack-plugin/blob/519045cb2cb60acbc834dfe6e899b4874e8d8e99/src/loader.js#L272-L274)
This PR add the setter for compatibility reason, a better solution should be https://github.com/webpack/webpack/pull/18714 (related issue: https://github.com/webpack/webpack/issues/14851)
> fix: change module matchResource in loader

- Cargo.lock
- Cargo.toml
- crates/rspack_allocator/Cargo.toml
1. Bumped mimalloc to v3 for macOS. 
According to my [investigation](https://github.com/microsoft/mimalloc/issues/1025#issuecomment-2693504806), although memory is still growing, upgrading mimalloc to v3 will greatly mitigate the memory bloating issue in development mode. That is to say, memory growing is slower than it was on mimalloc-v2 for each time the compiler rebuilds:
**With mimalloc dev3-bin:**
```
hyperfine --warmup 2 --runs 5 './target/release/mimalloc-test'
Benchmark 1: ./target/release/mimalloc-test
Time (mean ± σ):      9.230 s ±  0.157 s    [User: 28.923 s, System: 13.791 s]
Range (min … max):    9.052 s …  9.450 s    5 runs
```
**With mimalloc dev2-bin (rspack main):**
```
hyperfine --warmup 2 --runs 5 './target/release/mimalloc-test'
Benchmark 1: …
```
> feat(memory-allocator): use mimalloc-v3 on macOS and bump mimalloc to v2.1.7 on other platforms

- crates/rspack_core/src/artifacts/cgm_hash_artifact.rs
- crates/rspack_core/src/build_chunk_graph/incremental.rs
- crates/rspack_core/src/chunk_graph/chunk_graph_module.rs
- crates/rspack_core/src/compiler/compilation.rs
- crates/rspack_core/src/compiler/rebuild.rs
- crates/rspack_core/src/incremental/mutations.rs
- crates/rspack_core/src/old_cache/local/code_splitting_cache.rs
- crates/rspack_core/src/runtime.rs
- packages/rspack-test-tools/tests/watchCases/entries/dynamic-entries-add-same-entry/0/index.js
- packages/rspack-test-tools/tests/watchCases/entries/dynamic-entries-add-same-entry/rspack.config.js
- packages/rspack-test-tools/tests/watchCases/entries/dynamic-entries-add-same-entry/test.config.js
Should re-build chunk graph when adding a entry connection, which connect a module that already exist in the module graph by other connections, checkout the test case for more detail
This fix both incremental and non-incremental for the case, and refactor incremental `get_affected_modules_with_chunk_graph`: before we use it for moduleHashes, moduleCodegen, and moduleRuntimeRequirement, we use some strategy to guess the affected chunk modules, but we didn't consider an important fact, that the `chunk.runtime` will also affect, moduleHashes already have a well tested strategy to find all the add/updated chunk modules, so we just to refactor to use moduleHashes to find the affected chunk modules directly
> fix: should re-build chunk graph when adding a entry connection

- packages/rspack-cli/src/cli.ts
- packages/rspack-cli/src/commands/build.ts
- packages/rspack-cli/src/commands/preview.ts
- packages/rspack-cli/src/commands/serve.ts
- packages/rspack-cli/src/types.ts
- packages/rspack-cli/src/utils/options.ts
- website/docs/en/api/cli.mdx
- website/docs/zh/api/cli.mdx
Enhance the `rspack preview` command:
- Add support for `--nodeEnv` flag
- Set `process.env.NODE_ENV` to `production` by default (align with Rsbuild and other community tools)
> feat(cli): `rspack preview` support for `nodeEnv` flag and default env

- packages/rspack-test-tools/src/case/builtin.ts
- packages/rspack-test-tools/src/case/cache.ts
- packages/rspack-test-tools/src/case/diagnostic.ts
- packages/rspack-test-tools/src/case/hash.ts
- packages/rspack-test-tools/src/case/normal.ts
Run `builtin`, `cache`, `diagnostic`, `normal` test cases concurrently
> test: run partial cases concurrently

- packages/rspack-test-tools/tests/NewIncremental-node.test.js
- packages/rspack-test-tools/tests/NewIncremental-web.test.js
- packages/rspack-test-tools/tests/NewIncremental-webworker.test.js
- packages/rspack/etc/core.api.md
- packages/rspack/src/builtin-plugin/lazy-compilation/backend.ts
- packages/rspack/src/builtin-plugin/lazy-compilation/plugin.ts
close #7578
close #8305
Each compiler instance should have its own lazyCompilation state. Implementing communication between compilers and lazyCompilation using a global state can be disrupted by different compilers.
> fix(lazy-compilation): should have separate state in multi-compiler

- crates/rspack_plugin_html/src/tag.rs
- tests/e2e/cases/html/asset-tag-hooks/index.test.ts
- tests/e2e/cases/html/asset-tag-hooks/rspack.config.js
- tests/e2e/cases/html/asset-tag-hooks/src/index.html
I was trying to implement an `HtmlRspackPlugin` addition using the `alterAssetTags` hook, and for my use case I needed to set `innerHTML` on the generated tag (to get something like `<script>console.log("Hello")</script>`). After a lot of confusion about why things weren't showing up as I expected and instead got empty tags, I went to look at the implementation and found that [`HtmlPluginTag` was always setting `children` to an empty vector](https://github.com/web-infra-dev/rspack/blob/39f2bfba38266f72ea9e2dcdaacffe5a23cc322f/crates/rspack_plugin_html/src/tag.rs#L282).
This PR fixes that to render the `innerHTML` property of the tag there as a plain `Text` node if it's present. I also tried to add an end to end test for this, but wasn't able to get them running locally immediately, so …
> fix(html): include `innerHTML` content in rendered asset tags

- website/docs/en/guide/start/quick-start.mdx
- website/docs/zh/guide/start/quick-start.mdx
- website/project-words.txt
Add Rspeedy and Lynx to ecosystem:
- [Rspeedy](https://lynxjs.org/rspeedy/) is an Rspack-based build tool specifically designed for Lynx applications.
- [Lynx](https://lynxjs.org/) is a family of technologies empowering developers to use their existing web skills to create truly native UIs for both mobile and web from a single codebase.
> docs: add Rspeedy and Lynx to ecosystem

- crates/rspack_core/src/chunk.rs
- crates/rspack_plugin_split_chunks/src/plugin/max_size.rs
- tests/webpack-test/__snapshots__/StatsTestCases.basictest.js.snap
- tests/webpack-test/statsCases/split-chunks-cache-group-filename/index.js
- tests/webpack-test/statsCases/split-chunks-cache-group-filename/node_modules/a.js
- tests/webpack-test/statsCases/split-chunks-cache-group-filename/node_modules/b.js
- tests/webpack-test/statsCases/split-chunks-cache-group-filename/node_modules/c.js
- tests/webpack-test/statsCases/split-chunks-cache-group-filename/webpack.config.js
This is a reimplementation of a PR I opened against webpack (https://github.com/webpack/webpack/pull/19104). We found that the `splitChunks.cacheGroups.{cacheGroup}.filename` config option was not being respected for any split initial chunks created based on the `maxSize`-based deterministic grouping.
I added a stats test case which configures `vendors` cache group (with `filename` options) for anything in `node_modules` but with a small `maxSize` so it creates many little chunks. This is the diff for the test from before and after the fix in case it helps:
```diff
- Entrypoint main 5.88 KiB = 990.js 352 bytes 961.js 352 bytes 727.vendors.js 352 bytes main.js 4.85 KiB
+ Entrypoint main 5.88 KiB = 990.vendors.js 352 bytes 961.vendors.js 352 bytes 727.vendors.js 352 bytes main.js 4.85 KiB …
```
> fix: copy filename_template into split chunks

- packages/rspack-test-tools/etc/test-tools.api.md
- packages/rspack-test-tools/jest.config.js
- packages/rspack-test-tools/src/test/creator.ts
`-t` can only affect `it()`, so the build of every case will always compile while running concurrently. So we need to filter it manually to skip the whole `describe()`. In the future, we can add more filter logic in test creator to improve the DX of `-t`.
---
This pull request introduces a new feature to filter tests based on a provided string and includes several related changes across multiple files. The most important changes include adding a `shouldRun` method to determine if a test should be executed, updating the Jest configuration to support the new test filter, and declaring a global variable for the test filter.
> test: fix import failed while running cases concurrently

- pnpm-lock.yaml
Run pnpm dedupe on project to reduce dependency duplications
> chore(deps): Dedupe pnpm dependencies

- tests/bench/ts-react.bench.ts
use codspeed to bench stats.toJson()
> chore: bench stats.toJson()

- .github/actions/artifact/download/action.yml
- .github/actions/artifact/upload/action.yml
- .github/workflows/ecosystem-benchmark.yml
- .github/workflows/ecosystem-ci.yml
- .github/workflows/reusable-build.yml
The ecosystem benchmark will build rspack with github runner and run it with self hosted runner, so download artifact should support force use github artifact.
> chore: ecosystem benchmark should download artifact from github

- .cargo/config.toml
- .github/actions/rustup/action.yml
- .github/actions/rustup/cache/action.yml
- .github/workflows/ci.yml
- rust-toolchain.toml
1. Nightly will always install rust-docs which rspack does not use if install throw rust-toolchain.toml.
2. There is no need to store rust cache if it is not on main branch.
3. Use CI profile to build binding on windows.
Before:
After:
> ci: install nightly components manually

- .github/workflows/ci.yml
Rollback part of https://github.com/web-infra-dev/rspack/pull/9576, change profile from ci to dev cause building binding is much slower on windows
> test: rollback windows ci profile to dev

- tests/webpack-test/Compiler.test.js
enable 3 webpack  test cases , because we add module info header plugin.
> test: pass more webpack test after ModuleInfoHeaderPlugin finished

- .vscode/launch.json
- Cargo.toml
- examples/basic/README.md
- examples/basic/index.js
- examples/basic/lib.js
- examples/basic/rspack.config.cjs
- website/docs/en/contribute/development/debugging.mdx
- website/docs/zh/contribute/development/debugging.mdx
This pull request includes several changes to improve debugging configurations and documentation for the Rspack project. The most important changes involve updates to the `.vscode/launch.json` file, enhancements to debugging documentation, and the addition of example files for debugging.
* [`.vscode/launch.json`](diffhunk://#diff-bd5430ee7c51dc892a67b3f2829d1f5b6d223f0fd48b82322cfd45baf9f5e945L3-R47): Removed outdated configurations and added new ones for debugging Rspack, including 
* `Debug Rspack`: use lldb to debug rust code 
* `Attach JavaScript`: used to debug javascript code
* `Attach Rust`: used to debug launched rspack process
Also added input options for rspack command and configuration path
* rspackProjectPath: rspack config path,  default to examples/basic/rspack.config.js, so …
> docs: add debugging guide

- packages/rspack/src/builtin-plugin/html-plugin/options.ts
- website/docs/en/plugins/rspack/html-rspack-plugin.mdx
- website/docs/zh/plugins/rspack/html-rspack-plugin.mdx
The `sri` option of html rspack plugin only support html tags and not support dynamic import chunk loading. The full-featured SRI has been supported by `SubresourceIntegrityPlugin`. So the `sri` option of html rspack should be deprecated.
> docs: deprecate `sri` option of HTML plugin

- packages/rspack-test-tools/jest.config.js
- packages/rspack-test-tools/src/processor/config.ts
- packages/rspack-test-tools/src/processor/hot.ts
- packages/rspack-test-tools/src/processor/watch.ts
- packages/rspack-test-tools/src/runner/runner/cjs.ts
- packages/rspack-test-tools/tests/configCases/hooks/stillValidModule/plugins/MyStillValidModulePlugin.js
- packages/rspack-test-tools/tests/configCases/hooks/succeedModule/plugins/MySucceedModulePlugin.js
- packages/rspack-test-tools/tests/configCases/svg/different-module-by-loaders/test.config.js
Too much useless logs are print during the test. Only output them when test with `--verbose`.
> test: should not output too much logs during the test

- Cargo.lock
- crates/rspack_plugin_runtime/Cargo.toml
- crates/rspack_plugin_runtime/src/runtime_module/jsonp_chunk_loading.rs
- crates/rspack_plugin_runtime/src/runtime_module/load_script.rs
- crates/rspack_storage/src/pack/manager/mod.rs
Add `unconstrained` to tokio spawn tasks to prevent deadlock which caused by budget exhaustion . See [tokio blog](https://tokio.rs/blog/2020-04-preemption) for more details.
> refactor: add unconstrained to tokio spawn tasks

- .vscode/extensions.json
- .vscode/launch.json
simplify debug jest test by providing a interactive workflow, it relys on https://marketplace.visualstudio.com/items?itemName=augustocdias.tasks-shell-input extension
https://github.com/user-attachments/assets/c7d7999a-9979-407b-afc4-9e592198269e
> chore(workflow): add interactive debug test launch

- packages/rspack-test-tools/package.json
Not to print `Warning: The 'NO_COLOR' env is ignored due to the 'FORCE_COLOR' env being set.` and `ExperimentalWarning: VM Modules is an experimental feature and might change at any time` during test.
> test: remove color setting and node warnings

- crates/node_binding/package.json
- pnpm-lock.yaml
add a `build:wasm` script used for locally test wasm build 
swc's wasm plugin is not supported now due to https://github.com/swc-project/swc/blob/bccdafc0c394bf3979da3c6a06d974c7d2c9bcee/crates/swc/src/plugin.rs#L68
> chore: add build:wasm scripts

- Cargo.lock
- crates/rspack_core/src/compiler/compilation.rs
- crates/rspack_futures/Cargo.toml
- crates/rspack_futures/src/lib.rs
- crates/rspack_futures/src/scope.rs
This introduces a new asynchronous structured concurrency abstraction that is designed to prevent misuse, but is still unsafe.
cc @hardfist
> Introduce rspack_futures::scope 

- .github/workflows/ci.yml
- Cargo.lock
- crates/rspack_core/Cargo.toml
- crates/rspack_core/src/compiler/compilation.rs
- crates/rspack_core/src/compiler/mod.rs
FutureResults will call blocking_in_place to support non `'static` future parallel, but if there're multi compilers call it multi times, it will cause all tokio runtime working blocking and other  spawned task can't be scheduled, which will cause deadlock.
Unfortunately there're no safe way to implement parallel future which is proved in https://tmandry.gitlab.io/blog/posts/2023-03-01-scoped-tasks/
so we need choose use unsafe code or sacrifice parallel(which means sacrifice performance), for us performance is important so I choose use unsafe code.
> fix(core): remove blocking to avoid deadlock for multi compiler

- Cargo.lock
- crates/rspack/Cargo.toml
- crates/rspack/src/builder/mod.rs
- crates/rspack/tests/basic.rs
- crates/rspack/tests/defaults.rs
- crates/rspack/tests/errors.rs
- crates/rspack/tests/loader.rs
- crates/rspack/tests/snapshots/errors__options-2.snap
- crates/rspack/tests/snapshots/errors__options.snap
- tasks/benchmark/benches/basic.rs
- tasks/benchmark/benches/build_chunk_graph.rs
Closing https://github.com/web-infra-dev/rspack/issues/9379
Support  printing `BuilderError` and remove panics.
`CompilerBuilder::build` now returns `rspack_error::Result<Compiler>` (previously, `Compiler`).
> feat(compiler-builder)!: support `BuilderError`

- crates/rspack_core/src/module_graph/mod.rs
- crates/rspack_plugin_library/src/modern_module/import_dependency.rs
- crates/rspack_plugin_library/src/modern_module/reexport_star_external_dependency.rs
- crates/rspack_plugin_library/src/modern_module_library_plugin.rs
1. `mg.revoke_dependency` will clean dependency at module and block when the `force` parameter is true
``` rust
impl ModuleGraph {
fn revoke_dependency(&mut self, dep_id: &DependencyId) {
...
if force {
original_module.remove_dependency_id(dep_id);
parent_block.remove_dependency_id(dep_id);
}
}
}
```
2. optimize ModernModule finish_make hook code, remove useless clone and module queries.
> fix: revoke dependency clean dependency at module and block

- Cargo.lock
- crates/rspack_core/Cargo.toml
- crates/rspack_core/src/compiler/compilation.rs
- crates/rspack_core/src/compiler/mod.rs
- crates/rspack_futures/Cargo.toml
- crates/rspack_futures/src/lib.rs
- crates/rspack_futures/src/scope.rs
future_scope is more safe than async_scope cause you need explicitly pass ref to it and reviewer just need to review whether the passed ref is still valid during future execution
> fix(core): use future_scope to run parallel future

- .github/workflows/ci.yml
- a.sh
the current macos runner is target to aarch64 which cause https://github.com/web-infra-dev/rspack/actions/runs/13832395298/job/38700157592#step:9:3 fail
> chore: test mac on main branch

- crates/rspack_core/src/build_chunk_graph/mod.rs
- crates/rspack_core/src/build_chunk_graph/new_code_splitter.rs
- crates/rspack_core/src/build_chunk_graph/remove_available_modules.rs
- crates/rspack_core/src/chunk.rs
- crates/rspack_core/src/chunk_graph/chunk_graph_chunk.rs
- crates/rspack_core/src/old_cache/local/code_splitting_cache.rs
- crates/rspack_core/src/options/entry.rs
CodeSplitting reuses some calculate result from previous build.
The new code splitting steps are as following:
1. Analyze blocks to find all chunk entry
2. Find chunk modules in parallel
3. Find chunk's parents and children based on incoming blocks and outgoing blocks
4. Remove modules in chunk which are already present in the parent chunks
5. Create chunk and chunk group, connect chunk and module
We can cache results from step 1, step 2 and reuse some chunk in step 5, so next stages in seal can get information about which chunk has changed
> feat: incremental for new code splitting

- website/theme/index.css
Apply new theme colors to the documentation site:
- New brand color
- Default code block color of Rspress
- Clean up unused variables
> docs: apply new theme colors to the documentation site

- Cargo.toml
disable lto in ci will speedup ci time
link time reduced from 5min to 1min
* before
* after
> chore: disable lto for ci

- website/docs/en/config/experiments.mdx
- website/docs/zh/config/output.mdx
Correct `experiments.outputModule` default value, should be `false`.
The Chinese documentation is correct and does not need updating.
> docs: correct `experiments.outputModule` default value

- Cargo.lock
- crates/rspack_storage/Cargo.toml
- crates/rspack_storage/src/pack/manager/mod.rs
- crates/rspack_storage/tests/dev.rs
- crates/rspack_storage/tests/error.rs
- crates/rspack_storage/tests/expire.rs
- crates/rspack_storage/tests/lock.rs
Remove `block_on` in rspack_storage to prevent deadlock. This modification will make the cache scopes not to merge until writing files. So remove related test cases which run `.load()` just after save and before receiving the signal of saving scopes.
> refactor: remove `block_on` in rspack_storage

- .cargo/config.toml
- crates/node_binding/src/lib.rs
LIFO has some know issues https://github.com/tokio-rs/tokio/issues/4941  which may cause work-stealing not work well in some edge cases and this optimization is used to ensure work fairness and work latency which is not meaningful for rspack, so disable it for better deterministic scheduler
> chore: disable tokio lifo optimization

- packages/rspack-test-tools/tests/configCases/errors/push-custom-error/errors.js
- packages/rspack-test-tools/tests/configCases/errors/push-custom-error/rspack.config.js
- packages/rspack/src/util/index.ts
Should convert `loc` field to string type. Some plugin(TsChecker for example) will push error to compilation which contains object type `loc` field, currently Rspack will just panic in that situation
Even if we are not consuming `loc` field, we should not panic
> fix: should convert diagnostic.loc to string

- .cargo/config.toml
- crates/node_binding/src/lib.rs
Reverts web-infra-dev/rspack#9706
https://github.com/web-infra-dev/rspack/actions/runs/13915075923/job/38939976174#step:14:1545 build on aarch64-linux-musl failed caused by https://github.com/napi-rs/napi-rs/issues/2151
> chore: revert "chore: disable tokio lifo optimization"

- Cargo.lock
- crates/node_binding/src/raw_options/raw_split_chunks/raw_split_chunk_cache_group_test.rs
- crates/node_binding/src/raw_options/raw_split_chunks/raw_split_chunk_name.rs
- crates/rspack_core/src/compiler/compilation.rs
- crates/rspack_plugin_ensure_chunk_conditions/src/lib.rs
- crates/rspack_plugin_limit_chunk_count/src/lib.rs
- crates/rspack_plugin_merge_duplicate_chunks/src/lib.rs
- crates/rspack_plugin_progress/src/lib.rs
- crates/rspack_plugin_remove_duplicate_modules/src/lib.rs
- crates/rspack_plugin_remove_empty_chunks/src/lib.rs
- crates/rspack_plugin_rsdoctor/src/plugin.rs
- crates/rspack_plugin_split_chunks/Cargo.toml
- crates/rspack_plugin_split_chunks/src/options/cache_group_test.rs
- crates/rspack_plugin_split_chunks/src/options/chunk_name.rs
- crates/rspack_plugin_split_chunks/src/plugin/mod.rs
- crates/rspack_plugin_split_chunks/src/plugin/module_group.rs
Remove `block_on` in split chunk `name` and `test` of cache group options.
> refactor: remove `block_on` in split chunk name and test

- crates/node_binding/binding.d.ts
- crates/node_binding/src/raw_options/raw_builtins/raw_copy.rs
- crates/rspack_plugin_copy/src/lib.rs
- packages/rspack-test-tools/tests/configCases/plugins/copy-plugin-transform/index.js
- packages/rspack-test-tools/tests/configCases/plugins/copy-plugin-transform/rspack.config.js
- packages/rspack-test-tools/tests/configCases/plugins/copy-plugin-transform/src/test.txt
- website/docs/en/plugins/rspack/copy-rspack-plugin.mdx
- website/docs/zh/plugins/rspack/copy-rspack-plugin.mdx
closes: #8957 
Api align need something more to support:
I will support cache feature after `compilation` support `compilation.get_cache()` function, so this pr will not execute it.
> feat(copyRspackPlugin): align transform api with webpack plugin

- Cargo.lock
- Cargo.toml
- crates/node_binding/Cargo.toml
- crates/node_binding/src/raw_options/raw_module/mod.rs
- crates/node_binding/src/raw_options/raw_split_chunks/raw_split_chunk_chunks.rs
- crates/rspack_core/src/normal_module.rs
- crates/rspack_core/src/options/module.rs
- crates/rspack_core/src/parser_and_generator.rs
- crates/rspack_plugin_asset/src/lib.rs
- crates/rspack_plugin_css/src/parser_and_generator/mod.rs
- crates/rspack_plugin_javascript/src/parser_and_generator/mod.rs
- crates/rspack_plugin_json/Cargo.toml
- crates/rspack_plugin_json/src/lib.rs
- crates/rspack_plugin_split_chunks/src/common.rs
- crates/rspack_plugin_split_chunks/src/plugin/max_size.rs
- crates/rspack_plugin_split_chunks/src/plugin/mod.rs
- crates/rspack_plugin_split_chunks/src/plugin/module_group.rs
- crates/rspack_plugin_wasm/src/parser_and_generator.rs
Remove `block_on` in asset generator to prevent deadlock
- Modify ParserAndGenerator::generate to async fn
- Say goodbye to pollster
> refactor: remove `block_on` in asset generator

- Cargo.lock
- clippy.toml
- crates/node_binding/Cargo.toml
- crates/node_binding/src/lib.rs
- crates/rspack_core/src/utils/fast_actions.rs
- crates/rspack_futures/src/scope.rs
add rule to forbid block_on and std::mem::forget
add worker name so profiler can differentiate it with other thread
* before:
* after:
> chore: add rayon worker name and forbid block_on

- website/docs/en/config/output.mdx
- website/docs/en/guide/features/_meta.json
- website/docs/en/guide/features/asset-base-path.mdx
- website/docs/zh/config/output.mdx
- website/docs/zh/guide/features/_meta.json
- website/docs/zh/guide/features/asset-base-path.mdx
Add a new guide page for `output.publicPath` and updates to existing configuration documentation.
Currently, Rspack documentation has two issues:
1. The configuration page is extremely long
2. Guide documentation is insufficient (compared to webpack)
We will reorganize the content as follows:
- Provide dedicated guide pages for each major feature
- For configuration options that have corresponding guides, move detailed content to the guide pages and add cross-references
This restructuring will make the documentation more organized and easier to navigate.
> docs: add guide for assets base path

- crates/rspack_futures/Cargo.toml
- crates/rspack_futures/src/lib.rs
This PR introduces `par_iter_then_collect` to provide rayon-like `par_iter().collect()` feature, but async. this is implemented based on `rspack_futures::scope`, so it requires unsafe.
cc @hardfist
> feat: introduce par_iter_then_collect

- crates/rspack_plugin_javascript/src/plugin/mod.rs
This PR refactors the use statements in the crates/rspack_plugin_javascript/src/plugin/mod.rs file to consolidate and organize them for better readability and maintainability. The redundant and unnecessary imports have been removed, ensuring a cleaner and more efficient import structure.
> chore: Consolidate and organize `use` statements for better readability

- crates/node_binding/binding.d.ts
- crates/node_binding/scripts/banner.d.ts
- crates/node_binding/src/modules/concatenated_module.rs
- crates/node_binding/src/modules/external_module.rs
- crates/node_binding/src/modules/normal_module.rs
1. `request`, `resource`, `userRequest`, `rawRequest`, `loaders` in `NormalModule` should not be undefined.
2. `modules` in `ConcatenatedModule` should not be undefined. 
3. `userRequest` in `ExternalModule` should not be undefined.
> fix: getter and setter type in module subtype

- crates/node_binding/src/asset.rs
- packages/rspack-test-tools/tests/configCases/compilation/emit-asset/rspack.config.js
```js
compilation.emitAsset("/foo.txt", new compiler.webpack.sources.RawSource("foo"), {
additionalKeys: ["foo", "bar"],
});
```
`additionalKeys` will transform to the array like object `{0: "foo", 1: "bar"}`. but we expected the array.
The reason is Rust not transform js array right.
> fix: array in asset info

- Cargo.lock
- Cargo.toml
- crates/rspack_ast/Cargo.toml
- crates/rspack_core/Cargo.toml
- crates/rspack_error/Cargo.toml
- crates/rspack_plugin_swc_js_minimizer/Cargo.toml
- packages/rspack-test-tools/tests/configCases/source-map/verify-es6-minify/index.js
Swc lastest version has a performance improvement in swc_ecma_minifier and fix some bugs in es/minifier and ts/fast-strip. So we bump swc version.
- bump `swc_core` to 16.10.0
- bump `swc_ecma_minifier` to 12.4.0
- bump `swc_error_reporters` to 9.1.1
By default, Swc using chili when open concurrent features, but chili has high Idle CPU usage. So swc recommends open concurrent features using rayon.
- Open `rayon` features when concurrent is open.
More detail see: https://github.com/swc-project/swc/issues/10243#issuecomment-2742856826
> chore(deps): bump swc to 16.10.0

- Cargo.lock
- crates/node_binding/binding.d.ts
- crates/node_binding/src/chunk_graph.rs
- crates/node_binding/src/stats.rs
- crates/rspack_core/src/chunk_graph/chunk_graph_module.rs
- crates/rspack_core/src/stats/mod.rs
- crates/rspack_core/src/stats/struct.rs
- crates/rspack_core/src/stats/utils.rs
- crates/rspack_ids/src/named_module_ids_plugin.rs
- crates/rspack_plugin_lazy_compilation/Cargo.toml
- crates/rspack_plugin_lazy_compilation/src/module.rs
- crates/rspack_plugin_runtime/src/helpers.rs
- packages/rspack-test-tools/tests/configCases/chunk-graph/get-module-id/rspack.config.js
- packages/rspack/etc/core.api.md
- packages/rspack/src/ChunkGraph.ts
- packages/rspack/src/stats/statsFactoryUtils.ts
`getModuleId` should return number for deterministic moduleIds
> fix: `getModuleId` should return number for deterministic moduleIds

- packages/rspack-test-tools/tests/configCases/compilation/update-context-dependencies/index.js
- packages/rspack-test-tools/tests/configCases/compilation/update-context-dependencies/rspack.config.js
- packages/rspack/src/util/MergeCaller.ts
- packages/rspack/src/util/fake.ts
MergeCaller will store the calls to `compilation.*_dependencies.add` and add them to the rust side in the next microtask. However, if methods such as `has` and `iterator` are called before the microtask is executed, these pending items will not be obtained.
``` js
compiler.hooks.afterCompile.tap("TEST", compilation => {
compilation.contextDependencies.add("/a");
console.log(compilation.contextDependencies.has("/a"))) // ==> false
console.log([...compilation.contextDependencies].includes("/a")) // ==> false
});
```
> fix: compilation.*_dependencies iterator ignore added items when sync call

- crates/node_binding/src/plugins/js_loader/scheduler.rs
- crates/rspack_core/src/compiler/compilation.rs
- crates/rspack_core/src/compiler/mod.rs
- crates/rspack_core/src/concatenated_module.rs
- crates/rspack_core/src/context_module_factory.rs
- crates/rspack_core/src/loader/loader_runner.rs
- crates/rspack_core/src/loader/rspack_loader.rs
- crates/rspack_core/src/normal_module.rs
- crates/rspack_core/src/normal_module_factory.rs
- crates/rspack_loader_runner/src/plugin.rs
- crates/rspack_loader_runner/src/runner.rs
- crates/rspack_macros/src/hook.rs
- crates/rspack_macros_test/tests/hook.rs
- crates/rspack_macros_test/tests/plugin.rs
- crates/rspack_plugin_devtool/src/eval_dev_tool_module_plugin.rs
- crates/rspack_plugin_devtool/src/eval_source_map_dev_tool_plugin.rs
- crates/rspack_plugin_extract_css/src/plugin.rs
- crates/rspack_plugin_hmr/src/lib.rs
- crates/rspack_plugin_html/src/drive.rs
- crates/rspack_plugin_javascript/src/parser_plugin/define_plugin/mod.rs
- crates/rspack_plugin_javascript/src/parser_plugin/provide_plugin.rs
- crates/rspack_plugin_javascript/src/plugin/drive.rs
- crates/rspack_plugin_javascript/src/plugin/impl_plugin_for_js_plugin.rs
- crates/rspack_plugin_javascript/src/plugin/mod.rs
- crates/rspack_plugin_library/src/assign_library_plugin.rs
- crates/rspack_plugin_library/src/modern_module_library_plugin.rs
- crates/rspack_plugin_real_content_hash/src/drive.rs
- crates/rspack_plugin_rsdoctor/src/drive.rs
- crates/rspack_plugin_runtime/src/drive.rs
There is no need to use sync hook in rust:
- Modify all sync hooks to async
- Remove macros of sync hook
- Rename async hook trait, remove `async` in their names cause
> refactor: async hooks in rust

- crates/node_binding/binding.d.ts
- crates/node_binding/src/module.rs
- crates/node_binding/src/raw_options/raw_builtins/raw_banner.rs
- crates/node_binding/src/raw_options/raw_builtins/raw_circular_dependency.rs
- crates/node_binding/src/raw_options/raw_builtins/raw_copy.rs
- crates/node_binding/src/raw_options/raw_builtins/raw_html.rs
- crates/node_binding/src/raw_options/raw_builtins/raw_ignore.rs
- crates/node_binding/src/raw_options/raw_builtins/raw_lazy_compilation.rs
- crates/node_binding/src/raw_options/raw_builtins/raw_progress.rs
- crates/node_binding/src/raw_options/raw_builtins/raw_runtime_chunk.rs
- crates/node_binding/src/raw_options/raw_builtins/raw_size_limits.rs
- crates/node_binding/src/raw_options/raw_builtins/raw_sri.rs
- crates/node_binding/src/raw_options/raw_devtool.rs
- crates/node_binding/src/raw_options/raw_dynamic_entry.rs
- crates/node_binding/src/raw_options/raw_external.rs
- crates/node_binding/src/raw_options/raw_module/mod.rs
- crates/node_binding/src/raw_options/raw_split_chunks/mod.rs
- crates/node_binding/src/raw_options/raw_split_chunks/raw_split_chunk_cache_group_test.rs
- crates/node_binding/src/raw_options/raw_split_chunks/raw_split_chunk_chunks.rs
- crates/node_binding/src/raw_options/raw_split_chunks/raw_split_chunk_name.rs
- crates/rspack_napi/src/threadsafe_function.rs
Clean threadsafe function methods:
- Remove `call_with_auto` and `call_with_fatal ` which is never used
- Remove `call` which can be replaced with `call_with_sync` or `call_with_promise`
- Replace all `call` to `call_with_sync` or `call_with_promise`, according to their function types
> The napi binding function types should not support both sync and async modes. The logic of compatibility should be written in JavaScript.
> The `blocking_call_with_sync` will be removed in the future
> refactor: clean threadsafe function methods

- website/docs/en/guide/features/_meta.json
- website/docs/en/guide/features/lazy-compilation.mdx
- website/docs/zh/guide/features/_meta.json
- website/docs/zh/guide/features/lazy-compilation.mdx
Improve the lazy compilation guide:
- Add `lazy-compilation.mdx` to sidebar to display it.
- Add description for `lazyCompilationMiddleware` options.
- Add Rsbuild `dev.lazyCompilation` link.
> docs: improve lazy compilation guide

- crates/rspack_core/src/build_chunk_graph/new_code_splitter.rs
As chunk creations are from different threads, they have no determined order, so the diagnostics should be sorted before we push them to compilation
> fix: sort diagnostics before push to compilation

- crates/node_binding/binding.d.ts
- crates/node_binding/src/options/raw_resolve.rs
- crates/node_binding/src/resolver.rs
- crates/rspack_core/src/options/resolve/clever_merge.rs
- crates/rspack_core/src/options/resolve/mod.rs
- crates/rspack_core/src/resolver/resolver_impl.rs
- packages/rspack-test-tools/tests/configCases/resolve/alias/index.js
- packages/rspack-test-tools/tests/configCases/resolve/alias/no-alias.js
- packages/rspack-test-tools/tests/configCases/resolve/alias/node_modules/@b/index.js
- packages/rspack-test-tools/tests/configCases/resolve/alias/rspack.config.js
- packages/rspack/etc/core.api.md
- packages/rspack/src/builtin-plugin/ExternalsPlugin.ts
- packages/rspack/src/config/adapter.ts
- packages/rspack/src/config/types.ts
- packages/rspack/src/config/zod.ts
[webpack supports object and array for alias](https://github.com/webpack/enhanced-resolve/blob/38e9fd9acb79643a70e7bcd0d85dabc600ea321f/lib/ResolverFactory.js#L158-L172), the difference is object will merge with the default resolve options alias but array will overwrite the default resolve options alias, unless there is `"..."`, and undefined is equal to {}, false is equal to [].
I've never seen a requirement that needs to support array, so for now I only support false here for simplicity.
> feat: support alias false

- packages/rspack-cli/src/utils/profile.ts
adjust default traceFilter to "info" since release binary doesn't support trace level otherwise it will generate following warning 
related to https://github.com/web-infra-dev/rspack/pull/9825
> chore: adjust defaultRustTraceFilter to info

- packages/rspack-test-tools/src/helper/legacy/supportsImportFn.js
- packages/rspack-test-tools/tests/configCases/loader-parallel/additional-data-no-passthrough/rspack.config.js
- packages/rspack-test-tools/tests/configCases/loader-parallel/additional-data-passthrough/rspack.config.js
- packages/rspack-test-tools/tests/configCases/loader-parallel/additional-data/rspack.config.js
- packages/rspack-test-tools/tests/configCases/loader-parallel/async/rspack.config.js
- packages/rspack-test-tools/tests/configCases/loader-parallel/binary-with-source-map/rspack.config.js
- packages/rspack-test-tools/tests/configCases/loader-parallel/issue-webpack-9053/rspack.config.js
- packages/rspack-test-tools/tests/configCases/loader-parallel/loader-error-async/rspack.config.js
- packages/rspack-test-tools/tests/configCases/loader-parallel/loader-raw-string/rspack.config.js
- packages/rspack-test-tools/tests/configCases/loader-parallel/loader-raw/rspack.config.js
- packages/rspack-test-tools/tests/configCases/loader-parallel/loader-string/rspack.config.js
- packages/rspack-test-tools/tests/configCases/loader-parallel/module-build-error/rspack.config.js
- packages/rspack-test-tools/tests/configCases/loader-parallel/options/rspack.config.js
- packages/rspack-test-tools/tests/configCases/loader-parallel/parallel-option/rspack.config.js
- packages/rspack-test-tools/tests/configCases/loader-parallel/pitching-mixed/rspack.config.js
- packages/rspack-test-tools/tests/configCases/loader-parallel/pitching/rspack.config.js
- packages/rspack-test-tools/tests/configCases/loader-parallel/pre-post-loader/rspack.config.js
- packages/rspack-test-tools/tests/configCases/loader-parallel/source-map/rspack.config.js
- packages/rspack-test-tools/tests/configCases/loader-parallel/sync/rspack.config.js
In this PR, tests relying on `import()` are disabled. It causes segmentation fault in `vm` with `--experimental-vm-modules`, which is exactly what jest has been relying on and the issue has not been resolved in node 16 yet according to my local test.
> test(loader-parallel): disable cases that rely on `import()` in node 16

- packages/rspack/src/Compilation.ts
- packages/rspack/src/NormalModule.ts
- packages/rspack/src/builtin-plugin/JavascriptModulesPlugin.ts
- packages/rspack/src/builtin-plugin/RsdoctorPlugin.ts
- packages/rspack/src/builtin-plugin/RuntimePlugin.ts
- packages/rspack/src/builtin-plugin/html-plugin/hooks.ts
Make Compilation check logs clearer and extract a helper function. 
This should help users resolve issues with Rspack multiple instances after upgrading to 1.3.0.
Related: https://github.com/web-infra-dev/rspack/issues/9841
> fix: make Compilation check logs clearer

- crates/rspack/src/lib.rs
- crates/rspack_core/src/options/context.rs
Polish rspack crate document and add `PathBuf` and `&Path` support to `Context`. This cuts a dependency that users need to rely on to run rspack in Rust.
> feat: support passing `PathBuf` and `&Path` to `Context`

- .github/workflows/reusable-build.yml
The docker image `ghcr.io/napi-rs/napi-rs/nodejs-rust:lts-alpine` will use [edge](https://wiki.alpinelinux.org/wiki/Repositories#Edge) repository in apk by default, which may cause the following unstable bugs.
This PR will set `/etc/apk/repositories` to the v3.21 stable release branch to fix these bugs.
Test CI: https://github.com/web-infra-dev/rspack/actions/runs/14170169636/job/39692016419
> ci: alpine apk use stable release branch

- Cargo.lock
- Cargo.toml
- packages/rspack-test-tools/tests/__snapshots__/StatsAPI.test.js.snap
- packages/rspack-test-tools/tests/statsAPICases/basic.js
Dependency updates:
* Updated `swc` to version `18.0.0` in `Cargo.toml`.
* Updated `swc_core` to version `18.0.0` with the `parallel_rayon` feature enabled in `Cargo.toml`.
* Updated `swc_ecma_minifier` to version `14.0.0` in `Cargo.toml`.
* Updated `swc_html` to version `14.0.0` in `Cargo.toml`.
* Updated `swc_html_minifier` to version `14.0.0` in `Cargo.toml`.
More detail see: [SWC ChangeLog](https://github.com/swc-project/swc/blob/main/CHANGELOG-CORE.md)
> chore: bump swc to v18.0.0

- Cargo.lock
- Cargo.toml
- crates/node_binding/Cargo.toml
- crates/node_binding/src/filename.rs
- crates/node_binding/src/fs_node/node.rs
- crates/node_binding/src/fs_node/write.rs
- crates/node_binding/src/lib.rs
- crates/node_binding/src/raw_options/raw_builtins/raw_circular_dependency.rs
- crates/node_binding/src/raw_options/raw_builtins/raw_copy.rs
- crates/node_binding/src/raw_options/raw_builtins/raw_http_uri.rs
- crates/node_binding/src/raw_options/raw_builtins/raw_ignore.rs
- crates/node_binding/src/raw_options/raw_builtins/raw_progress.rs
- crates/node_binding/src/raw_options/raw_module/mod.rs
- crates/node_binding/src/source.rs
This is necessary for rspack wasi.
There is a big break change: https://github.com/napi-rs/napi-rs/pull/2401. Rust tuple passed into tsfn now becomes a single array arg in js. We should wrap it into `FnArgs { data: (...) }`.
Before: rs `tsfn((a, b))` -> js `tsfn(a,b)`
After: rs `tsfn((a, b))` -> js `tsfn([a,b])`
We need change to rs `tsfn(FnArgs { data: (a, b) })`/`tsfn((a, b).into())` -> js `tsfn(a,b)`
Other changes:
1. `Buffer` does not impl `Clone` any more: https://github.com/napi-rs/napi-rs/pull/2462
2. re-export `ctor`: https://github.com/napi-rs/napi-rs/pull/2472
close: https://github.com/web-infra-dev/rspack/issues/9618
> chore: bump napi 3.0.0-alpha.24 -> 3.0.0-alpha.33

- packages/rspack-cli/package.json
- pnpm-lock.yaml
- tests/e2e/package.json
Update @rspack/dev-server to v1.1.1 to remove duplicated socket import code.
Related:
- https://github.com/web-infra-dev/rspack-dev-server/pull/27
- https://github.com/web-infra-dev/rspack-dev-server/issues/26
- https://github.com/web-infra-dev/rspack-dev-server/releases/tag/v1.1.1
> fix(deps): update @rspack/dev-server to v1.1.1

- packages/rspack-cli/tests/api/type/js-api-cjs.test.ts
Should use `require` instead of `import` to avoid some transformation behaviour.
> test: fix cjs js api tests

- crates/node_binding/src/compilation/mod.rs
- crates/node_binding/src/error.rs
- crates/node_binding/src/lib.rs
- crates/node_binding/src/plugins/js_cleanup_plugin.rs
- crates/node_binding/src/plugins/js_loader/resolver.rs
- crates/node_binding/src/raw_options/raw_builtins/mod.rs
- crates/node_binding/src/raw_options/raw_builtins/raw_lightning_css_minimizer.rs
- crates/rspack_core/src/context_module_factory.rs
- crates/rspack_core/src/options/filename.rs
- crates/rspack_core/src/resolver/resolver_impl.rs
- crates/rspack_core/src/runtime_template.rs
- crates/rspack_error/src/convert.rs
- crates/rspack_loader_lightningcss/src/config.rs
- crates/rspack_loader_lightningcss/src/lib.rs
- crates/rspack_loader_runner/src/runner.rs
- crates/rspack_loader_swc/src/lib.rs
- crates/rspack_napi/src/errors.rs
- crates/rspack_napi/src/lib.rs
- crates/rspack_napi/src/threadsafe_function.rs
- crates/rspack_plugin_html/src/asset.rs
- crates/rspack_plugin_html/src/template.rs
- crates/rspack_plugin_schemes/src/file_uri.rs
- crates/rspack_plugin_schemes/src/http_uri/mod.rs
- crates/rspack_storage/src/fs/mod.rs
Convert `Result` with message
---
This pull request focuses on improving error handling and consistency across various modules by replacing custom error conversion methods with a new trait `ToStringResultToRspackResultExt`. The changes span multiple files and touch on different parts of the codebase, including compilation, error handling, plugins, and loaders.
> refactor: convert result with message

- packages/rspack/src/loader-runner/worker.ts
- website/docs/en/config/module.mdx
- website/docs/zh/config/module.mdx
`Compiler.inputFileSystem` is supposed to be a better choice. But it requires some hassle of wrapping it.
Let's use `node:fs` for now. This is the same as `thread-loader`'s [impl](https://github.com/webpack-contrib/thread-loader/blob/b15157daec07f52c6e5c41f40aff00f277d6d81b/src/worker.js#L160).
> feat(loader-parallel): support `LoaderContext.fs` as `node:fs`

- crates/rspack_core/src/build_chunk_graph/new_code_splitter.rs
- packages/rspack-test-tools/tests/cacheCases/common/basic/rspack.config.js
Persistant cache may clear caches, so if we want to incremental rebuild, not only ensure incremental config, but also make sure we have caches
> fix: should ensure cache exist when incremental rebuild chunk graph

- crates/rspack_ids/src/deterministic_chunk_ids_plugin.rs
- crates/rspack_ids/src/id_helpers.rs
- crates/rspack_ids/src/lib.rs
- crates/rspack_ids/src/named_chunk_ids_plugin.rs
- crates/rspack_ids/src/named_module_ids_plugin.rs
- crates/rspack_ids/src/natural_chunk_ids_plugin.rs
- crates/rspack_ids/src/occurrence_chunk_ids_plugin.rs
- packages/rspack-test-tools/tests/configCases/chunk-ids/stable-chunk-ids-with-duplicate-chunks/__snapshot__/snapshot.txt
- packages/rspack-test-tools/tests/configCases/chunk-ids/stable-chunk-ids-with-duplicate-chunks/index.js
- packages/rspack-test-tools/tests/configCases/chunk-ids/stable-chunk-ids-with-duplicate-chunks/module.js
- packages/rspack-test-tools/tests/configCases/chunk-ids/stable-chunk-ids-with-duplicate-chunks/node_modules/cell/index.js
- packages/rspack-test-tools/tests/configCases/chunk-ids/stable-chunk-ids-with-duplicate-chunks/node_modules/cell/package.json
- packages/rspack-test-tools/tests/configCases/chunk-ids/stable-chunk-ids-with-duplicate-chunks/node_modules/row/index.js
- packages/rspack-test-tools/tests/configCases/chunk-ids/stable-chunk-ids-with-duplicate-chunks/node_modules/row/package.json
- packages/rspack-test-tools/tests/configCases/chunk-ids/stable-chunk-ids-with-duplicate-chunks/node_modules/table/index.js
- packages/rspack-test-tools/tests/configCases/chunk-ids/stable-chunk-ids-with-duplicate-chunks/node_modules/table/package.json
- packages/rspack-test-tools/tests/configCases/chunk-ids/stable-chunk-ids-with-duplicate-chunks/node_modules/templater/index.js
- packages/rspack-test-tools/tests/configCases/chunk-ids/stable-chunk-ids-with-duplicate-chunks/node_modules/templater/package.json
- packages/rspack-test-tools/tests/configCases/chunk-ids/stable-chunk-ids-with-duplicate-chunks/package.json
- packages/rspack-test-tools/tests/configCases/chunk-ids/stable-chunk-ids-with-duplicate-chunks/webpack.config.js
Make named chunk ids more stable, comparing with chunk ukey in not stable enough, so we compare their groups index instead
> fix: more stable named chunk ids

- crates/node_binding/binding.d.ts
- crates/node_binding/src/plugins/interceptor.rs
- crates/node_binding/src/runtime.rs
- packages/rspack-test-tools/tests/configCases/hooks/runtime-requirement-in-tree/rspack.config.js
- packages/rspack/src/taps/compilation.ts
> fix: multiple runtimeRequirementInTree js hook call

- crates/rspack_plugin_javascript/src/parser_plugin/worker_plugin.rs
- packages/rspack-test-tools/tests/normalCases/worker/specifier-in-worker-args/config.js
- packages/rspack-test-tools/tests/normalCases/worker/specifier-in-worker-args/index.js
- packages/rspack-test-tools/tests/normalCases/worker/specifier-in-worker-args/worker.js
Fix the case: 
```js
import { something } from "./anotherFile"
new Worker(..., { workerData: something }) // some import specifier used in the second argument
```
> fix: should walk for worker args

- crates/node_binding/src/lib.rs
There are not many blocking tasks in rspack now, so set this to 1 to avoid creating too many workers.
> feat(wasm): limit tokio `max_blocking_threads` to  1

- website/docs/en/blog/announcing-1-3.mdx
- website/docs/en/guide/features/lazy-compilation.mdx
- website/docs/en/guide/tech/next.mdx
- website/docs/zh/blog/announcing-1-3.mdx
- website/docs/zh/guide/features/lazy-compilation.mdx
- website/docs/zh/guide/tech/next.mdx
- Rename `@next/plugin-rspack` to `next-rspack`.
- Add "Usage with next-compose-plugins" section.
- Add `next.config.ts` example.
- Add example link.
- Format MDX files.
> docs: improve Next.js guide

- crates/rspack_core/src/dependency/cached_const_dependency.rs
- crates/rspack_core/src/dependency/const_dependency.rs
- crates/rspack_core/src/dependency/dependency_template.rs
- crates/rspack_core/src/dependency/dependency_trait.rs
- crates/rspack_core/src/dependency/runtime_requirements_dependency.rs
- crates/rspack_plugin_javascript/src/dependency/esm/esm_compatibility_dependency.rs
- crates/rspack_plugin_javascript/src/dependency/esm/external_module_dependency.rs
- crates/rspack_plugin_javascript/src/dependency/export_info_dependency.rs
- crates/rspack_plugin_javascript/src/dependency/hmr/esm_accept_dependency.rs
- crates/rspack_plugin_javascript/src/dependency/module_argument_dependency.rs
The `AsDependency` trait is never used
> refactor: remove unused `AsDependency` trait

- rust-toolchain.toml
There is a bug in rust latest nightly version: https://github.com/rust-lang/rust/issues/139110 and seems caused by https://github.com/rust-lang/rust/pull/138824
So rollback to `nightly-2025-03-26` which is just a day before that pr
> chore: rollback rust to nightly 2025-03-26

- packages/rspack/move-tinypool.js
- packages/rspack/package.json
- packages/rspack/tsconfig.json
- packages/rspack/tsup.config.ts
- pnpm-lock.yaml
Use pre-compiled `tinypool` to avoid breaking changes to node versions that are lower than 18.
`tinypool` is copied from `node_modules` and removes `engines` field in `package.json`. Tinypool does not have dependencies, so we don't need to prebundle it.
> fix(deps): `tinypool` not being able to run on older node versions

- crates/rspack_plugin_library/src/modern_module_library_plugin.rs
- packages/rspack-test-tools/tests/configCases/library/modern-module-dynamic-error/index.js
- packages/rspack-test-tools/tests/configCases/library/modern-module-dynamic-error/rspack.config.js
Fix https://github.com/web-infra-dev/rspack/issues/9861.
Skip (directly continue) the dependency if not found, leave it to throw an error in resolve stage, only externalized dep will be processed in the modifed function.
> fix(modern-module): leave non exist dependency to throw on resolve

- packages/rspack-test-tools/tests/configCases/library/modern-module-dynamic-error/errors.js
- packages/rspack-test-tools/tests/configCases/library/modern-module-dynamic-error/rspack.config.js
Use errors.js to test expected error for https://github.com/web-infra-dev/rspack/pull/9863. As #9863 is not rebased before the test mechanism is changed.
> test: use errors.js to test expected error

- .github/actions/artifact/download/action.yml
- .github/actions/artifact/upload/action.yml
- .github/actions/cache/restore/action.yml
- .github/actions/cache/save/action.yml
- .github/actions/debuger/action.yml
- .github/actions/docker/linux-build/action.yml
- .github/actions/docker/run/action.yml
- .github/actions/pnpm/setup/action.yml
- .github/actions/rustup/action.yml
- .github/actions/rustup/cargo/action.yml
- .github/workflows/reusable-build.yml
1. update cache/restore, cache/save, artifact/download, artifact/upload to support self host runner.
2. move `docker-run` and `docker-build` to docker folder.
3. linux build directly to avoid download docker image.
> ci: cache support self hosted runner

- website/_redirects
Redirect rspack.org to rspack.dev to ensure that users access the same domain name.
See: https://docs.netlify.com/routing/redirects/redirect-options/#domain-level-redirects
> docs: redirect rspack.org to rspack.dev

- crates/rspack_core/src/compiler/compilation.rs
- crates/rspack_core/src/concatenated_module.rs
- crates/rspack_core/src/dependency/dependency_template.rs
- crates/rspack_core/src/dependency/module_dependency.rs
- crates/rspack_core/src/module.rs
- crates/rspack_core/src/normal_module.rs
- crates/rspack_core/src/parser_and_generator.rs
- crates/rspack_plugin_css/src/parser_and_generator/mod.rs
- crates/rspack_plugin_javascript/src/dependency/esm/import_dependency.rs
- crates/rspack_plugin_javascript/src/dependency/esm/mod.rs
- crates/rspack_plugin_javascript/src/parser_and_generator/mod.rs
- crates/rspack_plugin_javascript/src/plugin/impl_plugin_for_js_plugin.rs
- crates/rspack_plugin_javascript/src/visitors/dependency/parser/mod.rs
Currently, for scenarios such as Rstest and Rslib, there may be a need to customize the generated code of dependencies. By dynamically injecting a `DependencyTemplate` to override the default `DependencyTemplate` implementation of the dependency, it is possible to completely reuse the parser hooks and other processes of the dependency while only intervening in the generation of the code, thus reducing development costs. This is quite useful for implementing mocks in the bundleless mode of Rstest and for handling some module interop code in rslib.
- Mount dependency templates on the compilation.
- Register the dependency templates of dependencies in various plugins.
- During code generation, obtain the dependency template corresponding to the dependency from the compilation and then render …
> refactor: add dynamic dependency template implementation

- .github/actions/docker/linux-build/action.yml
The release build will mount ~/.rustup/toolchains to docker environment, and it will make rustup install target failed because of can not create hard link between two different file system.
```
could not rename component file from '/usr/local/rustup/tmp/pwqudzloviho19iy_dir/cargo/bin/cargo' to '/usr/local/rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/cargo': Invalid cross-device link (os error 18)
```
> ci: fix rustup download target failed

- website/docs/en/guide/tech/_meta.json
- website/docs/en/guide/tech/next.mdx
- website/docs/zh/guide/tech/_meta.json
- website/docs/zh/guide/tech/next.mdx
- Add next.js guide to sidebar
- Add blog post link
> docs: add next.js guide to sidebar

- crates/rspack_tracing/src/chrome.rs
since most of rspack task is async task, async trace style is much readable than thread trace style
* async style
* thread style
> chore: use async trace style for chrome tracing

- website/docs/en/blog/_meta.json
- website/docs/en/blog/rspack-next-partner.mdx
- website/docs/en/guide/start/quick-start.mdx
- website/docs/en/guide/tech/next.mdx
- website/docs/zh/blog/_meta.json
- website/docs/zh/blog/index.mdx
- website/docs/zh/blog/rspack-next-partner.mdx
- website/docs/zh/guide/start/quick-start.mdx
- website/docs/zh/guide/tech/next.mdx
- Translate the Next.js blog to Chinese.
- Add links for SWC and Lightning CSS.
- Correct webpack spelling.
> docs: translate Next.js blog to Chinese

- .github/workflows/ecosystem-ci.yml
Fix the EcoSystem CI failure as noted [here](https://github.com/web-infra-dev/rspack/actions/runs/14358129696/job/40253930696), caused by lynx-family/lynx-stack requiring Node.js v22.
It seems reasonable to update all tests to use Node.js v22 since it is LTS now.
> ci: use node v22 in ecosystem-ci

- crates/node_binding/src/lib.rs
It doesn't make sense to use a `Mutex` in this case, `RefCell` is a lower-cost option. but this probably won't give any performance improvement, since there's no access to `GLOBAL_TRACE_STATE` outside of `register_global_trace` and `cleanup_global_trace`.
> chore: use RefCell instead of Mutex in thread_local!

- pnpm-lock.yaml
- website/components/Tag.scss
- website/components/Tag.tsx
- website/docs/en/guide/start/_meta.json
- website/docs/en/guide/start/ecosystem.mdx
- website/docs/en/guide/start/quick-start.mdx
- website/docs/zh/guide/start/_meta.json
- website/docs/zh/guide/start/ecosystem.mdx
- website/docs/zh/guide/start/quick-start.mdx
- website/package.json
- Add a standalone ecosystem page to better showcase the projects in the Rspack ecosystem.
- Add tags to more clearly distinguish project types.
- Add a brief introduction for Rstack.
Preview:
> docs: add a standalone ecosystem page

- crates/rspack_core/src/compiler/compilation.rs
- crates/rspack_core/src/options/filename.rs
- crates/rspack_plugin_runtime/src/common_js_chunk_format.rs
- crates/rspack_plugin_runtime/src/helpers.rs
- crates/rspack_plugin_runtime/src/module_chunk_format.rs
- packages/rspack-test-tools/tests/NewIncremental-watch.test.js
- packages/rspack-test-tools/tests/watchCases/hashes/runtimeChunkFullHash/0/full-hash.js
- packages/rspack-test-tools/tests/watchCases/hashes/runtimeChunkFullHash/0/index.js
- packages/rspack-test-tools/tests/watchCases/hashes/runtimeChunkFullHash/0/index2.js
- packages/rspack-test-tools/tests/watchCases/hashes/runtimeChunkFullHash/1/index.js
- packages/rspack-test-tools/tests/watchCases/hashes/runtimeChunkFullHash/rspack.config.js
- packages/rspack-test-tools/tests/watchCases/hashes/runtimeChunkFullHash/test.config.js
fix https://github.com/web-infra-dev/rspack/issues/9985
In this repro https://github.com/hikerpig/module-runtimechunk-repro, the combination of `chunkFormat: module` and `runtimeChunk: true` causes the entry chunk to import the runtime chunk via `import __webpack_require__ from "./runtime~main.857eaa3b.js";`.
This leads to a situation, when relying on full hash (such as the entry injected by the dev server), during incremental builds in the dev mode, changes of the full hash will cause changes in the content of the runtime chunk. If the filename of the runtime chunk contains `[contenthash]`, then its final filename will change. At this time, due to the above mentioned `import` statement, the content of the entry chunk will also change, and consequently, its `[contenthash]` will change. …
> fix: sometimes entry chunk hash not changes with full hash runtime modules

- crates/node_binding/binding.d.ts
- crates/node_binding/scripts/banner.d.ts
- crates/node_binding/src/module.rs
- packages/rspack/etc/core.api.md
- packages/rspack/src/Compilation.ts
- packages/rspack/src/NormalModule.ts
This is to resolve the issue where invoking `NormalModule.getCompilationHooks` throws an error when Node.js loads `@rspack/binding` multiple times.
The error occurs because `NormalModule.getCompilationHooks` relies on the `Compilation` class to verify the validity of input parameters. To address this, we now:
1. Add a symbol to the Compilation instance for validation.
2. Move the `compilationHooksMap` into the Compilation instance itself.
> fix: error when load binding multiple times

- crates/rspack_plugin_javascript/src/plugin/infer_async_modules_plugin.rs
- packages/rspack-test-tools/tests/watchCases/async-modules/dynamic-entries/0/index0.js
- packages/rspack-test-tools/tests/watchCases/async-modules/dynamic-entries/0/module.js
- packages/rspack-test-tools/tests/watchCases/async-modules/dynamic-entries/0/tla.js
- packages/rspack-test-tools/tests/watchCases/async-modules/dynamic-entries/1/index0.js
- packages/rspack-test-tools/tests/watchCases/async-modules/dynamic-entries/1/index1.js
- packages/rspack-test-tools/tests/watchCases/async-modules/dynamic-entries/rspack.config.js
- packages/rspack-test-tools/tests/watchCases/async-modules/dynamic-entries/test.config.js
In the test case, before the affected modules for infer async modules is the added entry: `index1`, this cause the wrong generated code for `index1`, to fix this, we need also add the `index1`'s outgoing modules, and there outgoing modules, to the affected modules, but this would cause very bad performance (too may modules when iterate with `get_outgoing_connections`), so we just fallback to use all modules here since the infer async modules is not slow in the whole compilation, it's too hard to write a correct and performance well incremental infer async modules
> fix(incremental): dynamic add entries with infer async modules

- crates/rspack_core/src/normal_module_factory.rs
- packages/rspack-test-tools/src/case/config.ts
- packages/rspack-test-tools/src/case/new-code-splitting.ts
- packages/rspack-test-tools/tests/configCases/resolve/worker-alias/index.js
- packages/rspack-test-tools/tests/configCases/resolve/worker-alias/node_modules/corejs/modules/esnext.map.update.js
- packages/rspack-test-tools/tests/configCases/resolve/worker-alias/node_modules/corejs/package.json
- packages/rspack-test-tools/tests/configCases/resolve/worker-alias/package.json
- packages/rspack-test-tools/tests/configCases/resolve/worker-alias/rspack.config.cjs
- packages/rspack-test-tools/tests/configCases/resolve/worker-alias/worker.js
fix https://github.com/web-infra-dev/rspack/issues/9940
The resolve options which is stored in normal module should include the part of `byDependency`.
> fix: worker alias with module

- crates/node_binding/package.json
- npm/darwin-arm64/package.json
- npm/darwin-x64/package.json
- npm/linux-x64-gnu/package.json
- npm/wasm32-wasi/package.json
- npm/win32-x64-msvc/package.json
- package.json
- packages/create-rspack/package.json
- packages/rspack-cli/package.json
- packages/rspack-test-tools/package.json
- packages/rspack-tracing/package.json
- packages/rspack/package.json
* perf: js module loaders getter by @SyMind in https://github.com/web-infra-dev/rspack/pull/9955
* feat: adapter rspack-resolver async api by @stormslowly in https://github.com/web-infra-dev/rspack/pull/9747
* feat: rspack cacheable noop feature by @jerrykingxyz in https://github.com/web-infra-dev/rspack/pull/9990
* feat: resolver restriction support regex by @SyMind in https://github.com/web-infra-dev/rspack/pull/9885
* fix: stablelize order of concated modules by @JSerFeng in https://github.com/web-infra-dev/rspack/pull/9968
* fix: jsonpChunksLoadingWithCallback code format by @1714080902120 in https://github.com/web-infra-dev/rspack/pull/9923
* fix: lightningcss loader report error by default by @SyMind in https://github.com/web-infra-dev/rspack/pull/9979
* fix: external with …
> chore: release v1.3.5

- Cargo.lock
- Cargo.toml
- crates/rspack_ast/src/ast/javascript.rs
- crates/rspack_loader_swc/src/compiler.rs
- crates/rspack_plugin_swc_js_minimizer/src/minify.rs
- Bump swc version to latest
- Only emit help_msg when swc error include `load plugin errors`.
> chore: bump swc version to 22.4.0

- crates/rspack_plugin_javascript/src/parser_plugin/compatibility_plugin.rs
- packages/rspack-test-tools/tests/configCases/plugins/compatibility-plugin/index.js
```js
const __webpack_require__ = 1;
call({ __webpack_require__ })
```
After
```js
const __webpack_require_rename__ = 1;
call({ __webpack_require__: __webpack_require_rename__ })
```
The parameter is not visited by `pattern` hook, instead, it uses `identifier` hook, so we should also rename it in `identifier` hook
> fix: should rename __webpack_require__ pat in parameters

- packages/rspack-test-tools/etc/test-tools.api.md
- packages/rspack-test-tools/src/case/cache.ts
- packages/rspack-test-tools/src/helper/hot-update/index.ts
- packages/rspack-test-tools/src/helper/hot-update/loader.ts
- packages/rspack-test-tools/src/helper/hot-update/plugin.ts
- packages/rspack-test-tools/src/helper/util/refreshModifyTime.ts
- packages/rspack-test-tools/src/processor/cache.ts
- packages/rspack-test-tools/src/runner/cache.ts
- packages/rspack-test-tools/tests/Cache.test.js
Currently, CacheCases uses a loader to switch file contents during HMR, which doesn't work when we want to test file modifications or file hash changes.
* This PR upgrades the test flow of CacheCases:
1. Copy the working test directory to a temporary directory
2. Scan dynamic files and write target content
3. Run test cases in a temporary directory
4. Write dynamic file content when rebuilding
* support a command write style to allow delete file or force_write content
``` text
export default 1
---
<delete> // delete the file
---
export default 1 // create the file
---
export default 2  // write file
---
export default 2 // skip write file (not update file modify time)
---
<force_write>export default 2 // force wirte file(will update file modifiy time)
```
> test: cacheCases update dynamic file by write

- packages/rspack/rslib.config.ts
Fix failed to resolve tinypool when using parallel loader:
The tinypool is imported with `import()` and directory import is not supported in this case. We should import the full module path.
> fix: failed to resolve tinypool when using parallel loader

- crates/node_binding/rspack.wasi.cjs
- crates/rspack_core/src/build_chunk_graph/new_code_splitter.rs
- packages/rspack-test-tools/tests/configCases/chunk-loading/issue-9840/a.js
- packages/rspack-test-tools/tests/configCases/chunk-loading/issue-9840/b.js
- packages/rspack-test-tools/tests/configCases/chunk-loading/issue-9840/rspack.config.js
- packages/rspack-test-tools/tests/configCases/chunk-loading/issue-9840/test.config.js
- packages/rspack-test-tools/tests/configCases/chunk-loading/issue-9840/test.filter.js
- packages/rspack-test-tools/tests/configCases/chunk-loading/issue-9840/worker-impl.js
- packages/rspack-test-tools/tests/configCases/chunk-loading/issue-9840/worker.js
fix #9840 
AsyncEntrypoint has unique runtime, should not merge runtime when analyze module graph.
> fix: async entry should have unique runtime

- .github/workflows/ci.yml
The latest version of cargo shear (1.1.14) depends on GLIBC 2.38, which is not available on ubuntu 22. This PR will lock the shear version.
> ci: lock cargo shear version

- crates/node_binding/binding.d.ts
- crates/node_binding/src/rsdoctor.rs
- crates/rspack_plugin_rsdoctor/src/data.rs
- crates/rspack_plugin_rsdoctor/src/module_graph.rs
- crates/rspack_plugin_rsdoctor/src/plugin.rs
- packages/rspack-test-tools/tests/configCases/rsdoctor/moduleGraph/rspack.config.js
feat: rsdoctor module object add issuerPath properry.
This pull request introduces several changes to the `rsdoctor` module in the `rspack` project, primarily focusing on adding support for tracking the issuer path of modules. The most important changes include the addition of the `issuer_path` field to the `RsdoctorModule` and `JsRsdoctorModule` structs, and the corresponding logic to populate this field.
> feat: rsdoctor module object add issuerPath property

- crates/rspack_core/src/cache/persistent/mod.rs
- crates/rspack_core/src/cache/persistent/snapshot/mod.rs
- crates/rspack_core/src/cache/persistent/snapshot/option.rs
- crates/rspack_core/src/cache/persistent/snapshot/strategy.rs
- crates/rspack_core/src/cache/persistent/storage/mod.rs
- crates/rspack_core/src/utils/iterator_consumer/future.rs
- crates/rspack_fs/src/memory_fs.rs
- crates/rspack_fs/src/native_fs.rs
- crates/rspack_fs/src/read.rs
- packages/rspack-test-tools/src/helper/hot-update/plugin.ts
- packages/rspack-test-tools/src/helper/plugins/hot-update.ts
- packages/rspack-test-tools/tests/cacheCases/common/update-file/file.js
- packages/rspack-test-tools/tests/cacheCases/common/update-file/index.js
- packages/rspack-test-tools/tests/cacheCases/common/update-file/loader.js
- packages/rspack-test-tools/tests/cacheCases/common/update-file/rspack.config.js
The persistent cache snapshot will store the compile times and use them to calculate which files were modified when hot start. However, this strategy is invalid in scenarios such as CI because the update time of all files will be refreshed.
This PR will make snapshot store both compile time and file hash, and when calculate modified files the file hash will be compared when the file modification time has been updated.
This PR will introduce some performance regression due to the addition of hash calculations, and I manually benchmarked the performance of snapshot generation in cold start.
| Name | File Count | Hash Count | Before | After |
| -- | -- | -- | -- | -- |
| Docusaurus | 4059 | 2143 | 22.32ms | 73.274ms |
| Large real project | 44905 | 8891 | 106.189ms | 365.41ms |
As can be …
> feat: persistent cache snapshot save file hash by default

- Cargo.lock
- Cargo.toml
- crates/rspack_core/src/parser_and_generator.rs
- crates/rspack_core/src/self_module.rs
- crates/rspack_hash/Cargo.toml
- crates/rspack_hash/src/lib.rs
There are currently 3 unnecessary heap allocations in hash. This PR will remove as many of them as possible.
Since `md4` output is larger than `smol_str` capacity, a heap allocation still occurs when using `md4`. We use `xxhash` by default, so no further optimization is done here.
`data-encoding` is suitable for size-sensitive scenarios, but because it shares an impl with encodings such as base64, it is not usually inlined. here we replace it with our own simple impl.
> perf(hash): avoid heap allocations in hash

- crates/rspack/src/builder/mod.rs
- crates/rspack/tests/snapshots/defaults__default_options.snap
- crates/rspack_core/src/dependency/dependency_category.rs
- packages/rspack-test-tools/tests/__snapshots__/Defaults.test.js.snap
- packages/rspack-test-tools/tests/defaultsCases/target_/electron-main.js
- packages/rspack-test-tools/tests/defaultsCases/target_/electron-preload.js
- packages/rspack-test-tools/tests/defaultsCases/target_/node.js
- packages/rspack-test-tools/tests/defaultsCases/target_/nwjs.js
- packages/rspack/src/config/defaults.ts
- tests/webpack-test/configCases/concatenate-modules/import-module/test.filter.js
fix https://github.com/web-infra-dev/rspack/issues/8447
The import module entry dependency's category is `loaderImport`, and it is missed in by depenedency of default resolve options. This make the resolve options inconsistent with other modules.
> fix: import module entry dependency resolve options

- packages/rspack-cli/src/utils/profile.ts
- packages/rspack-cli/tests/build/profile/profile.test.ts
- website/docs/en/contribute/development/profiling.md
- website/docs/en/guide/optimization/profile.mdx
- website/docs/zh/contribute/development/profiling.md
- website/docs/zh/guide/optimization/profile.mdx
- website/project-words.txt
remove RSPACK_PROFILE=JSCPU and RSPACK_PROFILE=LOGGING support
both function are covered by TRACE now see https://github.com/web-infra-dev/rspack/pull/10009
> fix(cli): remove JSCPU & LOGGING support

- crates/rspack_plugin_library/src/module_library_plugin.rs
- packages/rspack-test-tools/tests/configCases/library/module-asset-entry-inline/rspack.config.js
- packages/rspack-test-tools/tests/configCases/library/module-asset-entry-inline/test.config.js
fix: #10024 
Should not have property access for module whose exportsType is Default
> fix: should have correct interop for default exportsType

- packages/rspack/src/config/zod.ts
Fixes the following error:
Invalid configuration object. Rspack has been initialized using a configuration object that does not match the API schema.
- Unrecognized key(s) in object: 'minSizeReduction' at "optimization.splitChunks.cacheGroups.{group}"
that is caused by valid config:
```
const config = {
...
optimization: {
splitChunks: {
...
vendor: {
priority: 5,
test: /[\\/]node_modules[\\/]/,
minSize: 20000,
minSizeReduction: 50000,
reuseExistingChunk: true,
},
}
}
};
```
Both of the following checks didn't seem pertinent:
> Add minSizeReduction to SplitChunks CacheGroup

- crates/rspack_napi/src/js_values/threadsafe_one_shot_value_ref.rs
ThreadsafeOneShotRef use ThreadsafeFunction to delete ref when struct drop not in node thread.
We should unref ThreadsafeFunction before create ThreadsafeFunction, avoid it prevents event loop destroy.
> fix: ThreadsafeOneShotRef prevents event loop destroy

- packages/rspack-cli/src/cli.ts
- packages/rspack-cli/src/utils/profile.ts
- packages/rspack-cli/tests/build/profile/profile.test.ts
- packages/rspack/src/exports.ts
- packages/rspack/src/loader-runner/index.ts
- packages/rspack/src/trace/index.ts
The current RSPACK_PROFILE syntax is too complex to understand(`RSPACK_PROFILE='TRACE=filter=trace&output=./rspack.trace&layer=chrome`) cause
* it supports JSCPU | LOGGING | TRACE at same time
* it supports trace layer trace output trace filter at same time
* trace filter itself is already very complex
so this pr try to simplify the RSPACK_PROFILE logic 
* remove JSCPU | LOGGING support: since it's already removed in https://github.com/web-infra-dev/rspack/pull/10071
* separate trace output and trace layer to separate environment RSPACK_TRACE_OUPUT and RSPACK_TRACE_LAYER
* supports two filter preset like turbopack  https://github.com/vercel/next.js/blob/da31ac70afbaf4ddd620ca06e5dbd55ce2d17255/crates/napi/src/next_api/project.rs#L341
* RSPACK_PROFILE=ALL means contains all trace event
* …
> fix(cli): simplify RSPACK_PROFILE

- Cargo.lock
- crates/node_binding/Cargo.toml
- crates/node_binding/binding.d.ts
- crates/node_binding/rspack.wasi-browser.js
- crates/node_binding/rspack.wasi.cjs
- crates/node_binding/src/compilation/chunks.rs
- crates/node_binding/src/compilation/mod.rs
- crates/rspack_napi/src/js_values/weak_ref.rs
- crates/rspack_napi/src/lib.rs
- packages/rspack-test-tools/tests/configCases/chunk-graph/compilation-chunks-instance/index.js
- packages/rspack-test-tools/tests/configCases/chunk-graph/compilation-chunks-instance/rspack.config.js
- packages/rspack/etc/core.api.md
- packages/rspack/src/Chunks.ts
- packages/rspack/src/Compilation.ts
Fix #9953
compilation.chunks should always to point a unique jsobject.
> fix: compilation.chuks not corresponds to a unique jsobect

- crates/rspack_plugin_javascript/src/webpack_comment.rs
- packages/rspack-test-tools/tests/cacheCases/common/update-file/rspack.config.js
fix https://github.com/web-infra-dev/rspack/issues/7356
> fix: comma in regex value of magic comments

- Cargo.lock
- crates/rspack_plugin_lightning_css_minimizer/Cargo.toml
- crates/rspack_plugin_lightning_css_minimizer/src/lib.rs
- packages/rspack-test-tools/tests/diagnosticsCases/minimize/lightning-css-invalid/stats.err
improve lightningcss minimize warning
before
```
WARNING in ⚠ Unexpected end of input at main.css<LINE_COL>
```
after
```
WARNING in ⚠ LightningCSS minimize warning: Unexpected end of input at main.css<LINE_COL>
╭─[13:13]
11 │ 
12 │ .b {
13 │   color; blue;
·              ▲
14 │ }
15 │ 
╰────
```
> feat: improve lightningcss minimize warning

- packages/rspack/src/util/bindingVersionCheck.ts
This eliminate errors if users only install `@rspack/binding-wasm32-wasi`. Usually users are aware of they are choosing wasm binding so I think we can avoid introducing very detailed messages.
> fix(wasm): add wasm fallback in `checkVersion`

- packages/rspack-test-tools/tests/cacheCases/snapshot/managed-paths/test_lib/package.json
- packages/rspack-test-tools/tests/cacheCases/snapshot/unmanaged-paths/test_lib/package.json
- packages/rspack-test-tools/tests/configCases/resolve/pnp-enable/package.json
- packages/rspack-test-tools/tests/diagnosticsCases/config/pnp-disable/package.json
Update package.json#name to fix the Jest haste module naming collision when running the Rspack test cases:
> test: fix Jest haste module naming collision

- Cargo.lock
- crates/rspack_error/Cargo.toml
- crates/rspack_error/src/graphical.rs
- packages/rspack-test-tools/tests/__snapshots__/NewCodeSplitting-stats-output.test.js.snap
- packages/rspack-test-tools/tests/__snapshots__/StatsOutput.test.js.snap
- packages/rspack-test-tools/tests/diagnosticsCases/builtins/recoverable_syntax_error/stats.err
This PR fixes the panic when calling `format_args!` with excessively large width (> u16::MAX), which is an constraint introduced in rust PR https://github.com/rust-lang/rust/issues/99012.
This is not an ideal way for handling a minimized source code. The way of printing diagnostics of minimized source remains to be discussed.
closes https://github.com/web-infra-dev/rspack/issues/9971
> fix(diagnostic): fix excessively large width causing `format_args` panics

- Cargo.lock
- Cargo.toml
close https://github.com/web-infra-dev/rspack/issues/9967
the root cause is pnp-rs return wrong file_type when querying zip cached path.
Solved by update pnp-rs in rspack resolver.
> fix(pnp):  resolved wrong description file in yarn pnp mode

- crates/rspack_plugin_javascript/src/parser_plugin/hot_module_replacement_plugin.rs
- packages/rspack-test-tools/src/runner/hot-step.ts
- packages/rspack-test-tools/src/runner/hot.ts
- tests/webpack-test/ConfigTestCases.template.js
- tests/webpack-test/HotTestCases.template.js
- tests/webpack-test/TestCases.template.js
- tests/webpack-test/WatchTestCases.template.js
- tests/webpack-test/checkArrayExpectation.js
- tests/webpack-test/helpers/FakeDocument.js
- tests/webpack-test/hotCases/css/css-modules/index.js
- tests/webpack-test/hotCases/css/css-modules/test.filter.js
- tests/webpack-test/hotCases/css/fetch-priority/test.filter.js
- tests/webpack-test/hotCases/css/vanilla/test.filter.js
- tests/webpack-test/hotCases/define/issue-6962/test.filter.js
- tests/webpack-test/lib/css/walkCssTokens.js
fix and enable more webpack hmr tests
the remaining not passed test cases:
not bug related to hmr:
- `css/fetch-priority`: not support fetch priority for css
- `loader-import-module/css`: bug on `importModule`
- `lazy-compilation/*`: we use middleware, all tests are migrated in `rspack-test-tools`
bug related to hmr but probably nobody will encounter:
- `hashing/full-hash-syntax-error`: bug on emitOnErrors
- `runtime/root-error`: bug on emitOnErrors
> fix: use evaluate expression to extract hmr accept dependencies

- .github/workflows/reusable-build-bench.yml
- Cargo.lock
- Cargo.toml
- README.md
- crates/rspack_tracing/Cargo.toml
- crates/rspack_tracing/src/chrome.rs
- crates/rspack_tracing_chrome/Cargo.toml
- crates/rspack_tracing_chrome/LICENSE
- crates/rspack_tracing_chrome/README.md
- crates/rspack_tracing_chrome/src/lib.rs
tracing-chrome crate has some limitation which cause it's hard to add better perfetto support for rspack, even maybe we can make pr to tracing-chrome but there may more custom behavior in the future which is coupled with rspack, so I think fork the implementation is better and we'll add perfetto support in following ways:
* support merge rust & js tracing file( the current tracing merge is too hacky, use regex to merge two json file to avoid parse large json file https://github.com/web-infra-dev/rspack/pull/10072/files#diff-b8118343bf83f27b63382f2a28551be6da81ef2bcbde3d5f88ece45a3f20b4f2R85
* support separate span in same track using `id2`(current overlap span will cause perfetto UI render wrong result, related to https://github.com/thoren-d/tracing-chrome/issues/24)
I don't separate this …
> chore: fork tracing-chrome for better support for perfetto

- packages/rspack-test-tools/tests/configCases/chunk-graph/compilation-chunks-instance/rspack.config.js
- packages/rspack/src/Chunks.ts
fix: compilation chunks for each is undefined
before node 22, there is not forEach function in `SetIterator<T>`.
> fix: compilation chunks for each is undefined

- README.md
- README.zh-CN.md
- crates/node_binding/README.md
- packages/create-rspack/README.md
- packages/rspack-cli/README.md
- packages/rspack-test-tools/README.md
- packages/rspack/README.md
- scripts/build-npm.cjs
- tests/e2e/README.md
This PR updates the banner image in README files to align with other Rstack projects.
- before:
- after:
> docs: update banner image

- crates/rspack_macros/src/hook.rs
- crates/rspack_macros/src/plugin.rs
How to enable:
`define_hook!(CompilerThisCompilation: Series(compilation: &mut Compilation, params: &mut CompilationParams), tracing = true);`
`#[plugin_hook(NormalModuleFactoryBeforeResolve for IgnorePlugin, tracing = true)]`
> chore: disable hook macro tracing by default

- packages/rspack/package.json
- packages/rspack/src/loader-runner/index.ts
- packages/rspack/src/loader-runner/worker.ts
- pnpm-lock.yaml
This PR removes the `json-parse-even-better-errors` dependency to remove ~100 loc from the `dist/index.js`.
I think this package can be removed due to two reasons:
1. The "loader string option parsing error" is a rare case, and I think few users will encounter this error.
2. `json-parse-even-better-errors` does not seem to improve the readability of the error, but makes the log more complicated:
```js
import jsonParse from "json-parse-even-better-errors";
const invalidJson = "{foo:1,bar:2,baz:`}";
try {
console.log("=== JSON.parse ===");
JSON.parse(invalidJson);
} catch (e) {
console.log(e);
console.log('\n');
}
try {
console.log("=== json-parse-even-better-errors ===");
jsonParse(invalidJson);
} catch (e) {
console.log(e);
}
```
> perf(core): remove json-parse-even-better-errors dependency

- crates/rspack_core/src/normal_module.rs
- crates/rspack_loader_swc/src/lib.rs
- crates/rspack_plugin_javascript/src/parser_and_generator/mod.rs
- crates/rspack_tracing_chrome/src/lib.rs
- packages/rspack/src/loader-runner/index.ts
- packages/rspack/src/trace/index.ts
- scripts/build-npm.cjs
It's harder for trace viewer(like perfetto) to explain overlap async event with same `name` and `id` and `cat`
```json
[
{
"name": "parse",
"ph": "b",
"ts": 0,
"id": "1",
"pid": 1,
"tid": 1
},
{
"name": "parse",
"ph": "e",
"ts": 4000,
"id": "1",
"pid": 1,
"tid": 1
},
{
"name": "parse",
"ph": "b",
"ts": 2000,
"id": "1",
"pid": 1,
"tid": 1
},
{
"name": "parse",
"ph": "e",
"ts": 5000,
"id": "1",
"pid": 1,
"tid": 1
}
]
```
it can explain the json in two different ways
* first
* second
chrome trace event supports use ["id2"](https://docs.google.com/document/d/1CvAClvFfyA5R-PhYUmn5OOQtYMH4h6I0nSsKchNAySU/preview?tab=t.0#heading=h.l7g30knytzzc) to different span, so we use "id2" instead to control how perfetto show overlap, it's not only useful to specify range but also can bind span with …
> fix(core): fix async event tracing showing in perfetto

- packages/create-rspack/package.json
- packages/rspack-cli/package.json
- packages/rspack/package.json
- pnpm-lock.yaml
bump Rslib from `v0.6.6` to `v0.6.7` since `v0.6.6` is built based on a canary version of Rspack which contains a reverted PR.
see https://github.com/web-infra-dev/rspack/pull/10126
> chore(deps): bump Rslib 0.6.7

- crates/node_binding/src/plugins/js_hooks_plugin.rs
- crates/rspack_core/src/compiler/mod.rs
- crates/rspack_core/src/compiler/rebuild.rs
- crates/rspack_core/src/plugin/mod.rs
- crates/rspack_core/src/plugin/plugin_driver.rs
- crates/rspack_plugin_html/src/plugin.rs
- crates/rspack_plugin_javascript/src/plugin/impl_plugin_for_js_plugin.rs
- crates/rspack_plugin_real_content_hash/src/lib.rs
- crates/rspack_plugin_rsdoctor/src/plugin.rs
- crates/rspack_plugin_runtime/src/runtime_plugin.rs
This PR removes the hooks in plugin's `COMPILATION_HOOKS_MAP` when `clear_cache` to avoid leak memory when rebuild.
Strictly speaking this is not semantically correct, since this is not a cache, and it is also hard to track hooks usage. There should be a better management mechanism in future. but for now, this is a simple fix.
> fix: plugin compilation hooks leak

- crates/node_binding/binding.d.ts
- crates/node_binding/src/raw_options/raw_builtins/raw_circular_dependency.rs
- crates/rspack_plugin_circular_dependencies/src/lib.rs
- packages/rspack-test-tools/tests/diagnosticsCases/plugins/circular-dependency-plugin/rspack.config.js
- packages/rspack/etc/core.api.md
- packages/rspack/src/RspackError.ts
- packages/rspack/src/builtin-plugin/CircularDependencyRspackPlugin.ts
- packages/rspack/src/exports.ts
In the method https://rspack.dev/zh/plugins/rspack/circular-dependency-rspack-plugin#ondetected , the `compilation` param is `JsCompilation` not `Compilation` in rust side(see docs: https://rspack.dev/api/javascript-api/compilation), which means:
I adjust the `compilation` inject time stage, just inject the `compilation` in the JS side, you can see my code at `packages/src/builtin-plugin/CircularDependencyRspackPlugin.ts`.
So the user can get the `compilation` api at js side:
closes issue: #9877
I add the case at `packages/rspack-test-tools`
> refactor: adjust circularDependencyRspackPlugin compilation api

- crates/rspack_storage/src/pack/strategy/split/util.rs
Should flush the file writer when testing rspack_storage otherwise the files will not be found
> fix(storage): should flush writer when flushing file mtime

- crates/node_binding/binding.d.ts
- crates/node_binding/src/dependency.rs
- crates/node_binding/src/modules/concatenated_module.rs
fix https://github.com/web-infra-dev/rspack/issues/8924
- add [`Dependency._parentModule`](https://github.com/codepunkt/webpack-license-plugin/blob/main/src/WebpackModuleFileIterator.ts#L30)
- add [`ConcatenatedModule.rootModule`](https://github.com/codepunkt/webpack-license-plugin/blob/main/src/WebpackModuleFileIterator.ts#L17)
> fix: support license plugin when enable concatenated

- packages/rspack-test-tools/tests/configCases/loader-parallel/parallel-option/rspack.config.js
- packages/rspack-test-tools/tests/configCases/loader-parallel/parallel-option/unclonable.js
- packages/rspack/src/loader-runner/index.ts
Worker threads would execute loaders until it's not set to `parallel` or it's a builtin loader that should be yielded to rust.
Previously, loader runner would pass loaders with `options` into worker thread without checking if the loader enabled `parallel`. In this PR, only `options` of which loader is set to `parallel` are passed.
> fix(parallel-loader): should not pass options for which loaders are not set to `parallel`

- pnpm-lock.yaml
- website/package.json
Upgrade to Rspress@2.0.0-beta.2.
https://github.com/web-infra-dev/rspress/releases/tag/v2.0.0-beta.2
> docs(llms): bump to Rspress@2.0.0-beta.2

- crates/rspack_core/src/cache/mod.rs
- crates/rspack_core/src/cache/persistent/mod.rs
- crates/rspack_core/src/cache/persistent/snapshot/mod.rs
- crates/rspack_core/src/compiler/mod.rs
This PR will expose `is_hot_start` to make the build method check if it is in hot start state.
> feat: persistent cache snapshot expose is_hot_start

- crates/rspack_plugin_circular_dependencies/src/lib.rs
- packages/rspack-test-tools/tests/diagnosticsCases/plugins/circular-dependency-plugin/multiple-circular/a.js
- packages/rspack-test-tools/tests/diagnosticsCases/plugins/circular-dependency-plugin/multiple-circular/b.js
- packages/rspack-test-tools/tests/diagnosticsCases/plugins/circular-dependency-plugin/multiple-circular/c.js
- packages/rspack-test-tools/tests/diagnosticsCases/plugins/circular-dependency-plugin/multiple-circular/d.js
- packages/rspack-test-tools/tests/diagnosticsCases/plugins/circular-dependency-plugin/multiple-circular/e.js
- packages/rspack-test-tools/tests/diagnosticsCases/plugins/circular-dependency-plugin/rspack.config.js
- packages/rspack-test-tools/tests/diagnosticsCases/plugins/circular-dependency-plugin/stats.err
In `CircularDependencyRspackPlugin`, we should check all cycle, for example, if we have follow case:
```
// a.js
import './b.js';
// b.js
import './c.js';
// c.js
import './d.js';
import './e.js';
// d.js
import './a.js';
// e.js
import './a.js';
```
In that case, we shoud output two cycle check diagnostic messages:
```output
a.js -> b.js -> c.js -> d.js -> a.js
a.js -> b.js -> c.js -> e.js -> a.js
```
In the algorithm of `CircularDependencyRspackPlugin`'s `fn recurse_dependencies()` we just use a `visited`(`seen_set`) hashmap to filter the duplicate module id, like `c.js` will be recurse twice, so it will not be outputed twice, the output now will be:
```output
a.js -> b.js -> c.js -> d.js -> a.js
```
The behavior is not right as the user's feedback, so we need to move the `visited` …
> fix: circularDependencyRspackPlugin should check all cycle

- crates/rspack_core/src/chunk_graph/chunk_graph_chunk.rs
- crates/rspack_plugin_runtime/src/helpers.rs
- crates/rspack_plugin_runtime/src/module_chunk_format.rs
- crates/rspack_plugin_runtime/src/runtime_module/get_chunk_filename.rs
- packages/rspack-test-tools/tests/watchCases/hashes/runtimeChunkGetChunkFilename/0/dependent-hash.js
- packages/rspack-test-tools/tests/watchCases/hashes/runtimeChunkGetChunkFilename/0/index.js
- packages/rspack-test-tools/tests/watchCases/hashes/runtimeChunkGetChunkFilename/0/index2.js
- packages/rspack-test-tools/tests/watchCases/hashes/runtimeChunkGetChunkFilename/0/warnings.js
- packages/rspack-test-tools/tests/watchCases/hashes/runtimeChunkGetChunkFilename/1/index.js
- packages/rspack-test-tools/tests/watchCases/hashes/runtimeChunkGetChunkFilename/rspack.config.js
- packages/rspack-test-tools/tests/watchCases/hashes/runtimeChunkGetChunkFilename/test.config.js
- packages/rspack-test-tools/tests/watchCases/hashes/runtimeChunkHash/0/warnings.js
another case of https://github.com/web-infra-dev/rspack/pull/9986
The GetChunkFilenameRuntimeModule may include some chunks that change after rebuilding. So this runtime module should depend on their hashes. Changing of their hashes may lead to the change of runtime chunk. And then the generated code of entry which uses `chunkFormat: "module"` should also change.
In webpack, it uses a `dependentHash` flag too handle this. But I think we can just reuse `fullhash` to handle this.
> fix: should regenerate runtime chunk hash when using get chunk filename runtime module

- packages/rspack/etc/core.api.md
- packages/rspack/src/builtin-plugin/lazy-compilation/middleware.ts
- packages/rspack/src/config/types.ts
- packages/rspack/src/config/zod.ts
- tests/e2e/cases/lazy-compilation/custom-prefix/index.test.ts
- tests/e2e/cases/lazy-compilation/custom-prefix/rspack.config.js
- tests/e2e/cases/lazy-compilation/custom-prefix/src/component.js
- tests/e2e/cases/lazy-compilation/custom-prefix/src/index.js
- tests/e2e/cases/lazy-compilation/default-prefix/index.test.ts
- tests/e2e/cases/lazy-compilation/default-prefix/rspack.config.js
- tests/e2e/cases/lazy-compilation/default-prefix/src/component.js
- tests/e2e/cases/lazy-compilation/default-prefix/src/index.js
- website/docs/en/config/experiments.mdx
- website/docs/en/guide/features/lazy-compilation.mdx
- website/docs/zh/config/experiments.mdx
- website/docs/zh/guide/features/lazy-compilation.mdx
This PR adds a new option to customize the URL prefix used for lazy compilation endpoints. Currently, the lazy compilation middleware uses a hardcoded `/lazy-compilation-using-` prefix for its endpoints, without any way to customize it.
This change adds a new `prefix` option to the `LazyCompilationOptions` type, allowing users to specify a custom prefix. When this option is provided, the middleware will use the custom prefix instead of the default one. This is particularly useful for:
1. Avoiding URL routing conflicts in complex setups
2. Integrating with existing systems that have specific URL requirements
3. Keeping consistent URL patterns across different parts of an application
The implementation maintains backward compatibility by using the default prefix when the custom prefix isn't …
> feat: custom prefix for lazy compilation

- crates/rspack_loader_lightningcss/src/lib.rs
- packages/rspack-test-tools/tests/configCases/builtin-lightningcss-loader/ignore-css-modules-warning/index.js
- packages/rspack-test-tools/tests/configCases/builtin-lightningcss-loader/ignore-css-modules-warning/index.module.css
- packages/rspack-test-tools/tests/configCases/builtin-lightningcss-loader/ignore-css-modules-warning/rspack.config.js
- website/docs/en/guide/features/builtin-lightningcss-loader.mdx
- website/docs/zh/guide/features/builtin-lightningcss-loader.mdx
1. ignore parsing errors on CSS modules from lightningcss-loader. CSS modules will be handled by downstream loaders.
2. improve lightningcss-loader warning message by `LightningCSS parse warning` prefix.
3. fix the document for ignore lightningcss-loader warning message.
Fix #10162
> fix: ignore parsing errors on CSS modules from lightningcss-loader

- packages/rspack-test-tools/tests/watchCases/hashes/runtimeChunkGetChunkFilename/0/warnings.js
- packages/rspack-test-tools/tests/watchCases/hashes/runtimeChunkGetChunkFilename/1/warnings.js
- packages/rspack-test-tools/tests/watchCases/hashes/runtimeChunkHash/0/warnings.js
- packages/rspack-test-tools/tests/watchCases/hashes/runtimeChunkHash/1/warnings.js
https://github.com/web-infra-dev/rspack/pull/10145 will show warnings when incremental really affects, which not include the first cold build anymore
fix https://github.com/web-infra-dev/rspack/actions/runs/14656609253/job/41133154090
> chore(ci): refactor incremental causes ci tests failed

- crates/rspack_error/src/graphical.rs
closes https://github.com/web-infra-dev/rspack/issues/10150
truncate width into `u16::MAX` for graphical reporter.
> fix: truncate width into `u16::MAX` for graphical reporter

- crates/rspack_loader_lightningcss/src/lib.rs
- packages/rspack-test-tools/tests/configCases/builtin-lightningcss-loader/ignore-css-modules-warning/index.module.css
fix warning to parse ::v-deep syntax.
relate https://github.com/web-infra-dev/rsbuild/issues/5102
> fix: Vue CSS pseudo class warning in lightningcss

- packages/rspack-test-tools/src/case/new-incremental.ts
- packages/rspack-test-tools/src/case/watch.ts
- packages/rspack-test-tools/src/processor/basic.ts
- packages/rspack-test-tools/src/test/creator.ts
Should add `.catch` to runner tasks of concurrent test cases. To prevent the error being thrown to `unhandledRejection` which will be captured by jest and attach to currently running test cases.
> test: should not report on wrong case when error

- packages/rspack/src/stats/DefaultStatsFactoryPlugin.ts
https://github.com/web-infra-dev/rspack/pull/10121 introduced a bug that makes rspack print webpack's version number rather than rspack's version number in `rspack serve` and `rspack build` (as reported in https://github.com/web-infra-dev/rspack/issues/10189).
This PR fixes it.
> fix: print rspack version instead of webpack's (fix #10189)

- package.json
- packages/rspack-test-tools/tests/statsAPICases/build-time-executed.js
- pnpm-lock.yaml
The `webpack-cli` package seems never used and can be removed to make CI faster.
> chore(deps): remove unused webpack-cli

- .github/actions/cache/restore/action.yml
- .github/actions/rustup/action.yml
- fix cache-hit in composition action; `cache-hit` is string.
ref https://github.com/actions/cache/blob/main/src/restoreImpl.ts#L79C1-L80C1
- if you use cahce save/restore api, the key and path parameter should be the same.
- add version segement in key to, isolate old un-rebased PR
> fix: CI mulit rust cache file with the same cache key

- website/docs/en/guide/tech/css.mdx
- website/docs/zh/guide/tech/css.mdx
- Added an example of using `css-loader` to enable CSS Modules support when built-in CSS support is not enabled
- Updated the description of CSS Modules
> docs: improve CSS Modules documentation

- crates/rspack_loader_lightningcss/src/lib.rs
- crates/rspack_plugin_lightning_css_minimizer/Cargo.toml
- crates/rspack_plugin_lightning_css_minimizer/src/lib.rs
- packages/rspack-test-tools/tests/configCases/builtin-lightningcss-loader/report-warning/test.filter.js
- packages/rspack-test-tools/tests/diagnosticsCases/minimize/lightning-css-invalid/test.filter.js
temporarily disable lightningcss warning cause it contains too much positive-negative warnings
> fix(core): temporarily disable lightningcss warning

- crates/node_binding/binding.d.ts
- crates/node_binding/src/clean_options.rs
- crates/node_binding/src/raw_options/raw_output.rs
- crates/rspack/tests/snapshots/defaults__default_options.snap
- crates/rspack_core/src/compiler/mod.rs
- crates/rspack_core/src/options/clean_options.rs
- crates/rspack_core/src/utils/fs_trim.rs
- packages/rspack/etc/core.api.md
- packages/rspack/src/config/types.ts
- packages/rspack/src/config/zod.ts
- tests/webpack-test/configCases/clean/ignore-fn/test.filter.js
- tests/webpack-test/configCases/clean/ignore-fn/webpack.config.js
- tests/webpack-test/configCases/clean/ignore-rx/test.filter.js
- website/docs/en/config/output.mdx
- website/docs/zh/config/output.mdx
close https://github.com/web-infra-dev/rspack/issues/7822
> feat: support regexp and function of `output.clean`

- crates/rspack_core/src/context_module_factory.rs
- packages/rspack-test-tools/tests/configCases/context/missing-dependency/errors.js
- packages/rspack-test-tools/tests/configCases/context/missing-dependency/index.js
- packages/rspack-test-tools/tests/configCases/context/missing-dependency/rspack.config.js
fix https://github.com/web-infra-dev/rspack/issues/5536
Removed context directory should be add to missing dependencies of watcher.
> fix: missing context depenendency

- packages/rspack/prebundle.config.mjs
- packages/rspack/src/builtin-loader/swc/pluginImport.ts
- packages/rspack/src/builtin-plugin/IgnorePlugin.ts
- packages/rspack/src/builtin-plugin/RsdoctorPlugin.ts
- packages/rspack/src/builtin-plugin/SubresourceIntegrityPlugin.ts
- packages/rspack/src/builtin-plugin/html-plugin/options.ts
- packages/rspack/src/config/utils.ts
- packages/rspack/src/config/zod.ts
- packages/rspack/src/lib/DllPlugin.ts
- packages/rspack/src/lib/DllReferencePlugin.ts
In https://github.com/web-infra-dev/rspack/pull/9899, I use default import to import `zod` to make types clear like below.
But if user use named import in daily development, the types will be emitted like:
And there exists an ast-grep issue when we try to redirect the import path, see https://github.com/ast-grep/ast-grep/issues/1959
Since the named import is the recommended one, so this PR, we use named import to import zod uniformly, and modify the prebundle script to copy the dts file directly instead of using `rollup-plugin-dts` for bundling to avoid the ast-grep issue and make the types simple and clear.
> BTW, zod use namespace and `rollup-plugin-dts` has some issues for namespace support, so we just use copy when prebundle.
> fix: copy zod types instead of bundling them

- website/docs/en/config/experiments.mdx
- website/docs/zh/config/experiments.mdx
These grammars are not supported by Rspress, but in surprising coincidence, it worked.
just standardize them
https://github.com/web-infra-dev/rspress/blob/415cefcdf2772f1e6442ead732e28b6f5eb55bd0/packages/plugin-container-syntax/src/remarkPlugin.ts
> docs: fix the wrong container syntax

- crates/rspack_core/src/normal_module_factory.rs
- crates/rspack_core/src/options/resolve/clever_merge.rs
- packages/rspack-test-tools/tests/configCases/resolve/mf-by-dependency-esm/index.js
- packages/rspack-test-tools/tests/configCases/resolve/mf-by-dependency-esm/node_modules/pkg/lib/a.native.js
- packages/rspack-test-tools/tests/configCases/resolve/mf-by-dependency-esm/node_modules/pkg/lib/index.js
- packages/rspack-test-tools/tests/configCases/resolve/mf-by-dependency-esm/node_modules/pkg/lib/package.json
- packages/rspack-test-tools/tests/configCases/resolve/mf-by-dependency-esm/node_modules/pkg/package.json
- packages/rspack-test-tools/tests/configCases/resolve/mf-by-dependency-esm/warnings.js
- packages/rspack-test-tools/tests/configCases/resolve/mf-by-dependency-esm/webpack.config.js
fix https://github.com/web-infra-dev/rspack/issues/10215
which is introduced by https://github.com/web-infra-dev/rspack/pull/10021, a wrong fix about merge resolve options by dependency, the real cause is the bug on `clever_merge`
> fix: clever merge resolve options

- packages/rspack-cli/src/cli.ts
- packages/rspack/src/index.ts
- packages/rspack/src/setupEnv.ts
We tried setting WATCHPACK_WATCHER_LIMIT by default in the Rspack CLI (https://github.com/web-infra-dev/rspack/pull/5486), but I found that this did not work because watchpack was loaded earlier than the WATCHPACK_WATCHER_LIMIT was set in the Rspack CLI.
This PR fixes the issue by setting WATCHPACK_WATCHER_LIMIT earlier in Rspack core.
Also submitted a PR to the watchpack repo: https://github.com/webpack/watchpack/pull/249, if that gets merged we can remove this.
> fix: set watchpack limit before loading watchpack

- Cargo.lock
- Cargo.toml
- crates/rspack_tracing/src/chrome.rs
https://github.com/swc-project/swc/pull/10411 change default swc trace level to debug level, so it's safe to enable swc tracing
> chore: upgrade swc to v22.5.3 and enable swc tracing

- packages/rspack/src/config/types.ts
- website/docs/en/api/runtime-api/module-methods.mdx
- website/docs/en/config/module.mdx
- website/docs/zh/api/runtime-api/module-methods.mdx
- website/docs/zh/config/module.mdx
- Added a new section detailing built-in MIME type rules supported by Rspack, including examples of default MIME type handling for `application/json`, `text/javascript`, etc.
- Provided examples for extending MIME type matching rules using `Rule.mimetype`.
> docs: enhance Data URI module and MIME type rules

- packages/rspack-test-tools/package.json
- packages/rspack-test-tools/tests/configCases/builtin-swc-loader/inline-pitching/pitching-loader.js
- packages/rspack-test-tools/tests/configCases/loader/rspack-issue-4838/node_modules/loader1.js
- pnpm-lock.yaml
- tests/webpack-test/cases/loaders/issue-10725/loader.js
- tests/webpack-test/cases/wasm/two-files-loader/wrapper-loader.js
- tests/webpack-test/cases/wasm/two-files-loader/wrapper-loader2.js
- tests/webpack-test/configCases/loaders/issue-3320/node_modules/any-loader.js
- tests/webpack-test/package.json
`stringifyRequest` and `getRemainingRequest` has been removed in `loader-utils` v3, we can just remove `loader-utils` v2 and use Rspack built-in methods instead.
- close https://github.com/web-infra-dev/rspack/pull/9654
- https://github.com/webpack/loader-utils/releases/tag/v3.0.0
> chore(deps): remove loader-utils v2

- crates/node_binding/binding.d.ts
- crates/node_binding/src/stats.rs
- crates/rspack_core/src/stats/mod.rs
- crates/rspack_core/src/stats/struct.rs
- packages/rspack-test-tools/tests/errorCases/warning-test-push.js
- packages/rspack-test-tools/tests/errorCases/warning-test-splice-2.js
- packages/rspack/src/Compilation.ts
- packages/rspack/src/Stats.ts
- packages/rspack/src/stats/DefaultStatsFactoryPlugin.ts
- packages/rspack/src/stats/statsFactoryUtils.ts
- tests/webpack-test/statsCases/ignore-warnings/test.filter.js
fix the wired behavior of  ignore warnings plugin in https://github.com/web-infra-dev/rspack/issues/10266
- not to process warning multiple times
- should create a error instance instead of plain object
> fix: process warnings multiple times

- crates/node_binding/binding.d.ts
- crates/node_binding/src/html.rs
- crates/node_binding/src/raw_options/raw_builtins/raw_html.rs
- crates/rspack_plugin_html/src/config.rs
- crates/rspack_plugin_html/src/drive.rs
- crates/rspack_plugin_html/src/plugin.rs
- packages/rspack-test-tools/tests/configCases/builtins/html-custom-options/index.js
- packages/rspack-test-tools/tests/configCases/builtins/html-custom-options/rspack.config.js
- packages/rspack-test-tools/tests/configCases/builtins/html-multiple-options/index.js
- packages/rspack-test-tools/tests/configCases/builtins/html-multiple-options/rspack.config.js
- packages/rspack/etc/core.api.md
- packages/rspack/src/builtin-plugin/html-plugin/hooks.ts
- packages/rspack/src/builtin-plugin/html-plugin/options.ts
- packages/rspack/src/builtin-plugin/html-plugin/plugin.ts
- packages/rspack/src/builtin-plugin/html-plugin/taps.ts
Using `compilationId` to obtain plugin options will lead to overriding when using multiple plugin instances.
- add uid to plugin options to make sure the javascript side can obtain the correct one when calling hooks
- allow passing extra plugin options. The csp plugin depends on this feature.
> fix(html): not to override plugin options when using multiple instances

- crates/rspack_tracing/src/chrome.rs
- crates/rspack_tracing/src/lib.rs
- crates/rspack_tracing/src/stdout.rs
- crates/rspack_tracing_chrome/src/lib.rs
- packages/rspack/src/Compiler.ts
Debugging wasm is very painful. So I hope this pr could help us find where the wasm crushes or get stuck. There are two things to do:
This pr can be holding on until there is a good solution.
> feat(wasm): support `tracing-chrome` in wasm

- packages/rspack/src/config/adapter.ts
When building a loader I noticed that `PitchLoaderDefinitionFunction` is not exported from `@rspack/core` so I updated the code to fix that. I see some JSDoc comments reference that type so this is technically a fix for those. Example:
https://github.com/web-infra-dev/rspack/blob/87ff2360a85d17d754868c112f7c77d7ec85e2a7/tests/webpack-test/configCases/css/css-auto/loader.js#L1-L2
Thanks!
> fix(types): export PitchLoaderDefinitionFunction type

- crates/node_binding/binding.d.ts
- crates/node_binding/src/chunk_graph.rs
- packages/rspack/src/ChunkGraph.ts
While Webpack provides `hasChunkEntryDependentChunks` method in its `ChunkGraph`, this functionality is missing in Rspack's `JsChunkGraph`. Although we have already implemented the underlying logic in `chunk_graph_chunk.rs`, it hasn't been exposed to the JavaScript interface.
This PR aims to expose this method to support the implementation of `StartupChunkDependenciesRuntimeModule`, which is crucial for fixing chunk splitting issues in Rspeedy.
Related links:
- https://github.com/web-infra-dev/rspack/blob/main/crates/node_binding/binding.d.ts#L179
- https://github.com/web-infra-dev/rspack/blob/main/crates/rspack_core/src/chunk_graph/chunk_graph_chunk.rs#L682
- https://github.com/webpack/webpack/blob/main/lib/ChunkGraph.js#L1243
- …
> feat: expose hasChunkEntryDependentChunks on ChunkGraph

- packages/rspack/src/builtin-plugin/SubresourceIntegrityPlugin.ts
allow the SRI plugin to be used without passing options, use `{}` by default
> fix: allow the SRI plugin to be used without passing options

- crates/rspack_plugin_javascript/src/parser_plugin/node_stuff_plugin.rs
- tests/webpack-test/configCases/parsing/issue-9042/index.js
- tests/webpack-test/configCases/parsing/issue-9042/test.filter.js
Should not evaluate `typeof __dirname` when `node.__dirname` is set to false
> fix: not evaluate `typeof __dirname` when set to false

- Cargo.lock
- Cargo.toml
- crates/rspack_core/Cargo.toml
- crates/rspack_error/Cargo.toml
- crates/rspack_javascript_compiler/Cargo.toml
- crates/rspack_plugin_swc_js_minimizer/Cargo.toml
- Updated SWC version from 21.0.0 to 22.0.0 in the root Cargo.toml. More detail about SWC changelog see:  [SWC CHANGELOG_CORE](https://github.com/swc-project/swc/blob/main/CHANGELOG-CORE.md#swc_corev2310---2025-05-06)
- Removed swc_parallel from multiple crates. We do not need to use swc_parallel to enable parallel feature. SWC export parallel feature in `swc_core` using [`parallel_rayon` feature](https://github.com/swc-project/swc/blob/main/crates/swc_core/Cargo.toml#L234-L235). So we remove swc_parallel crates.
> chore: bump SWC to v23.2.0 and remove swc_parallel

- crates/rspack_javascript_compiler/src/compiler/mod.rs
- crates/rspack_javascript_compiler/src/compiler/stringify.rs
- crates/rspack_javascript_compiler/src/compiler/transform.rs
- crates/rspack_loader_swc/src/lib.rs
The Swc plugin emit warn diagnostics will ignore by swc before, according to this PR https://github.com/swc-project/swc/pull/10027, swc will return a diagnostics. So we can emit diagnostics to loaderContext.
> feat(swc): enhance TransformOutput with diagnostics

- packages/create-rspack/template-react-js/rspack.config.mjs
- packages/create-rspack/template-react-ts/rspack.config.ts
- packages/create-rspack/template-vanilla-js/rspack.config.mjs
- packages/create-rspack/template-vanilla-ts/rspack.config.ts
- packages/create-rspack/template-vue-js/rspack.config.mjs
- packages/create-rspack/template-vue-ts/rspack.config.ts
Summary: The current browserslist default has two problems
1. It only covers [31% of users](https://browsersl.ist/#q=chrome+%3E%3D+87%2C+edge+%3E%3D+88%2C+firefox+%3E%3D+78%2C+safari+%3E%3D+14)
2. The versions are hardcoded, so needs to be manually updated
This commit changes the default browserslist to dynamically update as browser usage changes, and moves coverage from 31% to [91%](https://browsersl.ist/#q=last+2+versions%2C+Firefox+ESR%2C+%3E+0.2%25%2C+not+dead)
> feat(create-rspack): better default browserslist target

- packages/rspack-cli/src/utils/profile.ts
- packages/rspack-cli/tests/build/profile/profile.test.ts
- packages/rspack-cli/tests/utils/test-utils.ts
1. Remove `entries > 0` check, because `resolveLayer` returns a non-empty string rather than an object.
```diff
- const entries = Object.entries(resolveLayer(filterValue));
- if (entries.length <= 0) return;
```
2. Remove duplicated `mkdir`, it has the same function as `await ensureFileDir(traceOutput);`.
```diff
- await fs.promises.mkdir(defaultOutputDirname);
```
> fix: simplify trace implementation by removing unused code

- packages/create-rspack/template-react-js/package.json
- packages/create-rspack/template-react-js/rspack.config.mjs
- packages/create-rspack/template-react-ts/package.json
- packages/create-rspack/template-react-ts/rspack.config.ts
- packages/create-rspack/template-vue-js/rspack.config.mjs
- packages/create-rspack/template-vue-ts/rspack.config.ts
- packages/rspack-test-tools/package.json
- pnpm-lock.yaml
- tests/bench/package.json
- tests/e2e/package.json
Summary:
On my machine running Node v23.11.0, running this example fails with two errors:
1. `__dirname` is undefined
2. `RefreshPlugin` is an object instead of a class
This commit fixes both of these errors.
Test Plan:
1. use Node v23.11.0
2. run `pnpm create rspack@latest`
3. select react-typescript config
4. run `pnpm run dev`
Before this commit: it doesn't work
After this commit: it works
> fix(template-react-ts): work with newer Node

- crates/rspack_core/src/normal_module.rs
- crates/rspack_core/src/normal_module_factory.rs
- crates/rspack_loader_runner/src/content.rs
- crates/rspack_loader_runner/src/runner.rs
- crates/rspack_plugin_schemes/src/http_uri/http_cache.rs
- crates/rspack_plugin_schemes/src/http_uri/mod.rs
- packages/rspack/src/builtin-plugin/HttpUriPlugin.ts
- tests/webpack-examples/build-http/webpack.config.js
support build http-import with relative import 
* support context in resource_data to handle relative import in http scheme
* change fetch from 'recirect': 'manual' to align with http.get's behavior( fetch will auto redirect by default which will cause never return 30x for redirect request)
* enable example/build-http case(which is ignored before)
> fix(core): fix relative http import failed

- crates/rspack_tracing/src/chrome.rs
- crates/rspack_tracing_chrome/src/lib.rs
Related: https://github.com/web-infra-dev/rspack/pull/10246
Sorry, I made a mistake in https://github.com/web-infra-dev/rspack/pull/10246/commits/464b1814350b553bfd12391d489cc2a78c3a91ce, which passes the fd across threads.
> fix(wasm): avoid passing fd across threads

- website/docs/en/config/experiments.mdx
- website/docs/en/guide/optimization/tree-shaking.mdx
- website/docs/zh/config/experiments.mdx
- website/docs/zh/guide/optimization/tree-shaking.mdx
- Expanded the tree-shaking guide with new sections, including "What is tree shaking," "Prerequisites," and "Pure annotation.
- Fixed the incorrect casing of the `:::Tip` directive to `:::tip`:
> docs: add tree shaking prerequisites and pure annotation

- packages/rspack/src/loader-runner/utils.ts
Reason: 
1. Wasm memory is a large `SharedArrayBuffer`
2. `TextDecoder` in browser doesn't allow to decode data in `SharedArrayBuffer`
```js
sab = new SharedArrayBuffer(8);
buf = new Uint8Array(sab);
new TextDecoder().decode(buf); // Uncaught TypeError: Failed to execute 'decode' on 'TextDecoder': The provided ArrayBufferView value must not be shared.
```
3. Stackblitz wraps the `TextDecoder` in browser as its Node.js implementation
> fix(wasm): copy data to `ArrayBuffer` when decoding `SharedArrayBuffer`

- Cargo.lock
- crates/rspack/Cargo.toml
- crates/rspack/src/builder/browserslist_target.rs
- crates/rspack/src/builder/mod.rs
- crates/rspack/src/builder/snapshots/rspack__builder__browserslist_target__tests__browserslist_targets_snapshots.snap
- crates/rspack/src/builder/target.rs
- crates/rspack/tests/snapshots/defaults__default_options.snap
Supports using `browserslist` as the target.
`browserslist_rs` did not export `load_config`, this causes a difference between webpack and rspack. In webpack, if the bundler is not able to find a config, then it will fallback to target `web`. In rspack, it fallbacks to the default browserslist query instead.
Tests are being reviewed by my eyes to align with webpack's `target-browserslist` unit tests. Nevertheless, there could be some cases that I'm not aware of. Please file an issue if you find one.
Snapshot of `crates/rspack/tests/snapshots/defaults__default_options.snap` has been changed due to the previous reason.
> feat(compiler-builder): support `browserslist` as the target

- crates/node_binding/binding.d.ts
- crates/node_binding/src/compilation/mod.rs
- examples/basic/rspack.config.cjs
- packages/rspack/src/Compilation.ts
- packages/rspack/src/RspackError.ts
- packages/rspack/src/Stats.ts
- packages/rspack/src/stats/DefaultStatsFactoryPlugin.ts
calling filename function in sync js api will definitely cause deadlock so it's never working before, remove filename fn support to avoid deadlock risk for users. more background in https://github.com/web-infra-dev/rspack/discussions/3642
> fix(core): remove filename fn in sync js api

- crates/node_binding/binding.d.ts
- crates/node_binding/src/plugins/js_loader/context.rs
- crates/node_binding/src/plugins/js_loader/scheduler.rs
- packages/rspack/src/loader-runner/index.ts
Skip `UTF-8` validation on the Rust side in normal module build if the last loader returned a string. Also removes source map `UTF-8` validation as it's always `UTF-8` encoded.
> perf: skip UTF-8 validation if JS loader returned a string

- website/docs/en/config/experiments.mdx
- website/docs/en/config/externals.mdx
- website/docs/zh/config/experiments.mdx
- website/docs/zh/config/externals.mdx
I noticed that the note title is displayed incorrectly and the file name is not attached to the code block in the config documentation. I have fixed it for both languages.
> docs: fix render of note title and file name

- crates/rspack_plugin_javascript/src/parser_plugin/amd/amd_define_dependency_parser_plugin.rs
- crates/rspack_plugin_javascript/src/parser_plugin/amd/amd_require_dependencies_block_parser_plugin.rs
- tests/webpack-test/configCases/parsing/issue-8293/test.filter.js
Fix AMD parser plugin replaced define plugin values mutiple times
> fix: AMD parser plugin replaced define plugin values mutiple times

- crates/node_binding/binding.d.ts
- crates/node_binding/src/raw_options/raw_builtins/mod.rs
- crates/node_binding/src/raw_options/raw_devtool.rs
- packages/rspack/etc/core.api.md
- packages/rspack/src/builtin-plugin/EvalSourceMapDevToolPlugin.ts
- packages/rspack/src/builtin-plugin/SourceMapDevToolPlugin.ts
The EvalSourceMapDevToolPlugin on the Rust side supports all configuration options, but the JS side previously passed only a subset of these settings to Rust. Now, it will forward all configuration options.
> feat: support full options for EvalSourceMapDevToolPlugin

- crates/rspack_plugin_javascript/src/parser_plugin/inner_graph/plugin.rs
- crates/rspack_plugin_javascript/src/parser_plugin/inner_graph/state.rs
- crates/rspack_plugin_javascript/src/parser_plugin/javascript_meta_info_plugin.rs
- tests/webpack-test/configCases/inner-graph/blockScopes/test.filter.js
Fix inner graph block scope variables analysis
- Use TopLevelSymbol as inner graph map keys which align with [webpack](https://github.com/webpack/webpack/blob/main/lib/optimize/InnerGraph.js#L342-L349)
> fix: inner graph block scopes

- Cargo.lock
- crates/rspack_plugin_extract_css/Cargo.toml
- crates/rspack_plugin_extract_css/src/plugin.rs
When identical modules exist across different chunks:
* Their content hashes are equal .
* However, due to different module ordering in the render manifest, the final emitted content might differ, causing conflicts.
> fix: the modules order cross render manifest and content hash should be equal

- packages/rspack/src/builtin-plugin/HttpUriPlugin.ts
fetch is not supported in node 16, so replace it with node:http and node:https
> fix(core): make build-http compatible with node16

- crates/rspack_plugin_circular_dependencies/src/lib.rs
- packages/rspack-test-tools/tests/diagnosticsCases/plugins/circular-dependency-plugin/loader.js
- packages/rspack-test-tools/tests/diagnosticsCases/plugins/circular-dependency-plugin/rspack.config.js
- packages/rspack-test-tools/tests/diagnosticsCases/plugins/circular-dependency-plugin/stats.err
Use `module.readable_identifier` instead of plain `ModuleIdentifier`.
fix: #10378
> fix: use name instead of identifier in CircularDependencyRspackPlugin

- crates/rspack_plugin_javascript/src/dependency/esm/import_dependency.rs
- crates/rspack_plugin_javascript/src/parser_plugin/import_parser_plugin.rs
- packages/rspack-test-tools/tests/diagnosticsCases/factorize/dynamic-import-non-exist-module/stats.err
- packages/rspack/src/config/defaults.ts
- tests/webpack-test/ConfigTestCases.template.js
- tests/webpack-test/cases/runtime/missing-module-exception-dynamic-import/test.filter.js
- tests/webpack-test/configCases/asset-modules/entry-with-runtimeChunk/test.filter.js
- tests/webpack-test/configCases/library/issue-18951/test.filter.js
- tests/webpack-test/configCases/parsing/bom/test.filter.js
- tests/webpack-test/configCases/parsing/url-ignore/test.filter.js
- tests/webpack-test/configCases/target/amd-container-named/index.js
- tests/webpack-test/configCases/target/amd-container-named/test.filter.js
- tests/webpack-test/configCases/target/amd-container-unnamed/index.js
- tests/webpack-test/configCases/target/amd-container-unnamed/test.filter.js
- tests/webpack-test/configCases/target/amd-container-unnamed/webpack.config.js
- tests/webpack-test/configCases/target/amd-named/index.js
- tests/webpack-test/configCases/target/amd-named/test.filter.js
- tests/webpack-test/configCases/target/amd-unnamed/index.js
- tests/webpack-test/configCases/target/amd-unnamed/test.filter.js
- tests/webpack-test/configCases/target/amd-unnamed/webpack.config.js
- tests/webpack-test/configCases/target/umd-auxiliary-comments-object/index.js
- tests/webpack-test/configCases/target/umd-auxiliary-comments-object/test.filter.js
- tests/webpack-test/configCases/target/umd-auxiliary-comments-string/index.js
- tests/webpack-test/configCases/target/umd-auxiliary-comments-string/test.filter.js
- missing dynamic imported modules in try-catch should emit warnings instead of errors
- `universal` wasmLoading type leads to panic, so just return false
- enable more webpack test cases
> fix: emit warning when optional dynamic import missing

- crates/rspack_plugin_runtime/src/common_js_chunk_format.rs
- crates/rspack_plugin_runtime/src/module_chunk_format.rs
- packages/rspack-test-tools/src/test/creator.ts
- tests/webpack-test/ConfigTestCases.template.js
- tests/webpack-test/configCases/asset-modules/build-http/test.filter.js
- tests/webpack-test/configCases/asset-modules/only-entry/test.filter.js
- tests/webpack-test/configCases/cache-filesystem/multicompiler-mode-cache-3/test.filter.js
- tests/webpack-test/configCases/cache-filesystem/multicompiler-mode-cache-4/test.filter.js
- tests/webpack-test/configCases/chunk-index/issue-18008/test.filter.js
- tests/webpack-test/configCases/clean/lib-manifest-plugin/test.filter.js
- tests/webpack-test/configCases/runtime/dynamic-nested-with-deep-entries-commonjs/test.filter.js
- tests/webpack-test/configCases/runtime/dynamic-nested-with-deep-entries-esm/test.filter.js
- tests/webpack-test/configCases/runtime/dynamic-with-deep-entries-commonjs/test.filter.js
- tests/webpack-test/configCases/runtime/dynamic-with-deep-entries-esm/test.filter.js
- tests/webpack-test/configCases/runtime/single-with-deep-entries-commonjs/test.filter.js
- tests/webpack-test/configCases/runtime/single-with-deep-entries-esm/test.filter.js
- tests/webpack-test/configCases/target/universal/index.js
- tests/webpack-test/configCases/target/universal/test.filter.js
- tests/webpack-test/configCases/types/filesystems/test.filter.js
- tests/webpack-test/hotCases/css/fetch-priority/test.filter.js
- tests/webpack-test/package.json
- tests/webpack-test/watchCases/cache/loader-import-module-progress/test.filter.js
- tests/webpack-test/watchCases/cache/loader-load-module-progress/test.filter.js
- tests/webpack-test/watchCases/cache/max-generation/test.filter.js
- fix wrong runtime path when entry starts with `/`. for example, when entry is `/entry`, the runtime is `runtime.js`, the generated code should be `./runtime`, but get `../runtime` in rspack.
- enable some webpack test cases that can pass
> fix: chunk format runtime with entry starts with slash

- packages/rspack-test-tools/tests/errorCases/error-test-push.js
- packages/rspack-test-tools/tests/errorCases/error-test-set.js
- packages/rspack-test-tools/tests/errorCases/error-test-shift.js
- packages/rspack-test-tools/tests/errorCases/error-test-splice-1.js
- packages/rspack-test-tools/tests/errorCases/error-test-splice-2.js
- packages/rspack-test-tools/tests/errorCases/warning-test-push.js
- packages/rspack-test-tools/tests/errorCases/warning-test-set.js
- packages/rspack-test-tools/tests/errorCases/warning-test-shift.js
- packages/rspack-test-tools/tests/errorCases/warning-test-splice-1.js
- packages/rspack-test-tools/tests/errorCases/warning-test-splice-2.js
- packages/rspack/src/Compiler.ts
- packages/rspack/src/trace/index.ts
- packages/rspack/src/trace/traceHookPlugin.ts
needs more tracing to debug javascript plugin performance problem like https://github.com/web-infra-dev/rspack/issues/10372#issuecomment-2883992566 (and sometime the profile is not enough)
* after
Unfortunately the trace event is very limited to generated good perfetto UI and I can't group same hook in same track due to https://github.com/google/perfetto/issues/1548#issuecomment-2886020935,
so we may need to use perfetto native protocol in the future
> feat(core): add tracing for javascript plugin

- crates/rspack_plugin_javascript/src/parser_plugin/esm_import_dependency_parser_plugin.rs
- crates/rspack_plugin_javascript/src/utils/eval/eval_lit_expr.rs
- crates/rspack_plugin_javascript/src/visitors/dependency/parser/mod.rs
- crates/rspack_plugin_javascript/src/visitors/dependency/util.rs
- packages/rspack-test-tools/tests/treeShakingCases/cyclic-reference-export-all/__snapshots__/treeshaking.snap.txt
- tests/webpack-test/cases/errors/case-sensitive/test.filter.js
- tests/webpack-test/cases/errors/import-module-cycle-multiple/test.filter.js
- tests/webpack-test/cases/errors/import-module-cycle/test.filter.js
- tests/webpack-test/cases/parsing/harmony-destructuring-assignment/test.filter.js
pass `tests/webpack-test/cases/parsing/harmony-destructuring-assignment`, fix destucturing properties while getting referenced exports, and then impove the effect of tree shaking.
Also remove old ` parser.properties_in_destructuring` which can be full replaced by `parser.destructuring_assignment_properties_for()` which is aligned with webpack
> fix: missing destucturing properties while getting referenced exports

- Cargo.lock
- Cargo.toml
- crates/node_binding/Cargo.toml
- crates/node_binding/src/raw_options/raw_builtins/mod.rs
- crates/rspack_plugin_css/Cargo.toml
- crates/rspack_plugin_css/src/plugin/drive.rs
- crates/rspack_plugin_css/src/plugin/impl_plugin_for_css_plugin.rs
- crates/rspack_plugin_css/src/plugin/mod.rs
- crates/rspack_plugin_javascript/src/plugin/mod.rs
- crates/rspack_plugin_module_info_header/Cargo.toml
- crates/rspack_plugin_module_info_header/LICENSE
- crates/rspack_plugin_module_info_header/src/lib.rs
- packages/rspack-test-tools/tests/configCases/build-http/css/__snapshot__/bundle0.css.txt
- packages/rspack-test-tools/tests/configCases/css/export-selector/__snapshot__/imported_js.bundle0.css.txt
- tests/webpack-test/__snapshots__/ConfigTestCases.basictest.js.snap
- tests/webpack-test/configCases/chunk-index/recalc-index/test.filter.js
- tests/webpack-test/configCases/container/reference-hoisting/test.filter.js
- tests/webpack-test/configCases/container/track-initial-chunks/test.filter.js
- tests/webpack-test/configCases/contenthash/css-generator-options/test.config.js
- tests/webpack-test/configCases/contenthash/css-generator-options/test.filter.js
- tests/webpack-test/configCases/contenthash/css-generator-options/webpack.config.js
- tests/webpack-test/configCases/contenthash/module-ids-size/test.filter.js
- tests/webpack-test/configCases/css/pathinfo/test.config.js
- tests/webpack-test/configCases/css/pathinfo/test.filter.js
fix the missing of module header info in css modules and remove the old debug region infos. 
And also refactor the render methods of CssPlugin to async functions.
> fix: missing module header info of css modules

- website/docs/en/api/javascript-api/compilation.mdx
- website/docs/en/api/javascript-api/compiler.mdx
- website/docs/en/api/plugin-api/compilation-hooks.mdx
- website/docs/en/api/plugin-api/compiler-hooks.mdx
- website/docs/en/api/plugin-api/index.mdx
- website/docs/zh/api/javascript-api/compilation.mdx
- website/docs/zh/api/javascript-api/compiler.mdx
- website/docs/zh/api/plugin-api/compilation-hooks.mdx
- website/docs/zh/api/plugin-api/compiler-hooks.mdx
- website/docs/zh/api/plugin-api/index.mdx
This PR adds more detailed introductions of core objects like `Compiler`, `Compilation` and their hooks, which can help plugin developers better distinguish the core concepts in Rspack.
> docs: introducing Compilation and Compiler objects

- crates/node_binding/binding.d.ts
- crates/node_binding/src/raw_options/raw_builtins/raw_copy.rs
- crates/rspack_plugin_copy/src/lib.rs
- packages/rspack-test-tools/tests/configCases/plugins/copy-plugin-transform/rspack.config.js
- website/docs/en/plugins/rspack/copy-rspack-plugin.mdx
- website/docs/zh/plugins/rspack/copy-rspack-plugin.mdx
https://webpack.js.org/plugins/copy-webpack-plugin/#transform is actually out of date.
From https://github.com/webpack-contrib/copy-webpack-plugin/blob/0cae504f3044eef77a62b338cdf0c092675748fe/types/index.d.ts#L123 we can see that `input` parameter should be `Buffer`.
> fix: CopyRspackPlugin's transformer function should handle Buffer input

- crates/rspack_javascript_compiler/src/compiler/minify.rs
- packages/rspack-test-tools/tests/configCases/plugins/minify-parser/importAttributes.mjs
- packages/rspack-test-tools/tests/configCases/plugins/minify-parser/index.js
- packages/rspack-test-tools/tests/configCases/plugins/minify-parser/rspack.config.js
- packages/rspack-test-tools/tests/configCases/plugins/minify-parser/test.config.js
Fix https://github.com/web-infra-dev/rslib/issues/999.
Allow parsing import attributes syntax, as it might be handled directly by minimizer which is commonly used in library building.
> fix(minify): parser allow import attributes syntax

- crates/node_binding/binding.d.ts
- crates/node_binding/rspack.wasi-browser.js
- crates/node_binding/rspack.wasi.cjs
- crates/node_binding/src/compilation/mod.rs
- crates/rspack_core/src/compiler/compilation.rs
- packages/rspack-test-tools/tests/configCases/compilation/errors/loader.js
- packages/rspack-test-tools/tests/configCases/compilation/errors/rspack.config.js
- packages/rspack/src/Compilation.ts
Fix incorrect diagnostic removal when setting `compilation.errors = []`
Current Issue:
- When `compilation.errors = []` is set, the `spliceDiagnostic()` function removes all diagnostics without checking their level
Since warnings and errors are stored in the same array (differentiated only by level), this can cause incorrect diagnostic indexing (e.g., removing first item which might be a warning when we meant to remove errors)
> fix: set compilation errors result is wrong

- crates/node_binding/binding.d.ts
- crates/node_binding/src/swc.rs
- packages/rspack/etc/core.api.md
**Enhance**: add diagnostics field to TransformOutput for external plugin can emit warning in rust side.
Relative PR: https://github.com/web-infra-dev/rspack/pull/10312
> feat(swc_compiler_api): add diagnostics field to TransformOutput

- crates/rspack_tracing_chrome/src/lib.rs
- packages/rspack/src/trace/index.ts
sometimes the rust side json file is too big too read in js side, so avoid reading it in js side
```js
Error: Cannot create a string longer than 0x1fffffe8 characters
at Object.readFileSync (node:fs:448:20)
at JavaScriptTracer.dumpJavaScriptTrace
```
> refactor: avoid read rust side json in js side

- crates/node_binding/src/swc.rs
- packages/rspack-test-tools/tests/compilerCases/swc-api.js
swc wasm runtime need runnning in tokio runtime, otherwise it will panic: `Message:  there is no reactor running, must be called from the context of a Tokio 1.x runtime`
`napi-rs` will add tokio runtime auto in async fn.
So we using async fn directly, using the tokio runtime provided by `napi-rs`
fix: https://github.com/web-infra-dev/rspack/issues/10305
> fix: swc compiler api using wasm plugin without tokio runtime panic.

- crates/rspack_plugin_runtime/src/import_scripts_chunk_loading.rs
- crates/rspack_plugin_runtime/src/runtime_module/import_scripts_chunk_loading.rs
- crates/rspack_plugin_runtime/src/runtime_module/runtime/import_scripts_chunk_loading.ejs
- tests/webpack-test/configCases/runtime/target-webworker/test.filter.js
fix missing import scripts runtime when target is webworker
> fix: missing import scripts runtime when target is webworker

- crates/node_binding/binding.d.ts
- crates/node_binding/src/raw_options/raw_builtins/raw_copy.rs
- packages/rspack/etc/core.api.md
- packages/rspack/src/builtin-plugin/CopyRspackPlugin.ts
- website/docs/en/plugins/rspack/copy-rspack-plugin.mdx
- website/docs/zh/plugins/rspack/copy-rspack-plugin.mdx
- Add documentation for the `info` option of CopyRspackPlugin to demonstrate how to skip the code minification.
- Add JSDoc for all options of CopyRspackPlugin to improve DX.
Ref: https://github.com/webpack-contrib/copy-webpack-plugin/blob/0cae504f3044eef77a62b338cdf0c092675748fe/README.md#info
> docs: add info option and JSDoc for copy plugin

- package.json
Transitive preinstall/postinstall scripts keep showing up in supply-chain attacks. Running them automatically is no longer safe.
ref: https://github.com/orgs/pnpm/discussions/8945
> chore(infra): add `onlyBuiltDependencies`

- packages/rspack/src/util/bindingVersionCheck.ts
Rspack requires Node.js >= 16 and we can remove Node 10 compatibility code.
Ref: https://nodejs.org/api/process.html#processreportgetreporterr
> fix(core): remove Node 10 compatibility code

- packages/rspack/src/ExecuteModulePlugin.ts
- packages/rspack/src/builtin-plugin/HttpUriPlugin.ts
- packages/rspack/src/node/NodeWatchFileSystem.ts
- Lazy load some modules (`watchpack`, `node:vm`, `node:zlib`) to make startup faster.
- Removed an extra `new Watchpack()` to improve initial startup speed, always create watchpack instance in `the NodeWatchFileSystem.watch` method.
- before:
```bash
hyperfine --warmup 10 --runs 100  'node ./dist/index.js'
Benchmark 1: node ./dist/index.js
Time (mean ± σ):      61.4 ms ±   5.6 ms    [User: 43.2 ms, System: 16.9 ms]
Range (min … max):    58.5 ms … 115.7 ms    100 runs
```
- after:
```bash
hyperfine --warmup 10 --runs 100  'node ./dist/index.js'
Benchmark 1: node ./dist/index.js
Time (mean ± σ):      59.9 ms ±   0.8 ms    [User: 41.3 ms, System: 16.7 ms]
Range (min … max):    57.8 ms …  63.2 ms    100 runs
```
> perf: lazy load watchpack and some Node built-in modules

- crates/rspack_core/src/compiler/make/repair/add.rs
- crates/rspack_core/src/compiler/make/repair/build.rs
- crates/rspack_core/src/compiler/make/repair/factorize.rs
- crates/rspack_core/src/compiler/make/repair/process_dependencies.rs
- crates/rspack_core/src/compiler/module_executor/ctrl.rs
- crates/rspack_core/src/compiler/module_executor/entry.rs
- crates/rspack_core/src/compiler/module_executor/execute.rs
- crates/rspack_core/src/utils/task_loop.rs
This PR will rename TaskType::Sync to TaskType::Main & TaskType::Async to TaskType::background.
``` rust
struct TaskA {}
impl Task<MakeTaskContext> for TaskA {
fn get_task_type(&self) -> TaskType {
// run main_run
TaskType::Main
}
async fn main_run(self: Box<Self>, context: &mut MakeTaskContext) { ... }
}
struct TaskB {}
impl Task<MakeTaskContext> for TaskB {
fn get_task_type(&self) -> TaskType {
// run background
TaskType::Background
}
async fn background_run(self: Box<Self>) { ... }
}
```
> refactor: rename TaskType::Sync to Main & TaskType::Async to background

- crates/rspack_core/src/compiler/module_executor/entry.rs
- crates/rspack_core/src/compiler/module_executor/mod.rs
- crates/rspack_core/src/compiler/module_executor/module_tracker.rs
Print "ImportModuleMeta" information when a circular build dependency error occurs.
``` text
task exist for DependencyId(1), maybe have a circular build dependency
The added task is running, maybe have a circular build dependency. MetaInfo: ImportModuleMeta { origin_module_identifier: ..., request: ..., layer: ...}
```
> refactor: optimize module executor error info

- crates/rspack_core/src/options/filename.rs
- crates/rspack_plugin_runtime/src/runtime_module/get_chunk_filename.rs
- packages/rspack-test-tools/tests/configCases/hooks/get-path-custom-chunk/rspack.config.js
Fix should render name by chunk id when chunk name is empty.
The logic in wepback: https://github.com/webpack/webpack/blob/main/lib/TemplatedPathPlugin.js#L262 
Close: #10475
> fix: should render name by chunk id when chunk name is empty

- crates/rspack_plugin_javascript/src/visitors/dependency/parser/mod.rs
- crates/rspack_plugin_rstest/src/parser_plugin.rs
- packages/rspack-test-tools/tests/configCases/plugins/rstest/index.js
- packages/rspack-test-tools/tests/configCases/plugins/rstest/src/bar.js
- packages/rspack-test-tools/tests/configCases/plugins/rstest/src/baz.js
- packages/rspack-test-tools/tests/configCases/plugins/rstest/src/foo.js
- packages/rspack-test-tools/tests/configCases/plugins/rstest/src/index.js
Handle `import.meta.dirname` and `import.meta.filename` just like `__dirname` and `__filename` in Rstest plugin.
> feat(rstest_plugin): handle import.meta.dirname and import.meta.filename

- crates/rspack_core/src/exports/export_info.rs
- crates/rspack_core/src/exports/export_info_setter.rs
- crates/rspack_core/src/exports/exports_info.rs
- crates/rspack_core/src/exports/mod.rs
- crates/rspack_plugin_javascript/src/plugin/flag_dependency_exports_plugin.rs
- crates/rspack_plugin_javascript/src/plugin/flag_dependency_usage_plugin.rs
- crates/rspack_plugin_javascript/src/plugin/mangle_exports_plugin.rs
- crates/rspack_plugin_library/src/assign_library_plugin.rs
- crates/rspack_plugin_library/src/export_property_library_plugin.rs
Just remove module graph param of export info setters to not send the whole module graph everywhere
> refactor: remove module graph param of export info setters

- Cargo.lock
- Cargo.toml
upgrade rspack resolver to 0.6.0 to align the paths matching with [tsconfig-paths-webpack-plugin](https://www.npmjs.com/package/tsconfig-paths-webpack-plugin)
detail plz refer to https://github.com/web-infra-dev/rspack-resolver/releases/tag/v0.6.0
close https://github.com/web-infra-dev/rspack/issues/10487
> fix: align tsconfig paths matching with tsconfig-paths-webpack-plugin

- crates/rspack_plugin_runtime/src/module_chunk_format.rs
no need to panic for esm hmr, related to https://github.com/web-infra-dev/rspack/issues/10427
> fix: don't panic for esm hmr

- crates/node_binding/binding.d.ts
- crates/node_binding/scripts/banner.d.ts
- crates/node_binding/src/module.rs
- crates/node_binding/src/modules/macros.rs
- crates/node_binding/src/modules/normal_module.rs
- crates/node_binding/src/resource_data.rs
- crates/rspack_core/src/normal_module.rs
Cloning descriptionFileData and converting the descriptionFileData property to a JSObject may become a performance bottleneck.
New ReadonlyResourceData wrap `Arc<rspack_core::ResourceData>` to avoid clone descriptionFileData.
Additionally, descriptionFileData and descriptionFilePath are rarely used, so they are exposed via getter methods and only converted to JSObject when accessed.
> perf: use js api to access module.resourceResolveData

- crates/rspack_core/src/compiler/module_executor/entry.rs
- crates/rspack_core/src/compiler/module_executor/module_tracker.rs
- packages/rspack-test-tools/tests/configCases/loader-import-module/cycle-dependency/loader.js
- packages/rspack-test-tools/tests/configCases/loader-import-module/multi-import-module/index.js
- packages/rspack-test-tools/tests/configCases/loader-import-module/multi-import-module/loader.js
- packages/rspack-test-tools/tests/configCases/loader-import-module/multi-import-module/rspack.config.js
- packages/rspack-test-tools/tests/configCases/loader-import-module/multi-import-module/value.js
LoaderContext.importModule called from the main module graph will not cause a cycle error, so only the inner modules need to be checked.
> fix: module_executor circular check only for internal modules

- website/docs/en/config/target.mdx
- website/docs/zh/config/target.mdx
- website/project-words.txt
This pull request updates documentation for Rspack's `target` configuration, clarifying the default behavior and supported values for `browserslist`.
> docs: clarify `target` default value and browserslist usage

- crates/rspack_plugin_javascript/src/plugin/module_concatenation_plugin.rs
`get_imports()` is used to get module outgoings, which needs to visit moduleGraph many times to get the final outgoings, add cache for it
`try_to_add` is used to add module to concatenated module, which needs a bounch of tests, and one module may be visited many times, add cache for it
> perf: add cache for getImports and module graph visiting

- crates/rspack_core/src/concatenated_module.rs
- crates/rspack_core/src/exports/export_info.rs
- crates/rspack_core/src/exports/export_info_getter.rs
- crates/rspack_core/src/exports/exports_info.rs
- crates/rspack_core/src/exports/mod.rs
- crates/rspack_core/src/module.rs
- crates/rspack_plugin_css/src/parser_and_generator/mod.rs
- crates/rspack_plugin_javascript/src/dependency/commonjs/common_js_export_require_dependency.rs
- crates/rspack_plugin_javascript/src/dependency/esm/esm_compatibility_dependency.rs
- crates/rspack_plugin_javascript/src/dependency/esm/esm_export_imported_specifier_dependency.rs
- crates/rspack_plugin_javascript/src/dependency/esm/esm_import_dependency.rs
- crates/rspack_plugin_javascript/src/dependency/export_info_dependency.rs
- crates/rspack_plugin_javascript/src/plugin/flag_dependency_exports_plugin.rs
- crates/rspack_plugin_javascript/src/plugin/mangle_exports_plugin.rs
- crates/rspack_plugin_javascript/src/plugin/module_concatenation_plugin.rs
- crates/rspack_plugin_json/src/lib.rs
- crates/rspack_plugin_library/src/assign_library_plugin.rs
- crates/rspack_plugin_library/src/modern_module_library_plugin.rs
- crates/rspack_plugin_library/src/module_library_plugin.rs
- crates/rspack_plugin_module_info_header/src/lib.rs
Remove module graph param of getters of export info to make sure the module graph is not sent everywhere
> refactor: remove module graph of export_info getters

- .cargo/config.toml
- .github/workflows/reusable-build-build.yml
see https://kobzol.github.io/rust/rustc/2025/06/02/reduce-cargo-target-dir-size-with-z-no-embed-metadata.html
This reduced 700M in a fresh profiling build.
before:
```
4.3G ┌─┴ target
```
after:
```
3.6G ┌─┴ target
```
> chore: Enable no-embed-metadata

- crates/rspack_core/src/concatenated_module.rs
- crates/rspack_core/src/external_module.rs
- crates/rspack_core/src/utils/concatenation_scope.rs
- packages/rspack-test-tools/tests/configCases/externals/reexport-star/__snapshot__/case2.txt
- packages/rspack-test-tools/tests/configCases/externals/reexport-star/__snapshot__/case3.txt
- packages/rspack-test-tools/tests/configCases/externals/reexport-star/__snapshot__/case5.txt
- packages/rspack-test-tools/tests/configCases/externals/reexport-star/__snapshot__/case6.txt
- packages/rspack-test-tools/tests/configCases/library/modern-module-dynamic-import-runtime/index.js
- packages/rspack-test-tools/tests/configCases/library/modern-module-export-char/rspack.config.js
- packages/rspack-test-tools/tests/configCases/library/modern-module-named-import-externals/index.js
- packages/rspack-test-tools/tests/configCases/library/modern-module-named-import-externals/lib.js
- packages/rspack-test-tools/tests/configCases/library/modern-module-named-import-externals/rspack.config.js
- packages/rspack-test-tools/tests/configCases/library/modern-module-named-import-externals/test.config.js
- packages/rspack-test-tools/tests/configCases/library/modern-module-named-import-externals/test.js
- packages/rspack-test-tools/tests/configCases/plugins/minify-module/index.js
- packages/rspack-test-tools/tests/configCases/plugins/minify-parser/index.js
- tests/webpack-test/configCases/externals/module-import/index.js
Improve the rendering of ExternalModule.
Before:
```js
import * as __WEBPACK_EXTERNALS_foo__ from 'foo'
__WEBPACK_EXTERNALS_foo__.value
```
This PR:
```js
import { value } from 'foo'
value
```
Add a new concatenation hook named `concatenation_info`, this hook is used to let module prepare some data in the correct **topological** order, for example, moduleA, moduleB can use this hook to add their globally used names.
ExternalModule has global names because they will insert some import statements through `InitFragment`.
```
// a.js
import { a } from 'foo';
// b.js
import { a } from 'bar';
```
Tap this hook, and insert the `a` to the globally used names, so we can deconflict the conflict symbol name.
> feat: improve external render

- packages/rspack-cli/package.json
- pnpm-lock.yaml
- tests/e2e/package.json
Update @rspack/dev-server to ~1.1.3 to fix https://github.com/webpack/webpack-dev-server/security/advisories/GHSA-4v9v-hfq4-rm2v and https://github.com/webpack/webpack-dev-server/security/advisories/GHSA-9jgg-88mc-972h.
- resolve https://github.com/web-infra-dev/rspack-dev-server/issues/35
- release note: https://github.com/web-infra-dev/rspack-dev-server/releases/tag/v1.1.3
Note that I used "~1.1.3" instead of "1.1.3" to allow automatic patch version upgrades.
> fix(deps): update @rspack/dev-server to ~1.1.3 [security]

- Cargo.lock
- crates/node_binding/binding.d.ts
- crates/node_binding/scripts/banner.d.ts
- crates/node_binding/src/asset.rs
- crates/node_binding/src/build_info.rs
- crates/node_binding/src/define_symbols.rs
- crates/node_binding/src/lib.rs
- crates/node_binding/src/module.rs
- crates/node_binding/src/modules/macros.rs
- crates/rspack_core/src/module.rs
- crates/rspack_napi/Cargo.toml
- crates/rspack_napi/src/utils.rs
- packages/rspack-test-tools/tests/compilerCases/persist-build-info.js
- packages/rspack-test-tools/tests/fixtures/build-info-loader.js
- packages/rspack/src/BuildInfo.ts
- packages/rspack/src/Module.ts
- packages/rspack/src/loader-runner/index.ts
This PR synchronizes user-defined fields on the JavaScript buildInfo object to Rust, enabling persistent caching of these custom fields on the Rust side.
Additionally, minor refactors are included leveraging napi-rs' new support for symbol-named properties in define_properties. Private properties are now consolidated using Symbols to prevent accidental exposure to users.
> feat: serialized build info custom fields from js

- crates/node_binding/binding.d.ts
- crates/node_binding/src/rsdoctor.rs
- crates/rspack_plugin_rsdoctor/src/data.rs
- crates/rspack_plugin_rsdoctor/src/module_graph.rs
- crates/rspack_plugin_rsdoctor/src/plugin.rs
- packages/rspack-test-tools/tests/configCases/rsdoctor/moduleGraph/rspack.config.js
This pull request introduces a new `bailout_reason` field to the `RsdoctorModule` and `JsRsdoctorModule` structures, along with the necessary logic to populate and transfer this field during module processing. The changes enhance the ability to track optimization bailout reasons in the `Rsdoctor` plugin.
* [`crates/node_binding/src/rsdoctor.rs`](diffhunk://#diff-78b74f07f1c5a3728ce3495127830a73e965afe532de2330b19d670406c8bb48R30): Added an optional `bailout_reason` field to the `JsRsdoctorModule` struct and updated the `From<RsdoctorModule>` implementation to transfer the `bailout_reason` value. [[1]](diffhunk://#diff-78b74f07f1c5a3728ce3495127830a73e965afe532de2330b19d670406c8bb48R30) [[2]](diffhunk://#diff-78b74f07f1c5a3728ce3495127830a73e965afe532de2330b19d670406c8bb48R53)
* …
> feat: rsdoctor native plugin add bailout_reason property

- crates/rspack_core/src/build_chunk_graph/available_modules.rs
`remove_available_modules` has some issues that I cannot repro the failure case, but from my thought I think this fix is more accurate
> fix: correct remove_available_modules

- packages/rspack-test-tools/tests/Validation.test.js
- packages/rspack/src/builtin-plugin/IgnorePlugin.ts
- packages/rspack/src/builtin-plugin/html-plugin/options.ts
- packages/rspack/src/config/utils.ts
- packages/rspack/src/config/zod.ts
The result of `z.function()` in Zod v4 is no longer a schema: https://zod.dev/v4/changelog#zfunction. We need to migrate when upgrading to v4.
Since we are not exporting the Zod-generated types now, I think it would be fine to replace all the `z.function` with `z.custom<(...args: unknown[]) => any>`.
```ts
export const anyFunction = z.custom<(...args: unknown[]) => any>(
data => typeof data === "function",
input => ({ message: `Expected function, received ${getParsedType(input)}` })
);
```
<details><summary>Alternatives</summary>
<p>
I've tried the workaround at https://github.com/colinhacks/zod/issues/4143#issuecomment-2845134912 (which is recommended in the migration guide). It works with type but it will make validation pass for all inputs.
I've also tried to use generics in …
> refactor(zod/v4): replace `z.function` with `z.custom`

- website/docs/en/contribute/development/tracing.md
- website/docs/zh/contribute/development/tracing.md
This PR updates the documentation for enabling tracing to correct the command usage for `rsbuild`.
> docs: fix rsbuild command typo in tracing doc

- crates/rspack_util/src/number_hash.rs
related: https://github.com/web-infra-dev/rspack/issues/10614
This is a temporary fix. @quininer will port the new `fnv` algorithm.
> fix: `number_hash` should use `u64` to avoid addition overflow

- packages/create-rspack/template-common/gitignore
- packages/create-rspack/template-react-js/.npmignore
- packages/create-rspack/template-react-ts/.npmignore
- packages/create-rspack/template-vanilla-js/.npmignore
- packages/create-rspack/template-vanilla-ts/.npmignore
- packages/create-rspack/template-vue-js/.npmignore
- packages/create-rspack/template-vue-ts/.npmignore
- Updates the `.gitignore` file to add patterns to ignore Rspack profile directories (`.rspack-profile-*`).
- Remove the useless `.npmignore` files.
- https://rsbuild.rs/guide/debug/build-profiling#rspack-profiling
> fix(create-rspack): ignore rspack profile and remove npmignore file

- crates/node_binding/src/resolver.rs
- crates/node_binding/src/utils.rs
Support passing `ErrorCode` to `callbackify` callbacks.
Affected **internal** methods:
1. compilation.rebuildModule
2. compilation.addModule
3. compilation.addEntry
4. compilation.addInclude
5. compiler.build
6. compiler.rebuild
> feat: support passing error code to `callbackify` callbacks

- packages/rspack/etc/core.api.md
- packages/rspack/src/exports.ts
Export `StatsErrorCode` to support users filtering stats errors based on its code.
Check the original PR for the supported code: https://github.com/web-infra-dev/rspack/pull/10057
```js
import { rspack, StatsErrorCode } from '@rspack/core';
rspack(<your-config-here>, (err, stats) => {
if (err) {
// handle error
return;
}
// filter minification error
const hasMinificationError = stats.toJson({ errors: true }).errors
?.some(e => e.code === StatsErrorCode.ChunkMinificationError);
if (hasMinificationError) {
// handle minification error
return;
}
});
```
> feat(core): expose `StatsErrorCode`

- Cargo.lock
- crates/rspack_plugin_rstest/Cargo.toml
- crates/rspack_plugin_rstest/src/module_path_name_dependency.rs
- crates/rspack_plugin_rstest/src/parser_plugin.rs
- packages/rspack-test-tools/tests/configCases/rstest/module-path-names/index.js
Should use stringify to get correct path on win32.
> fix(rstest): should stringify resource path

- Cargo.lock
- Cargo.toml
- crates/node_binding/src/resolver.rs
- crates/node_binding/src/utils.rs
- deny.toml
Reverts web-infra-dev/rspack#10633
the build failure is caused by @napi-rs/cli not napi crate
> chore(deps): update napi to 3.0.0-beta.8

- crates/node_binding/src/rsdoctor.rs
- crates/rspack_plugin_rsdoctor/src/data.rs
- crates/rspack_plugin_rsdoctor/src/module_graph.rs
- crates/rspack_plugin_rsdoctor/src/plugin.rs
change bailout_reason to array in rsdoctor native plugin
> fix: change bailout_reason to array in rsdoctor native plugin

- crates/rspack_core/src/artifacts/module_graph_cache_artifact.rs
- crates/rspack_core/src/dependency/mod.rs
- crates/rspack_core/src/exports/exports_info.rs
- crates/rspack_plugin_javascript/src/dependency/esm/esm_export_imported_specifier_dependency.rs
- crates/rspack_plugin_javascript/src/plugin/flag_dependency_exports_plugin.rs
Some performance improvements after https://github.com/web-infra-dev/rspack/pull/10584
1. Split `ExportsMode` to enum variants and box the `DynamicReexport` case since it's larger than other variants. Data size: 112 bytes -> 40 bytes. This change also eliminates unnecessary `Option::expect`.
2. Avoid unnecessary `Vec` to `HashSet` reallocation. The data structures I change from `Vec` to `HashSet` in this pr are actually `Set`s in webpack.
3. Use `map.clear` rather than reallocate a new map in the loop.
> perf: reduce memory allocation in `esm_export_imported_specifier_dependency`

- packages/rspack/src/builtin-loader/swc/types.ts
Add Zod schema for the  `jsc.output.charset` option of `builtin:swc-loader`.
Ref: https://github.com/swc-project/swc/pull/10567
> fix(schema): add `jsc.output.charset` of swc-loader

- Cargo.lock
- Cargo.toml
- crates/rspack_core/src/concatenated_module.rs
- crates/rspack_error/src/error.rs
- crates/rspack_javascript_compiler/src/compiler/parse.rs
- crates/rspack_javascript_compiler/src/compiler/stringify.rs
- crates/rspack_javascript_compiler/src/compiler/transform.rs
- crates/rspack_plugin_javascript/src/utils/eval/eval_source.rs
- crates/rspack_util/src/swc.rs
- Update SWC dependencies to latest version 
SWC fixs dce bug, more detail see: [CHANGELOG-CORE.md](https://github.com/swc-project/swc/blob/main/CHANGELOG-CORE.md#swc_corev2704---2025-06-12)
- https://github.com/web-infra-dev/rspack/issues/10642
> chore: bump swc to 27.0.4

- packages/rspack-cli/src/commands/serve.ts
- packages/rspack-test-tools/etc/test-tools.api.md
- packages/rspack-test-tools/src/plugin/lazy-compilation-test-plugin.ts
- packages/rspack-test-tools/tests/fixtures/esm/d-dynamic.js
- packages/rspack-test-tools/tests/fixtures/esm/d.js
- packages/rspack-test-tools/tests/legacy-test/MultiCompiler.test.js
- packages/rspack/etc/core.api.md
- packages/rspack/src/MultiCompiler.ts
- packages/rspack/src/MultiWatching.ts
- packages/rspack/src/builtin-plugin/lazy-compilation/middleware.ts
- packages/rspack/src/config/devServer.ts
- tests/e2e/fixtures/rspack.ts
- website/docs/en/guide/features/lazy-compilation.mdx
- website/docs/zh/guide/features/lazy-compilation.mdx
Lazy compilation middleware can receive multiCompiler as parameter
When there is a module triggers update, we notify the multiWatching, then multiWatching will invalidate its sub watching.
Every compiler can has its own lazy-compilation config, for example you can make compiler_1 only lazy compiles entries, while compiler_2 only lazy compiles imports
> refactor!: lazy compilation middleware supports multiCompiler and use config from compiler instance

- crates/node_binding/src/raw_options/raw_module/mod.rs
- packages/rspack-test-tools/tests/configCases/asset/custom-encoder/index.js
- packages/rspack-test-tools/tests/configCases/asset/custom-encoder/rspack.config.js
- packages/rspack-test-tools/tests/configCases/asset/custom-encoder/style.css
AssetGeneratorDataUrlFn may be called during the importModule process, at which point the corresponding Module is not present in compilation.moduleGraph.
Therefore, we use a raw pointer to allow JavaScript to access the Module.
Close #10543
> fix: generator data url function panic

- crates/node_binding/binding.js
Rspack requires Node.js >= 16 and we can remove Node 10 compatibility code.
The same as https://github.com/web-infra-dev/rspack/pull/10464
> fix(binding): remove Node 10 compatibility code

- crates/node_binding/binding.d.ts
- crates/node_binding/src/raw_options/raw_experiments/mod.rs
- crates/node_binding/src/raw_options/raw_module/mod.rs
- crates/rspack/src/builder/mod.rs
- crates/rspack/tests/snapshots/defaults__default_options.snap
- crates/rspack_core/src/options/experiments/mod.rs
- crates/rspack_core/src/options/module.rs
- crates/rspack_plugin_javascript/src/dependency/esm/esm_import_dependency.rs
- packages/rspack-test-tools/tests/__snapshots__/Defaults.test.js.snap
- packages/rspack-test-tools/tests/configCases/type-reexports-presence/no-tolerant/basic.ts
- packages/rspack-test-tools/tests/configCases/type-reexports-presence/no-tolerant/index.ts
- packages/rspack-test-tools/tests/configCases/type-reexports-presence/no-tolerant/rspack.config.js
- packages/rspack-test-tools/tests/configCases/type-reexports-presence/no-tolerant/types.ts
- packages/rspack-test-tools/tests/configCases/type-reexports-presence/no-tolerant/warnings.js
- packages/rspack-test-tools/tests/configCases/type-reexports-presence/no-tolerant/with-empty.ts
- packages/rspack-test-tools/tests/configCases/type-reexports-presence/tolerant-no-check/index.ts
- packages/rspack-test-tools/tests/configCases/type-reexports-presence/tolerant-no-check/rspack.config.js
- packages/rspack-test-tools/tests/configCases/type-reexports-presence/tolerant-no-check/warnings.js
- packages/rspack/etc/core.api.md
- packages/rspack/src/config/adapter.ts
- packages/rspack/src/config/defaults.ts
- packages/rspack/src/config/normalization.ts
- packages/rspack/src/config/types.ts
- packages/rspack/src/config/zod.ts
Support tolerant exportsPresence for type re-exports:
```ts
export { T } from "./types.ts";
```
```ts
import { T } from "./types.ts";
export { T }
```
`typeReexportsPresence`:
- `"tolerant-no-check"`: identify this 👆 pattern and ignore the warning/error, this is fast but it may mistakenly ignore warning/error that should have been reported, this is [the same as esbuild](https://github.com/evanw/esbuild/blob/f4159a7b823cd5fe2217da2c30e8873d2f319667/internal/linker/linker.go#L3128)
- `"tolerant"`(not implemented in this PR): identify this 👆 pattern and check whether the export is included in the children modules' `build_info.type_exports`, this won't mistakenly ignore warning/error, but may slower (only on the error/warning path)
- `"no-tolerant"`: the current and default behavior
> feat: type reexports presence tolerant

- crates/rspack_core/src/cache/persistent/occasion/make/module_graph.rs
- crates/rspack_core/src/compiler/compilation.rs
- crates/rspack_core/src/compiler/make/mod.rs
- crates/rspack_core/src/compiler/make/repair/mod.rs
- crates/rspack_core/src/module_graph/mod.rs
There are at most two partials in the module graph. We may inline them to avoid allocating vectors.
> perf: inline module graph partials

- packages/rspack/etc/core.api.md
- packages/rspack/src/config/types.ts
- packages/rspack/src/config/zod.ts
Update the Zod schema of `devtool` to support `-debugids` (https://github.com/web-infra-dev/rspack/pull/8943)
Also update the types.
The pattern is copied from https://github.com/web-infra-dev/rspack/pull/9832
> fix: add `-debugids` to Zod schema

- crates/rspack_core/src/artifacts/module_graph_cache_artifact.rs
- crates/rspack_core/src/chunk_graph/chunk_graph_module.rs
- crates/rspack_core/src/concatenated_module.rs
- crates/rspack_core/src/context_module.rs
- crates/rspack_core/src/dependency/context_element_dependency.rs
- crates/rspack_core/src/dependency/runtime_template.rs
- crates/rspack_core/src/module.rs
- crates/rspack_plugin_javascript/src/dependency/commonjs/common_js_export_require_dependency.rs
- crates/rspack_plugin_javascript/src/dependency/commonjs/common_js_full_require_dependency.rs
- crates/rspack_plugin_javascript/src/dependency/esm/esm_export_imported_specifier_dependency.rs
- crates/rspack_plugin_javascript/src/dependency/esm/esm_import_dependency.rs
- crates/rspack_plugin_javascript/src/dependency/esm/esm_import_specifier_dependency.rs
- crates/rspack_plugin_javascript/src/dependency/esm/import_dependency.rs
- crates/rspack_plugin_javascript/src/dependency/esm/import_eager_dependency.rs
- crates/rspack_plugin_library/src/module_library_plugin.rs
Save `module.get_exports_type` on `module_graph_cache`. This exports type is calculated from `build_meta` + `strict` + `exports_info.get_target`. So it is safe to be cached just like `get_mode`.
> perf: cache get exports type on module graph cache

- packages/rspack-test-tools/tests/configCases/rstest/mock/rspack.config.js
- packages/rspack-test-tools/tests/configCases/rstest/module-path-names/rspack.config.js
- packages/rspack/etc/core.api.md
- packages/rspack/src/exports.ts
Place the Rstest plugin in the `experiments` field, similar to how Rsdoctor does it, to prevent misuse by users.
> fix(rstest): put Rstest plugin in `experiments` field

- crates/node_binding/package.json
- npm/darwin-arm64/package.json
- npm/darwin-x64/package.json
- npm/linux-x64-gnu/package.json
- npm/wasm32-wasi/package.json
- npm/win32-x64-msvc/package.json
- package.json
- packages/create-rspack/package.json
- packages/rspack-cli/package.json
- packages/rspack-test-tools/package.json
- packages/rspack/package.json
* perf(logger): calculate trace only when needed by @chenjiahan in https://github.com/web-infra-dev/rspack/pull/10683
* perf(ci): move benchmark building to self-hosted by @stormslowly in https://github.com/web-infra-dev/rspack/pull/10680
* perf: inline module graph partials by @CPunisher in https://github.com/web-infra-dev/rspack/pull/10727
* perf: improve zod references to reduce bundle size by @chenjiahan in https://github.com/web-infra-dev/rspack/pull/10738
* perf(zod/v4): disable Zod JIT by @colinaaa in https://github.com/web-infra-dev/rspack/pull/10739
* perf: cache get exports type on module graph cache by @LingyuCoder in https://github.com/web-infra-dev/rspack/pull/10741
* perf: parallel get runtime hash of concatenated modules by @LingyuCoder in …
> chore: release v1.4.0-rc.0

- packages/rspack/src/builtin-plugin/IgnorePlugin.ts
- packages/rspack/src/builtin-plugin/RsdoctorPlugin.ts
- packages/rspack/src/builtin-plugin/SubresourceIntegrityPlugin.ts
- packages/rspack/src/builtin-plugin/html-plugin/options.ts
- packages/rspack/src/config/zod.ts
- packages/rspack/src/container/ModuleFederationPlugin.ts
- packages/rspack/src/container/ModuleFederationPluginV1.ts
- packages/rspack/src/lib/DllPlugin.ts
- packages/rspack/src/lib/DllReferencePlugin.ts
- packages/rspack/src/rspack.ts
- packages/rspack/src/util/validate.ts
When schema validation is disabled via `RSPACK_CONFIG_VALIDATE=loose-silent`, we can skip schema creation and parse to improve the performance.
> perf: skip schema creation and parse when validation is disabled

- .cargo/config.toml
This is also a bug fix. It seems that there's something wrong with the fallback of `simd_json`. 
https://stackblitz.com/edit/pr-10771
> feat(wasm): add simd flag

- .github/actions/codspeed/action.yaml
- .github/workflows/reusable-build-bench.yml
- tasks/benchmark/benches/groups/bundle.rs
From my local bench, estimated cpu cycles varies from 0.5% to 1% without fair schedule while it varies less than 0.1% with fair schedule.
See https://valgrind.org/docs/manual/manual-core.html#manual-core.pthreads
> The fairness of the futex based locking produces better reproducibility of thread scheduling for different executions of a multithreaded application.
Noted that lai-callgrind enable it by default: https://iai-callgrind.github.io/iai-callgrind/latest/html/benchmarks/library_benchmarks/important.html
> chore: enable `fair-sched` for codspeed

- packages/rspack/src/Stats.ts
Now in the Rust side, the compilation address will never changed and the Compilation Object in the JS side access the latest Rust compilation instance.
> fix: remove catch for statsFactory.create

- crates/rspack_core/src/artifacts/module_graph_cache_artifact.rs
- crates/rspack_core/src/concatenated_module.rs
- crates/rspack_core/src/dependency/dependency_trait.rs
- crates/rspack_core/src/module.rs
- crates/rspack_core/src/module_graph/mod.rs
- crates/rspack_core/src/normal_module.rs
- crates/rspack_plugin_extract_css/src/css_dependency.rs
- crates/rspack_plugin_javascript/src/dependency/esm/esm_export_expression_dependency.rs
- crates/rspack_plugin_javascript/src/dependency/esm/esm_export_imported_specifier_dependency.rs
- crates/rspack_plugin_javascript/src/dependency/esm/esm_export_specifier_dependency.rs
- crates/rspack_plugin_javascript/src/dependency/esm/esm_import_dependency.rs
- crates/rspack_plugin_javascript/src/dependency/esm/esm_import_specifier_dependency.rs
- crates/rspack_plugin_javascript/src/dependency/pure_expression_dependency.rs
- crates/rspack_plugin_javascript/src/plugin/module_concatenation_plugin.rs
- crates/rspack_plugin_javascript/src/plugin/side_effects_flag_plugin.rs
- Add `cached_get_side_effects_connection_state` to prevent running `module.get_side_effects_connection_state` multiple times in normal modules
- Introduce `NoRuntimeModuleCache` in the Concatenated modules plugin to calculate module information unrelated to the runtime in parallel.
Before:
After:
> perf: improve concatenated modules plugin

- crates/rspack_plugin_javascript/src/dependency/esm/esm_import_specifier_dependency.rs
- packages/rspack-test-tools/tests/configCases/mangle-exports/issue-10565/errors.js
- packages/rspack-test-tools/tests/configCases/mangle-exports/issue-10565/index.js
- packages/rspack-test-tools/tests/configCases/mangle-exports/issue-10565/rspack.config.js
fix #10565
The module should not exists if it is failed to resolve. It is safe to ignore it and should not panic.
> fix: should not panic in esm specifier dependency when resolve failed

- crates/rspack_javascript_compiler/src/compiler/minify.rs
- crates/rspack_javascript_compiler/src/compiler/stringify.rs
- crates/rspack_javascript_compiler/src/compiler/transform.rs
When I'm profiling `swc_ecma_minifier`, I notice that reallocation of codegen buffer takes lots of time(1%-2%). I find oxc's codegen does this optimization: https://github.com/oxc-project/oxc/blob/b8b3530cd1ca7127d20bbd3794294657cf7578d3/crates/oxc_codegen/src/lib.rs#L193C19-L193C26
Since rspack doesn't use swc's codegen api, we can do this directly in rspack.
> perf: pre-allocate codegen buffer

- crates/rspack_core/src/concatenated_module.rs
- crates/rspack_plugin_javascript/src/plugin/mod.rs
There is no need to keep the ASTs and drop them together.
Before:
After:
> perf: parallel drop AST of concated module infos

- crates/rspack_binding_api/src/lib.rs
- crates/rspack_core/src/compiler/compilation.rs
- crates/rspack_core/src/compiler/mod.rs
- crates/rspack_core/src/old_cache/local/code_splitting_cache.rs
- crates/rspack_plugin_split_chunks/src/plugin/mod.rs
- crates/rspack_tracing/src/stdout.rs
- crates/rspack_util/src/lib.rs
- crates/rspack_util/src/tracing_preset.rs
- packages/rspack-cli/src/utils/profile.ts
* move preset logic into rspack_binding so it can be used in rspack js api
* add bench preset for benchmark analysis important phase
```sh
RSPACK_TRACE_LAYER=logger  RSPACK_PROFILE=BENCH node bin/rspack.js -c 'examples/basic/rspack.config.cjs'
```
> feat(tracing): add tracing bench preset for benchmark

- crates/rspack_plugin_sri/src/html.rs
- packages/rspack-test-tools/tests/configCases/sri/link-tags/index.js
- packages/rspack-test-tools/tests/configCases/sri/link-tags/rspack.config.js
- packages/rspack/src/builtin-plugin/SubresourceIntegrityPlugin.ts
Updated `getTagSrc()` to only process `<link>` tags that actually load resources requiring SRI:
- Process: `stylesheet`, `modulepreload`, `preload` (script/style only)  
- Skip: `dns-prefetch`, `preconnect`, `prefetch`, `icon`, etc.
This prevents unnecessary SRI processing on hint/metadata tags and improves plugin accuracy.
See MDN:
- https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/link#integrity
- resolve https://github.com/web-infra-dev/rsbuild/issues/5445
- https://github.com/waysact/webpack-subresource-integrity/issues/179
- https://github.com/waysact/webpack-subresource-integrity/pull/238
> fix: skip non-resource link tags in SRI plugin

- website/docs/en/plugins/rspack/html-rspack-plugin.mdx
- website/docs/zh/plugins/rspack/html-rspack-plugin.mdx
Correct hook usage in html-rspack-plugin documentation, `HtmlWebpackPlugin.getCompilationHooks()` should be `HtmlRspackPlugin.getCompilationHooks()`.
> docs: correct hook usage in HtmlRspackPlugin documentation

- crates/rspack_core/src/compiler/make/cutout/fix_issuers.rs
The persistent cache will generate an incomplete module graph because some modules can not be serialized, and the incomplete module graph will make `fix_issuer.analyze_force_build_module` panic.
> fix: fix_issuer compatibility with incomplete module graph

- crates/rspack_binding_api/src/lib.rs
- packages/rspack-test-tools/tests/compilerCases/tracing.js
stop emit tracing event after calling cleanup 
fix #10858
> fix(tracing): disable emit tracing event when call cleanup

- crates/rspack_core/src/build_chunk_graph/available_modules.rs
- crates/rspack_core/src/build_chunk_graph/new_code_splitter.rs
- packages/rspack-test-tools/tests/configCases/chunk-graph/depend-on-multiple-entry/async.js
- packages/rspack-test-tools/tests/configCases/chunk-graph/depend-on-multiple-entry/main.js
- packages/rspack-test-tools/tests/configCases/chunk-graph/depend-on-multiple-entry/rspack.config.js
- packages/rspack-test-tools/tests/configCases/chunk-graph/depend-on-multiple-entry/test.config.js
- packages/rspack-test-tools/tests/configCases/chunk-graph/depend-on-multiple-entry/vendor1.js
- packages/rspack-test-tools/tests/configCases/chunk-graph/depend-on-multiple-entry/vendor2.js
close #10261
Available modules should be intersection for async chunks' parents, and should be union for entries' parents.
Using dependOn will make the entry loading after all parents loaded, so all modules in parents are available at that time, should union their available modules.
> fix: should union available modules when depend on multiple entry

- crates/rspack_core/src/artifacts/module_graph_cache_artifact.rs
I found that the lock contention is heavy in ExportsTypeCache and it seems dashmap has less lock contention
* before
https://share.firefox.dev/45RMJSS
* after
https://share.firefox.dev/4l3QnO4
> perf: use dashmap to reduce lock contention

- crates/rspack_loader_lightningcss/Cargo.toml
it seems visitor feature is used for js visitor api which we don't use
> perf: remove visitor feature of lightningcss

- crates/rspack_core/src/module.rs
- packages/rspack-test-tools/tests/hotCases/make/rebuild-abnormal-module/__snapshots__/web/0.snap.txt
- packages/rspack-test-tools/tests/hotCases/make/rebuild-abnormal-module/__snapshots__/web/2.snap.txt
- packages/rspack-test-tools/tests/hotCases/make/rebuild-abnormal-module/a.js
- packages/rspack-test-tools/tests/hotCases/make/rebuild-abnormal-module/errors1.js
- packages/rspack-test-tools/tests/hotCases/make/rebuild-abnormal-module/file.js
- packages/rspack-test-tools/tests/hotCases/make/rebuild-abnormal-module/index.js
- packages/rspack-test-tools/tests/hotCases/make/rebuild-abnormal-module/loader.js
Align with webpack, modules should always be rebuilt if they have errors.
- https://github.com/web-infra-dev/rspack/issues/10698
> fix: always rebuild error module

- packages/rspack-test-tools/tests/configCases/target/invalid-browserslist/errors.js
- packages/rspack-test-tools/tests/configCases/target/invalid-browserslist/index.js
- packages/rspack-test-tools/tests/configCases/target/invalid-browserslist/rspack.config.js
- packages/rspack/src/config/target.ts
Add error handling for invalid browserslist configuration, such as:
```js
export default {
target: "browserslist:Chrome>=9999"
};
```
The current error is the same as webpack:
The new error message is more precise:
resolve https://github.com/web-infra-dev/rsbuild/issues/5525
> fix: add error handling for invalid browserslist configuration

- Cargo.lock
- crates/rspack_binding_api/Cargo.toml
Turn on `wasm_atomic` in `parking_lot`.
See: https://github.com/Amanieu/parking_lot/blob/master/core/src/thread_parker/wasm_atomic.rs
This fixes `Parking not supported on this platform` issue in wasm.
This also makes it possible to start multiple tokio workers.
> fix(wasm): use `parking_lot` nightly to avoid panic in tests

- crates/rspack_binding_api/src/lib.rs
I find that we can directly reuse the panic handler in wasm.
Before:
After:
> feat(wasm): align panic handler with native

- crates/node_binding/binding.d.ts
- crates/rspack_binding_api/src/stats.rs
- crates/rspack_core/src/stats/mod.rs
- crates/rspack_core/src/stats/struct.rs
- packages/rspack-test-tools/tests/__snapshots__/StatsOutput.test.js.snap
- packages/rspack-test-tools/tests/diagnosticsCases/factorize/missing-module/raw-warning.err
- packages/rspack-test-tools/tests/diagnosticsCases/factorize/missing-module/stats.err
- packages/rspack/etc/core.api.md
- packages/rspack/src/stats/DefaultStatsFactoryPlugin.ts
- packages/rspack/src/stats/StatsFactory.ts
- packages/rspack/src/stats/statsFactoryUtils.ts
JsStatsWarning and JsStateError have same data, just keep one.
> refactor: remove js stats warning

- Cargo.lock
- crates/rspack_plugin_real_content_hash/Cargo.toml
- crates/rspack_plugin_real_content_hash/src/lib.rs
- packages/rspack-test-tools/tests/hashCases/real-content-hash-consistent/test.filter.js
- packages/rspack-test-tools/tests/hashCases/real-content-hash-fullhash/test.filter.js
- packages/rspack-test-tools/tests/hashCases/real-content-hash-md4/test.filter.js
- packages/rspack-test-tools/tests/hashCases/real-content-hash-sha256/test.filter.js
- packages/rspack-test-tools/tests/hashCases/real-content-hash-xxhash64/test.filter.js
- packages/rspack-test-tools/tests/hashCases/real-content-hash/test.filter.js
Improve parallelism when calculating the real content hashes.
By recording the processed hashes and the hashes on which the current asset depends, if all have been processed, it is added to the current processing batch. Then process the batch together to prevent the number of tasks processed in parallel at one time from being too small, which would make the process approach sequential processing.
Before:
After:
> perf: improve parallelism of real content hash plugin

- crates/rspack_ids/src/deterministic_chunk_ids_plugin.rs
- crates/rspack_ids/src/id_helpers.rs
- crates/rspack_ids/src/named_chunk_ids_plugin.rs
- crates/rspack_ids/src/natural_chunk_ids_plugin.rs
- crates/rspack_ids/src/occurrence_chunk_ids_plugin.rs
The comparator will be called too many times, and then the `get_orded_chunk_modules()` will also be called many times with the same chunk ukey. So just add them too cache.
Before:
After:
> perf: cache ordered modules ids while sorting chunks

- Cargo.lock
- crates/rspack_plugin_size_limits/Cargo.toml
- crates/rspack_plugin_size_limits/src/lib.rs
Parallize getting source sizes in size limit plugin.
Before:
After:
> perf: parallelize getting source sizes in size limit plugin

- Cargo.lock
- Cargo.toml
- crates/rspack_plugin_real_content_hash/Cargo.toml
- crates/rspack_plugin_real_content_hash/src/lib.rs
fix #10798
~~The regex input source can be trust since those are content hash of the asset, which are generated by ourself, since this is only a check so should be fine to "skip" the check~~
AhoCorasick is perfect for the case
Can't found a good way to setup a test
> fix: use AhoCorasick for real content hash

- crates/rspack_core/src/compiler/compilation.rs
parallelize processing chunk hashes when creating compilation hash. Serialize calling `get_runtime_hash` of all runtime modules spent too much time.
Before:
After:
> perf: parallelize processing chunk hashes

- Cargo.lock
- Cargo.toml
Update swc to 30.1.2 to fix the support for `targets: ['ie 11']` option.
- See: https://github.com/swc-project/swc/pull/10778
- Repro: https://github.com/chenjiahan/rspack-repro-1.4.3-downgrade
> fix(deps): update swc to 30.1.2

- .github/workflows/ecosystem-benchmark.yml
- .github/workflows/ecosystem-ci.yml
Skip the ecosystem CI and ecosystem benchmark in forked repos. These can only be run on the main repo.
- Currently, there are some failed notificaiton on the forked repo, such as: https://github.com/mantou132/rspack/commit/7a9febeb254885269f1daee3165c59923f00125f#commitcomment-161535990
> chore(workflow): skip ecosystem CI and benchmark in forked repos

- .prettierignore
- packages/rspack/prebundle.config.mjs
- packages/rspack/tsconfig.api.extractor.json
Update the prebundle config to fix the type error with the pre-bundled watchpack package.
Fix an error when `skipLibCheck` is `false` in user project:
I added the `// @ts-ignore` comment to fix this instead of aliasing the dts path to `../compiled/graceful-fs` as api-extractor can not handle the graceful-fs types as expected:
> See https://github.com/microsoft/rushstack/pull/3528
> fix: type error with the pre-bundled watchpack package

- .github/actions/binary-limit/action.yml
- .github/actions/binary-limit/binary-limit-script.js
- .github/workflows/ci.yml
- .github/workflows/size-limit.yml
1. Add bytes threshold to limit binary size increasing too fast
2. Add Comparing base to the comment of Action Bot
> chore(ci): add size threadhold

- .github/workflows/ci.yml
size-limit will not be run in main push event, wil fail the CI test require check
> chore(ci): CI.yml failed due to size-limit skipped

- crates/node_binding/binding.d.ts
- crates/rspack_binding_api/src/lib.rs
- crates/rspack_javascript_compiler/src/compiler/transform.rs
- crates/rspack_workspace/src/lib.rs
- tasks/codegen/src/main.rs
This PR exports crate versions defined in root `Cargo.toml` in crate `rspack_binding_api` as `RSPACK_BINDING_WORKSPACE_VERSION`.
We're planning to detect binding version (a.k.a crate version) in `@rspack/core` to check the compatibility between JS and Rust packages or crates.
> feat(binding-builder): export workspace version

- Cargo.lock
- Cargo.toml
To avoid accidentally introduce unnecessary features by default, disable default features by default an  manually setting needed features
> chore: disable default features by default

- Cargo.lock
- crates/node_binding/Cargo.toml
- crates/node_binding/binding.d.ts
- crates/rspack_binding_api/src/lib.rs
- packages/rspack/rslib.config.ts
- packages/rspack/src/util/bindingVersionCheck.ts
This PR refactored the original version detecting strategy with a less error-prone strategy.
The new strategy is to let binding export an expected `@rspack/core` version. This version will later be checked within `@rspack/core` to ensure its version consistency.
> refactor: use symbol defined in `binding_api` to ensure the version consistency 

- crates/rspack_plugin_javascript/src/plugin/flag_dependency_exports_plugin.rs
- packages/rspack-test-tools/tests/normalCases/esm/reexport-with-cycle/index.js
- packages/rspack-test-tools/tests/normalCases/esm/reexport-with-cycle/lib.js
- packages/rspack-test-tools/tests/normalCases/esm/reexport-with-cycle/reexport.js
- packages/rspack-test-tools/tests/normalCases/esm/reexport-with-cycle/warnings.js
Collect dependent modules that need to backtrack at the end of the batch, to make sure dependent modules are backtracking its provided exports again, and now it doesn't need to be ordered
> fix: ensure reexport is backtracked for provided exports

- packages/rspack-test-tools/tests/configCases/split-chunks/cache-group-test/rspack.config.js
- packages/rspack/src/ChunkGraph.ts
Fix the getModulus ChunksIterable method was mistakenly deleted.
Relate https://github.com/web-infra-dev/rspack/pull/10502
> fix: getModuleChunksIterable was mistakenly deleted

- .github/actions/binary-limit/binary-limit-script.js
Pull Request from forked Rspack repo's CI fails, due to its github token isn't allowed to comment on the pull request.
Just ignore then comment error, the action should fail only when size limit hit.
> chore(ci): size-limit  ignore comment error

- crates/node_binding/binding.d.ts
- crates/rspack_binding_api/src/plugins/js_loader/context.rs
- crates/rspack_binding_api/src/plugins/js_loader/scheduler.rs
- crates/rspack_binding_api/src/source.rs
- packages/rspack/src/loader-runner/index.ts
Performance Benchmark for N-API Source Map transmission ways
```rs
// Method 1: String
#[napi]
pub fn send_source_map_by_string(json: String) -> Result<()> {
let mut slice = json.as_bytes().to_vec();
let _map: SourceMap = simd_json::serde::from_slice(&mut slice).unwrap();
Ok(())
}
// Method 2: Buffer
#[napi]
pub fn send_source_map_by_buffer(buffer: BufferSlice) -> Result<()> {
let mut slice = buffer.to_vec();
let _map: SourceMap = simd_json::serde::from_slice(&mut slice).unwrap();
Ok(())
}
// Method 3: Direct object
#[napi]
pub fn send_source_map_by_object(_object: SourceMap) -> Result<()> {
Ok(())
}
```
JavaScript benchmark:
```js
console.log("send source map by string", measure(() => {
sendSourceMapByString(JSON.stringify(json));
}));
console.log("send source map by buffer", measure(() …
```
> perf: napi source map serialize and deserialize

- Cargo.lock
- Cargo.toml
Update the swc version so it contains the fix for the typescript typings in ambient context. (see https://github.com/swc-project/swc/pull/10802)
As I understand it - the fix is part of the 31.1.0
Referensed in the swc repo:
- https://github.com/swc-project/swc/pull/10802
- https://github.com/swc-project/swc/issues/10800
> fix: update swc to 31.1.0

- packages/rspack-cli/src/cli.ts
- packages/rspack-cli/src/types.ts
- packages/rspack-cli/src/utils/options.ts
- packages/rspack-cli/tests/build/basic/basic.test.ts
- website/docs/en/config/devtool.mdx
- website/docs/zh/config/devtool.mdx
fix devtool cmd line not work and default value 
- #10721
> fix: the `--devtool` CLI flag not work as expected

- .github/workflows/release-crates.yml
- .github/workflows/reusable-rust-test.yml
- x.mjs
Added cargo-check-strategy "separated" to reusable-rust-test.yml. In crate publishing, separated strategy will be executed to mimick the cargo publish verification step. This PR also adds `--no-verify` flag to `cargo publish` to skip the verification step.
> chore: support separated cargo check for crate publishing

- Cargo.lock
- Cargo.toml
- crates/rspack_plugin_javascript/Cargo.toml
- crates/rspack_plugin_javascript/src/parser_plugin/initialize_evaluating.rs
- packages/rspack-test-tools/tests/configCases/context/issue-10889/index.js
close #10889 
this may bring performance regression since regress is much slower than regex crate
> fix: use regress to parse regex syntax

- crates/rspack_plugin_rstest/src/import_dependency.rs
- crates/rspack_plugin_rstest/src/mock_method_dependency.rs
- crates/rspack_plugin_rstest/src/parser_plugin.rs
- packages/rspack-test-tools/tests/configCases/rstest/mock/importActual.js
- packages/rspack-test-tools/tests/configCases/rstest/mock/rspack.config.js
> fix(rstest): bugs

- crates/rspack_core/src/compiler/module_executor/execute.rs
close #10987
The build hang is caused by redundant computation in ExecutorTask, resulting in approximately 90⁴ (i.e., 90×90×90×90) calculations, as seen in [this file](https://github.com/mjames-c/rspack-bug-10987/blob/main/src/dep-1.css)
> perf: avoid duplicate calculations in executor task

- crates/rspack_core/src/chunk_graph/chunk_graph_module.rs
- crates/rspack_core/src/stats/mod.rs
- packages/rspack-test-tools/tests/compilerCases/stats.js
User maybe get stats while rspack is compiling.
When moduleGraph is built, but chunkGraph is not built finished, the module relative chunk_graph_module maybe undefined.
We should not panic in this case.
fix: #10997
> fix: chunk_graph_module maybe undefined while compiling

- Cargo.lock
- Cargo.toml
- crates/node_binding/Cargo.toml
- crates/node_binding/scripts/build.js
- crates/rspack_binding_api/Cargo.toml
- crates/rspack_binding_api/src/panic.rs
backtrace@0.3.74 has weird bug that cause backtrace::Backtrace::new return empty frames which cause panic not print backtrace in panic_handler,  update to 0.3.75 fix this issue
> fix: fix not printing backtrace when panic

- Cargo.toml
I'm not sure why this is not set before. At that time I just copy the config from rolldown, but they have updated the config so we can sync.
Wasm size: 36.75MB -> 28.88MB
> perf(wasm): set lto=fat and cgu=1

- crates/rspack_loader_swc/src/lib.rs
- website/docs/en/guide/features/builtin-swc-loader.mdx
- website/docs/zh/guide/features/builtin-swc-loader.mdx
Remove the "last builtin:swc-loader" warning, duo to a very common use case: in rspack react-refresh-loader will use after the builtin:swc-loader.
And currently these two features based on collecting TypeScript information can be guaranteed by LSP (if the AST is modified by loader, the corresponding LSP also needs to modified; otherwise, the build results will be inconsistent with the feedback from LSP), and most of the loader won't change TypeScript information (at least the info that these two features needed)
> fix: remove last builtin:swc-loader warning for collecting ts info

- crates/rspack_core/src/cache/persistent/snapshot/strategy.rs
- crates/rspack_fs/src/file_metadata.rs
- crates/rspack_fs/src/lib.rs
- tests/e2e/cases/persistent-cache/rename-file/a.js
- tests/e2e/cases/persistent-cache/rename-file/b.js
- tests/e2e/cases/persistent-cache/rename-file/index.js
- tests/e2e/cases/persistent-cache/rename-file/index.test.ts
- tests/e2e/cases/persistent-cache/rename-file/rspack.config.js
- tests/e2e/fixtures/fileAction.ts
- tests/e2e/fixtures/rspack.ts
The persistent cache snapshot will first calculate the modified file based on the modification time of the file, but after the file is renamed, the modification time will not be updated, so the larger of ctime and mtime should be used as the modification time.
> fix: snapshot not work for renamed files

- crates/rspack_plugin_javascript/src/visitors/dependency/parser/mod.rs
- crates/rspack_plugin_rstest/src/mock_method_dependency.rs
- crates/rspack_plugin_rstest/src/mock_module_id_dependency.rs
- crates/rspack_plugin_rstest/src/module_path_name_dependency.rs
- crates/rspack_plugin_rstest/src/parser_plugin.rs
- packages/rspack-test-tools/tests/configCases/rstest/mock/rspack.config.js
- packages/rspack-test-tools/tests/configCases/rstest/mock/test.js
**The runtime code modification and integration test case is added in Rstest repository https://github.com/web-infra-dev/rstest/pull/389.**
This PR is to resolve two main issues in Rstest mock side:
1. **Issue:** mock hoist order conflict: if the mock for `../src/c` is hoisted to a position that is too top, the mock factory in `../src/c` will access an uninitialized (undefined) `rs` object.
**Solution:** When a mock factory exists, hoist `.mock` to the placeholder by using `InitFragmentStage::StageAsyncESMImports` and set its `position` to the maximum. Additionally, add the line `var _src_c__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__("./mock/src/c.ts");` to refresh the reference to `_src_c__WEBPACK_IMPORTED_MODULE_1__`.
```js
import { expect, it, rs } from '@rstest/core';
import { …
```
> fix: works with async mock factory

- Cargo.lock
- crates/node_binding/build.rs
This allows the release-debug profile to be run without have to specify the sftrace so path using LD_LIBRARY_PATH.
> chore: setup rpath for sftrace

- crates/node_binding/scripts/build.js
This is the missing part of https://github.com/web-infra-dev/rspack/pull/11077
In my mac:
Before: 28.86M
After: 28.39M
> perf(wasm): use build-std for release-wasi

- crates/rspack_plugin_mf/src/container/container_reference_plugin.rs
- packages/rspack-test-tools/tests/configCases/container-1-0/change-data-request/a.js
- packages/rspack-test-tools/tests/configCases/container-1-0/change-data-request/bootstrap.js
- packages/rspack-test-tools/tests/configCases/container-1-0/change-data-request/index.js
- packages/rspack-test-tools/tests/configCases/container-1-0/change-data-request/rspack.config.js
After https://github.com/web-infra-dev/rspack/pull/10999 modify data.request at beforeResolve won't change the dependency, so use data.request to get the request for mf remotes, this is also align with webpack
fix #11088
> fix: change request at before resolve for mf

- crates/rspack_plugin_circular_dependencies/src/lib.rs
- packages/rspack-test-tools/tests/diagnosticsCases/plugins/circular-dependency-plugin/rspack.config.js
- website/docs/en/plugins/rspack/circular-dependency-rspack-plugin.mdx
- website/docs/zh/plugins/rspack/circular-dependency-rspack-plugin.mdx
close: #11085
https://github.com/aackerman/circular-dependency-plugin/blob/21777bf980e78cb55bff0c91e43a03bbfb37f762/index.js#L28-L32
> fix: should match `resource` instead of `identifier`

- xtask/benchmark/benches/groups/bundle.rs
Assert bundle benchmark has no error.
Avoid errors like:
- https://github.com/rspack-contrib/rspack-benchcases/pull/2
- https://github.com/rspack-contrib/rspack-benchcases/pull/3
- https://github.com/rspack-contrib/rspack-benchcases/pull/4
- https://github.com/rspack-contrib/rspack-benchcases/pull/5
> test: assert bench error

- crates/rspack_loader_swc/Cargo.toml
- packages/rspack-test-tools/tests/configCases/builtin-swc-loader/external-helpers-default/index.js
- packages/rspack-test-tools/tests/configCases/builtin-swc-loader/external-helpers-default/lib.ts
- packages/rspack-test-tools/tests/configCases/builtin-swc-loader/external-helpers-default/rspack.config.js
- packages/rspack-test-tools/tests/configCases/builtin-swc-loader/external-helpers-false/index.js
- packages/rspack-test-tools/tests/configCases/builtin-swc-loader/external-helpers-false/lib.ts
- packages/rspack-test-tools/tests/configCases/builtin-swc-loader/external-helpers-false/rspack.config.js
- packages/rspack-test-tools/tests/configCases/builtin-swc-loader/external-helpers-true/index.js
- packages/rspack-test-tools/tests/configCases/builtin-swc-loader/external-helpers-true/lib.ts
- packages/rspack-test-tools/tests/configCases/builtin-swc-loader/external-helpers-true/rspack.config.js
Enable the `ecma_helpers_inline` feature of `swc_core`.
Fix there regression where `externalHelpers: false` of `builtin:swc-loader` take no effect.
Introduced in https://github.com/web-infra-dev/rspack/pull/11089
Related SWC change: https://github.com/swc-project/swc/pull/10808
We may also want to revert https://github.com/rspack-contrib/rspack-benchcases/pull/5 :)
> fix: should allow `externalHelpers: false`

- crates/rspack_plugin_rstest/src/parser_plugin.rs
- packages/rspack-test-tools/tests/configCases/rstest/mock/mockFirstArgIsImport.js
- packages/rspack-test-tools/tests/configCases/rstest/mock/rspack.config.js
- packages/rspack-test-tools/tests/configCases/rstest/mock/src/__mocks__/baz.js
- packages/rspack-test-tools/tests/configCases/rstest/mock/src/barrel.js
- packages/rspack-test-tools/tests/configCases/rstest/mock/src/baz.js
strip the import call in the first arg of `mock` and `doMock` and other mock functions.
```ts
rs.mock(import('./src/a'))
// will be parsed as
rs.mock('./src/a')
```
To allow using then stripping the import call is to gain better IDE type inferring support. No other differences.
There's something I'm not very sure in https://github.com/web-infra-dev/rspack/pull/11099/files#diff-40c0d32c43ce5b65da53481dcdff3dd9226e0e5565549315f49a120afe5c8525R203. I use a manual made UUID (by using expr loc) as the name of tagged import call to avoid confusion with other non-target import calls and support multiple target import calls with same request. But this kind of UUID is not seen elsewhere.
GitHub diff is terrible, here's the diff on VS Code on my machine.
> feat(rstest): strip import_call as first arg in mock function

- crates/node_binding/napi-binding.d.ts
- crates/rspack_binding_api/src/raw_options/raw_external.rs
- packages/rspack/src/builtin-plugin/ExternalsPlugin.ts
Directly implement the getResolve method through NAPI to avoid the overhead of constructing `JsResolver` multiple times.
In this Next.js benchmark case https://github.com/SyMind/shadcn-ui/tree/next-rspack, build performance improved from 17s to 16s.
> perf: get resolve in external plugin

- crates/rspack_core/src/cache/persistent/storage/memory.rs
- crates/rspack_storage/src/lib.rs
- crates/rspack_storage/src/pack/manager/mod.rs
- crates/rspack_storage/src/pack/mod.rs
- crates/rspack_storage/src/pack/strategy/mod.rs
- crates/rspack_storage/src/pack/strategy/split/mod.rs
Add a reset method for storage to clean current scopes and files, it will be used by build dependencies when file change. 
``` rust
trait Storage {
fn reset(&self);
}
// example for use
for item in modified_files {
if build_dependencies.contains(item) {
self.storage.reset();
}
}
```
> feat: rspack_storage support reset

- crates/node_binding/package.json
- crates/node_binding/rspack.wasi-browser.js
- crates/node_binding/rspack.wasi.cjs
- crates/node_binding/wasi-worker-browser.mjs
- crates/rspack_binding_builder_testing/package.json
- npm/wasm32-wasi/package.json
- pnpm-lock.yaml
This pr is necessary for @rspack/browser
1. Sync the hacky code to upstream so we can always generate template code
2. Remove some hacky code replaced with https://github.com/toyobayashi/emnapi/pull/156
3. Buffer injection https://github.com/napi-rs/napi-rs/pull/2777
> chore(wasm): bump @napi-rs/cli and @napi-rs/wasm-runtime

- crates/rspack_core/src/cache/disable.rs
- crates/rspack_core/src/cache/mod.rs
- crates/rspack_core/src/cache/persistent/mod.rs
- crates/rspack_core/src/compiler/compilation.rs
- crates/rspack_core/src/compiler/make/repair/mod.rs
- crates/rspack_core/src/compiler/mod.rs
- crates/rspack_core/src/compiler/module_executor/mod.rs
- crates/rspack_core/src/compiler/rebuild.rs
- xtask/benchmark/benches/groups/build_chunk_graph.rs
1. Delete all cache held elsewhere, leaving only compiler.cache
``` diff
struct Compiler {
-  cache: Arc<dyn Cache>
+  cache: Box<dyn Cache>
}
struct Compilation {
-  cache: Arc<dyn Cache>
}
```
2. Use mutable self in cache trait
``` diff
trait Cache {
-  fn before_make(&self, artifact: &MakeArtifact);
+  fn before_make(&mut self, artifact: &MakeArtifact);
...
}
```
> refactor: remove cache from compilation and use mutable self in cache trait

- crates/rspack_core/src/dependency/mod.rs
- crates/rspack_core/src/exports/export_info_setter.rs
- crates/rspack_core/src/exports/exports_info.rs
- crates/rspack_core/src/exports/exports_info_setter.rs
- crates/rspack_plugin_javascript/src/plugin/flag_dependency_exports_plugin.rs
- crates/rspack_plugin_library/src/export_property_library_plugin.rs
Parallelize process exports specs when:
- the exports info data does not have `redirect_to`
- the exports specs do not have nested `exports` which will only be used in cjs interop and json nested objects
This means only the module's direct exports info data will be modified and the modules can be distinct by module_ids, so they can be modified parallelly. 
Before：
After：
> perf: parallel process exports spec

- crates/rspack_binding_api/src/raw_options/raw_external.rs
- packages/rspack-test-tools/tests/configCases/externals/get-resolve/index.js
- packages/rspack-test-tools/tests/configCases/externals/get-resolve/node_modules/foo/index.cjs
- packages/rspack-test-tools/tests/configCases/externals/get-resolve/node_modules/foo/index.mjs
- packages/rspack-test-tools/tests/configCases/externals/get-resolve/node_modules/foo/package.json
- packages/rspack-test-tools/tests/configCases/externals/get-resolve/rspack.config.js
This PR fixes an issue with external module resolution in Rspack, specifically addressing how ESM modules are resolved during the external resolution process. The fix corrects the dependency category and resolve context being passed to the resolver.
> fix: external resolve esm module

- Cargo.lock
- crates/node_binding/napi-binding.d.ts
- crates/rspack_binding_api/Cargo.toml
- crates/rspack_binding_api/src/build_info.rs
- crates/rspack_binding_api/src/compilation/mod.rs
- crates/rspack_binding_api/src/dependency.rs
- crates/rspack_binding_api/src/module.rs
- crates/rspack_binding_api/src/module_graph.rs
- crates/rspack_binding_api/src/modules/concatenated_module.rs
- crates/rspack_binding_api/src/modules/context_module.rs
- crates/rspack_binding_api/src/modules/external_module.rs
- crates/rspack_binding_api/src/modules/macros.rs
- crates/rspack_binding_api/src/modules/normal_module.rs
- crates/rspack_binding_api/src/normal_module_factory.rs
- crates/rspack_binding_api/src/plugins/interceptor.rs
- crates/rspack_binding_api/src/raw_options/raw_external.rs
- crates/rspack_binding_api/src/resource_data.rs
- crates/rspack_core/src/module_graph/mod.rs
- packages/rspack/etc/core.api.md
- packages/rspack/src/builtin-plugin/ExternalsPlugin.ts
- packages/rspack/src/taps/normalModuleFactory.ts
Enhance NAPI communication performance through the following optimizations:
1. **Reduce memory allocation in JavaScript thread**: Use thread-local variables to store temporary data, avoiding frequent allocation/deallocation cycles
2. **Direct NAPI Array usage**: Replace Vec with direct NAPI Array operations to eliminate unnecessary Vec memory allocations
3. **Non-blocking Arc<T> cleanup**: Use rayon::spawn for dropping Arc<T> to prevent blocking the JavaScript thread
4. **RequestResult caching**: Cache RequestResult objects to avoid repeated JSON.parse operations
In this Next.js benchmark case https://github.com/SyMind/shadcn-ui/tree/next-rspack, build performance improved from 16s to 15s.
> perf: napi communication

- crates/rspack_core/src/build_chunk_graph/code_splitter.rs
- crates/rspack_core/src/build_chunk_graph/incremental.rs
- crates/rspack_core/src/build_chunk_graph/mod.rs
- crates/rspack_ids/src/id_helpers.rs
- packages/rspack-test-tools/tests/__snapshots__/Defaults.test.js.snap
- packages/rspack-test-tools/tests/diagnosticsCases/factorize/entry-runtime-error/raw-error.err
- packages/rspack-test-tools/tests/statsAPICases/verbose-time.js
- packages/rspack/src/config/defaults.ts
- tests/webpack-test/__snapshots__/StatsTestCases.basictest.js.snap
- website/docs/en/config/experiments.mdx
- website/docs/zh/config/experiments.mdx
As we have bugs in current parallelCodeSplitting algorithm, and poor performance in some specific cases, we decide switch to previous behavior, which is stable in all cases
But no worry, we'll make the previous algorithm more performant, and make it parallel as well, you can enable `experiments.parallelCodeSplitting` to check the improvement.
> refactor: disable parallel code splitting by default

- Cargo.lock
- crates/node_binding/napi-binding.d.ts
- crates/rspack_binding_api/src/native_watcher.rs
- crates/rspack_fs/Cargo.toml
- crates/rspack_fs/src/lib.rs
- crates/rspack_fs/src/watcher/analyzer/directories.rs
- crates/rspack_fs/src/watcher/analyzer/root.rs
- crates/rspack_fs/src/watcher/executor.rs
- crates/rspack_fs/src/watcher/ignored.rs
- crates/rspack_fs/src/watcher/mod.rs
- crates/rspack_fs/src/watcher/path_manager.rs
- crates/rspack_fs/src/watcher/scanner.rs
- packages/rspack-test-tools/jest.config.js
- packages/rspack-test-tools/src/case/nativeWatcher.ts
- packages/rspack-test-tools/src/processor/watch.ts
- packages/rspack/package.json
- packages/rspack/prebundle.config.mjs
- packages/rspack/src/NativeWatchFileSystem.ts
- packages/rspack/src/Watching.ts
- pnpm-lock.yaml
This PR significantly enhances Rspack's native watcher by introducing support for both glob pattern-based and function-based ignore patterns, while delivering substantial performance improvements over the previous implementation.
- Reduced NAPI Overhead: Replaced RegExp objects with string patterns to avoid expensive Thread-safe Function (tsfn) calls across the Rust-JavaScript boundary
- Native Glob Matching: Implemented fast, native glob pattern matching using the fast-glob crate instead of JavaScript regex operations
- Cross-Platform Path Handling: Added automatic path normalization for Windows compatibility (\ → /)
> perf: enhance native watcher with customizable ignore patterns

- packages/rspack-test-tools/tests/configCases/type-reexports-presence/tolerant/index.ts
- packages/rspack/src/builtin-loader/swc/collectTypeScriptInfo.ts
- packages/rspack/src/builtin-loader/swc/types.ts
- website/docs/en/guide/features/builtin-swc-loader.mdx
- website/docs/zh/guide/features/builtin-swc-loader.mdx
When `collectTypeScriptInfo.exportedEnum` is `undefined`, it should be resolved to `none` instead of `const-only`.
I meet this issue when I try to enable `typeExports` in Rsbuild: https://github.com/web-infra-dev/rsbuild/pull/5670
This PR also improved the JSDoc of `collectTypeScriptInfo` and its properties.
> fix: should not enable `exportedEnum` by default

- crates/rspack_core/src/build_chunk_graph/code_splitter.rs
Should add incoming blocks for async_entrypoints like normal chunks, so that they can be invalidated during incremental rebuild
> fix: should add incoming blocks for async entrypoint

- Cargo.lock
- Cargo.toml
Update rspack resolver to 0.6.1
Benefits:
yarn projects with PnP feature enabled will get some resolve performance improvement.
> chore: upgrade rspack_resolver to 0.6.1

- crates/rspack_plugin_split_chunks/src/plugin/min_size.rs
> perf: improve ensure min size fit

- crates/rspack_core/src/cache/persistent/occasion/make/mod.rs
- crates/rspack_core/src/cache/persistent/occasion/make/module_graph.rs
- packages/rspack-test-tools/src/helper/hot-update/plugin.ts
- packages/rspack-test-tools/src/processor/cache.ts
- packages/rspack-test-tools/tests/cacheCases/make/keep_module_error/errors.js
- packages/rspack-test-tools/tests/cacheCases/make/keep_module_error/file.js
- packages/rspack-test-tools/tests/cacheCases/make/keep_module_error/index.js
- packages/rspack-test-tools/tests/cacheCases/make/keep_module_error/loader.js
- packages/rspack-test-tools/tests/cacheCases/make/keep_module_error/rspack.config.js
The persistent cache will not restore module.diagnostics because it does not support serialization, we should skip the module contains diagnostics to make sure these module force build when hot start.
> fix: persistent cache lose module build error

- crates/rspack_core/src/build_chunk_graph/code_splitter.rs
- crates/rspack_core/src/build_chunk_graph/incremental.rs
- crates/rspack_core/src/build_chunk_graph/mod.rs
- crates/rspack_core/src/chunk_group.rs
- Use Arc to prevent cloning of `BigUint` multiple times
- Parallelize preparing dependencies and outgoing connections of modules before calling `split()`
Before:
After:
> perf: improve code splitting

- crates/rspack_binding_api/src/resolver.rs
- packages/rspack-test-tools/tests/configCases/resolver/resolve/rspack.config.js
- packages/rspack-test-tools/tests/configCases/resolver/with-fragment/rspack.config.js
- packages/rspack-test-tools/tests/configCases/resolver/with-query/rspack.config.js
- packages/rspack/etc/core.api.md
- packages/rspack/src/Resolver.ts
Return `resource` instead of `path` in `resolver.resolve`.
close: #11191
> fix: should return `resource` instead of `path` in resolve

- crates/rspack_fs/src/native_fs.rs
Makes `read_dir` work when using yarn pnp, preventing a crash when a third party module contains a dynamic require and making it properly the zip crawl directories.
I do not think that the require context ever worked with yarn pnp before anyway, but at least it did not crash prior to https://github.com/web-infra-dev/rspack/pull/10960.
This is not efficient at all because it iterates over the whole index of the zip file every time, the proper fix would be to add a mapping between folders and children directly in the [pnp-rs](https://github.com/yarnpkg/pnp-rs?tab=readme-ov-file#filesystem-utilities) crate (cc @arcanis 👋) but at least it should stop rspack from crashing in the meantime:
```
[rspack-cli] [Error:   × Rspack FS Error: Not a directory (os error 20)
╰─▶ Not a directory (os error …
```
> fix(pnp): add yarn pnp support to read_dir

- crates/rspack_core/src/compiler/make/cutout/fix_issuers.rs
- packages/rspack-test-tools/tests/hotCases/make/issue-10915/__snapshots__/web/0.snap.txt
- packages/rspack-test-tools/tests/hotCases/make/issue-10915/__snapshots__/web/1.snap.txt
- packages/rspack-test-tools/tests/hotCases/make/issue-10915/a.js
- packages/rspack-test-tools/tests/hotCases/make/issue-10915/b.js
- packages/rspack-test-tools/tests/hotCases/make/issue-10915/c.js
- packages/rspack-test-tools/tests/hotCases/make/issue-10915/d.js
- packages/rspack-test-tools/tests/hotCases/make/issue-10915/file.js
- packages/rspack-test-tools/tests/hotCases/make/issue-10915/index.js
- packages/rspack-test-tools/tests/hotCases/make/issue-10915/rspack.config.js
When fix_issuers cleans up cycled modules in step4, it will revoke many modules, and these modules may be issuer of other modules. lets look at a simple example for this problem:
This PR will remove ModuleC to make the module graph work properly.
> fix: fix_issuers not clean cycled modules children

- crates/rspack_binding_builder_macros/src/register_plugin.rs
Use `pub` and full path to `napi` bindgen preludes
> feat(binding-builder): use full path to `napi` bindgen preludes

- crates/rspack_plugin_sri/src/asset.rs
- packages/rspack-test-tools/tests/configCases/sri/async-entrypoints/index.js
- packages/rspack-test-tools/tests/configCases/sri/async-entrypoints/my-worker.worker.js
- packages/rspack-test-tools/tests/configCases/sri/async-entrypoints/rspack.config.js
- packages/rspack-test-tools/tests/configCases/sri/async-entrypoints/test.filter.js
- packages/rspack-test-tools/tests/configCases/sri/async-entrypoints/worker.js
close #11201
close #11082
SRI plugin should also process chunks under async entrypoints, eg: Worker or MF
> fix: sri plugin should process async chunk in async entrypoints

- crates/rspack_core/src/build_chunk_graph/code_splitter.rs
- crates/rspack_core/src/build_chunk_graph/incremental.rs
- crates/rspack_core/src/build_chunk_graph/new_code_splitter.rs
- crates/rspack_core/src/compiler/compilation.rs
- crates/rspack_core/src/old_cache/local/code_splitting_cache.rs
Improve performance of code splitting:
- Parallelize assigning depths of modules and parallelize getting outgoings of modules
- Use `Arc` to prevent cloning `RuntimeSpec` too many times
- Use `Arc` to prevent cloning block modules too many times
- Change `BlockConnectionMap` from `IndexMap` to `HashMap` because it is just used to indexing
- Remove `parents` of `ChunkGroupInfo` because it is not used
Before:
After:
> perf: improve code splitting part 2

- crates/rspack_plugin_javascript/src/dependency/esm/import_dependency.rs
- crates/rspack_plugin_javascript/src/parser_plugin/import_parser_plugin.rs
- crates/rspack_plugin_javascript/src/visitors/dependency/parser/mod.rs
- crates/rspack_plugin_library/src/modern_module/import_dependency.rs
- crates/rspack_plugin_library/src/modern_module_library_plugin.rs
- crates/rspack_plugin_rstest/src/parser_plugin.rs
- crates/rspack_util/src/swc.rs
- packages/rspack-test-tools/tests/configCases/library/modern-module-dynamic-import-runtime/index.js
- packages/rspack-test-tools/tests/configCases/library/modern-module-dynamic-import-runtime/main.js
Should preserve user's raw comments if dynamic imports are externalized
eg.
```js
import(/*comments should be preserved*/ './foo')
```
> feat: preserve all comments if user use externalize dynamic import

- package.json
- pnpm-lock.yaml
upgrade rslint to 0.0.15 which supports optionalDependencies
> chore: upgrade rslint to v0.0.15

- crates/rspack_plugin_library/src/modern_module_library_plugin.rs
- packages/rspack-test-tools/tests/configCases/library/modern-module-reexport-star/bar.js
- packages/rspack-test-tools/tests/configCases/library/modern-module-reexport-star/foo.js
- packages/rspack-test-tools/tests/configCases/library/modern-module-reexport-star/rspack.config.js
- packages/rspack-test-tools/tests/configCases/library/modern-module-reexport-star/test.config.js
fix #8557
use user_request to test if external module comes from a reexport dependency isn't necessary, and user_request is unstable if 2 external dependency has the same external config
> fix: do not use user_request to match external module

- crates/rspack_binding_api/src/raw_options/raw_split_chunks/raw_split_chunk_chunks.rs
- crates/rspack_binding_api/src/raw_options/raw_split_chunks/raw_split_chunk_name.rs
- crates/rspack_core/src/chunk_graph/chunk_graph_module.rs
- crates/rspack_plugin_split_chunks/src/common.rs
- crates/rspack_plugin_split_chunks/src/module_group.rs
- crates/rspack_plugin_split_chunks/src/options/chunk_name.rs
- crates/rspack_plugin_split_chunks/src/plugin/max_size.rs
- crates/rspack_plugin_split_chunks/src/plugin/min_size.rs
- crates/rspack_plugin_split_chunks/src/plugin/mod.rs
- crates/rspack_plugin_split_chunks/src/plugin/module_group.rs
- Add `is_any_module_in_chunk ` to prevent getting same chunk for every module
- No need to get `Chunk` for every calling of `chunk_filter` because the default filter function will not using it
- Add `source_types_modules` on `ModuleGroup` to save the source types to modules mapping. No need to visit all modules when some source types violate size limits that have only a few modules like `css`. This may make time cost of  bundle splitting much more stable.
- Get all modules only once during the whole bundle splitting phase.
- Parallelize preparing groups by chunks and sort the `chunk_sets_by_count` to prevent visiting all lengths
Before:
After:
> perf: improve bundle splitting part 2

- crates/rspack_binding_api/src/lib.rs
- crates/rspack_binding_api/src/plugins/js_loader/resolver.rs
Move builtin loader registration to plugin. This adds support for custom loader in custom bindings.
> refactor: move builtin loader registration to plugin

- crates/rspack_core/src/concatenated_module.rs
- crates/rspack_plugin_javascript/src/plugin/module_concatenation_plugin.rs
- Remove `original_source_hash` because it is never used 
- Parallelize creating concatenated modules
- Parallelize preparing outgoings and incoming connections of concatenated modules
> Can not remove `ModuleConcatenationPlugin::process_concatenated_configuration` and `ModuleGraph::copy_outgoing_module_connections` and `ModuleGraph::move_module_connections` because these methods are also used in `ModernModuleLibraryPlugin`. Should remove them in another pull request.
Before:
After:
> perf: improve process concatenated configurations

- crates/rspack/tests/snapshots/defaults__default_options.snap
- crates/rspack_binding_api/src/options/raw_resolve.rs
- crates/rspack_core/src/cache/persistent/build_dependencies/helper/mod.rs
- crates/rspack_core/src/options/resolve/clever_merge.rs
- crates/rspack_core/src/options/resolve/mod.rs
- crates/rspack_core/src/resolver/mod.rs
- crates/rspack_core/src/resolver/resolver_impl.rs
The persistent cache buildDependencies will recursively collect dependencies, and it should skip the nodejs builtin modules.
> fix: buildDependencies skip resolve nodejs builtin module

- package.json
- rslint.json
ignore 290 errors in `moduleFederationDefaultRuntime.js`.
it's a runtimejs file, ignore this temporally to reduce lint type errors
> chore: ignore moduleFederationDefaultRuntime.js in rslint

- .github/actions/rustup/action.yml
- .github/actions/rustup/cargo/action.yml
After self-hosted runner upgrade, zstd is default supported. So bumping cache version to adapt new cache version
> chore: supporting  linux cache compressing with zstd

- packages/rspack-cli/src/cli.ts
- packages/rspack-cli/src/commands/preview.ts
- packages/rspack-cli/src/utils/loadConfig.ts
- packages/rspack-cli/tests/build/issue-11009/base.config.js
- packages/rspack-cli/tests/build/issue-11009/entry.js
- packages/rspack-cli/tests/build/issue-11009/index.test.ts
- packages/rspack-cli/tests/build/issue-11009/rspack.config.js
- packages/rspack-cli/tests/build/plugin-apply-error/plugin-apply-error.test.ts
- packages/rspack-cli/tests/serve/issue-11009/base.config.js
- packages/rspack-cli/tests/serve/issue-11009/entry.js
- packages/rspack-cli/tests/serve/issue-11009/index.test.ts
- packages/rspack-cli/tests/serve/issue-11009/rspack.config.js
Rspack cli will find and load config, this PR will set the config path to build dependencies if persistent cache is enabled.
> feat: rspack cli add config path to build dependencies

- packages/rspack/src/loader-runner/worker.ts
This PR enhances the loader context in parallel loader by exposing `rspack.experiments.swc` API . This removes a need for importing `rspack` directly in the loader (or loader module) and instead makes it possible to access the `swc` API just like in non parallel loaders
n/a
> feat: expose `experiments.swc` in parallel loader context

- packages/rspack/src/loader-runner/index.ts
This PR fixes the `rootContext` in parallel loaders - currently it is the same as `context` which is different depending on the processed file, but it should be equal to `compiler.context`
related API reference: https://rspack.rs/api/loader-api/context#thisrootcontext
n/a
> fix: pass actual root context to parallel loader context

- Cargo.lock
- Cargo.toml
- crates/rspack_core/src/exports/exports_info_getter.rs
- crates/rspack_core/src/exports/utils.rs
- crates/rspack_loader_swc/src/collect_ts_info.rs
- crates/rspack_plugin_javascript/src/parser_plugin/inline_const.rs
- crates/rspack_plugin_javascript/src/utils/eval/mod.rs
- crates/rspack_plugin_javascript/src/visitors/dependency/parser/mod.rs
- crates/rspack_plugin_rstest/src/parser_plugin.rs
- crates/rspack_util/Cargo.toml
- crates/rspack_util/src/itoa.rs
- crates/rspack_util/src/lib.rs
- crates/rspack_util/src/ryu_js.rs
- packages/rspack-test-tools/tests/configCases/inline-const/basic/constants.js
- packages/rspack-test-tools/tests/configCases/inline-const/basic/index.js
- packages/rspack-test-tools/tests/configCases/inline-const/basic/rspack.config.js
- packages/rspack/src/config/defaults.ts
- website/docs/en/config/experiments.mdx
- website/docs/en/config/module.mdx
- website/docs/en/guide/features/builtin-swc-loader.mdx
- website/docs/zh/config/experiments.mdx
- website/docs/zh/config/module.mdx
- website/docs/zh/guide/features/builtin-swc-loader.mdx
Propagate const:
```js
const a = 1;
const b = 2;
export const value = a + b // before this won't inline, this PR will inline it
```
> feat: propagate const for inline const

- crates/rspack_plugin_rsdoctor/src/chunk_graph.rs
- crates/rspack_plugin_rsdoctor/src/module_graph.rs
- crates/rspack_plugin_rsdoctor/src/plugin.rs
Use compilation id to isolate data to prevent mistaken data removal in multi-compiler scenarios
> fix: rsdoctor multi compiler data scope

- crates/rspack_core/src/compiler/compilation.rs
- crates/rspack_plugin_real_content_hash/src/lib.rs
Batch version of rename_asset with parallel optimization.
Multiple calls to rename_asset would cause performance degradation due to repeated full traversals of chunk_by_ukey. This method uses parallel iteration over chunk_by_ukey to reduce traversal frequency and improve performance.
Fix performance regression in https://github.com/web-infra-dev/rspack/pull/11293
> fix: batch rename_asset with parallel optimization

- crates/rspack_core/src/artifacts/module_graph_cache_artifact.rs
- crates/rspack_core/src/chunk_graph/chunk_graph_module.rs
- crates/rspack_core/src/compiler/compilation.rs
- crates/rspack_core/src/concatenated_module.rs
- crates/rspack_core/src/exports/exports_info_getter.rs
- Add cache of concatenated imports to prevent getting concatenated import multiple times during generating module hash every runtime and the code generation.
- Add cache of module hash because it will be generated every runtime of module runtime spec and also every active connection.
Before:
After:
> perf: cache concatenated imports

- Cargo.lock
- Cargo.toml
- crates/rspack_core/Cargo.toml
- crates/rspack_core/src/concatenated_module.rs
- crates/rspack_core/src/normal_module_factory.rs
- crates/rspack_core/src/options/filename.rs
- crates/rspack_core/src/utils/comment.rs
- crates/rspack_core/src/utils/identifier.rs
- crates/rspack_loader_runner/Cargo.toml
- crates/rspack_loader_runner/src/loader.rs
- crates/rspack_plugin_devtool/Cargo.toml
- crates/rspack_plugin_devtool/src/module_filename_helpers.rs
- crates/rspack_plugin_externals/src/http_externals_plugin.rs
- crates/rspack_plugin_javascript/Cargo.toml
- crates/rspack_plugin_javascript/src/parser_plugin/worker_plugin.rs
- crates/rspack_util/src/identifier.rs
- deny.toml
This eliminates most of the regex block in small benchmark.
Partially solved https://github.com/web-infra-dev/rspack/issues/11319, but there are still many regex not replaced
> perf: Replace hot regex with parser

- crates/rspack_plugin_limit_chunk_count/src/lib.rs
- packages/rspack-test-tools/tests/watchCases/chunks/limit-chunk-count-plugin/0/index.js
- packages/rspack-test-tools/tests/watchCases/chunks/limit-chunk-count-plugin/0/utilA.js
- packages/rspack-test-tools/tests/watchCases/chunks/limit-chunk-count-plugin/0/utilB.js
- packages/rspack-test-tools/tests/watchCases/chunks/limit-chunk-count-plugin/1/utilA.js
- packages/rspack-test-tools/tests/watchCases/chunks/limit-chunk-count-plugin/rspack.config.js
- packages/rspack-test-tools/tests/watchCases/chunks/limit-chunk-count-plugin/test.config.js
This fixes https://github.com/web-infra-dev/rspack/issues/11232.
This bug only happens with `experiments.incremental` set to `advance` (or `advance-slient`), and it happens because of the order in which we add mutations. Here's an example failure scenario with 3 chunks, `a`, `b`, and `c`, with the `LimitChunkCountPlugin` configured to 1 `maxChunks`:
1. `c` gets integrated into `b`, `integrated_chunks.insert(b)` and `removed_chunks.insert(c)`
1. `b` gets integrated into `a`, `integrated_chunks.insert(a)` and `removed_chunks.insert(b)`
https://github.com/web-infra-dev/rspack/blob/c40ac65cf85f423ea3eb7ddbf61ac82a2fe542f8/crates/rspack_plugin_limit_chunk_count/src/lib.rs#L210-L212
So now, we have:
`removed_chunks` contains `c` and `b`
`integrated_chunks` contains `b` and `a`
So we add these …
> fix(incremental): LimitChunkCountPlugin panic with incremental turned on

- packages/rspack-test-tools/tests/configCases/plugins/virtual-modules-base/rspack.config.js
- packages/rspack-test-tools/tests/configCases/plugins/virtual-modules-context/rspack.config.js
- packages/rspack-test-tools/tests/configCases/plugins/virtual-modules-dynamic/rspack.config.js
- packages/rspack-test-tools/tests/configCases/plugins/virtual-modules-no-conflicts/rspack.config.js
- packages/rspack-test-tools/tests/configCases/plugins/virtual-modules-parent-dir/rspack.config.js
- packages/rspack-test-tools/tests/watchCases/virtual-modules/base/rspack.config.js
- packages/rspack/etc/core.api.md
- packages/rspack/src/exports.ts
- website/docs/en/plugins/rspack/virtual-modules-plugin.mdx
- website/docs/zh/plugins/rspack/virtual-modules-plugin.mdx
After calling for testing, then put that to `rspack.VirualMoudlesPlugin` in next minor or major.
> refactor: move builtin virtual module plugin to experiments

- crates/rspack_plugin_css/src/utils.rs
- tests/webpack-test/__snapshots__/ConfigTestCases.basictest.js.snap
- tests/webpack-test/configCases/css/local-ident-name/index.js
- tests/webpack-test/configCases/css/local-ident-name/nested1/nested2/style.module.css
- tests/webpack-test/configCases/css/local-ident-name/test.config.js
- tests/webpack-test/configCases/css/local-ident-name/webpack.config.js
Support `[folder]` template string in `localIdentName` option
close #11184
> feat: support `[folder]` template string in `localIdentName` option

- crates/rspack_binding_api/src/raw_options/raw_split_chunks/raw_split_chunk_chunks.rs
- crates/rspack_core/src/chunk_graph/chunk_graph_chunk.rs
- crates/rspack_plugin_split_chunks/src/common.rs
- crates/rspack_plugin_split_chunks/src/plugin/chunk.rs
- crates/rspack_plugin_split_chunks/src/plugin/max_size.rs
- crates/rspack_plugin_split_chunks/src/plugin/mod.rs
- crates/rspack_plugin_split_chunks/src/plugin/module_group.rs
- If the chunk filter is not a JavaScript binding function, handle it synchronously to reduce the time consumption introduced by "join_all".
- Add `disconnect_chunks_and_modules` and `connect_chunk_and_modules` on chunk graph to reduce the number of times of obtaining chunk_graph_chunk and chunk_graph_module.
- Call `get_module_chunks` in parallel to reduce the number of calls in the subsequent `prepare_module_group_map`.
- Cache the results of `get_combs` based on `used_exports` to prevent repeated calculations for the same module.
- When removing duplicate modules, traverse the chunk group with a smaller number of modules to reduce the hashing cost.
- When the cache group name exists, it is quite likely that the same module will obtain the same cache group key under different chunk …
> perf: improve bundle splitting

- tests/webpack-examples/build-http/example.js
Requesting `https://unpkg.com/p-map-series?module` will return 302 and redirect to the real resource link, but the request will not be cached. This PR removes such requests to ensure that the test is independent of network conditions.
> chore: build http test case avoid send http request

- crates/node_binding/scripts/build.js
- crates/rspack_core/src/utils/identifier.rs
This uses a macro instead of `debug_assert!` to ensure the correctness of the const table. avoids slow running in debug profile.
By the way, it also enables `-Csymbol-mangling-version=v0` for debug profile to get better symbol name.
> chore: Use macro instead of runtime debug_assert

- packages/rspack/src/util/require.ts
There could be security problems with `new Function` so we'd better not use it in rspack since it is a library.
> fix(wasm): remove cjs loader support

- website/docs/en/guide/start/quick-start.mdx
- website/docs/zh/guide/start/quick-start.mdx
Remove outdated Node version requirements from quick start.
Rsbuild v1.5 no longer support Node 16, see: https://github.com/web-infra-dev/rsbuild/releases/tag/v1.5.0-beta.0
> docs: remove outdated Node version requirements from quick start

- crates/rspack_core/src/artifacts/module_graph_cache_artifact.rs
- crates/rspack_core/src/concatenated_module.rs
concatenated module imports are related to runtime, should add it to cache key
> fix: cache concatenated module imports is not safe

- crates/rspack_plugin_extract_css/src/runtime/with_hmr.js
If dynamically add link tag through dom API and there is already a loaded style link, browsers sometimes treats the new link tag as the same link, and won't fetch the new style.
Use query to avoid browser cache the link tag, force to re-fetch new style, this is the same strategy as `updateCss` API
> fix: add query to avoid browser cache the link

- website/docs/en/config/index.mdx
- website/docs/zh/config/index.mdx
Node.js already support enable typescript by default, so update the guide and remove experimental options
- https://nodejs.org/en/blog/release/v22.18.0
- https://github.com/web-infra-dev/rspack/issues/11236#issuecomment-3199006061
> docs: update ts config guide

- packages/rspack-browser/package.json
- packages/rspack/src/browser/service.ts
1. Rsbuild enables `inlineEnum` by default so we have to add all enums to our browser shim.
2. Add `--fail-if-no-match` to build script. This makes ci fails if the build script fails.
> fix(browser): fix @rspack/browser building

- Cargo.lock
- Cargo.toml
- crates/rspack_workspace/src/generated.rs
- packages/rspack-test-tools/tests/diagnosticsCases/module-build-failed/loader-import-syntax-error/stats.err
https://github.com/swc-project/swc/blob/main/CHANGELOG-CORE.md#changelog
> chore: bump `swc_core` from 35.0.0 to 36.0.0

- .github/workflows/release.yml
- scripts/release/publish.mjs
Add fool-proofings to prevent prerelease version published to npm latest tag.
1. Add double check to release workflow to confirm which tag is going to release.
2. Prevent prerelease version publishing to latest npm tag.
> chore(ci): prevent prerelease published to lastest

- crates/rspack_core/src/concatenated_module.rs
- crates/rspack_core/src/external_module.rs
- crates/rspack_core/src/utils/concatenation_scope.rs
- packages/rspack-test-tools/tests/configCases/externals/multi-concat-modules/cjs.js
- packages/rspack-test-tools/tests/configCases/externals/multi-concat-modules/index.js
- packages/rspack-test-tools/tests/configCases/externals/multi-concat-modules/other-entry.js
- packages/rspack-test-tools/tests/configCases/externals/multi-concat-modules/rspack.config.js
- packages/rspack-test-tools/tests/configCases/externals/multi-concat-modules/test.config.js
Concate render in parallel, and each cannot have information of others. Thus when register global import, it must ensure that there is no other external modules in other concate scope.
eg.
```js
// foo.js in concate module 1
import {v} from 'externals1'
// bar.js in concate module 2
import {v} from 'externals2'
```
Result:
```js
import {v} from 'externals1'
import {v} from 'externals2' // <- duplicated imported specifier
__webpack_modules__ = {
"concate1": function() { ... }
"concate2": function() { ... }
}
```
> fix: bailout optimize if there are external modules in other concate scope

- crates/rspack_plugin_rslib/src/parser_plugin.rs
- packages/rspack-test-tools/tests/configCases/rslib/plugin-api/index.js
- packages/rspack-test-tools/tests/configCases/rslib/plugin-api/test.js
Intercept more expressions which are supposed to be handled by APIPlugin, this functionality should be enabled by default when targeting `node` in Rslib.
> feat(rslib): intercept more APIPlugin expressions

- crates/rspack_binding_api/src/lib.rs
- crates/rspack_binding_api/src/trace_event.rs
Generally I think nobody will use tracing in browser.
Before: 28.48MB
After: 27.50MB
> perf(browser): remove tracing

- crates/node_binding/scripts/build.js
We can remove the code for `Debug` trait if we don't need.
Before: 27.50M
After: 27.02M
> perf(browser): set `fmt_debug` to `none`

- packages/rspack/src/NativeWatchFileSystem.ts
This PR fixes an issue where the native file watcher doesn't work correctly with persistent cache. The main changes include:
1. Modified the getNativeWatcher method to return a tuple of [watcher, initialized], indicating whether the watcher is newly initialized or being reused.
2. Enhanced the watch method to handle file dependencies differently based on the watcher's initialization state:
- For newly initialized watchers: Pass all dependencies (files, directories, missing)
- For existing watchers: Only pass incremental changes (added/removed dependencies)
3. Improved code structure by extracting repeated logic into variables for better maintainability.
This fix ensures proper file watching behavior when persistent cache is enabled, preventing potential issues with file detection and …
> fix: native watcher fails to work correctly with persistent cache

- packages/rspack/src/trace/index.ts
This PR updates the node inspector import and removed workaround since Rspack now require Node.js 18.12+.
- reverts https://github.com/web-infra-dev/rspack/pull/10861
> fix: update node inspector import and remove workaround

- biome.jsonc
- crates/rspack_binding_api/src/swc.rs
- packages/rspack-cli/package.json
- packages/rspack-cli/src/utils/isTsFile.ts
- packages/rspack-cli/src/utils/loadConfig.ts
- packages/rspack-cli/tests/build/config/config.test.ts
- packages/rspack-cli/tests/build/config/ts-node-register/main.ts
- packages/rspack-cli/tests/build/config/ts-node-register/rspack.config.ts
- packages/rspack-cli/tests/build/config/ts-node-register/tsconfig.json
- pnpm-lock.yaml
Use  `experiments.swc` to transform TypeScript Rspack config files (CJS) at runtime and no need to install ts-node for most cases.
Provide out of box support of TypeScript config(CJS) support, TypeScript ESM is not covered and may be implemented in future PR.
@rspack/cli will not automatically try to load `ts-node/register` and `esbuild-resgister` to load TypeScript config, It will use builtin swc-register(based on rspack.experiments.transform) to load TypeScript config, It covers most cases of `ts-node` but if you still need more complex features(like declare const enum support), you can still use `ts-node/register` to  load typescript config by running following commands:
```
"build": "NODE_OPTIONS='--require ts-node/register' rspack build"
```
> feat(cli): use SWC to do TS config transformamation

- website/docs/en/guide/features/_meta.json
- website/docs/en/guide/features/esm.mdx
- website/docs/zh/guide/features/_meta.json
- website/docs/zh/guide/features/esm.mdx
add ESM guide, @JSerFeng please take a look at the roadmap section, i'll update English version after your revision.
> docs(ESM): add ESM guide

- crates/rspack_plugin_css/src/plugin/impl_plugin_for_css_plugin.rs
- crates/rspack_plugin_javascript/src/plugin/mod.rs
- crates/rspack_plugin_javascript/src/runtime.rs
- crates/rspack_plugin_module_info_header/src/lib.rs
Plugin compilation hooks maps are dashmap. Should not get the hook to render every module.
Before:
After:
> perf: reuse plugin hooks

- crates/rspack_plugin_javascript/src/parser_and_generator/mod.rs
- crates/rspack_plugin_javascript/src/parser_plugin/common_js_exports_parse_plugin.rs
- crates/rspack_plugin_javascript/src/parser_plugin/inner_graph/plugin.rs
- crates/rspack_plugin_javascript/src/parser_plugin/require_ensure_dependencies_block_parse_plugin.rs
- crates/rspack_plugin_javascript/src/plugin/side_effects_flag_plugin.rs
- crates/rspack_plugin_javascript/src/utils/eval/eval_source.rs
- crates/rspack_plugin_javascript/src/utils/eval/eval_unary_expr.rs
- crates/rspack_plugin_javascript/src/visitors/dependency/parser/mod.rs
- crates/rspack_plugin_javascript/src/visitors/dependency/parser/walk.rs
- crates/rspack_plugin_javascript/src/visitors/dependency/parser/walk_block_pre.rs
use cleaner ast to analyze dependencies
> refactor: clean paren ast for analyzing dependencies

- crates/rspack_fs/src/watcher/executor.rs
- crates/rspack_fs/src/watcher/mod.rs
- crates/rspack_fs/src/watcher/scanner.rs
- crates/rspack_fs/src/watcher/trigger.rs
This PR refactors the file system event handling architecture to support batch processing of FsEvents. 
The batch event will so fast consume if user setting watchOptions.aggregateTimeout as zero.
We should batch processing associated_event by trigger finding. Otherwise it will trigger twice callback.
> fix: update event handling to support batch processing of FsEvents

- crates/node_binding/napi-binding.d.ts
- crates/rspack/src/builder/builder_context.rs
- crates/rspack/src/builder/mod.rs
- crates/rspack_binding_api/src/raw_options/raw_builtins/mod.rs
- crates/rspack_binding_api/src/raw_options/raw_external.rs
- crates/rspack_core/src/external_module.rs
- crates/rspack_plugin_dll/src/dll_reference/dll_reference_agency_plugin.rs
- crates/rspack_plugin_externals/src/electron_target_plugin.rs
- crates/rspack_plugin_externals/src/http_externals_plugin.rs
- crates/rspack_plugin_externals/src/node_target_plugin.rs
- crates/rspack_plugin_externals/src/plugin.rs
- packages/rspack-test-tools/tests/configCases/externals/in-async-chunks/index.js
- packages/rspack-test-tools/tests/configCases/externals/in-async-chunks/module.js
- packages/rspack-test-tools/tests/configCases/externals/in-async-chunks/rspack.config.js
- packages/rspack-test-tools/tests/configCases/library/modern-module-dynamic-import-runtime/index.js
- packages/rspack/etc/core.api.md
- packages/rspack/src/builtin-plugin/ExternalsPlugin.ts
- packages/rspack/src/container/ContainerReferencePlugin.ts
- packages/rspack/src/rspackOptionsApply.ts
Allow normal external modules to be placed in async chunks.
Normally external modules are placed in initial chunks because they may access runtime, which only exist in entry chunks, however some externalType do not require it, they can be placed anywhere.
ModuleFederation implemented based on ExternalModule and it will load some container modules before chunk loading, which need external modules to be in initial chunks, so adding new configuration that forces external modules to be placed in initial chunks.
> feat: allow external modules placed in async chunks

- packages/rspack/src/browser/BrowserHttpImportEsmPlugin.ts
- packages/rspack/src/browser/index.ts
1. Rename `BrowserImportEsmPlugin` -> `BrowserHttpImportEsmPlugin`. Since `@rspack/browser` is still experimental, this breaking change is acceptable.
2. Ignore requests with match resource and inline loaders by filtering requests including `!`. I think generally there isn't request for dependent modules with inline loader like `sass-loader?react`
3. Only focus on http scheme.
> fix(browser): rename and ignore requests with match resource and inline loaders

- crates/rspack_plugin_split_chunks/src/module_group.rs
- crates/rspack_plugin_split_chunks/src/plugin/module_group.rs
- tests/e2e/cases/css/chunk-loading-order/index.test.ts
- tests/webpack-test/__snapshots__/StatsTestCases.basictest.js.snap
should use the global cache group index in `find_best_module_group`
> fix: unstable bundle splitting

- Cargo.lock
- crates/rspack_loader_runner/Cargo.toml
- crates/rspack_loader_runner/src/scheme.rs
Assume most modules don't contain scheme
> perf: add fast path for `get_scheme`

- packages/rspack/src/browser/BrowserHttpImportEsmPlugin.ts
We cannot guarantee that the CDN is stable and secure
> refactor(browser): remove `esm.sh` default domain in `BrowserHttpImportEsmPlugin`

- packages/rspack-browser/README.md
- website/docs/en/api/javascript-api/_meta.json
- website/docs/en/api/javascript-api/browser.mdx
- website/docs/zh/api/javascript-api/_meta.json
- website/docs/zh/api/javascript-api/browser.mdx
This pull request adds documentation and README for the new `@rspack/browser` package, which enables Rspack to run directly in browser environments.
> docs: add guide for the `@rspack/browser` package

- crates/rspack_core/src/build_chunk_graph/code_splitter.rs
- packages/rspack-test-tools/tests/watchCases/chunks/depend-on/0/main.js
- packages/rspack-test-tools/tests/watchCases/chunks/depend-on/rspack.config.js
- packages/rspack-test-tools/tests/watchCases/chunks/dynamic-entry-with-depend-on/0/foo.js
- packages/rspack-test-tools/tests/watchCases/chunks/dynamic-entry-with-depend-on/0/shared.js
- packages/rspack-test-tools/tests/watchCases/chunks/dynamic-entry-with-depend-on/1/main.js
- packages/rspack-test-tools/tests/watchCases/chunks/dynamic-entry-with-depend-on/rspack.config.js
- packages/rspack-test-tools/tests/watchCases/chunks/dynamic-entry-with-depend-on/test.config.js
This PR fixes an issue with building chunk graphs in incremental mode when dealing with dynamic entries that have dependencies. The fix ensures that chunk groups requiring combination are properly processed during the iterative traversal phase.
> fix: build chunk graph incremental logic when dynamic entry with depend on

- crates/rspack_plugin_mf/src/sharing/consume_shared_plugin.rs
The fields are only initialized once, so there's no need to use mutex.
> perf: replace `Mutex<Option<T>>` with `OnceLock<T>`

- crates/rspack_plugin_javascript/src/parser_plugin/amd/amd_define_dependency_parser_plugin.rs
- crates/rspack_plugin_javascript/src/parser_plugin/amd/amd_plugin.rs
- crates/rspack_plugin_javascript/src/parser_plugin/api_plugin.rs
- crates/rspack_plugin_javascript/src/parser_plugin/common_js_exports_parse_plugin.rs
- crates/rspack_plugin_javascript/src/parser_plugin/common_js_imports_parse_plugin.rs
- crates/rspack_plugin_javascript/src/parser_plugin/common_js_plugin.rs
- crates/rspack_plugin_javascript/src/parser_plugin/compatibility_plugin.rs
- crates/rspack_plugin_javascript/src/parser_plugin/define_plugin/parser.rs
- crates/rspack_plugin_javascript/src/parser_plugin/esm_import_dependency_parser_plugin.rs
- crates/rspack_plugin_javascript/src/parser_plugin/exports_info_api_plugin.rs
- crates/rspack_plugin_javascript/src/parser_plugin/hot_module_replacement_plugin.rs
- crates/rspack_plugin_javascript/src/parser_plugin/import_meta_context_dependency_parser_plugin.rs
- crates/rspack_plugin_javascript/src/parser_plugin/inline_const.rs
- crates/rspack_plugin_javascript/src/parser_plugin/inner_graph/plugin.rs
- crates/rspack_plugin_javascript/src/parser_plugin/javascript_meta_info_plugin.rs
- crates/rspack_plugin_javascript/src/parser_plugin/node_stuff_plugin.rs
- crates/rspack_plugin_javascript/src/parser_plugin/require_context_dependency_parser_plugin.rs
- crates/rspack_plugin_javascript/src/parser_plugin/require_ensure_dependencies_block_parse_plugin.rs
- crates/rspack_plugin_javascript/src/parser_plugin/worker_plugin.rs
- crates/rspack_plugin_javascript/src/utils/eval/eval_member_expr.rs
- crates/rspack_plugin_javascript/src/utils/eval/mod.rs
- crates/rspack_plugin_javascript/src/visitors/dependency/parser/call_hooks_name.rs
- crates/rspack_plugin_javascript/src/visitors/dependency/parser/mod.rs
- crates/rspack_plugin_javascript/src/visitors/dependency/parser/walk.rs
- crates/rspack_plugin_javascript/src/visitors/dependency/parser/walk_block_pre.rs
- crates/rspack_plugin_javascript/src/visitors/dependency/parser/walk_module_pre.rs
- crates/rspack_plugin_javascript/src/visitors/dependency/parser/walk_pre.rs
- crates/rspack_plugin_javascript/src/visitors/dependency/util.rs
- crates/rspack_plugin_javascript/src/visitors/scope_info.rs
- crates/rspack_plugin_rstest/src/parser_plugin.rs
- use Atom for variable name instead of String
- use for_name instead of extract name from ast in parser plugin
> refactor: use Atom for parser variable name

- crates/rspack_plugin_swc_js_minimizer/src/lib.rs
- packages/rspack-test-tools/tests/configCases/plugins/rspack-issue-11183/index.js
- packages/rspack-test-tools/tests/configCases/plugins/rspack-issue-11183/rspack.config.js
- packages/rspack-test-tools/tests/configCases/plugins/rspack-issue-11183/test.config.js
I forget to add test case in https://github.com/web-infra-dev/rspack/pull/11231.
And the regression happens in https://github.com/web-infra-dev/rspack/pull/11217
fixes https://github.com/web-infra-dev/rspack/issues/11183
> fix: wrong match object logic in `SwcJsMinimizerRspackPlugin`

- crates/node_binding/napi-binding.d.ts
- crates/rspack_binding_api/src/asset.rs
- packages/rspack-test-tools/tests/configCases/asset/update-asset-sourcemap-null/rspack.config.js
This PR fixes an issue where asset info related source map fields could not be set to null. The fix allows the sourceMap property in the related object to accept null values in addition to string values.
Close https://github.com/web-infra-dev/rspack/issues/11291
> fix: asset info related source map can set null

- packages/rspack/src/schema/loaders.ts
Add `tsEnumIsMutable` option to swc loader schema to fix the schema validation error in https://github.com/rspack-contrib/rstack-examples/tree/main/rspack/inline-const-enum
> fix: add tsEnumIsMutable option to SWC loader schema

- Cargo.lock
- Cargo.toml
- crates/rspack_workspace/src/generated.rs
Update SWC related crates to v37.0.0: https://github.com/swc-project/swc/blob/main/CHANGELOG-CORE.md
- https://github.com/web-infra-dev/rspack/discussions/11502
> chore(deps): update SWC related crates to v37.0.0

- packages/rspack/etc/core.api.md
- packages/rspack/src/config/adapterRuleUse.ts
- website/docs/en/api/loader-api/types.mdx
- website/docs/zh/api/loader-api/types.mdx
- Update the `LoaderDefinitionFunction` return types to include `void` in Promise to fix a type issue in Rsbuild
- Add `LoaderDefinition` type and example to loader documentation
> fix(types): allow async loader to return void

- packages/rspack-test-tools/tests/__snapshots__/Defaults.test.js.snap
- packages/rspack-test-tools/tests/watchCases/build-chunk-graph/available-modules-change/rspack.config.js
- packages/rspack-test-tools/tests/watchCases/build-chunk-graph/basic/rspack.config.js
- packages/rspack-test-tools/tests/watchCases/build-chunk-graph/chunk-add-then-change-ava-module/rspack.config.js
- packages/rspack-test-tools/tests/watchCases/build-chunk-graph/chunk-modify/rspack.config.js
- packages/rspack-test-tools/tests/watchCases/build-chunk-graph/chunk-remove/rspack.config.js
- packages/rspack-test-tools/tests/watchCases/build-chunk-graph/keep-order-index/rspack.config.js
- packages/rspack-test-tools/tests/watchCases/build-chunk-graph/pre-order-index/rspack.config.js
- packages/rspack-test-tools/tests/watchCases/build-chunk-graph/runtime-chunk-recover-error/rspack.config.js
- packages/rspack-test-tools/tests/watchCases/build-chunk-graph/runtime-chunk/rspack.config.js
- packages/rspack-test-tools/tests/watchCases/chunk-ids/update-module/rspack.config.js
- packages/rspack/src/config/defaults.ts
fix #11515
fix #11530
Temporarily disable incremental buildChunkGraph
> refactor: disable incremental buildChunkGraph by default

- crates/rspack_plugin_extract_css/src/runtime/css_load.js
- packages/rspack-test-tools/tests/hotCases/css/recovery/__snapshots__/web/2.snap.txt
- packages/rspack/src/runtime/cssExtractHmr.ts
- tests/e2e/cases/css/update-initial-chunks-after-hmr/index.test.ts
- tests/e2e/cases/css/update-initial-chunks-after-hmr/rspack.config.js
- tests/e2e/cases/css/update-initial-chunks-after-hmr/src/blue.css
- tests/e2e/cases/css/update-initial-chunks-after-hmr/src/index.css
- tests/e2e/cases/css/update-initial-chunks-after-hmr/src/index.html
- tests/e2e/cases/css/update-initial-chunks-after-hmr/src/index.js
fix #11532
This pr contains 2 errors in runtime
1. CSS hmr should get `href` through attributes instead of field, `link.href` will get the concrete url, which will break the assumption for `findStylesheet`. `link.href` returns 'http://localhost:3000/index.css' while link.getAttribute('href') returns 'index.css'.
2. `findStylesheet` should find url exclude the query part
> fix: css runtime

- packages/rspack-test-tools/tests/hotCases/css/recovery/__snapshots__/web/2.snap.txt
- packages/rspack/src/runtime/cssExtractHmr.ts
css hmr runtime using `link.href` to check if link url is correct http link, but should use `href` attribute to create the new link tag
> fix: should check http url using `link.href` for extract-css runtime

- packages/rspack/src/config/target.ts
This pr fix browserslist config loading when browserslist-rs correctly resolved query.
If browserslist-rs correctly resolve query (for example from environment variable) don't need to throw the error
closes #11527
> fix: don't throw error when browserslist config is resolved from env var

- Cargo.lock
- Cargo.toml
- crates/rspack_plugin_javascript/Cargo.toml
- crates/rspack_plugin_javascript/src/parser_and_generator/mod.rs
- crates/rspack_plugin_javascript/src/visitors/semicolon.rs
- packages/rspack-test-tools/tests/normalCases/parsing/asi/index.js
The `swc_ecma_parser::Lexer` will output different tokens when using it in `parse` and `.collect_vec()`
For example: 
```js
import {assert} from './a'
const labelType = `${node}Label`
const node = []
assert(labelType)
```
In `parse` this will have correct tokens, but using with `.collect_vec()` it will have a lexing error: `Error { error: (60..97, UnterminatedTpl) }`
And the lexing error causes rspack collected the wrong semicolons (which is used for adding semicolons before replaced dependency to generate the correct code)
So this PR switch to the stable `swc_ecma_lexer::Lexer`.
fix https://github.com/web-infra-dev/rspack/issues/11551
A better solution is using SWC's API https://github.com/swc-project/swc/issues/11053
> fix: use stable swc lexer for correct asi

- crates/rspack_javascript_compiler/src/compiler/minify.rs
- crates/rspack_javascript_compiler/src/compiler/stringify.rs
- crates/rspack_javascript_compiler/src/compiler/transform.rs
- crates/rspack_util/src/swc.rs
- packages/rspack-test-tools/tests/builtinCases/swc-loader/charset/__snapshots__/output.snap.txt
- packages/rspack-test-tools/tests/builtinCases/swc-loader/charset/a.js
- packages/rspack-test-tools/tests/builtinCases/swc-loader/charset/b.js
- packages/rspack-test-tools/tests/builtinCases/swc-loader/charset/rspack.config.js
Currently `jsc.output.charset` doesn't take effect because we always pass `ascii_only: true` to swc-loader printer.
Related https://github.com/web-infra-dev/rslib/issues/1204
> fix: respect to `jsc.output.charset` in swc loader

- crates/rspack_plugin_javascript/src/parser_plugin/common_js_imports_parse_plugin.rs
- crates/rspack_plugin_javascript/src/parser_plugin/drive.rs
- crates/rspack_plugin_javascript/src/parser_plugin/trait.rs
- crates/rspack_plugin_javascript/src/visitors/dependency/parser/mod.rs
- crates/rspack_plugin_javascript/src/visitors/dependency/parser/walk.rs
- crates/rspack_plugin_javascript/src/visitors/dependency/util.rs
- crates/rspack_plugin_rslib/src/parser_plugin.rs
- use for_name instead of extracting info from AST
> refactor: use for_name for cjs import parser plugin

- crates/rspack_core/src/exports/exports_info_getter.rs
- use `UkeyMap` to store exports infos
- just get named export info directly
> perf: improve exports info

- website/docs/en/api/loader-api/_meta.json
- website/docs/en/api/loader-api/context.mdx
- website/docs/en/api/loader-api/index.mdx
- website/docs/en/api/loader-api/writing-loaders.mdx
- website/docs/en/config/module.mdx
- website/docs/en/guide/features/loader.mdx
- website/docs/zh/api/loader-api/_meta.json
- website/docs/zh/api/loader-api/context.mdx
- website/docs/zh/api/loader-api/index.mdx
- website/docs/zh/api/loader-api/writing-loaders.mdx
- website/docs/zh/config/module.mdx
- website/docs/zh/guide/features/loader.mdx
- website/project-words.txt
- Added new sections for handling source maps in Rspack loaders.
- Renamed the `Loader types` page to `Writing loaders`.
- Updated all internal links and references from "Loader types" to "Writing loaders" across the documentation
> docs(loader-api): add new sections for handling source maps

- crates/rspack_core/src/chunk_graph/chunk_graph_chunk.rs
- crates/rspack_ids/src/deterministic_chunk_ids_plugin.rs
- crates/rspack_ids/src/id_helpers.rs
- crates/rspack_ids/src/named_chunk_ids_plugin.rs
- crates/rspack_ids/src/natural_chunk_ids_plugin.rs
- crates/rspack_ids/src/occurrence_chunk_ids_plugin.rs
We can make sure that chunk module exists when it is not a runtime module, then we can prevent finding all modules on module graph by `loop_partial` which needs to indexing multiple times.
Before:
After:
> perf: improve deterministic chunk ids

- crates/rspack_plugin_javascript/src/dependency/esm/esm_evaluated_import_specifier_dependency.rs
- crates/rspack_plugin_javascript/src/dependency/esm/esm_import_specifier_dependency.rs
- crates/rspack_plugin_javascript/src/parser_plugin/esm_import_dependency_parser_plugin.rs
- crates/rspack_plugin_javascript/src/parser_plugin/trait.rs
- crates/rspack_plugin_json/src/lib.rs
- packages/rspack-test-tools/tests/configCases/parsing/esm-in-operator/index.js
- packages/rspack-test-tools/tests/configCases/parsing/esm-in-operator/m.js
```js
import * as m from "./m"
("a" in m)
```
Before `./m` won't tree shaking, because `in m` is an namespace usage. In this PR we will identify `"a" in m` as only uses `.a` and tree shaking rest exports
> feat: static analyze in operator for esm import specifier

- crates/rspack_plugin_rslib/src/parser_plugin.rs
- tests/rspack-test/configCases/rslib/plugin-api/index.js
- tests/rspack-test/configCases/rslib/plugin-api/test.js
This reverts commit 15ba68ed9c9fd0b2da495702387a938c341b4fec.
`"modulle"` identifier hook is commonly used in bundling CJS module, can't be removed directly. this PR will break bundling in Rslib.
> fix: revert "fix(rslib): treat `module` identifier as normal (#11588)"

- .github/workflows/ecosystem-ci.yml
add rstest to ecosystem-ci.
https://github.com/rspack-contrib/rspack-ecosystem-ci/pull/84
> chore(ci): add rstest to ecosystem-ci

- website/docs/en/api/plugin-api/compiler-hooks.mdx
- website/docs/zh/api/plugin-api/compiler-hooks.mdx
* Removed the `hooks.emitRecords` from the compiler hooks diagram, as Rspack does not provide this hook.
- [ x Documentation updated (or not required).
> docs: remove incorrect `emitRecords` compiler hook

- crates/rspack_core/src/context_module_factory.rs
- crates/rspack_core/src/dependency/context_element_dependency.rs
- crates/rspack_plugin_module_replacement/src/context_replacement.rs
- tests/rspack-test/configCases/context-module/two_files_share_a_request/index.js
- tests/rspack-test/configCases/context-module/two_files_share_a_request/rspack.config.js
- tests/rspack-test/configCases/context-module/two_files_share_a_request/sub/index.js
- tests/rspack-test/configCases/context-module/two_files_share_a_request/sub/index.ts
close https://github.com/web-infra-dev/rspack/issues/11410 
[the test case](https://github.com/web-infra-dev/rspack/pull/11674/files#diff-9aeb9960f4b86bce0cb8675d4dfadaa73ec4a38cab38bc49cbeab45348d4bfbe)
```
src/
├── index.ts
└── sub
├── index.js
└── index.ts
```
```ts
// index.ts
const str = "index.ts";
async function bug(str) {
await import(`./sub/${str}`);
}
bug(str);
// sub/index.js
console.log("js")
// sub/index.js
console.log("ts")
```
`ts` is expected to be printed, but actually `js`
A context modules's dependencies are grouped by resolved resource's path named as `sorted_dependecies` which is a hashmap. In reproduction's example, it will be simplified as below.
```
src/sub/index.js: [
./         -> src/sub/index.js (DepId:4)
./index    -> src/sub/index.js (DepId:3)
./index.js -> …
```
> fix:  align context module element dependence resource identifer with webpack

- crates/rspack_plugin_javascript/src/visitors/dependency/parser/mod.rs
- crates/rspack_plugin_rslib/src/parser_plugin.rs
- tests/rspack-test/configCases/rslib/plugin-api/cjsFile.cjs
- tests/rspack-test/configCases/rslib/plugin-api/index.js
- tests/rspack-test/configCases/rslib/plugin-api/rspack.config.js
- tests/rspack-test/configCases/rslib/plugin-api/test.js
This is a revised version of 15ba68e.
This PR mainly do:
when `parser.is_esm` is `true` (which means the CJS exports is useless due to the presence of ESM syntax) add parser hooks just like what `crates/rspack_plugin_javascript/src/parser_plugin/common_js_exports_parse_plugin.rs` do to `module` variable. and simply return `true` to bailout the afterwards hooks.
revised version of https://github.com/web-infra-dev/rspack/pull/11588. only ignore`"module"` variable when ESM `import / export` are present.
> fix(rslib): only treat "module" as normal variable when module have ESM syntax

- Cargo.lock
- Cargo.toml
- crates/rspack_cacheable/src/with/as_preset/lightningcss.rs
- crates/rspack_cacheable_test/tests/with/as_preset/lightningcss.rs
Remove the `serde` feature of `lightningcss`.
Bump `swc_core` needs to bump `serde`, which would cause compile error.
- https://github.com/parcel-bundler/lightningcss/issues/1056
- https://github.com/swc-project/swc/issues/11092
- https://github.com/web-infra-dev/rspack/pull/11702#issuecomment-3306064858
> fix: remove `serde` feature of `lightningcss`

- crates/rspack_cacheable/src/with/custom.rs
- crates/rspack_cacheable/src/with/mod.rs
- crates/rspack_cacheable_test/tests/with/custom.rs
- crates/rspack_cacheable_test/tests/with/mod.rs
This PR will add `Custom` and `CustomConverter` to rspack_cacheable, which we can use to customize serialization and deserialization.
``` rust
#[cacheable(with=Custom)]
struct Data(PathBuf);
impl CustomConverter for Data {
type Target = String;
fn serialize(&self, _ctx: &dyn Any) -> Result<Self::Target, SerializeError> {
Ok(self.0.to_string_lossy().to_string())
}
fn deserialize(data: Self::Target, _ctx: &dyn Any) -> Result<Self, DeserializeError> {
Ok(Data(PathBuf::from(&data)))
}
}
```
> feat: rspack_cacheable add custom with wrapper

- crates/node_binding/napi-binding.d.ts
- crates/rspack_binding_api/src/stats.rs
- crates/rspack_core/src/compilation/make/graph_updater/repair/add.rs
- crates/rspack_core/src/compilation/make/graph_updater/repair/build.rs
- crates/rspack_core/src/compilation/make/graph_updater/repair/factorize.rs
- crates/rspack_core/src/compilation/make/graph_updater/repair/mod.rs
- crates/rspack_core/src/compilation/make/graph_updater/repair/process_dependencies.rs
- crates/rspack_core/src/compilation/make/module_executor/entry.rs
- crates/rspack_core/src/module_graph/module.rs
- crates/rspack_core/src/module_profile.rs
- crates/rspack_core/src/stats/mod.rs
- crates/rspack_core/src/stats/struct.rs
- packages/rspack/src/stats/DefaultStatsFactoryPlugin.ts
- packages/rspack/src/stats/statsFactoryUtils.ts
1. Update ModuleProfiler to be implemented as an enum and store time consumption in u64 to save more space.
``` diff
- pub struct TimeRange {
-   start: OnceCell<Instant>,
-   end: OnceCell<Instant>,
- }
+ enum ProfileState {
+   Pending,
+   Started(Instant),
+   Finish(u64),
+ }
```
2. Replace Option<Box<ModuleProfiler>> to Option<ModuleProfiler>
> refactor: rspack module profiler

- crates/rspack_core/src/module_graph/module.rs
- crates/rspack_core/src/module_profile.rs
- crates/rspack_plugin_wasm/src/parser_and_generator.rs
1. Remove `#[cacheable(with=Skip)]` for ModuleProfiler, and make ModuleProfiler cacheable.
2. Remove `#[cacheable(with=Unsupported)]` in AsyncWasmParserAndGenerator
> feat: persistent cache save ModuleProfiler

- packages/rspack-test-tools/src/test/tester.ts
Should close compiler when afterAll is not defined
> test: close compiler

- Cargo.lock
- Cargo.toml
- deny.toml
1. perf: RawBufferSource value_as_string
This PR optimizes the RawBufferSource struct to avoid unnecessary string allocations by using self-referential structs and Cow<'this, str> instead of String. The change leverages the ouroboros crate to create self-referential structures that can borrow from their own data.
https://github.com/web-infra-dev/rspack-sources/pull/167
2. perf: should flatten nested concat sources
This PR implements flattening for nested ConcatSource instances to improve performance by avoiding deeply nested source structures. The optimization flattens ConcatSource children during construction and addition operations.
https://github.com/web-infra-dev/rspack-sources/pull/166
3. perf: using writer to calculate concat source buffer
This PR optimizes buffer calculation by …
> perf: rspack sources buffer function

- website/docs/en/config/module.mdx
- website/docs/zh/config/module.mdx
add document for https://github.com/web-infra-dev/rspack/pull/11664
> docs: document parser jsx option

- crates/rspack_core/src/cache/persistent/occasion/make/mod.rs
- crates/rspack_core/src/compilation/make/artifact.rs
- crates/rspack_core/src/compilation/make/graph_updater/repair/factorize.rs
- crates/rspack_core/src/compilation/make/module_executor/execute.rs
- crates/rspack_core/src/dependency/factorize_info.rs
- crates/rspack_core/src/normal_module_factory.rs
- tests/rspack-test/configCases/context/missing-dependency/rspack.config.js
- tests/rspack-test/watchCases/resolve/alias/0/a.js
- tests/rspack-test/watchCases/resolve/alias/0/index.js
- tests/rspack-test/watchCases/resolve/alias/1/b.js
- tests/rspack-test/watchCases/resolve/alias/rspack.config.js
This PR enhances alias resolution in watch mode by ensuring that successful factorizations track missing dependencies. This allows the bundler to properly re-resolve and update module paths when higher-priority alias files or new resolution-relevant files (such as `package.json`) are created or modified.
In watch mode, when a user adds or modifies a file that could affect module resolution (e.g., adding a higher-priority alias file or changing `package.json` exports), the resolver should re-resolve affected dependencies to ensure correctness. Previously, the bundler did not track these resolution dependencies, leading to outdated references.
Given the alias configuration:
```js
alias: ["a.js", "b.js"]
```
Where `a.js` has higher priority than `b.js`, if a user adds `a.js` after the …
> fix: should update alias resolution when a higher-priority file is created in watch mode

- crates/node_binding/napi-binding.d.ts
- crates/rspack_binding_api/src/raw_options/raw_builtins/mod.rs
- crates/rspack_core/src/artifacts/code_generation_results.rs
- crates/rspack_core/src/concatenated_module.rs
- crates/rspack_core/src/dependency/dependency_id.rs
- crates/rspack_core/src/options/module.rs
- crates/rspack_plugin_javascript/src/dependency/url/mod.rs
- crates/rspack_plugin_javascript/src/parser_plugin/url_plugin.rs
- crates/rspack_plugin_javascript/src/plugin/mod.rs
- crates/rspack_plugin_javascript/src/plugin/url_plugin.rs
- crates/rspack_plugin_javascript/src/visitors/dependency/parser/mod.rs
- packages/rspack-test-tools/src/runner/node/index.ts
- packages/rspack/etc/core.api.md
- packages/rspack/src/builtin-plugin/URLPlugin.ts
- packages/rspack/src/builtin-plugin/index.ts
- packages/rspack/src/config/types.ts
- packages/rspack/src/rspackOptionsApply.ts
- packages/rspack/src/schema/config.ts
- tests/rspack-test/configCases/asset-url/new-url-relative/index.js
- tests/rspack-test/configCases/asset-url/new-url-relative/rspack.config.js
- tests/rspack-test/configCases/asset-url/new-url-relative/test.config.js
- tests/rspack-test/configCases/asset-url/new-url-relative/test.js
- website/docs/en/config/module.mdx
- website/docs/zh/config/module.mdx
Support new way to render url dependency, transform `new URL('./', import.meta.url)` without adding runtime
Config name is 'new-url-relative', it's useful for library cases
```js
new URL('./foo', import.meta.url)
// transforms without any runtime code
new URL('./foo-[hash].js', import.meta.url)
```
> feat: transform url in new URL without runtime

- crates/rspack_plugin_javascript/src/parser_plugin/import_parser_plugin.rs
- tests/rspack-test/normalCases/chunks/statical-dynamic-import/index.js
Forgot the `defineVariable` causes analyze to the same name variable that declared in upper scope
> fix: should analyze correct variable for dynamic import

- website/theme/index.css
Fix unexpected borders that appear when focusing on code blocks in the Rspack website. When users click on code blocks and press keys, browsers apply default focus outlines/borders. This fix removes these default focus styles specifically for code blocks using CSS pseudo-classes.
- Added CSS rules in `website/theme/index.css` to remove `outline` and `border` properties for `pre:focus`, `code:focus`, `pre:focus-visible`, and `code:focus-visible` selectors
- This prevents browser default focus styles from appearing on code blocks while preserving focus behavior for other elements
Fixes issue #11775
> docs(style): remove unexpected borders on code block focus

- crates/rspack_plugin_esm_library/Cargo.toml
This PR adds a missing description field to the Cargo.toml file for the rspack_plugin_esm_library crate.
```
error: failed to publish to registry at https://crates.io/
Caused by:
the remote server responded with an error (status 400 Bad Request): missing or empty metadata fields: description. Please see https://doc.rust-lang.org/cargo/reference/manifest.html for more information on configuring these fields
info published rspack_plugin_esm_library v0.5.8
```
> chore: rspack_plugin_esm_library should have description

- packages/rspack/etc/core.api.md
- packages/rspack/src/config/adapterRuleUse.ts
- packages/rspack/src/stats/statsFactoryUtils.ts
- website/docs/en/api/javascript-api/stats-json.mdx
- website/docs/en/api/loader-api/context.mdx
- website/docs/zh/api/javascript-api/stats-json.mdx
- website/docs/zh/api/loader-api/context.mdx
Add detailed descriptions for the `file`, `moduleIdentifier`, and `moduleName` fields in stats error objects.
> docs: improve documentation for stats properties

- biome.jsonc
- packages/rspack/src/loader-runner/index.ts
- packages/rspack/src/loader-runner/worker.ts
- packages/rspack/src/logging/createConsoleLogger.ts
- Adds missing break statements in switch cases.
- Enables Biomes's `noFallthroughSwitchClause` rule to disallow fallthrough of `switch` clauses.
Fix https://github.com/web-infra-dev/rspack/issues/11771
> fix(loader-runner): add missing break statements in switch cases

- website/docs/en/config/resolve.mdx
- website/docs/zh/config/resolve.mdx
Adds documentation about how `resolve.alias` affects package resolution, clarify the difference between default package resolution and aliased paths, especially in monorepo scenarios, and recommend best practices for maintaining standard package resolution behavior.
https://github.com/web-infra-dev/rsbuild/issues/5311
> docs: explain how `resolve.alias` affects package resolution
